Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/tcmi/syscall/tcmi_syscallhooks_groupident.c File Reference
tcmi_syscallhooks_groupident.c File Reference
syscalls hooks for proces identification manipulation.
#include <asm/uaccess.h>
#include <linux/capability.h>
#include <linux/limits.h>
#include <clondike/tcmi/tcmi_hooks.h>
#include <dbg.h>
#include <tcmi/syscall/tcmi_guest_rpc.h>
#include "tcmi_syscallhooks_groupident.h"
Macros
#define TCMI_SYSCALLHOOKS_GROUPIDENT_PRIVATE
Functions
int tcmi_syscall_hooks_groupident_init (void)
<<public>> Registers all user identification syscalls hooks with the kernel.
void tcmi_syscall_hooks_groupident_exit (void)
<<public>> Unregisters all user identifikation syscalls hooks.
static long tcmi_syscall_hooks_sys_getgid (void)
<<private>> Getgid system call hook
static long tcmi_syscall_hooks_sys_getegid (void)
<<private>> Getegid system call hook
static long tcmi_syscall_hooks_sys_setgid (gid_t gid)
<<private>> Setgid system call hook
static long tcmi_syscall_hooks_sys_setregid (gid_t rgid, gid_t egid)
<<private>> Setregid system call hook
static long tcmi_syscall_hooks_sys_getresgid (gid_t *rgid, gid_t *egid, gid_t *sgid)
<<private>> Getresgid system call hook
static long tcmi_syscall_hooks_sys_setresgid (gid_t rgid, gid_t egid, gid_t sgid)
<<private>> Setresgid system call hook
static long tcmi_syscall_hooks_sys_getgroups (int size, gid_t *groups)
<<private>> Getgroups system call hook
static long tcmi_syscall_hooks_sys_setgroups (int size, gid_t *groups)
<<private>> Setgroups system call hook
Detailed Description
syscalls hooks for proces identification manipulation.
Date: 13/06/2007
Author: Petr Malat
Id:
tcmi_syscallhooks_groupident.c,v 1.2 2007/09/02 13:54:30 stavam2 Exp
This file is part of Task Checkpointing and Migration Infrastructure(TCMI) Copyleft (C) 2007 Petr Malat
TCMI is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
TCMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file tcmi_syscallhooks_groupident.c.
Macro Definition Documentation
#define TCMI_SYSCALLHOOKS_GROUPIDENT_PRIVATE
Definition at line 40 of file tcmi_syscallhooks_groupident.c.
Function Documentation
static long tcmi_syscall_hooks_sys_getegid (void) static
<<private>> Getegid system call hook
Returns
effective group id
Definition at line 94 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call0(), and TCMI_RPC_SYS_GETEGID.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     return tcmi_rpc_call0(tcmi_guest_rpc, TCMI_RPC_SYS_GETEGID);
 }
static long tcmi_syscall_hooks_sys_getgid (void) static
<<private>> Getgid system call hook
Returns
- the session ID of the calling process
Definition at line 84 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call0(), and TCMI_RPC_SYS_GETGID.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     return tcmi_rpc_call0(tcmi_guest_rpc, TCMI_RPC_SYS_GETGID);
 }
static long tcmi_syscall_hooks_sys_getgroups (int size, gid_t * groups) static
<<private>> Getgroups system call hook
Returns
the session ID of the calling process
Definition at line 145 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call2(), and TCMI_RPC_SYS_GETGROUPS.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     if( size == 0 )
         return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_GETGROUPS, 0, (unsigned long)NULL);
     else{
         if( !access_ok( VERIFY_WRITE, groups, size * sizeof(gid_t) ) )
             return -EFAULT;
         return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_GETGROUPS, size, (unsigned long)groups);
     }
 }
static long tcmi_syscall_hooks_sys_getresgid (gid_t * rgid, gid_t * egid, gid_t * sgid) static
<<private>> Getresgid system call hook
Returns
zero on success
Definition at line 125 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_GETRESGID.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_GETRESGID, (unsigned long)rgid, (unsigned long)egid, (unsigned long)sgid);
 }
static long tcmi_syscall_hooks_sys_setgid (gid_t gid) static
<<private>> Setgid system call hook
Returns
zero on success
Definition at line 105 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call1(), and TCMI_RPC_SYS_SETGID.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     return tcmi_rpc_call1(tcmi_guest_rpc, TCMI_RPC_SYS_SETGID, gid);
 }
static long tcmi_syscall_hooks_sys_setgroups (int size, gid_t * groups) static
<<private>> Setgroups system call hook
Returns
the session ID of the calling process
Definition at line 161 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call2(), and TCMI_RPC_SYS_SETGROUPS.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     if( size > NGROUPS_MAX )
         return -EINVAL;
     else{
         if( !access_ok(VERIFY_READ, groups, size * sizeof(gid_t)) )
             return -EFAULT;
         return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_SETGROUPS,
                 size, (unsigned long)groups );
     }
 }
static long tcmi_syscall_hooks_sys_setregid (gid_t rgid, gid_t egid) static
<<private>> Setregid system call hook
Returns
zero on success
Definition at line 115 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call2(), and TCMI_RPC_SYS_SETREGID.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_SETREGID, rgid, egid);
 }
static long tcmi_syscall_hooks_sys_setresgid (gid_t rgid, gid_t egid, gid_t sgid) static
<<private>> Setresgid system call hook
Returns
zero on success
Definition at line 135 of file tcmi_syscallhooks_groupident.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_SETRESGID.
Referenced by tcmi_syscall_hooks_groupident_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_SETRESGID, rgid, egid, sgid);
 }