Clondike: proxyfs_generic_real_file class
proxyfs_generic_real_file class
proxyfs_real_file class
This class is used by server task for accessing generic files.
Macros
#define PROXYFS_GENERIC_REAL_FILE(arg) ((struct proxyfs_generic_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Functions
int proxyfs_generic_real_file_init (struct proxyfs_generic_real_file *self)
<<public>> Initialize generic_real_file
void proxyfs_generic_real_file_destroy (struct proxyfs_generic_real_file *self)
<<public>> Deinitialize generic_real_file
struct proxyfs_generic_real_file * proxyfs_generic_real_file_new (void)
<<public>> generic_real_file construktor
Detailed Description
This class is used by server task for accessing generic files.
Macro Definition Documentation
#define PROXYFS_GENERIC_REAL_FILE (arg) ((struct proxyfs_generic_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Definition at line 61 of file proxyfs_generic_real_file.h.
Function Documentation
void proxyfs_generic_real_file_destroy (struct proxyfs_generic_real_file * self)
<<public>> Deinitialize generic_real_file
int proxyfs_generic_real_file_init (struct proxyfs_generic_real_file * self)
<<public>> Initialize generic_real_file
<<public>> Initialize generic_real_file
Parameters
*self - pointer to this file instance
Returns
zero on success
Definition at line 173 of file proxyfs_generic_real_file.c.
References PROXYFS_REAL_FILE.
Referenced by proxyfs_generic_real_file_new().
 {
     PROXYFS_REAL_FILE(self)->ops = &generic_real_file_ops;
     return 0;
 }
struct proxyfs_generic_real_file* proxyfs_generic_real_file_new (void) read
<<public>> generic_real_file construktor
Returns
new proxyfs_generic_real_file instance or NULL on error
Definition at line 182 of file proxyfs_generic_real_file.c.
References mdbg, proxyfs_generic_real_file_init(), PROXYFS_REAL_FILE, proxyfs_real_file_destroy(), and proxyfs_real_file_init().
 {
     struct proxyfs_generic_real_file *self;
     self = (struct proxyfs_generic_real_file*)kmalloc(sizeof(struct proxyfs_generic_real_file), GFP_KERNEL);
     if( self == NULL ){
         mdbg(ERR3, "Allocating new proxyfs_generic_real_file failed");
         goto exit0;
     }
     if( proxyfs_real_file_init( PROXYFS_REAL_FILE(self) ) != 0 )
         goto exit1;
     if( proxyfs_generic_real_file_init( self ) != 0 )
         goto exit2;
     return self;
 exit2:
     proxyfs_real_file_destroy( PROXYFS_REAL_FILE(self) );
 exit1:
     kfree(self);
 exit0:
     return self;
 }