Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/migration/tcmi_npm_params.h File Reference
tcmi_npm_params.h File Reference
#include <linux/limits.h>
#include <linux/types.h>
#include <linux/compiler.h>
#include <linux/list.h>
#include <linux/binfmts.h>
#include <asm/page.h>
Data Structures
struct tcmi_npm_params
Structure containing data required for performing of non-preemtive restart.
Macros
#define MAX_ARG_PAGES (MAX_ARG_STRLEN/PAGE_SIZE)
#define NPM_FILENAME_MAX PATH_MAX
#define NPM_DATA_SIZE_MAX (PAGE_SIZE*MAX_ARG_PAGES)
Functions
struct tcmi_npm_params __attribute__ ((__packed__))
int extract_tcmi_npm_params (struct tcmi_npm_params *params, const char *filename, char __user *__user *argv, char __user *__user *envp)
Extracts npm params from user space passed params to a tcmi structure.
static int reserve_array_length (int count)
UGLY UGLY! Following 2 funcs would ideally not be in a header.
static int fixup_npm_params_pointers (struct tcmi_npm_params *params)
Given a npm params structure, this method will fixup args and envp pointers to point to correct places in the data member.
Variables
char file_name [PATH_MAX]
Name of the file that is being "execve-ed".
u_int8_t argsc
Count of args/envp params.
u_int8_t envpc
char ** args
Arrays of args and envps.
char ** envp
u_int32_t used_data_length
This field represents, how many bytes of data field is actually used.
char data [(PAGE_SIZE *(MAX_ARG_STRLEN/PAGE_SIZE))]
Helper field that stores content of args/envp for the serialization.
Data Structure Documentation
struct tcmi_npm_params
Structure containing data required for performing of non-preemtive restart.
The structure contains all required data in itself, the pointers all point to a "data" field. The organization in data field is as follows: args array (pointer to strings) + null termination args[0] first arg + null termination ..... envp array (pointer to envp strings) + null termination ...
Definition at line 32 of file tcmi_npm_params.h.
Data Fields
char ** args Arrays of args and envps.
. the actual values are stored in "data" member
u_int8_t argsc Count of args/envp params.
char data[(PAGE_SIZE *(MAX_ARG_STRLEN/PAGE_SIZE))] Helper field that stores content of args/envp for the serialization.
char ** envp
u_int8_t envpc
char file_name[PATH_MAX] Name of the file that is being "execve-ed".
u_int32_t used_data_length This field represents, how many bytes of data field is actually used.
(It is used for optimization of checkpoint size) This value is filled, when the args&envp are serialized into the data.
Macro Definition Documentation
#define MAX_ARG_PAGES (MAX_ARG_STRLEN/PAGE_SIZE)
Definition at line 15 of file tcmi_npm_params.h.
#define NPM_DATA_SIZE_MAX (PAGE_SIZE*MAX_ARG_PAGES)
Definition at line 19 of file tcmi_npm_params.h.
Referenced by copy_strings(), and extract_tcmi_npm_params().
#define NPM_FILENAME_MAX PATH_MAX
Definition at line 18 of file tcmi_npm_params.h.
Referenced by extract_tcmi_npm_params().
Function Documentation
struct tcmi_npm_params __attribute__ ((__packed__))
int extract_tcmi_npm_params (struct tcmi_npm_params * params, const char * filename, char __user *__user * argv, char __user *__user * envp)
Extracts npm params from user space passed params to a tcmi structure.
Parameters
params Structure to be filled with extracted data
Returns
0 on success
Definition at line 72 of file tcmi_npm_params.c.
References tcmi_npm_params::argsc, copy_strings(), count(), tcmi_npm_params::envpc, tcmi_npm_params::file_name, fixup_npm_params_pointers(), mdbg, NPM_DATA_SIZE_MAX, NPM_FILENAME_MAX, and tcmi_npm_params::used_data_length.
Referenced by tcmi_try_npm_on_exec().
{
     int remaining_max = NPM_DATA_SIZE_MAX;
     int err;
     if ( !params )
         return -EINVAL;
     if ( strlen(filename)+1 > NPM_FILENAME_MAX )
         return -EINVAL;
     strcpy(params->file_name, filename);
     params->argsc = count(argv, NPM_DATA_SIZE_MAX/sizeof(void*));
     params->envpc = count(envp, NPM_DATA_SIZE_MAX/sizeof(void*));
     if ( (err = copy_strings(params->argsc, argv, params, &remaining_max)) )
         return err;
     if ( (err = copy_strings(params->envpc, envp, params, &remaining_max)) )
         return err;
     params->used_data_length = NPM_DATA_SIZE_MAX - remaining_max;
     mdbg(INFO4, "Filename: %s, Argc: %d, Evnpc: %d Used data: %d", params->file_name, params->argsc, params->envpc, params->used_data_length);
     return fixup_npm_params_pointers(params);
 };
static int fixup_npm_params_pointers (struct tcmi_npm_params * params) static
Given a npm params structure, this method will fixup args and envp pointers to point to correct places in the data member.
Definition at line 68 of file tcmi_npm_params.h.
References tcmi_npm_params::args, tcmi_npm_params::argsc, tcmi_npm_params::data, tcmi_npm_params::envp, tcmi_npm_params::envpc, pos, and reserve_array_length().
Referenced by extract_tcmi_npm_params(), and tcmi_ckpt_npm_params_read().
{
     int i, pos =0;
     // Decode args array pointer
     params->args = (char**)params->data;
     pos += reserve_array_length(params->argsc);
     // Fill in pointers in arg arrays pointer
     for ( i=0; i < params->argsc; i++ ) {
         int len = strlen(params->data+pos);
         params->args[i] = params->data + pos;
         pos += (len+1);
     }
     params->args[i] = NULL;
     // Decode envp array pointer
     params->envp = (char**)(params->data + pos);
     pos += reserve_array_length(params->envpc);
     // Fill in pointers in envp arrays pointer
     for ( i=0; i < params->envpc; i++ ) {
         int len = strlen(params->data+pos);
         params->envp[i] = params->data + pos;
         pos += (len+1);
     }
     params->envp[i] = NULL;
     return 0;
 }
static int reserve_array_length (int count) inline static
UGLY UGLY! Following 2 funcs would ideally not be in a header.
. this is just a quick hack to made code working when deployed as modules.. better solution required How many bytes to be reserved for array
Definition at line 59 of file tcmi_npm_params.h.
Referenced by copy_strings(), and fixup_npm_params_pointers().
{
     // We have to use size of 64 bit pointer so that it is platform compatible
     return (1+count)*sizeof(int64_t);
 }
Variable Documentation
char** args
Arrays of args and envps.
. the actual values are stored in "data" member
Definition at line 52 of file tcmi_npm_params.h.
Referenced by ccfs_parse_options(), npm_check_full(), proxyfs_msg_compose_new(), tcmi_ccnmigman_new(), tcmi_ctlfs_dir_new(), tcmi_ctlfs_intfile_new(), tcmi_ctlfs_strfile_new(), tcmi_ctlfs_symlink_new(), tcmi_penmigman_new(), tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_get_response(), and tcmi_sock_new().
u_int8_t argsc
Count of args/envp params.
Definition at line 50 of file tcmi_npm_params.h.
char data[(PAGE_SIZE *(MAX_ARG_STRLEN/PAGE_SIZE))]
Helper field that stores content of args/envp for the serialization.
Definition at line 59 of file tcmi_npm_params.h.
Referenced by proxyfs_fs_fill_super(), proxyfs_task_data_ready_callback(), and tcmi_ctlfs_entry_traverse_pred().
char ** envp
Definition at line 52 of file tcmi_npm_params.h.
Referenced by copyof_kernel_execve(), npm_check_full(), tcmi_taskhelper_checkpoint(), and tcmi_taskhelper_restart().
u_int8_t envpc
Definition at line 50 of file tcmi_npm_params.h.
char file_name[PATH_MAX]
Name of the file that is being "execve-ed".
Definition at line 48 of file tcmi_npm_params.h.
u_int32_t used_data_length
This field represents, how many bytes of data field is actually used.
(It is used for optimization of checkpoint size) This value is filled, when the args&envp are serialized into the data.
Definition at line 57 of file tcmi_npm_params.h.