Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/manager/tcmi_ccnman.c File Reference
tcmi_ccnman.c File Reference
#include <linux/kthread.h>
#include <tcmi/migration/tcmi_migcom.h>
#include <tcmi/ctlfs/tcmi_ctlfs.h>
#include <tcmi/lib/tcmi_sock.h>
#include "tcmi_ccnmigman.h"
#include <kkc/kkc.h>
#include "tcmi_ccnman.h"
#include <dbg.h>
#include <director/director.h>
Macros
#define TCMI_CCNMAN_PRIVATE
#define MAX_LISTENINGS 2
maximum number of listenings
Functions
int tcmi_ccnman_init (struct tcmi_ctlfs_entry *root)
<<public>> Singleton instance initializer.
void tcmi_ccnman_shutdown (void)
<<public>> The manager is shutdown exactly in this order:
static int tcmi_ccnman_init_ctlfs_dirs (void)
<<private>> Creates the additional directories as described in here .
static int tcmi_ccnman_init_ctlfs_files (void)
<<private>> Creates the static files described here .
static void tcmi_ccnman_add_sleeper (struct kkc_sock_sleeper *sleeper)
Adds a sleeper that represents a wait queue element for a newly created socket into the internal sleepers list.
static void tcmi_ccnman_remove_sleepers (struct tcmi_sock *sock)
Searches the list of socket sleepers and removes all sleepers that match the socket.
static void tcmi_ccnman_stop_ctlfs_dirs (void)
<<private>> Releases all directories - called back by generic TCMI manager
static void tcmi_ccnman_stop_ctlfs_files (void)
<<private>> Unregisters and releases all control files.
static int tcmi_ccnman_listen (void *obj, void *str)
<<private>> Instantiates a new listening.
static int tcmi_ccnman_stop_listen_all (void *obj, void *data)
<<private>> Iterates through all active listenings and notifies each instance to quit.
static int tcmi_ccnman_stop_listen_one (void *obj, void *data)
<<private>> Destroys a particular listening specified by the user.
static int tcmi_man_set_mount (void *obj, void *data)
<<private>> Write method to set fs mount type
static int tcmi_man_set_mount_device (void *obj, void *data)
<<private>> Write method to set fs mount device
static int tcmi_man_set_mount_options (void *obj, void *data)
<<private>> Write method to set fs mount options
static void tcmi_ccnman_stop (void)
<<private>> This method is called back by the generic TCMI manager.
static int tcmi_ccnman_start_thread (void)
<<private>> Starts the listening thread.
static void tcmi_ccnman_stop_thread (void)
<<private>> The TCMI CCN manager listening thread is terminated.
static int tcmi_ccnman_thread (void *data)
<<private>> This is the actual listening thread.
static void tcmi_ccnman_process_sock (struct kkc_sock *sock)
<<private>> Processes a selected socket and checks for incoming connection.
struct fs_mount_params * tcmi_ccnman_get_mount_params (void)
<<public>> Getter of mount params structure.
Variables
static struct tcmi_ccnman self
Singleton instance pre-initialization.
static struct tcmi_man_ops ccnman_ops
Migration manager operations that support polymorphism.
Macro Definition Documentation
#define MAX_LISTENINGS 2
maximum number of listenings
Definition at line 52 of file tcmi_ccnman.c.
Referenced by tcmi_ccnman_init().
#define TCMI_CCNMAN_PRIVATE
Definition at line 43 of file tcmi_ccnman.c.
Function Documentation
int tcmi_ccnman_init (struct tcmi_ctlfs_entry * root)
<<public>> Singleton instance initializer.
The initialization is accomplished exactly in this order:
allocate new slot vector for listenings
start listening thread
delegate rest of initialization to TCMI generic manager
Parameters
*root - root directory of the filesystem, where all entries are to be created
Returns
0 upon success
Definition at line 65 of file tcmi_ccnman.c.
References ccnman_ops, MAX_LISTENINGS, mdbg, minfo, tcmi_ccnman_start_thread(), tcmi_ccnman_stop_thread(), TCMI_MAN, tcmi_man_init(), tcmi_slotvec_new(), and tcmi_slotvec_put().
Referenced by tcmi_module_init().
 {
     self.mount_params.mount_type[0] = '\0';
     self.mount_params.mount_options[0] = '\0';
     self.mount_params.mount_device[0] = '\0';
     minfo(INFO1, "Initializing TCMI CCN manager");
     if (!(self.listenings = tcmi_slotvec_new(MAX_LISTENINGS))) {
         mdbg(ERR3, "Failed to create listenings slot vector");
         goto exit0;
     }
     if (tcmi_ccnman_start_thread() < 0) {
         mdbg(ERR3, "Failed to start listening thread");
         goto exit1;
     }
     if (tcmi_man_init(TCMI_MAN(&self), root, &ccnman_ops, "ccn") < 0) {
         mdbg(ERR3, "TCMI CCN manager - generic init failed");
         goto exit2;
     }
     return 0;
     /* error handling */
  exit2:
     tcmi_ccnman_stop_thread();
  exit1:
     tcmi_slotvec_put(self.listenings);
  exit0:
     return -EINVAL;
 }
void tcmi_ccnman_shutdown (void)
<<public>> The manager is shutdown exactly in this order:
stop the listening thread, the thread doesn't need to worry about termination of any listenings-it will be done further
perform a generic shutdown (this destroys all files and stops migration etc.). This step preceeds stop listening as we need to be sure, that no control files are active (user might try adding a new listening interface)
stop listening on all interfaces
destroy the listenings slotvector (should be empty by now)
Definition at line 107 of file tcmi_ccnman.c.
References minfo, tcmi_ccnman_stop_listen_all(), tcmi_ccnman_stop_thread(), TCMI_MAN, tcmi_man_shutdown(), and tcmi_slotvec_put().
Referenced by tcmi_module_exit(), and tcmi_module_init().
 {
     int stop_listen = 1;
     minfo(INFO1, "Shutting down the TCMI CCN manager");
     tcmi_ccnman_stop_thread();
     tcmi_man_shutdown(TCMI_MAN(&self));
     tcmi_ccnman_stop_listen_all(NULL, &stop_listen);
     tcmi_slotvec_put(self.listenings);
 }