Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/comm/tcmi_comm.c File Reference
tcmi_comm.c File Reference
#include <linux/kthread.h>
#include "tcmi_msg_factory.h"
#include "tcmi_comm.h"
#include <dbg.h>
Macros
#define TCMI_COMM_PRIVATE
Functions
struct tcmi_comm * tcmi_comm_new (struct kkc_sock *sock, deliver_method_t *deliver, void *obj, int msg_group)
<<public>> TCMI communication component constructor.
void tcmi_comm_put (struct tcmi_comm *self)
<<public>> Releases the instance.
static int tcmi_comm_thread (void *comm)
<<private>> Messages receiving thread.
Variables
static int tcmi_comm_counter = 0
Thread counter - used for receiving thread naming.
Macro Definition Documentation
#define TCMI_COMM_PRIVATE
Definition at line 36 of file tcmi_comm.c.
Function Documentation
static int tcmi_comm_thread (void * comm) static
<<private>> Messages receiving thread.
receives any messages on the connection that is part of the tcmi_comm instance
as long as no invalid ID or other error occurs or the main thread signals to quit it will be delivering messages to the subscribed object via its delivery method.
messages that are not successfully delivered are discarded
The thread is always stopped synchronously with the instance destruction, therefore there is no need to account an extra reference for the thread.
Parameters
*comm - pointer to this communication instance
Returns
0 upon successful termination.
Definition at line 145 of file tcmi_comm.c.
References KKC_SOCK_BLOCK, kkc_sock_getpeername2(), kkc_sock_getsockname2(), kkc_sock_recv(), mdbg, minfo, tcmi_msg::msg_id, TCMI_COMM, tcmi_msg_factory(), tcmi_msg_put(), tcmi_msg_recv(), and wait_on_should_stop.
Referenced by tcmi_comm_new().
 {
     struct tcmi_comm *self = TCMI_COMM(comm);
     /* make local copies instance attributes, this saves one
      * dereference for each */
     struct kkc_sock *sock = self->sock;
     deliver_method_t *deliver = self->deliver;
     int msg_group = self->msg_group;
     void *obj = self->obj;
     /* pointer to the message received */
     struct tcmi_msg *m;
     u_int32_t msg_id;
     int err = 0;
     minfo(INFO3, "Receiving on socket local: '%s', remote: '%s'",
           kkc_sock_getsockname2(sock), kkc_sock_getpeername2(sock));
     /* receive messages, checking for signals or stop request */
     while (!(kthread_should_stop() || signal_pending(current))) {
         if ((err = kkc_sock_recv(sock, &msg_id, sizeof(msg_id), KKC_SOCK_BLOCK)) < 0) {
             minfo(ERR3, "Error receiving message ID, error code: %d, terminating", err);
             break;
         }
         if (!(m = tcmi_msg_factory(msg_id, msg_group))) {
             minfo(ERR3, "Error building message %x, terminating", msg_id);
             break;
         }
         if ((err = tcmi_msg_recv(m, sock)) < 0) {
             minfo(ERR3, "Error receiving message %x, error %d, terminating", msg_id, err);
             break;
         }
         /* try to deliver, if it fails destroy the message */
         if (deliver(obj, m) < 0)
             tcmi_msg_put(m);
     }
     /* very important to sync with the the thread that is terminating us */
     wait_on_should_stop();
     mdbg(INFO3, "Message receiving thread terminating");
     return err;
 }