Clondike: tcmi_task class
tcmi_task class
task component
TCMI task is an abstraction for any process in the system that participates in migration.
Modules
tcmi_guesttask class
This class is an abstraction for an 'immigrated' process on PEN.
tcmi_shadowtask class
This class is an abstraction for a migrated process on CCN.
Data Structures
struct tcmi_task
Compound structure that gathers necessary process information.
struct tcmi_task_ops
TCMI task operations that support polymorphism.
Macros
#define TCMI_TASK(t) ((struct tcmi_task*)t)
Casts to the task instance.
Enumerations
enum tcmi_task_method_status_t {
TCMI_TASK_KEEP_PUMPING, TCMI_TASK_MOVE_ME, TCMI_TASK_EXECVE_FAILED_KILL_ME, TCMI_TASK_KILL_ME,
TCMI_TASK_LET_ME_GO, TCMI_TASK_REMOVE_AND_LET_ME_GO
}
Describes the status returned by task methods that are executed from the method queue.
Functions
static int tcmi_task_show_remote_pid (void *obj, void *data)
<<private>> Read method for the TCMI ctlfs - reports remote PID.
static void tcmi_task_release_execve_context (struct tcmi_task *self)
<<private>> Releases the execve context (execve file, argv, envp) Since the argv/envp have allocated a linear chunks of memory (including all strings) we need to issue only 1 kfree/vfree for each and don't need to scan the array releasing each string separate.
int tcmi_task_deliver_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<public>> Delivers a specified message.
u_int32_t tcmi_task_migman_id (struct tcmi_task *self)
<<public>> Accessor of id of the migration manager associated with this task.
u_int tcmi_task_migman_slot_index (struct tcmi_task *self)
<<public>> Accessor of vector slot index of the migration manager associated with this task.
int tcmi_task_init (struct tcmi_task *self, pid_t local_pid, struct tcmi_migman *migman, struct kkc_sock *sock, struct tcmi_ctlfs_entry *d_migproc, struct tcmi_ctlfs_entry *d_migman, struct tcmi_task_ops *ops)
Initializes the task.
static struct tcmi_task * tcmi_task_get (struct tcmi_task *self)
<<public>> Instance accessor, increments the reference counter.
void tcmi_task_put (struct tcmi_task *self)
<<public>> Releases the instance.
void tcmi_task_submit_method (struct tcmi_task *self, tcmi_method_t *method, void *data, int size)
<<public>> Submits a method for execution.
void tcmi_task_flush_and_submit_method (struct tcmi_task *self, tcmi_method_t *method, void *data, int size)
<<public>> Prior to submitting, atomically flushes the method queue.
int tcmi_task_process_methods (struct tcmi_task *self)
<<public>> Processes all methods in the queue.
int tcmi_task_process_msg (void *self, struct tcmi_method_wrapper *wr)
<<public>> Processes message in the message queue.
int tcmi_task_send_message (void *self, struct tcmi_method_wrapper *wr)
<<public>> Sends a message to peer.
int tcmi_task_emigrate_ppm_p (void *self, struct tcmi_method_wrapper *wr)
<<public>> Emigrates a task to a PEN - PPM w/ physical checkpoint.
int tcmi_task_migrateback_ppm_p (void *self, struct tcmi_method_wrapper *wr)
<<public>> Migrates a task back to CCN - PPM w/ physical checkpoint.
int tcmi_task_emigrate_ppm_v (void *self, struct tcmi_method_wrapper *wr)
<<public>> Emigrates a task to a PEN - PPM w/ virtual checkpoint.
int tcmi_task_migrateback_ppm_v (void *self, struct tcmi_method_wrapper *wr)
<<public>> Migrates a task back to CCN - PPM w/ virtual checkpoint.
int tcmi_task_emigrate_npm (void *self, struct tcmi_method_wrapper *wr)
<<public>> Emigrates a task to a PEN - NPM.
int tcmi_task_migrateback_npm (void *self, struct tcmi_method_wrapper *wr)
<<public>> Migrates a task back to CCN - NPM.
int tcmi_task_exit (void *self, struct tcmi_method_wrapper *wr)
<<public>> Exits a task.
int tcmi_task_prepare_execve (struct tcmi_task *self, char *file, char **argv, char **envp)
<<public>> Prepares execution of a file given the arrays of arguments and environment.
int tcmi_task_execve (void *self, struct tcmi_method_wrapper *wr)
<<public>> Executes the file that has been previously setup for execution.
static struct tcmi_slotvec * tcmi_task_transactions (struct tcmi_task *self)
<<public>> Transactions accessor - needed when tasks construct their own messages.
static long tcmi_task_exit_code (struct tcmi_task *self)
<<public>> Exit code accessor.
static void tcmi_task_set_exit_code (struct tcmi_task *self, long code)
<<public>> Exit code setter.
static void * tcmi_task_context (struct tcmi_task *self)
<<public>> Process context accessor.
static void tcmi_task_set_context (struct tcmi_task *self, void *context)
<<public>> Process context setter.
static char * tcmi_task_ckpt_name (struct tcmi_task *self)
<<public>> Task checkpoint pathname accessor.
static pid_t tcmi_task_local_pid (struct tcmi_task *self)
<<public>> Local PID accessor.
static pid_t tcmi_task_remote_pid (struct tcmi_task *self)
<<public>> Remote PID accessor.
static void tcmi_task_set_local_pid (struct tcmi_task *self, pid_t local_pid)
<<public>> Local PID setter.
static int tcmi_task_show_remote_pid_rev (void *obj, void *data)
static void tcmi_task_set_remote_pid (struct tcmi_task *self, pid_t remote_pid)
<<public>> Remote PID setter.
static unsigned long tcmi_task_wait_for_pick_up_timeout (struct tcmi_task *self, unsigned long timeout)
<<public>> Waits until the task is picked up, by the associated process.
static void tcmi_task_pick_up (struct tcmi_task *self)
<<public>> Signals, the tcmi task has been pickedup by the associated process.n
static int tcmi_task_picked_up (struct tcmi_task *self)
<<public>> Checks whether the task has been picked up.
static int tcmi_task_send_anonymous_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<public>> Sends a specified message.
static int tcmi_task_get_execve_count (struct tcmi_task *self)
static void tcmi_task_inc_execve_count (struct tcmi_task *self)
static struct task_struct * tcmi_task_to_task_struct (struct tcmi_task *self)
Returns a task_struct associated with the tcmi_task.
static int tcmi_task_send_and_receive_msg (struct tcmi_task *self, struct tcmi_msg *req, struct tcmi_msg **resp)
<<public>> Sends a specified message and waits for a response.
static void tcmi_task_signal_peer_lost (struct tcmi_task *self)
Notifies task that it peer is lost and sends a kill signal to that task.
static int tcmi_task_do_signal (struct tcmi_task *self, unsigned long signr, siginfo_t *info)
<<public>> Processes a specified signal.
static enum tcmi_task_type tcmi_task_get_type (struct tcmi_task *self)
<<public>> Get task type
static u_int tcmi_task_hash (pid_t local_pid, u_int hashmask)
<<public>> Computes the hash value of the task (to be used in tasks slotvec of migman)
static int tcmi_task_check_peer_lost (struct tcmi_task *self, int err)
Simple error checking method to be used after communication operations to detect lost peer.
Detailed Description
TCMI task is an abstraction for any process in the system that participates in migration.
This <<template>> class gathers common functionality for shadow tasks that represent a migrated process on CCN as well as for guest tasks that represent the migrated process on PEN.
TCMI tasks are controlled from user space via migration component. Each task is associated with its migration manager. This ensures that all messages addressed to a particular task are also delivered to its message queue or transactions slotvector. A TCMI task is given a communication socket (KKC socket) upon its instantiation. It is the communication channel that it will use for sending messages out. Note, that message delivery is handled exclusively by the migration manager. This makes it very easy to move a task among TCMI migration managers.
The main purpose of this class is execution of methods in the context of the shadow and guest process resp. These methods are submitted by the migration component into the method queue and include:
request to migrate a process to a PEN - includes PPM_P, PPM_V, NPM
request to migrate a process back to CCN - includes PPM_P, PPM_V, NPM
request to process any incoming TCMI messages from the message queue.
request to terminate
Methods in the queue are processed via a 'method pump'. Each method returns a status that is used by the controlling component to make a decision what to do further. Status return codes have following meanings:
KEEP_PUMPING - the method pump should keep going as long as there are methods to process
MOVE_ME - stop pumping and tell the task controlling component to move it to a different migration manager (relevant for shadow tasks on CCN)
EXECVE_FAILED_KILL_ME - stop pumping and tell the task controlling component to kill this task. This status denotes the situation when the task tried issuing execve(typically when loading a new checkpoint or processing a non-preemptive migration request) and it failed. This status is needed as it also instructs the method pump not to discard the method wrapper as it has already been done by (tcmi_task_execve() method internally)
KILL_ME - stop pumping and tell the task controlling component to kill this task (issue do_exit()) and remove it from its migration manager
LET_ME_GO -stop pumping and tell the task controlling component leave the migration mode, leave the task as is.
REMOVE_AND_LET_ME_GO -stop pumping and tell the task controlling component to remove the task from its current migration manager, destroy the tcmi_task and and let the regular task go. For example, this status is returned by task_exit() method as it is called from the intercepted exit system call. Once the TCMI task is detached from its process the exit system call resumes and performs the actual exit.
In addition, the task also holds the filename along with argv and envp arrays that will be executed. It is important to keep track of this data as they are required by the execve (e.g. when migrating a a task by executing it's checkpoint image). These resources eventually need to be released once the execve has been issued or when the task is destroyed. There is functionality that makes arguments and environment management easy.
Abbreviations:
PPM_P - preemptive process migration using physical checkpoint image
PPM_V - preemptive process migration using virtual checkpoint image
NPM - non-preemptive process migration (using execve hook)
Data Structure Documentation
struct tcmi_task
Compound structure that gathers necessary process information.
Definition at line 139 of file tcmi_task.h.
Data Fields
char ** argv command line arguments for the checkpoint file (NULL terminated array of strings)
char * ckpt_pathname contains the pathname of the latest checkpoint file
void * context Pointer to the context of a process when switched into user mode.
struct tcmi_ctlfs_entry * d_migman_root
struct tcmi_ctlfs_entry * d_task TCMI ctlfs - migproc directory entry.
char ** envp environment (NULL terminated array of strings)
int execve_count How many time was execve called on this task, since it became controlled by the tcmi.
long exit_code Task exit code - used when terminating the task.
struct tcmi_ctlfs_entry * f_remote_pid TCMI ctlfs - contains remote PID.
struct tcmi_ctlfs_entry * f_remote_pid_rev
pid_t local_pid local PID on PEN, CCN resp.
struct tcmi_queue method_queue queue of methods to be executed.
struct tcmi_migman * migman Reference to a migration manager to which this task belongs to.
TODO: This "back" reference perhaps couples the class to tighly to migman class. We in fact need just a slotvector of migman tasks so that this task can handle its addition/removal on creation/deletion.
struct tcmi_queue msg_queue Message queue for transaction-less messages.
tcmi_slot_node_t node node for storage in the migration slot of the migration manager
struct tcmi_task_ops * ops Operations specific to shadow/guest tasks resp.
volatile int peer_lost Flag used to inform the task that its peer is lost and it should terminate.
struct completion picked_up Used for signalling when the task is picked up by the associated process.
int picked_up_flag This flag is set when the task has been picked up, indicates the completion is finished.
It is used when performing synchronized waiting on pickup with timeout.
void * proxyfs_data Data for proxyfs filesystem.
atomic_t ref_count Instance reference counter.
pid_t remote_pid remote PID on PEN, CCN resp.
struct tcmi_ctlfs_entry * s_migman TCMI ctlfs - symlink to the migration manager directory.
struct kkc_sock * sock communication socket.
struct tcmi_slotvec * transactions Message transactions.
struct tcmi_task_ops
TCMI task operations that support polymorphism.
Definition at line 219 of file tcmi_task.h.
Data Fields
int(* process_msg)(struct tcmi_task *, struct tcmi_msg *)
Processes a message that has arrived on the message queue.
int(* emigrate_ppm_p)(struct tcmi_task *)
Emigrates a task to a PEN - PPM w/ physical checkpoint.
int(* migrateback_ppm_p)(struct tcmi_task *)
Migrates a task back to CCN - PPM w/ physical checkpoint.
int(* emigrate_ppm_v)(struct tcmi_task *)
Emigrates a task to a PEN - PPM w/ virtual checkpoint.
int(* migrateback_ppm_v)(struct tcmi_task *)
Migrates a task back to CCN - PPM w/ virtual checkpoint.
int(* emigrate_npm)(struct tcmi_task *, struct tcmi_npm_params *)
Emigrates a task to a PEN - NPM.
int(* migrateback_npm)(struct tcmi_task *, struct tcmi_npm_params *)
Migrates a task back to CCN - NPM.
int(* exit)(struct tcmi_task *, long)
Used upon task exit.
int(* execve)(struct tcmi_task *)
Instance specific execve.
int(* do_signal)(struct tcmi_task *self, unsigned long signr, siginfo_t *info)
Handles a specific signal.
void(* free)(struct tcmi_task *)
Releases the instance specific resources.
enum tcmi_task_type(* get_type)(void)
Return type of task.
Field Documentation
int(* tcmi_task_ops::do_signal)(struct tcmi_task *self, unsigned long signr, siginfo_t *info)
Handles a specific signal.
Definition at line 239 of file tcmi_task.h.
int(* tcmi_task_ops::emigrate_npm)(struct tcmi_task *, struct tcmi_npm_params *)
Emigrates a task to a PEN - NPM.
Definition at line 231 of file tcmi_task.h.
Referenced by tcmi_task_emigrate_npm().
int(* tcmi_task_ops::emigrate_ppm_p)(struct tcmi_task *)
Emigrates a task to a PEN - PPM w/ physical checkpoint.
Definition at line 223 of file tcmi_task.h.
Referenced by tcmi_task_emigrate_ppm_p().
int(* tcmi_task_ops::emigrate_ppm_v)(struct tcmi_task *)
Emigrates a task to a PEN - PPM w/ virtual checkpoint.
Definition at line 227 of file tcmi_task.h.
Referenced by tcmi_task_emigrate_ppm_v().
int(* tcmi_task_ops::execve)(struct tcmi_task *)
Instance specific execve.
Definition at line 237 of file tcmi_task.h.
Referenced by tcmi_task_execve().
int(* tcmi_task_ops::exit)(struct tcmi_task *, long)
Used upon task exit.
Definition at line 235 of file tcmi_task.h.
Referenced by tcmi_task_exit().
void(* tcmi_task_ops::free)(struct tcmi_task *)
Releases the instance specific resources.
Definition at line 241 of file tcmi_task.h.
enum tcmi_task_type(* tcmi_task_ops::get_type)(void)
Return type of task.
Definition at line 243 of file tcmi_task.h.
int(* tcmi_task_ops::migrateback_npm)(struct tcmi_task *, struct tcmi_npm_params *)
Migrates a task back to CCN - NPM.
Definition at line 233 of file tcmi_task.h.
Referenced by tcmi_task_migrateback_npm().
int(* tcmi_task_ops::migrateback_ppm_p)(struct tcmi_task *)
Migrates a task back to CCN - PPM w/ physical checkpoint.
Definition at line 225 of file tcmi_task.h.
Referenced by tcmi_task_migrateback_ppm_p().
int(* tcmi_task_ops::migrateback_ppm_v)(struct tcmi_task *)
Migrates a task back to CCN - PPM w/ virtual checkpoint.
Definition at line 229 of file tcmi_task.h.
Referenced by tcmi_task_migrateback_ppm_v().
int(* tcmi_task_ops::process_msg)(struct tcmi_task *, struct tcmi_msg *)
Processes a message that has arrived on the message queue.
Definition at line 221 of file tcmi_task.h.
Referenced by tcmi_task_process_msg().
Macro Definition Documentation
#define TCMI_TASK (t) ((struct tcmi_task*)t)
Casts to the task instance.
Definition at line 261 of file tcmi_task.h.
Referenced by tcmi_guesttask_new(), tcmi_guesttask_post_fork_set_tid(), tcmi_man_fork(), tcmi_shadowtask_new(), tcmi_syscall_hooks_post_fork(), tcmi_task_emigrate_npm(), tcmi_task_emigrate_ppm_p(), tcmi_task_emigrate_ppm_v(), tcmi_task_execve(), tcmi_task_exit(), tcmi_task_migrateback_npm(), tcmi_task_migrateback_ppm_p(), tcmi_task_migrateback_ppm_v(), tcmi_task_process_msg(), tcmi_task_send_message(), tcmi_task_show_remote_pid(), and tcmi_task_show_remote_pid_rev().
Enumeration Type Documentation
enum tcmi_task_method_status_t
Describes the status returned by task methods that are executed from the method queue.
See the task detailed description for explanation of each individual return status.
Enumerator
TCMI_TASK_KEEP_PUMPING
TCMI_TASK_MOVE_ME
TCMI_TASK_EXECVE_FAILED_KILL_ME
TCMI_TASK_KILL_ME
TCMI_TASK_LET_ME_GO
TCMI_TASK_REMOVE_AND_LET_ME_GO
Definition at line 251 of file tcmi_task.h.
              {
     TCMI_TASK_KEEP_PUMPING,
     TCMI_TASK_MOVE_ME,
     TCMI_TASK_EXECVE_FAILED_KILL_ME,
     TCMI_TASK_KILL_ME,
     TCMI_TASK_LET_ME_GO,
     TCMI_TASK_REMOVE_AND_LET_ME_GO
 } tcmi_task_method_status_t;
Function Documentation
static int tcmi_task_check_peer_lost (struct tcmi_task * self, int err) inline static
Simple error checking method to be used after communication operations to detect lost peer.
In case err indicates broken connection, peer is considered dead for us.
Returns
Returns passed err param, so that it can be easily used for call chaining
Definition at line 648 of file tcmi_task.h.
References tcmi_task_signal_peer_lost().
Referenced by tcmi_guesttask_migrateback_p(), tcmi_guesttask_process_p_emigrate_msg(), tcmi_shadowtask_do_signal(), tcmi_shadowtask_emigrate_p(), tcmi_shadowtask_migrateback_ppm_p(), and tcmi_shadowtask_process_msg().
{
       // For now, we react only on broken pipe, but we may react on more cases, right?
       if ( err == -EPIPE )
       tcmi_task_signal_peer_lost(self);
       return err;
 }
static char* tcmi_task_ckpt_name (struct tcmi_task * self) inline static
<<public>> Task checkpoint pathname accessor.
Parameters
*self - pointer to this task instance
Returns
the most recent checkpoint pathname.
Definition at line 400 of file tcmi_task.h.
Referenced by tcmi_guesttask_migrateback_p(), and tcmi_shadowtask_emigrate_p().
 {
     return self->ckpt_pathname;
 }
static void* tcmi_task_context (struct tcmi_task * self) inline static
<<public>> Process context accessor.
Parameters
*self - pointer to this task instance
Returns
process context.
Definition at line 378 of file tcmi_task.h.
Referenced by tcmi_taskhelper_checkpoint(), and tcmi_taskhelper_notify_current().
 {
     return self->context;
 }
int tcmi_task_deliver_msg (struct tcmi_task * self, struct tcmi_msg * m)
<<public>> Delivers a specified message.
Asks the message to deliver itself into a message queue or associate itself with a matching transaction. The result is communicated back.
If the message is delivered sucessfully, an enter to the migration mode is requested.
Parameters
*self - pointer to this task instance
*m - message to be delivered.
Returns
0 when the message has been successfully delivered.
Definition at line 906 of file tcmi_task.c.
References mdbg, minfo, self, tcmi_msg_deliver(), TCMI_MSG_GROUP, TCMI_MSG_GROUP_PROC, tcmi_msg_id(), TCMI_PROCMSG, tcmi_procmsg_enforce_migmode(), tcmi_queue_empty(), tcmi_task_local_pid(), tcmi_task_process_msg(), tcmi_task_submit_method(), and tcmi_taskhelper_enter_mig_mode().
Referenced by tcmi_migcom_immigrate(), and tcmi_migman_deliver_msg().
 {
     int res = tcmi_msg_deliver(m, &self->msg_queue, self->transactions);
     if ( res ) {
         minfo(ERR3, "Failed to deliver the message: errno=%d", res);
         return res;
     }
     // Request migration mode only for proc messages with enforce migmode flag specified
     if (TCMI_MSG_GROUP(tcmi_msg_id(m)) == TCMI_MSG_GROUP_PROC && tcmi_procmsg_enforce_migmode(TCMI_PROCMSG(m)) ) {
         mdbg(INFO4, "Message successfully delivered, requesting migration mode for pid: %d", tcmi_task_local_pid(self));
         // TODO: Nasty workaround.. this should likely by in a guest task specific code, since it makes no sense for shadow
         if ( tcmi_queue_empty(&self->method_queue) ) {
             int wait_for_msg = 0;
             // If there is no method in method queue, there is nothing that would process the message, so we have to submit the processing method into the queue
             tcmi_task_submit_method(self, tcmi_task_process_msg, &wait_for_msg, sizeof(int));
         }
         tcmi_taskhelper_enter_mig_mode(self);
     }
     return 0;
 }
static int tcmi_task_do_signal (struct tcmi_task * self, unsigned long signr, siginfo_t * info) inline static
<<public>> Processes a specified signal.
The work is delegated to the task specific method if one is specified. This allows the shadow and guest processes to handle the signal differently. In fact, they have to: - shadow process takes appropriate actions and forwards the signal to the guest using signal forwarding component(since the guest might not be in migration mode) - guest process takes only appropriate actions and is able to communicate with the shadow directly.
Parameters
*self - pointer to this task instance
signr - signal that is to be processed
*info - info for signal to be processed
Returns
result of the task specific signal handling method or TCMI_TASK_KEEP_PUMPING
Definition at line 599 of file tcmi_task.h.
References mdbg, self, TCMI_TASK_KEEP_PUMPING, and TCMI_TASK_KILL_ME.
Referenced by tcmi_taskhelper_do_signals().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     mdbg(INFO2, "Processing signal %lu", signr);
     if ( self->peer_lost && signr == SIGKILL ) {
         mdbg(INFO2, "Peer task is dead, killing current task");
         return TCMI_TASK_KILL_ME;
     }
     if (self->ops->do_signal)
         res = self->ops->do_signal(self, signr, info);
     return res;
 }
int tcmi_task_emigrate_npm (void * self, struct tcmi_method_wrapper * wr)
<<public>> Emigrates a task to a PEN - NPM.
<<public>> Emigrates a task to a PEN - NPM.
NPM. All the work is delegated to the task specific emigrate method.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the task specific emigrate method or TCMI_TASK_KEEP_PUMPING
Definition at line 583 of file tcmi_task.c.
References tcmi_task_ops::emigrate_npm, mdbg, tcmi_task::ops, tcmi_method_wrapper_data(), TCMI_TASK, TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), and tcmi_task_remote_pid().
Referenced by tcmi_migcom_emigrate_ccn_npm().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     struct tcmi_npm_params* npm_params = *((struct tcmi_npm_params**)tcmi_method_wrapper_data(wr));
     mdbg(INFO3, "Task - local pid %d, remote pid %d, emigrating",
          tcmi_task_local_pid(self_tsk), tcmi_task_remote_pid(self_tsk));
     if (self_tsk->ops->emigrate_npm)
         res = self_tsk->ops->emigrate_npm(self_tsk, npm_params);
     return res;
 }
int tcmi_task_emigrate_ppm_p (void * self, struct tcmi_method_wrapper * wr)
<<public>> Emigrates a task to a PEN - PPM w/ physical checkpoint.
<<public>> Emigrates a task to a PEN - PPM w/ physical checkpoint.
PPM w/ physical checkpoint. All the work is delegated to the task specific emigrate method.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the task specific emigrate method or TCMI_TASK_KEEP_PUMPING
Definition at line 487 of file tcmi_task.c.
References tcmi_task_ops::emigrate_ppm_p, mdbg, tcmi_task::ops, TCMI_TASK, TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), and tcmi_task_remote_pid().
Referenced by tcmi_migcom_emigrate_ccn_ppm_p().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     mdbg(INFO3, "Task - local pid %d, remote pid %d, emigrating",
          tcmi_task_local_pid(self_tsk), tcmi_task_remote_pid(self_tsk));
     if (self_tsk->ops->emigrate_ppm_p)
         res = self_tsk->ops->emigrate_ppm_p(self_tsk);
     return res;
 }
int tcmi_task_emigrate_ppm_v (void * self, struct tcmi_method_wrapper * wr)
<<public>> Emigrates a task to a PEN - PPM w/ virtual checkpoint.
<<public>> Emigrates a task to a PEN - PPM w/ virtual checkpoint.
PPM w/ virtual checkpoint. All the work is delegated to the task specific emigrate method.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the task specific emigrate method or TCMI_TASK_KEEP_PUMPING
Definition at line 535 of file tcmi_task.c.
References tcmi_task_ops::emigrate_ppm_v, mdbg, tcmi_task::ops, TCMI_TASK, TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), and tcmi_task_remote_pid().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     mdbg(INFO3, "Task - local pid %d, remote pid %d, emigrating",
          tcmi_task_local_pid(self_tsk), tcmi_task_remote_pid(self_tsk));
     if (self_tsk->ops->emigrate_ppm_v)
         res = self_tsk->ops->emigrate_ppm_v(self_tsk);
     return res;
 }
int tcmi_task_execve (void * self, struct tcmi_method_wrapper * wr)
<<public>> Executes the file that has been previously setup for execution.
Prior to performing the exec, it is necessary to discard the method wrapper as the method pump won't resume anymore in this context. Also the instance specific execve method is called. This allows a particular TCMI task to get ready for an upcoming execve.
Parameters
*self - pointer to this task instance
*wr - method wrapper that carried this method in the queue.
Returns
- doesn't return upon succesful execve, otherwise TCMI_TASK_EXECVE_FAILED_KILL_ME to inform the method pump to quit without discarding the method wrapper as we have already done so.
Definition at line 804 of file tcmi_task.c.
References tcmi_task::argv, tcmi_task::ckpt_pathname, copyof_kernel_execve(), tcmi_task::envp, errno, tcmi_task_ops::execve, mdbg, memory_sanity_check, minfo, tcmi_task::ops, tcmi_method_wrapper_put(), TCMI_TASK, and TCMI_TASK_EXECVE_FAILED_KILL_ME.
Referenced by tcmi_taskhelper_restart().
 {
     int err = 0;
     mm_segment_t oldfs;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
 memory_sanity_check("Sanity check on execve");
     mdbg(INFO2, "Performing exec on '%s' Args: %p ([0] -> %p) Envp: %p ([0] -> %p) in atomic=%d", self_tsk->ckpt_pathname, self_tsk->argv, self_tsk->argv[0], self_tsk->envp, self_tsk->envp[0], in_atomic());
     /* discard the method wrapper prior to doing anything */
     tcmi_method_wrapper_put(wr);
     /* instance specific execve notification */
     if (self_tsk->ops->execve)
         err = self_tsk->ops->execve(self_tsk);
     if (err < 0) {
         mdbg(ERR3, "Task specific execve failed!");
         goto exit0;
     }
     oldfs = get_fs();
     set_fs(KERNEL_DS);
     /*mm_segment_t fs = get_fs();*/
 memory_sanity_check("Sanity check on execve - just before the call");
     if ((err = copyof_kernel_execve((const char*)self_tsk->ckpt_pathname, (const char* const *)self_tsk->argv,
     /* if ((err = execve(self_tsk->ckpt_pathname, self_tsk->argv, */
              (const char* const *)self_tsk->envp)) < 0) {
         minfo(ERR3, "Execve failed!!! %d, errno=%d", err, errno);
     }
     set_fs(oldfs);
     mdbg(INFO2, "Exec done!");
     /* error handling */
  exit0:
     return TCMI_TASK_EXECVE_FAILED_KILL_ME;
 }
int tcmi_task_exit (void * self, struct tcmi_method_wrapper * wr)
<<public>> Exits a task.
<<public>> Exits a task.
This method is primarily intended terminate the main method processing loop of the task. The task is then removed from its migration manager and destroyed. Task specific method has the chance to communicate this to its counter part. E.g. a guest task sends an exit code to the associated shadow process on the CCN.
The method wrapper might contain an exit code. If so, it is communicated to the specific task method. The default exit code is 0.
Parameters
*self - pointer to this task instance
*wr - method wrapper that stores the requested exit code.
Returns
result of the task specific exit method or TCMI_TASK_REMOVE_AND_LET_ME_GO
Definition at line 637 of file tcmi_task.c.
References tcmi_task_ops::exit, minfo, tcmi_task::ops, tcmi_method_wrapper_data(), TCMI_TASK, and TCMI_TASK_REMOVE_AND_LET_ME_GO.
Referenced by tcmi_mighooks_do_exit(), and tcmi_shadowtask_execve().
 {
     int res = TCMI_TASK_REMOVE_AND_LET_ME_GO;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     long *pcode, code;
     minfo(INFO3, "Doing exit");
     /* extract the exit code if any. */
     pcode = (long*)tcmi_method_wrapper_data(wr);
     code = (pcode ? *pcode : 0);
     minfo(INFO3, "Executing custom exit method");
     if (self_tsk->ops->exit)
         res = self_tsk->ops->exit(self_tsk, code);
     minfo(INFO3, "Executed custom exit method");
     return res;
 }
static long tcmi_task_exit_code (struct tcmi_task * self) inline static
<<public>> Exit code accessor.
Parameters
*self - pointer to this task instance
Returns
task exit code.
Definition at line 356 of file tcmi_task.h.
Referenced by tcmi_migcom_mig_mode_handler().
 {
     return self->exit_code;
 }
void tcmi_task_flush_and_submit_method (struct tcmi_task * self, tcmi_method_t * method, void * data, int size)
<<public>> Prior to submitting, atomically flushes the method queue.
<<public>> Prior to submitting, atomically flushes the method queue.
This operation must be atomic - under a queue lock, all methods are removed and a new wrapper is added to the method queue.
Parameters
*self - pointer to this task instance
*method - pointer to the method that is to be submitted
*data - argument for the submitted method
size - size of the argument in bytes
Definition at line 297 of file tcmi_task.c.
References __tcmi_queue_add(), __tcmi_queue_remove_entry, mdbg, tcmi_method_wrapper::node, self, tcmi_method_wrapper_new(), tcmi_method_wrapper_put(), tcmi_queue_empty(), tcmi_queue_lock(), and tcmi_queue_unlock().
Referenced by tcmi_shadowtask_execve(), tcmi_taskhelper_notify_by_pid(), tcmi_taskhelper_notify_current(), and tcmi_taskhelper_restart().
 {
     struct tcmi_method_wrapper *wr, *old_w;
     if (!(wr = tcmi_method_wrapper_new(method, data, size))) {
         mdbg(ERR3, "Can't create method wrapper");
         goto exit0;
     }
     tcmi_queue_lock(&self->method_queue);
     /* flush everything in the queue. */
     while (!tcmi_queue_empty(&self->method_queue)) {
         __tcmi_queue_remove_entry(&self->method_queue, old_w, node);
         tcmi_method_wrapper_put(old_w);
     }
     /* append the requested method into the queue. */
     __tcmi_queue_add(&self->method_queue, &wr->node);
     tcmi_queue_unlock(&self->method_queue);
     mdbg(INFO3, "Flushed method queue and submitted new method in atomic=%d", in_atomic());
  exit0:
     return;
 }
static struct tcmi_task* tcmi_task_get (struct tcmi_task * self) static read
<<public>> Instance accessor, increments the reference counter.
Parameters
*self - pointer to this task instance
Returns
tcmi_task instance
Definition at line 275 of file tcmi_task.h.
References self.
Referenced by tcmi_taskhelper_attach(), tcmi_taskhelper_attach_exclusive(), and tcmi_taskhelper_find_by_pid().
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static int tcmi_task_get_execve_count (struct tcmi_task * self) inline static
Definition at line 529 of file tcmi_task.h.
Referenced by tcmi_mighooks_execve().
 {
     return self->execve_count;
 }
static enum tcmi_task_type tcmi_task_get_type (struct tcmi_task * self) inline static
<<public>> Get task type
Parameters
*self - pointer to this task instance
Returns
(tcmi_task_type)shadow or (tcmi_task_type)guest (or unresolved if not defined).
Definition at line 624 of file tcmi_task.h.
References self.
Referenced by tcmi_mighooks_execve(), tcmi_taskhelper_attach(), and tcmi_taskhelper_attach_exclusive().
 {
     enum tcmi_task_type res = unresolved_type;
     if (self->ops->get_type)
         res = self->ops->get_type();
     return res;
 }
static u_int tcmi_task_hash (pid_t local_pid, u_int hashmask) inline static
<<public>> Computes the hash value of the task (to be used in tasks slotvec of migman)
Parameters
local_pid - local pid of the task
hashmask - hashmask limiting the maximum hash value.
Definition at line 638 of file tcmi_task.h.
Referenced by tcmi_migman_add_task(), and tcmi_migman_remove_task().
 {
     return (local_pid & hashmask);
 }
static void tcmi_task_inc_execve_count (struct tcmi_task * self) inline static
Definition at line 535 of file tcmi_task.h.
Referenced by tcmi_mighooks_execve().
 {
     self->execve_count++;
 }
int tcmi_task_init (struct tcmi_task * self, pid_t local_pid, struct tcmi_migman * migman, struct kkc_sock * sock, struct tcmi_ctlfs_entry * d_migproc, struct tcmi_ctlfs_entry * d_migman, struct tcmi_task_ops * ops)
Initializes the task.
Task initialization requires:
setting PID's (remote PID is set to 0 it will be updated once the migration is finished)
getting an extra reference to the communication socket
getting an extra reference to the associated migration manager
initializing method and message queues
create transaction slot vector
creating directory in migproc using the local PID as its name
creating symlink to the migration manager directory
creating remote PID TCMI ctlfs file
default exit code is set to 0, this might change when the guest task terminates and sends back its exit code.
setting all execve context to NULL (file, argv, envp)
initialize the completion synchronization element, so that the task instantiator (usually the migration component) can be notified when the task has been picked up by the associated process. Also reset the picked_up flag. This is used for atomic check if the task might have been pickedup short after the timeout.
setting operations for the specific task
Parameters
*self - this task instance
local_pid - local PID on CCN or PEN
migman - migration manager that maintains this task (can be null)
*sock - socket used for communication with guest task on PEN or shadow task on CCN resp.
*d_migproc - directory where ctlfs entries of migrated processes reside
*d_migman - TCMI ctlfs directory of the migration manager responsible for this task
*ops - task specific operations
Returns
0 upon success
Definition at line 114 of file tcmi_task.c.
References kkc_sock_get(), kkc_sock_put(), mdbg, minfo, self, tcmi_ctlfs_dir_new(), tcmi_ctlfs_entry_put(), tcmi_ctlfs_intfile_new(), tcmi_ctlfs_symlink_new(), tcmi_migman_add_task(), tcmi_migman_get(), tcmi_migman_put(), TCMI_PERMS_DIR, TCMI_PERMS_FILE_R, tcmi_queue_init(), tcmi_slotvec_hnew(), tcmi_slotvec_put(), tcmi_task_show_remote_pid(), and TRANSACTION_ORDER.
Referenced by tcmi_guesttask_new(), and tcmi_shadowtask_new().
 {
     int err = -EINVAL;
     self->local_pid = local_pid;
     self->migman = tcmi_migman_get(migman);
     self->remote_pid = 0;
     self->sock = kkc_sock_get(sock);
     self->execve_count = 0;
     self->peer_lost = 0;
     self->d_migman_root = d_migman;
     self->f_remote_pid_rev = NULL;
     tcmi_queue_init(&self->method_queue);
     tcmi_queue_init(&self->msg_queue);
     if (!ops) {
         mdbg(ERR3, "Missing task operations!");
         goto exit0;
     }
     if (!(self->transactions = tcmi_slotvec_hnew(TRANSACTION_ORDER))) {
         mdbg(ERR3, "Can't create transactions slotvector!");
         err = -ENOMEM;
         goto exit0;
     }
     if (!(self->d_task =
           tcmi_ctlfs_dir_new(d_migproc, TCMI_PERMS_DIR, "%d", local_pid))) {
         mdbg(ERR3, "Can't create migproc entry for %d", local_pid);
         goto exit1;
     }
     if (!(self->s_migman =
           tcmi_ctlfs_symlink_new(self->d_task, d_migman, "migman"))) {
         mdbg(ERR3, "Can't create symlink to migration manager for %d", local_pid);
         goto exit2;
     }
     if (!(self->f_remote_pid =
           tcmi_ctlfs_intfile_new(self->d_task, TCMI_PERMS_FILE_R,
                      self, tcmi_task_show_remote_pid, NULL,
                      sizeof(pid_t), "remote-pid"))) {
         mdbg(ERR3, "Can't create remote PID file entry for %d", local_pid);
         goto exit3;
     }
     if ( migman && tcmi_migman_add_task(migman, self) ) {
         mdbg(ERR3, "Can't add task to migman tasks struct: lpid %d", local_pid);
         goto exit4;
     }
     self->exit_code = 0;
     atomic_set(&self->ref_count, 1);
     self->ckpt_pathname = NULL;
     self->argv = NULL;
     self->envp = NULL;
     init_completion(&self->picked_up);
     self->picked_up_flag = 0;
     self->ops = ops;
     minfo(INFO4, "Initialized TCMI task PID=%d, %p", local_pid, self);
     return 0;
     /* error handling */
  exit4:
     tcmi_ctlfs_entry_put(self->f_remote_pid);
  exit3:
     tcmi_ctlfs_entry_put(self->s_migman);
  exit2:
     tcmi_ctlfs_entry_put(self->d_task);
  exit1:
     tcmi_slotvec_put(self->transactions);
  exit0:
     kkc_sock_put(self->sock);
     tcmi_migman_put(self->migman);
     return err;
 }
static pid_t tcmi_task_local_pid (struct tcmi_task * self) inline static
<<public>> Local PID accessor.
Parameters
*self - pointer to this task instance
Returns
local PID of the task
Definition at line 411 of file tcmi_task.h.
Referenced by kill_all_tasks(), tcmi_guesttask_migrateback_p(), tcmi_guesttask_post_fork(), tcmi_guesttask_process_msg(), tcmi_guesttask_process_p_emigrate_msg(), tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_migcom_guest_fork(), tcmi_migcom_immigrate(), tcmi_migcom_shadow_fork(), tcmi_migman_add_task(), tcmi_migman_deliver_msg(), tcmi_migman_remove_task(), tcmi_penmigman_migrate_all_home(), tcmi_shadowtask_emigrate_p(), tcmi_shadowtask_migrateback_ppm_p(), tcmi_shadowtask_process_msg(), tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg(), tcmi_shadowtask_verify_migration(), tcmi_task_deliver_msg(), tcmi_task_emigrate_npm(), tcmi_task_emigrate_ppm_p(), tcmi_task_emigrate_ppm_v(), tcmi_task_migrateback_npm(), tcmi_task_migrateback_ppm_p(), tcmi_task_migrateback_ppm_v(), tcmi_task_prepare_execve(), tcmi_task_put(), tcmi_task_release_execve_context(), tcmi_task_show_remote_pid_rev(), tcmi_task_to_task_struct(), tcmi_taskhelper_attach(), tcmi_taskhelper_attach_exclusive(), tcmi_taskhelper_enter_mig_mode(), tcmi_taskhelper_sanity_check(), and tcmi_taskhelper_wait_for_pick_up_timeout().
 {
     return self->local_pid;
 }
u_int32_t tcmi_task_migman_id (struct tcmi_task * self)
<<public>> Accessor of id of the migration manager associated with this task.
Parameters
*self - pointer to this task instance
Returns
migration manager id
Definition at line 936 of file tcmi_task.c.
References self, and tcmi_migman_id().
Referenced by tcmi_migman_deliver_msg().
 {
     return self->migman ? tcmi_migman_id(self->migman) : -1;
 }
u_int tcmi_task_migman_slot_index (struct tcmi_task * self)
<<public>> Accessor of vector slot index of the migration manager associated with this task.
Definition at line 944 of file tcmi_task.c.
References self, and tcmi_migman_slot_index().
Referenced by tcmi_man_fork().
{
     return self->migman ? tcmi_migman_slot_index(self->migman) : -1;
 }
int tcmi_task_migrateback_npm (void * self, struct tcmi_method_wrapper * wr)
<<public>> Migrates a task back to CCN - NPM.
<<public>> Migrates a task back to CCN - NPM.
work is delegated to the task specific emigrate method.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the task specific migrate back method or TCMI_TASK_KEEP_PUMPING
Definition at line 607 of file tcmi_task.c.
References mdbg, tcmi_task_ops::migrateback_npm, tcmi_task::ops, tcmi_method_wrapper_data(), TCMI_TASK, TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), and tcmi_task_remote_pid().
Referenced by tcmi_penman_migrateback_npm().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     struct tcmi_npm_params* npm_params = tcmi_method_wrapper_data(wr);
     mdbg(INFO3, "Task - local pid %d, remote pid %d, migrating back",
          tcmi_task_local_pid(self_tsk), tcmi_task_remote_pid(self_tsk));
     if (self_tsk->ops->migrateback_npm)
         res = self_tsk->ops->migrateback_npm(self_tsk, npm_params);
     return res;
 }
int tcmi_task_migrateback_ppm_p (void * self, struct tcmi_method_wrapper * wr)
<<public>> Migrates a task back to CCN - PPM w/ physical checkpoint.
<<public>> Migrates a task back to CCN - PPM w/ physical checkpoint.
All the work is delegated to the task specific emigrate method.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the task specific migrate back method or TCMI_TASK_KEEP_PUMPING
Definition at line 511 of file tcmi_task.c.
References mdbg, tcmi_task_ops::migrateback_ppm_p, tcmi_task::ops, TCMI_TASK, TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), and tcmi_task_remote_pid().
Referenced by tcmi_migcom_migrate_home_ppm_p().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     mdbg(INFO3, "Task - local pid %d, remote pid %d, migrating back",
          tcmi_task_local_pid(self_tsk), tcmi_task_remote_pid(self_tsk));
     if (self_tsk->ops->migrateback_ppm_p)
         res = self_tsk->ops->migrateback_ppm_p(self_tsk);
     return res;
 }
int tcmi_task_migrateback_ppm_v (void * self, struct tcmi_method_wrapper * wr)
<<public>> Migrates a task back to CCN - PPM w/ virtual checkpoint.
<<public>> Migrates a task back to CCN - PPM w/ virtual checkpoint.
All the work is delegated to the task specific emigrate method.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the task specific migrate back method or TCMI_TASK_KEEP_PUMPING
Definition at line 559 of file tcmi_task.c.
References mdbg, tcmi_task_ops::migrateback_ppm_v, tcmi_task::ops, TCMI_TASK, TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), and tcmi_task_remote_pid().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     mdbg(INFO3, "Task - local pid %d, remote pid %d, migrating back",
          tcmi_task_local_pid(self_tsk), tcmi_task_remote_pid(self_tsk));
     if (self_tsk->ops->migrateback_ppm_v)
         res = self_tsk->ops->migrateback_ppm_v(self_tsk);
     return res;
 }
static void tcmi_task_pick_up (struct tcmi_task * self) inline static
<<public>> Signals, the tcmi task has been pickedup by the associated process.n
Parameters
*self - pointer to this task instance
Returns
0 when successfully completed
Definition at line 496 of file tcmi_task.h.
References self.
Referenced by tcmi_taskhelper_sanity_check().
 {
     complete(&self->picked_up);
     self->picked_up_flag = 1;
 }
static int tcmi_task_picked_up (struct tcmi_task * self) inline static
<<public>> Checks whether the task has been picked up.
Parameters
*self - pointer to this task instance
Returns
true when it has already been picked up
Definition at line 509 of file tcmi_task.h.
Referenced by tcmi_taskhelper_sanity_check(), and tcmi_taskhelper_wait_for_pick_up_timeout().
 {
     return self->picked_up_flag > 0;
 }
int tcmi_task_prepare_execve (struct tcmi_task * self, char * file, char ** argv, char ** envp)
<<public>> Prepares execution of a file given the arrays of arguments and environment.
Allocates memory for all execve parameters and copies the parameters into the instance. The main purpose of this method is setup everything for execve. After using this method, the caller is able to release all memory resources and issue tcmi_task_execve().
To reduce the overhead when releasing the argv/envp arrays of the task, the layout of each array is as follows. All strings are put at the end of the array.
+-------------+
| pointer  0  |--+
+-------------+  |
| pointer  1  |--------------------+
+-------------+  |                 |
.             .  |                 |
.             .  |                 |
+-------------+  |                 |
| pointer  n  |---------------------------------------------+
+-------------+  |                 |                        |
| NULL        |  |                 |                        |
+-------------+--V-----------------V------------------------V----------+
| "string 0 goes up here\0", "string 1 here\0", ..., "string n here\0" |
+----------------------------------------------------------------------+
This code can be used to printout the argv/envp arrays for testing.
   int i;
   mdbg(INFO3, "Environ test");
   for(i = 0; self->argv[i] != NULL; i++)
    mdbg(INFO3, "ARGV[%d]='%s'", i, self->argv[i]);
   for(i = 0; self->envp[i] != NULL; i++)
    mdbg(INFO3, "ENVP[%d]='%s'", i, self->envp[i]);
Parameters
*self - pointer to this task instance
*file
**argv - arguments list terminated by NULL
**envp - environment strings terminated by NULL
Returns
0 upon success, otherwise -ENOEXEC
Definition at line 757 of file tcmi_task.c.
References mdbg, self, tcmi_task_copy_strings(), tcmi_task_local_pid(), and tcmi_task_release_execve_context().
Referenced by tcmi_taskhelper_checkpoint(), and tcmi_taskhelper_restart().
 {
     /* release the old context first. */
     tcmi_task_release_execve_context(self);
     if (!(self->ckpt_pathname = (char*)kmalloc(strlen(file) + 1, GFP_ATOMIC))) {
         mdbg(ERR3, "Can't allocate memory for execve file '%s'", file);
         goto exit0;
     }
     strcpy(self->ckpt_pathname, file);
     if (tcmi_task_copy_strings(&self->argv, argv) < 0) {
         mdbg(ERR3, "Failed copying ARGV array for file '%s'", file);
         goto exit1;
     }
     if (tcmi_task_copy_strings(&self->envp, envp) < 0) {
         mdbg(ERR3, "Failed copying ENVP array for file '%s'", file);
         goto exit2;
     }
     mdbg(INFO4, "Allocated TCMI task execve context(%s, %p, %p) PID=%d, %p",
          self->ckpt_pathname, self->argv, self->envp, tcmi_task_local_pid(self), self);
     return 0;
     /* error handling */
  exit2:
     kfree(self->argv);
     self->argv = NULL;
  exit1:
     kfree(self->ckpt_pathname);
     self->ckpt_pathname = NULL;
  exit0:
     return -ENOEXEC;
 }
int tcmi_task_process_methods (struct tcmi_task * self)
<<public>> Processes all methods in the queue.
This method is used as a method pump, it keeps on unwrapping methods from the queue and executing them until one of them returns a results different from TCMI_TASK_KEEP_PUMPING. This result is communicated to the component that controls this particular task (usually the migration component). Every iteration, the signals are also handled. This might also influence the method pump and terminate it.
The method wrapper is released once the method is executed only if there was no execve problem. To explain this: some methods perform an execve operation - in which case, the execution context changes immediately. Therefore, these methods have to discard the method wrapper on their own. Should the execve fail, they have already discarded the wrapper and thus have on control over it. In that case, the returned error is TCMI_TASK_EXECVE_FAILED_KILL_ME and we have to prevent releasing this method wrapper.
The specific task method that had been executed had a chance to get an extra reference and resubmit the method wrapper into the method queue.
Parameters
*self - pointer to this task instance
Returns
result of the last executed method
Definition at line 348 of file tcmi_task.c.
References mdbg, tcmi_method_wrapper::node, self, tcmi_method_wrapper_call(), tcmi_method_wrapper_put(), tcmi_queue_empty(), tcmi_queue_remove_entry, TCMI_TASK_EXECVE_FAILED_KILL_ME, TCMI_TASK_KEEP_PUMPING, and tcmi_taskhelper_do_signals().
Referenced by tcmi_migcom_mig_mode_handler().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_method_wrapper *w;
     while ((!tcmi_queue_empty(&self->method_queue)) &&
            (res == TCMI_TASK_KEEP_PUMPING)) {
         /* handle any pending signals */
         if ((res = tcmi_taskhelper_do_signals(self)) != TCMI_TASK_KEEP_PUMPING)
             break;
         /* get next method to proces */
         tcmi_queue_remove_entry(&self->method_queue, w, node);
         /* unwrap & destroy the method wrapper excluding the execve failure */
         if ((res = tcmi_method_wrapper_call(w, self)) !=
             TCMI_TASK_EXECVE_FAILED_KILL_ME) {
             mdbg(INFO3, "Execve have NOT failed.");
             tcmi_method_wrapper_put(w);
         } else {
             mdbg(INFO3, "Execve have failed.");
         }
     }
     mdbg(INFO3, "Process methods finished with res %d", res);
     return res;
 }
int tcmi_task_process_msg (void * self, struct tcmi_method_wrapper * wr)
<<public>> Processes message in the message queue.
<<public>> Processes message in the message queue.
Waits for the message to arrive or a signal to wake us up.
Upon message arrival, the message is processed (delegated to the task specific method if any) and discarded.
Eventually, the method resubmits itself into the method queue reusing the method wrapper iff the result of the message processing is TCMI_TASK_KEEP_PUMPING.
Optionally, this method can take an integer argument (argument to wrapper). This argument specifies, whether we should be waiting for new messages, if there is no message, or not. By default, this method waits for messages and in the end it resubmits itself. If wait for messages is false, and there are no messages this method returns.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the last executed method
Definition at line 400 of file tcmi_task.c.
References mdbg, tcmi_task::msg_queue, tcmi_task::node, tcmi_task::ops, tcmi_task_ops::process_msg, tcmi_method_wrapper_data(), tcmi_method_wrapper_get(), tcmi_msg_id(), tcmi_msg_put(), tcmi_queue_empty(), tcmi_queue_remove_entry, tcmi_queue_wait_on_empty_interruptible(), TCMI_TASK, and TCMI_TASK_KEEP_PUMPING.
Referenced by tcmi_migcom_immigrate(), tcmi_migcom_shadow_fork(), tcmi_shadowtask_emigrate_p(), and tcmi_task_deliver_msg().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     int err;
     struct tcmi_msg *m; /* message that is being processed */
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     int wait_for_messages = 1;
     if ( tcmi_method_wrapper_data(wr) ) {
         wait_for_messages = *(int*)tcmi_method_wrapper_data(wr);
     }
     // No msgs and we do not want to wait?
     if ( !wait_for_messages && tcmi_queue_empty(&self_tsk->msg_queue) )
         return res;
     if ((err = tcmi_queue_wait_on_empty_interruptible(&self_tsk->msg_queue)) < 0) {
         mdbg(INFO3, "Signal arrived %d", err);
         goto exit0;
     }
     tcmi_queue_remove_entry(&self_tsk->msg_queue, m, node);
     /* process the message that has arrived */
     if (m) {
         mdbg(INFO3, "Processing message..%x", tcmi_msg_id(m));
         if (self_tsk->ops->process_msg)
             res = self_tsk->ops->process_msg(self_tsk, m);
         /* discard the mesage*/
         tcmi_msg_put(m);
     }
  exit0:
     /* resubmit the process_msg method. */
     if (res == TCMI_TASK_KEEP_PUMPING) {
         /* This is to have an extra reference for resubmitting */
         tcmi_method_wrapper_get(wr);
         /* resubmit the method. */
         tcmi_task_add_wrapper(self_tsk, wr);
     }
     return res;
 }
void tcmi_task_put (struct tcmi_task * self)
<<public>> Releases the instance.
calls custom free method for a specific task
destroys all ctlfs files, directories, symlinks
destroys the transaction slot vector
empties the message queue
empties the method queue
releases the execve context (execve filename, argv, envp)
Parameters
*self - pointer to this task instance
Definition at line 211 of file tcmi_task.c.
References kkc_sock_put(), mdbg, minfo, tcmi_method_wrapper::node, self, tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), tcmi_method_wrapper_put(), tcmi_migman_put(), tcmi_migman_remove_task(), tcmi_msg_id(), tcmi_msg_put(), tcmi_queue_empty(), tcmi_queue_remove_entry, tcmi_slotvec_empty(), tcmi_slotvec_put(), tcmi_task_local_pid(), and tcmi_task_release_execve_context().
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_migcom_guest_fork(), tcmi_migcom_immigrate(), tcmi_migcom_mig_mode_handler(), tcmi_migcom_shadow_fork(), tcmi_migman_deliver_msg(), tcmi_taskhelper_notify_by_pid(), and tcmi_taskhelper_wait_for_pick_up_timeout().
 {
     /* Used for destruction of messages and methods. */
     struct tcmi_msg *m;
     struct tcmi_method_wrapper *w;
     if (self && atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying TCMI task PID=%d, %p",
              tcmi_task_local_pid(self), self);
         /* instance specific free method */
         if (self->ops->free)
             self->ops->free(self);
         kkc_sock_put(self->sock);
         /* destroy all ctlfs entries */
         tcmi_ctlfs_file_unregister(self->f_remote_pid);
         tcmi_ctlfs_entry_put(self->f_remote_pid);
         tcmi_ctlfs_entry_put(self->s_migman);
         tcmi_ctlfs_entry_put(self->d_task);
         tcmi_ctlfs_entry_put(self->f_remote_pid_rev);
         if (!tcmi_slotvec_empty(self->transactions))
             mdbg(WARN2, "Task %d, destroying non-empty transactions slotvector!!",
                  self->local_pid);
         tcmi_slotvec_put(self->transactions);
         /* destroy remaining messages in the queue. */
         while (!tcmi_queue_empty(&self->msg_queue)) {
             tcmi_queue_remove_entry(&self->msg_queue, m, node);
             mdbg(INFO3, "Task %d, destroying message %x",
                  tcmi_task_local_pid(self), tcmi_msg_id(m));
             tcmi_msg_put(m);
         }
         /* destroy remaining methods in the queue. */
         while (!tcmi_queue_empty(&self->method_queue)) {
             tcmi_queue_remove_entry(&self->method_queue, w, node);
             mdbg(INFO3, "Task %d, destroying method wrapper %p",
                  tcmi_task_local_pid(self), w);
             tcmi_method_wrapper_put(w);
         }
         minfo(INFO3, "Releasing execve context");
         tcmi_task_release_execve_context(self);
         minfo(INFO3, "Done..");
         tcmi_migman_remove_task(self->migman, self);
         minfo(INFO3, "Removed from migman tasks done");
         tcmi_migman_put(self->migman);
         kfree(self);
     }
 }
static void tcmi_task_release_execve_context (struct tcmi_task * self) static
<<private>> Releases the execve context (execve file, argv, envp) Since the argv/envp have allocated a linear chunks of memory (including all strings) we need to issue only 1 kfree/vfree for each and don't need to scan the array releasing each string separate.
Releasing is atomic as this method is also used when preparing a new execve context (tcmi_task_prepare_execve()).
Parameters
*self - pointer to this task instance
Definition at line 875 of file tcmi_task.c.
References mdbg, self, and tcmi_task_local_pid().
Referenced by tcmi_task_prepare_execve(), and tcmi_task_put().
 {
     char *tmp1, **tmp2;
     mdbg(INFO4, "Destroying TCMI task execve context(%p, %p, %p) PID=%d, %p",
          self->ckpt_pathname, self->argv, self->envp, tcmi_task_local_pid(self), self);
     tmp1 = self->ckpt_pathname;
     self->ckpt_pathname = NULL;
     kfree(tmp1);
     tmp2 = self->argv;
     self->argv = NULL;
     kfree(tmp2);
     tmp2 = self->envp;
     self->envp = NULL;
     kfree(tmp2);
 }
static pid_t tcmi_task_remote_pid (struct tcmi_task * self) inline static
<<public>> Remote PID accessor.
Parameters
*self - pointer to this task instance
Returns
remote PID of the task
Definition at line 422 of file tcmi_task.h.
Referenced by tcmi_guesttask_exit(), tcmi_guesttask_migrateback_p(), tcmi_guesttask_post_fork(), tcmi_guesttask_post_fork_set_tid(), tcmi_guesttask_process_p_emigrate_msg(), tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_get_response(), tcmi_shadowtask_do_signal(), tcmi_shadowtask_migrateback_ppm_p(), tcmi_shadowtask_process_msg(), tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg(), tcmi_syscall_hooks_sys_getpid(), tcmi_task_emigrate_npm(), tcmi_task_emigrate_ppm_p(), tcmi_task_emigrate_ppm_v(), tcmi_task_migrateback_npm(), tcmi_task_migrateback_ppm_p(), tcmi_task_migrateback_ppm_v(), and tcmi_task_show_remote_pid().
 {
     return self->remote_pid;
 }
static int tcmi_task_send_and_receive_msg (struct tcmi_task * self, struct tcmi_msg * req, struct tcmi_msg ** resp) inline static
<<public>> Sends a specified message and waits for a response.
All work is delegate to tcmi_msg.c::tcmi_msg_send_and_receive() method
Parameters
*self - pointer to this task instance
*req - request message to be sent.
**resp - output parameter, stores the response message or NULL
Returns
0 when the message has been sent.
Definition at line 567 of file tcmi_task.h.
References self, and tcmi_msg_send_and_receive().
Referenced by tcmi_rpcresp_procmsg_get_response(), and tcmi_shadowtask_emigrate_p().
 {
     return tcmi_msg_send_and_receive(req, self->sock, resp);
 }
static int tcmi_task_send_anonymous_msg (struct tcmi_task * self, struct tcmi_msg * m) inline static
<<public>> Sends a specified message.
The message is sent as anonymous, so that any potential responses will be delivered to the message queue.
Parameters
*self - pointer to this task instance
*m - message to be sent.
Returns
0 when the message has been successfully sent
Definition at line 524 of file tcmi_task.h.
References self, and tcmi_msg_send_anonymous().
Referenced by tcmi_guesttask_exit(), tcmi_guesttask_migrateback_p(), tcmi_guesttask_post_fork(), tcmi_guesttask_process_p_emigrate_msg(), tcmi_mighooks_execve(), tcmi_shadowtask_migrateback_ppm_p(), tcmi_shadowtask_process_msg(), and tcmi_task_send_message().
 {
     return tcmi_msg_send_anonymous(m, self->sock);
 }
int tcmi_task_send_message (void * self, struct tcmi_method_wrapper * wr)
<<public>> Sends a message to peer.
<<public>> Sends a message to peer.
The method is primarily designed for retransmission of messages in case the original transimision failed due to pending signals.
Parameters
*self - pointer to this task instance
*wr - method wrapper used to store the method in the method queue
Returns
result of the task specific emigrate method or TCMI_TASK_KEEP_PUMPING
Definition at line 452 of file tcmi_task.c.
References mdbg, minfo, resp, tcmi_method_wrapper_data(), tcmi_msg_get(), tcmi_msg_put(), TCMI_TASK, TCMI_TASK_KEEP_PUMPING, tcmi_task_send_anonymous_msg(), tcmi_task_send_message(), and tcmi_task_submit_method().
Referenced by tcmi_shadowtask_process_msg(), and tcmi_task_send_message().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     int send_res;
     struct tcmi_task *self_tsk = TCMI_TASK(self);
     struct tcmi_msg *resp = *((struct tcmi_msg**)tcmi_method_wrapper_data(wr));
     //ERESTARTSYS
     send_res = tcmi_task_send_anonymous_msg(self_tsk, resp);
     if ( send_res == -ERESTARTSYS ) {
       minfo(ERR3, "Signal arrived while sending message, will retransmit later.");
       tcmi_msg_get(resp);
       tcmi_task_submit_method(self, tcmi_task_send_message, resp, sizeof(struct tcmi_msg));
     } else if ( send_res != 0 ) {
       minfo(ERR3, "Sending of message has failed with error: %d. The message will NOT be retransmitted.", send_res);
     } else {
       mdbg(INFO3, "Message send");
     }
     tcmi_msg_put( resp );
     return res;
 }
static void tcmi_task_set_context (struct tcmi_task * self, void * context) inline static
<<public>> Process context setter.
Parameters
*self - pointer to this task instance
*context - pointer to the context stored in the task
Definition at line 389 of file tcmi_task.h.
Referenced by tcmi_taskhelper_do_mig_mode().
 {
     self->context = context;
 }
static void tcmi_task_set_exit_code (struct tcmi_task * self, long code) inline static
<<public>> Exit code setter.
Parameters
*self - pointer to this task instance
code - exit code that is to be set for the task
Definition at line 367 of file tcmi_task.h.
Referenced by tcmi_guesttask_do_signal(), and tcmi_shadowtask_process_msg().
 {
     self->exit_code = code;
 }
static void tcmi_task_set_local_pid (struct tcmi_task * self, pid_t local_pid) inline static
<<public>> Local PID setter.
Parameters
*self - pointer to this task instance
local_pid - new local PID of the task
Definition at line 433 of file tcmi_task.h.
 {
     self->local_pid = local_pid;
 }
static void tcmi_task_set_remote_pid (struct tcmi_task * self, pid_t remote_pid) inline static
<<public>> Remote PID setter.
Parameters
*self - pointer to this task instance
remote_pid - new remote PID of the task
Definition at line 453 of file tcmi_task.h.
References tcmi_task::remote_pid, self, tcmi_ctlfs_intfile_new(), TCMI_PERMS_FILE_R, and tcmi_task_show_remote_pid_rev().
Referenced by tcmi_guesttask_post_fork(), tcmi_guesttask_process_p_emigrate_msg(), tcmi_shadowtask_process_msg(), and tcmi_shadowtask_verify_migration().
 {
     self->remote_pid = remote_pid;
     self->f_remote_pid_rev = tcmi_ctlfs_intfile_new(self->d_migman_root, TCMI_PERMS_FILE_R,
                                      self, tcmi_task_show_remote_pid_rev, NULL,
                                      sizeof(pid_t),"%d" , self->remote_pid);
 }
static int tcmi_task_show_remote_pid (void * obj, void * data) static
<<private>> Read method for the TCMI ctlfs - reports remote PID.
For a shadow process, the remote PID is the identifier of the guest process on PEN and vica versa.
Parameters
*obj - pointer to this task instance
*data - pointer where the PID is to be stored.
Returns
0 upon success
Definition at line 854 of file tcmi_task.c.
References tcmi_task::remote_pid, TCMI_TASK, and tcmi_task_remote_pid().
Referenced by tcmi_task_init().
 {
     struct tcmi_task *self = TCMI_TASK(obj);
     int *remote_pid = (int*) data;
     *remote_pid = tcmi_task_remote_pid(self);
     return 0;
 }
static int tcmi_task_show_remote_pid_rev (void * obj, void * data) static
Definition at line 439 of file tcmi_task.h.
References tcmi_task::local_pid, TCMI_TASK, and tcmi_task_local_pid().
Referenced by tcmi_task_set_remote_pid().
 {
     struct tcmi_task *self = TCMI_TASK(obj);
     int * local_pid = (int*) data;
     *local_pid = tcmi_task_local_pid(self);
     return 0;
 }
static void tcmi_task_signal_peer_lost (struct tcmi_task * self) inline static
Notifies task that it peer is lost and sends a kill signal to that task.
The method is used for termination of tasks with lost peers.
Definition at line 577 of file tcmi_task.h.
References tcmi_task_to_task_struct().
Referenced by kill_all_tasks(), and tcmi_task_check_peer_lost().
{
       self->peer_lost = 1;
       force_sig(SIGKILL, tcmi_task_to_task_struct(self));
 }
void tcmi_task_submit_method (struct tcmi_task * self, tcmi_method_t * method, void * data, int size)
<<public>> Submits a method for execution.
Creates a new method wrapper with the specified data and delegates all work to tcmi_task_add_wrapper
Parameters
*self - pointer to this task instance
*method - pointer to the method that is to be submitted
*data - argument for the submitted method
size - size of the argument in bytes
Definition at line 272 of file tcmi_task.c.
References mdbg, and tcmi_method_wrapper_new().
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_migcom_guest_fork(), tcmi_migcom_immigrate(), tcmi_migcom_shadow_fork(), tcmi_penman_migrateback_npm(), tcmi_shadowtask_emigrate_p(), tcmi_shadowtask_process_msg(), tcmi_task_deliver_msg(), tcmi_task_send_message(), tcmi_taskhelper_notify_by_pid(), and tcmi_taskhelper_notify_current().
 {
     struct tcmi_method_wrapper *wr;
     if (!(wr = tcmi_method_wrapper_new(method, data, size))) {
         mdbg(ERR3, "Can't create method wrapper");
         goto exit0;
     }
     tcmi_task_add_wrapper(self, wr);
  exit0:
     return;
 }
static struct task_struct* tcmi_task_to_task_struct (struct tcmi_task * self) static read
Returns a task_struct associated with the tcmi_task.
Definition at line 542 of file tcmi_task.h.
References mdbg, task_find_by_pid(), and tcmi_task_local_pid().
Referenced by tcmi_task_signal_peer_lost(), and tcmi_taskhelper_enter_mig_mode().
{
     struct task_struct *task;
     /* try finding the target kernel task for our TCMI task by PID */
     read_lock_irq(&tasklist_lock);
     if (!(task = task_find_by_pid(tcmi_task_local_pid(self)))) {
         mdbg(ERR3, "Can't find corresponding task_struct for PID: %d",
              tcmi_task_local_pid(self));
     }
     read_unlock_irq(&tasklist_lock);
     return task;
 }
static struct tcmi_slotvec* tcmi_task_transactions (struct tcmi_task * self) static read
<<public>> Transactions accessor - needed when tasks construct their own messages.
Parameters
*self - pointer to this task instance
Returns
transactions slot vector.
Definition at line 344 of file tcmi_task.h.
Referenced by tcmi_rpcresp_procmsg_get_response(), and tcmi_shadowtask_emigrate_p().
 {
     return self->transactions;
 }
static unsigned long tcmi_task_wait_for_pick_up_timeout (struct tcmi_task * self, unsigned long timeout) inline static
<<public>> Waits until the task is picked up, by the associated process.
Returns also when the timer expires. This method is meant to be used by the task helper, that provides tcmi_taskhelper_wait_for_pickup_timeout() .
Parameters
*self - pointer to this task instance
timeout - time out limit in ticks to wait for pickup
Returns
0 when successfully completed
Definition at line 483 of file tcmi_task.h.
References self.
Referenced by tcmi_taskhelper_wait_for_pick_up_timeout().
 {
     return wait_for_completion_interruptible_timeout(&self->picked_up, timeout);
 }