Clondike: tcmi_ckpt_mm class
tcmi_ckpt_mm class
tcmi_ckpt class
This is a <<singleton>> that takes care of (re)storing a process memory descriptor.
Data Structures
struct tcmi_ckpt_mm_hdr
Compound structure describes a process memory descriptor.
struct tcmi_sigset
struct tcmi_k_sigaction
struct tcmi_ckpt_sig_hdr
Compound structure describes a process memory descriptor.
Functions
struct tcmi_ckpt_mm_hdr __attribute__ ((__packed__))
static int tcmi_ckpt_mm_write (struct tcmi_ckpt *ckpt)
Writes a current process memory descriptor into the checkpoint file.
static int tcmi_ckpt_mm_read (struct tcmi_ckpt *ckpt)
Reads a memory area from the checkpoint file and sets the those in the memory descriptor.
static int tcmi_ckpt_sig_write (struct tcmi_ckpt *ckpt)
Writes a current process memory descriptor into the checkpoint file.
static int tcmi_ckpt_sig_read (struct tcmi_ckpt *ckpt)
Reads a memory area from the checkpoint file and sets the those in the memory descriptor.
Detailed Description
This is a <<singleton>> that takes care of (re)storing a process memory descriptor.
Data Structure Documentation
struct tcmi_ckpt_mm_hdr
Compound structure describes a process memory descriptor.
Explanation if individual items is e.g. in Understanding the Linux Kernel(chapter 8)
Definition at line 56 of file tcmi_ckpt_mm.h.
Data Fields
u_int64_t arg_end
u_int64_t arg_start arguments and environment.
u_int64_t brk
u_int64_t def_flags default access flags of the memory regions.
u_int64_t end_code
u_int64_t end_data
u_int64_t env_end
u_int64_t env_start
u_int64_t start_brk heap and stack.
u_int64_t start_code code section, data section.
u_int64_t start_data
u_int64_t start_stack
struct tcmi_sigset
Definition at line 51 of file tcmi_ckpt_sig.h.
Data Fields
u_int64_t sigs
struct tcmi_k_sigaction
Definition at line 56 of file tcmi_ckpt_sig.h.
Data Fields
u_int64_t sa_flags
u_int64_t sa_handler
struct tcmi_sigset sa_mask
u_int64_t sa_restorer
struct tcmi_ckpt_sig_hdr
Compound structure describes a process memory descriptor.
Explanation if individual items is e.g. in Understanding the Linux Kernel(chapter 8)
Definition at line 67 of file tcmi_ckpt_sig.h.
Data Fields
struct tcmi_k_sigaction action[_NSIG] Signal actions.
struct tcmi_sigset blocked Blocked signals.
struct tcmi_sigset real_blocked Blocked signals.
u_int64_t sas_ss_size Alternative signal handler stack size.
u_int64_t sas_ss_sp Ponter to alternative signal handler stack.
Function Documentation
struct tcmi_ckpt_mm_hdr __attribute__ ((__packed__))
static int tcmi_ckpt_mm_read (struct tcmi_ckpt * ckpt) inline static
Reads a memory area from the checkpoint file and sets the those in the memory descriptor.
This also assumes that the old execution context has already been flushed by the caller.
Parameters
*ckpt - checkpoint file where the area is to be stored
Returns
0 upon success.
Definition at line 122 of file tcmi_ckpt_mm.h.
References tcmi_ckpt_mm_hdr::arg_end, tcmi_ckpt_mm_hdr::arg_start, tcmi_ckpt_mm_hdr::brk, CHECKED_UINT64_TO_ULONG, tcmi_ckpt_mm_hdr::def_flags, tcmi_ckpt_mm_hdr::end_code, tcmi_ckpt_mm_hdr::end_data, tcmi_ckpt_mm_hdr::env_end, tcmi_ckpt_mm_hdr::env_start, mdbg, tcmi_ckpt_mm_hdr::start_brk, tcmi_ckpt_mm_hdr::start_code, tcmi_ckpt_mm_hdr::start_data, tcmi_ckpt_mm_hdr::start_stack, and tcmi_ckpt_read().
Referenced by tcmi_ckptcom_restart().
 {
     struct tcmi_ckpt_mm_hdr mm_hdr;
     /* write the header into the checkpoint */
     if (tcmi_ckpt_read(ckpt, &mm_hdr, sizeof(mm_hdr)) < 0) {
         mdbg(ERR3, "Error reading memory descriptor header");
         goto exit0;
     }
         current->mm->start_code  = CHECKED_UINT64_TO_ULONG(mm_hdr.start_code);
         current->mm->end_code    = CHECKED_UINT64_TO_ULONG(mm_hdr.end_code);
         current->mm->start_data  = CHECKED_UINT64_TO_ULONG(mm_hdr.start_data);
         current->mm->end_data    = CHECKED_UINT64_TO_ULONG(mm_hdr.end_data);
         current->mm->start_brk   = CHECKED_UINT64_TO_ULONG(mm_hdr.start_brk);
         current->mm->brk         = CHECKED_UINT64_TO_ULONG(mm_hdr.brk);
         current->mm->start_stack = CHECKED_UINT64_TO_ULONG(mm_hdr.start_stack);
         current->mm->arg_start   = CHECKED_UINT64_TO_ULONG(mm_hdr.arg_start);
         current->mm->arg_end     = CHECKED_UINT64_TO_ULONG(mm_hdr.arg_end);
         current->mm->env_start   = CHECKED_UINT64_TO_ULONG(mm_hdr.env_start);
         current->mm->env_end     = CHECKED_UINT64_TO_ULONG(mm_hdr.env_end);
         current->mm->def_flags   = CHECKED_UINT64_TO_ULONG(mm_hdr.def_flags);
     /* no regions left as they all have been flushed */
     current->mm->mmap = NULL;
     mdbg(INFO4, "Read memory descriptor:");
     mdbg(INFO4, "START CODE :      %08lx", current->mm->start_code);
     mdbg(INFO4, "END CODE   :      %08lx", current->mm->end_code);
     mdbg(INFO4, "START DATA :      %08lx", current->mm->start_data);
     mdbg(INFO4, "END DATA   :      %08lx", current->mm->end_data);
     mdbg(INFO4, "START BRK  :      %08lx", current->mm->start_brk);
     mdbg(INFO4, "BRK        :      %08lx", current->mm->brk);
     mdbg(INFO4, "START STACK:      %08lx", current->mm->start_stack);
     mdbg(INFO4, "ARG START:      %08lx", current->mm->arg_start);
     mdbg(INFO4, "ARG END:      %08lx", current->mm->arg_end);
     mdbg(INFO4, "ENV START:      %08lx", current->mm->env_start);
     mdbg(INFO4, "ENV END:      %08lx", current->mm->env_end);
     mdbg(INFO4, "DEF FLAGS:      %08lx", current->mm->def_flags);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_mm_write (struct tcmi_ckpt * ckpt) inline static
Writes a current process memory descriptor into the checkpoint file.
Parameters
*ckpt - checkpoint file where the area is to be stored
Returns
0 upon success.
Definition at line 74 of file tcmi_ckpt_mm.h.
References tcmi_ckpt_mm_hdr::arg_end, tcmi_ckpt_mm_hdr::arg_start, tcmi_ckpt_mm_hdr::brk, tcmi_ckpt_mm_hdr::def_flags, tcmi_ckpt_mm_hdr::end_code, tcmi_ckpt_mm_hdr::end_data, tcmi_ckpt_mm_hdr::env_end, tcmi_ckpt_mm_hdr::env_start, mdbg, tcmi_ckpt_mm_hdr::start_brk, tcmi_ckpt_mm_hdr::start_code, tcmi_ckpt_mm_hdr::start_data, tcmi_ckpt_mm_hdr::start_stack, and tcmi_ckpt_write().
Referenced by tcmi_ckptcom_checkpoint().
 {
     struct tcmi_ckpt_mm_hdr mm_hdr;
         /* Now we dump the memory mapping */
         mm_hdr.start_code  = current->mm->start_code;
         mm_hdr.end_code    = current->mm->end_code;
         mm_hdr.start_data  = current->mm->start_data;
         mm_hdr.end_data    = current->mm->end_data;
         mm_hdr.start_brk   = current->mm->start_brk;
         mm_hdr.brk         = current->mm->brk;
         mm_hdr.start_stack = current->mm->start_stack;
         mm_hdr.arg_start   = current->mm->arg_start;
         mm_hdr.arg_end     = current->mm->arg_end;
         mm_hdr.env_start   = current->mm->env_start;
         mm_hdr.env_end     = current->mm->env_end;
         mm_hdr.def_flags   = current->mm->def_flags;
     /* write the header into the checkpoint */
     if (tcmi_ckpt_write(ckpt, &mm_hdr, sizeof(mm_hdr)) < 0) {
         mdbg(ERR3, "Error writing memory descriptor header");
         goto exit0;
     }
     mdbg(INFO4, "Written memory descriptor:");
     mdbg(INFO4, "START CODE :      %08lx", current->mm->start_code);
     mdbg(INFO4, "END CODE   :      %08lx", current->mm->end_code);
     mdbg(INFO4, "START DATA :      %08lx", current->mm->start_data);
     mdbg(INFO4, "END DATA   :      %08lx", current->mm->end_data);
     mdbg(INFO4, "START BRK  :      %08lx", current->mm->start_brk);
     mdbg(INFO4, "BRK        :      %08lx", current->mm->brk);
     mdbg(INFO4, "START STACK:      %08lx", current->mm->start_stack);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_sig_read (struct tcmi_ckpt * ckpt) inline static
Reads a memory area from the checkpoint file and sets the those in the memory descriptor.
This also assumes that the old execution context has already been flushed by the caller.
Parameters
*ckpt - checkpoint file where the area is to be stored
Returns
0 upon success.
Definition at line 131 of file tcmi_ckpt_sig.h.
References tcmi_ckpt_sig_hdr::action, tcmi_ckpt_sig_hdr::blocked, mdbg, tcmi_ckpt_sig_hdr::real_blocked, tcmi_k_sigaction::sa_flags, tcmi_k_sigaction::sa_handler, tcmi_k_sigaction::sa_mask, tcmi_k_sigaction::sa_restorer, tcmi_ckpt_sig_hdr::sas_ss_size, tcmi_ckpt_sig_hdr::sas_ss_sp, tcmi_sigset::sigs, and tcmi_ckpt_read().
Referenced by tcmi_ckptcom_restart().
 {
     struct tcmi_ckpt_sig_hdr sig_hdr;
     int i;
     /* write the header into the checkpoint */
     if (tcmi_ckpt_read(ckpt, &sig_hdr, sizeof(sig_hdr)) < 0) {
         mdbg(ERR3, "Error reading signals");
         goto exit0;
     }
         current->sas_ss_sp   = sig_hdr.sas_ss_sp;
         current->sas_ss_size = sig_hdr.sas_ss_size;
     //for(i = 0; i < _NSIG_WORDS; i++){ // Only few bytes
         current->blocked      = *(sigset_t*)&sig_hdr.blocked.sigs;
         current->real_blocked = *(sigset_t*)&sig_hdr.real_blocked.sigs;
     //}
     // Signal actions
     for(i = 0; i < _NSIG; i++){
         current->sighand->action[i].sa.sa_handler = (__sighandler_t)(long)sig_hdr.action[i].sa_handler;
         current->sighand->action[i].sa.sa_restorer = (__sigrestore_t)(long)sig_hdr.action[i].sa_restorer;
         current->sighand->action[i].sa.sa_flags = sig_hdr.action[i].sa_flags;
         current->sighand->action[i].sa.sa_mask = *(sigset_t*)&sig_hdr.action[i].sa_mask.sigs;
     }
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_sig_write (struct tcmi_ckpt * ckpt) inline static
Writes a current process memory descriptor into the checkpoint file.
Parameters
*ckpt - checkpoint file where the area is to be stored
Returns
0 upon success.
Definition at line 87 of file tcmi_ckpt_sig.h.
Referenced by tcmi_ckptcom_checkpoint().
 {
     struct tcmi_ckpt_sig_hdr sig_hdr;
     int i;
         /* Now we dump the memory mapping */
         sig_hdr.sas_ss_sp   = current->sas_ss_sp;
         sig_hdr.sas_ss_size = current->sas_ss_size;
     //for(i = 0; i < _NSIG_WORDS; i++){ // Only few bytes
             sig_hdr.blocked.sigs       = *(u_int64_t*)(void*)&current->blocked;
             sig_hdr.real_blocked.sigs  = *(u_int64_t*)(void*)&current->real_blocked;
     //}
     // Add pending signals
     for(i = 0; i < _NSIG; i++){
         sig_hdr.action[i].sa_handler = (u_int64_t)(long)current->sighand->action[i].sa.sa_handler;
         sig_hdr.action[i].sa_restorer = (u_int64_t)(long)current->sighand->action[i].sa.sa_restorer;
         sig_hdr.action[i].sa_flags = current->sighand->action[i].sa.sa_flags;
         sig_hdr.action[i].sa_mask.sigs = *(u_int64_t*)(void*)&current->sighand->action[i].sa.sa_mask;
     }
     /* write the header into the checkpoint */
     if (tcmi_ckpt_write(ckpt, &sig_hdr, sizeof(sig_hdr)) < 0) {
         mdbg(ERR3, "Error writing signal header");
         goto exit0;
     }
     mdbg(INFO4, "Written signal header");
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }