Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/ccfs/ccfs.h File Reference
ccfs.h File Reference
#include <linux/fs.h>
#include <linux/fs_stack.h>
#include <linux/namei.h>
#include <linux/scatterlist.h>
#include <linux/hash.h>
#include "filter.h"
Data Structures
struct ccfs_super
Super block.
struct ccfs_file
File struct.
struct ccfs_inode
struct ccfs_dentry
Dentry.
Functions
static void ccfs_set_nested_file (struct file *ccfsfile, struct file *nested_file)
static struct file * ccfs_get_nested_file (struct file *ccfsfile)
static void ccfs_set_file_private (struct file *ccfsfile, struct ccfs_file *priv)
static struct ccfs_file * ccfs_get_file_private (struct file *ccfsfile)
static struct ccfs_dentry * ccfs_dentry_to_private (struct dentry *dentry)
static void ccfs_set_dentry_private (struct dentry *dentry, struct ccfs_dentry *dentry_priv)
static struct dentry * ccfs_get_nested_dentry (struct dentry *dentry)
static void ccfs_set_nested_dentry (struct dentry *dentry, struct dentry *lower_dentry)
static struct vfsmount * ccfs_dentry_to_nested_mnt (struct dentry *dentry)
static void ccfs_set_dentry_nested_mnt (struct dentry *dentry, struct vfsmount *lower_mnt)
static struct ccfs_inode * ccfs_inode_to_private (struct inode *inode)
static struct inode * ccfs_get_nested_inode (struct inode *inode)
static void ccfs_set_nested_inode (struct inode *inode, struct inode *lower_inode)
static int ccfs_is_inode_cacheable (struct inode *inode)
static struct ccfs_super * ccfs_superblock_to_private (struct super_block *sb)
static void ccfs_set_superblock_private (struct super_block *sb, struct ccfs_super *sb_info)
static struct super_block * ccfs_superblock_to_lower (struct super_block *sb)
static void ccfs_set_superblock_lower (struct super_block *sb, struct super_block *lower_sb)
int ccfs_interpose (struct dentry *lower_dentry, struct dentry *dentry, struct super_block *sb, int flag)
int ccfs_reopen_persistent_file (struct dentry *ccfsdentry, struct inode *ccfsinode)
void ccfs_init_inode (struct inode *inode, struct inode *lower_inode)
int ccfs_read_lower_page_segment (struct page *page_for_ccfs, pgoff_t page_index, size_t offset_in_page, size_t size, struct inode *ccfsinode)
int ccfs_write_lower_page_segment (struct inode *ccfsinode, struct page *page_for_lower, size_t offset_in_page, size_t size)
int ccfs_inode_test (struct inode *inode, void *candidate_lower_inode)
int ccfs_inode_set (struct inode *inode, void *lower_inode)
Variables
struct ccfs_super __attribute__
struct file_operations ccfs_main_fops
struct file_operations ccfs_dir_fops
struct inode_operations ccfs_main_iops
struct inode_operations ccfs_dir_iops
struct inode_operations ccfs_symlink_iops
struct super_operations ccfs_sops
struct dentry_operations ccfs_dops
struct address_space_operations ccfs_aops
struct kmem_cache * ccfs_file_cache
struct kmem_cache * ccfs_dentry_cache
struct kmem_cache * ccfs_inode_cache
struct kmem_cache * ccfs_sb_cache
struct kmem_cache * ccfs_lower_page_cache
Data Structure Documentation
struct ccfs_super
Super block.
Definition at line 13 of file ccfs.h.
Data Fields
struct filter * cacheable_filter Filter of cacheable files.
If null, all files are cacheable
struct super_block * nested_superblock
int prefetch Is aggressive file prefech enabled?
struct ccfs_file
File struct.
Definition at line 22 of file ccfs.h.
Data Fields
struct file * nested_file File in the backing store.
struct ccfs_inode
Definition at line 27 of file ccfs.h.
Data Fields
int cacheable Is this inode cacheable?
char * link Cached link pointer of this inode (in case it is a symlink)
struct file * lower_file
struct mutex lower_file_mutex
struct inode * nested_inode Reference to nested inode.
struct kstat * stat Cached stats of file.
struct inode vfs_inode This inode data.
struct ccfs_dentry
Dentry.
Definition at line 43 of file ccfs.h.
Data Fields
struct path lower_path Lower dentry & its path.
Function Documentation
static struct vfsmount* ccfs_dentry_to_nested_mnt (struct dentry * dentry) static read
Definition at line 93 of file ccfs.h.
Referenced by ccfs_create_underlying_file(), ccfs_d_release(), ccfs_d_revalidate(), ccfs_getattr(), ccfs_init_persistent_file_unlocked(), ccfs_lookup(), and ccfs_show_options().
 {
     return ((struct ccfs_dentry *)dentry->d_fsdata)->lower_path.mnt;
 }
static struct ccfs_dentry* ccfs_dentry_to_private (struct dentry * dentry) static read
Definition at line 67 of file ccfs.h.
Referenced by ccfs_d_release(), ccfs_fill_super(), and ccfs_lookup().
 {
     return (struct ccfs_dentry *)dentry->d_fsdata;
 }
static struct ccfs_file* ccfs_get_file_private (struct file * ccfsfile) static read
Definition at line 61 of file ccfs.h.
Referenced by ccfs_release().
{
     return (struct ccfs_file*)ccfsfile->private_data;
 }
static struct dentry* ccfs_get_nested_dentry (struct dentry * dentry) static read
Definition at line 80 of file ccfs.h.
Referenced by ccfs_create_underlying_file(), ccfs_d_release(), ccfs_d_revalidate(), ccfs_do_create(), ccfs_fsync(), ccfs_getattr(), ccfs_getxattr(), ccfs_init_persistent_file_unlocked(), ccfs_link(), ccfs_listxattr(), ccfs_lookup(), ccfs_mkdir(), ccfs_mknod(), ccfs_readlink(), ccfs_removexattr(), ccfs_rename(), ccfs_rmdir(), ccfs_setattr(), ccfs_setxattr(), ccfs_show_options(), ccfs_statfs(), ccfs_symlink(), ccfs_truncate(), and ccfs_unlink().
 {
     return ((struct ccfs_dentry *)dentry->d_fsdata)->lower_path.dentry;
 }
static struct file* ccfs_get_nested_file (struct file * ccfsfile) static read
Definition at line 53 of file ccfs.h.
Referenced by ccfs_fasync(), ccfs_flush(), ccfs_fsync(), ccfs_ioctl(), ccfs_readdir(), and ccfs_splice_read().
{
     return ((struct ccfs_file*)ccfsfile->private_data)->nested_file;
 }
static struct inode* ccfs_get_nested_inode (struct inode * inode) static read
Definition at line 111 of file ccfs.h.
References ccfs_inode_to_private(), and ccfs_inode::nested_inode.
Referenced by ccfs_bmap(), ccfs_clear_inode(), ccfs_d_revalidate(), ccfs_inode_test(), ccfs_ioctl(), ccfs_link(), ccfs_permission(), ccfs_setattr(), and ccfs_unlink().
 {
     return ccfs_inode_to_private(inode)->nested_inode;
 }
void ccfs_init_inode (struct inode * inode, struct inode * lower_inode)
Definition at line 60 of file super.c.
Referenced by ccfs_inode_set().
 {
     mdbg(INFO3, "Initializing inode: %p with lower inode: %p", inode, lower_inode);
     ccfs_set_nested_inode(inode, lower_inode);
     inode->i_ino = lower_inode->i_ino;
     inode->i_version++;
     inode->i_op = &ccfs_main_iops;
     inode->i_fop = &ccfs_main_fops;
     inode->i_mapping->a_ops = &ccfs_aops;
     ccfs_inode_to_private(inode)->cacheable = 1;
 }
int ccfs_inode_set (struct inode * inode, void * lower_inode)
Definition at line 706 of file inode.c.
Referenced by ccfs_interpose().
 {
     ccfs_init_inode(inode, (struct inode *)lower_inode);
     return 0;
 }
int ccfs_inode_test (struct inode * inode, void * candidate_lower_inode)
Definition at line 695 of file inode.c.
Referenced by ccfs_interpose().
 {
     if ((ccfs_get_nested_inode(inode)
          == (struct inode *)candidate_lower_inode)) {
         mdbg(INFO3,"Search matched: %p -> %p", inode, candidate_lower_inode);
         return 1;
     } else {
         return 0;
     }
 }
static struct ccfs_inode* ccfs_inode_to_private (struct inode * inode) static read
Definition at line 106 of file ccfs.h.
References ccfs_inode::vfs_inode.
Referenced by ccfs_destroy_inode(), ccfs_get_nested_inode(), ccfs_getattr(), ccfs_init_inode(), ccfs_init_persistent_file(), ccfs_init_persistent_file_unlocked(), ccfs_interpose(), ccfs_is_inode_cacheable(), ccfs_lookup(), ccfs_open(), ccfs_read_lower(), ccfs_read_lower_page_segment(), ccfs_readlink(), ccfs_reopen_persistent_file(), ccfs_set_nested_inode(), ccfs_write_lower(), and ccfs_write_lower_page_segment().
 {
     return container_of(inode, struct ccfs_inode, vfs_inode);
 }
int ccfs_interpose (struct dentry * lower_dentry, struct dentry * dentry, struct super_block * sb, int flag)
Definition at line 104 of file main.c.
Referenced by ccfs_do_create(), ccfs_link(), ccfs_lookup(), ccfs_mkdir(), ccfs_mknod(), ccfs_read_super(), and ccfs_symlink().
 {
     struct inode *lower_inode;
     struct inode *inode;
     int rc = 0;
     int matches;
     struct filter* filter;
     mdbg(INFO3, "Inode %p being interposed", dentry->d_inode);
     lower_inode = lower_dentry->d_inode;
     if (lower_inode->i_sb != ccfs_superblock_to_lower(sb)) {
         mdbg(ERR3, "Dentry %s EXDEV", dentry->d_name.name);
         rc = -EXDEV;
         goto out;
     }
     if (!igrab(lower_inode)) {
         mdbg(ERR3, "Dentry %s STALE", dentry->d_name.name);
         rc = -ESTALE;
         goto out;
     }
     inode = iget5_locked(sb, (unsigned long)lower_inode,
                  ccfs_inode_test, ccfs_inode_set,
                  lower_inode);
     if (!inode) {
           mdbg(ERR3, "Dentry %s No access", dentry->d_name.name);
         rc = -EACCES;
         iput(lower_inode);
         goto out;
     }
     if (S_ISLNK(lower_inode->i_mode))
         inode->i_op = &ccfs_symlink_iops;
     else if (S_ISDIR(lower_inode->i_mode))
         inode->i_op = &ccfs_dir_iops;
     if (S_ISDIR(lower_inode->i_mode))
         inode->i_fop = &ccfs_dir_fops;
     if (special_file(lower_inode->i_mode))
         init_special_inode(inode, lower_inode->i_mode,
                    lower_inode->i_rdev);
     dentry->d_op = &ccfs_dops;
     fsstack_copy_attr_all(inode, lower_inode);
     fsstack_copy_inode_size(inode, lower_inode);
     inode->i_uid = lower_inode->i_uid;
     inode->i_gid = lower_inode->i_gid;
     // TODO: Only first time!
     filter = ccfs_superblock_to_private(inode->i_sb)->cacheable_filter;
     matches = filter_matches(filter, dentry->d_name.name, dentry->d_name.len, &inode->i_ctime, inode->i_mode);
     if ( !matches )
         ccfs_inode_to_private(inode)->cacheable = 0;
     mdbg(INFO3, "Dentry %s matches pattern: %d. Cacheable: %d", dentry->d_name.name, matches, ccfs_inode_to_private(inode)->cacheable);
     rc = ccfs_init_persistent_file(dentry, inode);
     // Must be done AFTER the inner file is initialized!
     if (flag)
         d_add(dentry, inode);
     else
         d_instantiate(dentry, inode);
     if (rc) {
         mdbg(INFO3, "%s: Error attempting to initialize the "
                "persistent file for the dentry with name [%s]; "
                "rc = [%d]", __FUNCTION__, dentry->d_name.name, rc);
         goto out; // TODO: Release something?
     }
     // Must be done AFTER the inner file is initialized!
     if (inode->i_state & I_NEW)
         unlock_new_inode(inode);
     else
         iput(lower_inode); // TODO: Comment why release only on new
 out:
     return rc;
 }
static int ccfs_is_inode_cacheable (struct inode * inode) inline static
Definition at line 122 of file ccfs.h.
References ccfs_inode::cacheable, and ccfs_inode_to_private().
Referenced by ccfs_d_delete(), ccfs_drop_inode(), and ccfs_init_persistent_file_unlocked().
{
     return ccfs_inode_to_private(inode)->cacheable;
 }
int ccfs_read_lower_page_segment (struct page * page_for_ccfs, pgoff_t page_index, size_t offset_in_page, size_t size, struct inode * ccfsinode)
Definition at line 85 of file read_write.c.
Referenced by ccfs_readpage(), and ccfs_write_begin().
 {
     char *virt;
     loff_t offset;
     int rc;
     struct ccfs_inode *inode_info =
         ccfs_inode_to_private(ccfsinode);
     mdbg(INFO3, "Inode %p has lower file: %p (%ld)", ccfsinode, inode_info->lower_file, atomic_long_read(&inode_info->lower_file->f_count));
     offset = ((((loff_t)page_index) << PAGE_CACHE_SHIFT) + offset_in_page);
     virt = kmap(page_for_ccfs);
     rc = ccfs_read_lower(virt, offset, size, ccfsinode);
     kunmap(page_for_ccfs);
     flush_dcache_page(page_for_ccfs);
     return rc;
 }
int ccfs_reopen_persistent_file (struct dentry * ccfsdentry, struct inode * ccfsinode)
Definition at line 77 of file main.c.
{
     struct ccfs_inode *inode_info;
     int rc = 0;
     mdbg(INFO3, "Inode %p reopen requested", ccfsdentry->d_inode);
     if ( !ccfsdentry || !ccfsinode )
         return -EINVAL;
     inode_info = ccfs_inode_to_private(ccfsinode);
     mdbg(INFO3, "Inode %p (%p) with lower file: %p being reopened", ccfsdentry->d_inode, ccfsinode, inode_info->lower_file);
     mutex_lock(&inode_info->lower_file_mutex);
     if ( inode_info->lower_file )   {
         mdbg(INFO3, "Inode %p file release (%p -> %ld)", ccfsdentry->d_inode, inode_info->lower_file, atomic_long_read(&inode_info->lower_file->f_count));
         fput(inode_info->lower_file);
         mdbg(INFO3, "Inode file release done");
         inode_info->lower_file = NULL;
     }
     rc = ccfs_init_persistent_file_unlocked(ccfsdentry, ccfsinode);
     mutex_unlock(&inode_info->lower_file_mutex);
     return rc;
 }
static void ccfs_set_dentry_nested_mnt (struct dentry * dentry, struct vfsmount * lower_mnt) inline static
Definition at line 99 of file ccfs.h.
Referenced by ccfs_lookup(), and ccfs_read_super().
 {
     ((struct ccfs_dentry *)dentry->d_fsdata)->lower_path.mnt =
         lower_mnt;
 }
static void ccfs_set_dentry_private (struct dentry * dentry, struct ccfs_dentry * dentry_priv) inline static
Definition at line 73 of file ccfs.h.
Referenced by ccfs_fill_super(), and ccfs_lookup().
 {
     dentry->d_fsdata = dentry_priv;
 }
static void ccfs_set_file_private (struct file * ccfsfile, struct ccfs_file * priv) inline static
Definition at line 57 of file ccfs.h.
Referenced by ccfs_open().
{
     ccfsfile->private_data = priv;
 }
static void ccfs_set_nested_dentry (struct dentry * dentry, struct dentry * lower_dentry) inline static
Definition at line 86 of file ccfs.h.
Referenced by ccfs_lookup(), and ccfs_read_super().
 {
     ((struct ccfs_dentry *)dentry->d_fsdata)->lower_path.dentry =
         lower_dentry;
 }
static void ccfs_set_nested_file (struct file * ccfsfile, struct file * nested_file) inline static
Definition at line 49 of file ccfs.h.
References ccfs_file::nested_file.
Referenced by ccfs_open(), and ccfs_release().
{
     ((struct ccfs_file*)ccfsfile->private_data)->nested_file = nested_file;
 }
static void ccfs_set_nested_inode (struct inode * inode, struct inode * lower_inode) inline static
Definition at line 117 of file ccfs.h.
References ccfs_inode_to_private(), and ccfs_inode::nested_inode.
Referenced by ccfs_init_inode().
 {
     ccfs_inode_to_private(inode)->nested_inode = lower_inode;
 }
static void ccfs_set_superblock_lower (struct super_block * sb, struct super_block * lower_sb) inline static
Definition at line 145 of file ccfs.h.
Referenced by ccfs_read_super().
 {
     ((struct ccfs_super *)sb->s_fs_info)->nested_superblock = lower_sb;
 }
static void ccfs_set_superblock_private (struct super_block * sb, struct ccfs_super * sb_info) inline static
Definition at line 134 of file ccfs.h.
Referenced by ccfs_fill_super(), and ccfs_put_super().
 {
     sb->s_fs_info = sb_info;
 }
static struct super_block* ccfs_superblock_to_lower (struct super_block * sb) static read
Definition at line 140 of file ccfs.h.
Referenced by ccfs_interpose().
 {
     return ((struct ccfs_super *)sb->s_fs_info)->nested_superblock;
 }
static struct ccfs_super* ccfs_superblock_to_private (struct super_block * sb) static read
Definition at line 129 of file ccfs.h.
Referenced by ccfs_fill_super(), ccfs_interpose(), ccfs_open(), ccfs_parse_options(), and ccfs_put_super().
 {
     return (struct ccfs_super *)sb->s_fs_info;
 }
int ccfs_write_lower_page_segment (struct inode * ccfsinode, struct page * page_for_lower, size_t offset_in_page, size_t size)
Definition at line 35 of file read_write.c.
Referenced by ccfs_write_end().
 {
     struct ccfs_inode *inode_info;
     char *virt;
     loff_t offset;
     int rc;
     inode_info = ccfs_inode_to_private(ccfsinode);
     mdbg(INFO3, "Inode %p has lower file: %p (%ld)", ccfsinode, inode_info->lower_file, atomic_long_read(&inode_info->lower_file->f_count));
     offset = ((((loff_t)page_for_lower->index) << PAGE_CACHE_SHIFT)
           + offset_in_page);
     virt = kmap(page_for_lower);
     rc = ccfs_write_lower(ccfsinode, virt, offset, size);
     kunmap(page_for_lower);
     return rc;
 }
Variable Documentation
struct ccfs_super __attribute__
struct address_space_operations ccfs_aops
Definition at line 151 of file mmap.c.
Referenced by ccfs_init_inode().
struct kmem_cache* ccfs_dentry_cache
Definition at line 59 of file dentry.c.
Referenced by ccfs_d_release(), ccfs_fill_super(), and ccfs_lookup().
struct file_operations ccfs_dir_fops
Definition at line 211 of file file.c.
Referenced by ccfs_interpose().
struct inode_operations ccfs_dir_iops
Definition at line 727 of file inode.c.
Referenced by ccfs_interpose().
struct dentry_operations ccfs_dops
Definition at line 88 of file dentry.c.
Referenced by ccfs_fill_super(), ccfs_interpose(), and ccfs_lookup().
struct kmem_cache* ccfs_file_cache
Definition at line 13 of file file.c.
Referenced by ccfs_open(), and ccfs_release().
struct kmem_cache* ccfs_inode_cache
Definition at line 11 of file super.c.
Referenced by ccfs_alloc_inode(), and ccfs_destroy_inode().
struct kmem_cache* ccfs_lower_page_cache
Definition at line 13 of file mmap.c.
struct file_operations ccfs_main_fops
Definition at line 223 of file file.c.
Referenced by ccfs_init_inode().
struct inode_operations ccfs_main_iops
Definition at line 746 of file inode.c.
Referenced by ccfs_init_inode().
struct kmem_cache* ccfs_sb_cache
Definition at line 186 of file main.c.
Referenced by ccfs_fill_super(), and ccfs_put_super().
struct super_operations ccfs_sops
Definition at line 132 of file super.c.
Referenced by ccfs_fill_super().
struct inode_operations ccfs_symlink_iops
Definition at line 714 of file inode.c.
Referenced by ccfs_interpose().