Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/director/netlink/comm.c File Reference
comm.c File Reference
#include "msgs.h"
#include "comm.h"
#include "genl_ext.h"
#include <linux/skbuff.h>
#include <linux/resource.h>
#include <dbg.h>
#include "generic_user_message_send_handler.h"
Functions
static int check_for_error (struct genl_info *info)
Checks, if the transaction returned an error.
static int is_director_connected (void)
Returns pid of director process if there is user-space director connected, 0 otherwise.
int is_director_pid (pid_t ppid)
Returns 1 if, ppid is equal to userspace director pid.
static int get_unique_seq (void)
Returns unique sequence number for transaction.
static int register_pid_handler (struct sk_buff *skb, struct genl_info *info)
int init_director_comm (void)
Initializes director generic netlink family.
void destroy_director_comm (void)
Finalizes director generic netlink family.
static int msg_transaction_request (int msg_code, struct genl_tx *tx, struct msg_transaction_ops *ops, void *params, int interruptible)
Helper method to create&send request.
static int msg_transaction_response (struct genl_tx *tx, struct msg_transaction_ops *ops, void *params)
int msg_transaction_do (int msg_code, struct msg_transaction_ops *ops, void *params, int interruptible)
Performs a netlink transaction.
Variables
const char * DIRECTOR_CHANNEL_NAME = "DIRECTORCHNL"
static u32 user_director_pid = 0
Pid of associated user space process (if any)
static atomic_t director_seq = ATOMIC_INIT(1)
Sequence generating unique transaction numbers.
static int read_timeout = 5
Read timeout in seconds.
static struct genl_family director_gnl_family
static struct nla_policy director_genl_policy [__DIRECTOR_ATTR_MAX+1]
static struct genl_ops register_pid_ops
static struct genl_ops send_user_message_ops
static struct genl_ops * check_npm_ops_ref
static struct genl_ops * node_connected_ops_ref
static struct genl_ops * ack_ops_ref
static struct genl_ops * immigration_request_ops_ref
Function Documentation
static int check_for_error (struct genl_info * info) static
Checks, if the transaction returned an error.
Returns
0, if there was no error, error code otherwise
Definition at line 43 of file comm.c.
References DIRECTOR_A_ERRNO, and minfo.
Referenced by msg_transaction_response().
{
     struct nlattr* attr;
     int err;
     attr = nlmsg_find_attr(info->nlhdr, sizeof(struct genlmsghdr), DIRECTOR_A_ERRNO);
     if ( attr == NULL ) {
         return 0;
     }
     err = nla_get_u32(attr);
     minfo(ERR3, "Error code from user deamon: %d", err);
     return err;
 }
void destroy_director_comm (void)
Finalizes director generic netlink family.
Definition at line 145 of file comm.c.
References director_gnl_family.
{
     //int res;
 //  if ( (res = shutdown_user_daemon_request()) ) {
 //      printk(KERN_ERR "Failed to stop the helper daemon: %d\n", res);
 //  }
     genl_unregister_ops(&director_gnl_family, &register_pid_ops);
     genl_unregister_ops(&director_gnl_family, &send_user_message_ops);
     genl_unregister_ops(&director_gnl_family, check_npm_ops_ref);
     genl_unregister_ops(&director_gnl_family, node_connected_ops_ref);
     genl_unregister_ops(&director_gnl_family, ack_ops_ref);
     genl_unregister_ops(&director_gnl_family, immigration_request_ops_ref);
     genl_unregister_family(&director_gnl_family);
     kfree(check_npm_ops_ref);
 }
static int get_unique_seq (void) static
Returns unique sequence number for transaction.
Definition at line 67 of file comm.c.
References director_seq.
Referenced by msg_transaction_request().
{
     return atomic_inc_return(&director_seq);
 }
int init_director_comm (void)
Initializes director generic netlink family.
Definition at line 108 of file comm.c.
References DIRECTOR_ACK, director_genl_policy, director_gnl_family, DIRECTOR_IMMIGRATION_REQUEST_RESPONSE, DIRECTOR_NODE_CONNECT_RESPONSE, DIRECTOR_NPM_RESPONSE, genlmsg_register_tx_ops(), and minfo.
{
     int ret;
     ret = genl_register_family(&director_gnl_family);
     if (ret != 0)
         return ret;
     // TODO: Release temporarily allocated resources ;)
     /* Register callback for daemin PID registration */
     genl_register_ops(&director_gnl_family, &register_pid_ops);
     genl_register_ops(&director_gnl_family, &send_user_message_ops);
     /* Register generic dispatching callback for all other calls */
     check_npm_ops_ref = genlmsg_register_tx_ops(&director_gnl_family, director_genl_policy, DIRECTOR_NPM_RESPONSE);
     if ( !check_npm_ops_ref )
         return -1;
     node_connected_ops_ref = genlmsg_register_tx_ops(&director_gnl_family, director_genl_policy, DIRECTOR_NODE_CONNECT_RESPONSE);
     if ( !check_npm_ops_ref )
         return -1;
     immigration_request_ops_ref = genlmsg_register_tx_ops(&director_gnl_family, director_genl_policy, DIRECTOR_IMMIGRATION_REQUEST_RESPONSE);
     if ( !immigration_request_ops_ref )
         return -1;
     ack_ops_ref = genlmsg_register_tx_ops(&director_gnl_family, director_genl_policy, DIRECTOR_ACK);
     if ( !ack_ops_ref )
         return -1;
     minfo(INFO3, "Director comm component initialized");
     return 0;
 }
static int is_director_connected (void) static
Returns pid of director process if there is user-space director connected, 0 otherwise.
Definition at line 58 of file comm.c.
References user_director_pid.
Referenced by msg_transaction_request().
{
     return user_director_pid;
 }
int is_director_pid (pid_t ppid)
Returns 1 if, ppid is equal to userspace director pid.
Definition at line 62 of file comm.c.
References user_director_pid.
{
     return (u32)ppid == user_director_pid;
 }
int msg_transaction_do (int msg_code, struct msg_transaction_ops * ops, void * params, int interruptible)
Performs a netlink transaction.
1) Creates a message (with specified code) 2) Uses "create_resquest" method to fill params 3) Sends the request 4) Reads response 5) Uses "read_response" to parse output data
Parameters
msg_code Code of the message to be created
ops Transaction specific operations to fill params and read response
params Structure that will contain input params and hold output values
interruptible if !=0, the waiting for response can be interrupted by a signal
Returns
0 on success, error code otherwise
Definition at line 232 of file comm.c.
References msg_transaction_request(), and msg_transaction_response().
{
     struct genl_tx tx;
     int res = msg_transaction_request(msg_code, &tx, ops, params, interruptible);
     if ( res )
         return res;
     return msg_transaction_response(&tx, ops, params);
 }
static int msg_transaction_request (int msg_code, struct genl_tx * tx, struct msg_transaction_ops * ops, void * params, int interruptible) static
Helper method to create&send request.
Definition at line 167 of file comm.c.
References msg_transaction_ops::create_request, director_gnl_family, genlmsg_unicast_tx(), get_unique_seq(), and is_director_connected().
Referenced by msg_transaction_do().
{
   int ret;
   void *msg_head;
   struct sk_buff *skb;
   int seq, director_pid;
   director_pid = is_director_connected();
   if ( !director_pid )
     return -EFAULT;
   skb = nlmsg_new(63000, GFP_KERNEL);
   if (skb == NULL)
       return -1;
   seq = get_unique_seq();
   msg_head = genlmsg_put(skb, director_pid, seq, &director_gnl_family, 0, msg_code);
   if (msg_head == NULL) {
       ret = -ENOMEM;
       goto failure;
   }
   ret = ops->create_request(skb, params);
   if (ret < 0)
       goto failure;
   ret = genlmsg_end(skb, msg_head);
   if (ret < 0)
       goto failure;
   ret = genlmsg_unicast_tx(skb, director_pid, tx, interruptible);
   if (ret != 0)
       goto failure;
   return ret;
 failure:
   genlmsg_cancel(skb, msg_head);
   return ret;
 }
static int msg_transaction_response (struct genl_tx * tx, struct msg_transaction_ops * ops, void * params) static
Definition at line 209 of file comm.c.
References check_for_error(), genlmsg_read_response(), msg_transaction_ops::read_response, and read_timeout.
Referenced by msg_transaction_do().
{
     struct sk_buff *skb;
     struct genl_info info;
     unsigned int ret = 0;
     if ( (ret= genlmsg_read_response(tx, &skb, &info, read_timeout)) )
         return ret;
     if ( (ret=check_for_error(&info)) )
         goto done;
     if ( ops->read_response ) {
       ret = ops->read_response(&info, params);
       if (ret < 0)
           goto done;
     }
 done:
     kfree_skb(skb);
     return ret;
 }
static int register_pid_handler (struct sk_buff * skb, struct genl_info * info) static
Definition at line 72 of file comm.c.
References DIRECTOR_A_PID, minfo, and user_director_pid.
{
     struct nlattr* attr;
     attr = nlmsg_find_attr(info->nlhdr, sizeof(struct genlmsghdr), DIRECTOR_A_PID);
     if ( attr == NULL ) {
         return -1;
     }
     user_director_pid = nla_get_u32(attr);
     minfo(INFO1, "Registered director pid: %u", user_director_pid);
     return 0;
 }
Variable Documentation
struct genl_ops * ack_ops_ref static
Definition at line 103 of file comm.c.
struct genl_ops* check_npm_ops_ref static
Definition at line 103 of file comm.c.
const char* DIRECTOR_CHANNEL_NAME = "DIRECTORCHNL"
Definition at line 11 of file comm.c.
struct nla_policy director_genl_policy[__DIRECTOR_ATTR_MAX+1] static
Initial value:
= {
    [DIRECTOR_A_PID] = { .type = NLA_U32 },
    [DIRECTOR_A_LENGTH] = { .type = NLA_U32 },
    [DIRECTOR_A_EXIT_CODE] = { .type = NLA_U32 },
    [DIRECTOR_A_ERRNO] = { .type = NLA_U32 },
    [DIRECTOR_A_RUSAGE] = { .type = NLA_BINARY, .len = sizeof(struct rusage) },
}
Definition at line 30 of file comm.c.
Referenced by init_director_comm().
struct genl_family director_gnl_family static
Initial value:
= {
    .id = GENL_ID_GENERATE,
    .hdrsize = 0,
    .name = "DIRECTORCHNL",
    .version = 1,
    .maxattr =  __DIRECTOR_ATTR_MAX
}
Definition at line 21 of file comm.c.
Referenced by destroy_director_comm(), init_director_comm(), and msg_transaction_request().
atomic_t director_seq = ATOMIC_INIT(1) static
Sequence generating unique transaction numbers.
Definition at line 16 of file comm.c.
Referenced by get_unique_seq().
struct genl_ops * immigration_request_ops_ref static
Definition at line 103 of file comm.c.
struct genl_ops * node_connected_ops_ref static
Definition at line 103 of file comm.c.
int read_timeout = 5 static
Read timeout in seconds.
Definition at line 19 of file comm.c.
Referenced by msg_transaction_response().
struct genl_ops register_pid_ops static
Initial value:
= {
        .cmd = DIRECTOR_REGISTER_PID,
        .flags = 0,
        .policy = director_genl_policy,
    .doit = register_pid_handler,
    .dumpit = NULL,
}
Definition at line 87 of file comm.c.
struct genl_ops send_user_message_ops static
Initial value:
= {
        .cmd = DIRECTOR_SEND_GENERIC_USER_MESSAGE,
        .flags = 0,
        .policy = director_genl_policy,
    .doit = handle_send_generic_user_message,
    .dumpit = NULL,
}
Definition at line 95 of file comm.c.
u32 user_director_pid = 0 static
Pid of associated user space process (if any)
Definition at line 14 of file comm.c.
Referenced by is_director_connected(), is_director_pid(), and register_pid_handler().