Clondike: tcmi_ctlfs_dir class
tcmi_ctlfs_dir class
tcmi_ctlfs_entry class
This class represents a directory in the tcmi control file system.
Data Structures
struct tcmi_ctlfs_dir
A directory compound structure, extends the parent entry class.
Macros
#define TCMI_CTLFS_DIR(e) ((struct tcmi_ctlfs_dir *)e)
Casts an entry to directory.
Functions
struct tcmi_ctlfs_entry * tcmi_ctlfs_dir_new (struct tcmi_ctlfs_entry *parent, mode_t mode, const char namefmt[],...)
<<public>> Creates a new directory instance.
struct tcmi_ctlfs_entry * tcmi_ctlfs_dir_vnew (struct tcmi_ctlfs_entry *parent, mode_t mode, const char namefmt[], va_list args)
<<public>> Creates a new directory instance - va_list version.
struct tcmi_ctlfs_entry * tcmi_ctlfs_rootdir_new (struct super_block *sb)
<<public>> Creates a root directory instance.
Detailed Description
This class represents a directory in the tcmi control file system.
It provides a functionality to instantiate a root directory and regular directories. The root directory is special as it doesn't have a parent entry.
Data Structure Documentation
struct tcmi_ctlfs_dir
A directory compound structure, extends the parent entry class.
Definition at line 54 of file tcmi_ctlfs_dir.h.
Data Fields
struct tcmi_ctlfs_entry super parent class instance
Macro Definition Documentation
#define TCMI_CTLFS_DIR (e) ((struct tcmi_ctlfs_dir *)e)
Casts an entry to directory.
Definition at line 73 of file tcmi_ctlfs_dir.h.
Function Documentation
struct tcmi_ctlfs_entry* tcmi_ctlfs_dir_new (struct tcmi_ctlfs_entry * parent, mode_t mode, const char namefmt[], ...) read
<<public>> Creates a new directory instance.
<<public>> Creates a new directory instance.
Handles variable number of arguments and delegates work to tcmi_ctlfs_dir_vnew()
Parameters
*parent - pointer to the parent entry - has to be a directory
*mode - access rights for the inode
namefmt - nameformat string (printf style)
Returns
pointer to the new directory or NULL
Definition at line 49 of file tcmi_ctlfs_dir.c.
References args, and tcmi_ctlfs_dir_vnew().
Referenced by tcmi_ccnman_init_ctlfs_dirs(), tcmi_man_init_ctlfs_dirs(), tcmi_migman_init_ctlfs_dirs(), and tcmi_task_init().
 {
     struct tcmi_ctlfs_entry *dir;
     va_list args;
     va_start(args, namefmt);
     dir = tcmi_ctlfs_dir_vnew(parent, mode, namefmt, args);
     va_end(args);
     return dir;
 }
struct tcmi_ctlfs_entry* tcmi_ctlfs_dir_vnew (struct tcmi_ctlfs_entry * parent, mode_t mode, const char namefmt[], va_list args) read
<<public>> Creates a new directory instance - va_list version.
<<public>> Creates a new directory instance - va_list version.
The instance is:
created
initialized (delegated to the parent class)
link counts of parent and new directory need to be adjusted
Parameters
*parent - pointer to the parent entry - has to be a directory
*mode - access rights for the inode
namefmt - nameformat string (printf style)
args - arguments to the format string
Returns
pointer to the new directory or NULL
Definition at line 73 of file tcmi_ctlfs_dir.c.
References mdbg, TCMI_CTLFS_ENTRY, tcmi_ctlfs_entry_inc_links(), and tcmi_ctlfs_entry_init().
Referenced by tcmi_ctlfs_dir_new(), tcmi_migman_init_ctlfs_dirs(), and tcmi_sock_new().
 {
     struct tcmi_ctlfs_dir *dir;
     mdbg(INFO4, "Creating new directory");
     if (!(dir = kmalloc(sizeof(struct tcmi_ctlfs_dir), GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate memory for directory");
         goto exit0;
     }
         /* directory file operations are taken from fs/libfs.c */
     if (tcmi_ctlfs_entry_init(TCMI_CTLFS_ENTRY(dir),
                   TCMI_CTLFS_ENTRY(parent),
                   S_IFDIR | mode,
                   NULL,
                   &simple_dir_inode_operations,
                   &simple_dir_operations, namefmt, args)) {
         mdbg(ERR3, "Failed to create the directory");
         goto exit1;
     }
     /* success, append the directory to its parent (account for '..') and
        increment the link count for '.' */
     tcmi_ctlfs_entry_inc_links(TCMI_CTLFS_ENTRY(parent));
     tcmi_ctlfs_entry_inc_links(TCMI_CTLFS_ENTRY(dir));
     return TCMI_CTLFS_ENTRY(dir);
     /* error handling */
  exit1:
     kfree(dir);
  exit0:
     return NULL;
 }
struct tcmi_ctlfs_entry* tcmi_ctlfs_rootdir_new (struct super_block * sb) read
<<public>> Creates a root directory instance.
<<public>> Creates a root directory instance.
Parameters
*sb - super block of the file system
Returns
pointer to the new root directory or NULL
Definition at line 114 of file tcmi_ctlfs_dir.c.
References mdbg, TCMI_CTLFS_ENTRY, tcmi_ctlfs_entry_inc_links(), and tcmi_ctlfs_rootentry_init().
Referenced by tcmi_ctlfs_fill_super().
 {
     struct tcmi_ctlfs_dir *root;
     mdbg(INFO4, "Creating root directory");
     if (!(root = kmalloc(sizeof(struct tcmi_ctlfs_dir), GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate memory for root directory");
         goto exit0;
     }
     /* directory file operations are taken from fs/libfs.c */
     if (tcmi_ctlfs_rootentry_init(TCMI_CTLFS_ENTRY(root), sb,
                       S_IFDIR | 0755,
                       NULL,
                       &simple_dir_inode_operations,
                       &simple_dir_operations)) {
         mdbg(ERR3, "Failed to create root directory");
         goto exit1;
     }
     /* account for '.' */
     tcmi_ctlfs_entry_inc_links(TCMI_CTLFS_ENTRY(root));
     return TCMI_CTLFS_ENTRY(root);
     /* error handling */
  exit1:
     kfree(root);
  exit0:
     return NULL;
 }