Clondike: tcmi_method_wrapper class
tcmi_method_wrapper class
task component
This artificial class is used for queueing methods to an arbitrary object.
Data Structures
struct tcmi_method_wrapper
Compound structure that describes the method.
Typedefs
typedef int tcmi_method_t (void *, struct tcmi_method_wrapper *)
Describes the method that can be submitted into the method queue.
Functions
static struct tcmi_method_wrapper * tcmi_method_wrapper_new (tcmi_method_t *method, void *data, int size)
<<public>> Creates a new wrapper for the specified method.
static struct tcmi_method_wrapper * tcmi_method_wrapper_get (struct tcmi_method_wrapper *self)
<<public>> Method wrapper accessor.
static void tcmi_method_wrapper_put (struct tcmi_method_wrapper *self)
<<public>> Decrements the reference counter, when the count reaches 0, the instance is destroyed.
static int tcmi_method_wrapper_call (struct tcmi_method_wrapper *self, void *obj)
<<public>> Calls the method that resides in the wrapper.
static void * tcmi_method_wrapper_data (struct tcmi_method_wrapper *self)
<<public>> Accessor for the data stored in the method wrapper.
Detailed Description
This artificial class is used for queueing methods to an arbitrary object.
It contains the method to be called and a node to link the instance into a queue. In addition, there is data stored inside the wrapper. The wrapper instance itself is passed as the method argument, so that target object can extract the data.
Data Structure Documentation
struct tcmi_method_wrapper
Compound structure that describes the method.
Definition at line 60 of file tcmi_method_wrapper.h.
Data Fields
void * data data passed as an argument to the method.
tcmi_method_t * method method stored in the wrapper.
struct list_head node node to link the wrapper in a queue.
atomic_t ref_count Instance reference counter.
Typedef Documentation
typedef int tcmi_method_t(void *, struct tcmi_method_wrapper *)
Describes the method that can be submitted into the method queue.
Definition at line 57 of file tcmi_method_wrapper.h.
Function Documentation
static int tcmi_method_wrapper_call (struct tcmi_method_wrapper * self, void * obj) inline static
<<public>> Calls the method that resides in the wrapper.
The target object is specified as the parameter
Parameters
*self - pointer to this method wrapper instance
*obj - object whose method is to be called
Returns
status of the called method
Definition at line 158 of file tcmi_method_wrapper.h.
References self.
Referenced by tcmi_task_process_methods().
 {
     int ret = 0;
     if (self && self->method) {
         ret = self->method(obj, self);
     }
     return ret;
 }
static void* tcmi_method_wrapper_data (struct tcmi_method_wrapper * self) inline static
<<public>> Accessor for the data stored in the method wrapper.
Parameters
*self - pointer to this method wrapper instance
Returns
pointer to the data
Definition at line 175 of file tcmi_method_wrapper.h.
Referenced by tcmi_task_emigrate_npm(), tcmi_task_exit(), tcmi_task_migrateback_npm(), tcmi_task_mount_proxyfs(), tcmi_task_process_msg(), and tcmi_task_send_message().
 {
     return self->data;
 }
static struct tcmi_method_wrapper* tcmi_method_wrapper_get (struct tcmi_method_wrapper * self) static read
<<public>> Method wrapper accessor.
Increments the reference counter
Parameters
*self - pointer to this method wrapper instance
Returns
- self
Definition at line 122 of file tcmi_method_wrapper.h.
References self.
Referenced by tcmi_task_process_msg().
 {
     if (!self)
         return NULL;
     atomic_inc(&self->ref_count);
     return self;
 }
static struct tcmi_method_wrapper* tcmi_method_wrapper_new (tcmi_method_t * method, void * data, int size) static read
<<public>> Creates a new wrapper for the specified method.
If the data argument is non-NULL, it will also allocate space for the data and copy 'size' bytes over.
Parameters
method - method that the wrapper holds
data - data that is used as method argumet
size - size of the data
Returns
new method wrapper instance or NULL
Definition at line 82 of file tcmi_method_wrapper.h.
References tcmi_method_wrapper::data, mdbg, tcmi_method_wrapper::method, tcmi_method_wrapper::node, and tcmi_method_wrapper::ref_count.
Referenced by tcmi_task_flush_and_submit_method(), and tcmi_task_submit_method().
 {
     struct tcmi_method_wrapper *wrapper;
     if (!(wrapper = (struct tcmi_method_wrapper*)kmalloc(sizeof(struct tcmi_method_wrapper),
                                  GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for the wrapper");
         goto exit0;
     }
     INIT_LIST_HEAD(&wrapper->node);
     wrapper->method = method;
     wrapper->data = NULL;
     /* copy the data over if any specified. */
     if (data && size) {
         if (!(wrapper->data = vmalloc(size))) {
             mdbg(ERR3, "Can't allocate memory for the wrapper data");
             goto exit1;
         }
         memcpy(wrapper->data, data, size);
     }
     atomic_set(&wrapper->ref_count, 1);
     mdbg(INFO4, "Created method wrapper %p", wrapper);
     return wrapper;
     /* error handling */
  exit1:
     kfree(wrapper);
  exit0:
     return NULL;
 }
static void tcmi_method_wrapper_put (struct tcmi_method_wrapper * self) inline static
<<public>> Decrements the reference counter, when the count reaches 0, the instance is destroyed.
Parameters
*self - pointer to this method wrapper instance
Definition at line 136 of file tcmi_method_wrapper.h.
References mdbg, and self.
Referenced by tcmi_task_execve(), tcmi_task_flush_and_submit_method(), tcmi_task_process_methods(), and tcmi_task_put().
 {
     if (!self)
         return;
     if (atomic_dec_and_test(&self->ref_count)) {
         list_del_init(&self->node);
         mdbg(INFO4, "Destroying method wrapper %p", self);
         vfree(self->data);
         kfree(self);
     }
 }