Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/proxyfs/buffer.h File Reference
buffer.h File Reference
#include <linux/vmalloc.h>
#include <linux/slab.h>
#include <asm/uaccess.h>
Data Structures
struct circ_buf
Circular buffer structure.
Macros
#define CIRC_BUF_USE_VMALLOC (4 << 10)
Functions
int circ_buf_write (struct circ_buf *self, const char *buf, unsigned count)
<<public>> Initialize buffer structure
int circ_buf_write_user (struct circ_buf *self, const char *buf, unsigned count)
<<public>> Write to buffer from user space
int circ_buf_read (struct circ_buf *self, char *buf, unsigned count)
<<public>> Destructively read from buffer
int circ_buf_read_user (struct circ_buf *self, char *buf, unsigned count)
<<public>> Destructively read from buffer to userspace
static int circ_buf_init (struct circ_buf *self, unsigned size)
static void circ_buf_destroy (struct circ_buf *self)
<<public>> Opossite function to circ_buf_init
static unsigned circ_buf_get_read_size (const struct circ_buf *self)
<<public>> Returns maximum amount of data which are continuos - can by copied with one memcpy call
static void * circ_buf_get_read_addr (const struct circ_buf *self)
<<public>> Returns base address for reading -
static unsigned circ_buf_get_write_size (const struct circ_buf *self)
<<public>> Returns maximum amount of free space which is continuos - can by filled with one memcpy call
static void * circ_buf_get_write_addr (const struct circ_buf *self)
<<public>> Returns base address for writting -
static void circ_buf_adjust_read_ptr (struct circ_buf *self, const unsigned count)
<<public>> Adjust read pointer
static void circ_buf_adjust_write_ptr (struct circ_buf *self, const unsigned count)
<<public>> Adjust write pointer
static unsigned circ_buf_free_space (struct circ_buf *self)
<<public>> get total free space in buffer
static unsigned circ_buf_count (struct circ_buf *self)
<<public>> get count of total data contained in the buffer
int circ_buf_look_at (struct circ_buf *self, char *buf, unsigned count, size_t offset)
<<public>> Nondestructively read from buffer at offset
void circ_buf_dump (const char *prefix, struct circ_buf *self)
<<public>> Method used for debugging purposes.
Function Documentation
static void circ_buf_adjust_read_ptr (struct circ_buf * self, const unsigned count) inline static
<<public>> Adjust read pointer
Parameters
self - pointer to this buffer instance
count - how much adjust WARNING: count must be between 0 and data total in buffer
Definition at line 168 of file buffer.h.
References count(), and self.
 {
     if( count > 0 ){
         self->full = 0;
         self->read += count;
         if( self->read >= self->buf + self->size || self->read < self->buf )
             self->read -= self->size;
     }
 }
static void circ_buf_adjust_write_ptr (struct circ_buf * self, const unsigned count) inline static
<<public>> Adjust write pointer
Parameters
self - pointer to this buffer instance
count - how much adjust WARNING: count must be between 0 and free space in buffer
Definition at line 182 of file buffer.h.
References count(), and self.
 {
     if( count > 0 ){
         self->write += count;
         if( self->write >= self->buf + self->size || self->write < self->buf )
             self->write -= self->size;
         if( self->write == self->read ) self->full = 1;
     }
 }
static unsigned circ_buf_count (struct circ_buf * self) inline static
<<public>> get count of total data contained in the buffer
Parameters
self - pointer to this buffer instance
Returns
total bytes contained by the buffer
Definition at line 214 of file buffer.h.
References circ_buf_free_space().
 {
     return self->size - circ_buf_free_space(self);
 }
static void circ_buf_destroy (struct circ_buf * self) inline static
<<public>> Opossite function to circ_buf_init
Parameters
self - pointer to this buffer instance
Definition at line 100 of file buffer.h.
References CIRC_BUF_USE_VMALLOC, and self.
 {
     if( self->size >= CIRC_BUF_USE_VMALLOC )
         vfree(self->buf);
     else
         kfree(self->buf);
     self->size = 0;
     self->read = NULL;
     self->write = NULL;
 }
static unsigned circ_buf_free_space (struct circ_buf * self) inline static
<<public>> get total free space in buffer
Parameters
self - pointer to this buffer instance
Returns
amount of free bytes in buffer
Definition at line 197 of file buffer.h.
References self.
Referenced by circ_buf_count().
 {
     if( self->write > self->read )
         return (self->size - (self->write - self->read));
     else if( self->write < self->read )
         return self->read - self->write;
     else if( self->full )
         return 0;
     // buf is empty
     return self->size;
 }
static void* circ_buf_get_read_addr (const struct circ_buf * self) inline static
<<public>> Returns base address for reading -
Parameters
self - pointer to this buffer instance
Returns
address from which read should start
Definition at line 131 of file buffer.h.
 {
     return self->read;
 }
static unsigned circ_buf_get_read_size (const struct circ_buf * self) inline static
<<public>> Returns maximum amount of data which are continuos - can by copied with one memcpy call
Parameters
self - pointer to this buffer instance
Returns
the amount of data
Definition at line 117 of file buffer.h.
References self.
 {
     if( self->write > self->read )
         return self->write - self->read;
     else if( self->write < self->read || self->full )
         return (self->buf + self->size) - self->read;
     return 0;
 }
static void* circ_buf_get_write_addr (const struct circ_buf * self) inline static
<<public>> Returns base address for writting -
Parameters
self - pointer to this buffer instance
Returns
address from which write should start
Definition at line 159 of file buffer.h.
 {
     return self->write;
 }
static unsigned circ_buf_get_write_size (const struct circ_buf * self) inline static
<<public>> Returns maximum amount of free space which is continuos - can by filled with one memcpy call
Parameters
self - pointer to this buffer instance
Returns
the amount of data
Definition at line 142 of file buffer.h.
References self.
 {
     if( self->write > self->read )
         return self->buf + self->size - self->write;
     else if( self->write < self->read )
         return self->read - self->write;
     else if( self->full )
         return 0;
     // buf is empty
     return self->buf + self->size - self->write;
 }
static int circ_buf_init (struct circ_buf * self, unsigned size) inline static
Definition at line 81 of file buffer.h.
References CIRC_BUF_USE_VMALLOC, self, and size.
 {
     if( size >= CIRC_BUF_USE_VMALLOC )
         self->buf = vmalloc( size );
     else
         self->buf = kmalloc( size, GFP_KERNEL );
     if( self->buf == NULL ) return -1;
     self->size = size;
     self->read = self->buf;
     self->write = self->buf;
     self->full = 0;
     return 0;
 }