Clondike: tcmi_syscallhooks class
tcmi_syscallhooks class
syscall forwarding
A <<singleton>> class that installs syscalls hooks into the kernel.
Modules
Group identification
A part of tcmi_syscallhooks class that installs group identity manipulation syscalls hooks into the kernel.
tcmi_syscallhooks_other class
A <<singleton>> class that installs syscalls hooks into the kernel.
PID & GID manipulation
A <<singleton>> class that installs PID manipulation syscalls hooks into the kernel.
Signal sending
A <<singleton>> class that installs syscalls hooks into the kernel.
User identification
A <<singleton>> class that installs user identity manipulation syscalls hooks into the kernel.
Functions
int tcmi_syscall_hooks_init (void)
<<public>> Registers all syscalls hooks with the kernel.
void tcmi_syscall_hooks_exit (void)
<<public>> Unregisters all syscalls hooks.
static long tcmi_syscall_hooks_sys_wait4 (pid_t pid, int __user *stat_addr, int options, struct rusage __user *ru)
<<private>> sys_wait4 system call hook.
static long tcmi_syscall_hooks_pre_fork (unsigned long clone_flags, unsigned long stack_start, struct pt_regs *regs, unsigned long stack_size, int __user *parent_tidptr, int __user *child_tidptr)
<<private>> pre-fork
static long tcmi_syscall_hooks_in_fork (struct task_struct *child)
<<private>> in-fork...
static long tcmi_syscall_hooks_post_fork (struct task_struct *child, long res, pid_t remote_pid, int __user *parent_tidptr, int __user *child_tidptr)
<<private>> post-fork
static long tcmi_syscall_hooks_sys_kill (int pid, int sig)
<<private>> Kill system call hook.
static long tcmi_syscall_hooks_do_tkill (int tgid, int pid, int sig)
<<private>> do_tkill hook.
static long tcmi_syscall_hooks_sys_rt_sigqueueinfo (int pid, int sig, siginfo_t *info)
<<private>> sys_rt_sigqueueinfo hook.
Detailed Description
A <<singleton>> class that installs syscalls hooks into the kernel.
Function Documentation
static long tcmi_syscall_hooks_do_tkill (int tgid, int pid, int sig) static
<<private>> do_tkill hook.
Handles both tkill and tgkill system call
Parameters
tgid - the thread group ID of the thread
pid - the PID of the thread
sig - signal to be sent
Returns
- zero on sucess.
Definition at line 95 of file tcmi_syscallhooks_signal.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_TKILL.
Referenced by tcmi_syscall_hooks_signal_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_TKILL, tgid, pid, sig);
 }
void tcmi_syscall_hooks_exit (void)
<<public>> Unregisters all syscalls hooks.
<<public>> Unregisters all hooks.
Definition at line 65 of file tcmi_syscallhooks.c.
References minfo, tcmi_syscall_hooks_groupident_exit(), tcmi_syscall_hooks_other_exit(), tcmi_syscall_hooks_pidman_exit(), tcmi_syscall_hooks_signal_exit(), and tcmi_syscall_hooks_userident_exit().
Referenced by tcmi_module_exit().
 {
     minfo(INFO1, "Unregistering TCMI syscalls hooks");
     tcmi_syscall_hooks_signal_exit();
     tcmi_syscall_hooks_pidman_exit();
     tcmi_syscall_hooks_userident_exit();
     tcmi_syscall_hooks_groupident_exit();
     tcmi_syscall_hooks_other_exit();
 }
static long tcmi_syscall_hooks_in_fork (struct task_struct * child) static
<<private>> in-fork...
performs attachement of guest/shadow task to TCMI
Definition at line 112 of file tcmi_syscallhooks_other.c.
References TCMI_MAN, and tcmi_man_fork().
Referenced by tcmi_syscall_hooks_other_init().
{
     if ( current->tcmi.task_type == guest ) {
         // Parent task is guest => child will be guest
         struct tcmi_penman* pen_man = tcmi_penman_get_instance();
         return tcmi_man_fork(TCMI_MAN(pen_man), current, child);
     } else if ( current->tcmi.task_type == shadow ) {
         // Parent task is shadow => child should be shadow
         struct tcmi_ccnman* ccn_man = tcmi_ccnman_get_instance();
         return tcmi_man_fork(TCMI_MAN(ccn_man), current, child);
     }
     return 0;
 }
int tcmi_syscall_hooks_init (void)
<<public>> Registers all syscalls hooks with the kernel.
<<public>> Registers all hooks with the kernel.
Returns
0 upon success
Definition at line 51 of file tcmi_syscallhooks.c.
References minfo, tcmi_syscall_hooks_groupident_init(), tcmi_syscall_hooks_other_init(), tcmi_syscall_hooks_pidman_init(), tcmi_syscall_hooks_signal_init(), and tcmi_syscall_hooks_userident_init().
Referenced by tcmi_module_init().
 {
     minfo(INFO1, "Registering TCMI syscalls hooks");
     tcmi_syscall_hooks_signal_init();
     tcmi_syscall_hooks_pidman_init();
     tcmi_syscall_hooks_userident_init();
     tcmi_syscall_hooks_groupident_init();
     tcmi_syscall_hooks_other_init();
     return 0;
 }
static long tcmi_syscall_hooks_post_fork (struct task_struct * child, long res, pid_t remote_pid, int __user * parent_tidptr, int __user * child_tidptr) static
<<private>> post-fork
Definition at line 131 of file tcmi_syscallhooks_other.c.
References director_task_fork(), mdbg, proxyfs_server_duplicate_all_parent(), tcmi_task::remote_pid, tcmi_guesttask_post_fork(), and TCMI_TASK.
Referenced by tcmi_syscall_hooks_other_init().
 {
     if ( current->tcmi.task_type == guest ) {
         // Guest task hook
         struct tcmi_task* child_task = NULL;
         if ( IS_ERR((void*)res) ) {
             mdbg(INFO3, "Resetting fork return values due to error");
             if ( parent_tidptr != NULL )
                 //put_user((int)-1, parent_tidptr);
             if ( child_tidptr != NULL ) {
                 //put_user((int)-1, child_tidptr);
             }
         } else {
             child_task = TCMI_TASK(child->tcmi.tcmi_task);
         }
         tcmi_guesttask_post_fork(TCMI_TASK(current->tcmi.tcmi_task), child_task, res, remote_pid);
         return remote_pid;
     } else if ( current->tcmi.task_type == shadow ) {
         // Shadow task hook
         // We have to duplicate all proxyfs file references for child.. this way we are in a same situation as
         // if the fork happend on CCN before the migration
         if (!IS_ERR((void*)res) ) {
             proxyfs_server_duplicate_all_parent(current, child);
         }
     }
     director_task_fork(res, current->pid);
     return res;
 };
static long tcmi_syscall_hooks_pre_fork (unsigned long clone_flags, unsigned long stack_start, struct pt_regs * regs, unsigned long stack_size, int __user * parent_tidptr, int __user * child_tidptr) static
<<private>> pre-fork
Definition at line 97 of file tcmi_syscallhooks_other.c.
References tcmi_guest_rpc, tcmi_rpc_call6(), and TCMI_RPC_SYS_FORK.
Referenced by tcmi_syscall_hooks_other_init().
   {
     // Pre-fork is hooked only on DN, on CN we fork normally
     if ( current->tcmi.task_type == guest ) {
         return tcmi_rpc_call6(tcmi_guest_rpc, TCMI_RPC_SYS_FORK, clone_flags, stack_start, (unsigned long)regs, stack_size, (unsigned long)parent_tidptr, (unsigned long)child_tidptr);
     }
     return 0;
 };
static long tcmi_syscall_hooks_sys_kill (int pid, int sig) static
<<private>> Kill system call hook.
Parameters
pid - PID of signal target
sig - what signal
Returns
- zero on sucess.
Definition at line 80 of file tcmi_syscallhooks_signal.c.
References tcmi_guest_rpc, tcmi_rpc_call2(), and TCMI_RPC_SYS_KILL.
Referenced by tcmi_syscall_hooks_signal_init().
 {
     return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_KILL, pid, sig);
 }
static long tcmi_syscall_hooks_sys_rt_sigqueueinfo (int pid, int sig, siginfo_t * info) static
<<private>> sys_rt_sigqueueinfo hook.
Parameters
pid - the PID of the thread
sig - signal to be sent
*info - pointer siginfo struct in kernel space
Returns
- zero on sucess.
Definition at line 109 of file tcmi_syscallhooks_signal.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_SIGQUEUE.
Referenced by tcmi_syscall_hooks_signal_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_SIGQUEUE, pid, sig, (unsigned long)info);
 }
static long tcmi_syscall_hooks_sys_wait4 (pid_t pid, int __user * stat_addr, int options, struct rusage __user * ru) static
<<private>> sys_wait4 system call hook.
Definition at line 89 of file tcmi_syscallhooks_other.c.
References tcmi_guest_rpc, tcmi_rpc_call4(), and TCMI_RPC_SYS_WAIT4.
Referenced by tcmi_syscall_hooks_other_init().
{
     return tcmi_rpc_call4(tcmi_guest_rpc, TCMI_RPC_SYS_WAIT4, pid, (unsigned long)stat_addr, options, (unsigned long)ru);
 };