Clondike: TCMI
TCMI
This <<singleton>> class is the base of the infrastructure and is responsible for initialization/shutdown of TCMI.
Modules
checkpointing component
<<Singleton>> class that creates a checkpoint of a process.
communication
Classes in this group provide TCMI communication features.
control filesystem
This <<singleton>> class represents TCMI control filesystem.
lib
Classes in this group provide basic objects used commonly throughout the whole framework.
managers
Classes in this group are responsible for various controlling tasks in the infrastructure.
migration
Classes in this group are responsible migration control in the infrastructure.
syscall forwarding
Classes in this group are used for system calls modification and forwarding to provide migration transparency.
task component
Classes in this group represent migrating processes in the system and related objects.
Functions
static int tcmi_debug_set (void *obj, void *data)
Method to set debug flag via a ctlfs file.
static int tcmi_debug_get (void *obj, void *data)
Reader of debug state from ctlfs file.
static int tcmi_send_generic_user_message_handler (int is_core_slot, int target_slot_index, int user_data_size, char *user_data)
static void tcmi_register_director_user_message_handler (void)
static int __init tcmi_module_init (void)
Module initialization.
static void __exit tcmi_module_exit (void)
Module cleanup.
Variables
static struct tcmi_ctlfs_entry * debug_file = NULL
Ctl FS file for setting/reading of debug settings.
Detailed Description
This <<singleton>> class is the base of the infrastructure and is responsible for initialization/shutdown of TCMI.
The initializition requires notifying CCN and/or PEN manager resp.
Initialized TCMI provides control in user space to:
migrate a process from a CCN to a PEN
migrate a process home from a PEN to a CCN
display information about migrated processes
connect a PEN to CCN
setup interfaces where CCN listens for incoming connections from PEN's
shutdown the whole infrastructure
Function Documentation
static int tcmi_debug_get (void * obj, void * data) static
Reader of debug state from ctlfs file.
Definition at line 90 of file tcmi_module.c.
Referenced by tcmi_module_init().
 {
     *((int *)data) = tcmi_dbg;
     return 0;
 }
static int tcmi_debug_set (void * obj, void * data) static
Method to set debug flag via a ctlfs file.
Definition at line 76 of file tcmi_module.c.
References minfo.
Referenced by tcmi_module_init().
 {
     int new_debug = *((int *)data);
     minfo(INFO3, "Setting TCMI debug to %d", new_debug);
     tcmi_dbg = new_debug;
     return 0;
 }
static void __exit tcmi_module_exit (void) static
Module cleanup.
Definition at line 168 of file tcmi_module.c.
References minfo, tcmi_ccnman_shutdown(), tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), tcmi_ctlfs_put_root(), tcmi_mighooks_exit(), tcmi_penman_shutdown(), and tcmi_syscall_hooks_exit().
 {
     minfo(INFO1, "Unloading TCMI framework");
     /* Managers must be shutdown first, because they may need other parts of infrastructure to proceed with migration back */
     tcmi_penman_shutdown();
     tcmi_ccnman_shutdown();
     tcmi_mighooks_exit();
     tcmi_syscall_hooks_exit();
     tcmi_ctlfs_file_unregister(debug_file);
     tcmi_ctlfs_entry_put(debug_file);
     tcmi_ctlfs_put_root();
     minfo(INFO1, "TCMI framework unloaded");
 }
static int __init tcmi_module_init (void) static
Module initialization.
Initializes 3 core components:
tcmi hooks in kernel
CCN manager - (when enabled in kernel)
PEN manager - (when enabled in kernel)
The resulting node setup depends how TCMI has been configured in kernel.
Returns
0 upon successfull initialization
Definition at line 122 of file tcmi_module.c.
References minfo, tcmi_ccnman_init(), tcmi_ccnman_shutdown(), tcmi_ctlfs_get_root(), tcmi_ctlfs_intfile_new(), tcmi_debug_get(), tcmi_debug_set(), tcmi_mighooks_init(), tcmi_penman_init(), tcmi_penman_shutdown(), TCMI_PERMS_FILE_RW, tcmi_register_director_user_message_handler(), and tcmi_syscall_hooks_init().
 {
     struct tcmi_ctlfs_entry *root;
     minfo(INFO1, "Loading the TCMI framework");
     tcmi_dbg = 1; // Enable debug temporarily at least for startup time
     root = tcmi_ctlfs_get_root();
     tcmi_mighooks_init();
     tcmi_syscall_hooks_init();
     tcmi_register_director_user_message_handler();
     if (tcmi_ccnman_init(root) < 0) {
         minfo(ERR1, "Failed initializing TCMI CCN manager");
         goto exit0;
     }
     if (tcmi_penman_init(root) < 0) {
         minfo(ERR1, "Failed initializing TCMI PEN manager");
         goto exit1;
     }
         debug_file = tcmi_ctlfs_intfile_new(root, TCMI_PERMS_FILE_RW,
                  NULL, tcmi_debug_get, tcmi_debug_set,
                  sizeof(int), "debug");
     if ( !debug_file ) {
         minfo(ERR1, "Failed to create debug control file");
         goto exit2;
     }
     minfo(INFO1, "TCMI framework loaded");
     tcmi_dbg = 0; // Startup succeeded, disable debug, it can be reenabled via ctlfs
     return 0;
     /* error handling */
  exit2:
     tcmi_penman_shutdown();
  exit1:
     tcmi_ccnman_shutdown();
  exit0:
     return -EINVAL;
 }
static void tcmi_register_director_user_message_handler (void) static
Definition at line 105 of file tcmi_module.c.
References director_register_send_generic_user_message_handler(), and tcmi_send_generic_user_message_handler().
Referenced by tcmi_module_init().
{
     director_register_send_generic_user_message_handler(tcmi_send_generic_user_message_handler);
 }
static int tcmi_send_generic_user_message_handler (int is_core_slot, int target_slot_index, int user_data_size, char * user_data) static
Definition at line 97 of file tcmi_module.c.
References TCMI_MAN, and tcmi_man_send_generic_user_message().
Referenced by tcmi_register_director_user_message_handler().
{
     if ( is_core_slot ) {
         return tcmi_man_send_generic_user_message(TCMI_MAN(tcmi_ccnman_get_instance()), target_slot_index, user_data_size, user_data);
     } else {
         return tcmi_man_send_generic_user_message(TCMI_MAN(tcmi_penman_get_instance()), target_slot_index, user_data_size, user_data);
     }
 }
Variable Documentation
struct tcmi_ctlfs_entry* debug_file = NULL static
Ctl FS file for setting/reading of debug settings.
Definition at line 71 of file tcmi_module.c.