Clondike: tcmi_sock class
tcmi_sock class
lib
This class is a wrapper for KKC socket.
Data Structures
struct tcmi_sock
A compound structure that holds the actual KKC listening.
Macros
#define TCMI_SOCK(l) ((struct tcmi_sock *)l)
Casts to a tcmi_sock instance.
Functions
static int tcmi_sock_getsockname (void *object, void *data)
<<private>> Asks the KKC socket to supply its localname.
static int tcmi_sock_getpeername (void *object, void *data)
<<private>> Asks the KKC socket to supply its peername.
static int tcmi_sock_getarchname (void *object, void *data)
<<private>> Asks the KKC socket to supply its peername.
struct tcmi_sock * tcmi_sock_new (struct tcmi_ctlfs_entry *root, struct kkc_sock *sock, const char namefmt[],...)
<<public>> TCMI socket constructor.
static struct kkc_sock * tcmi_sock_kkc_sock_get (struct tcmi_sock *self)
<<public>> KKC socket accessor.
static struct tcmi_sock * tcmi_sock_get (struct tcmi_sock *self)
<<public>> Instance accessor.
static tcmi_slot_node_t * tcmi_sock_node (struct tcmi_sock *self)
<<public>> Sock node accessor.
void tcmi_sock_put (struct tcmi_sock *self)
<<public>> Releases the instance.
Detailed Description
This class is a wrapper for KKC socket.
It provides a TCMI ctlfs user interface, that allows the user to read information about the socket - local name, peername and architecture.
Sockets are meant to be stored in a slot vector . For that reason they provide a slot node, so that they can be linked into the slotvector.
There is no need for additional lock since access to the data structures from user space is serialized via the TCMI ctlfs files. Other kernel threads accessing the socket don't manipulate its internal datastructures, except for the last thread that destroys it. This protection is implemented by standard reference counting.
Data Structure Documentation
struct tcmi_sock
A compound structure that holds the actual KKC listening.
Definition at line 67 of file tcmi_sock.h.
Data Fields
struct tcmi_ctlfs_entry * d_id TCMI ctlfs directory where there are the control files of the listening.
The name is based on slot index
struct tcmi_ctlfs_entry * f_archname TCMI ctlfs - shows the architecture name.
struct tcmi_ctlfs_entry * f_peername TCMI ctlfs - shows the remote socketa addres - meaningful for connected sockets only.
struct tcmi_ctlfs_entry * f_sockname TCMI ctlfs - shows the local socket address.
tcmi_slot_node_t node A slot node, used for insertion the listening into a slot.
atomic_t ref_count Instance reference counter.
struct kkc_sock * sock KKC socket contained in the instance.
Macro Definition Documentation
#define TCMI_SOCK (l) ((struct tcmi_sock *)l)
Casts to a tcmi_sock instance.
Definition at line 150 of file tcmi_sock.h.
Referenced by tcmi_sock_getarchname(), tcmi_sock_getpeername(), and tcmi_sock_getsockname().
Function Documentation
static struct tcmi_sock* tcmi_sock_get (struct tcmi_sock * self) static read
<<public>> Instance accessor.
increments the reference counter. The user is now guaranteed, that the instance stays in memory while he is using it.
Parameters
*self - pointer to this instance
Returns
tcmi_sock instance
Definition at line 119 of file tcmi_sock.h.
References self.
Referenced by tcmi_ccnman_thread().
 {
     if (self) {
 /*      mdbg(CRIT4, "Incrementing ref. count(%d) of local:'%s', remote:'%s' (%p)",
              atomic_read(&self->ref_count),
              kkc_sock_getsockname2(tcmi_sock_kkc_sock_get(self)),
              kkc_sock_getpeername2(tcmi_sock_kkc_sock_get(self)), self);
 */
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static int tcmi_sock_getarchname (void * object, void * data) static
<<private>> Asks the KKC socket to supply its peername.
Parameters
*object - pointer to this tcmi socket instance
*data - storage for the architecture string
Returns
0 upon success
Definition at line 190 of file tcmi_sock.c.
References KKC_MAX_ARCH_LENGTH, kkc_sock_getarchname(), self, and TCMI_SOCK.
Referenced by tcmi_sock_new().
 {
     struct tcmi_sock *self = TCMI_SOCK(object);
     kkc_sock_getarchname(self->sock, data, KKC_MAX_ARCH_LENGTH);
     return 0;
 }
static int tcmi_sock_getpeername (void * object, void * data) static
<<private>> Asks the KKC socket to supply its peername.
Parameters
*object - pointer to this tcmi socket instance
*data - storage for the peername string
Returns
0 upon success
Definition at line 175 of file tcmi_sock.c.
References kkc_sock_getpeername(), KKC_SOCK_MAX_ADDR_LENGTH, self, and TCMI_SOCK.
Referenced by tcmi_sock_new().
 {
     struct tcmi_sock *self = TCMI_SOCK(object);
     kkc_sock_getpeername(self->sock, data, KKC_SOCK_MAX_ADDR_LENGTH);
     return 0;
 }
static int tcmi_sock_getsockname (void * object, void * data) static
<<private>> Asks the KKC socket to supply its localname.
Parameters
*object - pointer to this tcmi socket instance
*data - storage for the localname string
Returns
0 upon success
Definition at line 160 of file tcmi_sock.c.
References kkc_sock_getsockname(), KKC_SOCK_MAX_ADDR_LENGTH, self, and TCMI_SOCK.
Referenced by tcmi_sock_new().
 {
     struct tcmi_sock *self = TCMI_SOCK(object);
     kkc_sock_getsockname(self->sock, data, KKC_SOCK_MAX_ADDR_LENGTH);
     return 0;
 }
static struct kkc_sock* tcmi_sock_kkc_sock_get (struct tcmi_sock * self) static read
<<public>> KKC socket accessor.
Reference counter of the KKC socket is not adjusted as the socket is part of the tcmi_sock instance. The caller is expected to have a valid reference to the tcmi_sock instance.
Parameters
*self - pointer to this instance
Returns
tcmi_sock instance
Definition at line 104 of file tcmi_sock.h.
Referenced by tcmi_ccnman_remove_sleepers(), tcmi_ccnman_thread(), and tcmi_migman_sock().
 {
     if (!self)
         return NULL;
     return self->sock;
 }
struct tcmi_sock* tcmi_sock_new (struct tcmi_ctlfs_entry * root, struct kkc_sock * k_sock, const char namefmt[], ...) read
<<public>> TCMI socket constructor.
A listening is constructed as follows:
a new instance is allocated
a new socket directory is created in the root directory. The name of the directory is specified by the method caller.
localname, peername and archname control files are crated
Parameters
*root - directory which all listening control files and its main directory will reside in.
*k_sock - KKC socket, that this instance is to present in ctlfs
namefmt - nameformat string (printf style)
Returns
- a new tcmi_sock instance or NULL
Definition at line 58 of file tcmi_sock.c.
References args, tcmi_sock::d_id, tcmi_sock::f_archname, tcmi_sock::f_peername, tcmi_sock::f_sockname, KKC_MAX_ARCH_LENGTH, kkc_sock_get(), kkc_sock_getsockname2(), KKC_SOCK_MAX_ADDR_LENGTH, kkc_sock_put(), mdbg, tcmi_sock::ref_count, tcmi_sock::sock, tcmi_ctlfs_dir_vnew(), tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), tcmi_ctlfs_strfile_new(), TCMI_PERMS_DIR, TCMI_PERMS_FILE_R, tcmi_sock_getarchname(), tcmi_sock_getpeername(), and tcmi_sock_getsockname().
Referenced by tcmi_ccnman_listen(), and tcmi_migman_init().
 {
     struct tcmi_sock *t_sock;
     va_list args;
     va_start(args, namefmt);
     mdbg(INFO3, "Creating new TCMI socket");
     if (!(t_sock = kmalloc(sizeof(struct tcmi_sock), GFP_KERNEL))) {
         mdbg(ERR3, "Failed to allocate memory for tcmi socket '%s'",
              kkc_sock_getsockname2(k_sock));
         goto exit0;
     }
     /* create KKC t_sock */
     atomic_set(&t_sock->ref_count, 1);
     t_sock->sock = kkc_sock_get(k_sock);
     /* main t_sock directory named after the index of its slot */
     if (!(t_sock->d_id =
           tcmi_ctlfs_dir_vnew(root, TCMI_PERMS_DIR, namefmt, args)))
         goto exit1;
     if (!(t_sock->f_sockname =
           tcmi_ctlfs_strfile_new(t_sock->d_id, TCMI_PERMS_FILE_R,
                      t_sock, tcmi_sock_getsockname, NULL,
                      KKC_SOCK_MAX_ADDR_LENGTH, "sockname")))
         goto exit2;
     if (!(t_sock->f_peername =
           tcmi_ctlfs_strfile_new(t_sock->d_id, TCMI_PERMS_FILE_R,
                      t_sock, tcmi_sock_getpeername, NULL,
                      KKC_SOCK_MAX_ADDR_LENGTH, "peername")))
         goto exit3;
     if (!(t_sock->f_archname =
           tcmi_ctlfs_strfile_new(t_sock->d_id, TCMI_PERMS_FILE_R,
                      t_sock, tcmi_sock_getarchname, NULL,
                      KKC_MAX_ARCH_LENGTH, "archname")))
         goto exit4;
     va_end(args);
     mdbg(INFO4, "Allocated new TCMI socket memory=%p", t_sock);
     return t_sock;
     /* error handling */
  exit4:
     tcmi_ctlfs_file_unregister(t_sock->f_peername);
     tcmi_ctlfs_entry_put(t_sock->f_peername);
  exit3:
     tcmi_ctlfs_file_unregister(t_sock->f_sockname);
     tcmi_ctlfs_entry_put(t_sock->f_sockname);
  exit2:
     tcmi_ctlfs_entry_put(t_sock->d_id);
  exit1:
     kkc_sock_put(t_sock->sock);
     kfree(t_sock);
     va_end(args);
  exit0:
     return NULL;
 }
static tcmi_slot_node_t* tcmi_sock_node (struct tcmi_sock * self) inline static
<<public>> Sock node accessor.
Parameters
*self - pointer to this instance
Returns
tcmi_slot_node
Definition at line 139 of file tcmi_sock.h.
Referenced by tcmi_ccnman_listen(), and tcmi_ccnman_thread().
 {
     if (!self)
         return NULL;
     return &self->node;
 }
void tcmi_sock_put (struct tcmi_sock * self)
<<public>> Releases the instance.
<<public>> Releases the instance.
Unregistering the file is safe as the access is internally serialized by TCMI ctlfs - the instance is removed from the file and drop its reference counter.
Parameters
*self - pointer to this listening instance
Definition at line 128 of file tcmi_sock.c.
References kkc_sock_put(), mdbg, self, tcmi_ctlfs_entry_put(), and tcmi_ctlfs_file_unregister().
Referenced by tcmi_ccnman_stop_listen_all(), tcmi_ccnman_stop_listen_one(), tcmi_ccnman_thread(), tcmi_migman_free(), and tcmi_migman_init().
 {
     if (self && atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying TCMI socket memory=%p", self);
         tcmi_ctlfs_file_unregister(self->f_archname);
         tcmi_ctlfs_entry_put(self->f_archname);
         tcmi_ctlfs_file_unregister(self->f_peername);
         tcmi_ctlfs_entry_put(self->f_peername);
         tcmi_ctlfs_file_unregister(self->f_sockname);
         tcmi_ctlfs_entry_put(self->f_sockname);
         tcmi_ctlfs_entry_put(self->d_id);
         kkc_sock_put(self->sock);
         kfree(self);
     }
 }