Clondike: checkpointing component
checkpointing component
TCMI
<<Singleton>> class that creates a checkpoint of a process.
Modules
tcmi_ckpt class
This is a helper class used by the checkpointing component that provides functionality to:
Functions
int tcmi_ckptcom_checkpoint_ppm (struct file *file, struct pt_regs *regs, int heavy)
<<public>> Creates a preemptive process checkpoint.
int tcmi_ckptcom_checkpoint_npm (struct file *file, struct pt_regs *regs, struct tcmi_npm_params *params)
<<public>> Creates a non-preemptive process checkpoint.
int tcmi_ckptcom_restart (struct linux_binprm *bprm, struct pt_regs *regs)
<<public>> Restarts a process from a checkpoint (new binfmt handler).
Variables
static struct linux_binfmt tcmi_ckptcom_format
Initialize the new checkpoint binary format.
Detailed Description
<<Singleton>> class that creates a checkpoint of a process.
It uses the checkpoint class as a temporary object to store the state of the process.
It provides a simple interface that that allows:
creating a checkpoint into a specified file
restoring the checkpoint via a new bin_fmt handler that it registers in the kernel.
While creating a checkpoint there are two types of checkpoints supported - heavy and light. See tcmi_ckptcom_checkpoint() for explanation.
Function Documentation
int tcmi_ckptcom_checkpoint_npm (struct file * file, struct pt_regs * regs, struct tcmi_npm_params * params)
<<public>> Creates a non-preemptive process checkpoint.
Definition at line 168 of file tcmi_ckptcom.c.
References tcmi_ckptcom_checkpoint().
Referenced by tcmi_taskhelper_checkpoint().
{
     return tcmi_ckptcom_checkpoint(file, regs, 0, params);
 }
int tcmi_ckptcom_checkpoint_ppm (struct file * file, struct pt_regs * regs, int heavy)
<<public>> Creates a preemptive process checkpoint.
Definition at line 163 of file tcmi_ckptcom.c.
References tcmi_ckptcom_checkpoint().
Referenced by tcmi_taskhelper_checkpoint().
{
     return tcmi_ckptcom_checkpoint(file, regs, heavy, NULL);
 }
int tcmi_ckptcom_restart (struct linux_binprm * bprm, struct pt_regs * regs)
<<public>> Restarts a process from a checkpoint (new binfmt handler).
This consists of:
creating a new checkpoint instance
reading a checkpoint header - might fail, if the magic number doesn't match.
reading open files
reading memory descriptor
reading memory areas along with pages
reading process state (registers)
reading signal handlers
Parameters
*bprm - binary object that is passed to this method by execve and contains a pointer to the executable file
*regs - references the registers of the process, so that they can be overlayed from the checkpoint.
Returns
0 upon success
Definition at line 191 of file tcmi_ckptcom.c.
References tcmi_npm_params::args, tcmi_npm_params::argsc, tcmi_ckpt_hdr::checkpoint_arch, tcmi_npm_params::envp, tcmi_npm_params::envpc, tcmi_npm_params::file_name, tcmi_ckpt::hdr, tcmi_ckpt_hdr::is_32bit_application, tcmi_ckpt_hdr::is_npm, mdbg, memory_sanity_check, minfo, tcmi_ckpt_check_magic(), tcmi_ckpt_fsstruct_read(), tcmi_ckpt_mm_read(), tcmi_ckpt_new(), tcmi_ckpt_npm_params_read(), tcmi_ckpt_put(), tcmi_ckpt_read_files(), tcmi_ckpt_read_hdr(), tcmi_ckpt_read_rlimit(), tcmi_ckpt_read_vmas(), tcmi_ckpt_regs_read(), tcmi_ckpt_sig_read(), tcmi_ckpt_tls_read(), tcmi_ckptcom_format, and tcmi_resolve_restart_block().
 {
     struct tcmi_ckpt *ckpt;
     struct pt_regs* original_regs;
 //  int i;
     u64 beg_time = 0, end_time = 0;
     beg_time = cpu_clock(smp_processor_id());
 memory_sanity_check("Start");
     original_regs = kmalloc(sizeof(struct pt_regs), GFP_KERNEL);
     if ( !original_regs )
         return -ENOMEM;
     if (!tcmi_ckpt_check_magic(bprm->buf)) {
         goto exit0;
     }
     mdbg(INFO3, "Restarting '%s'", bprm->filename);
     if (!(ckpt = tcmi_ckpt_new(bprm->file))) {
         mdbg(ERR3, "Failed to instantiate a checkpoint");
         goto exit0;
     }
     if (tcmi_ckpt_read_hdr(ckpt) < 0) {
         mdbg(ERR3, "Error reading checkpoint header!");
         goto exit1;
     }
 memory_sanity_check("Post header");
     /* Flush all traces of the currently running executable */
     if (flush_old_exec(bprm)) {
         mdbg(ERR3, "Error flushing the old execution context!");
         goto exit0;
     }
 memory_sanity_check("Pre-rlimit");
     if (tcmi_ckpt_read_rlimit(ckpt, current) < 0) {
         mdbg(ERR3, "Error reading checkpoint rlimit!");
         goto exit1;
     }
 memory_sanity_check("Post-rlimit");
     // Replaced macro FD_ISSET to function test_bit with equal parameters by Jiri Rakosnik
   if ( test_bit(0, current->files->fdt->open_fds) ) {
         mdbg(INFO3, "Closing open fs.. this should not happend though..");
         sys_close(0);
     }
 memory_sanity_check("Pre files");
     if (tcmi_ckpt_read_files(ckpt) < 0) {
         mdbg(ERR3, "Error reading checkpoint files!");
         goto exit1;
     }
 memory_sanity_check("Post - files");
     if (tcmi_ckpt_mm_read(ckpt) < 0) {
         mdbg(ERR3, "Error reading memory descriptor!");
         goto exit1;
     }
 memory_sanity_check("Post mm");
     if ( !ckpt->hdr.is_npm ) {
         if (tcmi_ckpt_read_vmas(ckpt) < 0) {
             mdbg(ERR3, "Error reading VM areas");
             goto exit1;
         }
     }
     *original_regs = *regs;
     if (tcmi_ckpt_regs_read(ckpt, regs) < 0) {
         mdbg(ERR3, "Error reading processor registers descriptor!");
         goto exit1;
     }
     if (tcmi_ckpt_tls_read(ckpt, current, regs) < 0) {
         mdbg(ERR3, "Error reading process tls!");
         goto exit1;
     }
     if (tcmi_ckpt_fsstruct_read(ckpt, current) < 0) {
         mdbg(ERR3, "Error reading process fsstruct!");
         goto exit1;
     }
     if (tcmi_ckpt_sig_read(ckpt) < 0) {
         mdbg(ERR3, "Error reading signals informations!");
         goto exit1;
     }
     if ( ckpt->hdr.is_npm ) {
         struct tcmi_npm_params* params = vmalloc(sizeof(struct tcmi_npm_params));
         int exec_result = -EFAULT;
         mm_segment_t old_fs;
         *regs = *original_regs;
         if ( !params ) {
             mdbg(ERR3, "Cannot allocate memory for npm params!");
             goto exit1;
         }
         if (tcmi_ckpt_npm_params_read(ckpt, params) < 0) {
             mdbg(ERR3, "Error reading npm params!");
             goto exit1;
         }
         tcmi_ckpt_put(ckpt);
         // TEMPORARY DEBUG!
         if ( current->mm )
             mdbg(INFO2, "MM %p nr_ptes: %lu", current->mm, current->mm->nr_ptes);
         if ( current->active_mm )
             mdbg(INFO2, "ACTIVE %p MM nr_ptes: %lu", current->active_mm, current->active_mm->nr_ptes);
         // TODO: This is something REALLY NASTY! Some better solution is appreciated
         if ( current->mm ) {
             current->mm->nr_ptes = 0;
         }
         old_fs = get_fs();
         set_fs(KERNEL_DS);
         // TEMPORARY DEBUG!
         if ( current->mm )
             mdbg(INFO2, "MM %p nr_ptes: %lu", current->mm, current->mm->nr_ptes);
         if ( current->active_mm )
             mdbg(INFO2, "ACTIVE %p MM nr_ptes: %lu", current->active_mm, current->active_mm->nr_ptes);
         // We have to unlock temprarily guar to prevent recursive lock (we are calling recursive exceve). TODO: Some better solution?
         // Moved cred_guard_mutex to struct signal in new kernel 3.x.x => Fix by Jiri Rakosnik
     mutex_unlock(&current->signal->cred_guard_mutex);
         current->fs->in_exec = 0; // Required to pass through 'check_unsafe_exec'
         mdbg(INFO3, "Going to execute '%s', Args: %d, Envps %d", params->file_name, params->argsc, params->envpc);
         //mdbg(INFO3, "Arg[0] '%s', Envp[0] '%s'", params->args[0], params->envp[0]);
         exec_result = do_execve(params->file_name, (const char __user * const __user *)params->args, (const char __user * const __user *)params->envp, regs);
         mdbg(INFO3, "NPM internal execution result %d", exec_result);
         // And now we relock again as the relock of outer execve will be attempted.
         // Moved cred_guard_mutex to struct signal in new kernel 3.x.x => Fix by Jiri Rakosnik
     if (mutex_lock_interruptible(&current->signal->cred_guard_mutex)) {
             minfo(ERR3, "Failed to relock cred guard!");
         }
         // TODO: How do we release reference to the binmt of the module that was used for this execve.. ?
         // Do we have to call "set_binfmt(&tcmi_ckptcom_format);" here or can we release it here?
         set_fs(old_fs);
         vfree(params);
         mdbg(INFO3, "NPM after param free");
         if ( exec_result ) {// In case of error of internal execution, we have to return ENOEXEC
             return -EFAULT;
         }
         end_time = cpu_clock(smp_processor_id());
         mdbg(INFO3, "Checkpoint NPM took '%llu' ms.'", (end_time - beg_time) / 1000000);
         printk("Checkpoint NPM took '%llu' ms.\n'", (end_time - beg_time) / 1000000);
         return 0;
     } else {
         // Restart fixup is performed only in PPM
         tcmi_resolve_restart_block(current, regs, ckpt->hdr.checkpoint_arch, ckpt->hdr.is_32bit_application);
     }
     kfree(original_regs);
     /* flush_signals(current);*/
     tcmi_ckpt_put(ckpt);
     /* successul execution of the image - need to set the format */
     set_binfmt(&tcmi_ckptcom_format);
   end_time = cpu_clock(smp_processor_id());
     mdbg(INFO3, "Checkpoint PPM took '%llu' ms.'", (end_time - beg_time) / 1000000);
     printk("Checkpoint PPM took '%llu' ms.\n'", (end_time - beg_time) / 1000000);
     /* Something went wrong, return the inode and free the argument pages*/
 /*
 What is the point of the following code? It does not really seem to free memory, but in any case, it does not compile on latest kernels ;)
     for (i = 0 ; i < MAX_ARG_PAGES ; i++) {
         bprm->page[i] = NULL;
     }
 */
     return 0;
     /* error handling */
  exit1:
     tcmi_ckpt_put(ckpt);
  exit0:
     return -ENOEXEC;
 }
Variable Documentation
struct linux_binfmt tcmi_ckptcom_format static
Initial value:
= {
    .module = THIS_MODULE,
    .load_binary = tcmi_ckptcom_restart,
    .core_dump = tcmi_core_dump,
    .min_coredump = 0
}
Initialize the new checkpoint binary format.
Definition at line 414 of file tcmi_ckptcom.c.
Referenced by tcmi_ckptcom_exit(), tcmi_ckptcom_init(), and tcmi_ckptcom_restart().