Clondike: tcmi_taskhelper class
tcmi_taskhelper class
task component
This <<singleton>> class implements platform specific methods that make handling TCMI tasks easier.
Functions
static int tcmi_taskhelper_run_mig_mode_handler (void)
Runs migration mode handler of the current process.
static void tcmi_taskhelper_enter_mig_mode (struct tcmi_task *t_task)
<<public>> Switches the task into migration mode.
static void tcmi_taskhelper_enter_mig_mode_exclusive (struct task_struct *l_task, struct tcmi_task *t_task)
<<public>> Same as standard enter_mig_mode, but in this case we have already a reference to current task, so we do not perform any locking
static struct tcmi_task * tcmi_taskhelper_find_by_pid (pid_t pid)
<<public>> Finds a TCMI task based on PID, in addition checks whether the task has a valid migration mode handler assigned.
static int tcmi_taskhelper_notify_by_pid (pid_t pid, tcmi_method_t *method, void *data, int size, int priority)
<<public>> Submits a specified method to a TCMI task identified by PID.
static int tcmi_taskhelper_wait_for_pick_up_timeout (struct tcmi_task *t_task, unsigned long timeout)
<<public>> Synchronizes with a task entering the migration mode for the first time.
static int tcmi_taskhelper_do_signals (struct tcmi_task *t_task)
<<public>> Checks if there are any pending signals and handles them.
static void tcmi_taskhelper_flush_signals (struct tcmi_task *t_task)
<<public>> Flushes all pending signals of the task.
static int tcmi_taskhelper_attach (struct tcmi_task *t_task, mig_mode_handler_t *mig_mode_handler)
<<public>> Attaches the TCMI task to its kernel task.
static int tcmi_taskhelper_attach_exclusive (struct task_struct *l_task, struct tcmi_task *t_task, mig_mode_handler_t *mig_mode_handler)
<<public>> Same as standard attach, but here we have a reference to a real task and we are exclusive owner of this reference and the task is not yet running => no locking required.
static struct tcmi_task * __tcmi_taskhelper_detach (struct task_struct *l_task)
<<private>> Dettaches the TCMI task from a specified process - lock free version.
static struct tcmi_task * tcmi_taskhelper_detach (void)
<<public>> Dettaches the TCMI task from its process The user specifies only kernel task, that is to be handled.
static struct tcmi_task * tcmi_taskhelper_detach_by_pid (pid_t pid)
<<public>> Dettaches the TCMI task from its process.
static struct tcmi_task * tcmi_taskhelper_sanity_check (void)
<<public>> This method is intended for migration mode handler, it should be the very first check it performs.
static void tcmi_taskhelper_do_mig_mode (struct pt_regs *regs)
<<public>> This method is registered by CCN or PEN component as the SIGUNUSED signal handler.
static int tcmi_taskhelper_notify_current (tcmi_method_t *method, void *data, int size, int priority)
<<public>> current process notification - submission of a method.
static int tcmi_taskhelper_checkpoint (struct tcmi_task *t_task, struct tcmi_npm_params *npm_params)
<<public>> Creates a new checkpoint of the process.
static int tcmi_taskhelper_restart (struct tcmi_task *t_task, char *ckpt_name)
<<public>> Schedules a task restart from a given checkpoint image.
static void tcmi_taskhelper_flushfiles (void)
<<public>> Flushing files is required prior to issuing a migrate request.
static void tcmi_taskhelper_catch_all_signals (struct k_sigaction *action)
<<public>> Set action for all signals accept SIGKILL and SIGSTOP
Detailed Description
This <<singleton>> class implements platform specific methods that make handling TCMI tasks easier.
The functionality includes:
method to switch a task into migration mode
method to submit a specific method to a TCMI task and have it process the method
synchronization with a task entering the migration mode for the
OS specific basic signal handling
Function Documentation
static struct tcmi_task* __tcmi_taskhelper_detach (struct task_struct * l_task) static read
<<private>> Dettaches the TCMI task from a specified process - lock free version.
This method is intended for internal use only. It resets all TCMI related data in the specified process and returns the TCMI task pointer. It is user responsibility to ensure proper locking.
Returns
TCMI task that has been detached.
Definition at line 426 of file tcmi_taskhelper.h.
Referenced by tcmi_taskhelper_detach(), and tcmi_taskhelper_detach_by_pid().
 {
     struct tcmi_task *tmp;
     tmp = l_task->tcmi.tcmi_task;
     l_task->tcmi.tcmi_task = NULL;
     l_task->tcmi.mig_mode_handler = NULL;
     if ( l_task->tcmi.task_type == shadow )
         l_task->tcmi.task_type = shadow_detached;
     return tmp;
 }
static int tcmi_taskhelper_attach (struct tcmi_task * t_task, mig_mode_handler_t * mig_mode_handler) inline static
<<public>> Attaches the TCMI task to its kernel task.
This requires:
looking up the target thread (denoted by task's local PID)
checking if there has been assigned no handler/task assigned yet
storing the specified handler+task inside the kernel task(process)
The target kernel task will have an extra reference to the task.
Parameters
*t_task - pointer to the TCMI task that is to be attached
*mig_mode_handler - migration mode handler specific to the task.
Returns
0 upon success.
Definition at line 339 of file tcmi_taskhelper.h.
References mdbg, task_find_by_pid(), tcmi_task_get(), tcmi_task_get_type(), and tcmi_task_local_pid().
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), and tcmi_migcom_immigrate().
 {
     int err = -EINVAL;
     struct task_struct *l_task;
     /* try finding the target process for our TCMI task by PID */
     read_lock_irq(&tasklist_lock);
     if (!(l_task = task_find_by_pid(tcmi_task_local_pid(t_task)))) {
         mdbg(ERR3, "No such process %d", tcmi_task_local_pid(t_task));
         err = -ESRCH;
         goto exit0;
     }
     /* synchronize with the migration mode handler that might run in paralle */
     task_lock(l_task);
     if (l_task->tcmi.mig_mode_handler || l_task->tcmi.tcmi_task) {
         mdbg(ERR3, "Kernel task %d already has a mig. mode handler - %p "
              "or TCMI task - %p assigned, bailing out",
               tcmi_task_local_pid(t_task), l_task->tcmi.mig_mode_handler,
              l_task->tcmi.tcmi_task);
         task_unlock(l_task);
         goto exit0;
     }
     l_task->tcmi.mig_mode_handler = mig_mode_handler;
     /* extra reference on TCMI task for the target process/its
      * migration component resp. */
     l_task->tcmi.tcmi_task = tcmi_task_get(t_task);
     l_task->tcmi.task_type = tcmi_task_get_type(t_task);
     task_unlock(l_task);
     read_unlock_irq(&tasklist_lock);
     return 0;
     /* error handling */
  exit0:
     read_unlock_irq(&tasklist_lock);
     return err;
 }
static int tcmi_taskhelper_attach_exclusive (struct task_struct * l_task, struct tcmi_task * t_task, mig_mode_handler_t * mig_mode_handler) inline static
<<public>> Same as standard attach, but here we have a reference to a real task and we are exclusive owner of this reference and the task is not yet running => no locking required.
Parameters
*l_task - pointer to a kernel task struct, to which we are attaching
*t_task - pointer to the TCMI task that is to be attached
*mig_mode_handler - migration mode handler specific to the task.
Returns
0 upon success.
Definition at line 391 of file tcmi_taskhelper.h.
References mdbg, tcmi_task_get(), tcmi_task_get_type(), and tcmi_task_local_pid().
Referenced by tcmi_migcom_guest_fork(), and tcmi_migcom_shadow_fork().
 {
     int err = -EINVAL;
     if (l_task->tcmi.mig_mode_handler || l_task->tcmi.tcmi_task) {
         mdbg(ERR3, "Kernel task %d already has a mig. mode handler - %p "
              "or TCMI task - %p assigned, bailing out",
               tcmi_task_local_pid(t_task), l_task->tcmi.mig_mode_handler,
              l_task->tcmi.tcmi_task);
         goto exit0;
     }
     l_task->tcmi.mig_mode_handler = mig_mode_handler;
     /* extra reference on TCMI task for the target process/its
      * migration component resp. */
     l_task->tcmi.tcmi_task = tcmi_task_get(t_task);
     l_task->tcmi.task_type = tcmi_task_get_type(t_task);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static void tcmi_taskhelper_catch_all_signals (struct k_sigaction * action) inline static
<<public>> Set action for all signals accept SIGKILL and SIGSTOP
Parameters
*action - struct k_sigaction, which will be set to all signals
Definition at line 756 of file tcmi_taskhelper.h.
Referenced by tcmi_shadowtask_emigrate_p().
 {
     int i;
     for( i = 1; i < _NSIG; i++ ){
         if( i != SIGKILL && i != SIGSTOP )
             do_sigaction( i, action, NULL );
     }
 }
static int tcmi_taskhelper_checkpoint (struct tcmi_task * t_task, struct tcmi_npm_params * npm_params) inline static
<<public>> Creates a new checkpoint of the process.
It might be a good idea to delete the old checkpoint too. This method has to be called from the context of the process that is to be checkpointed.
The checkpoint name is composed of the process name stored in current->comm pid and current value of jiffies. Once the checkpoint name is complete, it is stored in the task instance(so that it can be accessed later on).
a new checkpoint file is open(created)
file object along with task context is passed onto the checkpointing component.
Parameters
*t_task - pointer to the TCMI task that is to be checkpointed. *npm_params - Pointer to non-preemtive migration params (or null in case of preemptive migration)
Returns
0 upon success
Definition at line 620 of file tcmi_taskhelper.h.
References envp, mdbg, tcmi_ckptcom_checkpoint_npm(), tcmi_ckptcom_checkpoint_ppm(), tcmi_task_context(), and tcmi_task_prepare_execve().
Referenced by tcmi_guesttask_migrateback_p(), and tcmi_shadowtask_emigrate_p().
 {
     /* page for the filepathname */
     unsigned long page;
     char *pathname = NULL;
     struct file *file;
     char *argv[] = { NULL };
     char *envp[] = { NULL };
     /* resolve the path name. */
     if (!(page = __get_free_page(GFP_ATOMIC))) {
         mdbg(ERR3, "Can't allocate page for file pathname!");
         goto exit0;
     }
     pathname = (char*) page;
     snprintf(pathname, PAGE_SIZE, "/home/clondike/%s.%d.%lu", current->comm,
          current->pid, jiffies);
     mdbg(INFO3, "Composed checkpoint name: '%s' Npm params: %p", pathname, npm_params);
     /* setup execve arguments - this is just to store checkpoint name in the instance */
     if (tcmi_task_prepare_execve(t_task, pathname, argv, envp) < 0) {
         mdbg(ERR3, "Failed preparing execve of the checkpoint '%s'", pathname);
         goto exit1;
     }
     /* Ask the checkpointing component for a checkpoint */
     file = filp_open(pathname,
              O_CREAT | O_RDWR  | O_NOFOLLOW | O_LARGEFILE | O_TRUNC, 0700);
     if (IS_ERR(file)) {
         mdbg(ERR3, "Failed to create a checkpoint file for pid %d. Ckptname = '%s'. Error: %ld", current->pid,
              pathname, PTR_ERR(file));
         goto exit1;
     }
     /* create the checkpoint, task context contains pointer to process registers */
     if ( npm_params ) {
         // Non-preemptive checkpoint
         if (tcmi_ckptcom_checkpoint_npm(file, tcmi_task_context(t_task), npm_params) < 0) {
             mdbg(ERR3, "Failed npm checkpointing process PID %d ckptname = '%s'", current->pid,
             pathname);
             goto exit2;
         }
     } else {
         // Preemptive checkpoint
         if (tcmi_ckptcom_checkpoint_ppm(file, tcmi_task_context(t_task), 1) < 0) {
             mdbg(ERR3, "Failed ppm checkpointing process PID %d ckptname = '%s'", current->pid,
             pathname);
             goto exit2;
         }
     }
     filp_close(file, NULL);
     free_page(page);
     return 0;
     /* error handling */
  exit2:
     filp_close(file, NULL);
  exit1:
     free_page(page);
  exit0:
     return -EINVAL;
 }
static struct tcmi_task* tcmi_taskhelper_detach (void) static read
<<public>> Dettaches the TCMI task from its process The user specifies only kernel task, that is to be handled.
This method is typically used from migration mode handler -
Dettaching the task includes also resetting the migration mode handler to NULL. This work is delegated to __tcmi_taskhelper_detach().
Returns
TCMI task that has been detached.
Definition at line 451 of file tcmi_taskhelper.h.
References __tcmi_taskhelper_detach().
Referenced by tcmi_migcom_mig_mode_handler().
 {
     struct tcmi_task *tmp;
     read_lock_irq(&tasklist_lock);
     task_lock(current);
     tmp = __tcmi_taskhelper_detach(current);
     task_unlock(current);
     read_unlock_irq(&tasklist_lock);
     return tmp;
 }
static struct tcmi_task* tcmi_taskhelper_detach_by_pid (pid_t pid) static read
<<public>> Dettaches the TCMI task from its process.
The process is looked up based on PID and the task is removed from the task_struct.
Parameters
pid - PID of the process whose TCMI task is to be detached
Returns
TCMI task that has been detached.
Definition at line 475 of file tcmi_taskhelper.h.
References __tcmi_taskhelper_detach(), mdbg, and task_find_by_pid().
 {
     struct task_struct *l_task;
     struct tcmi_task *t_task;
     /* try finding the process by PID */
     read_lock_irq(&tasklist_lock);
     if (!(l_task = task_find_by_pid(pid))) {
         mdbg(ERR3, "Can't notify, no such process %d", pid);
         goto exit0;
     }
     task_lock(l_task);
     t_task = __tcmi_taskhelper_detach(l_task);
     task_unlock(l_task);
     read_unlock_irq(&tasklist_lock);
     return t_task;
     /* error handling */
  exit0:
     read_unlock_irq(&tasklist_lock);
     return NULL;
 }
static void tcmi_taskhelper_do_mig_mode (struct pt_regs * regs) inline static
<<public>> This method is registered by CCN or PEN component as the SIGUNUSED signal handler.
It is responsible for storing the current process user mode context into the shadow/guest task resp.
Parameters
*regs - the current process context (registers)
Definition at line 547 of file tcmi_taskhelper.h.
References mdbg, and tcmi_task_set_context().
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_mighooks_mig_mode(), tcmi_penman_migrateback_npm(), and tcmi_taskhelper_notify_current().
 {
     if (current->tcmi.mig_mode_handler && current->tcmi.tcmi_task) {
         mdbg(INFO3, "Migration mode active for %p '%s'", current, current->comm);
         tcmi_task_set_context(current->tcmi.tcmi_task, regs);
         current->tcmi.mig_mode_handler();
     }
 }
static int tcmi_taskhelper_do_signals (struct tcmi_task * t_task) inline static
<<public>> Checks if there are any pending signals and handles them.
For each pending signal, the task is requested to process it as long as the signal is not SIGUNUSED - which indicates an attempt to switch to migration mode, eventhough we are already in migration mode. This signal is ignored.
We keep processing the signals as long as there are any pending left and the task method returns TCMI_TASK_KEEP_PUMPING.
The result of the last call of the task method is communicated back.
Parameters
*t_task - pointer to this task instance
Returns
result of the task specific signal handling method or TCMI_TASK_KEEP_PUMPING
Definition at line 282 of file tcmi_taskhelper.h.
References info, mdbg, tcmi_task_do_signal(), and TCMI_TASK_KEEP_PUMPING.
Referenced by tcmi_task_process_methods().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     siginfo_t info;
     unsigned long signr = 0;
     sigset_t *mask = &current->blocked;
     mdbg(INFO2, "Do signals being processed.");
     /* check pending signal */
     if (signal_pending(current)) {
         mdbg(INFO2, "Has signal pending");
         /* for all signals */
         while (res == TCMI_TASK_KEEP_PUMPING) {
             /* dequeue signal */
             spin_lock_irq(&current->sighand->siglock);
             signr = dequeue_signal(current, mask, &info);
             spin_unlock_irq(&current->sighand->siglock);
             /* no more signals in queue */
             if (!signr)
                 break;
             mdbg(INFO2, "Dequeued signal number: %lu..", signr);
             if (signr != SIGUNUSED)
                 res = tcmi_task_do_signal(t_task, signr, &info);
         }
     }
     mdbg(INFO2, "Signal handling finished. Result: %d", res);
     return res;
 }
static void tcmi_taskhelper_enter_mig_mode (struct tcmi_task * t_task) inline static
<<public>> Switches the task into migration mode.
It is necessary to lookup the regular kernel process that the TCMI task is attached to and enforce its migration mode. Essentially, it sends SIG_UNUSED signal to the process. The signal handler hook(see tcmi_taskhelper_do_mig_mode()) takes care of running the migration mode handler.
Parameters
*t_task - pointer to the TCMI task that is to be preempted into migration mode
Definition at line 92 of file tcmi_taskhelper.h.
References minfo, tcmi_task_local_pid(), and tcmi_task_to_task_struct().
Referenced by tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_shadowtask_execve(), tcmi_task_deliver_msg(), and tcmi_taskhelper_notify_by_pid().
 {
     struct task_struct* l_task = tcmi_task_to_task_struct(t_task);
     if ( !l_task ) {
         minfo(ERR3, "Can't enter to mig_mode. Cannot find corresponding task_struct for PID: %d",
              tcmi_task_local_pid(t_task));
         return;
     }
     /* switch the task to migration mode */
     force_sig(SIGUNUSED, l_task);
 }
static void tcmi_taskhelper_enter_mig_mode_exclusive (struct task_struct * l_task, struct tcmi_task * t_task) inline static
<<public>> Same as standard enter_mig_mode, but in this case we have already a reference to current task, so we do not perform any locking
Definition at line 111 of file tcmi_taskhelper.h.
Referenced by tcmi_migcom_guest_fork(), and tcmi_migcom_shadow_fork().
 {
     /* switch the task to migration mode */
     force_sig(SIGUNUSED, l_task);
     return;
 }
static struct tcmi_task* tcmi_taskhelper_find_by_pid (pid_t pid) static read
<<public>> Finds a TCMI task based on PID, in addition checks whether the task has a valid migration mode handler assigned.
Parameters
pid - PID of a taks to be looked up
Returns
TCMI task or NULL
Definition at line 128 of file tcmi_taskhelper.h.
References mdbg, task_find_by_pid(), and tcmi_task_get().
Referenced by tcmi_migman_deliver_msg(), and tcmi_taskhelper_notify_by_pid().
 {
     struct task_struct *l_task;
     struct tcmi_task *t_task = NULL;
     /* try finding the process by PID */
     read_lock_irq(&tasklist_lock);
     if (!(l_task = task_find_by_pid(pid))) {
         mdbg(ERR3, "Can't find, no such process %d", pid);
         goto exit0;
     }
     task_lock(l_task);
     /* check whether the process has a TCMI task and a valid handler */
     if (!(l_task->tcmi.mig_mode_handler && l_task->tcmi.tcmi_task)) {
         mdbg(ERR3, "Process %d has no a mig. mode handler"
              "or TCMI task", pid);
         task_unlock(l_task);
         goto exit0;
     }
     /* get the extra task reference */
     t_task = tcmi_task_get(l_task->tcmi.tcmi_task);
     task_unlock(l_task);
     read_unlock_irq(&tasklist_lock);
     return t_task;
     /* error handling */
  exit0:
     read_unlock_irq(&tasklist_lock);
     return NULL;
 }
static void tcmi_taskhelper_flush_signals (struct tcmi_task * t_task) inline static
<<public>> Flushes all pending signals of the task.
Usually needed right after establishing a new shadow process.
Parameters
*t_task - pointer to this task instance
Definition at line 320 of file tcmi_taskhelper.h.
 {
     flush_signals(current);
 }
static void tcmi_taskhelper_flushfiles (void) inline static
<<public>> Flushing files is required prior to issuing a migrate request.
It is necessary to close all regular files that the process has open as those files will be accessed again by the restarted checkpoint. This prevents write conflicts.
Definition at line 728 of file tcmi_taskhelper.h.
References fd, mdbg, and tcmi_ckpt_foreach_openfile.
Referenced by tcmi_guesttask_migrateback_p(), and tcmi_shadowtask_emigrate_p().
 {
     int fd;
     struct file *file;
     struct inode *inode;
     unsigned int old_flags = current->flags & PF_EXITING;
     /* We do a special trick here. In order to preserve proxy files during the migration, we need to tell the other end not to close the files.
        It does not close the files in case the clsoe was called in context of exit, as this file is going to be closed on process exit.
        So we pretend we are exitting here so that the server things it should not close the file */
     current->flags |= PF_EXITING;
     /* Check each open file */
     tcmi_ckpt_foreach_openfile(file, fd) {
         inode = file->f_dentry->d_inode;
         if (S_ISREG(inode->i_mode) || S_ISDIR(inode->i_mode) || S_ISCHR(inode->i_mode) || S_ISFIFO(inode->i_mode) ) {
             mdbg(INFO4, "Closing file fd=%d, type=%0o '%s'", fd, file->f_flags,
                  file->f_dentry->d_name.name);
             sys_close(fd);
         }
     }
     current->flags = old_flags;
 }
static int tcmi_taskhelper_notify_by_pid (pid_t pid, tcmi_method_t * method, void * data, int size, int priority) inline static
<<public>> Submits a specified method to a TCMI task identified by PID.
To accomplish the job in SMP safe manner we need to:
get a valid reference to a TCMI task associated with particular PID
submit the method - based on priority we can also choose to flush the method queue
switch the process to migration mode - again, to be safe, we use the tcmi_taskhelper_enter_mig_mode()
drop the task reference
Parameters
pid - process that is to be notified
*method - task method that is to be submitted
*data - argument for the submitted method
size - size of the argument in bytes
priority - when > 0, the method queue is also flushed
Returns
0 upon success
Todo:
Simplify the way the task is forced into migration mode, so that a full lookup doesn't need to be performed again via tcmi_taskhelper_enter_mig_mode()
Definition at line 181 of file tcmi_taskhelper.h.
References mdbg, tcmi_task_flush_and_submit_method(), tcmi_task_put(), tcmi_task_submit_method(), tcmi_taskhelper_enter_mig_mode(), and tcmi_taskhelper_find_by_pid().
Referenced by tcmi_migcom_migrate_home_ppm_p().
 {
     struct tcmi_task *t_task = NULL;
     if (!(t_task = tcmi_taskhelper_find_by_pid(pid))) {
         mdbg(ERR3, "Can't find TCMI task PID %d", pid);
         goto exit0;
     }
     /* now we can safely operate on the task as we own 1 reference */
     if (priority > 0)
         tcmi_task_flush_and_submit_method(t_task, method, data, size);
     else
         tcmi_task_submit_method(t_task, method, data, size);
     /* using method is safe as we have no reference l_task */
     tcmi_taskhelper_enter_mig_mode(t_task);
     tcmi_task_put(t_task);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_taskhelper_notify_current (tcmi_method_t * method, void * data, int size, int priority) inline static
<<public>> current process notification - submission of a method.
The notification requires:
checks for a valid TCMI task in current process
submits the method based on priority
launches the migration mode handler - we need to reassign the process context as this notification is typically used from system call hooks.
Parameters
*method - task method that is to be submitted
*data - argument for the submitted method
size - size of the argument in bytes
priority - when > 0, the method queue is also flushed
Returns
0 upon success
Definition at line 574 of file tcmi_taskhelper.h.
References mdbg, tcmi_task_context(), tcmi_task_flush_and_submit_method(), tcmi_task_submit_method(), and tcmi_taskhelper_do_mig_mode().
Referenced by tcmi_mighooks_do_exit().
 {
     struct tcmi_task *t_task;
     mdbg(INFO3, "Notify current %p", current);
     if (!(t_task = current->tcmi.tcmi_task)) {
         goto exit0;
     }
     /* now we can safely operate on the task as we own 1 reference */
     if (priority > 0)
         tcmi_task_flush_and_submit_method(t_task, method, data, size);
     else
         tcmi_task_submit_method(t_task, method, data, size);
     tcmi_taskhelper_do_mig_mode(tcmi_task_context(t_task));
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_taskhelper_restart (struct tcmi_task * t_task, char * ckpt_name) inline static
<<public>> Schedules a task restart from a given checkpoint image.
This requires:
preparing execve of the checkpoint (the task stores internally the execve name string, so that it can be released upon task destruction)
submitting execve method - it will be picked up by the method pump in its next iteration. We WANT to flush all methods from the queue as execve we is of high importance and want to make sure it runs next.
Parameters
*t_task - pointer to the TCMI task whose image will be overlayed with the checkpoint image
ckpt_name - checkpoint image name.
Returns
0 upon success
Definition at line 700 of file tcmi_taskhelper.h.
References envp, mdbg, tcmi_task_execve(), tcmi_task_flush_and_submit_method(), and tcmi_task_prepare_execve().
Referenced by tcmi_guesttask_process_p_emigrate_msg(), and tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg().
 {
     char *argv[] = { NULL };
     char *envp[] = { NULL };
     /* setup execve arguments*/
     if (tcmi_task_prepare_execve(t_task, ckpt_name, argv, envp) < 0) {
         mdbg(ERR3, "Failed preparing execve of the checkpoint '%s'", ckpt_name);
         goto exit0;
     }
     /* schedule task execve as the next method - requires flushing
      * all methods in the queue */
     mdbg(INFO3, "Submitting execve");
     tcmi_task_flush_and_submit_method(t_task, tcmi_task_execve, NULL, 0);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_taskhelper_run_mig_mode_handler (void) inline static
Runs migration mode handler of the current process.
Returns
0 upon success
Definition at line 67 of file tcmi_taskhelper.h.
References mdbg.
Referenced by tcmi_migcom_migrated_task().
 {
     if (!current->tcmi.mig_mode_handler) {
         mdbg(ERR3, "Missing migration mode handler for current process!!");
         goto exit0;
     }
     current->tcmi.mig_mode_handler();
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static struct tcmi_task* tcmi_taskhelper_sanity_check (void) static read
<<public>> This method is intended for migration mode handler, it should be the very first check it performs.
We verify that the current process has a valid TCMI task assigned. Also, if this is the first time entering the migration mode, the task has to be 'picked up'. This is a synchronization mechanism that is available for the TCMI task instantiator (usually the migration component).
Returns
a valid TCMI task that is attached to the current kernel process or NULL;
Definition at line 512 of file tcmi_taskhelper.h.
References mdbg, tcmi_task_local_pid(), tcmi_task_pick_up(), and tcmi_task_picked_up().
Referenced by tcmi_migcom_mig_mode_handler().
 {
     struct tcmi_task *t_task;
     task_lock(current);
     /* safes a few dereferences */
     t_task = current->tcmi.tcmi_task;
     /* check that the TCMI task exists */
     if (!t_task) {
         mdbg(ERR3, "Kernel task '%s' PID=%d has no TCMI task assigned",
              current->comm, current->pid);
         goto exit0;
     }
     /* pickup the task when entering the migration mode for the first time */
     if (!tcmi_task_picked_up(t_task)) {
         mdbg(INFO2, "TCMI task %p PID=%d first time in mig. mode, picking up",
              t_task, tcmi_task_local_pid(t_task));
         tcmi_task_pick_up(t_task);
     }
     task_unlock(current);
     return t_task;
     /* error handling */
  exit0:
     task_unlock(current);
     return NULL;
 }
static int tcmi_taskhelper_wait_for_pick_up_timeout (struct tcmi_task * t_task, unsigned long timeout) inline static
<<public>> Synchronizes with a task entering the migration mode for the first time.
The thread associated with the task already has an extra reference. If the task doesn't get picked up on time, it will be safely removed from under the thread.
We don't need an extra reference to the kernel task struct as we are holding task_list_lock -> the task struct can't be removed from under us.
Parameters
*t_task - pointer to the task instance that we are syncing with
timeout - in ticks
Returns
0 if the task has successfully entered the migration mode
Definition at line 224 of file tcmi_taskhelper.h.
References mdbg, minfo, task_find_by_pid(), tcmi_task_local_pid(), tcmi_task_picked_up(), tcmi_task_put(), and tcmi_task_wait_for_pick_up_timeout().
Referenced by tcmi_migcom_emigrate_ccn_ppm_p(), and tcmi_migcom_immigrate().
 {
     int err = 0;
     /* temporary storage for the task. */
     struct tcmi_task *tmp = NULL;
     /* regular linux task used for lookup*/
     struct task_struct *l_task;
     /* Wait for pickup first */
     if (!tcmi_task_wait_for_pick_up_timeout(t_task, timeout)) {
         /* try finding thread associated with the task by PID */
         read_lock_irq(&tasklist_lock);
         if (!(l_task = task_find_by_pid(tcmi_task_local_pid(t_task)))) {
             mdbg(ERR3, "Failed to wait - no such process %d",
                  tcmi_task_local_pid(t_task));
             err = -ESRCH;
             read_unlock_irq(&tasklist_lock);
             goto exit0;
         }
         /* A bad inconsistency if tasks don't match - bug */
         BUG_ON(t_task != l_task->tcmi.tcmi_task);
         /* the task might still have been picked up in the
          * meantime, we have to check again */
         task_lock(l_task);
         if (!tcmi_task_picked_up(l_task->tcmi.tcmi_task)) {
             minfo(INFO1, "Task local PID = %d still not picked up destroying..",
                   tcmi_task_local_pid(t_task));
             tmp = l_task->tcmi.tcmi_task;
             l_task->tcmi.mig_mode_handler = NULL;
             l_task->tcmi.tcmi_task = NULL;
             err = -EINVAL;
         }
         task_unlock(l_task);
         read_unlock_irq(&tasklist_lock);
         /* Release the task instance - safe if still NULL. We must release 1 reference as the thread that owned the task no longer owns it. */
         tcmi_task_put(tmp);
     }
     /* error handling */
  exit0:
     return err;
 }