Clondike: Tcmi_generic_user_msg_class
Tcmi_generic_user_msg_class
Functions
static int tcmi_generic_user_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_generic_user_msg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Sends the message via a specified connection.
static void tcmi_generic_user_msg_send_free (struct tcmi_msg *self)
<<private>> Frees custom message resources.
static int tcmi_generic_user_procmsg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_generic_user_procmsg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Sends the message via a specified connection.
static void tcmi_generic_user_procmsg_send_free (struct tcmi_msg *self)
<<private>> Frees custom message resources.
Variables
static struct tcmi_msg_ops generic_user_msg_ops
Message operations that support polymorphism.
static struct tcmi_msg_ops generic_user_procmsg_ops
Message operations that support polymorphism.
Detailed Description
Function Documentation
static int tcmi_generic_user_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 116 of file tcmi_generic_user_msg.c.
References KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_generic_user_msg::node_id, tcmi_generic_user_msg::size, TCMI_GENERIC_USER_MSG, and tcmi_generic_user_msg::user_data.
 {
     int err = -EINVAL;
     struct tcmi_generic_user_msg *self_msg = TCMI_GENERIC_USER_MSG(self);
     mdbg(INFO2, "Generic user message received");
     if ((err = kkc_sock_recv(sock, &self_msg->node_id,
                  sizeof(self_msg->node_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive node id");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive size of user data");
         goto exit0;
     }
     if ( self_msg->size > 0 ) {
         if (!(self_msg->user_data = (char*)kmalloc(self_msg->size, GFP_KERNEL))) {
             mdbg(ERR3, "Can't allocate memory for user data.");
             goto exit0;
         }
         /* Receive the user data */
         if ((err = kkc_sock_recv(sock, self_msg->user_data,
                     self_msg->size, KKC_SOCK_BLOCK)) < 0) {
             mdbg(ERR3, "Failed to receive user data");
             goto exit0;
         }
     } else {
         self_msg->user_data = NULL;
     }
     return 0;
     /* error handling*/
  exit0:
     return err;
 }
static int tcmi_generic_user_msg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Sends the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 165 of file tcmi_generic_user_msg.c.
References KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_generic_user_msg::node_id, tcmi_generic_user_msg::size, TCMI_GENERIC_USER_MSG, and tcmi_generic_user_msg::user_data.
 {
     int err;
     struct tcmi_generic_user_msg *self_msg = TCMI_GENERIC_USER_MSG(self);
     if ((err = kkc_sock_send(sock, &self_msg->node_id,
                  sizeof(self_msg->node_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send node id");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send user data size");
         goto exit0;
     }
     if ( self_msg->size > 0 ) {
         /* Send the user data */
         if ((err = kkc_sock_send(sock, self_msg->user_data,
                     self_msg->size, KKC_SOCK_BLOCK)) < 0) {
             mdbg(ERR3, "Failed to send user data");
             goto exit0;
         }
     }
     mdbg(INFO2, "User data message sent. Pen ID=%d Auth data length=%d", self_msg->node_id, self_msg->size);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static void tcmi_generic_user_msg_send_free (struct tcmi_msg * self) static
<<private>> Frees custom message resources.
The checkpoint image name string is released from memory.
Parameters
*self - this message instance
Definition at line 205 of file tcmi_generic_user_msg.c.
References mdbg, TCMI_GENERIC_USER_MSG, and tcmi_generic_user_msg::user_data.
 {
     struct tcmi_generic_user_msg *self_msg = TCMI_GENERIC_USER_MSG(self);
     mdbg(INFO3, "Freeing user message");
     kfree(self_msg->user_data);
 }
static int tcmi_generic_user_procmsg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 116 of file tcmi_generic_user_procmsg.c.
References KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_generic_user_procmsg::node_id, tcmi_generic_user_procmsg::size, TCMI_GENERIC_USER_PROCMSG, and tcmi_generic_user_procmsg::user_data.
 {
     int err = -EINVAL;
     struct tcmi_generic_user_procmsg *self_msg = TCMI_GENERIC_USER_PROCMSG(self);
     mdbg(INFO2, "Generic user message received");
     if ((err = kkc_sock_recv(sock, &self_msg->node_id,
                  sizeof(self_msg->node_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive node id");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive size of user data");
         goto exit0;
     }
     if ( self_msg->size > 0 ) {
         if (!(self_msg->user_data = (char*)kmalloc(self_msg->size, GFP_KERNEL))) {
             mdbg(ERR3, "Can't allocate memory for user data.");
             goto exit0;
         }
         /* Receive the user data */
         if ((err = kkc_sock_recv(sock, self_msg->user_data,
                     self_msg->size, KKC_SOCK_BLOCK)) < 0) {
             mdbg(ERR3, "Failed to receive user data");
             goto exit0;
         }
     } else {
         self_msg->user_data = NULL;
     }
     return 0;
     /* error handling*/
  exit0:
     return err;
 }
static int tcmi_generic_user_procmsg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Sends the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 165 of file tcmi_generic_user_procmsg.c.
References KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_generic_user_procmsg::node_id, tcmi_generic_user_procmsg::size, TCMI_GENERIC_USER_PROCMSG, and tcmi_generic_user_procmsg::user_data.
 {
     int err;
     struct tcmi_generic_user_procmsg *self_msg = TCMI_GENERIC_USER_PROCMSG(self);
     if ((err = kkc_sock_send(sock, &self_msg->node_id,
                  sizeof(self_msg->node_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send node id");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send user data size");
         goto exit0;
     }
     if ( self_msg->size > 0 ) {
         /* Send the user data */
         if ((err = kkc_sock_send(sock, self_msg->user_data,
                     self_msg->size, KKC_SOCK_BLOCK)) < 0) {
             mdbg(ERR3, "Failed to send user data");
             goto exit0;
         }
     }
     mdbg(INFO2, "User data message sent. Pen ID=%d Auth data length=%d", self_msg->node_id, self_msg->size);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static void tcmi_generic_user_procmsg_send_free (struct tcmi_msg * self) static
<<private>> Frees custom message resources.
The checkpoint image name string is released from memory.
Parameters
*self - this message instance
Definition at line 205 of file tcmi_generic_user_procmsg.c.
References mdbg, TCMI_GENERIC_USER_PROCMSG, and tcmi_generic_user_procmsg::user_data.
 {
     struct tcmi_generic_user_procmsg *self_msg = TCMI_GENERIC_USER_PROCMSG(self);
     mdbg(INFO3, "Freeing user message");
     kfree(self_msg->user_data);
 }
Variable Documentation
struct tcmi_msg_ops generic_user_msg_ops static
Initial value:
= {
    .recv = tcmi_generic_user_msg_recv,
    .send = tcmi_generic_user_msg_send,
    .free = tcmi_generic_user_msg_send_free
}
Message operations that support polymorphism.
Definition at line 215 of file tcmi_generic_user_msg.c.
Referenced by tcmi_generic_user_msg_new_rx(), and tcmi_generic_user_msg_new_tx().
struct tcmi_msg_ops generic_user_procmsg_ops static
Initial value:
= {
    .recv = tcmi_generic_user_procmsg_recv,
    .send = tcmi_generic_user_procmsg_send,
    .free = tcmi_generic_user_procmsg_send_free
}
Message operations that support polymorphism.
Definition at line 215 of file tcmi_generic_user_procmsg.c.
Referenced by tcmi_generic_user_procmsg_new_rx(), and tcmi_generic_user_procmsg_new_tx().