Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/kkc/kkc_sock_tcp.c File Reference
kkc_sock_tcp.c File Reference
#include <linux/types.h>
#include <linux/string.h>
#include <linux/socket.h>
#include <net/sock.h>
#include <net/tcp.h>
#include <linux/in.h>
#include "kkc_arch.h"
#include "kkc_sock_tcp.h"
#include <dbg.h>
Macros
#define KKC_SOCK_TCP_PRIVATE
Functions
EXPORT_SYMBOL_GPL (kkc_arch_tcp)
static kkc_arch_obj_t kkc_sock_tcp_new (void)
<<private>> Creates an empty TCP socket.
static int kkc_sock_tcp_connect (struct kkc_sock *self, char *addr)
<<private>> Connects to the given address.
static int kkc_sock_tcp_listen (struct kkc_sock *self, char *addr)
<<private>> Starts listening on a specified address.
static int kkc_sock_tcp_accept (struct kkc_sock *self, struct kkc_sock **new_kkc_sock, kkc_sock_flags_t flags)
<<private>> Creates a new socket by accepting the incoming connection.
static int kkc_sock_tcp_send (struct kkc_sock *self, void *buf, int buflen, kkc_sock_flags_t flags)
<<private>> Sends out specified data.
static int kkc_sock_tcp_recv (struct kkc_sock *self, void *buf, int buflen, kkc_sock_flags_t flags)
<<private>> Receives requested number of bytes of data.
static int kkc_sock_tcp_shutdown (struct kkc_sock *self)
<<private>> Disconnects the socket.
static int kkc_sock_tcp_add_wait_queue (struct kkc_sock *self, wait_queue_t *wait)
<<private>> Adds a task to the queue of processes sleeping on this socket.
static int kkc_sock_tcp_remove_wait_queue (struct kkc_sock *self, wait_queue_t *wait)
<<private>> Removes a task from the queue of processes sleeping on this socket.
static void kkc_sock_tcp_callback (struct sock *sk, int count)
<<private>> Method that will be registered to standard sock as a callback function and will dispatch the request to our registered callback
static int kkc_sock_tcp_register_read_callback (struct kkc_sock *self, kkc_data_ready callback, void *callback_data)
<<private>> Registeres callback function that will be called when there are some data to be read in the socket
static void kkc_sock_tcp_free (struct kkc_sock *self)
<<private>> Free TCP socket related resources.
static int kkc_sock_tcp_getname (struct kkc_sock *self, char *name, int size, int local)
<<private>> Socket name accessor.
static int kkc_sock_tcp_is_address_equal_to (struct kkc_sock *self, const char *addr, int addr_length, int local)
<<private>> IP Comparator
static int kkc_sock_tcp_extract_addr (char *addr, struct sockaddr_in *sin)
<<private>> Helper class method for extracting ip address and port number from string argument.
int kkc_sock_enable_keepalive (struct kkc_sock *self)
Method used for enabling of keep alive on socket and setting of aggressive timing of timeout detection.
int kkc_sock_tcp_disable_nagle (struct kkc_sock *self)
Method used for disabling of nagels algorithm on a tcp connection.
int kkc_sock_tcp_enable_quickack (struct kkc_sock *self)
Method used for enabling quick-ack on a tcp connection.
Variables
struct kkc_arch kkc_arch_tcp = { .name = "tcp", .arch_ops = &tcp_arch_ops , .owner = THIS_MODULE, .data = NULL }
Declare the TCP architecture.
static struct kkc_arch_ops tcp_arch_ops
TCP architecture specific operations.
static struct kkc_sock_ops tcp_sock_ops
Socket operations that support polymorphism.
Macro Definition Documentation
#define KKC_SOCK_TCP_PRIVATE
Definition at line 37 of file kkc_sock_tcp.c.
Function Documentation
EXPORT_SYMBOL_GPL (kkc_arch_tcp)
static int kkc_sock_tcp_accept (struct kkc_sock * self, struct kkc_sock ** new_kkc_sock, kkc_sock_flags_t flags) static
<<private>> Creates a new socket by accepting the incoming connection.
After instantiating a new socket, a TCP socket specific method is called to accept a connection. This will setup the rest of the newly created TCP socket.
Parameters
*self - pointer to this socket instance
**new_kkc_sock - storage for the new socket created for the incoming connection.
flags - specify blocking/nonblocking mode
Returns
0 upon successful connection
Todo:
this needs an optimization, so that a full socket doesn't get manufactured everytime. This is a performance problem when using nonblock mode
Definition at line 192 of file kkc_sock_tcp.c.
References KKC_SOCK, KKC_SOCK_NONBLOCK, kkc_sock_put(), KKC_SOCK_TCP, kkc_sock_tcp_new(), and mdbg.
 {
     int err = 0;
     int tmp_flags;
     struct socket *sock, *new_sock;
     /* Create a new TCP socket that will handle the incoming connection */
     if (!(*new_kkc_sock = KKC_SOCK(kkc_sock_tcp_new()))) {
         mdbg(ERR4, "Failed to create a new KKC TCP socket");
         err = -ENOMEM;
         goto exit0;
     }
     /* BSD socket where we check for incoming connections */
     sock = KKC_SOCK_TCP(self)->sock;
     /* newly created BSD socket that handles the incoming connection */
     new_sock = KKC_SOCK_TCP(*new_kkc_sock)->sock;
     /* compose flags for accepting */
     tmp_flags = O_RDWR | ((flags & KKC_SOCK_NONBLOCK) != 0 ? O_NONBLOCK : 0);
     mdbg(INFO4, "Accepting incoming connection");
     if ((err = sock->ops->accept(sock, new_sock, tmp_flags)) < 0) {
         if ( err != -EAGAIN ) {
             mdbg(ERR4, "Cannot accept new connection %d", err);
         } else {
             mdbg(INFO4, "Accept timeouted.");
         }
         goto exit1;
     }
     mdbg(INFO4, "Accepted a TCP connection..");
     return 0;
     /* error handling */
  exit1:
     kkc_sock_put(*new_kkc_sock);
     new_kkc_sock = NULL; /* user will get back NULL */
  exit0:
     return err;
 }
static int kkc_sock_tcp_add_wait_queue (struct kkc_sock * self, wait_queue_t * wait) static
<<private>> Adds a task to the queue of processes sleeping on this socket.
We use the sk_sleep wait queue, no locking needed waitqueues handle serialization on their own.
Parameters
*self - pointer to this socket instance
*wait - pointer to the waitqueue element with the task that wants to sleep on this socket.
Returns
0 upon success
Definition at line 352 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, and mdbg.
 {
     int err = 0;
     mdbg(INFO4, "TCP adding to wait queue..");
     /* add to socket wait queue */
     add_wait_queue(sk_sleep(KKC_SOCK_TCP(self)->sock->sk), wait);
     // Fix for kernel 3.7.1 call inline function sk_sleep instead of original record sk_sleep in structure sk | by Jiri Rakosnik
     return err;
 }
static void kkc_sock_tcp_callback (struct sock * sk, int count) static
<<private>> Method that will be registered to standard sock as a callback function and will dispatch the request to our registered callback
Definition at line 388 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP.
Referenced by kkc_sock_tcp_register_read_callback().
{
     if ( sk->sk_user_data ) {
         struct kkc_sock* self = sk->sk_user_data;
         if ( KKC_SOCK_TCP(self)->read_callback ) {
             KKC_SOCK_TCP(self)->read_callback(KKC_SOCK_TCP(self)->callback_data, count);
         }
     }
 }
static int kkc_sock_tcp_connect (struct kkc_sock * self, char * addr) static
<<private>> Connects to the given address.
Stores the address inside the socket and delegates all work to the architecture specific socket.
Parameters
*self - pointer to this socket instance
*addr - address where to connect to.
Returns
0 upon successful connection
Definition at line 117 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, kkc_sock_tcp_extract_addr(), and mdbg.
 {
     int err = 0;
     struct socket *sock = KKC_SOCK_TCP(self)->sock;
     struct sockaddr_in sin;
     /* Extract ip address and port number from addr argument */
     if ((err = kkc_sock_tcp_extract_addr(addr, &sin))) {
         mdbg(ERR4, "Cannot extract ip address from argument '%s'", addr);
         goto exit0;
     }
     mdbg(INFO4, "Connecting to '%s' ..", addr);
     if ((err = sock->ops->connect(sock, (struct sockaddr*)&sin, sizeof(sin), O_RDWR)) < 0) {
         mdbg(ERR4, "Cannot connect to '%s', error=%d", addr, err);
         goto exit0;
     }
     mdbg(INFO4, "Connected to '%s' ..", addr);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static int kkc_sock_tcp_extract_addr (char * addr, struct sockaddr_in * sin) static
<<private>> Helper class method for extracting ip address and port number from string argument.
Parameters
*addr - string with the address in the form a.b.c.d:p
*sin - output parameter that will have ip address and port filled out upon success
Returns
0 if a valid IP address and port have been extracted
Definition at line 516 of file kkc_sock_tcp.c.
References mdbg.
Referenced by kkc_sock_tcp_connect(), and kkc_sock_tcp_listen().
 {
     char *colon_ptr;
     int colon_pos;
     char tmp_ip[16];
     unsigned long int tmp_port;
     char *dummy;
     int err = 0;
     /* find colon in address */
     if ((colon_ptr = strchr(addr, ':')) == NULL) {
         mdbg(ERR4, "Invalid IP address syntax");
         err = -EINVAL;
         goto leave;
     }
     /*
      * Extract ip address
      */
     colon_pos = colon_ptr - addr;
     if (colon_pos > 15) {
         mdbg(ERR4, "Invalid IP address syntax");
         err = -EINVAL;
         goto leave;
     }
     strncpy(tmp_ip, addr, colon_pos);
     tmp_ip[colon_pos] = '\0';
     mdbg(INFO4, "Extracted ip address is '%s'", tmp_ip);
     /* extract port */
     tmp_port = simple_strtoul(colon_ptr + 1, &dummy, 10);
     mdbg(INFO4, "Extracted port number is '%lu'", tmp_port);
     /* fill results */
     sin->sin_addr.s_addr = in_aton(tmp_ip);
     sin->sin_port = htons((unsigned short int)tmp_port);
     sin->sin_family = AF_INET;
 leave:
     return err;
 }
static void kkc_sock_tcp_free (struct kkc_sock * self) static
<<private>> Free TCP socket related resources.
Essentially, it terminates the connection and releases the socket. This method is called by the super class when the last reference to the socket is dropped.
Parameters
*self - pointer to this socket instance
Definition at line 425 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, kkc_sock_tcp_shutdown(), and mdbg.
 {
     mdbg(INFO4, "TCP freeing socket resources..");
     kkc_sock_tcp_shutdown(self);
     sock_release(KKC_SOCK_TCP(self)->sock);
 }
static int kkc_sock_tcp_getname (struct kkc_sock * self, char * name, int size, int local) static
<<private>> Socket name accessor.
The socket name is returned in format 'a.b.c.d:p' We use a socket operation to retrieve the desired part of the address(local or peer). The address is then formated as mentioned above and stored in the buffer.
Parameters
*self - pointer to this socket instance
*name - pointer to the buffer where the sockname is to be stored
size - maximum string length that fits into the sockname buffer
local - if set to 0, retrieves the local name, otherwise retreives the remote(peer) name
Returns
0 upon success
Definition at line 446 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP.
 {
     int err = 0;
     int len = sizeof(struct sockaddr_in);
     struct socket *sock = KKC_SOCK_TCP(self)->sock;
     struct sockaddr_in address;
     /* used to remap the s_addr for byte access */
     unsigned char *paddr;
     if ((err = sock->ops->getname(sock, (struct sockaddr *)&address,
                       &len, local)) < 0) {
         goto exit0;
     }
     paddr = (char *) &address.sin_addr.s_addr;
     snprintf(name, size, "%u.%u.%u.%u:%u", paddr[0], paddr[1], paddr[2], paddr[3],
          ntohs(address.sin_port));
     return 0;
     /* error handling */
  exit0:
     memset(name, 0, size);
     return err;
 }
static int kkc_sock_tcp_is_address_equal_to (struct kkc_sock * self, const char * addr, int addr_length, int local) static
<<private>> IP Comparator
Parameters
*address - string with the address in the form a.b.c.d:p
*addr_length
*local - 1 to compare with local IP, 0 if to compare with peer IP
Returns
1, if address equals to local or peer addres (depending on local flag)
Definition at line 479 of file kkc_sock_tcp.c.
References KKC_SOCK_MAX_ADDR_LENGTH, and KKC_SOCK_TCP.
{
     int err = 0;
     int len = sizeof(struct sockaddr_in);
     struct socket *sock = KKC_SOCK_TCP(self)->sock;
     struct sockaddr_in address;
     unsigned char *paddr;
     char name[KKC_SOCK_MAX_ADDR_LENGTH];
     if ( !addr )
         return 0;
     /* used to remap the s_addr for byte access */
     if ((err = sock->ops->getname(sock, (struct sockaddr *)&address,
                       &len, local)) < 0) {
         goto exit0;
     }
     paddr = (char *) &address.sin_addr.s_addr;
     snprintf(name, KKC_SOCK_MAX_ADDR_LENGTH, "tcp:%u.%u.%u.%u:%u", paddr[0], paddr[1], paddr[2], paddr[3],
          ntohs(address.sin_port));
 //  printk("Comparing: %s with %s local %d, %d, %d\n", name, addr, local, strncmp(addr, name, min((size_t)addr_length, strlen(name))), strcmp(addr, name));
     return strncmp(addr, name, min((size_t)addr_length, strlen(name))) == 0;
     /* error handling */
  exit0:
     return 0;
 }
static int kkc_sock_tcp_listen (struct kkc_sock * self, char * addr) static
<<private>> Starts listening on a specified address.
Extracts the address from the string, binds the socket to this address and starts listening.
Parameters
*self - pointer to this socket instance
*addr - address where to connect to.
Returns
0 upon successfully establishing the listening
Definition at line 150 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, kkc_sock_tcp_extract_addr(), and mdbg.
 {
     int err = 0;
     struct socket *sock = KKC_SOCK_TCP(self)->sock;
     struct sockaddr_in sin;
     /* Extract ip address and port number from addr argument */
     if ((err = kkc_sock_tcp_extract_addr(addr, &sin))) {
         mdbg(ERR4, "Cannot extract ip address from argument '%s'", addr);
         goto exit0;
     }
     if ((err = sock->ops->bind(sock, (struct sockaddr*)&sin, sizeof(sin))) < 0) {
         mdbg(ERR4, "Cannot bind to '%s'", addr);
         goto exit0;
     }
     if ((err = sock->ops->listen(sock, 32)) < 0) {
         mdbg(ERR4, "Cannot start listening on '%s'", addr);
         goto exit0;
     }
     mdbg(INFO4, "TCP Listening on '%s' ..", addr);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static kkc_arch_obj_t kkc_sock_tcp_new (void) static
<<private>> Creates an empty TCP socket.
The BSD socket is created for a stream connection using TCP protocol. In addition, socket reuse option is set. Eventhough a regular TCP socket instance is created it is casted to kkc_arch_obj_t, which is a generic object supported by kkc_arch. The user of the architecture class instance always knows, what instance to expect, so he/she can cast it to kkc_sock without problems. The reason, why we cannot return directly kkc_sock, is that it would create a circular dependency between kkc_arch and kkc_sock .
Returns
architecture object instance or NULL
Definition at line 66 of file kkc_sock_tcp.c.
References KKC_ARCH, kkc_arch_get(), KKC_ARCH_OBJ, KKC_SOCK, kkc_sock_enable_keepalive(), kkc_sock_init(), KKC_SOCK_TCP, kkc_sock_tcp_disable_nagle(), kkc_sock_tcp_enable_quickack(), mdbg, kkc_sock_tcp::read_callback, kkc_sock_tcp::sock, and tcp_sock_ops.
Referenced by kkc_sock_tcp_accept().
 {
     struct kkc_sock_tcp *sock;
     mdbg(INFO4, "Creating a new TCP socket..");
     /* Allocate the instance */
     if (!(sock = KKC_SOCK_TCP(kmalloc(sizeof(struct kkc_sock_tcp), GFP_KERNEL)))) {
         mdbg(ERR4, "Can't allocate memory for TCP socket");
         goto exit0;
     }
     /* Initialize the generic socket */
     if (kkc_sock_init(KKC_SOCK(sock), kkc_arch_get(&KKC_ARCH(tcp)), &tcp_sock_ops)) {
         mdbg(ERR4, "Error initializing TCP socket");
         goto exit1;
     }
     mdbg(INFO4, "Creating BSD socket");
     if (sock_create_kern(PF_INET, SOCK_STREAM, IPPROTO_TCP, &sock->sock)) {
         mdbg(ERR4, "Cannot create socket");
         goto exit1;
     }
     // TODO: At the moment, we set this on all TCP connections, but in a future we may want to use this selectively
     kkc_sock_tcp_disable_nagle(KKC_SOCK(sock));
     kkc_sock_tcp_enable_quickack(KKC_SOCK(sock));
     kkc_sock_enable_keepalive(KKC_SOCK(sock));
     /* setup reuse option - this is how it was in original KKC, why? */
     sock->sock->sk->sk_reuse = 1;
     sock->read_callback = NULL;
     sock->sock->sk->sk_user_data = sock; // Back reference to kkc socket
     return KKC_ARCH_OBJ(sock);
     /* error handling */
  exit1:
     kfree(sock);
  exit0:
     return NULL;
 }
static int kkc_sock_tcp_recv (struct kkc_sock * self, void * buf, int buflen, kkc_sock_flags_t flags) static
<<private>> Receives requested number of bytes of data.
What needs to be done:
setup a message header
setup iovec and store the buffer base address and length into it
asks the kernel to receive the message
Parameters
*self - pointer to this socket instance
*buf - buffer where to store received data.
buflen - length of the buffer to be sent
flags - specify blocking or non-blocking mode.
Returns
number of bytes actually received or error when < 0
Definition at line 291 of file kkc_sock_tcp.c.
References KKC_SOCK_NONBLOCK, KKC_SOCK_TCP, and mdbg.
 {
     struct socket *sock = KKC_SOCK_TCP(self)->sock;
     struct msghdr msg;
     struct iovec iov;
     int tmp_flags;
     int result = 0;
     /* Setup message header */
     msg.msg_name = NULL;
     msg.msg_namelen = 0;
     msg.msg_control = NULL;
     msg.msg_controllen = 0;
     tmp_flags = (flags & KKC_SOCK_NONBLOCK ? MSG_DONTWAIT : 0);
     iov.iov_base = buf;
     iov.iov_len = buflen;
     result = kernel_recvmsg(sock, &msg, (struct kvec*)&iov, 1, buflen, tmp_flags);
     mdbg(INFO4, "TCP receiving buffer %p length: %d bytes, received %d", buf, buflen, result);
     /* connection reset is marked as 0, so if the user requested
      * more than 0bytes to be sent, we have to check for this and
      * convert the error */
     return ((result == 0) && (buflen > 0)) ? -ECONNRESET : result;
 }
static int kkc_sock_tcp_register_read_callback (struct kkc_sock * self, kkc_data_ready callback, void * callback_data) static
<<private>> Registeres callback function that will be called when there are some data to be read in the socket
Parameters
*self - pointer to this socket instance
*wait - pointer to the callback function
Returns
0 upon success
Definition at line 405 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, kkc_sock_tcp_callback(), and mdbg.
 {
     int err = 0;
     mdbg(INFO4, "TCP registering read callback..");
     KKC_SOCK_TCP(self)->read_callback = callback;
     KKC_SOCK_TCP(self)->callback_data = callback_data;
     KKC_SOCK_TCP(self)->sock->sk->sk_data_ready = kkc_sock_tcp_callback;
     return err;
 }
static int kkc_sock_tcp_remove_wait_queue (struct kkc_sock * self, wait_queue_t * wait) static
<<private>> Removes a task from the queue of processes sleeping on this socket.
Parameters
*self - pointer to this socket instance
*wait - pointer to the waitqueue element with the task that wants to sleep on this socket.
Returns
0 upon success
Definition at line 373 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, and mdbg.
 {
     int err = 0;
     mdbg(INFO4, "TCP removing from wait queue..");
     /* remove from socket wait queue */
     remove_wait_queue(sk_sleep(KKC_SOCK_TCP(self)->sock->sk), wait);
     // Fix for kernel 3.7.1 call inline function sk_sleep instead of original record sk_sleep in structure sk | by Jiri Rakosnik
     return err;
 }
static int kkc_sock_tcp_send (struct kkc_sock * self, void * buf, int buflen, kkc_sock_flags_t flags) static
<<private>> Sends out specified data.
What needs to be done:
setup a message header
setup iovec and store the buffer base address and length into it
asks the kernel to receive the message
Parameters
*self - pointer to this socket instance
*buf - buffer with the data to be sent
buflen - length of the buffer to be sent
flags - specify blocking or non-blocking mode.
Returns
number of bytes actually sent or error when < 0
Definition at line 246 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, and mdbg.
 {
     struct socket *sock;
     struct msghdr msg;
     struct iovec iov;
     int result = 0;
     mdbg(INFO4, "TCP Sending buffer %p length: %d bytes", buf, buflen);
     sock = KKC_SOCK_TCP(self)->sock;
     /* Setup message header */
     msg.msg_name = NULL;
     msg.msg_namelen = 0;
     msg.msg_control = NULL;
     msg.msg_controllen = 0;
     msg.msg_flags = 0;  /* blocking mode do we need to set
                  * this, it should be default for
                  * sending??*/
     iov.iov_base = buf;
     iov.iov_len = buflen;
     result = kernel_sendmsg(sock, &msg,(struct kvec*)&iov, 1, buflen);
     mdbg(INFO4, "TCP sending buffer %p length: %d bytes, sent %d", buf, buflen, result);
     return result;
 }
static int kkc_sock_tcp_shutdown (struct kkc_sock * self) static
<<private>> Disconnects the socket.
Connection is shutdown in both directions, it might be a good idea, to add the option for the user to specify which part of the connection is to be closed.
Parameters
*self - pointer to this socket instance
Returns
0 upon success
Definition at line 330 of file kkc_sock_tcp.c.
References KKC_SOCK_TCP, and mdbg.
Referenced by kkc_sock_tcp_free().
 {
     int err = 0;
     struct socket *sock = KKC_SOCK_TCP(self)->sock;
     mdbg(INFO4, "TCP disconnecting..");
     err = sock->ops->shutdown(sock, SEND_SHUTDOWN | RCV_SHUTDOWN);
     return err;
 }
Variable Documentation
struct kkc_arch kkc_arch_tcp = { .name = "tcp", .arch_ops = &tcp_arch_ops , .owner = THIS_MODULE, .data = NULL }
Declare the TCP architecture.
Definition at line 44 of file kkc_sock_tcp.c.