Clondike: tcmi_vfork_done_procmsg class
tcmi_vfork_done_procmsg class
tcmi_procmsg class
This class represents an vfork done notification message.
Data Structures
struct tcmi_vfork_done_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Macros
#define TCMI_VFORK_DONE_PROCMSG_DSC TCMI_MSG_DSC(TCMI_VFORK_DONE_PROCMSG_ID, tcmi_vfork_done_procmsg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
#define TCMI_VFORK_DONE_PROCMSG(m) ((struct tcmi_vfork_done_procmsg*)m)
Casts to the tcmi_vfork_done_procmsg instance.
Functions
static int tcmi_vfork_done_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_vfork_done_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Sends the vfork_done notification via a specified connection.
struct tcmi_msg * tcmi_vfork_done_procmsg_new_rx (u_int32_t msg_id)
<<public>> Vfork done process message constructor for receiving.
struct tcmi_msg * tcmi_vfork_done_procmsg_new_tx (pid_t dst_pid)
<<public>> Vfork done process message constructor for transferring.
Variables
static struct tcmi_procmsg_ops vfork_done_procmsg_ops
Message operations that support polymorphism.
Detailed Description
This class represents an vfork done notification message.
Data Structure Documentation
struct tcmi_vfork_done_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Definition at line 19 of file tcmi_vfork_done_procmsg.h.
Data Fields
struct tcmi_procmsg super parent class instance.
Macro Definition Documentation
#define TCMI_VFORK_DONE_PROCMSG (m) ((struct tcmi_vfork_done_procmsg*)m)
Casts to the tcmi_vfork_done_procmsg instance.
Definition at line 39 of file tcmi_vfork_done_procmsg.h.
Referenced by tcmi_vfork_done_procmsg_new_rx(), and tcmi_vfork_done_procmsg_new_tx().
#define TCMI_VFORK_DONE_PROCMSG_DSC TCMI_MSG_DSC(TCMI_VFORK_DONE_PROCMSG_ID, tcmi_vfork_done_procmsg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
Definition at line 36 of file tcmi_vfork_done_procmsg.h.
Function Documentation
struct tcmi_msg* tcmi_vfork_done_procmsg_new_rx (u_int32_t msg_id) read
<<public>> Vfork done process message constructor for receiving.
<<public>> Vfork done process message constructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID - used for verification instance.
Returns
a new message or NULL.
Definition at line 25 of file tcmi_vfork_done_procmsg.c.
References mdbg, TCMI_MSG, TCMI_PROCMSG, tcmi_procmsg_init_rx(), TCMI_VFORK_DONE_PROCMSG, TCMI_VFORK_DONE_PROCMSG_ID, and vfork_done_procmsg_ops.
 {
     struct tcmi_vfork_done_procmsg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_VFORK_DONE_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_VFORK_DONE_PROCMSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_VFORK_DONE_PROCMSG(kmalloc(sizeof(struct tcmi_vfork_done_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate vfork_done request message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_VFORK_DONE_PROCMSG_ID, &vfork_done_procmsg_ops)) {
         mdbg(ERR3, "Error initializing test request message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_vfork_done_procmsg_new_tx (pid_t dst_pid) read
<<public>> Vfork done process message constructor for transferring.
<<public>> Vfork done process message constructor for transferring.
The vfork_done notification has no transaction associated.
Parameters
dst_pid - destination process PID
Returns
a new message ready for the transfer or NULL.
Definition at line 64 of file tcmi_vfork_done_procmsg.c.
References mdbg, TCMI_MSG, TCMI_PROCMSG, tcmi_procmsg_init_tx(), TCMI_TRANSACTION_INVAL_ID, TCMI_VFORK_DONE_PROCMSG, TCMI_VFORK_DONE_PROCMSG_ID, and vfork_done_procmsg_ops.
Referenced by tcmi_mighooks_execve().
 {
     struct tcmi_vfork_done_procmsg *msg;
     if (!(msg = TCMI_VFORK_DONE_PROCMSG(kmalloc(sizeof(struct tcmi_vfork_done_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate vfork_done notification message");
         goto exit0;
     }
     /* Initialize the message for transfer, no transaction to be
      * created, no response expected, no timeout for response, not a reply to any transaction */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_VFORK_DONE_PROCMSG_ID, &vfork_done_procmsg_ops,
                  dst_pid, 0,
                  NULL, 0,
                  0, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing vfork_done notification message message");
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_vfork_done_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 105 of file tcmi_vfork_done_procmsg.c.
 {
     return 0;
 }
static int tcmi_vfork_done_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Sends the vfork_done notification via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully sent.
Definition at line 117 of file tcmi_vfork_done_procmsg.c.
 {
     return 0;
 }
Variable Documentation
struct tcmi_procmsg_ops vfork_done_procmsg_ops static
Initial value:
= {
    .recv = tcmi_vfork_done_procmsg_recv,
    .send = tcmi_vfork_done_procmsg_send
}
Message operations that support polymorphism.
Definition at line 125 of file tcmi_vfork_done_procmsg.c.
Referenced by tcmi_vfork_done_procmsg_new_rx(), and tcmi_vfork_done_procmsg_new_tx().