Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ctlfs/tcmi_ctlfs_file.c File Reference
tcmi_ctlfs_file.c File Reference
#include <linux/module.h>
#include <linux/errno.h>
#include <linux/slab.h>
#include "tcmi_ctlfs_file.h"
#include <dbg.h>
Macros
#define TCMI_CTLFS_FILE_PRIVATE
Functions
struct tcmi_ctlfs_entry * tcmi_ctlfs_intfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, const char namefmt[],...)
<<public>> Creates a new instance of a file.
struct tcmi_ctlfs_entry * tcmi_ctlfs_strfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, const char namefmt[],...)
<<public>> Creates a new instance of a file.
struct tcmi_ctlfs_entry * tcmi_ctlfs_rawfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, const char namefmt[],...)
<<public>> Creates a raw file instance.
void tcmi_ctlfs_file_unregister (struct tcmi_ctlfs_entry *self)
<<public>> This method unregisters the file uses the semaphore lock as protection from races.
void tcmi_ctlfs_file_unregister2 (struct tcmi_ctlfs_entry *self, tcmi_ctlfs_file_unreg_t unreg)
<<public>> This method unregisters the file and allows the user to specify the preferred way of unregistration (w/ or w/o the lock).
static struct tcmi_ctlfs_entry * tcmi_ctlfs_genericfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, proc_handler *proc_handler, const char namefmt[], va_list args)
<<private>> This is a generic method, that creates a new instance of a file as follows:
static void tcmi_ctlfs_file_release (struct tcmi_ctlfs_entry *entry)
<<private>> This method is used to free the data associated with the file.
static ssize_t tcmi_ctlfs_file_read (struct file *filp, char __user *buf, size_t count, loff_t *ppos)
<<private>> The read file operation, called by the read system call.
static ssize_t tcmi_ctlfs_file_write (struct file *filp, const char __user *buf, size_t count, loff_t *ppos)
<<private>> The write file operation, called by the write system call.
static void __tcmi_ctlfs_file_unregister (struct tcmi_ctlfs_entry *self)
This method is used when object associated with the file wants to unregister with the file.
EXPORT_SYMBOL_GPL (tcmi_ctlfs_intfile_new)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_strfile_new)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_rawfile_new)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_file_unregister)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_file_unregister2)
Variables
static struct tcmi_ctlfs_ops tcmi_ctlfs_file_ops
A file requires special entry operations to free all resources.
static struct file_operations tcmi_ctlfs_file_operations
File operations for VFS.
static struct inode_operations tcmi_ctlfs_file_inode_operations
Inode operations for VFS, the only method getattr is taken from fs/libfs.c.
Macro Definition Documentation
#define TCMI_CTLFS_FILE_PRIVATE
Definition at line 39 of file tcmi_ctlfs_file.c.
Function Documentation
static void __tcmi_ctlfs_file_unregister (struct tcmi_ctlfs_entry * self) static
This method is used when object associated with the file wants to unregister with the file.
The calling object is responsible for waking up a user process currently using this file (e.g. that have it open and might be sleeping in the read/write methods of the object).
This method assumes, that the file lock is already held by the caller. A typical use can be when the file is supposed to destroy itself upon user reading from or writing into the file (from inside the registered object's methods).
The unregistration requires resetting read/write methods and associated proc_handler and object pointer. The unregistered flag ensures that the methods will be ignored on the next read/write issued by any user process.
Parameters
*self - pointer to this file instance
Definition at line 447 of file tcmi_ctlfs_file.c.
References tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, tcmi_ctlfs_file::read_method, TCMI_CTLFS_FILE, tcmi_ctlfs_file_unregister_prepare(), and tcmi_ctlfs_file::write_method.
Referenced by tcmi_ctlfs_file_unregister(), and tcmi_ctlfs_file_unregister2().
 {
     struct tcmi_ctlfs_file *self_f = TCMI_CTLFS_FILE(self);
     if (self_f) {
         /* in case the object hasn't set the unregistered flag in advance */
         tcmi_ctlfs_file_unregister_prepare(self);
         self_f->object = NULL;
         self_f->read_method = NULL;
         self_f->write_method = NULL;
         self_f->proc_handler = NULL;
     }
 }
EXPORT_SYMBOL_GPL (tcmi_ctlfs_intfile_new)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_strfile_new)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_rawfile_new)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_file_unregister)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_file_unregister2)
static ssize_t tcmi_ctlfs_file_read (struct file * filp, char __user * buf, size_t count, loff_t * ppos) static
<<private>> The read file operation, called by the read system call.
The access to the file associated data is serialized, so that the object method always receives consistent data.
Read requests are possible only from offset (ppos) 0.
Initial check whether an object is already unregistered with the file is performed. This is to prevent calling the method when the the object is currently detaching from the file. The associated object might have already taken steps that don't allow calling the read method - E.g. has already woken up the sleeping process and doesn't want another process to call the method again.
The registered object is first sent a read request and data is returned
The data is then processed by the proc_handler. It is necessary to setup the ctl_table, so that the we can reuse the sysctl.c data parsing code for integers and strings.
Parameters
*filp - pointer to the kernel file object that is being read
*buf - user buffer where to store the result
count - number of bytes to be read
*ppos - pointer to the current position in the file
Returns
- when >= 0 - number of bytes written, the result from the proc_handler is usually 0, just to denote success converting from binary to ascii when < 0 - error
Definition at line 321 of file tcmi_ctlfs_file.c.
References count(), tcmi_ctlfs_file::data, tcmi_ctlfs_file::maxlen, mdbg, tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, tcmi_ctlfs_file::read_method, TCMI_CTLFS_DENTRY_TO_ENTRY, TCMI_CTLFS_FILE, tcmi_ctlfs_file_lock_interruptible(), tcmi_ctlfs_file_unlock(), and tcmi_ctlfs_file::unregistered.
 {
     struct tcmi_ctlfs_file *file =
         TCMI_CTLFS_FILE(TCMI_CTLFS_DENTRY_TO_ENTRY(filp->f_dentry));
     size_t res;
     ssize_t error = 0;
     struct ctl_table tbl = {
         .data = file->data,
         .maxlen = file->maxlen,
     };
     mdbg(INFO4, "file read in progress count=%lu, ppos=%Ld", (unsigned long)count, *ppos);
     if (tcmi_ctlfs_file_lock_interruptible(file)) {
         error = -ERESTARTSYS;
         goto exit0;
     }
     /* when object unregistering is in progress don't start any operation */
     if (file->unregistered)
         goto exit1;
     /* when trying from other position than 0, reset the file position and quit */
     if (*ppos) {
         *ppos = 0;
         goto exit1;
     }
     if (file->read_method)
         if ((error = file->read_method(file->object, file->data)))
             goto exit1;
     if (file->proc_handler) {
         /* res is in/out parameter, initially stores the number of requested bytes.
          The handler then returns the number of bytes really processed */
         res = count;
         if ((error = file->proc_handler(&tbl, 0, buf, &res, ppos)))
             goto exit1;
         error = (ssize_t)res;
     }
  exit1:
     tcmi_ctlfs_file_unlock(file);
     /* signal arrived, semaphore still busy */
  exit0:
     return error;
 }
static void tcmi_ctlfs_file_release (struct tcmi_ctlfs_entry * entry) static
<<private>> This method is used to free the data associated with the file.
No explicit locking is needed since:
the semaphore is already held by the unregister function or
the method of the registered object is currently executing and the file protects itself and this is an attempt to destroy the file from inside the object method.
Parameters
*entry - points to the file that is to be freed
Returns
0 upon succes.
Definition at line 285 of file tcmi_ctlfs_file.c.
References tcmi_ctlfs_file::data, mdbg, and TCMI_CTLFS_FILE.
 {
     struct tcmi_ctlfs_file *file = TCMI_CTLFS_FILE(entry);
     mdbg(INFO4, "Freeing file associated data(%p)", file->data);
     kfree(file->data);
     file->data = NULL;
 }
static ssize_t tcmi_ctlfs_file_write (struct file * filp, const char __user * buf, size_t count, loff_t * ppos) static
<<private>> The write file operation, called by the write system call.
The access to the file associated data is serialized, so that the object method always receives consistent data.
Initial check whether an object is already unregistered with the file is performed. This is to prevent calling the method when the the object is currently detaching from the file. The associated object might have already taken steps that don't allow calling the write method - E.g. has already woken up the sleeping process and doesn't want another process to call the method again.
The requested file offset can be arbitrary, but must not exceed the size of the data assoicated with the file - handled by the proc_handler
The data is first processed by the proc_handler. It is necessary to setup the ctl_table, so that the we can reuse the sysctl.c data parsing code for integers and strings.
Finally, the registered object is notified about the write event and the data is passed to it.
Parameters
*filp - pointer to the kernel file object that is being written
*buf - user buffer where to take the source data
count - number of bytes to be written
*ppos - pointer to the current position in the file
Returns
- when >= 0 - number of bytes written, the result from the proc_handler is usually 0, just to denote success converting the ascii data to binary when < 0 - error
Definition at line 392 of file tcmi_ctlfs_file.c.
References count(), tcmi_ctlfs_file::data, tcmi_ctlfs_file::maxlen, mdbg, tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, TCMI_CTLFS_DENTRY_TO_ENTRY, TCMI_CTLFS_FILE, tcmi_ctlfs_file_lock_interruptible(), tcmi_ctlfs_file_unlock(), tcmi_ctlfs_file::unregistered, and tcmi_ctlfs_file::write_method.
 {
     struct tcmi_ctlfs_file *file =
         TCMI_CTLFS_FILE(TCMI_CTLFS_DENTRY_TO_ENTRY(filp->f_dentry));
     size_t res;
     ssize_t error = 0;
     struct ctl_table tbl = {
         .data = file->data,
         .maxlen = file->maxlen,
     };
     mdbg(INFO4, "file write in progress count=%lu, ppos=%Ld", (unsigned long)count, *ppos);
     if (tcmi_ctlfs_file_lock_interruptible(file)) {
         error = -ERESTARTSYS;
         goto exit0;
     }
     /* when object unregistering is in progress don't start any operation */
     if (file->unregistered)
         goto exit1;
     if (file->proc_handler) {
         res = count;
         if ((error = file->proc_handler(&tbl, 1, (char __user *)buf, &res, ppos)))
             goto exit1;
     }
     if (file->write_method) {
         if ((error = file->write_method(file->object, file->data)))
             goto exit1;
         error = (ssize_t)res;
     }
  exit1:
     tcmi_ctlfs_file_unlock(file);
     /* signal arrived, semaphore still busy */
  exit0:
     return error;
 }
static struct tcmi_ctlfs_entry* tcmi_ctlfs_genericfile_new (struct tcmi_ctlfs_entry * parent, mode_t mode, void * object, object_method * read_method, object_method * write_method, int maxlen, proc_handler * proc_handler, const char namefmt[], va_list args) static read
<<private>> This is a generic method, that creates a new instance of a file as follows:
allocates a new instance and delegates the entry initialization to the parent class. There is a custom tcmi_ctlfs_ops vector as file destruction needs special handling. There are also file and inode specific operations.
allocates file associated data
registers the object and its 2 methods with the file. None of the methods are mandatory
there is a custom entry_free operation that releases the above allocated file data upon file destruction
proc_handler is associated with the data, so that ascii data can be parsed when passing from/to the object's read/write method
Parameters
*parent - pointer to the parent entry - has to be a directory
*mode - access rights for the inode
*object - points to the object that creates the file
*read_method - method of the file creator that will be called upon file read
*write_method - method of the file creator that will be called upon file write
maxlen - maximum length of the data in bytes
*proc_handler - data parsing handler that does the conversion from/to ascii
namefmt - nameformat string (printf style)
args - arguments to the format string
Returns
pointer to the new file or NULL
Definition at line 225 of file tcmi_ctlfs_file.c.
References tcmi_ctlfs_file::data, tcmi_ctlfs_file::f_sem, tcmi_ctlfs_file::maxlen, mdbg, tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, tcmi_ctlfs_file::read_method, TCMI_CTLFS_ENTRY, tcmi_ctlfs_entry_init(), tcmi_ctlfs_file_inode_operations, tcmi_ctlfs_file_operations, tcmi_ctlfs_file_ops, tcmi_ctlfs_file::unregistered, and tcmi_ctlfs_file::write_method.
Referenced by tcmi_ctlfs_intfile_new(), and tcmi_ctlfs_strfile_new().
 {
     struct tcmi_ctlfs_file *file;
     mdbg(INFO4, "Creating new file");
     if (!(file = kmalloc(sizeof(struct tcmi_ctlfs_file), GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate memory for file");
         goto exit0;
     }
     if (tcmi_ctlfs_entry_init(TCMI_CTLFS_ENTRY(file),
                   TCMI_CTLFS_ENTRY(parent),
                   S_IFREG | mode,
                   &tcmi_ctlfs_file_ops,
                   &tcmi_ctlfs_file_inode_operations,
                   &tcmi_ctlfs_file_operations, namefmt, args)) {
         mdbg(ERR3, "Failed to create the file");
         goto exit1;
     }
     if (!(file->data = kmalloc(maxlen, GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate %d bytes of file data", maxlen);
         goto exit2;
     }
     file->maxlen = maxlen;
     sema_init(&file->f_sem, 1); //Replaced macro init_MUTEX to sema_init for kernel 3.7.x | by Jiri Rakosnik
     /* object associated with the file */
     file->object = object;
     file->read_method = read_method; /*TESTING */
     file->write_method = write_method; /*TESTING */
     file->proc_handler = proc_handler; /* TESTING */
     /* indicates a valid object has registered with the file */
     file->unregistered = 0;
     return TCMI_CTLFS_ENTRY(file);
     /* error handling */
  exit2:
     kfree(file->data);
  exit1:
     kfree(file);
  exit0:
     return NULL;
 }