Clondike: User identification
User identification
tcmi_guest_rpc class
A <<singleton>> class that is executing RPC on PEN side.
Functions
long tcmi_guest_rpc_sys_getresuid (unsigned rpc_num, long params[6])
Getresud system call RPC.
Detailed Description
A <<singleton>> class that is executing RPC on PEN side.
Function Documentation
long tcmi_guest_rpc_sys_getresuid (unsigned rpc_num, long params[6])
Getresud system call RPC.
Parameters
rpc_num - RPC number
params - pointer to array with RPC parameters - three pointers to uid_t
Returns
RPC return value
Definition at line 40 of file tcmi_guest_userident_rpc.c.
References mdbg, tcmi_msg_put(), TCMI_RPCRESP_PROCMSG, tcmi_rpcresp_procmsg_data_base(), tcmi_rpcresp_procmsg_get_response(), and tcmi_rpcresp_procmsg_rtn().
 {
     struct tcmi_msg *r; long rtn, *resp_data;
     r = tcmi_rpcresp_procmsg_get_response(
             rpc_num, 0);
     if(r == NULL){
         mdbg(ERR3, "Response message hasn't arrived");
         return -EAGAIN;
     }
     rtn = tcmi_rpcresp_procmsg_rtn( TCMI_RPCRESP_PROCMSG(r) );
     if( rtn == 0 ){
         resp_data = tcmi_rpcresp_procmsg_data_base( TCMI_RPCRESP_PROCMSG(r), 0 );
         put_user( (uid_t)resp_data[0], (uid_t*)params[0] );
         put_user( (uid_t)resp_data[1], (uid_t*)params[1] );
         put_user( (uid_t)resp_data[2], (uid_t*)params[2] );
     }
     tcmi_msg_put(r);
     return rtn;
 }