Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/proxyfs/proxyfs_real_file.c File Reference
proxyfs_real_file.c File Reference
Main real file class (used by proxyfs_server_task)
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/vfs.h>
#include <asm/poll.h>
#include <dbg.h>
#include <proxyfs/proxyfs_peer.h>
#include "proxyfs_real_file.h"
Macros
#define PROXYFS_REAL_FILE_PRIVATE
#define PROXYFS_REAL_FILE_PROTECTED
Functions
long proxyfs_real_file_do_ioctl (struct proxyfs_real_file *self, unsigned int cmd, unsigned long arg)
<<public>> Do ioctl
int proxyfs_real_file_write (struct proxyfs_real_file *self)
<<public>> Write to real file
int proxyfs_real_file_read (struct proxyfs_real_file *self)
<<public>> Read from real file
int proxyfs_real_file_init (struct proxyfs_real_file *self)
<<public>> Initialize real_file
int proxyfs_real_file_open (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> "Open" file and send response message
int proxyfs_real_file_close (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> "Close" file
int proxyfs_real_file_fsync (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> fsync file
int proxyfs_real_file_mark_read_request (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> Marks file as read requested.
void proxyfs_real_file_destroy (struct proxyfs_real_file *self)
<<public>> Deinitialize real_file
static void proxyfs_real_file_write_buf_info (struct proxyfs_file_t *self, size_t *total_size, size_t *size, void **addr)
<<private>> Get maximum amount and address of data, that can be read at one time
static int proxyfs_real_file_write_from_peer (struct proxyfs_file_t *self, const char *buf, size_t count)
<<private>> Writes to file from peer - writes to read buffer
static int proxyfs_real_file_read_to_peer (struct proxyfs_file_t *self, char *buf, size_t count)
<<private>> Reads from file to peer - reads from write buffer
static void proxyfs_real_file_submit_read_to_peer (struct proxyfs_file_t *self, size_t count)
<<private>> Submit that data was written to file on other side (can be safely deleted from proxyfs_file buffer)
int proxyfs_real_file_add_shadow (struct proxyfs_real_file *self, struct task_struct *shadow)
<<public>> Adds shadow task into a shadow list of the file
int proxyfs_real_file_remove_shadow (struct proxyfs_real_file *self, struct task_struct *shadow)
<<public>> Removes shadow task from a shadow list of the file
int proxyfs_real_file_has_shadow (struct proxyfs_real_file *self, struct task_struct *shadow)
<<public>> Checks, whether shadow task is in list of shadow tasks of this file
Detailed Description
Main real file class (used by proxyfs_server_task)
Date: 08/02/2007
Author: Petr Malat
Id:
proxyfs_real_file.c,v 1.8 2008/01/17 14:36:44 stavam2 Exp
This file is part of Proxy filesystem (ProxyFS) Copyleft (C) 2007 Petr Malat
ProxyFS is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
ProxyFS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file proxyfs_real_file.c.
Macro Definition Documentation
#define PROXYFS_REAL_FILE_PRIVATE
Definition at line 39 of file proxyfs_real_file.c.
#define PROXYFS_REAL_FILE_PROTECTED
Definition at line 40 of file proxyfs_real_file.c.
Function Documentation
int proxyfs_real_file_add_shadow (struct proxyfs_real_file * self, struct task_struct * shadow)
<<public>> Adds shadow task into a shadow list of the file
Returns
0 on success
Definition at line 304 of file proxyfs_real_file.c.
References self.
Referenced by proxyfs_server_duplicate_overtaken_file(), and proxyfs_server_overtake_file().
{
     struct proxyfs_real_file_task* file_task = kmalloc(sizeof(struct proxyfs_real_file_task), GFP_KERNEL);
     if ( !file_task )
         return -ENOMEM;
     file_task->shadow = shadow;
     list_add( &file_task->shadow_list, &self->shadow_list );
     return 0;
 }
int proxyfs_real_file_has_shadow (struct proxyfs_real_file * self, struct task_struct * shadow)
<<public>> Checks, whether shadow task is in list of shadow tasks of this file
Returns
1, if the file is used also by provided shadow task
Definition at line 341 of file proxyfs_real_file.c.
References self.
Referenced by proxyfs_server_duplicate_all_parent().
{
     struct list_head *l;
     struct proxyfs_real_file_task* file_task;
     list_for_each( l,  &self->shadow_list ){
         file_task = list_entry(l, struct proxyfs_real_file_task, shadow_list);
         if ( file_task->shadow == shadow ) {
             return 1;
         }
     }
     return 0;
 }
static int proxyfs_real_file_read_to_peer (struct proxyfs_file_t * self, char * buf, size_t count) static
<<private>> Reads from file to peer - reads from write buffer
Parameters
*self - pointer to this file instance
*buf - pointer to buffer in kernelspace
count - size of data
Returns
the number of bytes read or error (negative number)
Definition at line 277 of file proxyfs_real_file.c.
References circ_buf_look_at(), and self.
 {
     int lenght;
     lenght = circ_buf_look_at( & self->write_buf, buf, count, self->write_buf_unconfirmed);
     if( lenght > 0 )
         self->write_buf_unconfirmed += lenght;
     return lenght;
 }
int proxyfs_real_file_remove_shadow (struct proxyfs_real_file * self, struct task_struct * shadow)
<<public>> Removes shadow task from a shadow list of the file
Returns
1, if list become empty, 0 otherwise
Definition at line 320 of file proxyfs_real_file.c.
References self.
Referenced by proxyfs_server_release_all().
{
     struct list_head *l, *nxt;
     struct proxyfs_real_file_task* file_task;
     list_for_each_safe( l, nxt, &self->shadow_list ){
         file_task = list_entry(l, struct proxyfs_real_file_task, shadow_list);
         if ( file_task->shadow == shadow ) {
             list_del(l);
             kfree(file_task);
             break;
         }
     }
     return list_empty(&self->shadow_list);
 }
static void proxyfs_real_file_submit_read_to_peer (struct proxyfs_file_t * self, size_t count) static
<<private>> Submit that data was written to file on other side (can be safely deleted from proxyfs_file buffer)
Parameters
*self - pointer to this file instance
count - ammount of submited data
Definition at line 293 of file proxyfs_real_file.c.
References circ_buf_adjust_read_ptr(), count(), and self.
 {
     circ_buf_adjust_read_ptr( & self->write_buf, count);
     self->write_buf_unconfirmed -= count;
 }
static void proxyfs_real_file_write_buf_info (struct proxyfs_file_t * self, size_t * total_size, size_t * size, void ** addr) static
<<private>> Get maximum amount and address of data, that can be read at one time
Parameters
*self - pointer to this file instance
*total_size - pointer to size_t into which a total available data count will be written
*size - pointer to size_t into which the data size will be written
**addr - pointer to void* into which the data address will be written
Definition at line 246 of file proxyfs_real_file.c.
References circ_buf_count(), circ_buf_get_read_addr(), circ_buf_get_read_size(), and self.
 {
     // TODO: No need of lock here? Comment why ;)
     *total_size = circ_buf_count( & self->write_buf );
     *size = circ_buf_get_read_size( & self->write_buf );
     *addr = circ_buf_get_read_addr( & self->write_buf );
 }
static int proxyfs_real_file_write_from_peer (struct proxyfs_file_t * self, const char * buf, size_t count) static
<<private>> Writes to file from peer - writes to read buffer
Parameters
*self - pointer to this file instance
*buf - pointer to data in kernelspace
count - size of data
Returns
the number of bytes written
Definition at line 261 of file proxyfs_real_file.c.
References circ_buf_write(), and self.
 {
     int lenght;
     lenght = circ_buf_write( & self->read_buf, buf, count );
     return lenght;
 }