Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/comm/tcmi_transaction.c File Reference
tcmi_transaction.c File Reference
#include <linux/types.h>
#include <linux/random.h>
#include <linux/jiffies.h>
#include <linux/slab.h>
#include "tcmi_transaction.h"
#include <dbg.h>
Macros
#define TCMI_TRANSACTION_PRIVATE
Functions
struct tcmi_transaction * tcmi_transaction_new (struct tcmi_slotvec *transactions, u_int32_t resp_id, unsigned long timeout)
<<public>> Creates a new transaction.
int tcmi_transaction_start (struct tcmi_transaction *self, int flags)
<<public>> Starts a transaction.
void * tcmi_transaction_abort (struct tcmi_transaction *self)
<<public>> Aborting the transaction requires:
int tcmi_transaction_complete (struct tcmi_transaction *self, void *context, u_int32_t resp_id)
<<public>> Completes a transaction and wakes up the processing thread.
struct tcmi_transaction * tcmi_transaction_lookup (struct tcmi_slotvec *transactions, u_int32_t trans_id)
<<public>> Tries to find a transaction based on its ID.
void tcmi_transaction_put (struct tcmi_transaction *self)
<<public>> Releases the instance.
static void tcmi_transaction_gen_id (struct tcmi_transaction *self)
<<private>> Generates a transaction ID.
static void tcmi_transaction_timer (unsigned long trans)
<<private>> Callback for the kernel timer that handles transaction timeouts.
Macro Definition Documentation
#define TCMI_TRANSACTION_PRIVATE
Definition at line 37 of file tcmi_transaction.c.
Function Documentation
static void tcmi_transaction_gen_id (struct tcmi_transaction * self) static
<<private>> Generates a transaction ID.
Parameters
*self - this transaction instance
Definition at line 361 of file tcmi_transaction.c.
References mdbg, and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_transaction_new().
 {
     u_int32_t id = TCMI_TRANSACTION_INVAL_ID;
     while (id == TCMI_TRANSACTION_INVAL_ID) {
         get_random_bytes(&id, sizeof(u_int32_t));
     }
     self->id = id;
     mdbg(INFO4, "Generated new transaction ID: %x", id);
 }
static void tcmi_transaction_timer (unsigned long trans) static
<<private>> Callback for the kernel timer that handles transaction timeouts.
This method is called upon timer expiration and means that no response has arrived so far, the transaction needs to be aborted. Expired flag is set to indicate that the timer has executed. This means that the 'complete' or 'abort' operations won't try to release the timer reference.
Also, the thread that handles the transaction is woken up.
Other transaction operations (complete, abort) are serialized with this method by means of del_timer_sync() - they cannot proceed any further until this method finishes.
Parameters
trans - pointer to the transaction instance
Definition at line 388 of file tcmi_transaction.c.
References mdbg, self, tcmi_transaction::state, TCMI_TRANSACTION_ABORTED, and tcmi_transaction_put().
Referenced by tcmi_transaction_new().
 {
     struct tcmi_transaction *self = (struct tcmi_transaction*) trans;
     self->state = TCMI_TRANSACTION_ABORTED;
     mdbg(INFO3, "Transaction ID %x expired, aborting..", self->id);
     tcmi_transaction_set_expired(self);
     tcmi_transaction_notify_owner(self);
     tcmi_transaction_put(self);
 }