Clondike: tcmi_ctlfs_file class
tcmi_ctlfs_file class
tcmi_ctlfs_entry class
A file in the TCMI control file system is used to export object interfaces.
Data Structures
struct tcmi_ctlfs_file
A file compound structure, extends the parent entry class.
Macros
#define TCMI_CTLFS_FILE(e) ((struct tcmi_ctlfs_file *)e)
Casts an entry to file.
Enumerations
enum tcmi_ctlfs_file_unreg_t { TCMI_CTLFS_FILE_REGULAR, TCMI_CTLFS_FILE_FROM_METHOD }
Describes the type of the file unregistration that is taking place.
Functions
static struct tcmi_ctlfs_entry * tcmi_ctlfs_genericfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, proc_handler *proc_handler, const char namefmt[], va_list args)
<<private>> This is a generic method, that creates a new instance of a file as follows:
static void tcmi_ctlfs_file_release (struct tcmi_ctlfs_entry *entry)
<<private>> This method is used to free the data associated with the file.
static ssize_t tcmi_ctlfs_file_read (struct file *filp, char __user *buf, size_t count, loff_t *ppos)
<<private>> The read file operation, called by the read system call.
static ssize_t tcmi_ctlfs_file_write (struct file *filp, const char __user *buf, size_t count, loff_t *ppos)
<<private>> The write file operation, called by the write system call.
static void __tcmi_ctlfs_file_unregister (struct tcmi_ctlfs_entry *self)
This method is used when object associated with the file wants to unregister with the file.
struct tcmi_ctlfs_entry * tcmi_ctlfs_intfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, const char namefmt[],...)
<<public>> Creates a new integer file instance.
struct tcmi_ctlfs_entry * tcmi_ctlfs_strfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, const char namefmt[],...)
<<public>> Creates a new string file instance.
struct tcmi_ctlfs_entry * tcmi_ctlfs_rawfile_new (struct tcmi_ctlfs_entry *parent, mode_t mode, void *object, object_method *read_method, object_method *write_method, int maxlen, const char namefmt[],...)
<<public>> Creates a raw file instance.
static void tcmi_ctlfs_file_unregister_prepare (struct tcmi_ctlfs_entry *self)
<<public>> Sets the unregistered flag of the file.
void tcmi_ctlfs_file_unregister (struct tcmi_ctlfs_entry *self)
<<public>> Unregisters the file.
void tcmi_ctlfs_file_unregister2 (struct tcmi_ctlfs_entry *self, tcmi_ctlfs_file_unreg_t unreg)
<<public>> Unregisters the file, advanced version
static int tcmi_ctlfs_file_lock_interruptible (struct tcmi_ctlfs_file *self)
<<public>> Locks this file instance, interruptible version, the process can be woken up by a signal.
static void tcmi_ctlfs_file_lock (struct tcmi_ctlfs_file *self)
<<public>> Locks this file instance.
static void tcmi_ctlfs_file_unlock (struct tcmi_ctlfs_file *self)
<<public>> Unlocks this file instance.
Variables
static struct tcmi_ctlfs_ops tcmi_ctlfs_file_ops
A file requires special entry operations to free all resources.
static struct file_operations tcmi_ctlfs_file_operations
File operations for VFS.
static struct inode_operations tcmi_ctlfs_file_inode_operations
Inode operations for VFS, the only method getattr is taken from fs/libfs.c.
Detailed Description
A file in the TCMI control file system is used to export object interfaces.
An object or a component creates a new control file for each method it wants to made available to the user space. The design idea is an extension of how linux sysctl works.
When a user space application reads from a file, the associated object is notified by calling its registered method. The result is communicated back to user space. Similarly to sysctl, there are various data types that can be passed to the objects method. Their conversion from/to ascii is handled by special handlers.
When a user space program writes data to the file, the data is parsed by the TCMI file object and the binary form is passed on to the registered object's method.
As in sysctl, following functions for parsing ascii input data are provided:
string
an array of integers
in addition, a raw data can be passed into the method of the registered object.
Based on this we can create three types of files:
integer files - methods of file instantiators accept/return integer data. Conversion from/to ascii is handled internally by this class
string files - methods of file instantiators accept/return string data. String parsing (overflow checks, new lines conversion) is handled internally by this class.
raw files - methods of file instantiators accept raw data. No conversion is performed.
The object that creates the control file, specifies maximum allowed data length as it is in sysctl.
To prevent code duplication, this class reuses the procfs functions(sysctl.c) - proc_dostring(), proc_dointvec() for ascii/binary conversions.
When the data is being passed to registered object's method, a mutual access guarantees integrity (implemented using mutex)
Data Structure Documentation
struct tcmi_ctlfs_file
A file compound structure, extends the parent entry class.
Contains a reference to the object whose read/write methods are to be called.
Definition at line 114 of file tcmi_ctlfs_file.h.
Data Fields
void * data storage for the data associated with the file.
struct semaphore f_sem mutex semaphore to serialized the file access via read/write methods.
int maxlen maximal data length.
void * object object that instantiated this file.
proc_handler * proc_handler data parsing handler (reused from sysctl).
object_method * read_method read method that the file instantiator registers.
struct tcmi_ctlfs_entry super parent class instance.
int unregistered flag that indicates when the object unregisters with the file
object_method * write_method write method that the file instantiator registers.
Macro Definition Documentation
#define TCMI_CTLFS_FILE (e) ((struct tcmi_ctlfs_file *)e)
Casts an entry to file.
Definition at line 140 of file tcmi_ctlfs_file.h.
Referenced by __tcmi_ctlfs_file_unregister(), tcmi_ctlfs_file_read(), tcmi_ctlfs_file_release(), tcmi_ctlfs_file_unregister(), tcmi_ctlfs_file_unregister_prepare(), and tcmi_ctlfs_file_write().
Enumeration Type Documentation
enum tcmi_ctlfs_file_unreg_t
Describes the type of the file unregistration that is taking place.
regular way - is explicit file unregistration without using the file. This is requires locking the actual file, before unregistering its object.
from a method of the registered object - this is a special situation when the file is already locked (access is serialized by read/write file operations). Therefore, no locking is needed.
Enumerator
TCMI_CTLFS_FILE_REGULAR
TCMI_CTLFS_FILE_FROM_METHOD
Definition at line 104 of file tcmi_ctlfs_file.h.
              {
     TCMI_CTLFS_FILE_REGULAR,
     TCMI_CTLFS_FILE_FROM_METHOD
 } tcmi_ctlfs_file_unreg_t;
Function Documentation
static void __tcmi_ctlfs_file_unregister (struct tcmi_ctlfs_entry * self) static
This method is used when object associated with the file wants to unregister with the file.
The calling object is responsible for waking up a user process currently using this file (e.g. that have it open and might be sleeping in the read/write methods of the object).
This method assumes, that the file lock is already held by the caller. A typical use can be when the file is supposed to destroy itself upon user reading from or writing into the file (from inside the registered object's methods).
The unregistration requires resetting read/write methods and associated proc_handler and object pointer. The unregistered flag ensures that the methods will be ignored on the next read/write issued by any user process.
Parameters
*self - pointer to this file instance
Definition at line 447 of file tcmi_ctlfs_file.c.
References tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, tcmi_ctlfs_file::read_method, TCMI_CTLFS_FILE, tcmi_ctlfs_file_unregister_prepare(), and tcmi_ctlfs_file::write_method.
Referenced by tcmi_ctlfs_file_unregister(), and tcmi_ctlfs_file_unregister2().
 {
     struct tcmi_ctlfs_file *self_f = TCMI_CTLFS_FILE(self);
     if (self_f) {
         /* in case the object hasn't set the unregistered flag in advance */
         tcmi_ctlfs_file_unregister_prepare(self);
         self_f->object = NULL;
         self_f->read_method = NULL;
         self_f->write_method = NULL;
         self_f->proc_handler = NULL;
     }
 }
static void tcmi_ctlfs_file_lock (struct tcmi_ctlfs_file * self) inline static
<<public>> Locks this file instance.
Parameters
*self - pointer to this file instance
Definition at line 209 of file tcmi_ctlfs_file.h.
References self.
Referenced by tcmi_ctlfs_file_unregister().
 {
         down(&self->f_sem);
 }
static int tcmi_ctlfs_file_lock_interruptible (struct tcmi_ctlfs_file * self) inline static
<<public>> Locks this file instance, interruptible version, the process can be woken up by a signal.
Parameters
*self - pointer to this file instance
Definition at line 199 of file tcmi_ctlfs_file.h.
References self.
Referenced by tcmi_ctlfs_file_read(), and tcmi_ctlfs_file_write().
 {
     return (down_interruptible(&self->f_sem));
 }
static ssize_t tcmi_ctlfs_file_read (struct file * filp, char __user * buf, size_t count, loff_t * ppos) static
<<private>> The read file operation, called by the read system call.
The access to the file associated data is serialized, so that the object method always receives consistent data.
Read requests are possible only from offset (ppos) 0.
Initial check whether an object is already unregistered with the file is performed. This is to prevent calling the method when the the object is currently detaching from the file. The associated object might have already taken steps that don't allow calling the read method - E.g. has already woken up the sleeping process and doesn't want another process to call the method again.
The registered object is first sent a read request and data is returned
The data is then processed by the proc_handler. It is necessary to setup the ctl_table, so that the we can reuse the sysctl.c data parsing code for integers and strings.
Parameters
*filp - pointer to the kernel file object that is being read
*buf - user buffer where to store the result
count - number of bytes to be read
*ppos - pointer to the current position in the file
Returns
- when >= 0 - number of bytes written, the result from the proc_handler is usually 0, just to denote success converting from binary to ascii when < 0 - error
Definition at line 321 of file tcmi_ctlfs_file.c.
References count(), tcmi_ctlfs_file::data, tcmi_ctlfs_file::maxlen, mdbg, tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, tcmi_ctlfs_file::read_method, TCMI_CTLFS_DENTRY_TO_ENTRY, TCMI_CTLFS_FILE, tcmi_ctlfs_file_lock_interruptible(), tcmi_ctlfs_file_unlock(), and tcmi_ctlfs_file::unregistered.
 {
     struct tcmi_ctlfs_file *file =
         TCMI_CTLFS_FILE(TCMI_CTLFS_DENTRY_TO_ENTRY(filp->f_dentry));
     size_t res;
     ssize_t error = 0;
     struct ctl_table tbl = {
         .data = file->data,
         .maxlen = file->maxlen,
     };
     mdbg(INFO4, "file read in progress count=%lu, ppos=%Ld", (unsigned long)count, *ppos);
     if (tcmi_ctlfs_file_lock_interruptible(file)) {
         error = -ERESTARTSYS;
         goto exit0;
     }
     /* when object unregistering is in progress don't start any operation */
     if (file->unregistered)
         goto exit1;
     /* when trying from other position than 0, reset the file position and quit */
     if (*ppos) {
         *ppos = 0;
         goto exit1;
     }
     if (file->read_method)
         if ((error = file->read_method(file->object, file->data)))
             goto exit1;
     if (file->proc_handler) {
         /* res is in/out parameter, initially stores the number of requested bytes.
          The handler then returns the number of bytes really processed */
         res = count;
         if ((error = file->proc_handler(&tbl, 0, buf, &res, ppos)))
             goto exit1;
         error = (ssize_t)res;
     }
  exit1:
     tcmi_ctlfs_file_unlock(file);
     /* signal arrived, semaphore still busy */
  exit0:
     return error;
 }
static void tcmi_ctlfs_file_release (struct tcmi_ctlfs_entry * entry) static
<<private>> This method is used to free the data associated with the file.
No explicit locking is needed since:
the semaphore is already held by the unregister function or
the method of the registered object is currently executing and the file protects itself and this is an attempt to destroy the file from inside the object method.
Parameters
*entry - points to the file that is to be freed
Returns
0 upon succes.
Definition at line 285 of file tcmi_ctlfs_file.c.
References tcmi_ctlfs_file::data, mdbg, and TCMI_CTLFS_FILE.
 {
     struct tcmi_ctlfs_file *file = TCMI_CTLFS_FILE(entry);
     mdbg(INFO4, "Freeing file associated data(%p)", file->data);
     kfree(file->data);
     file->data = NULL;
 }
static void tcmi_ctlfs_file_unlock (struct tcmi_ctlfs_file * self) inline static
<<public>> Unlocks this file instance.
Parameters
*self - pointer to this file instance
Definition at line 219 of file tcmi_ctlfs_file.h.
References self.
Referenced by tcmi_ctlfs_file_read(), tcmi_ctlfs_file_unregister(), and tcmi_ctlfs_file_write().
 {
         up(&self->f_sem);
 }
void tcmi_ctlfs_file_unregister (struct tcmi_ctlfs_entry * self)
<<public>> Unregisters the file.
<<public>> Unregisters the file.
This is the prefered way of detaching the file from an object. If the file is to unregister itself (e.g. from inside the registered object's methods), the previous version is recommended to prevent deadlocks.
Parameters
*self - pointer to this file instance
Definition at line 155 of file tcmi_ctlfs_file.c.
References __tcmi_ctlfs_file_unregister(), TCMI_CTLFS_FILE, tcmi_ctlfs_file_lock(), and tcmi_ctlfs_file_unlock().
Referenced by tcmi_ccnman_stop_ctlfs_files(), tcmi_ccnmigman_stop_ctlfs_files(), tcmi_ctlfs_file_unregister2(), tcmi_man_init_ctlfs_files(), tcmi_man_stop_ctlfs_files(), tcmi_migman_init_ctlfs_files(), tcmi_migman_stop_ctlfs_files(), tcmi_module_exit(), tcmi_penman_stop_ctlfs_files(), tcmi_penmigman_stop_ctlfs_files(), tcmi_sock_new(), tcmi_sock_put(), and tcmi_task_put().
 {
     struct tcmi_ctlfs_file *self_f = TCMI_CTLFS_FILE(self);
     if (self_f) {
         tcmi_ctlfs_file_lock(self_f);
         __tcmi_ctlfs_file_unregister(self);
         tcmi_ctlfs_file_unlock(self_f);
     }
 }
void tcmi_ctlfs_file_unregister2 (struct tcmi_ctlfs_entry * self, tcmi_ctlfs_file_unreg_t unreg)
<<public>> Unregisters the file, advanced version
<<public>> Unregisters the file, advanced version
It is typically used if owning object uses this file is for unregistering other files including this file. All work is delegate to either __tcmi_ctlfs_file_unregister() or tcmi_ctlfs_file_unregister()
Parameters
*self - pointer to this file instance
unreg - describes a unregistration type, if a regular shutdown is requested, the file is unregistered using the lock version. A file unregistrationn from inside the registered object's method requires using a lock free version. The access to the file is already serialized.
Definition at line 181 of file tcmi_ctlfs_file.c.
References __tcmi_ctlfs_file_unregister(), TCMI_CTLFS_FILE_FROM_METHOD, and tcmi_ctlfs_file_unregister().
Referenced by tcmi_migman_stop_ctlfs_files().
 {
     /* unregistration issued from owning object's method, no locking */
     if (unreg == TCMI_CTLFS_FILE_FROM_METHOD)
         __tcmi_ctlfs_file_unregister(self);
     /* default case - explicit unregistration , requires locking*/
     else
         tcmi_ctlfs_file_unregister(self);
 }
static void tcmi_ctlfs_file_unregister_prepare (struct tcmi_ctlfs_entry * self) inline static
<<public>> Sets the unregistered flag of the file.
This is used when the associated object is about to unregister from the file. However, the object needs to be guaranteed that from now on, no new process will send him a read/write message. This is exactly what the unregistered flag does.
Parameters
*self - pointer to this file instance
See Also
tcmi_ctlfs_file_unregister()
Definition at line 179 of file tcmi_ctlfs_file.h.
References TCMI_CTLFS_FILE.
Referenced by __tcmi_ctlfs_file_unregister().
 {
     if (self)
         TCMI_CTLFS_FILE(self)->unregistered = 1;
 }
static ssize_t tcmi_ctlfs_file_write (struct file * filp, const char __user * buf, size_t count, loff_t * ppos) static
<<private>> The write file operation, called by the write system call.
The access to the file associated data is serialized, so that the object method always receives consistent data.
Initial check whether an object is already unregistered with the file is performed. This is to prevent calling the method when the the object is currently detaching from the file. The associated object might have already taken steps that don't allow calling the write method - E.g. has already woken up the sleeping process and doesn't want another process to call the method again.
The requested file offset can be arbitrary, but must not exceed the size of the data assoicated with the file - handled by the proc_handler
The data is first processed by the proc_handler. It is necessary to setup the ctl_table, so that the we can reuse the sysctl.c data parsing code for integers and strings.
Finally, the registered object is notified about the write event and the data is passed to it.
Parameters
*filp - pointer to the kernel file object that is being written
*buf - user buffer where to take the source data
count - number of bytes to be written
*ppos - pointer to the current position in the file
Returns
- when >= 0 - number of bytes written, the result from the proc_handler is usually 0, just to denote success converting the ascii data to binary when < 0 - error
Definition at line 392 of file tcmi_ctlfs_file.c.
References count(), tcmi_ctlfs_file::data, tcmi_ctlfs_file::maxlen, mdbg, tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, TCMI_CTLFS_DENTRY_TO_ENTRY, TCMI_CTLFS_FILE, tcmi_ctlfs_file_lock_interruptible(), tcmi_ctlfs_file_unlock(), tcmi_ctlfs_file::unregistered, and tcmi_ctlfs_file::write_method.
 {
     struct tcmi_ctlfs_file *file =
         TCMI_CTLFS_FILE(TCMI_CTLFS_DENTRY_TO_ENTRY(filp->f_dentry));
     size_t res;
     ssize_t error = 0;
     struct ctl_table tbl = {
         .data = file->data,
         .maxlen = file->maxlen,
     };
     mdbg(INFO4, "file write in progress count=%lu, ppos=%Ld", (unsigned long)count, *ppos);
     if (tcmi_ctlfs_file_lock_interruptible(file)) {
         error = -ERESTARTSYS;
         goto exit0;
     }
     /* when object unregistering is in progress don't start any operation */
     if (file->unregistered)
         goto exit1;
     if (file->proc_handler) {
         res = count;
         if ((error = file->proc_handler(&tbl, 1, (char __user *)buf, &res, ppos)))
             goto exit1;
     }
     if (file->write_method) {
         if ((error = file->write_method(file->object, file->data)))
             goto exit1;
         error = (ssize_t)res;
     }
  exit1:
     tcmi_ctlfs_file_unlock(file);
     /* signal arrived, semaphore still busy */
  exit0:
     return error;
 }
static struct tcmi_ctlfs_entry* tcmi_ctlfs_genericfile_new (struct tcmi_ctlfs_entry * parent, mode_t mode, void * object, object_method * read_method, object_method * write_method, int maxlen, proc_handler * proc_handler, const char namefmt[], va_list args) static read
<<private>> This is a generic method, that creates a new instance of a file as follows:
allocates a new instance and delegates the entry initialization to the parent class. There is a custom tcmi_ctlfs_ops vector as file destruction needs special handling. There are also file and inode specific operations.
allocates file associated data
registers the object and its 2 methods with the file. None of the methods are mandatory
there is a custom entry_free operation that releases the above allocated file data upon file destruction
proc_handler is associated with the data, so that ascii data can be parsed when passing from/to the object's read/write method
Parameters
*parent - pointer to the parent entry - has to be a directory
*mode - access rights for the inode
*object - points to the object that creates the file
*read_method - method of the file creator that will be called upon file read
*write_method - method of the file creator that will be called upon file write
maxlen - maximum length of the data in bytes
*proc_handler - data parsing handler that does the conversion from/to ascii
namefmt - nameformat string (printf style)
args - arguments to the format string
Returns
pointer to the new file or NULL
Definition at line 225 of file tcmi_ctlfs_file.c.
References tcmi_ctlfs_file::data, tcmi_ctlfs_file::f_sem, tcmi_ctlfs_file::maxlen, mdbg, tcmi_ctlfs_file::object, tcmi_ctlfs_file::proc_handler, tcmi_ctlfs_file::read_method, TCMI_CTLFS_ENTRY, tcmi_ctlfs_entry_init(), tcmi_ctlfs_file_inode_operations, tcmi_ctlfs_file_operations, tcmi_ctlfs_file_ops, tcmi_ctlfs_file::unregistered, and tcmi_ctlfs_file::write_method.
Referenced by tcmi_ctlfs_intfile_new(), and tcmi_ctlfs_strfile_new().
 {
     struct tcmi_ctlfs_file *file;
     mdbg(INFO4, "Creating new file");
     if (!(file = kmalloc(sizeof(struct tcmi_ctlfs_file), GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate memory for file");
         goto exit0;
     }
     if (tcmi_ctlfs_entry_init(TCMI_CTLFS_ENTRY(file),
                   TCMI_CTLFS_ENTRY(parent),
                   S_IFREG | mode,
                   &tcmi_ctlfs_file_ops,
                   &tcmi_ctlfs_file_inode_operations,
                   &tcmi_ctlfs_file_operations, namefmt, args)) {
         mdbg(ERR3, "Failed to create the file");
         goto exit1;
     }
     if (!(file->data = kmalloc(maxlen, GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate %d bytes of file data", maxlen);
         goto exit2;
     }
     file->maxlen = maxlen;
     sema_init(&file->f_sem, 1); //Replaced macro init_MUTEX to sema_init for kernel 3.x.x | by Jiri Rakosnik
     /* object associated with the file */
     file->object = object;
     file->read_method = read_method; /*TESTING */
     file->write_method = write_method; /*TESTING */
     file->proc_handler = proc_handler; /* TESTING */
     /* indicates a valid object has registered with the file */
     file->unregistered = 0;
     return TCMI_CTLFS_ENTRY(file);
     /* error handling */
  exit2:
     kfree(file->data);
  exit1:
     kfree(file);
  exit0:
     return NULL;
 }
struct tcmi_ctlfs_entry* tcmi_ctlfs_intfile_new (struct tcmi_ctlfs_entry * parent, mode_t mode, void * object, object_method * read_method, object_method * write_method, int maxlen, const char namefmt[], ...) read
<<public>> Creates a new integer file instance.
<<public>> Creates a new integer file instance.
The file will be used as an interface of the registered object to the user space. It allows calling object methods and pass integer numbers as arguments in ascii form.
For conversion ascii<->integer, the proc_dointvec() function is used from kernel/sysctl.c
Parameters
*parent - pointer to the parent entry - has to be a directory
*mode - access rights for the inode
*object - points to the object that creates the file
*read_method - method of the file creator that will be called upon file read
*write_method - method of the file creator that will be called upon file write
maxlen - maximum length of the data in bytes
namefmt - nameformat string (printf style)
Returns
pointer to the new file or NULL
Definition at line 63 of file tcmi_ctlfs_file.c.
References args, and tcmi_ctlfs_genericfile_new().
Referenced by tcmi_ccnman_init_ctlfs_files(), tcmi_ccnmigman_init_ctlfs_files(), tcmi_man_init_ctlfs_files(), tcmi_migman_init_ctlfs_files(), tcmi_module_init(), tcmi_penmigman_init_ctlfs_files(), tcmi_task_init(), and tcmi_task_set_remote_pid().
 {
     struct tcmi_ctlfs_entry *file;
     va_list args;
     va_start(args, namefmt);
     file = tcmi_ctlfs_genericfile_new(parent, mode, object,
                       read_method, write_method,
                       maxlen, proc_dointvec, namefmt, args);
     va_end(args);
     return file;
 }
struct tcmi_ctlfs_entry* tcmi_ctlfs_rawfile_new (struct tcmi_ctlfs_entry * parent, mode_t mode, void * object, object_method * read_method, object_method * write_method, int maxlen, const char namefmt[], ...) read
<<public>> Creates a raw file instance.
The file will be used as an interface of the registered object to the user space. It allows calling object methods and passing raw unprocessed data as an argument.
Parameters
*parent - pointer to the parent entry - has to be a directory
*mode - access rights for the inode
*object - points to the object that creates the file
*read_method - method of the file creator that will be called upon file read
*write_method - method of the file creator that will be called upon file write
maxlen - maximum length of the data in bytes
namefmt - nameformat string (printf style)
Returns
pointer to the new file or NULL
Note
Currently not implemented
Definition at line 134 of file tcmi_ctlfs_file.c.
 {
     return NULL;
 }
struct tcmi_ctlfs_entry* tcmi_ctlfs_strfile_new (struct tcmi_ctlfs_entry * parent, mode_t mode, void * object, object_method * read_method, object_method * write_method, int maxlen, const char namefmt[], ...) read
<<public>> Creates a new string file instance.
<<public>> Creates a new string file instance.
The file will be used as an interface of the registered object to the user space. It allows calling object methods and pass strings as an argument.
For conversion overflow checking and newlines conversions are handled by proc_dostring(). The function is used from kernel/sysctl.c
Parameters
*parent - pointer to the parent entry - has to be a directory
*mode - access rights for the inode
*object - points to the object that creates the file
*read_method - method of the file creator that will be called upon file read
*write_method - method of the file creator that will be called upon file write
maxlen - maximum length of the data in bytes
namefmt - nameformat string (printf style)
Returns
pointer to the new file or NULL
Definition at line 100 of file tcmi_ctlfs_file.c.
References args, and tcmi_ctlfs_genericfile_new().
Referenced by tcmi_ccnman_init_ctlfs_files(), tcmi_migman_init_ctlfs_files(), tcmi_penman_init_ctlfs_files(), and tcmi_sock_new().
 {
     struct tcmi_ctlfs_entry *file;
     va_list args;
     va_start(args, namefmt);
     file = tcmi_ctlfs_genericfile_new(parent, mode, object,
                       read_method, write_method,
                       maxlen, proc_dostring, namefmt, args);
     va_end(args);
     return file;
 }
Variable Documentation
struct inode_operations tcmi_ctlfs_file_inode_operations static
Initial value:
= {
    .getattr    = simple_getattr,
}
Inode operations for VFS, the only method getattr is taken from fs/libfs.c.
Definition at line 471 of file tcmi_ctlfs_file.c.
Referenced by tcmi_ctlfs_genericfile_new().
struct file_operations tcmi_ctlfs_file_operations static
Initial value:
= {
    .read       = tcmi_ctlfs_file_read,
    .write      = tcmi_ctlfs_file_write,
}
File operations for VFS.
Definition at line 465 of file tcmi_ctlfs_file.c.
Referenced by tcmi_ctlfs_genericfile_new().
struct tcmi_ctlfs_ops tcmi_ctlfs_file_ops static
Initial value:
= {
    .entry_release = tcmi_ctlfs_file_release,
}
A file requires special entry operations to free all resources.
Definition at line 461 of file tcmi_ctlfs_file.c.
Referenced by tcmi_ctlfs_genericfile_new().