Clondike: tcmi_exit_procmsg class
tcmi_exit_procmsg class
tcmi_procmsg class
This class represents an exit message that will be sent out by a guest process upon exit.
Data Structures
struct tcmi_exit_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Macros
#define TCMI_EXIT_PROCMSG_DSC TCMI_MSG_DSC(TCMI_EXIT_PROCMSG_ID, tcmi_exit_procmsg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
#define TCMI_EXIT_PROCMSG(m) ((struct tcmi_exit_procmsg*)m)
Casts to the tcmi_exit_procmsg instance.
Functions
static int tcmi_exit_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_exit_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Sends the exit code via a specified connection.
struct tcmi_msg * tcmi_exit_procmsg_new_rx (u_int32_t msg_id)
<<public>> Exit process message constructor for receiving.
struct tcmi_msg * tcmi_exit_procmsg_new_tx (pid_t dst_pid, int32_t code)
<<public>> Exit process message constructor for transferring.
static int32_t tcmi_exit_procmsg_code (struct tcmi_exit_procmsg *self)
Exit code accessor.
Variables
static struct tcmi_procmsg_ops exit_procmsg_ops
Message operations that support polymorphism.
Detailed Description
This class represents an exit message that will be sent out by a guest process upon exit.
The receiving shadow process has to take appropriate actions.
Data Structure Documentation
struct tcmi_exit_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Definition at line 48 of file tcmi_exit_procmsg.h.
Data Fields
int32_t code exit code the message is carrying.
struct tcmi_procmsg super parent class instance.
Macro Definition Documentation
#define TCMI_EXIT_PROCMSG (m) ((struct tcmi_exit_procmsg*)m)
Casts to the tcmi_exit_procmsg instance.
Definition at line 70 of file tcmi_exit_procmsg.h.
Referenced by tcmi_exit_procmsg_new_rx(), tcmi_exit_procmsg_new_tx(), tcmi_exit_procmsg_recv(), tcmi_exit_procmsg_send(), and tcmi_shadowtask_process_msg().
#define TCMI_EXIT_PROCMSG_DSC TCMI_MSG_DSC(TCMI_EXIT_PROCMSG_ID, tcmi_exit_procmsg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
Definition at line 67 of file tcmi_exit_procmsg.h.
Function Documentation
static int32_t tcmi_exit_procmsg_code (struct tcmi_exit_procmsg * self) inline static
Exit code accessor.
Parameters
*self - this message instance
Returns
exit code
Definition at line 78 of file tcmi_exit_procmsg.h.
Referenced by tcmi_shadowtask_process_msg().
 {
     return self->code;
 }
struct tcmi_msg* tcmi_exit_procmsg_new_rx (u_int32_t msg_id) read
<<public>> Exit process message constructor for receiving.
<<public>> Exit process message constructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID - used for verification instance.
Returns
a new error message or NULL.
Definition at line 51 of file tcmi_exit_procmsg.c.
References exit_procmsg_ops, mdbg, TCMI_EXIT_PROCMSG, TCMI_EXIT_PROCMSG_ID, TCMI_MSG, TCMI_PROCMSG, and tcmi_procmsg_init_rx().
 {
     struct tcmi_exit_procmsg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_EXIT_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_EXIT_PROCMSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_EXIT_PROCMSG(kmalloc(sizeof(struct tcmi_exit_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate test request message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_EXIT_PROCMSG_ID, &exit_procmsg_ops)) {
         mdbg(ERR3, "Error initializing test request message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_exit_procmsg_new_tx (pid_t dst_pid, int32_t code) read
<<public>> Exit process message constructor for transferring.
<<public>> Exit process message constructor for transferring.
The exit message has no transaction associated. The user specifies the desired exit code and the destination PID only.
Parameters
dst_pid - destination process PID
code - exit code
Returns
a new error ready for the transfer or NULL.
Definition at line 92 of file tcmi_exit_procmsg.c.
References tcmi_exit_procmsg::code, exit_procmsg_ops, mdbg, TCMI_EXIT_PROCMSG, TCMI_EXIT_PROCMSG_ID, TCMI_MSG, TCMI_PROCMSG, tcmi_procmsg_init_tx(), and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_guesttask_exit(), and tcmi_guesttask_post_fork().
 {
     struct tcmi_exit_procmsg *msg;
     if (!(msg = TCMI_EXIT_PROCMSG(kmalloc(sizeof(struct tcmi_exit_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate test request message");
         goto exit0;
     }
     /* Initialize the message for transfer, no transaction to be
      * created, no response expected, no timeout for response, not a reply to any transaction */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_EXIT_PROCMSG_ID, &exit_procmsg_ops,
                  dst_pid, 0,
                  NULL, 0,
                  0, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing test request message message");
         goto exit1;
     }
     msg->code = code;
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_exit_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the exit code requires reading the error code from the specified connection
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 136 of file tcmi_exit_procmsg.c.
References tcmi_exit_procmsg::code, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, and TCMI_EXIT_PROCMSG.
 {
     int err;
     struct tcmi_exit_procmsg *self_msg = TCMI_EXIT_PROCMSG(self);
     err = kkc_sock_recv(sock, &self_msg->code,
                 sizeof(self_msg->code), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Received exit code: %lu", (long)self_msg->code);
     return err;
 }
static int tcmi_exit_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Sends the exit code via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully sent.
Definition at line 155 of file tcmi_exit_procmsg.c.
References tcmi_exit_procmsg::code, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, and TCMI_EXIT_PROCMSG.
 {
     int err;
     struct tcmi_exit_procmsg *self_msg = TCMI_EXIT_PROCMSG(self);
     err = kkc_sock_send(sock, &self_msg->code,
                 sizeof(self_msg->code), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Sent exit code: %lu", (long)self_msg->code);
     return err;
 }
Variable Documentation
struct tcmi_procmsg_ops exit_procmsg_ops static
Initial value:
= {
    .recv = tcmi_exit_procmsg_recv,
    .send = tcmi_exit_procmsg_send
}
Message operations that support polymorphism.
Definition at line 171 of file tcmi_exit_procmsg.c.
Referenced by tcmi_exit_procmsg_new_rx(), and tcmi_exit_procmsg_new_tx().