Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ckpt/tcmi_ckpt_regs.h File Reference
tcmi_ckpt_regs.h File Reference
#include <asm/uaccess.h>
#include <arch/current/regs.h>
#include "tcmi_ckpt.h"
Functions
static int tcmi_ckpt_regs_write (struct tcmi_ckpt *ckpt, struct pt_regs *regs)
Writes a current process registers into the checkpoint file.
static int tcmi_ckpt_regs_read (struct tcmi_ckpt *ckpt, struct pt_regs *regs)
Reads a process registers from the checkpoint file and sets them for the current process.
Function Documentation
static int tcmi_ckpt_regs_read (struct tcmi_ckpt * ckpt, struct pt_regs * regs) inline static
Reads a process registers from the checkpoint file and sets them for the current process.
Parameters
*ckpt - checkpoint file where the area is to be stored
*regs - registers of the current process
Returns
0 upon success.
Definition at line 89 of file tcmi_ckpt_regs.h.
References tcmi_ckpt_hdr::checkpoint_arch, debug_registers(), tcmi_ckpt::hdr, tcmi_ckpt_hdr::is_32bit_application, load_from_platform_registers(), mdbg, and tcmi_ckpt_read().
 {
     void* platform_regs = NULL;
     int32_t regs_length;
     if (tcmi_ckpt_read(ckpt, &regs_length, sizeof(regs_length)) < 0) {
         mdbg(ERR3, "Error reading process register length");
         goto exit0;
     }
     platform_regs = kmalloc(regs_length, GFP_KERNEL);
     if ( !platform_regs ) {
         mdbg(ERR3, "Not enough memory to load registers");
         goto exit0;
     }
     /* Read the regisiters */
     if (tcmi_ckpt_read(ckpt, platform_regs, regs_length) < 0) {
         mdbg(ERR3, "Error reading process register descriptor header");
         goto exit1;
     }
     load_from_platform_registers(platform_regs, regs, ckpt->hdr.checkpoint_arch, ckpt->hdr.is_32bit_application);
     platform_start_thread(regs, instruction_pointer(regs), stack_pointer(regs), ckpt->hdr.checkpoint_arch, ckpt->hdr.is_32bit_application);
     mdbg(INFO4, "Read process registers:");
     debug_registers(regs);
     kfree(platform_regs);
     return 0;
     /* error handling */
  exit1:
     kfree(platform_regs);
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_regs_write (struct tcmi_ckpt * ckpt, struct pt_regs * regs) inline static
Writes a current process registers into the checkpoint file.
Adjusts the EIP value if the process has aborted a system call.
Parameters
*ckpt - checkpoint file where the area is to be stored
*regs - registers of the current process
Returns
0 upon success.
Definition at line 47 of file tcmi_ckpt_regs.h.
References debug_registers(), get_registers(), mdbg, and tcmi_ckpt_write().
 {
     struct tcmi_regs tcmi_regs;
     int32_t regs_length;
     mdbg(INFO4, "Getting registers: %p", regs);
     /* copy the process registers into the header */
     get_registers(regs, &tcmi_regs);
     regs_length = sizeof(tcmi_regs);
     /* write length of the registers structure to ckpt (every architecture can have different length) */
     if (tcmi_ckpt_write(ckpt, &regs_length, sizeof(regs_length)) < 0) {
         mdbg(ERR3, "Error writing registers length");
         goto exit0;
     }
     /* write the registers into the checkpoint */
     if (tcmi_ckpt_write(ckpt, &tcmi_regs, sizeof(tcmi_regs)) < 0) {
         mdbg(ERR3, "Error writing registers");
         goto exit0;
     }
     mdbg(INFO4, "Written process registers:");
     debug_registers(regs);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }