Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/tcmi/ckpt/tcmi_ckptcom.c File Reference
tcmi_ckptcom.c File Reference
Process checkpointing component.
#include <linux/module.h>
#include <linux/fs_struct.h>
#include <linux/fdtable.h>
#include "tcmi_ckpt.h"
#include "tcmi_ckpt_mm.h"
#include "tcmi_ckpt_regs.h"
#include "tcmi_ckpt_thread.h"
#include "tcmi_ckpt_fsstruct.h"
#include "tcmi_ckpt_resources.h"
#include "tcmi_ckptcom.h"
#include "tcmi_ckpt_sig.h"
#include "tcmi_ckpt_npm_params.h"
#include <arch/current/restart_fixup.h>
#include <linux/vmalloc.h>
Macros
#define TCMI_CKPTCOM_PRIVATE
Functions
static int tcmi_ckptcom_checkpoint (struct file *file, struct pt_regs *regs, int heavy, struct tcmi_npm_params *npm_params)
<<private>> Helper method that handles both PPM and NPM checkpoint creation
int tcmi_ckptcom_checkpoint_ppm (struct file *file, struct pt_regs *regs, int heavy)
<<public>> Creates a preemptive process checkpoint.
int tcmi_ckptcom_checkpoint_npm (struct file *file, struct pt_regs *regs, struct tcmi_npm_params *params)
<<public>> Creates a non-preemptive process checkpoint.
int tcmi_ckptcom_restart (struct linux_binprm *bprm, struct pt_regs *regs)
<<public>> Restarts a process from a checkpoint (new binfmt handler).
static int tcmi_core_dump (struct coredump_params *cprm)
Core dumping function.
static int __init tcmi_ckptcom_init (void)
Initializes the migration component.
static void __exit tcmi_ckptcom_exit (void)
Shutdown for the migration component.
module_init (tcmi_ckptcom_init)
module_exit (tcmi_ckptcom_exit)
EXPORT_SYMBOL_GPL (tcmi_ckptcom_checkpoint_ppm)
EXPORT_SYMBOL_GPL (tcmi_ckptcom_checkpoint_npm)
EXPORT_SYMBOL_GPL (tcmi_ckptcom_restart)
MODULE_LICENSE ("GPL")
MODULE_AUTHOR ("Jan Capek")
Variables
static struct linux_binfmt tcmi_ckptcom_format
Initialize the new checkpoint binary format.
Detailed Description
Process checkpointing component.
Date: 05/01/2005
Author: Jan Capek
Id:
tcmi_ckptcom.c,v 1.14 2008/01/17 14:36:44 stavam2 Exp
This file is part of Task Checkpointing and Migration Infrastructure(TCMI) Copyleft (C) 2005 Jan Capek
TCMI is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
TCMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file tcmi_ckptcom.c.
Macro Definition Documentation
#define TCMI_CKPTCOM_PRIVATE
Definition at line 42 of file tcmi_ckptcom.c.
Function Documentation
EXPORT_SYMBOL_GPL (tcmi_ckptcom_checkpoint_ppm)
EXPORT_SYMBOL_GPL (tcmi_ckptcom_checkpoint_npm)
EXPORT_SYMBOL_GPL (tcmi_ckptcom_restart)
MODULE_AUTHOR ("Jan Capek")
module_exit (tcmi_ckptcom_exit)
module_init (tcmi_ckptcom_init)
MODULE_LICENSE ("GPL")
static int tcmi_ckptcom_checkpoint (struct file * file, struct pt_regs * regs, int heavy, struct tcmi_npm_params * npm_params) static
<<private>> Helper method that handles both PPM and NPM checkpoint creation
This consists of:
creating a new checkpoint instance
writing a checkpoint header - might fail if the process can't be checkpointed (e.g. has open files or memory areas that are not supported)
writing open files
writing memory descriptor
writing memory areas along with pages
writing process state (registers)
writing signal handlers
Parameters
*file - file where the checkpoint is to be stored
*regs - registers of the checkpointed process
heavy - if set a full checkpoint of all process pages is made, all memory mapped files will be then restored from the checkpoint image. Setting this options yields a bigger checkpoint image size..
npm_params - Non-preemptive checkpoint params, or null if we are doing PPM checkpoint
Returns
0 upon success
Definition at line 74 of file tcmi_ckptcom.c.
References is_npm, mdbg, tcmi_ckpt_fsstruct_write(), tcmi_ckpt_mm_write(), tcmi_ckpt_new(), tcmi_ckpt_npm_params_write(), tcmi_ckpt_put(), tcmi_ckpt_regs_write(), tcmi_ckpt_sig_write(), tcmi_ckpt_tls_write(), tcmi_ckpt_write_files(), tcmi_ckpt_write_hdr(), tcmi_ckpt_write_rlimit(), and tcmi_ckpt_write_vmas().
Referenced by tcmi_ckptcom_checkpoint_npm(), and tcmi_ckptcom_checkpoint_ppm().
 {
     struct tcmi_ckpt *ckpt;
     int is_npm = npm_params != NULL;
     u64 beg_time = 0, end_time = 0 ;
     beg_time = cpu_clock(smp_processor_id());
     mdbg(INFO3, "Start checkpointing. Is_npm: %d", is_npm);
     if ( !regs ) {
         mdbg(ERR3, "Failed to create a checkpoint file. No regs provided");
         goto exit0;
     }
     ckpt = tcmi_ckpt_new(file);
     if ( IS_ERR(ckpt) ) {
         mdbg(ERR3, "Failed to create a checkpoint file. Err: %ld", PTR_ERR(ckpt));
         goto exit0;
     }
     if ( ckpt == NULL ) {
         mdbg(ERR3, "Failed to create a checkpoint file.");
         goto exit0;
     }
     if (tcmi_ckpt_write_hdr(ckpt, is_npm) < 0) {
         mdbg(ERR3, "Error writing checkpoint header!");
         goto exit1;
     }
     if (tcmi_ckpt_write_rlimit(ckpt, current) < 0) {
         mdbg(ERR3, "Error writing checkpoint rlimit!");
         goto exit1;
     }
     if (tcmi_ckpt_write_files(ckpt) < 0) {
         mdbg(ERR3, "Error writing checkpoint files!");
         goto exit1;
     }
     if (tcmi_ckpt_mm_write(ckpt) < 0) {
         mdbg(ERR3, "Error writing memory descriptor!");
         goto exit1;
     }
     if ( !is_npm ) {
         if (tcmi_ckpt_write_vmas(ckpt, heavy) < 0) {
             mdbg(ERR3, "Error writing VM areas type: %d", heavy);
             goto exit1;
         }
     }
     if (tcmi_ckpt_regs_write(ckpt, regs) < 0) {
         mdbg(ERR3, "Error writing processor registers descriptor!");
         goto exit1;
     }
     if (tcmi_ckpt_tls_write(ckpt, current) < 0) {
         mdbg(ERR3, "Error writing process tls!");
         goto exit1;
     }
     if (tcmi_ckpt_fsstruct_write(ckpt, current) < 0) {
         mdbg(ERR3, "Error writing process fs struct!");
         goto exit1;
     }
     if (tcmi_ckpt_sig_write(ckpt) < 0) {
         mdbg(ERR3, "Error writing signal data!");
         goto exit1;
     }
     if ( is_npm ) {
         if (tcmi_ckpt_npm_params_write(ckpt, npm_params) < 0) {
             mdbg(ERR3, "Error writing npm params!");
             goto exit1;
         }
     }
     end_time = cpu_clock(smp_processor_id());
     mdbg(INFO3, "Checkpoint (npm: %d) took '%llu' ms.'", is_npm, (end_time - beg_time) / 1000000);
     printk("Checkpoint (npm: %d) took '%llu' ms.\n'", is_npm, (end_time - beg_time) / 1000000);
     tcmi_ckpt_put(ckpt);
     return 0;
     /* error handling */
  exit1:
     tcmi_ckpt_put(ckpt);
  exit0:
     return -ENOEXEC;
 }
static void __exit tcmi_ckptcom_exit (void) static
Shutdown for the migration component.
This requires unregistering a new binary format with the kernel.
Definition at line 403 of file tcmi_ckptcom.c.
References tcmi_ckptcom_format.
 {
     unregister_binfmt(&tcmi_ckptcom_format);
 }
static int __init tcmi_ckptcom_init (void) static
Initializes the migration component.
This requires registering a new binary format with the kernel.
Returns
0 upon success
Definition at line 393 of file tcmi_ckptcom.c.
References tcmi_ckptcom_format.
 {
     register_binfmt(&tcmi_ckptcom_format);
   return 0;
 }
static int tcmi_core_dump (struct coredump_params * cprm) static
Core dumping function.
Currently just logs some process data.
: We should somehow keep track of the original binary format and locate corresponding dump function here and perform original binmt dump
Definition at line 381 of file tcmi_ckptcom.c.
References debug_registers().
{
     debug_registers(cprm->regs);
     return 0;
 }