Clondike: proxyfs_msg class
proxyfs_msg class
ProxyFS
This class represents connection between two peers allows sending and receiving messages.
Data Structures
struct proxyfs_msg_header
Proxyfs message header structure We allways start sending with sending this structure.
struct proxyfs_msg
Proxyfs message structure.
Macros
#define MSG_HDR_SIZE (sizeof(struct proxyfs_msg_header))
<<public>> Size od message header
#define MSG_MAGIC 0x1ee7babe
<<public>> Magic number, each message starts with it
#define MSG_MAX_SIZE (4 << 10)
<<public>> Max.
#define MSG_OPEN 1
<<public>> msg_num for message which is send when opening file
#define MSG_WRITE 3
<<public>> msg_num for write message
#define MSG_IOCTL 4
<<public>> msg_num for ioctl message
#define MSG_CLOSE 5
<<public>> msg_num for message which is send when closing file
#define MSG_FSYNC 6
<<public>> msg_num for message which is send when syncing file
#define MSG_READ_REQUEST 7
<<public>> Read request is used to notify server that the client is interested in reading from a file.
#define MSG_OPEN_RESP_OK 101
<<public>> msg_num for message which can be send as reply for MSG_OPEN
#define MSG_OPEN_RESP_FAILED 102
<<public>> msg_num for message which can be send as reply for MSG_OPEN
#define MSG_WRITE_RESP 301
<<public>> msg_num for message which can be send as reply for MSG_WRITE
#define MSG_IOCTL_RESP 401
<<public>> msg_num for message which can be send as reply for MSG_IOCTL
#define MSG_CLOSE_RESP 501
<<public>> msg_num for message which can be send as reply for MSG_CLOSE
#define MSG_FSYNC_RESP 601
<<public>> msg_num for message which can be send as reply for MSG_FSYNC
#define MSG_READ_REQUEST_RESP 701
<<public>> msg_num for message which can be send as reply for MSG_READ_REQUEST
#define WRITE_RESP_BUFFER_FULL 1
write_resp msg constants
#define WRITE_RESP_BUFFER_NOT_FULL 2
Functions
static int proxyfs_msg_get_size (struct proxyfs_msg *self)
<<public>> Returns size of message (header + data)
struct proxyfs_msg * proxyfs_msg_new (unsigned long msg_num, unsigned long file_ident, unsigned long data_size, void *data_ptr)
<<public>> Proxyfs message constructor
struct proxyfs_msg * proxyfs_msg_new_takeover_ownership (unsigned long msg_num, unsigned long file_ident, unsigned long data_size, void *data_ptr)
<<public>> Proxyfs message constructor.
struct proxyfs_msg * proxyfs_msg_compose_new (unsigned long msg_num, unsigned long file_ident,...)
<<public>> Proxyfs message constructor
void proxyfs_msg_destroy (struct proxyfs_msg *self)
<<public>> Releases a message instance
int proxyfs_msg_real_send (struct proxyfs_msg *self, struct kkc_sock *sock)
<<public>> Send message to socket
Variables
struct proxyfs_msg_header __attribute__
Detailed Description
This class represents connection between two peers allows sending and receiving messages.
Data Structure Documentation
struct proxyfs_msg_header
Proxyfs message header structure We allways start sending with sending this structure.
Definition at line 47 of file proxyfs_msg.h.
Data Fields
u_int32_t data[] Open structure...
unsigned long data_size Size of data which are send after header.
unsigned long file_ident Identifiktion of file which is the message afecting.
unsigned long magic Magic for error detection.
unsigned long msg_num Message type.
struct proxyfs_msg
Proxyfs message structure.
Definition at line 61 of file proxyfs_msg.h.
Data Fields
void * data Pointer to data which are send after header.
int free Call kfree on data after sending message.
struct proxyfs_msg_header header Message header.
struct list_head msg_queue Struct for queueing messagges.
size_t send_start How far we are in sending progress.
Macro Definition Documentation
#define MSG_CLOSE 5
<<public>> msg_num for message which is send when closing file
Definition at line 89 of file proxyfs_msg.h.
Referenced by proxyfs_proxy_file_close(), and proxyfs_server_handle_msg().
#define MSG_CLOSE_RESP 501
<<public>> msg_num for message which can be send as reply for MSG_CLOSE
Definition at line 109 of file proxyfs_msg.h.
Referenced by proxyfs_client_handle_msg(), proxyfs_proxy_file_close(), proxyfs_real_file_close(), and proxyfs_server_handle_msg().
#define MSG_FSYNC 6
<<public>> msg_num for message which is send when syncing file
Definition at line 91 of file proxyfs_msg.h.
Referenced by proxyfs_proxy_file_fsync(), and proxyfs_server_handle_msg().
#define MSG_FSYNC_RESP 601
<<public>> msg_num for message which can be send as reply for MSG_FSYNC
Definition at line 111 of file proxyfs_msg.h.
Referenced by proxyfs_client_handle_msg(), proxyfs_proxy_file_fsync(), proxyfs_real_file_fsync(), and proxyfs_server_handle_msg().
#define MSG_HDR_SIZE (sizeof(struct proxyfs_msg_header))
<<public>> Size od message header
Definition at line 76 of file proxyfs_msg.h.
Referenced by proxyfs_msg_get_size(), proxyfs_msg_new_internal(), proxyfs_msg_real_send(), proxyfs_peer_clear_msg(), proxyfs_peer_get_msg(), proxyfs_peer_real_recv(), and proxyfs_task_send_write_buf().
#define MSG_IOCTL 4
<<public>> msg_num for ioctl message
Definition at line 87 of file proxyfs_msg.h.
Referenced by proxyfs_proxy_file_ioctl_user(), and proxyfs_server_handle_msg().
#define MSG_IOCTL_RESP 401
<<public>> msg_num for message which can be send as reply for MSG_IOCTL
Definition at line 107 of file proxyfs_msg.h.
Referenced by proxyfs_client_handle_msg(), and proxyfs_server_handle_msg().
#define MSG_MAGIC 0x1ee7babe
<<public>> Magic number, each message starts with it
Definition at line 78 of file proxyfs_msg.h.
Referenced by proxyfs_msg_compose_new(), proxyfs_msg_get_size(), and proxyfs_msg_new_internal().
#define MSG_MAX_SIZE (4 << 10)
<<public>> Max.
messagge size
Definition at line 80 of file proxyfs_msg.h.
Referenced by proxyfs_msg_new_internal(), proxyfs_peer_init(), proxyfs_peer_put(), and proxyfs_task_send_write_buf().
#define MSG_OPEN 1
<<public>> msg_num for message which is send when opening file
Definition at line 83 of file proxyfs_msg.h.
Referenced by proxyfs_client_open_files(), and proxyfs_server_handle_msg().
#define MSG_OPEN_RESP_FAILED 102
<<public>> msg_num for message which can be send as reply for MSG_OPEN
Definition at line 103 of file proxyfs_msg.h.
Referenced by proxyfs_client_handle_msg(), and proxyfs_server_handle_msg().
#define MSG_OPEN_RESP_OK 101
<<public>> msg_num for message which can be send as reply for MSG_OPEN
Definition at line 101 of file proxyfs_msg.h.
Referenced by proxyfs_client_handle_msg(), proxyfs_generic_real_file_open(), proxyfs_pipe_real_file_open(), and proxyfs_tty_real_file_open().
#define MSG_READ_REQUEST 7
<<public>> Read request is used to notify server that the client is interested in reading from a file.
It is a workaround for not nice behaving programs like make, which open pipe, fork child and use correctly pipe as unidiractional, but they do not close the other end. We may then send the data to a reading end, which is not interested in this data, and the process that really wants the data from pipe won't ever get them..
Definition at line 98 of file proxyfs_msg.h.
Referenced by proxyfs_pipe_proxy_file_read_user(), and proxyfs_server_handle_msg().
#define MSG_READ_REQUEST_RESP 701
<<public>> msg_num for message which can be send as reply for MSG_READ_REQUEST
Definition at line 113 of file proxyfs_msg.h.
Referenced by proxyfs_client_handle_msg(), proxyfs_pipe_proxy_file_read_user(), proxyfs_real_file_mark_read_request(), and proxyfs_server_handle_msg().
#define MSG_WRITE 3
<<public>> msg_num for write message
Definition at line 85 of file proxyfs_msg.h.
Referenced by proxyfs_server_read_and_write_real_files(), proxyfs_task_handle_msg(), and proxyfs_task_send_write_buf().
#define MSG_WRITE_RESP 301
<<public>> msg_num for message which can be send as reply for MSG_WRITE
Definition at line 105 of file proxyfs_msg.h.
Referenced by proxyfs_proxy_file_read_user(), proxyfs_server_read_and_write_real_files(), and proxyfs_task_handle_msg().
#define WRITE_RESP_BUFFER_FULL 1
write_resp msg constants
Definition at line 116 of file proxyfs_msg.h.
#define WRITE_RESP_BUFFER_NOT_FULL 2
Definition at line 117 of file proxyfs_msg.h.
Function Documentation
struct proxyfs_msg* proxyfs_msg_compose_new (unsigned long msg_num, unsigned long file_ident, ...) read
<<public>> Proxyfs message constructor
Parameters
msg_num - Message type identifikator
file_ident - File identifikator
... - size of the first arg., pointer to the first arg., size of the second arg. pointer to the second arg. etc... ended by 0
Returns
new message or NULL on error
Definition at line 98 of file proxyfs_msg.c.
References args, proxyfs_msg::data, proxyfs_msg_header::data_size, proxyfs_msg_header::file_ident, file_ident, proxyfs_msg::free, proxyfs_msg::header, proxyfs_msg_header::magic, mdbg, MSG_MAGIC, proxyfs_msg_header::msg_num, and proxyfs_msg::send_start.
Referenced by proxyfs_proxy_file_read_user(), proxyfs_server_handle_msg(), and proxyfs_server_read_and_write_real_files().
 {
     struct proxyfs_msg *msg;
     va_list args;
     size_t msg_size, element_size;
     msg = (struct proxyfs_msg *)kmalloc( sizeof(struct proxyfs_msg), GFP_KERNEL );
     if( msg == NULL ){
         mdbg(ERR3, "Proxyfs message allocation failed");
         goto exit0;
     }
     va_start(args, file_ident);
     for(msg_size = 0; (element_size = va_arg(args, u_int32_t)) != 0; va_arg(args, void*)) {
         msg_size += element_size;
     }
     va_end(args);
     if( (msg->data = kmalloc( msg_size, GFP_KERNEL ) ) == NULL ){
         mdbg(ERR3, "Memory allocation for data (%lu bytes)  failed", (unsigned long)msg_size);
         goto exit1;
     }
     va_start(args, file_ident);
     for(msg_size = 0; (element_size = va_arg(args, u_int32_t)) != 0; msg_size += element_size ) {
         void* from_pointer = va_arg(args, void*);
         mdbg(INFO3, "Appending argument on post %lu. Arg size: %lu", (unsigned long)msg_size, (unsigned long)element_size);
         memcpy( msg->data + msg_size, from_pointer, element_size );
     }
     va_end(args);
     msg->header.magic = MSG_MAGIC;
     msg->header.msg_num = msg_num;
     msg->header.file_ident = file_ident;
     msg->header.data_size = msg_size;
     msg->free = 1;
     msg->send_start = 0;
     return msg;
 exit1:
     kfree(msg);
 exit0:
     return NULL;
 }
void proxyfs_msg_destroy (struct proxyfs_msg * self)
<<public>> Releases a message instance
Definition at line 191 of file proxyfs_msg.c.
References mdbg, and self.
Referenced by proxyfs_peer_real_send().
{
     if ( self->free ) {
         mdbg(INFO3, "Destroying message data: %p (Size: %lu)", self->data, self->header.data_size);
         kfree(self->data);
     }
     mdbg(INFO3, "Destroying message: %p", self);
     kfree(self);
 };
static int proxyfs_msg_get_size (struct proxyfs_msg * self) inline static
<<public>> Returns size of message (header + data)
Parameters
self - pointer to proxyfs_msg
Returns
message size
Definition at line 123 of file proxyfs_msg.h.
References mdbg, MSG_HDR_SIZE, MSG_MAGIC, and self.
Referenced by proxyfs_client_handle_msg(), proxyfs_msg_real_send(), proxyfs_peer_clear_msg(), proxyfs_peer_get_msg(), and proxyfs_peer_real_recv().
 {
     if( self->header.magic != MSG_MAGIC ){
         mdbg(ERR3, "Bad magic");
         return 0;
     }
     else
         return self->header.data_size + MSG_HDR_SIZE;
 }
struct proxyfs_msg* proxyfs_msg_new (unsigned long msg_num, unsigned long file_ident, unsigned long data_size, void * data_ptr) read
<<public>> Proxyfs message constructor
Parameters
msg_num - Message type identifikator
file_ident - File identifikator
data_size - size of data which will be send after header
data_ptr - pointer to data
Returns
new message or NULL on error
Definition at line 77 of file proxyfs_msg.c.
References proxyfs_msg_new_internal().
Referenced by proxyfs_client_open_files(), proxyfs_generic_real_file_open(), proxyfs_pipe_proxy_file_read_user(), proxyfs_pipe_real_file_open(), proxyfs_proxy_file_close(), proxyfs_proxy_file_fsync(), proxyfs_proxy_file_ioctl_user(), proxyfs_real_file_close(), proxyfs_real_file_fsync(), proxyfs_real_file_mark_read_request(), proxyfs_server_handle_msg(), and proxyfs_tty_real_file_open().
 {
     return proxyfs_msg_new_internal(msg_num, file_ident, data_size, data_ptr, 0);
 }
struct proxyfs_msg* proxyfs_msg_new_takeover_ownership (unsigned long msg_num, unsigned long file_ident, unsigned long data_size, void * data_ptr) read
<<public>> Proxyfs message constructor.
In this version the message takes ownership of the data
Definition at line 84 of file proxyfs_msg.c.
References proxyfs_msg_new_internal().
Referenced by proxyfs_task_send_write_buf().
{
     return proxyfs_msg_new_internal(msg_num, file_ident, data_size, data_ptr, 1);
 }
int proxyfs_msg_real_send (struct proxyfs_msg * self, struct kkc_sock * sock)
<<public>> Send message to socket
Parameters
self - pointer to proxyfs_msg instance
sock - socket used for sending
Returns
1 if the message was completely send
Definition at line 151 of file proxyfs_msg.c.
References kkc_sock_getpeername2(), KKC_SOCK_NONBLOCK, kkc_sock_send(), mdbg, MSG_HDR_SIZE, proxyfs_msg_get_size(), and self.
Referenced by proxyfs_peer_real_send().
 {
     int msg_size;
     int result;
     msg_size = proxyfs_msg_get_size( self );
     mdbg(INFO3, "Sending message %lu for file %lu size %d peer_name %s;",
         self->header.msg_num, self->header.file_ident, msg_size,
         kkc_sock_getpeername2(sock));
     if( self->send_start < MSG_HDR_SIZE ){ // Header hasn't been send yet
         result = kkc_sock_send( sock, self + self->send_start,
                 MSG_HDR_SIZE - self->send_start, KKC_SOCK_NONBLOCK);
         if( result > 0 ){
             mdbg(INFO3, "Send %d bytes", result);
             self->send_start += result;
         }
         else
             return result;
     }
     if( self->send_start >= MSG_HDR_SIZE ){ // Header has been send
         if( self->send_start == msg_size )
             return 1; // Message send
         result = kkc_sock_send( sock, self->data + self->send_start - MSG_HDR_SIZE,
                 msg_size - self->send_start, KKC_SOCK_NONBLOCK);
         if( result > 0 ){
             mdbg(INFO3, "Send %d bytes", result);
             self->send_start += result;
             if( self->send_start == msg_size )
                 return 1; // Message send
         }
         else
             return result;
     }
     return 0;
 }
Variable Documentation
struct proxyfs_msg_header __attribute__