Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/migration/tcmi_mighooks.c File Reference
tcmi_mighooks.c File Reference
#include <linux/kernel.h>
#include <linux/types.h>
#include <linux/module.h>
#include <linux/vmalloc.h>
#include <linux/resource.h>
#include <tcmi/task/tcmi_taskhelper.h>
#include <tcmi/comm/tcmi_vfork_done_procmsg.h>
#include <tcmi/manager/tcmi_ccnman.h>
#include <tcmi/manager/tcmi_penman.h>
#include <clondike/tcmi/tcmi_hooks.h>
#include "tcmi_mighooks.h"
#include "tcmi_npm_params.h"
#include <arch/current/regs.h>
#include <dbg.h>
#include <director/director.h>
#include <proxyfs/proxyfs_server.h>
#include <proxyfs/proxyfs_helper.h>
Macros
#define TCMI_MIGHOOKS_PRIVATE
Functions
int tcmi_mighooks_init (void)
<<public>> Registers all hooks with the kernel.
void tcmi_mighooks_exit (void)
<<public>> Unregisters all hooks.
static long tcmi_mighooks_do_exit (long code)
<<private>> Exit system call hook.
static long tcmi_mighooks_mig_mode (struct pt_regs *regs)
<<private>> This hook is called upon SIGUNUSED delivery to a particular process.
static void tcmi_try_npm_on_exec (const char *filename, const char __user *const __user *argv, const char __user *const __user *envp, struct pt_regs *regs, struct tcmi_man *man, int is_guest)
static long tcmi_mighooks_execve (const char *filename, const char __user *const __user *argv, const char __user *const __user *envp, struct pt_regs *regs)
static long tcmi_mighooks_replace_proc_self_file (const char *filename, const char **result)
Macro Definition Documentation
#define TCMI_MIGHOOKS_PRIVATE
Definition at line 43 of file tcmi_mighooks.c.
Function Documentation
static long tcmi_mighooks_do_exit (long code) static
<<private>> Exit system call hook.
Delegates work to the task helper that notifies current process by submitting a task_exit method and supplying the exit code. The task handles the rest on its own.
The priority notification is used, so that the exit follows immediately.
This hook is called for every process in the system, but does something only for TCMI tasks.
Parameters
code - process exit code
Returns
- status of how the notification went.
Definition at line 135 of file tcmi_mighooks.c.
References director_task_exit(), proxyfs_server_release_all(), proxyfs_sync_files_on_exit(), tcmi_task_exit(), and tcmi_taskhelper_notify_current().
Referenced by tcmi_mighooks_init().
 {
     int prio = 1, is_shadow;
     struct rusage rusage;
     mm_segment_t old_fs;
     long res;
     is_shadow = (current->tcmi.task_type == shadow || current->tcmi.task_type == shadow_detached);
     old_fs = get_fs();
     set_fs(get_ds());
     res = getrusage(current, RUSAGE_SELF, &rusage);
     set_fs(old_fs);
     director_task_exit(current->pid, code, &rusage);
     res = tcmi_taskhelper_notify_current(tcmi_task_exit, &code,
                           sizeof(code), prio);
     if ( is_shadow ) { // If the exitting task is a shadow task, we release all its proxy files as they won't be needed
         proxyfs_sync_files_on_exit(); // We have to synchronize all files first so that no new writes occur after server release
         proxyfs_server_release_all();
     }
     return res;
 }
static long tcmi_mighooks_mig_mode (struct pt_regs * regs) static
<<private>> This hook is called upon SIGUNUSED delivery to a particular process.
All work is delegated to the task helper. The context passed onto the task helper is used for updating the TCMI task. Any potential migration request thus operates on the latest process context.
Parameters
*regs - process context right before entering kernel mode.
Definition at line 171 of file tcmi_mighooks.c.
References tcmi_taskhelper_do_mig_mode().
Referenced by tcmi_mighooks_init().
 {
     tcmi_taskhelper_do_mig_mode(regs);
     return 0;
 }
static long tcmi_mighooks_replace_proc_self_file (const char * filename, const char ** result) static
Definition at line 264 of file tcmi_mighooks.c.
References mdbg.
Referenced by tcmi_mighooks_init().
{
     if ( strncmp("/proc/self",filename,10) == 0 ) {
         int len;
         char * tmp_result = __getname();
         if ( !(tmp_result) )
             return -ENOMEM;
         //len = sprintf((tmp_result), "/proc/%d%s", tcmi_task_remote_pid(current->tcmi.tcmi_task), filename+10);
         len = sprintf((tmp_result), "/mnt/local/proc/self%s", filename+10);
         mdbg(ERR3, "Replaced open filename from %s to %s (len: %d)", filename, (tmp_result), len);
         *result = tmp_result;
     }
     return 0;
 }