Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/director/netlink/npm_msg.h File Reference
npm_msg.h File Reference
#include <linux/types.h>
#include <linux/resource.h>
Enumerations
enum npm_msg_response {
DO_NOT_MIGRATE, MIGRATE, MIGRATE_BACK, REQUIRE_ARGS,
REQUIRE_ENVP, REQUIRE_ARGS_AND_ENVP
}
Functions
int npm_check (pid_t pid, uid_t uid, int is_guest, const char *name, int *decision, int *decision_value, struct rusage *rusage)
Checks, whether the process should be non-preemptively migrated to some other node.
int npm_check_full (pid_t pid, uid_t uid, int is_guest, const char *name, const char __user *const __user *args, const char __user *const __user *envp, int *decision, int *decision_value)
Checks, whether the process should be non-preemptively migrated to some other node.
Enumeration Type Documentation
enum npm_msg_response
Enumerator
DO_NOT_MIGRATE
MIGRATE
MIGRATE_BACK
REQUIRE_ARGS
REQUIRE_ENVP
REQUIRE_ARGS_AND_ENVP
Definition at line 7 of file npm_msg.h.
                       {
     DO_NOT_MIGRATE,
     MIGRATE, // In this case second return params is target migman id
     MIGRATE_BACK,
     // Following return codes indicate, that we need to provide more info to user mode director for decision
     REQUIRE_ARGS,
     REQUIRE_ENVP,
     REQUIRE_ARGS_AND_ENVP,
 };
Function Documentation
int npm_check (pid_t pid, uid_t uid, int is_guest, const char * name, int * decision, int * decision_value, struct rusage * rusage)
Checks, whether the process should be non-preemptively migrated to some other node.
Parameters
pid Pid of the process
uid Effective user ID of the process being executed
is_guest 1 if the process is guest
name File name, that is being executed
decision Output parameter.. element of "npm_msg_response" enum
decision_value Output param .. if result is to perform migration, this will contain slot of the migration manager to be used
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 94 of file npm_msg.c.
References npm_check_params::args, npm_check_params::decision, npm_check_params::decision_value, DIRECTOR_CHECK_NPM, npm_check_params::envp, npm_check_params::is_guest, msg_transaction_do(), npm_check_params::name, npm_check_params::name_length, npm_check_params::pid, pid, npm_check_params::rusage, and npm_check_params::uid.
Referenced by director_npm_check().
{
     struct npm_check_params params;
     int ret;
     params.pid = pid;
     params.uid = uid;
     params.is_guest = is_guest;
     params.name = name;
     params.name_length = strlen(name);
     params.args = NULL;
     params.envp = NULL;
     params.rusage = rusage;
     ret = msg_transaction_do(DIRECTOR_CHECK_NPM, &npm_check_msg_ops, &params, 0);
     if ( ret )
         return ret;
     *decision = params.decision;
     *decision_value = params.decision_value;
     return 0;
 }
int npm_check_full (pid_t pid, uid_t uid, int is_guest, const char * name, const char __user *const __user * args, const char __user *const __user * envp, int * decision, int * decision_value)
Checks, whether the process should be non-preemptively migrated to some other node.
This version in addition passes args & envp
Parameters
pid Pid of the process
uid Effective user ID of the process being executed
is_guest 1 if the process is guest
name File name, that is being executed
args Args, or NULL if no args are provided
envp Envinromental properties, or NULL if no envs are provided
decision Output parameter.. element of "npm_msg_response" enum
decision_value Output param .. if result is to perform migration, this will contain slot of the migration manager to be used
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 198 of file npm_msg.c.
References npm_check_params::args, args, npm_check_params::decision, npm_check_params::decision_value, DIRECTOR_CHECK_FULL_NPM, npm_check_params::envp, envp, npm_check_params::is_guest, msg_transaction_do(), npm_check_params::name, npm_check_params::name_length, npm_check_params::pid, pid, npm_check_params::rusage, and npm_check_params::uid.
Referenced by director_npm_check().
{
     struct npm_check_params params;
     int ret;
     params.pid = pid;
     params.uid = uid;
     params.is_guest = is_guest;
     params.name = name;
     params.name_length = strlen(name);
     params.args = args;
     params.envp = envp;
     params.rusage = NULL;
     ret = msg_transaction_do(DIRECTOR_CHECK_FULL_NPM, &npm_check_full_msg_ops, &params, 0);
     if ( ret )
         return ret;
     *decision = params.decision;
     *decision_value = params.decision_value;
     return 0;
 }