Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/lib/util.h File Reference
util.h File Reference
#include <linux/pid_namespace.h>
#include <linux/namei.h>
Functions
static struct task_struct * task_find_by_pid (pid_t pid)
static int mk_dir (const char *path, int mode)
Creates a new directory.
Function Documentation
static int mk_dir (const char * path, int mode) inline static
Creates a new directory.
Assumes, its parent directory already exists!!
Definition at line 14 of file util.h.
Referenced by global_9p_mount(), and mount_local_procfs().
{
     struct nameidata nd;
     struct dentry *dentry;
     int err;
     err = path_lookup(path, LOOKUP_PARENT ,&nd);
     if ( err ) {
         return err;
     }
     dentry = lookup_create(&nd, 1);
         err = PTR_ERR(dentry);
         if (IS_ERR(dentry))
                 return err;
     err = vfs_mkdir(nd.path.dentry->d_inode, dentry, mode);
     return err;
 }
static struct task_struct* task_find_by_pid (pid_t pid) static read
Definition at line 7 of file util.h.
Referenced by tcmi_penmigman_send_signal(), tcmi_task_to_task_struct(), tcmi_taskhelper_attach(), tcmi_taskhelper_detach_by_pid(), tcmi_taskhelper_find_by_pid(), and tcmi_taskhelper_wait_for_pick_up_timeout().
{
     return pid_task(find_pid_ns(pid, current->nsproxy->pid_ns), PIDTYPE_PID);
 }