Clondike: tcmi_rpc_procmsg class
tcmi_rpc_procmsg class
tcmi_procmsg class
Data Structures
struct tcmi_rpc_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Macros
#define TCMI_RPC_PROCMSG_DSC TCMI_MSG_DSC(TCMI_RPC_PROCMSG_ID, tcmi_rpc_procmsg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
#define TCMI_RPC_PROCMSGTIMEOUT 10*60*HZ
RPC message transaction timeout set to 10 minutes.
#define TCMI_RPC_PROCMSG(m) ((struct tcmi_rpc_procmsg*)m)
Casts to the tcmi_rpc_procmsg instance.
Functions
static int tcmi_rpc_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the RPC message via a specified connection.
static int tcmi_rpc_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Sends the RPC message via a specified connection.
static void tcmi_rpc_procmsg_free (struct tcmi_procmsg *self)
<<private>> Frees RPC message resources
struct tcmi_rpc_procmsg __attribute__ ((__packed__))
struct tcmi_msg * tcmi_rpc_procmsg_new_rx (u_int32_t msg_id)
<<public>> RPC process message constructor for receiving.
struct tcmi_msg * tcmi_rpc_procmsg_new_tx (struct tcmi_slotvec *transactions, pid_t dst_pid)
<<public>> RPC process message constructor for sending.
static void * tcmi_rpc_procmsg_data_base (struct tcmi_rpc_procmsg *self, unsigned int index)
<<public>> Return RPC parameter.
static unsigned long tcmi_rpc_procmsg_data_size (struct tcmi_rpc_procmsg *self, unsigned int index)
<<public>> Return RPC parameter size.
static int tcmi_rpc_procmsg_num (struct tcmi_rpc_procmsg *self)
<<public>> Return RPC number.
Variables
static struct tcmi_procmsg_ops rpc_procmsg_ops
Message operations that support polymorphism.
Detailed Description
This class represents RPC process control message and is intended to be used for system call forwarding .
Data Structure Documentation
struct tcmi_rpc_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Definition at line 49 of file tcmi_rpc_procmsg.h.
Data Fields
void ** elem_base Array of pointers to elements.
u_int32_t * elem_size Array with size of elements.
bool free_data Free data on put.
u_int16_t nmemb Number of memory elements.
u_int16_t rpcnum RPC number.
struct tcmi_procmsg super parent class instance
Macro Definition Documentation
#define TCMI_RPC_PROCMSG (m) ((struct tcmi_rpc_procmsg*)m)
Casts to the tcmi_rpc_procmsg instance.
Definition at line 100 of file tcmi_rpc_procmsg.h.
Referenced by tcmi_rpc_procmsg_free(), tcmi_rpc_procmsg_new_rx(), tcmi_rpc_procmsg_new_tx(), tcmi_rpc_procmsg_recv(), tcmi_rpc_procmsg_send(), tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_get_response(), tcmi_shadow_rpc_do_fork(), tcmi_shadow_rpc_getgroups(), tcmi_shadow_rpc_rt_sigqueueinfo(), tcmi_shadow_rpc_setgroups(), tcmi_shadow_rpc_sys_wait4(), and tcmi_shadowtask_process_msg().
#define TCMI_RPC_PROCMSG_DSC TCMI_MSG_DSC(TCMI_RPC_PROCMSG_ID, tcmi_rpc_procmsg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
Definition at line 95 of file tcmi_rpc_procmsg.h.
#define TCMI_RPC_PROCMSGTIMEOUT 10*60*HZ
RPC message transaction timeout set to 10 minutes.
Definition at line 97 of file tcmi_rpc_procmsg.h.
Referenced by tcmi_rpc_procmsg_new_tx().
Function Documentation
struct tcmi_rpc_procmsg __attribute__ ((__packed__))
static void* tcmi_rpc_procmsg_data_base (struct tcmi_rpc_procmsg * self, unsigned int index) inline static
<<public>> Return RPC parameter.
Definition at line 73 of file tcmi_rpc_procmsg.h.
Referenced by tcmi_shadow_rpc_do_fork(), tcmi_shadow_rpc_getgroups(), tcmi_shadow_rpc_rt_sigqueueinfo(), tcmi_shadow_rpc_setgroups(), and tcmi_shadow_rpc_sys_wait4().
{
     if(index < self->nmemb)
         return self->elem_base[index];
     mdbg(ERR3, "Trying to acces beyond array boundary");
     return NULL;
 }
static unsigned long tcmi_rpc_procmsg_data_size (struct tcmi_rpc_procmsg * self, unsigned int index) inline static
<<public>> Return RPC parameter size.
Definition at line 81 of file tcmi_rpc_procmsg.h.
References mdbg, and nmemb.
{
     if(index < self->nmemb)
         return self->elem_size[index];
     mdbg(ERR3, "Trying to acces beyond array boundary");
     return 0;
 }
static void tcmi_rpc_procmsg_free (struct tcmi_procmsg * self) static
<<private>> Frees RPC message resources
Parameters
*self - this message instance
Definition at line 233 of file tcmi_rpc_procmsg.c.
References tcmi_rpc_procmsg::elem_base, tcmi_rpc_procmsg::elem_size, tcmi_rpc_procmsg::free_data, tcmi_rpc_procmsg::nmemb, and TCMI_RPC_PROCMSG.
 {
     struct tcmi_rpc_procmsg *self_msg = TCMI_RPC_PROCMSG(self);
     if ( !self_msg )
         return;
     if( self_msg->nmemb > 0 ){
         if( self_msg->free_data == 1 ) kfree( self_msg->elem_base[0] ); /* frees all data */
         kfree( self_msg->elem_size );    /* elem_base and elem_size are allocated in one time */
     }
 }
struct tcmi_msg* tcmi_rpc_procmsg_new_rx (u_int32_t msg_id) read
<<public>> RPC process message constructor for receiving.
<<public>> RPC process message constructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this RPC message instance.
Returns
a new RPC message or NULL.
Definition at line 50 of file tcmi_rpc_procmsg.c.
References tcmi_rpc_procmsg::free_data, mdbg, rpc_procmsg_ops, TCMI_MSG, TCMI_PROCMSG, tcmi_procmsg_init_rx(), TCMI_RPC_PROCMSG, and TCMI_RPC_PROCMSG_ID.
 {
     struct tcmi_rpc_procmsg *msg;
     mdbg(INFO3, "in tcmi_rpc_procmsg_new_rx()");
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_RPC_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_RPC_PROCMSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_RPC_PROCMSG(kmalloc(sizeof(struct tcmi_rpc_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate RPC message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_RPC_PROCMSG_ID, &rpc_procmsg_ops)) {
         mdbg(ERR3, "Error initializing RPC message %x", msg_id);
         goto exit1;
     }
     msg->free_data = 1;
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_rpc_procmsg_new_tx (struct tcmi_slotvec * transactions, pid_t dst_pid) read
<<public>> RPC process message constructor for sending.
<<public>> RPC process message constructor for sending.
When performing the generic proc tx init, the response message ID is specified (TCMI_RESPRPC_PROCMSG_ID) so that it will be associated with the transaction. Also, the generic tx initializer is supplied with the destination process ID.
Parameters
*transactions - storage for the new transaction(NULL for one-way messages)
dst_pid - destination process PID
Returns
a new error ready for the transfer or NULL.
Definition at line 93 of file tcmi_rpc_procmsg.c.
References tcmi_rpc_procmsg::free_data, mdbg, rpc_procmsg_ops, TCMI_MSG, TCMI_PROCMSG, tcmi_procmsg_init_tx(), TCMI_RPC_PROCMSG, TCMI_RPC_PROCMSG_ID, TCMI_RPC_PROCMSGTIMEOUT, TCMI_RPCRESP_PROCMSG_ID, and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_rpcresp_procmsg_get_response().
 {
     struct tcmi_rpc_procmsg *msg;
     if (!(msg = TCMI_RPC_PROCMSG(kmalloc(sizeof(struct tcmi_rpc_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate RPC message");
         goto exit0;
     }
     msg->free_data = 0;
     /* Initialize the message for transfer */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_RPC_PROCMSG_ID, &rpc_procmsg_ops,
                  dst_pid, 0,
                  transactions, TCMI_RPCRESP_PROCMSG_ID,
                  TCMI_RPC_PROCMSGTIMEOUT, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing RPC message");
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_rpc_procmsg_num (struct tcmi_rpc_procmsg * self) inline static
<<public>> Return RPC number.
Definition at line 89 of file tcmi_rpc_procmsg.h.
Referenced by tcmi_rpcresp_procmsg_create(), and tcmi_shadowtask_process_msg().
{
     return self->rpcnum;
 }
static int tcmi_rpc_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the RPC message via a specified connection.
Receiving the erro message requires reading the error code from the specified connection
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 135 of file tcmi_rpc_procmsg.c.
References tcmi_rpc_procmsg::elem_base, tcmi_rpc_procmsg::elem_size, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_rpc_procmsg::nmemb, tcmi_rpc_procmsg::rpcnum, SIZE_OF_ELEM_BASE, SIZE_OF_ELEM_SIZE, and TCMI_RPC_PROCMSG.
 {
     int err, data_size, total, i;
     struct tcmi_rpc_procmsg *self_msg = TCMI_RPC_PROCMSG(self);
     err = kkc_sock_recv(sock, &self_msg->rpcnum,
                 sizeof(self_msg->rpcnum) + sizeof(self_msg->nmemb), KKC_SOCK_BLOCK) ;
     if( err < 0 ) {
         mdbg(ERR3, "Cannot read rpc message header");
         return err;
     }
     total = err;
     if( self_msg->nmemb > 0 ){
         /* Allocate memory for array of elements size and array of pointers to elements */
         self_msg->elem_size = kmalloc(SIZE_OF_ELEM_SIZE + SIZE_OF_ELEM_BASE, GFP_KERNEL);
         self_msg->elem_base = (void*)self_msg->elem_size + SIZE_OF_ELEM_SIZE;
         self_msg->elem_base[0] = NULL;
         err = kkc_sock_recv(sock, self_msg->elem_size, SIZE_OF_ELEM_SIZE, KKC_SOCK_BLOCK);
         if( err < 0 ) {
             mdbg(ERR3, "Cannot read elem size of RPC#%d", self_msg->rpcnum);
             return err;
         }
         total += err;
         /* Allocate memory for data */
         for(data_size = 0, i = 0; i < self_msg->nmemb; data_size += self_msg->elem_size[i++]);
         self_msg->elem_base[0] = kmalloc( data_size, GFP_KERNEL );
         err = kkc_sock_recv(sock, self_msg->elem_base[0], data_size, KKC_SOCK_BLOCK);
         if( err < 0 ) {
             mdbg(ERR3, "Cannot read elements of RPC#%d (data_size %d)", self_msg->rpcnum, data_size);
             return err;
         }
         total += err;
         for( i = 1; i < self_msg->nmemb; i++ )
             self_msg->elem_base[i] = self_msg->elem_base[i-1] + self_msg->elem_size[i-1];
     }
     mdbg(INFO3, "Received: RPC#%d message (%d Bytes, %d params)", self_msg->rpcnum, total, self_msg->nmemb);
     return 0;
 }
static int tcmi_rpc_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Sends the RPC message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 190 of file tcmi_rpc_procmsg.c.
References tcmi_rpc_procmsg::elem_base, tcmi_rpc_procmsg::elem_size, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_rpc_procmsg::nmemb, tcmi_rpc_procmsg::rpcnum, SIZE_OF_ELEM_SIZE, and TCMI_RPC_PROCMSG.
 {
     int err, total, i;
     struct tcmi_rpc_procmsg *self_msg = TCMI_RPC_PROCMSG(self);
     err = kkc_sock_send(sock, &self_msg->rpcnum,
                 sizeof(self_msg->rpcnum) + sizeof(self_msg->nmemb), KKC_SOCK_BLOCK) ;
     if( err < 0 ) {
         mdbg(ERR3, "Error sending RPC#%d message. Error code: %d", self_msg->rpcnum, err);
         return err;
     }
     total = err;
     if( self_msg->nmemb > 0 ){
         err = kkc_sock_send(sock, self_msg->elem_size, SIZE_OF_ELEM_SIZE, KKC_SOCK_BLOCK);
         if( err < 0 ) {
             mdbg(ERR3, "Error sending RPC#%d message elem size. Error code: %d", self_msg->rpcnum, err);
             return err;
         }
         total += err;
         for( i = 0; i < self_msg->nmemb; i++ ){
             err = kkc_sock_send(sock, self_msg->elem_base[i],
                     self_msg->elem_size[i], KKC_SOCK_BLOCK);
             if( err < 0 ) {
                 mdbg(ERR3, "Error sending RPC#%d message elem[%d]. Error code: %d", self_msg->rpcnum, i, err);
                 return err;
             }
             total += err;
         }
     }
     mdbg(INFO3, "Sent: RPC#%d message (%d Bytes)", self_msg->rpcnum, total);
     return 0;
 }
Variable Documentation
struct tcmi_procmsg_ops rpc_procmsg_ops static
Initial value:
= {
    .recv = tcmi_rpc_procmsg_recv,
    .send = tcmi_rpc_procmsg_send,
    .free = tcmi_rpc_procmsg_free
}
Message operations that support polymorphism.
Definition at line 247 of file tcmi_rpc_procmsg.c.
Referenced by tcmi_rpc_procmsg_new_rx(), and tcmi_rpc_procmsg_new_tx().