Clondike: tcmi_ccnmigman class
tcmi_ccnmigman class
tcmi_migman class
TCMI CCN migration manager controls migrating tasks for a particular CCN-PEN pair and resides as the name describes - on a CCN.
Data Structures
struct tcmi_ccnmigman
A compound structure that holds all current shadow processes and other migration related data.
Macros
#define TCMI_CCNMIGMAN(migman) ((struct tcmi_ccnmigman *)migman)
Casts to the CCN migration manager.
Functions
static int tcmi_ccnmigman_init_ctlfs_files (struct tcmi_migman *self)
<<private>> Creates the static files described here .
static void tcmi_ccnmigman_stop_ctlfs_files (struct tcmi_migman *self)
<<private>> Unregisters and releases all control files.
static void tcmi_ccnmigman_stop (struct tcmi_migman *self, int remote_requested)
<<private>> Called on stop request
static int tcmi_ccnmigman_load (void *obj, void *data)
<<private>> Read method for the TCMI ctlfs - reports current PEN load.
static void tcmi_ccnmigman_free (struct tcmi_migman *self)
<<private>> Called upon migman destruction.
static void tcmi_ccnmigman_process_msg (struct tcmi_migman *self, struct tcmi_msg *m)
<<private>> Processes a TCMI message m.
struct tcmi_migman * tcmi_ccnmigman_new (struct kkc_sock *sock, u_int32_t ccn_id, struct tcmi_slot *manager_slot, struct tcmi_ctlfs_entry *root, struct tcmi_ctlfs_entry *migproc, const char namefmt[],...)
<<public>> TCMI CCN migration manager constructor.
int tcmi_ccnmigman_auth_pen (struct tcmi_ccnmigman *self)
<<public>> Tries authenticating a PEN.
Variables
static struct tcmi_migman_ops ccnmigman_ops
Migration manager operations that support polymorphism.
Detailed Description
TCMI CCN migration manager controls migrating tasks for a particular CCN-PEN pair and resides as the name describes - on a CCN.
Basic message handling capabilities are used from the generic migration manager .
There are specific tasks that needs to be accomplished:
authenticate a connecting PEN
It provides an additional entry in the TCMI ctlfs. This file reports an average load of a PEN that is connected to this migration manager.
Data Structure Documentation
struct tcmi_ccnmigman
A compound structure that holds all current shadow processes and other migration related data.
Definition at line 61 of file tcmi_ccnmigman.h.
Data Fields
struct tcmi_ctlfs_entry * f_load TCMI ctlfs - reports current load of the remote PEN.
struct tcmi_migman super parent class instance.
wait_queue_head_t wq General purpose wait queue, e.g.
used when syncing the context performing authentication with authentication processing method
Macro Definition Documentation
#define TCMI_CCNMIGMAN (migman) ((struct tcmi_ccnmigman *)migman)
Casts to the CCN migration manager.
Definition at line 74 of file tcmi_ccnmigman.h.
Referenced by tcmi_ccnman_process_sock(), tcmi_ccnmigman_init_ctlfs_files(), tcmi_ccnmigman_new(), tcmi_ccnmigman_process_msg(), and tcmi_ccnmigman_stop_ctlfs_files().
Function Documentation
int tcmi_ccnmigman_auth_pen (struct tcmi_ccnmigman * self)
<<public>> Tries authenticating a PEN.
<<public>> Tries authenticating a PEN.
Authentication is considered successful if after processing the message the new manager state is 'CONNECTED'. The check is fully left upto the message processing framework. All that needs to be done is wait for a given time if the state changes. Of course, the connection message processing wakes us up earlier when needed.
Parameters
*self - pointer to this migration manager instance
Returns
0 if successfully, -EINVAL otherwise
Definition at line 111 of file tcmi_ccnmigman.c.
References mdbg, self, TCMI_MIGMAN, TCMI_MIGMAN_CONNECTED, and tcmi_migman_state().
Referenced by tcmi_ccnman_process_sock().
 {
     int ret;
     mdbg(INFO3, "Waiting for connection authentication.. %p", self);
     ret = wait_event_interruptible_timeout(self->wq,
                            (tcmi_migman_state(TCMI_MIGMAN(self)) ==
                         TCMI_MIGMAN_CONNECTED), 5*HZ);
     mdbg(INFO3, "woke up after %d, checking authentication result", ret);
     return (tcmi_migman_state(TCMI_MIGMAN(self)) == TCMI_MIGMAN_CONNECTED ?
         0 : -EINVAL);
 }
static void tcmi_ccnmigman_free (struct tcmi_migman * self) static
<<private>> Called upon migman destruction.
Parameters
*self - pointer to this migration manager instance
Definition at line 200 of file tcmi_ccnmigman.c.
 {
     /* struct tcmi_ccnmigman *self_ccn  = TCMI_CCNMIGMAN(self); */
     /* nothing to do */
 }
static int tcmi_ccnmigman_init_ctlfs_files (struct tcmi_migman * self) static
<<private>> Creates the static files described here .
Parameters
*self - pointer to this migration manager instance
Returns
0 upon success
Definition at line 137 of file tcmi_ccnmigman.c.
References tcmi_ccnmigman::f_load, mdbg, TCMI_CCNMIGMAN, tcmi_ccnmigman_load(), tcmi_ctlfs_intfile_new(), tcmi_migman_root(), and TCMI_PERMS_FILE_R.
 {
     struct tcmi_ccnmigman *self_ccn = TCMI_CCNMIGMAN(self);
     mdbg(INFO4, "Creating files");
     if (!(self_ccn->f_load =
           tcmi_ctlfs_intfile_new(tcmi_migman_root(self), TCMI_PERMS_FILE_R,
                      self, NULL, tcmi_ccnmigman_load,
                      sizeof(int), "load")))
         goto exit0;
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ccnmigman_load (void * obj, void * data) static
<<private>> Read method for the TCMI ctlfs - reports current PEN load.
Load is reported based on the last sent info from PEN
Parameters
*obj - this CCN manager instance
*data - pointer to this migration manager instance
Returns
0 upon success
Definition at line 188 of file tcmi_ccnmigman.c.
Referenced by tcmi_ccnmigman_init_ctlfs_files().
 {
     return 0;
 }
struct tcmi_migman* tcmi_ccnmigman_new (struct kkc_sock * sock, u_int32_t ccn_id, struct tcmi_slot * manager_slot, struct tcmi_ctlfs_entry * root, struct tcmi_ctlfs_entry * migproc, const char namefmt[], ...) read
<<public>> TCMI CCN migration manager constructor.
<<public>> TCMI CCN migration manager constructor.
The initialization is accomplished exactly in this order:
create new instance
allocate new slot vector for shadow processes.
delegates all remaining intialization work to the generic manager.
authenticate the connecting PEN
Parameters
*sock - socket where the new PEN is registering
ccn_id - CCN identifier
*root - directory where the migration manager should create its files and directories
*migproc - directory where the migrated process will have their info
namefmt - nameformat string for the main manager directory name (printf style)
... - variable arguments
Returns
new TCMI CCN manager instance or NULL
Definition at line 66 of file tcmi_ccnmigman.c.
References args, ccnmigman_ops, mdbg, minfo, TCMI_CCNMIGMAN, TCMI_MIGMAN, tcmi_migman_init(), UNKNOWN, and tcmi_ccnmigman::wq.
Referenced by tcmi_ccnman_process_sock().
 {
     struct tcmi_ccnmigman *migman;
     va_list args;
     minfo(INFO2, "Creating new TCMI CCN migration manager");
     if (!(migman = TCMI_CCNMIGMAN(kmalloc(sizeof(struct tcmi_ccnmigman),
                           GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for CCM migration manager");
         goto exit0;
     }
     init_waitqueue_head(&migman->wq);
     va_start(args, namefmt);
     if (tcmi_migman_init(TCMI_MIGMAN(migman), sock, ccn_id, 0, UNKNOWN, manager_slot, root, migproc,
                  &ccnmigman_ops, namefmt, args) < 0) {
         mdbg(ERR3, "TCMI CCN migman initialization failed!");
         va_end(args);
         goto exit1;
     }
     va_end(args);
     return TCMI_MIGMAN(migman);
     /* error handling */
  exit1:
     kfree(migman);
  exit0:
     return NULL;
 }
static void tcmi_ccnmigman_process_msg (struct tcmi_migman * self, struct tcmi_msg * m) static
<<private>> Processes a TCMI message m.
The message is desposed afterwords.
Parameters
*self - pointer to this migration manager instance
*m - pointer to a message to be processed
Definition at line 214 of file tcmi_ccnmigman.c.
References director_generic_user_message_recv(), director_node_connected(), kkc_sock_getpeername2(), mdbg, minfo, resp, self, TCMI_AUTHENTICATE_MSG, tcmi_authenticate_msg_arch(), tcmi_authenticate_msg_auth_data(), tcmi_authenticate_msg_auth_data_size(), TCMI_AUTHENTICATE_MSG_ID, tcmi_authenticate_msg_pen_id(), tcmi_authenticate_resp_msg_new_tx(), tcmi_ccnman_get_mount_params(), TCMI_CCNMIGMAN, TCMI_GENERIC_USER_MSG, TCMI_GENERIC_USER_MSG_ID, tcmi_generic_user_msg_node_id(), tcmi_generic_user_msg_user_data(), tcmi_generic_user_msg_user_data_size(), TCMI_MIGMAN_CONNECTED, tcmi_migman_set_state(), tcmi_migman_slot_index(), tcmi_migman_sock(), tcmi_msg_id(), tcmi_msg_put(), tcmi_msg_req_id(), and tcmi_msg_send_anonymous().
 {
     struct tcmi_msg *resp;
     int result_code = 0;
     int accepted;
     struct tcmi_authenticate_msg *auth_msg;
     struct tcmi_generic_user_msg *user_msg;
     /* struct tcmi_ccnmigman *self_ccn = TCMI_CCNMIGMAN(self); */
     int err;
     mdbg(INFO4, "Processing message ID");
     switch(tcmi_msg_id(m)) {
     case TCMI_AUTHENTICATE_MSG_ID:
         auth_msg = TCMI_AUTHENTICATE_MSG(m);
         minfo(INFO1, "Authentication message arrived.");
         // Inform director that the node was connected
         err = director_node_connected(kkc_sock_getpeername2(tcmi_migman_sock(self)), tcmi_migman_slot_index(self), tcmi_authenticate_msg_auth_data_size(auth_msg), tcmi_authenticate_msg_auth_data(auth_msg), &accepted);
         // The check for accept is performed only if the director responded, otherwise the call is ignored
         if ( !err && !accepted ) {
             minfo(ERR1, "Director rejected peer connection");
             break;
         }
         self->pen_id = tcmi_authenticate_msg_pen_id(auth_msg);
         self->peer_arch_type = tcmi_authenticate_msg_arch(auth_msg);
         if ( !( resp = tcmi_authenticate_resp_msg_new_tx(tcmi_msg_req_id(m), self->ccn_id, ARCH_CURRENT, result_code, tcmi_ccnman_get_mount_params()) ) ) {
             mdbg(ERR3, "Error creating response message");
             break;
         }
         if ((err = tcmi_msg_send_anonymous(resp, tcmi_migman_sock(self)))) {
             mdbg(ERR3, "Error sending response message %d", err);
         }
         tcmi_msg_put(resp);
         tcmi_migman_set_state(self, TCMI_MIGMAN_CONNECTED);
         wake_up(&(TCMI_CCNMIGMAN(self)->wq));
         break;
     case TCMI_GENERIC_USER_MSG_ID:
         user_msg = TCMI_GENERIC_USER_MSG(m);
         minfo(INFO1, "User message arrived.");
         err = director_generic_user_message_recv(tcmi_generic_user_msg_node_id(user_msg), 1, tcmi_migman_slot_index(self), tcmi_generic_user_msg_user_data_size(user_msg), tcmi_generic_user_msg_user_data(user_msg));
         if ( err ) {
             mdbg(ERR3, "Error in processing user message %d", err);
         }
         break;
     default:
         minfo(INFO1, "Unexpected message ID %x, no handler available.",
               tcmi_msg_id(m));
         break;
     }
     /* release the message */
     tcmi_msg_put(m);
 }
static void tcmi_ccnmigman_stop (struct tcmi_migman * self, int remote_requested) static
<<private>> Called on stop request
Parameters
*self - pointer to this migration manager instance
Definition at line 174 of file tcmi_ccnmigman.c.
References director_node_disconnected(), and tcmi_migman_slot_index().
{
     director_node_disconnected(tcmi_migman_slot_index(self), 1, remote_requested);
 }
static void tcmi_ccnmigman_stop_ctlfs_files (struct tcmi_migman * self) static
<<private>> Unregisters and releases all control files.
Parameters
*self - pointer to this migration manager instance
Definition at line 161 of file tcmi_ccnmigman.c.
References tcmi_ccnmigman::f_load, mdbg, TCMI_CCNMIGMAN, tcmi_ctlfs_entry_put(), and tcmi_ctlfs_file_unregister().
 {
     struct tcmi_ccnmigman *self_ccn = TCMI_CCNMIGMAN(self);
     mdbg(INFO3, "Destroying  TCMI ctlfs files - CCN migman");
     tcmi_ctlfs_file_unregister(self_ccn->f_load);
     tcmi_ctlfs_entry_put(self_ccn->f_load);
 }
Variable Documentation
struct tcmi_migman_ops ccnmigman_ops static
Initial value:
= {
    .init_ctlfs_files = tcmi_ccnmigman_init_ctlfs_files,
    .stop_ctlfs_files = tcmi_ccnmigman_stop_ctlfs_files,
    .stop = tcmi_ccnmigman_stop,
    .free = tcmi_ccnmigman_free,
    .process_msg = tcmi_ccnmigman_process_msg,
}
Migration manager operations that support polymorphism.
Definition at line 277 of file tcmi_ccnmigman.c.
Referenced by tcmi_ccnmigman_new().