Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/ccfs/filter.c File Reference
filter.c File Reference
#include <linux/spinlock.h>
#include <linux/list.h>
#include <linux/kernel.h>
#include <linux/err.h>
#include <linux/fs.h>
#include <linux/file.h>
#include <asm/page.h>
#include <linux/sched.h>
#include <linux/kthread.h>
#include <linux/wait.h>
#include <linux/pagemap.h>
#include <linux/pagevec.h>
#include <dbg.h>
#include "filter.h"
Data Structures
struct filter_pattern
Functions
struct filter * create_filter (void)
void destroy_filter (struct filter *filter)
void parse_filter (struct filter *filter, char *definition)
Parses filter definition.
int add_filter_pattern (struct filter *filter, const char *pattern, int pattern_length)
Registers a new patter to the filter.
static int pattern_matches (struct filter_pattern *filter_pattern, const char *name, int name_length, struct timespec *ctime, umode_t umode)
int filter_matches (struct filter *filter, const char *name, int name_length, struct timespec *ctime, umode_t umode)
Returns 1, if name matches any of the filter patterns.
Data Structure Documentation
struct filter_pattern
Definition at line 18 of file filter.c.
Data Fields
struct list_head head For enlistment.
struct timespec older_than Files creation data has to be older than this time.
char * pattern Pattern itself.
int pattern_length
Function Documentation
int add_filter_pattern (struct filter * filter, const char * pattern, int pattern_length)
Registers a new patter to the filter.
Returns 0 upon succes, error code otherwise
Definition at line 64 of file filter.c.
References filter_pattern::head, filter_pattern::older_than, filter_pattern::pattern, filter_pattern::pattern_length, and filter::patterns.
Referenced by parse_filter().
{
     struct filter_pattern* filter_pattern = kmalloc(sizeof(struct filter_pattern), GFP_KERNEL);
     printk("Adding filter pattern: %s (%d)\n", pattern, pattern_length);
     if ( !filter_pattern )
         return -ENOMEM;
     if ( strcmp(pattern, "OLD") == 0 ) {
       filter_pattern->pattern = NULL;
       filter_pattern->older_than = CURRENT_TIME;
       // Consider also files created in last hour to be new files.. as we may assume they may change again soon (not realy smart but should be good enough for our purposes)
       filter_pattern->older_than.tv_sec = filter_pattern->older_than.tv_sec - 3600;
     } else {
       filter_pattern->pattern = kmalloc(pattern_length, GFP_KERNEL);
       if ( !filter_pattern->pattern ) {
           kfree(filter_pattern);
           return -ENOMEM;
       }
       memcpy(filter_pattern->pattern, pattern, pattern_length);
       filter_pattern->pattern_length = pattern_length;
     }
     list_add(&filter_pattern->head, &filter->patterns);
     return 0;
 }
struct filter* create_filter (void) read
Definition at line 28 of file filter.c.
References filter::patterns.
Referenced by ccfs_parse_options().
{
     struct filter* filter = kmalloc(sizeof(struct filter), GFP_KERNEL);
     if ( !filter )
         return NULL;
     INIT_LIST_HEAD(&filter->patterns);
     return filter;
 }
void destroy_filter (struct filter * filter)
Definition at line 38 of file filter.c.
References filter_pattern::head, and filter::patterns.
Referenced by ccfs_put_super().
{
     struct filter_pattern *head, *tmp;
     if ( !filter )
         return;
         list_for_each_entry_safe(head, tmp, &filter->patterns, head) {
                 list_del(&head->head);
         kfree(head);
     }
     kfree(filter);
 }
int filter_matches (struct filter * filter, const char * name, int name_length, struct timespec * ctime, umode_t umode)
Returns 1, if name matches any of the filter patterns.
0 otherwise
Definition at line 122 of file filter.c.
References filter_pattern::head, pattern_matches(), and filter::patterns.
Referenced by ccfs_interpose().
{
     struct filter_pattern *head;
     if ( !filter )
         return 1;
         list_for_each_entry(head, &filter->patterns, head) {
          if ( pattern_matches(head, name, name_length, ctime, umode) )
             return 1;
     }
     return 0;
 }
void parse_filter (struct filter * filter, char * definition)
Parses filter definition.
Expects colon separated patterns
Definition at line 52 of file filter.c.
References add_filter_pattern().
Referenced by ccfs_parse_options().
{
     char* p;
     while ((p = strsep(&definition, ":")) != NULL) {
         if (!*p)
             continue;
         add_filter_pattern(filter, p, strcspn(p, ":"));
     }
 }
static int pattern_matches (struct filter_pattern * filter_pattern, const char * name, int name_length, struct timespec * ctime, umode_t umode) static
Definition at line 92 of file filter.c.
References mdbg, filter_pattern::older_than, filter_pattern::pattern, and filter_pattern::pattern_length.
Referenced by filter_matches().
{
     int name_index = name_length - 1;
     int pattern_index = filter_pattern->pattern_length - 1;
     const char* pattern = filter_pattern->pattern;
     if ( filter_pattern->pattern == NULL ) {
       /* Match time pattern. Do not check age for dir, they can be always cached since readdir is uncached anyway */
       mdbg(INFO3, "Date compare: %d vs %d", &filter_pattern->older_than.tv_sec, ctime->tv_sec);
       return S_ISDIR(umode) || timespec_compare(&filter_pattern->older_than, ctime) > 0;
     } else {
       /* Match string pattern */
       while ( name_index > -1 && pattern_index > -1 ) {
           if ( pattern[pattern_index] == '*' ) {
               if ( pattern_index != 0 ) {
                   printk(KERN_WARNING "Illegal pattern '%s'! Pattern must have * only at the beggining!\n", filter_pattern->pattern);
               }
               return 1;
           } else if ( pattern[pattern_index] != name[name_index] ) {
               return 0;
           }
           name_index--;
           pattern_index--;
       }
     }
     return name_index == pattern_index;
 }