Clondike: tcmi_guest_started_procmsg class
tcmi_guest_started_procmsg class
tcmi_procmsg class
This class represents a message that is sent to the migration initiator as a response to a migration request.
Data Structures
struct tcmi_guest_started_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Macros
#define TCMI_GUEST_STARTED_PROCMSG_DSC TCMI_MSG_DSC(TCMI_GUEST_STARTED_PROCMSG_ID, tcmi_guest_started_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
#define TCMI_GUEST_STARTED_PROCMSG(m) ((struct tcmi_guest_started_procmsg*)m)
Casts to the tcmi_guest_started_procmsg instance.
Functions
static int tcmi_guest_started_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_guest_started_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Sends the message via a specified connection.
struct tcmi_msg * tcmi_guest_started_procmsg_new_rx (u_int32_t msg_id)
<<public>> Guest started message rx constructor.
struct tcmi_msg * tcmi_guest_started_procmsg_new_tx (u_int32_t trans_id, pid_t dst_pid, pid_t guest_pid)
<<public>> Guest started message tx constructor.
static pid_t tcmi_guest_started_procmsg_guest_pid (struct tcmi_guest_started_procmsg *self)
<<public>> Stub PID accessor.
Variables
static struct tcmi_procmsg_ops guest_started_procmsg_ops
Message operations that support polymorphism.
Detailed Description
This class represents a message that is sent to the migration initiator as a response to a migration request.
The main purpose is to communicate the PID of the guest process to the migration initiator.
Data Structure Documentation
struct tcmi_guest_started_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Definition at line 50 of file tcmi_guest_started_procmsg.h.
Data Fields
pid_t guest_pid guest PID, used for further communication.
struct tcmi_procmsg super parent class instance
Macro Definition Documentation
#define TCMI_GUEST_STARTED_PROCMSG (m) ((struct tcmi_guest_started_procmsg*)m)
Casts to the tcmi_guest_started_procmsg instance.
Definition at line 75 of file tcmi_guest_started_procmsg.h.
Referenced by tcmi_guest_started_procmsg_new_rx(), tcmi_guest_started_procmsg_new_tx(), tcmi_guest_started_procmsg_recv(), tcmi_guest_started_procmsg_send(), tcmi_shadowtask_process_msg(), and tcmi_shadowtask_verify_migration().
#define TCMI_GUEST_STARTED_PROCMSG_DSC TCMI_MSG_DSC(TCMI_GUEST_STARTED_PROCMSG_ID, tcmi_guest_started_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
Definition at line 71 of file tcmi_guest_started_procmsg.h.
Function Documentation
static pid_t tcmi_guest_started_procmsg_guest_pid (struct tcmi_guest_started_procmsg * self) inline static
<<public>> Stub PID accessor.
Parameters
*self - this message instance
Returns
guest PID
Definition at line 83 of file tcmi_guest_started_procmsg.h.
Referenced by tcmi_shadowtask_process_msg(), and tcmi_shadowtask_verify_migration().
 {
     return self->guest_pid;
 }
struct tcmi_msg* tcmi_guest_started_procmsg_new_rx (u_int32_t msg_id) read
<<public>> Guest started message rx constructor.
This method is called by the factory class.
Parameters
msg_id - message ID, to check with the actual response process message ID.
Returns
a new guest started process message or NULL.
Definition at line 52 of file tcmi_guest_started_procmsg.c.
References guest_started_procmsg_ops, mdbg, TCMI_GUEST_STARTED_PROCMSG, TCMI_GUEST_STARTED_PROCMSG_ID, TCMI_MSG, TCMI_PROCMSG, and tcmi_procmsg_init_rx().
 {
     struct tcmi_guest_started_procmsg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_GUEST_STARTED_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified process message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_GUEST_STARTED_PROCMSG_ID);
         goto exit0;
     }
     if (!(msg = TCMI_GUEST_STARTED_PROCMSG(kmalloc(sizeof(struct tcmi_guest_started_procmsg),
                               GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate guest started process message");
         goto exit0;
     }
     /* initialize the message for receiving */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_GUEST_STARTED_PROCMSG_ID,
                  &guest_started_procmsg_ops)) {
         mdbg(ERR3, "Error initializing process message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_guest_started_procmsg_new_tx (u_int32_t trans_id, pid_t dst_pid, pid_t guest_pid) read
<<public>> Guest started message tx constructor.
<<public>> Guest started message tx constructor.
The response message requires specifying the local PID(guest PID) of the sender in addition to the destination PID used for routing.
Parameters
trans_id - transaction ID that this message is replying to.
dst_pid - destination process PID
guest_pid - PID of the sending process
Returns
a new test response message for the transfer or NULL.
Definition at line 94 of file tcmi_guest_started_procmsg.c.
References tcmi_guest_started_procmsg::guest_pid, guest_started_procmsg_ops, mdbg, TCMI_GUEST_STARTED_PROCMSG, TCMI_GUEST_STARTED_PROCMSG_ID, TCMI_MSG, TCMI_PROCMSG, and tcmi_procmsg_init_tx().
Referenced by tcmi_guesttask_post_fork(), and tcmi_guesttask_process_p_emigrate_msg().
 {
     struct tcmi_guest_started_procmsg *msg;
     if (!(msg = TCMI_GUEST_STARTED_PROCMSG(kmalloc(sizeof(struct tcmi_guest_started_procmsg),
                           GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate testing message");
         goto exit0;
     }
     /* Initialize the message for transfer, no transaction
      * required, no timout, no response ID */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_GUEST_STARTED_PROCMSG_ID, &guest_started_procmsg_ops,
                  dst_pid, 0,
                  NULL, 0, 0, trans_id)) {
         mdbg(ERR3, "Error initializing testing response message");
         goto exit1;
     }
     msg->guest_pid = guest_pid;
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_guest_started_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the guest started process message requires reading guest PID from the specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 139 of file tcmi_guest_started_procmsg.c.
References tcmi_guest_started_procmsg::guest_pid, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, and TCMI_GUEST_STARTED_PROCMSG.
 {
     int err;
     struct tcmi_guest_started_procmsg *self_msg = TCMI_GUEST_STARTED_PROCMSG(self);
     err = kkc_sock_recv(sock, &self_msg->guest_pid,
                 sizeof(self_msg->guest_pid), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Received guest PID %d", self_msg->guest_pid);
     return err;
 }
static int tcmi_guest_started_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Sends the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully sent.
Definition at line 159 of file tcmi_guest_started_procmsg.c.
References tcmi_guest_started_procmsg::guest_pid, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, and TCMI_GUEST_STARTED_PROCMSG.
 {
     int err;
     struct tcmi_guest_started_procmsg *self_msg = TCMI_GUEST_STARTED_PROCMSG(self);
     err = kkc_sock_send(sock, &self_msg->guest_pid,
                 sizeof(self_msg->guest_pid), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Sent guest PID %d", self_msg->guest_pid);
     return err;
 }
Variable Documentation
struct tcmi_procmsg_ops guest_started_procmsg_ops static
Initial value:
= {
    .recv = tcmi_guest_started_procmsg_recv,
    .send = tcmi_guest_started_procmsg_send
}
Message operations that support polymorphism.
Definition at line 175 of file tcmi_guest_started_procmsg.c.
Referenced by tcmi_guest_started_procmsg_new_rx(), and tcmi_guest_started_procmsg_new_tx().