Clondike: Signal sending
Signal sending
tcmi_syscallhooks class
A <<singleton>> class that installs syscalls hooks into the kernel.
Functions
int tcmi_syscall_hooks_signal_init (void)
<<public>> Registers all hooks with the kernel.
void tcmi_syscall_hooks_signal_exit (void)
<<public>> Unregisters all hooks.
Detailed Description
A <<singleton>> class that installs syscalls hooks into the kernel.
Function Documentation
void tcmi_syscall_hooks_signal_exit (void)
<<public>> Unregisters all hooks.
Definition at line 59 of file tcmi_syscallhooks_signal.c.
References minfo.
Referenced by tcmi_syscall_hooks_exit().
 {
     minfo(INFO3, "Unregistering TCMI signal syscalls hooks");
     tcmi_hooks_unregister_sys_kill();
     tcmi_hooks_unregister_do_tkill();
     tcmi_hooks_unregister_sys_rt_sigqueueinfo();
 }
int tcmi_syscall_hooks_signal_init (void)
<<public>> Registers all hooks with the kernel.
<<public>> Registers all hooks with the kernel.
Returns
0 upon success
Definition at line 46 of file tcmi_syscallhooks_signal.c.
References minfo, tcmi_syscall_hooks_do_tkill(), tcmi_syscall_hooks_sys_kill(), and tcmi_syscall_hooks_sys_rt_sigqueueinfo().
Referenced by tcmi_syscall_hooks_init().
 {
     minfo(INFO3, "Registering TCMI signal syscalls hooks\n"
              "For: kill, tkill, tgkill, sigqueue");
     tcmi_hooks_register_sys_kill(tcmi_syscall_hooks_sys_kill);
     tcmi_hooks_register_do_tkill(tcmi_syscall_hooks_do_tkill);
     tcmi_hooks_register_sys_rt_sigqueueinfo( tcmi_syscall_hooks_sys_rt_sigqueueinfo );
     return 0;
 }