Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/tcmi/ckpt/tcmi_ckpt_resources.h File Reference
tcmi_ckpt_resources.h File Reference
a helper class that provides functionality to checkpoint process rlimits
#include <asm/uaccess.h>
#include <linux/resource.h>
#include "tcmi_ckpt.h"
Data Structures
struct tcmi_ckpt_rlimit
struct tcmi_ckpt_rlimits
Functions
struct tcmi_ckpt_rlimit __attribute__ ((__packed__))
static int tcmi_ckpt_write_rlimit (struct tcmi_ckpt *ckpt, struct task_struct *task)
Writes a current process rlimits into the file.
static int tcmi_ckpt_read_rlimit (struct tcmi_ckpt *ckpt, struct task_struct *task)
Reads a process rlimits.
Variables
u_int64_t rlim_cur
u_int64_t rlim_max
struct tcmi_ckpt_rlimit rlim [RLIM_NLIMITS]
Detailed Description
a helper class that provides functionality to checkpoint process rlimits
Definition in file tcmi_ckpt_resources.h.
Data Structure Documentation
struct tcmi_ckpt_rlimit
Definition at line 12 of file tcmi_ckpt_resources.h.
Data Fields
u_int64_t rlim_cur
u_int64_t rlim_max
struct tcmi_ckpt_rlimits
Definition at line 17 of file tcmi_ckpt_resources.h.
Data Fields
struct tcmi_ckpt_rlimit rlim[RLIM_NLIMITS]
Function Documentation
struct tcmi_ckpt_rlimit __attribute__ ((__packed__))
static int tcmi_ckpt_read_rlimit (struct tcmi_ckpt * ckpt, struct task_struct * task) inline static
Reads a process rlimits.
Parameters
*ckpt - checkpoint file where the area is stored
*task - current task
Returns
0 upon success.
Definition at line 60 of file tcmi_ckpt_resources.h.
References CHECKED_UINT64_TO_ULONG, mdbg, tcmi_ckpt_rlimits::rlim, tcmi_ckpt_rlimit::rlim_cur, tcmi_ckpt_rlimit::rlim_max, and tcmi_ckpt_read().
Referenced by tcmi_ckptcom_restart().
 {
     struct tcmi_ckpt_rlimits rlims;
     int i;
     if (tcmi_ckpt_read(ckpt, &rlims, sizeof(rlims)) < 0) {
         mdbg(ERR3, "Error reading process limits");
         goto exit0;
     }
     for ( i=0; i < RLIM_NLIMITS; i++ ) {
         task->signal->rlim[i].rlim_cur = CHECKED_UINT64_TO_ULONG(rlims.rlim[i].rlim_cur);
         task->signal->rlim[i].rlim_max = CHECKED_UINT64_TO_ULONG(rlims.rlim[i].rlim_max);
     }
     mdbg(INFO4, "Read process limits.");
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_write_rlimit (struct tcmi_ckpt * ckpt, struct task_struct * task) inline static
Writes a current process rlimits into the file.
Parameters
*ckpt - checkpoint file where the area is to be stored
*task - current task
Returns
0 upon success.
Definition at line 28 of file tcmi_ckpt_resources.h.
References mdbg, tcmi_ckpt_rlimits::rlim, tcmi_ckpt_rlimit::rlim_cur, tcmi_ckpt_rlimit::rlim_max, and tcmi_ckpt_write().
Referenced by tcmi_ckptcom_checkpoint().
 {
     struct tcmi_ckpt_rlimits rlims;
     int i;
     for ( i=0; i < RLIM_NLIMITS; i++ ) {
         rlims.rlim[i].rlim_cur = task->signal->rlim[i].rlim_cur;
         rlims.rlim[i].rlim_max = task->signal->rlim[i].rlim_max;
     }
     if (tcmi_ckpt_write(ckpt, &rlims, sizeof(rlims)) < 0) {
         mdbg(ERR3, "Error writing resource limits");
         goto exit0;
     }
     mdbg(INFO4, "Written resouce limits.");
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
Variable Documentation
struct tcmi_ckpt_rlimit rlim[RLIM_NLIMITS]
Definition at line 20 of file tcmi_ckpt_resources.h.
u_int64_t rlim_cur
Definition at line 16 of file tcmi_ckpt_resources.h.
u_int64_t rlim_max
Definition at line 17 of file tcmi_ckpt_resources.h.