Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/tcmi/migration/fs/9p_fs_helper.h File Reference
9p_fs_helper.h File Reference
#include <linux/types.h>
#include <linux/completion.h>
#include <linux/file.h>
#include <linux/fs.h>
#include <linux/fs_struct.h>
#include <linux/mount.h>
#include <linux/namei.h>
#include <linux/sched.h>
#include <linux/jiffies.h>
#include <linux/slab.h>
Macros
#define MAX_ADDITIONAL_CONNECT_STR_LEN 200
Functions
static int mount_9p_fs (const char *mount_point, struct fs_mounter *mounter, int16_t fsuid, int16_t fsgid)
static int chroot_to (const char *path_to_chroot)
Chroots process to a new root.
Macro Definition Documentation
#define MAX_ADDITIONAL_CONNECT_STR_LEN 200
Definition at line 15 of file 9p_fs_helper.h.
Referenced by mount_9p_fs().
Function Documentation
static int chroot_to (const char * path_to_chroot) static
Chroots process to a new root.
Todo:
: Move to some generic fs helper, if we ever have another fs mounter.
Definition at line 62 of file 9p_fs_helper.h.
References minfo.
Referenced by chroot_to_mount(), and do_private_9p_mount().
{
     int err;
     struct path old_root;
     //struct nameidata nd;
     struct path p;
     //Function path_lookup() is replaced to kern_path() with last parameter pointer to struct path
     err = kern_path(path_to_chroot, LOOKUP_FOLLOW | LOOKUP_DIRECTORY ,&p);
     if ( err ) {
         minfo(ERR1, "Failed to lookup path %s: %d", path_to_chroot, err);
         goto exit0;
     }
     /* Chroots.. duplicated code from chroot as it cannot be used directly */
         spin_lock(&current->fs->lock);      //Replaced write_lock to spin_lock (write_unlock -> spin_unlock) because in struct fs_struct type of lock was changed to spinlock_t | by Jiri Rakosnik
         old_root = current->fs->root;
         path_get(&p);
         current->fs->root = p;
         spin_unlock(&current->fs->lock);
         if (old_root.dentry) {
                  path_put(&old_root);
         }
     return 0;
 exit0:
     return err;
 };
static int mount_9p_fs (const char * mount_point, struct fs_mounter * mounter, int16_t fsuid, int16_t fsgid) static
Definition at line 17 of file 9p_fs_helper.h.
References MAX_ADDITIONAL_CONNECT_STR_LEN, mdbg, minfo, fs_mount_params::mount_device, fs_mount_params::mount_options, and fs_mounter::params.
Referenced by do_private_9p_mount(), and global_9p_mount().
{
     int err;
     char* device = mounter->params.mount_device;
     char* connect_param = mounter->params.mount_options;
     char* mount_point_page = __getname();
     int connect_str_len = strlen(connect_param);
     if ( !mount_point_page )
         return -ENOMEM;
     memcpy(mount_point_page, mount_point, strlen(mount_point) + 1);
     connect_param = kmalloc(connect_str_len + MAX_ADDITIONAL_CONNECT_STR_LEN, GFP_KERNEL);
     if ( !connect_param ) {
         err = -ENOMEM;
         goto exit0;
     }
     if ( connect_str_len == 0 ) {
         snprintf(connect_param, connect_str_len + MAX_ADDITIONAL_CONNECT_STR_LEN, "cuid=%d,cgid=%d", fsuid, fsgid);
     } else {
         snprintf(connect_param, connect_str_len + MAX_ADDITIONAL_CONNECT_STR_LEN, "%s,cuid=%d,cgid=%d", mounter->params.mount_options, fsuid, fsgid);
     }
     mdbg(INFO2, "9p mount device: %s mount options: %s mount point: %s", device, connect_param, mount_point);
     err = do_mount(device, mount_point_page, "9p", 0, connect_param);
     mdbg(INFO2, "After 9P mount: %d", err);
     if ( err ) {
         minfo(ERR1, "Failed to mount filesystem: %d", err);
         goto exit1;
     }
     return 0;
 exit1:
     kfree(connect_param);
 exit0:
     __putname(mount_point_page);
     return err;
 };