Clondike: proxyfs_pipe_real_file class
proxyfs_pipe_real_file class
proxyfs_real_file class
This class is used by server task for accessing pipe files.
Macros
#define PROXYFS_PIPE_REAL_FILE(arg) ((struct proxyfs_pipe_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Functions
int proxyfs_pipe_real_file_init (struct proxyfs_pipe_real_file *self)
<<public>> Initialize pipe_real_file
void proxyfs_pipe_real_file_destroy (struct proxyfs_pipe_real_file *self)
<<public>> Deinitialize pipe_real_file
struct proxyfs_pipe_real_file * proxyfs_pipe_real_file_new (void)
<<public>> pipe_real_file construktor
Detailed Description
This class is used by server task for accessing pipe files.
Macro Definition Documentation
#define PROXYFS_PIPE_REAL_FILE (arg) ((struct proxyfs_pipe_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Definition at line 61 of file proxyfs_pipe_real_file.h.
Referenced by proxyfs_pipe_real_file_duplicate(), and proxyfs_pipe_real_file_write().
Function Documentation
void proxyfs_pipe_real_file_destroy (struct proxyfs_pipe_real_file * self)
<<public>> Deinitialize pipe_real_file
int proxyfs_pipe_real_file_init (struct proxyfs_pipe_real_file * self)
<<public>> Initialize pipe_real_file
<<public>> Initialize pipe_real_file
Parameters
*self - pointer to this file instance
Returns
zero on success
Definition at line 274 of file proxyfs_pipe_real_file.c.
References PROXYFS_REAL_FILE.
Referenced by proxyfs_pipe_real_file_duplicate(), and proxyfs_pipe_real_file_new().
 {
     PROXYFS_REAL_FILE(self)->ops = &pipe_real_file_ops;
     self->write_counter = 0;
     return 0;
 }
struct proxyfs_pipe_real_file* proxyfs_pipe_real_file_new (void) read
<<public>> pipe_real_file construktor
Returns
new proxyfs_pipe_real_file instance or NULL on error
Definition at line 285 of file proxyfs_pipe_real_file.c.
References mdbg, proxyfs_pipe_real_file_init(), PROXYFS_REAL_FILE, proxyfs_real_file_destroy(), and proxyfs_real_file_init().
Referenced by proxyfs_server_overtake_file().
 {
     struct proxyfs_pipe_real_file *self;
     self = (struct proxyfs_pipe_real_file*)kmalloc(sizeof(struct proxyfs_pipe_real_file), GFP_KERNEL);
     if( self == NULL ){
         mdbg(ERR3, "Allocating new proxyfs_pipe_real_file failed");
         goto exit0;
     }
     if( proxyfs_real_file_init( PROXYFS_REAL_FILE(self) ) != 0 )
         goto exit1;
     if( proxyfs_pipe_real_file_init( self ) != 0 )
         goto exit2;
     return self;
 exit2:
     proxyfs_real_file_destroy( PROXYFS_REAL_FILE(self) );
 exit1:
     kfree(self);
 exit0:
     return self;
 }