Clondike: tcmi_disconnect_msg class
tcmi_disconnect_msg class
tcmi_msg class
This message is send by PEN or CCN when it is going to disconnect from its peer.
Data Structures
struct tcmi_disconnect_msg
Disconnect message structure.
Macros
#define TCMI_DISCONNECT_MSG_DSC TCMI_MSG_DSC(TCMI_DISCONNECT_MSG_ID, tcmi_disconnect_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
#define TCMI_DISCONNECT_MSG(m) ((struct tcmi_disconnect_msg*)m)
Casts to the tcmi_disconnect_msg instance.
Functions
static int tcmi_disconnect_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_disconnect_msg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Sends the message via a specified connection.
struct tcmi_msg * tcmi_disconnect_msg_new_rx (u_int32_t msg_id)
<<public>> Disconnect message consutructor for receiving.
struct tcmi_msg * tcmi_disconnect_msg_new_tx (void)
<<public>> Disconnect message constructor for transferring.
Variables
static struct tcmi_msg_ops disconnect_msg_ops
Message operations that support polymorphism.
Detailed Description
This message is send by PEN or CCN when it is going to disconnect from its peer.
It serves as a notification, to tell the peer it shall as well terminate the connection. In addition, if send from CCN to PEN, the PEN should as a resonpse first try to migrate back all tasks from a peer core node.
Data Structure Documentation
struct tcmi_disconnect_msg
Disconnect message structure.
Definition at line 22 of file tcmi_disconnect_msg.h.
Data Fields
struct tcmi_msg super parent class instance.
Macro Definition Documentation
#define TCMI_DISCONNECT_MSG (m) ((struct tcmi_disconnect_msg*)m)
Casts to the tcmi_disconnect_msg instance.
Definition at line 42 of file tcmi_disconnect_msg.h.
Referenced by tcmi_disconnect_msg_new_rx(), and tcmi_disconnect_msg_new_tx().
#define TCMI_DISCONNECT_MSG_DSC TCMI_MSG_DSC(TCMI_DISCONNECT_MSG_ID, tcmi_disconnect_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
Definition at line 39 of file tcmi_disconnect_msg.h.
Function Documentation
struct tcmi_msg* tcmi_disconnect_msg_new_rx (u_int32_t msg_id) read
<<public>> Disconnect message consutructor for receiving.
<<public>> Disconnect message consutructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this message instance.
Returns
a new message or NULL.
Definition at line 23 of file tcmi_disconnect_msg.c.
References disconnect_msg_ops, mdbg, TCMI_DISCONNECT_MSG, TCMI_DISCONNECT_MSG_ID, TCMI_MSG, and tcmi_msg_init_rx().
 {
     struct tcmi_disconnect_msg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_DISCONNECT_MSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_DISCONNECT_MSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_DISCONNECT_MSG(kmalloc(sizeof(struct tcmi_disconnect_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate disconnect request message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_DISCONNECT_MSG_ID, &disconnect_msg_ops)) {
         mdbg(ERR3, "Error initializing disconnect request message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_disconnect_msg_new_tx (void) read
<<public>> Disconnect message constructor for transferring.
<<public>> Disconnect message constructor for transferring.
Parameters
*transactions - storage for the new transaction
Returns
a new message ready for the transfer or NULL.
Definition at line 61 of file tcmi_disconnect_msg.c.
References disconnect_msg_ops, mdbg, TCMI_DISCONNECT_MSG, TCMI_DISCONNECT_MSG_ID, TCMI_MSG, tcmi_msg_init_tx(), and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_migman_notify_peer_disconnect().
 {
     struct tcmi_disconnect_msg *msg;
     if (!(msg = TCMI_DISCONNECT_MSG(kmalloc(sizeof(struct tcmi_disconnect_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate disconnect request message");
         goto exit0;
     }
     /* Initialize the message for transfer */
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_DISCONNECT_MSG_ID, &disconnect_msg_ops,
                  NULL, 0,
                  0, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing disconnect request message message");
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_disconnect_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 100 of file tcmi_disconnect_msg.c.
References mdbg.
 {
     mdbg(INFO2, "Disconnect message received");
     return 0;
 }
static int tcmi_disconnect_msg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Sends the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 114 of file tcmi_disconnect_msg.c.
References mdbg.
 {
     mdbg(INFO2, "Disconnect request message sent.");
     return 0;
 }
Variable Documentation
struct tcmi_msg_ops disconnect_msg_ops static
Initial value:
= {
    .recv = tcmi_disconnect_msg_recv,
    .send = tcmi_disconnect_msg_send,
    .free = NULL,
}
Message operations that support polymorphism.
Definition at line 122 of file tcmi_disconnect_msg.c.
Referenced by tcmi_disconnect_msg_new_rx(), and tcmi_disconnect_msg_new_tx().