Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/syscall/tcmi_syscallhooks_pidman.c File Reference
tcmi_syscallhooks_pidman.c File Reference
syscalls hooks for proces identification manipulation.
#include <clondike/tcmi/tcmi_hooks.h>
#include <dbg.h>
#include <tcmi/syscall/tcmi_guest_rpc.h>
#include <tcmi/task/tcmi_task.h>
#include <arch/current/make_syscall.h>
#include "tcmi_syscallhooks_pidman.h"
Macros
#define TCMI_SYSCALLHOOKS_PIDMAN_PRIVATE
Functions
int tcmi_syscall_hooks_pidman_init (void)
<<public>> Registers all PID manipulaton syscalls hooks with the kernel.
void tcmi_syscall_hooks_pidman_exit (void)
<<public>> Unregisters all PID manipulation syscalls hooks.
static long tcmi_syscall_hooks_sys_getppid (void)
<<private>> Getppid system call hook
static long tcmi_syscall_hooks_sys_getpid (void)
<<private>> Getpid system call hook
static long tcmi_syscall_hooks_sys_getpgid (pid_t pid)
<<private>> Getpgid system call hook
static long tcmi_syscall_hooks_sys_setpgid (pid_t pid, pid_t pgid)
<<private>> Setpgid system call hook
static long tcmi_syscall_hooks_sys_getsid (pid_t pid)
<<private>> Getsid system call hook
static long tcmi_syscall_hooks_sys_setsid (void)
<<private>> Setsid system call hook
static long tcmi_syscall_hooks_sys_getpgrp (void)
<<private>> Getpgrp system call hook
Detailed Description
syscalls hooks for proces identification manipulation.
Date: 13/06/2007
Author: Petr Malat
Id:
tcmi_syscallhooks_pidman.c,v 1.7 2007/10/20 14:24:20 stavam2 Exp
This file is part of Task Checkpointing and Migration Infrastructure(TCMI) Copyleft (C) 2007 Petr Malat
TCMI is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
TCMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file tcmi_syscallhooks_pidman.c.
Macro Definition Documentation
#define TCMI_SYSCALLHOOKS_PIDMAN_PRIVATE
Definition at line 39 of file tcmi_syscallhooks_pidman.c.
Function Documentation
static long tcmi_syscall_hooks_sys_getpgid (pid_t pid) static
<<private>> Getpgid system call hook
Parameters
pid - PID
Returns
the process group ID of the process specified by pid.
Definition at line 105 of file tcmi_syscallhooks_pidman.c.
References tcmi_guest_rpc, tcmi_rpc_call1(), and TCMI_RPC_SYS_GETPGID.
Referenced by tcmi_syscall_hooks_pidman_init().
 {
     return tcmi_rpc_call1(tcmi_guest_rpc, TCMI_RPC_SYS_GETPGID, pid);
 }
static long tcmi_syscall_hooks_sys_getpgrp (void) static
<<private>> Getpgrp system call hook
Returns
current process group
Definition at line 148 of file tcmi_syscallhooks_pidman.c.
References tcmi_guest_rpc, tcmi_rpc_call0(), and TCMI_RPC_SYS_GETPGRP.
Referenced by tcmi_syscall_hooks_pidman_init().
 {
     return tcmi_rpc_call0(tcmi_guest_rpc, TCMI_RPC_SYS_GETPGRP);
 }
static long tcmi_syscall_hooks_sys_getpid (void) static
<<private>> Getpid system call hook
Returns
pid of current process.
Definition at line 92 of file tcmi_syscallhooks_pidman.c.
References mdbg, and tcmi_task_remote_pid().
Referenced by tcmi_syscall_hooks_pidman_init().
 {
     mdbg(INFO3, "Getpid hook called. Returning via fast-path pid %d. Physical pid: %d",tcmi_task_remote_pid(current->tcmi.tcmi_task), current->pid);
     /* Won't work with threads */
     return tcmi_task_remote_pid(current->tcmi.tcmi_task);
 }
static long tcmi_syscall_hooks_sys_getppid (void) static
<<private>> Getppid system call hook
Returns
pid of parent process.
Definition at line 82 of file tcmi_syscallhooks_pidman.c.
References tcmi_guest_rpc, tcmi_rpc_call0(), and TCMI_RPC_SYS_GETPPID.
Referenced by tcmi_syscall_hooks_pidman_init().
 {
     return tcmi_rpc_call0(tcmi_guest_rpc, TCMI_RPC_SYS_GETPPID);
 }
static long tcmi_syscall_hooks_sys_getsid (pid_t pid) static
<<private>> Getsid system call hook
Parameters
pid -
Returns
the session ID of the process with process ID pid
Definition at line 128 of file tcmi_syscallhooks_pidman.c.
References tcmi_guest_rpc, tcmi_rpc_call1(), and TCMI_RPC_SYS_GETSID.
Referenced by tcmi_syscall_hooks_pidman_init().
 {
     return tcmi_rpc_call1(tcmi_guest_rpc, TCMI_RPC_SYS_GETSID, pid);
 }
static long tcmi_syscall_hooks_sys_setpgid (pid_t pid, pid_t pgid) static
<<private>> Setpgid system call hook
Parameters
pid - PID of affected process
sig - target group ID
Returns
zero on sucess
Definition at line 117 of file tcmi_syscallhooks_pidman.c.
References tcmi_guest_rpc, tcmi_rpc_call2(), and TCMI_RPC_SYS_SETPGID.
Referenced by tcmi_syscall_hooks_pidman_init().
 {
     return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_SETPGID, pid, pgid);
 }
static long tcmi_syscall_hooks_sys_setsid (void) static
<<private>> Setsid system call hook
Returns
the session ID of the calling process
Definition at line 138 of file tcmi_syscallhooks_pidman.c.
References tcmi_guest_rpc, tcmi_rpc_call0(), and TCMI_RPC_SYS_SETSID.
Referenced by tcmi_syscall_hooks_pidman_init().
 {
     return tcmi_rpc_call0(tcmi_guest_rpc, TCMI_RPC_SYS_SETSID);
 }