Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/manager/tcmi_man.c File Reference
tcmi_man.c File Reference
#include <linux/types.h>
#include <linux/random.h>
#include <linux/kthread.h>
#include <tcmi/ctlfs/tcmi_ctlfs.h>
#include <tcmi/lib/tcmi_sock.h>
#include <tcmi/task/tcmi_task.h>
#include "tcmi_ccnmigman.h"
#include <kkc/kkc.h>
#include "tcmi_man.h"
#include <dbg.h>
Macros
#define TCMI_MAN_PRIVATE
#define MAX_NODES 40
maximum number of connected nodes
Functions
int tcmi_man_init (struct tcmi_man *self, struct tcmi_ctlfs_entry *root, struct tcmi_man_ops *ops, const char *man_dirname)
<<public>> Initializes the TCMI manager.
static void tcmi_man_wait_for_migmans_termination (struct tcmi_man *self)
Waits for all migration managers to terminate.
void tcmi_man_shutdown (struct tcmi_man *self)
<<public>> The manager is shutdown exactly in this order:
static int tcmi_man_do_send_generic_user_message (struct tcmi_man *self, int target_slot_index, int user_data_size, char *user_data, struct tcmi_migman *migman)
int tcmi_man_send_generic_user_message (struct tcmi_man *self, int target_slot_index, int user_data_size, char *user_data)
<<public>> Send generic user message
static int tcmi_man_init_ctlfs_dirs (struct tcmi_man *self, struct tcmi_ctlfs_entry *root, const char *man_dirname)
<<private>> Creates the directories as described in here .
static int tcmi_man_init_ctlfs_files (struct tcmi_man *self)
<<private>> Creates the static files described here .
static void tcmi_man_stop_ctlfs_dirs (struct tcmi_man *self)
<<private>> Destroys all ctlfs directories, first the singleton instance specific directories are destroyed
static void tcmi_man_stop_ctlfs_files (struct tcmi_man *self)
<<private>> Unregisters and releases all control files.
static int tcmi_man_init_migration (struct tcmi_man *self)
<<private>>.
static struct tcmi_migman * tcmi_man_get_non_shutdowning_migman (struct tcmi_man *self)
Finds and returns arbitrary migration manager that is either in INIT or CONNECTED state.
static void tcmi_man_stop_migration (struct tcmi_man *self)
<<private>> Stops all migration components.
static int tcmi_man_stop (void *obj, void *data)
<<private>> If the user called this method with parameter > 0, the TCMI manager stops the migration framework.
static int tcmi_man_emig_ppm_p (void *obj, void *data)
<<private>> TCMI ctlfs write method - emigration PPM P What needs to be done:
int tcmi_man_emig_npm (struct tcmi_man *self, pid_t pid, u_int32_t migman_id, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
<<public>> Method that performs non-preemtive migration
int tcmi_man_fork (struct tcmi_man *self, struct task_struct *parent, struct task_struct *child)
<<public>> Method that performs task fork
static int tcmi_man_mig_home_ppm_p (void *obj, void *data)
<<private>> TCMI ctlfs write method - migration home.
Macro Definition Documentation
#define MAX_NODES 40
maximum number of connected nodes
Definition at line 49 of file tcmi_man.c.
Referenced by tcmi_man_init().
#define TCMI_MAN_PRIVATE
Definition at line 43 of file tcmi_man.c.
Function Documentation
static int tcmi_man_do_send_generic_user_message (struct tcmi_man * self, int target_slot_index, int user_data_size, char * user_data, struct tcmi_migman * migman) inline static
Definition at line 155 of file tcmi_man.c.
References mdbg, self, tcmi_generic_user_msg_new_tx(), tcmi_migman_sock(), TCMI_MSG, tcmi_msg_put(), and tcmi_msg_send_anonymous().
Referenced by tcmi_man_send_generic_user_message().
{
     int err = 0;
     struct tcmi_msg* msg;
     // TODO: Node id is passed incorrectly, but on the other hand this node id is complete bullshit and should be likely removed, right?
     if ( !( msg = TCMI_MSG(tcmi_generic_user_msg_new_tx(self->id, user_data, user_data_size)) ) ) {
         mdbg(ERR3, "Error creating response message");
         return - ENOMEM;        ;
     }
     if ((err = tcmi_msg_send_anonymous(msg, tcmi_migman_sock(migman)))) {
         mdbg(ERR3, "Error sending user message %d", err);
         err = -EINVAL;
     }
     tcmi_msg_put(msg);
     return err;
 }
static void tcmi_man_wait_for_migmans_termination (struct tcmi_man * self) static
Waits for all migration managers to terminate.
Note: We perform wait by active polling of count of remaining migmas (100ms) interval. In case there were no remote processes running, there would be no wait as all migmans were terminated synchronously. In case there were remote processes, the waiting time for their migration back would be likely in order of seconds, so 100ms does not add much latency In case somebody volunteers, the code could be migrated to notify/wait patter to get rid of polling
Definition at line 113 of file tcmi_man.c.
References self, tcmi_slotvec_empty(), tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_man_shutdown().
{
     int is_empty;
     tcmi_slotvec_lock(self->mig_mans);
     is_empty = tcmi_slotvec_empty(self->mig_mans);
     tcmi_slotvec_unlock(self->mig_mans);
     while (!is_empty) {
         set_current_state(TASK_INTERRUPTIBLE);
         schedule_timeout(msecs_to_jiffies(100));
         tcmi_slotvec_lock(self->mig_mans);
         is_empty = tcmi_slotvec_empty(self->mig_mans);
         tcmi_slotvec_unlock(self->mig_mans);
     }
 }