Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ckpt/tcmi_ckpt.h File Reference
tcmi_ckpt.h File Reference
#include <linux/fs.h>
#include <linux/file.h>
#include <linux/mm.h>
#include <asm/uaccess.h>
#include <linux/syscalls.h>
#include <linux/unistd.h>
#include "tcmi_fdcache.h"
#include <arch/arch_ids.h>
#include <dbg.h>
Data Structures
struct tcmi_ckpt_hdr
Describes the checkpoint header.
struct tcmi_ckpt
Compound structure that gathers necessary process information.
Macros
#define __KERNEL_SYSCALLS__
enables access to system calls from kernel
#define TCMI_CKPT(ckpt) ((struct tcmi_ckpt*)ckpt)
Casts to the checkpoint instance.
#define TCMI_CKPT_MAGIC 0xdeadbeef
a magic number for the header
#define tcmi_ckpt_foreach_openfile(file, fd)
<<public>> Iterates through all open files
Typedefs
typedef ssize_t vfs_method_t (struct file *, char __user *, size_t, loff_t *)
Describes the signature of the VFS method (typically vfs_read or vfs_write.
Functions
struct tcmi_ckpt_hdr __attribute__ ((__packed__))
struct tcmi_ckpt * tcmi_ckpt_new (struct file *file)
<<public>> Checkpoint constructor.
int tcmi_ckpt_write_hdr (struct tcmi_ckpt *self, int is_npm)
<<public>> Writes a checkpoint header.
int tcmi_ckpt_read_hdr (struct tcmi_ckpt *self)
<<public>> Reads a checkpoint header.
int tcmi_ckpt_write_files (struct tcmi_ckpt *self)
<<public>> Writes open files into the checkpoint.
int tcmi_ckpt_read_files (struct tcmi_ckpt *self)
<<public>> Reads open files from the checkpoint.
int tcmi_ckpt_write_vmas (struct tcmi_ckpt *self, int heavy)
<<public>> Writes process memory regions into the checkpoint.
int tcmi_ckpt_read_vmas (struct tcmi_ckpt *self)
<<public>> Reads process memory regions from the checkpoint.
int tcmi_ckpt_write_regs (struct tcmi_ckpt *self, struct pt_regs *regs)
<<public>> Writes process CPU registers into the checkpoint.
int tcmi_ckpt_read_regs (struct tcmi_ckpt *self, struct pt_regs *regs)
<<public>> Reads process CPU registers from the checkpoint.
static int tcmi_ckpt_check_magic (void *buf)
<<public>> Writes signals related stuff into the checkpoint.
static struct tcmi_ckpt * tcmi_ckpt_get (struct tcmi_ckpt *self)
<<public>> Instance accessor, increments the reference counter.
static void tcmi_ckpt_put (struct tcmi_ckpt *self)
<<public>> Releases the instance.
static int tcmi_ckpt_read_write (struct tcmi_ckpt *self, void *data, int count, vfs_method_t *vfs_method)
<<private>> Executes a specified VFS method on the checkpoint file.
static int tcmi_ckpt_write (struct tcmi_ckpt *self, void *data, int count)
<<public>> Writes a specified number of bytes into a checkpoint file.
static int tcmi_ckpt_read (struct tcmi_ckpt *self, void *data, int count)
<<public>> Reads a specified number of bytes from a checkpoint file.
static loff_t tcmi_ckpt_seek (struct tcmi_ckpt *self, loff_t offset, int origin)
<<public>> Seeks in the checkpoint file based on specified offset.
static unsigned long tcmi_ckpt_do_mmap (struct tcmi_ckpt *self, unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags)
<<public>> Helper method that performs a memory mapping on the checkpoint file at its current offset.
static loff_t tcmi_ckpt_page_align (struct tcmi_ckpt *self)
<<public>> Aligns the position in the checkpoint file to page boundary.
static int tcmi_ckpt_fdcache_add (struct tcmi_ckpt *self, int fd, struct file *file)
<<public>> Adds a file descriptor - file object pair into the fd cache.
static int tcmi_ckpt_fdcache_lookup (struct tcmi_ckpt *self, struct file *file)
<<public>> Searches the file descriptor cache for a file.
Variables
int32_t magic
magic number identifying the checkpoint file.
int32_t map_count
total count of virtual memory areas.
int32_t file_count
total count of open files.
enum arch_ids checkpoint_arch
Architecture (hw) of the checkpointed data.
int8_t is_32bit_application
Flag, indicating whether the checkpointed application was 32 bit application (otherwise 64 bit is assumed)
int8_t is_npm
1, if this is checkpoint created as a result of non-preemptive migration request (0 otherwise)
char comm [TASK_COMM_LEN]
Process executable name.
struct tcmi_ckpt __attribute__
Macro Definition Documentation
#define __KERNEL_SYSCALLS__
enables access to system calls from kernel
Definition at line 40 of file tcmi_ckpt.h.
Function Documentation
static int tcmi_ckpt_check_magic (void * buf) inline static
<<public>> Writes signals related stuff into the checkpoint.
<<public>> Reads signals related stuff from the checkpoint. <<public>> Performs a quick check if the specified buffer contains a valid magic number of the checkpoint file.
Parameters
*buf - buffer containing the magic number
Returns
true when valid.
Definition at line 143 of file tcmi_ckpt.h.
References TCMI_CKPT_MAGIC.
 {
     return ((struct tcmi_ckpt_hdr*)buf)->magic == TCMI_CKPT_MAGIC;
 }
static unsigned long tcmi_ckpt_do_mmap (struct tcmi_ckpt * self, unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags) inline static
<<public>> Helper method that performs a memory mapping on the checkpoint file at its current offset.
After that the position is advanced by len bytes.
Parameters
*self - this checkpoint instance
addr - starting address where the
len - length of the region
prot - access rights of the pages included in the memory region
flags - memory region flags (see mm.h)
Returns
new file position or error (< 0)
Definition at line 270 of file tcmi_ckpt.h.
References mdbg, self, and tcmi_ckpt_seek().
 {
     mdbg(INFO4, "Mapping VMA start:%08lx, len %08lx, prot: %08lx, flags: %08lx, pgoff: %08Lx",
          addr, len, prot, flags, self->file->f_pos >> PAGE_SHIFT);
     down_write(&current->mm->mmap_sem);
     addr = do_mmap_pgoff(self->file, addr, len, prot, flags, self->file->f_pos);  //Replaced function do_mmap to do_mmap_pgoff for kernel 3.7.x by Jiri Rakosnik
     up_write(&current->mm->mmap_sem);
     tcmi_ckpt_seek(self, len, 1);
     mdbg(INFO4, "Memory mapping at %08lx, new off %08Lx", addr, self->file->f_pos);
     return addr;
 }
static int tcmi_ckpt_fdcache_add (struct tcmi_ckpt * self, int fd, struct file * file) inline static
<<public>> Adds a file descriptor - file object pair into the fd cache.
This information will be used for later lookup of duplicate file descriptors.
Parameters
*self - this checkpoint instance
fd - file descriptor of the file
*file - file object - used for duplicate file descriptor lookup
Returns
0 upon success
Definition at line 311 of file tcmi_ckpt.h.
References self, and tcmi_fdcache_add().
 {
     return tcmi_fdcache_add(self->fdcache, fd, file);
 }
static int tcmi_ckpt_fdcache_lookup (struct tcmi_ckpt * self, struct file * file) inline static
<<public>> Searches the file descriptor cache for a file.
Parameters
*self - this checkpoint instance
*file - file object to be looked up
Returns
file descriptor of the file or error (< 0)
Definition at line 323 of file tcmi_ckpt.h.
References self, and tcmi_fdcache_lookup().
 {
     return tcmi_fdcache_lookup(self->fdcache, file);
 }
static struct tcmi_ckpt* tcmi_ckpt_get (struct tcmi_ckpt * self) static read
<<public>> Instance accessor, increments the reference counter.
Parameters
*self - pointer to this checkpoint instance
Returns
tcmi_ckpt instance
Definition at line 154 of file tcmi_ckpt.h.
References self.
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static loff_t tcmi_ckpt_page_align (struct tcmi_ckpt * self) inline static
<<public>> Aligns the position in the checkpoint file to page boundary.
This is needed when reading or writing pages.
Parameters
*self - this checkpoint instance
Returns
new file position or error (< 0)
Definition at line 295 of file tcmi_ckpt.h.
References self.
 {
     return vfs_llseek(self->file, (self->file->f_pos + PAGE_SIZE - 1) & PAGE_MASK, 0);
 }
static void tcmi_ckpt_put (struct tcmi_ckpt * self) inline static
<<public>> Releases the instance.
Parameters
*self - pointer to this instance
Definition at line 168 of file tcmi_ckpt.h.
References mdbg, self, and tcmi_fdcache_put().
 {
     if (self && atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying TCMI ckpt, %p", self);
         fput(self->file);
         tcmi_fdcache_put(self->fdcache);
         kfree(self);
     }
 }
static int tcmi_ckpt_read (struct tcmi_ckpt * self, void * data, int count) inline static
<<public>> Reads a specified number of bytes from a checkpoint file.
Parameters
*self - this checkpoint instance
*data - buffer for the data
count - number of bytes to be read
Returns
0 upon successful write of count bytes
Definition at line 233 of file tcmi_ckpt.h.
References mdbg, and tcmi_ckpt_read_write().
 {
     mdbg(INFO3, "CKPT read to %p, count %d bytes", data, count);
     return tcmi_ckpt_read_write(self, data, count, (vfs_method_t*)vfs_read);
 }
static int tcmi_ckpt_read_write (struct tcmi_ckpt * self, void * data, int count, vfs_method_t * vfs_method) inline static
<<private>> Executes a specified VFS method on the checkpoint file.
Parameters
*self - this checkpoint instance
*data - buffer for the data
count - number of bytes to be processed
*vfs_method - VFS method to be executed on the checkpoint and data
Returns
0 upon successful vfs method execution or an error (< 0)
Definition at line 194 of file tcmi_ckpt.h.
References self.
Referenced by tcmi_ckpt_read(), and tcmi_ckpt_write().
 {
     mm_segment_t old_fs;
     int result = 0;
     old_fs = get_fs();
     set_fs(get_ds());
     /* The cast to a user pointer is valid due to the set_fs() */
     result = vfs_method(self->file, (void __user *)data, count, &self->file->f_pos);
     set_fs(old_fs);
     return (result == count ? 0 : -EINVAL);
 }
static loff_t tcmi_ckpt_seek (struct tcmi_ckpt * self, loff_t offset, int origin) inline static
<<public>> Seeks in the checkpoint file based on specified offset.
Parameters
*self - this checkpoint instance
*offset - relative offset
origin - 0 - offset is absolute from file start 1 - offset is relative from current file position 2 - offset is relative from end of file
Returns
new file position or error (< 0)
Definition at line 251 of file tcmi_ckpt.h.
References self.
Referenced by tcmi_ckpt_do_mmap().
 {
     return vfs_llseek(self->file, offset, origin);
 }
static int tcmi_ckpt_write (struct tcmi_ckpt * self, void * data, int count) inline static
<<public>> Writes a specified number of bytes into a checkpoint file.
Parameters
*self - this checkpoint instance
*data - data to be written
count - number of bytes to be written
Returns
0 upon successful write of count bytes
Definition at line 219 of file tcmi_ckpt.h.
References tcmi_ckpt_read_write().
 {
     return tcmi_ckpt_read_write(self, data, count, (vfs_method_t*)vfs_write);
 }
Variable Documentation
enum arch_ids checkpoint_arch
Architecture (hw) of the checkpointed data.
Definition at line 92 of file tcmi_ckpt.h.
char comm[TASK_COMM_LEN]
Process executable name.
Definition at line 98 of file tcmi_ckpt.h.
int32_t file_count
total count of open files.
Definition at line 90 of file tcmi_ckpt.h.
int8_t is_32bit_application
Flag, indicating whether the checkpointed application was 32 bit application (otherwise 64 bit is assumed)
Definition at line 94 of file tcmi_ckpt.h.
int8_t is_npm
1, if this is checkpoint created as a result of non-preemptive migration request (0 otherwise)
Definition at line 96 of file tcmi_ckpt.h.
int32_t magic
magic number identifying the checkpoint file.
Definition at line 86 of file tcmi_ckpt.h.
int32_t map_count
total count of virtual memory areas.
Definition at line 88 of file tcmi_ckpt.h.