Clondike: proxyfs_peer class
proxyfs_peer class
ProxyFS
This class represents connection between two peers allows sending and receiving messages.
Data Structures
struct proxyfs_peer_t
Structure representing peer connection.
Macros
#define PROXYFS_PEER(arg) ((struct proxyfs_peer_t *)arg)
Cast to struct proxyfs_peer_t *.
Enumerations
enum proxyfs_peer_state_t { PEER_CREATED, PEER_CONNECTED, PEER_DISCONNECTED, PEER_DEAD }
Functions
struct proxyfs_peer_t * proxyfs_peer_new (void)
<<public>> Create proxyfs_peer instance
int proxyfs_peer_init (struct proxyfs_peer_t *self)
<<public>> Initialize proxyfs_peer instance
static struct proxyfs_peer_t * proxyfs_peer_get (struct proxyfs_peer_t *self)
<<public>> Gets proxyfs peers reference
void proxyfs_peer_put (struct proxyfs_peer_t *self)
<<public>> Puts proxyfs peers reference
void proxyfs_peer_real_send (struct proxyfs_peer_t *self)
<<public>> Nonblocking send queued messages
int proxyfs_peer_real_recv (struct proxyfs_peer_t *self)
<<public>> Nonblocking recv messages
static proxyfs_peer_state_t proxyfs_peer_get_state (struct proxyfs_peer_t *self)
<<public>> Getter of peer state
static void proxyfs_peer_set_state (struct proxyfs_peer_t *self, proxyfs_peer_state_t state)
<<public>> Setter of peer state
static int proxyfs_peer_clear_msg (struct proxyfs_peer_t *self)
<<public>> Delete received message, and prepare to receiving new one
static struct proxyfs_msg * proxyfs_peer_get_msg (struct proxyfs_peer_t *self)
<<public>> Recv message
static void proxyfs_peer_send_msg (struct proxyfs_peer_t *self, struct proxyfs_msg *msg)
<<public>> Add message to sending queue
int proxyfs_peer_connect (struct proxyfs_peer_t *self, const char *connect_str)
<<public>> Connects to peer
int proxyfs_peer_disconnect (struct proxyfs_peer_t *self)
<<public>> Disconnects peer
int proxyfs_peer_wait (struct proxyfs_peer_t *self)
<<public> Wait on till peer is connected
Detailed Description
This class represents connection between two peers allows sending and receiving messages.
Data Structure Documentation
struct proxyfs_peer_t
Structure representing peer connection.
Definition at line 60 of file proxyfs_peer.h.
Data Fields
spinlock_t enqueue_msg_lock Lock guarding message enqueueing.
struct list_head msg_queue Queue of messages.
struct list_head peers Peers list.
void * recv_buf Buffer for receiving.
size_t recv_start Receiving offset to rec_buf.
atomic_t ref_count reference counter
struct kkc_sock * sock Comunication socket.
wait_queue_t socket_wait For waiting on this socket.
proxyfs_peer_state_t state State of the peer.
Macro Definition Documentation
#define PROXYFS_PEER (arg) ((struct proxyfs_peer_t *)arg)
Cast to struct proxyfs_peer_t *.
Definition at line 87 of file proxyfs_peer.h.
Enumeration Type Documentation
enum proxyfs_peer_state_t
Enumerator
PEER_CREATED
PEER_CONNECTED
PEER_DISCONNECTED
PEER_DEAD
Definition at line 51 of file proxyfs_peer.h.
              {
     PEER_CREATED,
     PEER_CONNECTED,
     PEER_DISCONNECTED,
     PEER_DEAD,
 } proxyfs_peer_state_t;
Function Documentation
static int proxyfs_peer_clear_msg (struct proxyfs_peer_t * self) inline static
<<public>> Delete received message, and prepare to receiving new one
Parameters
self - pointer to proxyfs_peer_t instance
Returns
Zero on success
Definition at line 126 of file proxyfs_peer.h.
References mdbg, MSG_HDR_SIZE, proxyfs_msg_get_size(), and self.
Referenced by proxyfs_task_recv_peers().
 {
     if( self->recv_start >=  MSG_HDR_SIZE &&
             proxyfs_msg_get_size( self->recv_buf ) == self->recv_start){
         self->recv_start = 0;
         return 0;
     }
     else
     {
         mdbg(ERR2, "Attempt to clear incomplete message");
         return -1;
     }
 }
int proxyfs_peer_connect (struct proxyfs_peer_t * self, const char * connect_str)
<<public>> Connects to peer
<<public>> Connects to peer
Parameters
self - pointer to proxyfs_peer_t instance
connect_str - connection string for peer we are connecting to
Returns
0 when success
Definition at line 200 of file proxyfs_peer.c.
References kkc_connect(), mdbg, PEER_CONNECTED, and self.
Referenced by proxyfs_client_thread().
{
     int err;
     if ((err = kkc_connect(&(self->sock), connect_str))) {
           self->sock = NULL;
               mdbg(ERR3, "Failed creating KKC connecting to '%s' error %d", connect_str, err);
           return -1;
     }
     self->state = PEER_CONNECTED;
     return 0;
 }
int proxyfs_peer_disconnect (struct proxyfs_peer_t * self)
<<public>> Disconnects peer
Parameters
self - pointer to proxyfs_peer_t instance
Returns
0 when success
Definition at line 218 of file proxyfs_peer.c.
References kkc_sock_shutdown(), PEER_CONNECTED, PEER_DISCONNECTED, and self.
Referenced by proxyfs_client_thread(), proxyfs_task_free(), and proxyfs_task_handle_dead_peers().
{
     if( self->sock != NULL && self->state == PEER_CONNECTED ) {
         self->state = PEER_DISCONNECTED;
         return kkc_sock_shutdown(self->sock);
     }
     return 0;
 }
static struct proxyfs_peer_t* proxyfs_peer_get (struct proxyfs_peer_t * self) static read
<<public>> Gets proxyfs peers reference
Definition at line 96 of file proxyfs_peer.h.
References self.
Referenced by proxyfs_file_set_peer().
{
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 };
static struct proxyfs_msg* proxyfs_peer_get_msg (struct proxyfs_peer_t * self) static read
<<public>> Recv message
Parameters
self - pointer to proxyfs_peer_t instance
Returns
Pointer to received message or NULL if there is none
Definition at line 144 of file proxyfs_peer.h.
References mdbg, MSG_HDR_SIZE, proxyfs_msg_get_size(), and self.
Referenced by proxyfs_client_handle_msg(), proxyfs_server_handle_msg(), and proxyfs_task_handle_msg().
 {
     if( self->recv_start >=  MSG_HDR_SIZE &&
             proxyfs_msg_get_size( self->recv_buf ) == self->recv_start)
         return (struct proxyfs_msg *)self->recv_buf;
     else{
         mdbg(INFO4, "Attempt to get incomplete message");
         return NULL;
     }
 }
static proxyfs_peer_state_t proxyfs_peer_get_state (struct proxyfs_peer_t * self) inline static
<<public>> Getter of peer state
Definition at line 113 of file proxyfs_peer.h.
Referenced by check_syscall_done(), proxyfs_proxy_file_close(), proxyfs_proxy_file_wait_interruptible(), and proxyfs_task_handle_dead_peers().
{
     return self->state;
 };
int proxyfs_peer_init (struct proxyfs_peer_t * self)
<<public>> Initialize proxyfs_peer instance
Parameters
self - pointer to proxyfs_peer_t instance
Returns
0 on success
Definition at line 65 of file proxyfs_peer.c.
References mdbg, MSG_MAX_SIZE, PEER_CREATED, self, and USE_VMALLOC.
Referenced by proxyfs_peer_new().
 {
     if( MSG_MAX_SIZE >= USE_VMALLOC )
         self->recv_buf = vmalloc( MSG_MAX_SIZE );
     else
         self->recv_buf = kmalloc( MSG_MAX_SIZE, GFP_KERNEL );
     if( self->recv_buf == NULL ){
         mdbg(ERR3, "Allocating recv_buf failed");
         return -1;
     }
     self->recv_start = 0;
     atomic_set(&self->ref_count, 1);
     spin_lock_init(&self->enqueue_msg_lock);
     self->state = PEER_CREATED;
     INIT_LIST_HEAD( & self->msg_queue );
     return 0;
 }
struct proxyfs_peer_t* proxyfs_peer_new (void) read
<<public>> Create proxyfs_peer instance
Returns
new proxyfs_peer instance or NULL on error
Definition at line 42 of file proxyfs_peer.c.
References mdbg, and proxyfs_peer_init().
Referenced by proxyfs_client_thread(), and proxyfs_task_add_to_peers().
 {
     struct proxyfs_peer_t *self;
     self = (struct proxyfs_peer_t *)kmalloc( sizeof(struct proxyfs_peer_t), GFP_KERNEL );
     if( self == NULL ){
         mdbg(ERR3, "Allocating proxyfs_peer failed");
         goto exit0;
     }
     if( proxyfs_peer_init(self) != 0 )
         goto exit1;
     return self;
 exit1:
     kfree(self);
 exit0:
     return NULL;
 }
void proxyfs_peer_put (struct proxyfs_peer_t * self)
<<public>> Puts proxyfs peers reference
<<public>> Puts proxyfs peers reference
Parameters
self - pointer to proxyfs_peer_t instance
Definition at line 87 of file proxyfs_peer.c.
References kkc_sock_getpeername2(), kkc_sock_put(), mdbg, MSG_MAX_SIZE, PEER_DISCONNECTED, self, and USE_VMALLOC.
Referenced by proxyfs_client_thread(), proxyfs_file_destroy(), proxyfs_file_set_peer(), proxyfs_task_free(), and proxyfs_task_handle_dead_peers().
 {
     if (!self)
         return;
     if ( self->sock )
         mdbg(INFO4, "Dropping peer reference %s - ref count: %d", kkc_sock_getpeername2(self->sock), atomic_read(&self->ref_count));
     else
         mdbg(INFO4, "Dropping peer reference - ref count: %d", atomic_read(&self->ref_count));
     if (atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO3, "Freeing peer");
         if( MSG_MAX_SIZE >= USE_VMALLOC )
             vfree(self->recv_buf);
         else
             kfree(self->recv_buf);
         kkc_sock_put(self->sock);
         self->state = PEER_DISCONNECTED;
         self->sock = NULL;
         kfree(self);
         mdbg(INFO3, "Peer released");
     }
 }
int proxyfs_peer_real_recv (struct proxyfs_peer_t * self)
<<public>> Nonblocking recv messages
Parameters
self - pointer to proxyfs_peer_t instance
Returns
1 when complete message is received
Definition at line 149 of file proxyfs_peer.c.
References kkc_sock_getpeername2(), KKC_SOCK_NONBLOCK, kkc_sock_recv(), mdbg, MSG_HDR_SIZE, proxyfs_msg_get_size(), and self.
Referenced by proxyfs_task_recv_peers().
 {
     int result = 0;
     int msg_size;
     if( self->recv_start < MSG_HDR_SIZE ){
         result = kkc_sock_recv( self->sock, self->recv_buf + self->recv_start,
                 MSG_HDR_SIZE - self->recv_start, KKC_SOCK_NONBLOCK);
         if( result == -EAGAIN ){
             //mdbg(INFO3, "No incoming data from %s", kkc_sock_getpeername2(self->sock));
         }
         else if( result > 0 ){
             mdbg(INFO3, "Received %d bytes from %s", result, kkc_sock_getpeername2(self->sock));
             self->recv_start += result;
         }
         else
             mdbg(ERR3, "recv(%s) returned %d", kkc_sock_getpeername2(self->sock), result);
     }
     if( self->recv_start >=  MSG_HDR_SIZE ){
         msg_size = proxyfs_msg_get_size( self->recv_buf );
         if( msg_size == self->recv_start )
             return 1; // Message is complete
         result = kkc_sock_recv( self->sock, self->recv_buf + self->recv_start,
                 msg_size - self->recv_start, KKC_SOCK_NONBLOCK);
         if( result == -EAGAIN ){
             //mdbg(INFO3, "No incoming data from %s", kkc_sock_getpeername2(self->sock));
         }
         else if( result > 0 ){
             mdbg(INFO3, "Received %d bytes from %s", result, kkc_sock_getpeername2(self->sock));
             self->recv_start += result;
             if( self->recv_start == proxyfs_msg_get_size(self->recv_buf) )
                 return 1; // Message is complete
             else
                 return 0;
         }
         else
             mdbg(ERR3, "recv(%s) returned %d", kkc_sock_getpeername2(self->sock), result);
     }
     return result;
 }
void proxyfs_peer_real_send (struct proxyfs_peer_t * self)
<<public>> Nonblocking send queued messages
Parameters
self - pointer to proxyfs_peer_t instance
Definition at line 116 of file proxyfs_peer.c.
References kkc_sock_getpeername2(), mdbg, proxyfs_msg::msg_queue, PEER_DISCONNECTED, proxyfs_msg_destroy(), proxyfs_msg_real_send(), and self.
Referenced by proxyfs_client_loop(), and proxyfs_task_send_peers().
 {
     struct proxyfs_msg *msg;
     int status;
     // Cannot send in non-connected state
     if ( self->state == PEER_DISCONNECTED || !self->sock) {
         mdbg(INFO3, "Skipping real send for peer %s. Not connected (was in state %d)", kkc_sock_getpeername2(self->sock), self->state );
         return;
     }
 send_n: if( ! list_empty( & self->msg_queue ) ){
         msg = list_entry( self->msg_queue.next, struct proxyfs_msg, msg_queue );
         status = proxyfs_msg_real_send( msg, self->sock );
         if( status == 1 ){
             mdbg(INFO3, "Message was send");
             list_del( self->msg_queue.next );
             proxyfs_msg_destroy(msg);
             goto send_n;
         }
         else
             mdbg(INFO3, "Sending returned %d", status);
     }
     else {
         //mdbg(INFO3, "Message queue for %s is empty", kkc_sock_getpeername2(self->sock));
     }
 }
static void proxyfs_peer_send_msg (struct proxyfs_peer_t * self, struct proxyfs_msg * msg) inline static
<<public>> Add message to sending queue
Parameters
self - pointer to proxyfs_peer_t instance
msg - pointer to msg, which will be added to queue
Definition at line 159 of file proxyfs_peer.h.
References proxyfs_msg_header::file_ident, proxyfs_msg::header, mdbg, proxyfs_msg_header::msg_num, proxyfs_msg::msg_queue, and self.
Referenced by proxyfs_client_do_syscall(), proxyfs_client_open_files(), proxyfs_client_send_message(), proxyfs_generic_real_file_open(), proxyfs_pipe_real_file_open(), proxyfs_real_file_close(), proxyfs_real_file_fsync(), proxyfs_real_file_mark_read_request(), proxyfs_server_handle_msg(), proxyfs_server_read_and_write_real_files(), proxyfs_task_send_write_buf(), and proxyfs_tty_real_file_open().
 {
     mdbg(INFO4, "Adding msg %p to a send queue of peer %p", msg, self);
     spin_lock(&self->enqueue_msg_lock);
     list_add_tail( & msg->msg_queue, & self->msg_queue );
     spin_unlock(&self->enqueue_msg_lock);
     mdbg(INFO3, "Queued message %lu for file %lu", msg->header.msg_num, msg->header.file_ident);
 }
static void proxyfs_peer_set_state (struct proxyfs_peer_t * self, proxyfs_peer_state_t state) inline static
<<public>> Setter of peer state
Definition at line 118 of file proxyfs_peer.h.
References proxyfs_peer_t::state.
Referenced by proxyfs_task_recv_peers().
{
     self->state = state;
 };
int proxyfs_peer_wait (struct proxyfs_peer_t * self)
<<public> Wait on till peer is connected
<<public> Wait on till peer is connected
Parameters
self - pointer to proxyfs_peer_t instance
Returns
0 when success
Definition at line 233 of file proxyfs_peer.c.
References kkc_sock_add_wait_queue(), and self.
Referenced by proxyfs_client_thread(), and proxyfs_server_accept().
{
     init_waitqueue_entry( &self->socket_wait, current );
     return kkc_sock_add_wait_queue( self->sock, &self->socket_wait );
 }