Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/director/director.c File Reference
director.c File Reference
#include "director.h"
#include "netlink/comm.h"
#include "netlink/npm_msg.h"
#include "netlink/node_connected_msg.h"
#include "netlink/node_disconnected_msg.h"
#include "netlink/generic_user_message_recv_msg.h"
#include "netlink/generic_user_message_send_handler.h"
#include "netlink/task_exitted_msg.h"
#include "netlink/task_forked_msg.h"
#include "netlink/immigration_request_msg.h"
#include "netlink/immigration_confirmed_msg.h"
#include "netlink/emigration_failed_msg.h"
#include "netlink/migrated_home_msg.h"
#include <linux/module.h>
#include <dbg.h>
Functions
MODULE_LICENSE ("GPL")
int director_npm_check (pid_t pid, uid_t uid, int is_guest, const char *name, const char *__user const *__user argv, const char *__user const *__user envp, int *migman_to_use, int *migrate_home, struct rusage *rusage)
This is the main entry point that can be used by TCMI when it needs to consult user space director.
EXPORT_SYMBOL (director_npm_check)
int director_immigration_request (int slot_index, uid_t uid, const char *name, int *accept)
Request to immigrate process from core node specified by slot_index to this node.
EXPORT_SYMBOL (director_immigration_request)
int director_immigration_confirmed (int slot_index, uid_t uid, const char *name, pid_t local_pid, pid_t remote_pid)
Notification about successful imigration.
EXPORT_SYMBOL (director_immigration_confirmed)
int director_node_connected (const char *address, int slot_index, int auth_data_size, char *auth_data, int *accept)
Called, when a detached node connects to the core node.
EXPORT_SYMBOL (director_node_connected)
int director_node_disconnected (int slot_index, int detached, int reason)
Called, when a peer node disconnets.
EXPORT_SYMBOL (director_node_disconnected)
int director_generic_user_message_recv (int node_id, int is_core_node, int slot_index, int user_data_size, char *user_data)
Called, when a generic user message arrives.
EXPORT_SYMBOL (director_generic_user_message_recv)
void director_register_send_generic_user_message_handler (send_generic_user_message_handler_t handler)
Registers handler for send generic user message command.
EXPORT_SYMBOL (director_register_send_generic_user_message_handler)
int director_task_exit (pid_t pid, int exit_code, struct rusage *rusage)
Called, when a task exits.
EXPORT_SYMBOL (director_task_exit)
int director_task_fork (pid_t pid, pid_t ppid)
Called, when a task forks.
EXPORT_SYMBOL (director_task_fork)
int director_emigration_failed (pid_t pid)
Called, when a task emigration has failed.
EXPORT_SYMBOL (director_emigration_failed)
int director_migrated_home (pid_t pid)
Called, when a task migrates home.
EXPORT_SYMBOL (director_migrated_home)
static int __init init_director_module (void)
static void __exit exit_director_module (void)
module_init (init_director_module)
module_exit (exit_director_module)
Function Documentation
int director_emigration_failed (pid_t pid)
Called, when a task emigration has failed.
Parameters
pid Pid of a new task that failed to emigrate
Returns
0 on success, error code otherwise.
Definition at line 112 of file director.c.
References emigration_failed().
Referenced by tcmi_migcom_emigrate_ccn_npm(), and tcmi_migcom_emigrate_ccn_ppm_p().
{
     return emigration_failed(pid);
 }
int director_generic_user_message_recv (int node_id, int is_core_node, int slot_index, int user_data_size, char * user_data)
Called, when a generic user message arrives.
Parameters
node_id Id of remote node
is_core_node 1 if the slot_index is index of core node manager, 0 if it is indes of detached node manager
slot_index Index in manager that was assigned to this connection
user_data_size Size of user data
user_data User data, or NULL
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 84 of file director.c.
References generic_user_message_recv().
Referenced by tcmi_ccnmigman_process_msg(), and tcmi_penmigman_process_msg().
{
     return generic_user_message_recv(node_id, is_core_node, slot_index, user_data_size, user_data);
 }
int director_immigration_confirmed (int slot_index, uid_t uid, const char * name, pid_t local_pid, pid_t remote_pid)
Notification about successful imigration.
Parameters
slot_index Index of the remote core node manager that requests immigration to this node
uid Uid of user on the remote node that is requesting the migration
name Name of the binary the process (executable) that should be immigrated
local_pid Local pid of the task
remote_pid Pid of the task on core node
Returns
0 on success, error code otherwise
Definition at line 65 of file director.c.
References immigration_confirmed().
Referenced by tcmi_migcom_immigrate().
{
     return immigration_confirmed(slot_index, uid, name, local_pid, remote_pid);
 }
int director_immigration_request (int slot_index, uid_t uid, const char * name, int * accept)
Request to immigrate process from core node specified by slot_index to this node.
Parameters
slot_index Index of the remote core node manager that requests immigration to this node
uid Uid of user on the remote node that is requesting the migration
name Name of the binary the process (executable) that should be immigrated
accept Output param. 0 if immigration is rejected, everything else if it is accepted
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 59 of file director.c.
References immigration_request().
Referenced by tcmi_migcom_immigrate().
{
     return immigration_request(slot_index, uid, name, accept);
 }
int director_migrated_home (pid_t pid)
Called, when a task migrates home.
Parameters
pid Pid of a new task that returned home
Returns
0 on success, error code otherwise.
Definition at line 118 of file director.c.
References migrated_home().
Referenced by tcmi_guesttask_migrateback_p(), and tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg().
{
     return migrated_home(pid);
 }
int director_node_connected (const char * address, int slot_index, int auth_data_size, char * auth_data, int * accept)
Called, when a detached node connects to the core node.
Parameters
address Protocol specific address string of a detached node
slot_index Index in manager that was assigned to this connection
accept Output parameter. 0 if remote node connection should be rejected, otherwise it is accepted
auth_data_size Size of authentication data, if any
auth_data Authentication data, or NULL
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 70 of file director.c.
References node_connected().
Referenced by tcmi_ccnmigman_process_msg().
{
     return node_connected(address, slot_index, auth_data_size, auth_data, accept);
 }
int director_node_disconnected (int slot_index, int detached, int reason)
Called, when a peer node disconnets.
Parameters
slot_index Index in manager that was assigned to this connection
detached Was the disconnected remote peer node was playing role of detached node or of a core node (in the particular connection that was broken)
reason Reason of disconnection - 0 - local request, 1 remote request
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 76 of file director.c.
References minfo, and node_disconnected().
Referenced by tcmi_ccnmigman_stop(), and tcmi_penmigman_stop().
{
     minfo(INFO4, "Node disconnected being called");
     return node_disconnected(slot_index, detached, reason);
 }
int director_npm_check (pid_t pid, uid_t uid, int is_guest, const char * name, const char *__user const *__user argv, const char *__user const *__user envp, int * migman_to_use, int * migrate_home, struct rusage * rusage)
This is the main entry point that can be used by TCMI when it needs to consult user space director.
Checks, whether the process should be non-preemptively migrated to some other node.
Parameters
pid Pid of the process
uid Effective user ID of the process being executed
is_guest 1 if the process is guest
name File name, that is being executed
argv Args of execve
envp Envp of execve
migman_to_use Output parameter.. slot index of migration manager to be used
migrate_home Output param .. should we migrate home?
rusage Resource usage structure of process
Returns
0 on success, if no migration should be performed 1 on success, when a migration should be performed error code otherwise. In case of error, output params are not valid!
Definition at line 20 of file director.c.
References DO_NOT_MIGRATE, MIGRATE, MIGRATE_BACK, minfo, npm_check(), npm_check_full(), REQUIRE_ARGS, REQUIRE_ARGS_AND_ENVP, and REQUIRE_ENVP.
Referenced by tcmi_try_npm_on_exec().
{
     int res, decision, decision_value;
     // TODO: If full is not too expensive do full every time? Or perhaps some "learning" for which processes we should do full immediately and for which not?
     res = npm_check(pid, uid, is_guest, name, &decision, &decision_value, rusage);
     minfo(INFO4, "Npm check [%s]. Decision: %d, Res %d", name, decision, res);
     if ( res )
         return res;
     if ( decision == REQUIRE_ARGS || decision == REQUIRE_ENVP || decision == REQUIRE_ARGS_AND_ENVP ) {
         res = npm_check_full(pid, uid, is_guest, name, argv, envp, &decision, &decision_value);
         minfo(INFO4, "Npm check full [%s]. Decision: %d, Res %d", name, decision, res);
         if ( res )
             return res;
     }
     minfo(INFO4, "Npm result [%s]. Decision %d, migman %d", name, decision, decision_value);
     if ( decision == MIGRATE_BACK ) {
         *migrate_home = 1;
         return 1;
     } else if ( decision == MIGRATE ) {
         *migman_to_use = decision_value;
         return 1;
     } else if ( decision == DO_NOT_MIGRATE ) {
         return 0;
     }
     minfo(ERR1, "How did we get here %d?", decision);
     return 0;
 };
void director_register_send_generic_user_message_handler (send_generic_user_message_handler_t handler)
Registers handler for send generic user message command.
Definition at line 90 of file director.c.
References register_send_generic_user_message_handler().
Referenced by tcmi_register_director_user_message_handler().
{
     register_send_generic_user_message_handler(handler);
 }
int director_task_exit (pid_t pid, int exit_code, struct rusage * rusage)
Called, when a task exits.
Parameters
pid Pid of the task that exists
exit_code Exit code of the task
rusage Resource usage structure of process
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 96 of file director.c.
References task_exitted().
Referenced by tcmi_mighooks_do_exit().
{
     return task_exitted(pid, exit_code, rusage);
 }
int director_task_fork (pid_t pid, pid_t ppid)
Called, when a task forks.
Parameters
pid Pid of a new task that was forked
ppid Pid of a parent task that was forked
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Do not notify directory about its own forks, as this would lead to a lock-out of netlink communications
Definition at line 102 of file director.c.
References is_director_pid(), and task_forked().
Referenced by tcmi_syscall_hooks_post_fork().
{
     /** Do not notify directory about its own forks, as this would lead to a lock-out of netlink communications */
     if ( is_director_pid(ppid) )
         return 0;
     return task_forked(pid, ppid);
 }
static void __exit exit_director_module (void) static
Definition at line 129 of file director.c.
References destroy_director_comm().
{
     destroy_director_comm();
 }
EXPORT_SYMBOL (director_npm_check)
EXPORT_SYMBOL (director_immigration_request)
EXPORT_SYMBOL (director_immigration_confirmed)
EXPORT_SYMBOL (director_node_connected)
EXPORT_SYMBOL (director_node_disconnected)
EXPORT_SYMBOL (director_generic_user_message_recv)
EXPORT_SYMBOL (director_register_send_generic_user_message_handler)
EXPORT_SYMBOL (director_task_exit)
EXPORT_SYMBOL (director_task_fork)
EXPORT_SYMBOL (director_emigration_failed)
EXPORT_SYMBOL (director_migrated_home)
static int __init init_director_module (void) static
Definition at line 124 of file director.c.
References init_director_comm().
{
     init_director_comm();
     return 0;
 }
module_exit (exit_director_module)
module_init (init_director_module)
MODULE_LICENSE ("GPL")