Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/comm/tcmi_transaction.h File Reference
tcmi_transaction.h File Reference
#include <asm/atomic.h>
#include <linux/types.h>
#include <linux/sched.h>
#include <linux/timer.h>
#include <linux/errno.h>
#include <linux/wait.h>
#include <tcmi/lib/tcmi_slotvec.h>
Data Structures
struct tcmi_transaction
Compound structure holding transaction attributes.
Macros
#define TCMI_TRANSACTION_INVAL_ID 0
denotes an invalid transaction ID
#define TCMI_TRANS_FLAGS_ANONYMOUS 0x00000001
Denotes a transaction, where nobody is waiting for the response.
#define TCMI_TRANS_FLAGS_EXPIRED 0x00000002
Denotes an expired transaction that hasn't been completed.
Enumerations
enum tcmi_trans_state_t {
TCMI_TRANSACTION_INIT, TCMI_TRANSACTION_RUNNING, TCMI_TRANSACTION_COMPLETE, TCMI_TRANSACTION_ABORTED,
TCMI_TRANSACTION_INIT, TCMI_TRANSACTION_RUNNING, TCMI_TRANSACTION_COMPLETE, TCMI_TRANSACTION_ABORTED
}
Describes the current state of the transaction:
Functions
struct tcmi_transaction * tcmi_transaction_new (struct tcmi_slotvec *transactions, u_int32_t resp_id, unsigned long timeout)
<<public>> Creates a new transaction.
int tcmi_transaction_start (struct tcmi_transaction *self, int flags)
<<public>> Starts a transaction.
void * tcmi_transaction_abort (struct tcmi_transaction *self)
<<public>> Aborting the transaction.
int tcmi_transaction_complete (struct tcmi_transaction *self, void *context, u_int32_t type_id)
<<public>> Completes a transaction and wakes up the processing thread.
struct tcmi_transaction * tcmi_transaction_lookup (struct tcmi_slotvec *transactions, u_int32_t trans_id)
<<public>> Tries to find a transaction based on its ID.
void tcmi_transaction_put (struct tcmi_transaction *self)
<<public>> Releases the instance - serialized version.
static void tcmi_transaction_lock (struct tcmi_transaction *self)
<<public>> Locks the instance data.
static void tcmi_transaction_unlock (struct tcmi_transaction *self)
<<public>> Unlocks the instance data
static struct tcmi_transaction * tcmi_transaction_get (struct tcmi_transaction *self)
<<public>> Instance accessor.
static u_int32_t tcmi_transaction_id (struct tcmi_transaction *self)
<<public>> Transaction ID accessor.
static tcmi_trans_state_t tcmi_transaction_state (struct tcmi_transaction *self)
<<public>> Transaction state accessor.
static void * tcmi_transaction_context (struct tcmi_transaction *self)
<<public>> Transaction context accessor.
static void tcmi_transaction_set_flags (struct tcmi_transaction *self, int flags)
<<public>> Sets flags in the transaction that denote additional transaction attributes.
static int tcmi_transaction_is_complete (struct tcmi_transaction *self)
<<public>> Checks on a complete transaction.
static int tcmi_transaction_is_aborted (struct tcmi_transaction *self)
<<public>> Checks on aborted transaction.
static int tcmi_transaction_is_running (struct tcmi_transaction *self)
<<public>> Checks on a running transaction.
static int tcmi_transaction_is_anon (struct tcmi_transaction *self)
<<public>> Checks on an anonymous transaction.
static int tcmi_transaction_wait (struct tcmi_transaction *self)
<<public>> Waits on a transaction till it expires or is completed.
static int tcmi_transaction_wait_interruptible (struct tcmi_transaction *self)
<<public>> Waits on a transaction till it expires or is completed, the task can be prematurely woken up by a signal.
Function Documentation
static void* tcmi_transaction_context (struct tcmi_transaction * self) inline static
<<public>> Transaction context accessor.
Parameters
*self - pointer to this transaction instance
Returns
pointer to the context associated with the transaction
Definition at line 238 of file tcmi_transaction.h.
 {
     return self->context;
 }
static struct tcmi_transaction* tcmi_transaction_get (struct tcmi_transaction * self) static read
<<public>> Instance accessor.
increments the reference counter. The user is now guaranteed, that the instance stays in memory while he is using it. Assumes, the access is serialized by means of locking the slot where the instance resides.
Parameters
*self - pointer to this instance
Returns
tcmi_transaction instance
Definition at line 199 of file tcmi_transaction.h.
References self.
 {
     if (self)
         atomic_inc(&self->ref_count);
     return self;
 }
static u_int32_t tcmi_transaction_id (struct tcmi_transaction * self) inline static
<<public>> Transaction ID accessor.
Parameters
*self - pointer to this transaction instance
Returns
transaction ID
Definition at line 213 of file tcmi_transaction.h.
 {
     return self->id;
 }
static int tcmi_transaction_is_aborted (struct tcmi_transaction * self) inline static
<<public>> Checks on aborted transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction has been aborted
Definition at line 275 of file tcmi_transaction.h.
References self, and TCMI_TRANSACTION_ABORTED.
Referenced by tcmi_transaction_wait(), and tcmi_transaction_wait_interruptible().
 {
     return (self->state == TCMI_TRANSACTION_ABORTED);
 }
static int tcmi_transaction_is_anon (struct tcmi_transaction * self) inline static
<<public>> Checks on an anonymous transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction is marked as anonymous.
Definition at line 297 of file tcmi_transaction.h.
References self, and TCMI_TRANS_FLAGS_ANONYMOUS.
 {
     return atomic_read(&self->flags) & TCMI_TRANS_FLAGS_ANONYMOUS;
 }
static int tcmi_transaction_is_complete (struct tcmi_transaction * self) inline static
<<public>> Checks on a complete transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction has been successfully finished
Definition at line 264 of file tcmi_transaction.h.
References self, and TCMI_TRANSACTION_COMPLETE.
Referenced by tcmi_transaction_wait(), and tcmi_transaction_wait_interruptible().
 {
     return (self->state == TCMI_TRANSACTION_COMPLETE);
 }
static int tcmi_transaction_is_running (struct tcmi_transaction * self) inline static
<<public>> Checks on a running transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction is still running..
Definition at line 286 of file tcmi_transaction.h.
References self, and TCMI_TRANSACTION_RUNNING.
 {
     return (self->state == TCMI_TRANSACTION_RUNNING);
 }
static void tcmi_transaction_lock (struct tcmi_transaction * self) inline static
<<public>> Locks the instance data.
Spin lock used - no sleeping allowed!
Parameters
*self - pointer to this transaction instance
Definition at line 174 of file tcmi_transaction.h.
References self.
 {
     spin_lock(&self->t_lock);
 }
static void tcmi_transaction_set_flags (struct tcmi_transaction * self, int flags) inline static
<<public>> Sets flags in the transaction that denote additional transaction attributes.
Valid flags are:
TCMI_TRANS_FLAGS_DELETED - transaction marked for deletion
TCMI_TRANS_FLAGS_ANONYMOUS - transaction is anonymous,
TCMI_TRANS_FLAGS_EXPIRED - timer has expired.
Parameters
*self - pointer to this transaction instance
flags - additional flag setting
Definition at line 253 of file tcmi_transaction.h.
References self.
 {
     atomic_set_mask(flags, &self->flags);
 }
static tcmi_trans_state_t tcmi_transaction_state (struct tcmi_transaction * self) inline static
<<public>> Transaction state accessor.
The transaction should be locked by the caller, so that the transaction state doesn't change when making decisions based on it.
Parameters
*self - pointer to this transaction instance
Returns
curren transaction state
Definition at line 226 of file tcmi_transaction.h.
Referenced by tcmi_transaction_wait(), and tcmi_transaction_wait_interruptible().
 {
     return self->state;
 }
static void tcmi_transaction_unlock (struct tcmi_transaction * self) inline static
<<public>> Unlocks the instance data
Parameters
*self - pointer to this transaction instance
Definition at line 184 of file tcmi_transaction.h.
References self.
 {
     spin_unlock(&self->t_lock);
 }
static int tcmi_transaction_wait (struct tcmi_transaction * self) inline static
<<public>> Waits on a transaction till it expires or is completed.
Parameters
*self - pointer to this transaction instance
Returns
transaction status
Definition at line 310 of file tcmi_transaction.h.
References self, tcmi_transaction_is_aborted(), tcmi_transaction_is_complete(), and tcmi_transaction_state().
 {
     int ret;
     /* Sleep until the transaction times out or completes (response arrival) */
     wait_event(self->wq, (tcmi_transaction_is_aborted(self) ||
                   tcmi_transaction_is_complete(self)));
     ret = tcmi_transaction_state(self);
     return ret;
 }
static int tcmi_transaction_wait_interruptible (struct tcmi_transaction * self) inline static
<<public>> Waits on a transaction till it expires or is completed, the task can be prematurely woken up by a signal.
Parameters
*self - pointer to this transaction instance
Returns
transaction status or -ERESTARTSYS on signal arrival
Definition at line 328 of file tcmi_transaction.h.
References mdbg, self, tcmi_transaction_is_aborted(), tcmi_transaction_is_complete(), and tcmi_transaction_state().
 {
     int ret = 0;
     /* Sleep until the transaction times out or completes (response arrival) */
     ret = wait_event_interruptible(self->wq, (tcmi_transaction_is_aborted(self) ||
                           tcmi_transaction_is_complete(self)));
     if (ret < 0)
         mdbg(INFO3, "Signal arrived");
     else
         ret = tcmi_transaction_state(self);
     return ret;
 }