Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/proxyfs/proxyfs_server.c File Reference
proxyfs_server.c File Reference
#include <proxyfs/buffer.h>
#include <asm/uaccess.h>
#include <linux/fs.h>
#include <linux/file.h>
#include <linux/kthread.h>
#include <kkc/kkc.h>
#include <dbg.h>
#include <proxyfs/proxyfs_ioctl.h>
#include <asm/ioctls.h>
#include <asm/termbits.h>
#include <arch/current/make_syscall.h>
#include "proxyfs_server.h"
#include "proxyfs_real_file.h"
#include "proxyfs_tty_real_file.h"
#include "proxyfs_generic_real_file.h"
#include "proxyfs_pipe_real_file.h"
#include <linux/mount.h>
Macros
#define PROXYFS_SERVER_PRIVATE
#define PROXYFS_SERVER_PROTECTED
#define PROXYFS_REAL_FILE_PROTECTED
Functions
static _syscall3 (long, ioctl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
int proxyfs_server_thread (void *ss)
<<public>>
int proxyfs_server_listen (const char *listen_str)
<<private>> Start listening on socket
int proxyfs_server_accept (void)
<<private>> Try to accept new connection
void proxyfs_server_loop (void)
<<private>> Main server loop
static void proxyfs_server_handle_msg (struct proxyfs_task *self, struct proxyfs_peer_t *peer)
<<private>> Handle message specific for server
void proxyfs_server_read_and_write_real_files (void)
<<private>> Try to write all write buffers to file
void proxyfs_server_release_all (void)
<<public>> <<exported>> Release all files taken from current proccess
EXPORT_SYMBOL_GPL (proxyfs_server_release_all)
static int proxyfs_server_register_poll_callback (struct proxyfs_real_file *file)
struct proxyfs_file_identifier * proxyfs_server_overtake_file (int fd)
<<public>> <<exported>> Make file available trought proxyfs
EXPORT_SYMBOL_GPL (proxyfs_server_overtake_file)
static void proxyfs_server_duplicate_overtaken_file (struct proxyfs_real_file *file, struct task_struct *new_owner)
void proxyfs_server_duplicate_all_parent (struct task_struct *parent, struct task_struct *child)
<<public>> <<exported>> Duplicates all file that were overtaken by a "parent" process and makes child as a owner of duplicates.
EXPORT_SYMBOL_GPL (proxyfs_server_duplicate_all_parent)
void proxyfs_server_poll_queue_proc (struct file *file, wait_queue_head_t *wait_head, struct poll_table_struct *wait_table)
<<private>> Method used for waiting on files, callback for poll structure
static void proxyfs_server_free (struct proxyfs_task *self)
Variables
static int errno
static struct proxyfs_server * self = NULL
Macro Definition Documentation
#define PROXYFS_REAL_FILE_PROTECTED
Definition at line 51 of file proxyfs_server.c.
#define PROXYFS_SERVER_PRIVATE
Definition at line 47 of file proxyfs_server.c.
#define PROXYFS_SERVER_PROTECTED
Definition at line 48 of file proxyfs_server.c.
Function Documentation
static _syscall3 (long , ioctl , unsigned int, fd , unsigned int, cmd , unsigned long, arg) inline static
EXPORT_SYMBOL_GPL (proxyfs_server_release_all)
EXPORT_SYMBOL_GPL (proxyfs_server_overtake_file)
EXPORT_SYMBOL_GPL (proxyfs_server_duplicate_all_parent)
int proxyfs_server_accept (void)
<<private>> Try to accept new connection
Returns
1 if we accepted a new conection (and there can be another one waiting)
Definition at line 108 of file proxyfs_server.c.
References kkc_sock_accept(), KKC_SOCK_NONBLOCK, kkc_sock_register_read_callback(), mdbg, proxyfs_peer_wait(), PROXYFS_TASK, proxyfs_task_add_to_peers(), proxyfs_task_data_ready_callback(), and self.
{
     struct kkc_sock *peer_sock;
     struct proxyfs_peer_t *p;
     int err;
     if ((err = kkc_sock_accept( self->server_sock, &peer_sock,
                              KKC_SOCK_NONBLOCK)) < 0) {
                 //mdbg(INFO4, "No connection, accept would block %d", err);
                 return 0;
         }
     mdbg(INFO3, "Accepted new connection");
     p = proxyfs_task_add_to_peers(PROXYFS_TASK(self), peer_sock); // FIXME osetrit chybu
     if( p != NULL ) {
         kkc_sock_register_read_callback(peer_sock,proxyfs_task_data_ready_callback, self);
         proxyfs_peer_wait(p);
     }
     return 1;
 }
static void proxyfs_server_duplicate_overtaken_file (struct proxyfs_real_file * file, struct task_struct * new_owner) static
Definition at line 441 of file proxyfs_server.c.
References mdbg, PROXYFS_FILE, proxyfs_file_get_file_ident(), proxyfs_real_file_add_shadow(), proxyfs_real_file_destroy(), proxyfs_server_register_poll_callback(), and PROXYFS_TASK.
Referenced by proxyfs_server_duplicate_all_parent().
{
     struct proxyfs_real_file* clone = NULL;
     if ( file->ops == NULL || file->ops->duplicate == NULL ) {
         mdbg(ERR1, "Cannot duplicate file [%lu], it does not have duplicate method defined", proxyfs_file_get_file_ident(PROXYFS_FILE(file)));
         return;
     }
     clone = file->ops->duplicate(file);
     if ( clone == NULL ) {
         mdbg(ERR1, "Failed to duplicate file [%lu].", proxyfs_file_get_file_ident(PROXYFS_FILE(file)));
         return;
     }
     PROXYFS_FILE(clone)->file_identifier.file_owner_pid = task_tgid_vnr(new_owner);
     proxyfs_real_file_add_shadow(clone, new_owner);
     if ( proxyfs_server_register_poll_callback(clone) )
         goto exit;
     list_add_tail( & PROXYFS_FILE(clone)->files, &PROXYFS_TASK(self)->files );
     return;
 exit:
     fput(clone->file);
     proxyfs_real_file_destroy(clone);
 }
static void proxyfs_server_free (struct proxyfs_task * self) static
Definition at line 531 of file proxyfs_server.c.
References kkc_sock_put(), and mdbg.
{
     mdbg(INFO1, "Freeing proxy server");
     kkc_sock_put( PROXYFS_SERVER_TASK(self)->server_sock );
 };
static void proxyfs_server_handle_msg (struct proxyfs_task * self, struct proxyfs_peer_t * peer) static
<<private>> Handle message specific for server
Parameters
self - pointer to this proxyfs_task instance
peer - peer struct with received message
Definition at line 156 of file proxyfs_server.c.
References proxyfs_msg_header::data, proxyfs_msg_header::file_ident, proxyfs_msg::header, IOCTL_ARG_SIZE, ioctl_get_info(), IOCTL_WILL_READ, mdbg, MSG_CLOSE, MSG_CLOSE_RESP, MSG_FSYNC, MSG_FSYNC_RESP, MSG_IOCTL, MSG_IOCTL_RESP, proxyfs_msg_header::msg_num, MSG_OPEN, MSG_OPEN_RESP_FAILED, MSG_READ_REQUEST, MSG_READ_REQUEST_RESP, PROXYFS_FILE_CLOSED, proxyfs_file_get_file_ident(), proxyfs_file_set_status(), proxyfs_msg_compose_new(), proxyfs_msg_new(), proxyfs_peer_get_msg(), proxyfs_peer_send_msg(), PROXYFS_REAL_FILE, proxyfs_real_file_close(), proxyfs_real_file_do_ioctl(), proxyfs_real_file_fsync(), proxyfs_real_file_mark_read_request(), proxyfs_real_file_open(), and proxyfs_task_find_file().
 {
     struct proxyfs_msg *msg = proxyfs_peer_get_msg(peer);
     struct proxyfs_file_t *real_file;
     u_int32_t exitting;
     //long rtn;
     mdbg(INFO1, "Msg%lu DATA: (%p)",msg->header.file_ident ,msg);
     switch( msg->header.msg_num ){
         case MSG_OPEN:
             mdbg(INFO1, "MSG_OPEN ident=%lu", msg->header.file_ident);
             real_file = proxyfs_task_find_file( self, msg->header.file_ident);
             if( real_file != NULL ){
                 mdbg(INFO1, "File found");
                 if( 0 && real_file->peer != NULL )
                     mdbg(INFO1, "Atempt to open already opened file, rejecting...");
                 else{
                     proxyfs_real_file_open( PROXYFS_REAL_FILE(real_file), peer );
                     return;
                 }
             }
             mdbg(INFO1, "File not found");
             msg = proxyfs_msg_new(MSG_OPEN_RESP_FAILED, msg->header.file_ident, 0, NULL );
             proxyfs_peer_send_msg( peer, msg );
             break;
         case MSG_IOCTL:
             mdbg(INFO1, "MSG_IOCTL");
             real_file = proxyfs_task_find_file( self, msg->header.file_ident);
             if( real_file != NULL ){
                 u_int32_t ioctl_info = ioctl_get_info(msg->header.data[0]);
                 char* ioctl_buffer = kmalloc(IOCTL_ARG_SIZE(ioctl_info), GFP_KERNEL);
                 if ( ioctl_buffer ) {
                     u_int32_t result;
                     mdbg(INFO2, "MSG_IOCTL execute command: %d Arg size: %d", msg->header.data[0], IOCTL_ARG_SIZE(ioctl_info));
                     result = proxyfs_real_file_do_ioctl(PROXYFS_REAL_FILE(real_file),
                             msg->header.data[0], (unsigned long)ioctl_buffer);
                     mdbg(INFO2, "MSG_IOCTL performed with result: %d", result);
                     if( IOCTL_WILL_READ(ioctl_info) )
                         msg = proxyfs_msg_compose_new(MSG_IOCTL_RESP, proxyfs_file_get_file_ident(real_file),
                             sizeof(u_int32_t), &result,
                             IOCTL_ARG_SIZE(ioctl_info), ioctl_buffer,
                             (u_int32_t)0);
                     else
                         msg = proxyfs_msg_compose_new(MSG_IOCTL_RESP, proxyfs_file_get_file_ident(real_file),
                             sizeof(u_int32_t), &result,
                             (u_int32_t)0);
                     kfree(ioctl_buffer);
                     if( msg )
                         proxyfs_peer_send_msg( peer, msg );
                     else
                         mdbg(ERR2, "Failed creating response");
                 } else {
                     mdbg(ERR2, "Not enough memory to create ioctl read buffer of size: %d", IOCTL_ARG_SIZE(ioctl_info));
                 }
                 return;
             }
             mdbg(INFO1, "File not found");
             /*msg = proxyfs_msg_new(MSG_OPEN_RESP_FAILED, msg->header.file_ident, 0, NULL );
             proxyfs_peer_send_msg( peer, msg );*/
             break;
         case MSG_CLOSE:
             exitting = msg->header.data[0];
             mdbg(INFO1, "MSG_CLOSE ident=%lu was exitting: %d", msg->header.file_ident, exitting);
             real_file = proxyfs_task_find_file( self, msg->header.file_ident);
             if( real_file != NULL ){
                 mdbg(INFO1, "File found");
                 proxyfs_real_file_close( PROXYFS_REAL_FILE(real_file), peer );
                 if ( !exitting ) {
                     /* If the process was not exitted, the close was ordinary close request made
                        by the process, so we can mark the file closed, since nobody is going to
                        open it again */
                     mdbg(INFO1, "Marking physical file closed");
                     proxyfs_file_set_status( real_file, PROXYFS_FILE_CLOSED );
                 }
                 return;
             }
             msg = proxyfs_msg_new(MSG_CLOSE_RESP, msg->header.file_ident, 0, NULL );
             proxyfs_peer_send_msg( peer, msg );
             break;
         case MSG_FSYNC:
             mdbg(INFO1, "MSG_FSYNC ident=%lu", msg->header.file_ident);
             real_file = proxyfs_task_find_file( self, msg->header.file_ident);
             if( real_file != NULL ){
                 mdbg(INFO1, "File found");
                 proxyfs_real_file_fsync( PROXYFS_REAL_FILE(real_file), peer );
                 return;
             }
             msg = proxyfs_msg_new(MSG_FSYNC_RESP, msg->header.file_ident, 0, NULL );
             proxyfs_peer_send_msg( peer, msg );
             break;
         case MSG_READ_REQUEST:
             mdbg(INFO1, "MSG_READ_REQUEST ident=%lu", msg->header.file_ident);
             real_file = proxyfs_task_find_file( self, msg->header.file_ident);
             if( real_file != NULL ){
                 mdbg(INFO1, "File found");
                 proxyfs_real_file_mark_read_request( PROXYFS_REAL_FILE(real_file), peer );
                 return;
             }
             msg = proxyfs_msg_new(MSG_READ_REQUEST_RESP, msg->header.file_ident, 0, NULL );
             proxyfs_peer_send_msg( peer, msg );
             break;
         default:
             mdbg(ERR3, "Unknown msg number");
     }
 }
int proxyfs_server_listen (const char * listen_str)
<<private>> Start listening on socket
Parameters
*listen_str - kkc address on which server will listen
Returns
zero on succes
Definition at line 92 of file proxyfs_server.c.
References kkc_listen(), kkc_sock_add_wait_queue(), kkc_sock_register_read_callback(), mdbg, proxyfs_task_data_ready_callback(), and self.
{
     int err;
     if ((err = kkc_listen(&self->server_sock, listen_str))) {
               mdbg(ERR3, "Failed creating KKC listening on '%s' error %d", listen_str, err);
           return -1;
     }
         mdbg(INFO3, "Server listening on '%s'", listen_str);
     kkc_sock_register_read_callback(self->server_sock, proxyfs_task_data_ready_callback, self);
     mdbg(INFO3, "Callback registered");
     init_waitqueue_entry(&self->server_sock_wait, current );
     return kkc_sock_add_wait_queue( self->server_sock, &self->server_sock_wait );
 }
void proxyfs_server_loop (void)
<<private>> Main server loop
Definition at line 130 of file proxyfs_server.c.
References mdbg, proxyfs_server_accept(), proxyfs_server_read_and_write_real_files(), PROXYFS_TASK, proxyfs_task_handle_dead_peers(), proxyfs_task_recv_peers(), proxyfs_task_send_buffers(), proxyfs_task_send_peers(), and proxyfs_task_wait_for_data_ready().
{
     while(!kthread_should_stop()){
         proxyfs_task_wait_for_data_ready(PROXYFS_TASK(self));
         // Accept all incoming conections
         while( proxyfs_server_accept() == 1 );
         // Try to recv from all socket.
         proxyfs_task_recv_peers( PROXYFS_TASK(self) );
         //mdbg(INFO3, "STATE: %lx", current->state);
         // Try to write all buffers to files and read from files.
         proxyfs_server_read_and_write_real_files();
         //mdbg(INFO3, "STATE: %lx", current->state);
         proxyfs_task_send_buffers( PROXYFS_TASK(self) );
         //mdbg(INFO3, "STATE: %lx", current->state);
         proxyfs_task_send_peers( PROXYFS_TASK(self) );
         proxyfs_task_handle_dead_peers( PROXYFS_TASK(self) );
     }
     mdbg(INFO1, "Finished server thread");
 }
void proxyfs_server_poll_queue_proc (struct file * file, wait_queue_head_t * wait_head, struct poll_table_struct * wait_table)
<<private>> Method used for waiting on files, callback for poll structure
Parameters
*file - pointer to file in which wait queue this task will be added
*wait_head - pointer to struct used for queueing in wait queues
*wait_table - pointer to poll table
Definition at line 508 of file proxyfs_server.c.
References mdbg, PROXYFS_FILE, proxyfs_file_get_file_ident(), and PROXYFS_TASK.
 {
     struct hacked_poll_table *table = (struct hacked_poll_table *)wait_table;
     struct proxyfs_real_file_waiter *waiter;
     waiter = (struct proxyfs_real_file_waiter *)kmalloc( sizeof(struct proxyfs_real_file_waiter), GFP_KERNEL);
     if( waiter == NULL ){
         mdbg(ERR3, "Waiter allocation failed");
         return;
     }
     waiter->wait_head = wait_head;
     // File keeps track of all its waiters in its "waiter_list" member
     list_add( &waiter->waiters_list, &table->real_file->waiters_list );
     init_waitqueue_entry(&waiter->wait, PROXYFS_TASK(self)->tsk);
     // The waiter itself is registered to a file wait queue, this establishing relation between the physical file and the proxy_real_file
     add_wait_queue(wait_head, &waiter->wait);
     mdbg(INFO3, "Server added to wait queue on file %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(table->real_file)));
 }
void proxyfs_server_read_and_write_real_files (void)
<<private>> Try to write all write buffers to file
Definition at line 271 of file proxyfs_server.c.
References file_count, mdbg, MSG_WRITE, MSG_WRITE_RESP, PROXYFS_FILE, PROXYFS_FILE_ALL_READ, PROXYFS_FILE_CLOSED, proxyfs_file_get_file_ident(), proxyfs_file_get_status(), PROXYFS_FILE_READ_EOF, proxyfs_file_set_status(), proxyfs_msg_compose_new(), proxyfs_peer_send_msg(), PROXYFS_REAL_FILE, proxyfs_real_file_destroy(), proxyfs_real_file_read(), proxyfs_real_file_write(), PROXYFS_TASK, and self.
{
     struct list_head *l, *nxt;
     struct proxyfs_msg *msg;
     struct proxyfs_real_file *real_file;
     struct proxyfs_peer_t *peer;
     u_int32_t length;
     down( & self->files_sem ); // Serialize access
     list_for_each_safe( l, nxt, & PROXYFS_TASK(self)->files ){
         // up( & self.files_sem ); // Adding new file can wait :-)
         real_file = PROXYFS_REAL_FILE( list_entry(l, struct proxyfs_file_t, files) );
         peer = PROXYFS_FILE(real_file)->peer;
         mdbg(INFO4, "Processing %lu, status %x", proxyfs_file_get_file_ident(PROXYFS_FILE(real_file)),
             proxyfs_file_get_status( PROXYFS_FILE(real_file), 0xffff ) );
         // write to file
         if( (length = proxyfs_real_file_write(real_file)) > 0 ){
             mdbg(INFO3, "Sending WRITE_RESP msg for file %lu, ack %d",
                 proxyfs_file_get_file_ident(PROXYFS_FILE(real_file)), length );
             if ( peer ) {
                 msg = proxyfs_msg_compose_new(MSG_WRITE_RESP, proxyfs_file_get_file_ident(PROXYFS_FILE(real_file)),
                     sizeof(u_int32_t), &length, 0 );
                 proxyfs_peer_send_msg( peer, msg );
             }
         }
         // Close file if it should be closed
         if( proxyfs_file_get_status( PROXYFS_FILE(real_file), PROXYFS_FILE_CLOSED ) &&
             proxyfs_file_get_status( PROXYFS_FILE(real_file), PROXYFS_FILE_ALL_READ )){
             struct file* physical_file = real_file->file;
             mdbg(INFO3, "Closing file %lu. Ref count: %ld", proxyfs_file_get_file_ident(PROXYFS_FILE(real_file)), file_count(real_file->file) );
             //l = l->next;
             list_del( & PROXYFS_FILE(real_file)->files ); // Delete from list
             proxyfs_real_file_destroy( real_file );
             kfree( real_file );
             // Close file AFTER we de-list proxy file.. fput may actually destroy the file, if we hold last reference
             fput( physical_file );
             continue;
         }
         // read from file
         if ( peer && !proxyfs_file_get_status( PROXYFS_FILE(real_file), PROXYFS_FILE_READ_EOF ) &&
                 proxyfs_real_file_read(real_file) == 0 ){ // EOF
             msg = proxyfs_msg_compose_new(MSG_WRITE, proxyfs_file_get_file_ident(PROXYFS_FILE(real_file)), 0);
             proxyfs_peer_send_msg(peer , msg );
             proxyfs_file_set_status( PROXYFS_FILE(real_file), PROXYFS_FILE_READ_EOF );
         }
         // down( & self.files_sem );
     }
     up( & self->files_sem );
 }
static int proxyfs_server_register_poll_callback (struct proxyfs_real_file * file) static
Definition at line 346 of file proxyfs_server.c.
References mdbg, and proxyfs_server_poll_queue_proc().
Referenced by proxyfs_server_duplicate_overtaken_file(), and proxyfs_server_overtake_file().
{
     struct hacked_poll_table table;
     // Poll hack
     INIT_LIST_HEAD(& file->waiters_list );
     table.parent._qproc = proxyfs_server_poll_queue_proc;                  //Added underscore by Jiri Rakosnik for new kernel 3.7.x but warning in source of kernel is
                                                                         // Do not touch the structure directly, use the access functions * poll_does_not_wait() and poll_requested_events() instead.
     table.real_file = file;
     if (file->file->f_op && file->file->f_op->poll ) {
         file->file->f_op->poll( file->file, (struct poll_table_struct*)&table );
     } else {
         mdbg(ERR3, "Poll unavailable! File op: %p", file->file->f_op);
         if ( file->file->f_vfsmnt)
             //mdbg(ERR3, "Mount point: %s", file->file->f_vfsmnt->mnt_devname);
         return -EINVAL;
     }
     return 0;
 }
Variable Documentation
int errno static
Definition at line 43 of file proxyfs_server.c.
struct proxyfs_server* self = NULL static
Definition at line 59 of file proxyfs_server.c.
Referenced by proxyfs_server_accept(), proxyfs_server_duplicate_all_parent(), proxyfs_server_listen(), proxyfs_server_overtake_file(), proxyfs_server_read_and_write_real_files(), proxyfs_server_release_all(), and proxyfs_server_thread().