Clondike: control filesystem
control filesystem
TCMI
This <<singleton>> class represents TCMI control filesystem.
Modules
tcmi_ctlfs_entry class
This class represents a generic entry in the tcmi control file system.
Data Structures
struct tcmi_ctlfs
A compound structure that contains all internal data of TCMI ctlfs.
Macros
#define TCMI_PERMS_DIR (S_IRWXU | S_IRGRP | S_IXGRP)
Preferred directory rights.
#define TCMI_PERMS_FILE_W (S_IWUSR)
Preferred write file rights.
#define TCMI_PERMS_FILE_R (S_IRUSR | S_IRGRP)
Preferred read file rights.
#define TCMI_PERMS_FILE_RW (TCMI_PERMS_FILE_R | TCMI_PERMS_FILE_W)
Preferred read/write file rights.
Functions
static void init_once (void *foo)
static int init_inodecache (void)
static void destroy_inodecache (void)
static int tcmi_ctlfs_fill_super (struct super_block *sb, void *data, int silent)
<<private>> Sets up super block and instantiates the root directory.
static struct dentry * tcmi_ctlfs_get_super (struct file_system_type *fst, int flags, const char *devname, void *data)
<<private>> Super block as assigned a nonexistent device and the super block is obtained via mount_single().
static int __init tcmi_ctlfs_init (void)
Module initialization.
static void __exit tcmi_ctlfs_exit (void)
module cleanup
struct tcmi_ctlfs_entry * tcmi_ctlfs_get_root (void)
<<public>> Root entry accessor.
void tcmi_ctlfs_put_root (void)
<<public>> Releases the root directory.
Variables
static struct kmem_cache * ctlfs_inode_cachep
static struct super_operations s_ops
static struct tcmi_ctlfs self
<<singleton>> instance initialization
Detailed Description
This <<singleton>> class represents TCMI control filesystem.
The idea behind the filesystem is very similar to what we have in sysfs. The reason why a separate filesystem has been created is that TCMI doesn't fit among regular device drivers which is the primary use of sysfs.
Similarly to sysfs, we provide a mechanism that allows any object in TCMI to create an interface presented to user space. The user is able to notify the object via reading/writing a file.
An entity in TCMI ctlfs is called an 'entry'. Currently there are entries that represent a file , a directory and a symbolic link .
Data Structure Documentation
struct tcmi_ctlfs
A compound structure that contains all internal data of TCMI ctlfs.
This is for internal use only.
Definition at line 65 of file tcmi_ctlfs.h.
Data Fields
struct file_system_type fs_type A forward declaration describing this filesystem type.
struct tcmi_ctlfs_entry * root_dir forward declaration of the root directory of the TCMI control filesystem
struct super_block * sb Filesystem super block object.
struct vfsmount * vfs_mnt forward declaration of the mount object of TCMI control filesystem
struct semaphore vfs_mnt_sem a semaphore that protects the vfs_mount variable against concurrent accesses.
This is important when issuing tcmi_ctlfs_get_root/tcmi_ctlfs_put_root
Macro Definition Documentation
#define TCMI_PERMS_DIR (S_IRWXU | S_IRGRP | S_IXGRP)
Preferred directory rights.
Definition at line 87 of file tcmi_ctlfs.h.
Referenced by tcmi_ccnman_init_ctlfs_dirs(), tcmi_man_init_ctlfs_dirs(), tcmi_migman_init_ctlfs_dirs(), tcmi_sock_new(), and tcmi_task_init().
#define TCMI_PERMS_FILE_R (S_IRUSR | S_IRGRP)
Preferred read file rights.
Definition at line 91 of file tcmi_ctlfs.h.
Referenced by tcmi_ccnmigman_init_ctlfs_files(), tcmi_migman_init_ctlfs_files(), tcmi_sock_new(), tcmi_task_init(), and tcmi_task_set_remote_pid().
#define TCMI_PERMS_FILE_RW (TCMI_PERMS_FILE_R | TCMI_PERMS_FILE_W)
Preferred read/write file rights.
Definition at line 93 of file tcmi_ctlfs.h.
Referenced by tcmi_module_init().
#define TCMI_PERMS_FILE_W (S_IWUSR)
Preferred write file rights.
Definition at line 89 of file tcmi_ctlfs.h.
Referenced by tcmi_ccnman_init_ctlfs_files(), tcmi_man_init_ctlfs_files(), tcmi_migman_init_ctlfs_files(), tcmi_penman_init_ctlfs_files(), and tcmi_penmigman_init_ctlfs_files().
Function Documentation
static void destroy_inodecache (void) static
Definition at line 192 of file tcmi_ctlfs.c.
References ctlfs_inode_cachep.
Referenced by tcmi_ctlfs_exit().
 {
     kmem_cache_destroy(ctlfs_inode_cachep);
 }
static int init_inodecache (void) static
Definition at line 183 of file tcmi_ctlfs.c.
References ctlfs_inode_cachep, and init_once().
Referenced by tcmi_ctlfs_init().
 {
     ctlfs_inode_cachep = kmem_cache_create("ctlfs_inode_cache", sizeof(struct inode), 0, (SLAB_RECLAIM_ACCOUNT| SLAB_MEM_SPREAD), init_once);
     if (ctlfs_inode_cachep == NULL)
         return -ENOMEM;
     return 0;
 }
static void init_once (void * foo) static
Definition at line 151 of file tcmi_ctlfs.c.
Referenced by init_inodecache().
{
          struct inode *inode = (struct inode *) foo;
          inode_init_once(inode);
  }
static void __exit tcmi_ctlfs_exit (void) static
module cleanup
Definition at line 270 of file tcmi_ctlfs.c.
References destroy_inodecache(), and minfo.
 {
     minfo(INFO3, "Unregistering TCMI control filesystem");
     destroy_inodecache();
     unregister_filesystem(&self.fs_type);
 }
static int tcmi_ctlfs_fill_super (struct super_block * sb, void * data, int silent) static
<<private>> Sets up super block and instantiates the root directory.
This method is called only once through out the super block life.
Parameters
sb - pointer to the super block
*data - custom data supplied when reading the superblock(not used)
silent - required by VFS, no idea what it means.
Returns
0 upon success
Definition at line 215 of file tcmi_ctlfs.c.
References mdbg, s_ops, TCMI_CTLFS_MAGIC, and tcmi_ctlfs_rootdir_new().
Referenced by tcmi_ctlfs_get_super().
 {
     sb->s_blocksize = PAGE_CACHE_SIZE;
     sb->s_blocksize_bits = PAGE_CACHE_SHIFT;
     sb->s_magic = TCMI_CTLFS_MAGIC;
     sb->s_op = &s_ops;
     self.sb = sb;
 mdbg(INFO4, "TMPDBG: GOING TO REQUEST ROOT");
     self.root_dir = tcmi_ctlfs_rootdir_new(sb);
 mdbg(INFO4, "TMPDBG: ROOT SUCCEEDED");
     return 0;
 }
struct tcmi_ctlfs_entry* tcmi_ctlfs_get_root (void) read
<<public>> Root entry accessor.
If the filesystem has not been activated yet, a kernel mount is performed. The kernel mount in turn ensures instantiation of the root directory. A user might have already mounted the filesystem from userspace. This is not a problem as we allow only one instance of the filesystem in memory(enforced by mount_single()), so only a reference counter of the root directory and the associated superblock is incremented. The last thread that releases the last reference to the super block and eventually to the root directory causes the whole filesystem to be released. See tcmi_ctlfs_kill_super() for details on this.
If the filesystem is already active (the vfs_mnt is valid), the mount reference count is adjusted.
It is necessary to protect the vfs_mnt variable as it can be manipulated by other threads that might issue tcmi_ctlfs_put_root() and release the vfs mount from under us.
Returns
pointer to the root entry (reference counter adjusted by tcmi_ctlfs_entry_get()) or NULL
Definition at line 76 of file tcmi_ctlfs.c.
References mdbg, minfo, and tcmi_ctlfs_entry_get().
Referenced by tcmi_module_init().
 {
     down(&self.vfs_mnt_sem);
     /* when the VFS mount is currently inactive we have to create
      * a new one */
     if (!self.vfs_mnt) {
         mdbg(INFO3, "Mounting");
         self.vfs_mnt = kern_mount(&self.fs_type);
         if (IS_ERR(self.vfs_mnt)) {
             minfo(ERR1, "Could not mount!");
             self.vfs_mnt = NULL;
             /* if the mount failed, the root directory
              * instance doesn't exist too, so we don't
              * need to explicitely delete it*/
             self.root_dir = NULL;
         }
     }
     /* VFS mount still active, just increment its ref. counter */
     else
         mntget(self.vfs_mnt);
     up(&self.vfs_mnt_sem);
     mdbg(INFO3, "sb c_count=%d, s_active=%d", self.sb->s_count,
          atomic_read(&self.sb->s_active));
     //mdbg(INFO3, "mount mnt_count=%d", atomic_read(&self.vfs_mnt->mnt_count));
     return tcmi_ctlfs_entry_get(self.root_dir);
 }
static struct dentry* tcmi_ctlfs_get_super (struct file_system_type * fst, int flags, const char * devname, void * data) static read
<<private>> Super block as assigned a nonexistent device and the super block is obtained via mount_single().
The kernel function mount_single() ensures that only 1 instance of the filesystem can be mounted at a time. Custom method to fill the super block is passed as parameter.
Parameters
*fst - points to the file system type, that is being mounted
flags -
*devname - device name, on which the file system resides (it has no meaning here)
*data - pointer to private filesystem data - not used
Returns
- pointer to the dentry object that has been created
Definition at line 243 of file tcmi_ctlfs.c.
References tcmi_ctlfs_fill_super().
 {
     return mount_single(fst, flags, data, tcmi_ctlfs_fill_super);
 }
static int __init tcmi_ctlfs_init (void) static
Module initialization.
Returns
- status of the register_filesystem() call
Definition at line 254 of file tcmi_ctlfs.c.
References init_inodecache(), and minfo.
 {
     int error;
     minfo(INFO3, "Registering TCMI control filesystem");
     error = init_inodecache();
     if (error)
         return error;
     error = register_filesystem(&self.fs_type);
     return error;
 }
void tcmi_ctlfs_put_root (void)
<<public>> Releases the root directory.
<<public>> Releases the root directory.
VFS takes care of releasing the object in case their reference count reaches 0. We need to take care of setting the mnt to NULL.
The last 2 steps don't need to be semaphore protected as we are working on copies of both pointers and we wanted to protect the access to mnt only. If anybody tries to get a root from now on a new VFS mount will be created. If the root directory has been also destroyed, the read_super method takes care of instantiating a new super block along with the root directory.
Definition at line 117 of file tcmi_ctlfs.c.
References mdbg, and tcmi_ctlfs_entry_put().
Referenced by tcmi_module_exit().
 {
     struct vfsmount *cur_vfs_mnt;
     struct tcmi_ctlfs_entry *cur_root_dir;
     mdbg(INFO3, "sb c_count=%d, s_active=%d", self.sb->s_count,
          atomic_read(&self.sb->s_active));
     //mdbg(INFO3, "mount mnt_count=%d", atomic_read(&self.vfs_mnt->mnt_count));
     /* mdbg(INFO3, "root d_count=%d", atomic_read(&self.root_dir->super.dentry->d_count));*/
     down(&self.vfs_mnt_sem);
     cur_vfs_mnt = self.vfs_mnt;
     cur_root_dir = self.root_dir;
     /* If we are the last thread accesing the kernel mount */
     //Replaced construction reading mnt_count which it isn't included in vfsmount structure to function may_umount which return 1 when fs may be umounted | by Jiri Rakosnik
   if(may_umount(self.vfs_mnt))
     self.vfs_mnt = NULL;
     up(&self.vfs_mnt_sem);
     /* no locking needed since working on copies of both
      * pointers */
     tcmi_ctlfs_entry_put(cur_root_dir);
     mntput(cur_vfs_mnt);
 }
Variable Documentation
struct kmem_cache* ctlfs_inode_cachep static
Definition at line 149 of file tcmi_ctlfs.c.
Referenced by destroy_inodecache(), and init_inodecache().
struct super_operations s_ops static
Initial value:
= {
    .statfs = simple_statfs,
}
Definition at line 198 of file tcmi_ctlfs.c.
Referenced by tcmi_ctlfs_fill_super().
struct tcmi_ctlfs self static
Initial value:
= {
    .root_dir = NULL,
    .vfs_mnt_sem = __SEMAPHORE_INITIALIZER( self.vfs_mnt_sem, 1 ),
    .vfs_mnt = NULL,
    .sb = NULL,
    .fs_type = {
        .owner          = THIS_MODULE,
        .name           = "tcmi_ctlfs",
        .mount          = tcmi_ctlfs_get_super,
        .kill_sb        = kill_litter_super,
    },
}
<<singleton>> instance initialization
Definition at line 280 of file tcmi_ctlfs.c.