Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/migration/tcmi_npm_params.c File Reference
tcmi_npm_params.c File Reference
#include "tcmi_npm_params.h"
#include <asm/uaccess.h>
#include <linux/module.h>
#include <dbg.h>
Functions
static int count (const char __user *const __user *argv, int max)
static int copy_strings (int argc, const char __user *const __user *argv, struct tcmi_npm_params *params, int *remaining_max_length)
int extract_tcmi_npm_params (struct tcmi_npm_params *params, const char *filename, const char __user *const __user *argv, const char __user *const __user *envp)
Extracts npm params from user space passed params to a tcmi structure.
Function Documentation
static int copy_strings (int argc, const char __user *const __user * argv, struct tcmi_npm_params * params, int * remaining_max_length) static
Definition at line 38 of file tcmi_npm_params.c.
References tcmi_npm_params::data, NPM_DATA_SIZE_MAX, and reserve_array_length().
Referenced by extract_tcmi_npm_params().
 {
     int ret = 0, i;
     (*remaining_max_length) -= reserve_array_length(argc); // Reserve space for the array pointing to strings
     for (i = 0; i < argc; i++ ) {
         const char __user *str;
         int len, err;
         if (get_user(str, (argv+i)) ||
                 !(len = strnlen_user(str, *remaining_max_length))) {
             ret = -EFAULT;
             goto out;
         } // Retrieved len includes trailing zero
         if ( *remaining_max_length < len)  {
             ret = -E2BIG;
             goto out;
         }
         err = copy_from_user(params->data + NPM_DATA_SIZE_MAX - (*remaining_max_length), str, len);
         if (err) {
             ret = -EFAULT;
             goto out;
         }
         *remaining_max_length -= len;
     }
 out:
     return ret;
 }
static int count (const char __user *const __user * argv, int max) static
Definition at line 17 of file tcmi_npm_params.c.
Referenced by extract_tcmi_npm_params().
 {
     int i = 0;
     if (argv != NULL) {
         for (;;) {
             const char __user * p;
             if (get_user(p, argv))
                 return -EFAULT;
             if (!p)
                 break;
             argv++;
             if(++i > max)
                 return -E2BIG;
             cond_resched();
         }
     }
     return i;
 }
int extract_tcmi_npm_params (struct tcmi_npm_params * params, const char * filename, const char __user *const __user * argv, const char __user *const __user * envp)
Extracts npm params from user space passed params to a tcmi structure.
Parameters
params Structure to be filled with extracted data
Returns
0 on success
Definition at line 72 of file tcmi_npm_params.c.
References tcmi_npm_params::argsc, copy_strings(), count(), tcmi_npm_params::envpc, tcmi_npm_params::file_name, fixup_npm_params_pointers(), mdbg, NPM_DATA_SIZE_MAX, NPM_FILENAME_MAX, and tcmi_npm_params::used_data_length.
{
     int remaining_max = NPM_DATA_SIZE_MAX;
     int err;
     if ( !params )
         return -EINVAL;
     if ( strlen(filename)+1 > NPM_FILENAME_MAX )
         return -EINVAL;
     strcpy(params->file_name, filename);
     params->argsc = count(argv, NPM_DATA_SIZE_MAX/sizeof(void*));
     params->envpc = count(envp, NPM_DATA_SIZE_MAX/sizeof(void*));
     if ( (err = copy_strings(params->argsc, argv, params, &remaining_max)) )
         return err;
     if ( (err = copy_strings(params->envpc, envp, params, &remaining_max)) )
         return err;
     params->used_data_length = NPM_DATA_SIZE_MAX - remaining_max;
     mdbg(INFO4, "Filename: %s, Argc: %d, Evnpc: %d Used data: %d", params->file_name, params->argsc, params->envpc, params->used_data_length);
   return fixup_npm_params_pointers(params);
 };