Clondike: tcmi_penmigman class
tcmi_penmigman class
tcmi_migman class
TCMI PEN migration manager controls migrating tasks for a particular CCN-PEN pair and resides as the name describes - on a PEN.
Data Structures
struct tcmi_penmigman
A compound structure that holds all current shadow processes and other migration related data.
Macros
#define TCMI_PENMIGMAN(migman) ((struct tcmi_penmigman *)migman)
Casts to the CCN migration manager.
Functions
static int tcmi_penmigman_init_ctlfs_files (struct tcmi_migman *self)
<<private>> Creates the static files described here .
static void tcmi_penmigman_stop_ctlfs_files (struct tcmi_migman *self)
<<private>> Unregisters and releases all control files.
static int tcmi_penmigman_migrate_all_home (void *obj, void *data)
Forward declaration.
static void tcmi_penmigman_free (struct tcmi_migman *self)
static void tcmi_penmigman_stop (struct tcmi_migman *self, int remote_requested)
<<private>> Called on stop request
static void tcmi_penmigman_send_signal (struct tcmi_migman *self, int pid, siginfo_t *info)
<<public>> Send dignal to process
static void tcmi_penmigman_process_msg (struct tcmi_migman *self, struct tcmi_msg *m)
<<private>> Processes a TCMI message m.
struct tcmi_migman * tcmi_penmigman_new (struct kkc_sock *sock, u_int32_t pen_id, struct tcmi_slot *manager_slot, struct tcmi_ctlfs_entry *root, struct tcmi_ctlfs_entry *migproc, const char namefmt[],...)
<<public>> TCMI PEN migration manager constructor.
int tcmi_penmigman_auth_ccn (struct tcmi_penmigman *self, int auth_data_length, char *auth_data)
<<public>> Tries authenticating itself at the CCN that it is connected to.
static struct fs_mount_params * tcmi_penmigman_get_mount_params (struct tcmi_penmigman *self)
<<public>> Getter of mount params structure.
Variables
static struct tcmi_migman_ops penmigman_ops
Migration manager operations that support polymorphism.
Detailed Description
TCMI PEN migration manager controls migrating tasks for a particular CCN-PEN pair and resides as the name describes - on a PEN.
Basic message handling capabilities are used from the generic migration manager .
There are specific tasks that it needs to accomplish:
authenticate at the CCN that it is connected to
accept migrating tasks
Data Structure Documentation
struct tcmi_penmigman
A compound structure that holds all current shadow processes and other migration related data.
Definition at line 61 of file tcmi_penmigman.h.
Data Fields
struct tcmi_ctlfs_entry * f_mighome_all TCMI ctlfs - migrate-home-all file.
struct fs_mount_params mount_params Mount params to be used when starting processes from associated CCN.
struct tcmi_migman super parent class instance.
Macro Definition Documentation
#define TCMI_PENMIGMAN (migman) ((struct tcmi_penmigman *)migman)
Casts to the CCN migration manager.
Definition at line 71 of file tcmi_penmigman.h.
Referenced by tcmi_migcom_immigrate(), tcmi_penman_connect(), tcmi_penmigman_init_ctlfs_files(), tcmi_penmigman_new(), tcmi_penmigman_process_msg(), and tcmi_penmigman_stop_ctlfs_files().
Function Documentation
int tcmi_penmigman_auth_ccn (struct tcmi_penmigman * self, int auth_data_length, char * auth_data)
<<public>> Tries authenticating itself at the CCN that it is connected to.
<<public>> Tries authenticating itself at the CCN that it is connected to.
Parameters
*self - pointer to this migration manager instance
auth_data_size - optional authentication data string length
auth_data - optional authentication data string, or NULL
Returns
0 if successfully, -EINVAL otherwise
Definition at line 108 of file tcmi_penmigman.c.
References mdbg, minfo, req, resp, tcmi_authenticate_msg_new_tx(), TCMI_MIGMAN, TCMI_MIGMAN_CONNECTED, tcmi_migman_sock(), tcmi_migman_state(), tcmi_migman_transactions(), tcmi_msg_put(), tcmi_msg_send_and_receive(), and tcmi_penmigman_process_msg().
Referenced by tcmi_penman_connect().
 {
     /* authentication request and response*/
     struct tcmi_msg *req, *resp;
     /* Build the request */
     if ( !(req = tcmi_authenticate_msg_new_tx(tcmi_migman_transactions(TCMI_MIGMAN(self)), TCMI_MIGMAN(self)->pen_id, ARCH_CURRENT, auth_data, auth_data_length)) ) {
         mdbg(ERR3, "Error creating the authentication request");
         goto exit0;
     }
     if (tcmi_msg_send_and_receive(req, tcmi_migman_sock(TCMI_MIGMAN(self)),
                       &resp) < 0) {
         minfo(ERR3, "Failed to send the authentication request!!");
         goto exit1;
     }
     if (!resp) {
         minfo(ERR3, "No authentication response from CCN - nothing arrived");
         goto exit1;
     }
     mdbg(INFO3, "Authentication response  is now to be handled");
     tcmi_penmigman_process_msg(TCMI_MIGMAN(self), resp);
     /* fall through is ok, the response message has been discarded
      * by process_msg */
  exit1:
     /* release the message */
     tcmi_msg_put(req);
  exit0:
     return (tcmi_migman_state(TCMI_MIGMAN(self)) == TCMI_MIGMAN_CONNECTED ?
         0 : -EINVAL);
 }
static void tcmi_penmigman_free (struct tcmi_migman * self) inline static
TODO: We cannot do it so simply as this method won't get called if there are tasks pointing to the migman.. either tasks should not keep reference to migman or we better we have to introduce some 'stop' method, that is invoked before the free is performed. This stop will migrate everything back and so we wouldn't need to migrate back here, but we'd do that in the stop method
Definition at line 219 of file tcmi_penmigman.c.
{
     /* struct tcmi_penmigman *self_ppn  = TCMI_PENMIGMAN(self); */
     /**
         TODO: We cannot do it so simply as this method won't get called if there are tasks pointing to the migman.. either tasks should not keep reference to migman
         or we better we have to introduce some 'stop' method, that is invoked before the free is performed. This stop will migrate everything back and so we wouldn't need
         to migrate back here, but we'd do that in the stop method
      */
     //tcmi_penmigman_migrate_all_home(self, NULL);
     /* TODO: Wait till all migrations are finished? */
 }
static struct fs_mount_params* tcmi_penmigman_get_mount_params (struct tcmi_penmigman * self) static read
<<public>> Getter of mount params structure.
Definition at line 84 of file tcmi_penmigman.h.
Referenced by tcmi_migcom_immigrate().
{
     return &self->mount_params;
 };
static int tcmi_penmigman_init_ctlfs_files (struct tcmi_migman * self) static
<<private>> Creates the static files described here .
Parameters
*self - pointer to this migration manager instance
Returns
0 upon success
Definition at line 154 of file tcmi_penmigman.c.
References tcmi_penmigman::f_mighome_all, mdbg, self, tcmi_ctlfs_intfile_new(), TCMI_PENMIGMAN, tcmi_penmigman_migrate_all_home(), and TCMI_PERMS_FILE_W.
 {
     struct tcmi_penmigman *self_pen = TCMI_PENMIGMAN(self);
     mdbg(INFO4, "Creating TCMI ctlfs files - PEN migman");
     if (!(self_pen->f_mighome_all =
           tcmi_ctlfs_intfile_new(self->d_migman, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_penmigman_migrate_all_home,
                     sizeof(int),"migrate-home-all")))
         goto exit0;
     return 0;
 exit0:
     return -EINVAL;
 }
static int tcmi_penmigman_migrate_all_home (void * obj, void * data) static
Forward declaration.
<<private>> Emigrates all contained tasks back to home node The method is asynchrounous.
Migrate home requests are issued to all contained tasks, but we do not wait till the migration back is performed.
Parameters
*obj - pointer to this migration manager instance
*data - not used
Definition at line 195 of file tcmi_penmigman.c.
References mdbg, self, tcmi_migcom_migrate_home_ppm_p(), TCMI_MIGMAN, tcmi_slot_entry, tcmi_slot_for_each, tcmi_slotvec_for_each_used_slot, tcmi_slotvec_lock(), tcmi_slotvec_unlock(), and tcmi_task_local_pid().
Referenced by tcmi_penmigman_init_ctlfs_files(), and tcmi_penmigman_stop().
{
     struct tcmi_task* task;
     struct tcmi_slot *slot;
     tcmi_slot_node_t* node;
     struct tcmi_migman *self  = TCMI_MIGMAN(obj);
     mdbg(INFO3, "Penmigman migrate all home requested");
     /* we protect the iteration so that migration backs do not interfere with the iteration */
     tcmi_slotvec_lock(self->tasks);
     /* Iterate over all managed tasks */
     tcmi_slotvec_for_each_used_slot(slot, self->tasks) {
         tcmi_slot_for_each(node, slot) {
             task = tcmi_slot_entry(node, struct tcmi_task, node);
             mdbg(INFO3, "Sending migrate home request to task: local_pid=%d", tcmi_task_local_pid(task));
             tcmi_migcom_migrate_home_ppm_p(tcmi_task_local_pid(task));
         };
     };
     tcmi_slotvec_unlock(self->tasks);
     mdbg(INFO3, "Penmigman migrate all home done");
     return 0;
 }
struct tcmi_migman* tcmi_penmigman_new (struct kkc_sock * sock, u_int32_t pen_id, struct tcmi_slot * manager_slot, struct tcmi_ctlfs_entry * root, struct tcmi_ctlfs_entry * migproc, const char namefmt[], ...) read
<<public>> TCMI PEN migration manager constructor.
The initialization is accomplished exactly in this order:
create new instance
delegates all remaining intialization work to the generic manager.
Parameters
*sock - socket where the new PEN is registering
pen_id - PEN identifier
*root - directory where the migration manager should create its files and directories
*migproc - directory where the migrated process will have their info
namefmt - nameformat string for the main manager directory name (printf style)
... - variable arguments
Returns
new TCMI PEN manager instance or NULL
Definition at line 67 of file tcmi_penmigman.c.
References args, mdbg, minfo, penmigman_ops, TCMI_MIGMAN, tcmi_migman_init(), TCMI_PENMIGMAN, and UNKNOWN.
Referenced by tcmi_penman_connect().
 {
     struct tcmi_penmigman *migman;
     va_list args;
     minfo(INFO2, "Creating new TCMI PEN migration manager");
     if (!(migman = TCMI_PENMIGMAN(kmalloc(sizeof(struct tcmi_penmigman),
                           GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for CCM migration manager");
         goto exit0;
     }
     va_start(args, namefmt);
     if (tcmi_migman_init(TCMI_MIGMAN(migman), sock, 0, pen_id, UNKNOWN, manager_slot, root, migproc,
                  &penmigman_ops, namefmt, args) < 0) {
         mdbg(ERR3, "TCMI PEN migman initializtion failed!");
         va_end(args);
         goto exit1;
     }
     va_end(args);
     return TCMI_MIGMAN(migman);
     /* error handling */
  exit1:
     kfree(migman);
  exit0:
     return NULL;
 }
static void tcmi_penmigman_process_msg (struct tcmi_migman * self, struct tcmi_msg * m) static
<<private>> Processes a TCMI message m.
The message is disposed afterwords.
Parameters
*self - pointer to this migration manager instance
*m - pointer to a message to be processed
Definition at line 271 of file tcmi_penmigman.c.
References director_generic_user_message_recv(), info, mdbg, minfo, fs_mount_params::mount_device, fs_mount_params::mount_options, tcmi_penmigman::mount_params, fs_mount_params::mount_type, pid, resp, tcmi_authenticate_resp_msg::result_code, TCMI_AUTHENTICATE_RESP_MSG, tcmi_authenticate_resp_msg_arch(), tcmi_authenticate_resp_msg_ccn_id(), TCMI_AUTHENTICATE_RESP_MSG_ID, tcmi_authenticate_resp_msg_mount_params(), tcmi_err_procmsg_new_tx(), TCMI_GENERIC_USER_MSG, TCMI_GENERIC_USER_MSG_ID, tcmi_generic_user_msg_node_id(), tcmi_generic_user_msg_user_data(), tcmi_generic_user_msg_user_data_size(), TCMI_GUEST_STARTED_PROCMSG_ID, tcmi_migcom_immigrate(), TCMI_MIGMAN_CONNECTED, tcmi_migman_set_state(), tcmi_migman_slot_index(), tcmi_migman_sock(), TCMI_MSG_FLG_SET_ERR, tcmi_msg_id(), tcmi_msg_put(), tcmi_msg_req_id(), tcmi_msg_send_anonymous(), TCMI_P_EMIGRATE_MSG, TCMI_P_EMIGRATE_MSG_ID, tcmi_p_emigrate_msg_reply_pid(), TCMI_PENMIGMAN, tcmi_penmigman_send_signal(), TCMI_SIGNAL_MSG, and TCMI_SIGNAL_MSG_ID.
Referenced by tcmi_penmigman_auth_ccn().
 {
     struct tcmi_authenticate_resp_msg *auth_msg;
     struct tcmi_generic_user_msg *user_msg;
     struct tcmi_msg *resp;
     struct tcmi_penmigman *self_pen  = TCMI_PENMIGMAN(self);
     int err;
     mdbg(INFO4, "Processing message (%p)", m);
     if ( !m )
         return;
     switch(tcmi_msg_id(m)) {
         case TCMI_AUTHENTICATE_RESP_MSG_ID:
             auth_msg = TCMI_AUTHENTICATE_RESP_MSG(m);
             if ( auth_msg->result_code == 0) {
                 minfo(INFO1, "Authentication at CCN successful..");
                 self->peer_arch_type = tcmi_authenticate_resp_msg_arch(auth_msg);
                 self->ccn_id = tcmi_authenticate_resp_msg_ccn_id(auth_msg);
                 self_pen->mount_params = *tcmi_authenticate_resp_msg_mount_params(auth_msg);
                 minfo(INFO1, "received mount_params - type: %s device: %s options: %s",
                         self_pen->mount_params.mount_type, self_pen->mount_params.mount_device,
                         self_pen->mount_params.mount_options);
                 tcmi_migman_set_state(self, TCMI_MIGMAN_CONNECTED);
             } else {
                 minfo(INFO1, "Authentication at CCN failed with error=%d..", auth_msg->result_code);
             }
             break;
         case TCMI_MSG_FLG_SET_ERR(TCMI_AUTHENTICATE_RESP_MSG_ID):
             minfo(INFO1, "Authentication at CCN failed, error received..");
             break;
         case TCMI_SIGNAL_MSG_ID:
             tcmi_penmigman_send_signal(self, TCMI_SIGNAL_MSG(m)->pid,
                     &TCMI_SIGNAL_MSG(m)->info);
             break;
         case TCMI_P_EMIGRATE_MSG_ID:
             minfo(INFO1, "Physical emigrate message has arrived..");
             if (tcmi_migcom_immigrate(m, self) < 0) {
                 minfo(ERR3, "Error immigrating process");
                 if (!(resp = tcmi_err_procmsg_new_tx(TCMI_GUEST_STARTED_PROCMSG_ID, tcmi_msg_req_id(m), -EINVAL, tcmi_p_emigrate_msg_reply_pid(TCMI_P_EMIGRATE_MSG(m))))) {
                       minfo(ERR3, "Failed to send error response");
                 } else {
                       tcmi_msg_send_anonymous(resp, tcmi_migman_sock(self));
                 }
             }
             break;
         case TCMI_GENERIC_USER_MSG_ID:
             user_msg = TCMI_GENERIC_USER_MSG(m);
             minfo(INFO1, "User message arrived in pen.");
             err = director_generic_user_message_recv(tcmi_generic_user_msg_node_id(user_msg), 0, tcmi_migman_slot_index(self), tcmi_generic_user_msg_user_data_size(user_msg), tcmi_generic_user_msg_user_data(user_msg));
             if ( err ) {
                 mdbg(ERR3, "Error in processing user message %d", err);
             }
             break;
         default:
             minfo(INFO1, "Unexpected message ID %x, no handler available.",
             tcmi_msg_id(m));
             break;
     }
     /* release the message */
     tcmi_msg_put(m);
 }
static void tcmi_penmigman_send_signal (struct tcmi_migman * self, int pid, siginfo_t * info) static
<<public>> Send dignal to process
Parameters
*self - pointer to this penmigman instance
pid - signal target pid
*info - info for signal to be send
Definition at line 249 of file tcmi_penmigman.c.
References mdbg, and task_find_by_pid().
Referenced by tcmi_penmigman_process_msg().
 {
     int sig;
     struct task_struct *task;
     rcu_read_lock();
     task = task_find_by_pid(pid);
     rcu_read_unlock();
     sig = info->si_signo;
     mdbg(INFO2, "Sending signal %d to task %p (PID %d)", sig, task, pid);
     if(task)
         send_sig_info(sig, info, task);
 }
static void tcmi_penmigman_stop (struct tcmi_migman * self, int remote_requested) static
<<private>> Called on stop request
Emigrates all contained tasks back to home node (asynchronously - only emigration requests are issued in context of this method)
Parameters
*self - pointer to this migration manager instance
Definition at line 238 of file tcmi_penmigman.c.
References director_node_disconnected(), tcmi_migman_slot_index(), and tcmi_penmigman_migrate_all_home().
{
     tcmi_penmigman_migrate_all_home(self, NULL);
     director_node_disconnected(tcmi_migman_slot_index(self), 0, remote_requested);
 }
static void tcmi_penmigman_stop_ctlfs_files (struct tcmi_migman * self) static
<<private>> Unregisters and releases all control files.
Parameters
*self - pointer to this migration manager instance
Definition at line 177 of file tcmi_penmigman.c.
References tcmi_penmigman::f_mighome_all, mdbg, tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), and TCMI_PENMIGMAN.
 {
     struct tcmi_penmigman *self_pen = TCMI_PENMIGMAN(self);
     mdbg(INFO3, "Destroying  TCMI ctlfs files - PEN migman");
     tcmi_ctlfs_file_unregister(self_pen->f_mighome_all);
     tcmi_ctlfs_entry_put(self_pen->f_mighome_all);
 }
Variable Documentation
struct tcmi_migman_ops penmigman_ops static
Initial value:
= {
    .init_ctlfs_files = tcmi_penmigman_init_ctlfs_files,
    .stop_ctlfs_files = tcmi_penmigman_stop_ctlfs_files,
    .stop = tcmi_penmigman_stop,
    .process_msg = tcmi_penmigman_process_msg,
}
Migration manager operations that support polymorphism.
Definition at line 342 of file tcmi_penmigman.c.
Referenced by tcmi_penmigman_new().