Clondike: fs_mounter Struct Reference
fs_mounter Struct Reference
Class handling the filesystem mounting, that is performed before the process restart If there is no fs_mounter registered, no mounting is performed and the filesystem is expected to be already mounted (or not required)
#include <fs_mounter.h>
Data Fields
struct fs_mount_params params
int(* global_mount)(struct fs_mounter *self, int16_t fsuid, int16_t fsgid)
Called, in context of a kernel process, it can make mounts to a global namespace.
int(* private_mount)(struct fs_mounter *self, int16_t fsuid, int16_t fsgid)
Called, in context of a new process, in its private namespace.
void(* free)(struct fs_mounter *self)
Custom free method.
Detailed Description
Class handling the filesystem mounting, that is performed before the process restart If there is no fs_mounter registered, no mounting is performed and the filesystem is expected to be already mounted (or not required)
Definition at line 11 of file fs_mounter.h.
Field Documentation
void(* fs_mounter::free)(struct fs_mounter *self)
Custom free method.
Definition at line 18 of file fs_mounter.h.
Referenced by free_mounter(), new_9p_fs_mounter(), and new_9p_global_fs_mounter().
int(* fs_mounter::global_mount)(struct fs_mounter *self, int16_t fsuid, int16_t fsgid)
Called, in context of a kernel process, it can make mounts to a global namespace.
Definition at line 14 of file fs_mounter.h.
Referenced by new_9p_fs_mounter(), new_9p_global_fs_mounter(), and tcmi_migcom_immigrate().
struct fs_mount_params fs_mounter::params
Definition at line 12 of file fs_mounter.h.
Referenced by chroot_to_mount(), global_9p_mount(), mount_9p_fs(), new_9p_fs_mounter(), and new_9p_global_fs_mounter().
int(* fs_mounter::private_mount)(struct fs_mounter *self, int16_t fsuid, int16_t fsgid)
Called, in context of a new process, in its private namespace.
Definition at line 16 of file fs_mounter.h.
Referenced by new_9p_fs_mounter(), new_9p_global_fs_mounter(), and tcmi_migcom_migrated_task().
The documentation for this struct was generated from the following file:
C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/migration/fs/fs_mounter.h