Clondike: tcmi_signal_msg class
tcmi_signal_msg class
tcmi_msg class
This class represents a test message and is intended to be used as a skeleton when implementing new messages in the TCMI protocol.
Data Structures
struct tcmi_signal_msg
Compound structure, inherits from tcmi_msg_class.
Macros
#define TCMI_SIGNAL_MSG_DSC TCMI_MSG_DSC(TCMI_SIGNAL_MSG_ID, tcmi_signal_msg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
#define TCMI_SIGNAL_MSGTIMEOUT 5*HZ
Skeleton message transaction timeout set to 5 seconds.
#define TCMI_SIGNAL_MSG(m) ((struct tcmi_signal_msg*)m)
Casts to the tcmi_signal_msg instance.
Functions
static int tcmi_signal_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_signal_msg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
struct tcmi_msg * tcmi_signal_msg_new (pid_t pid, siginfo_t *info)
<<public>> Construktor for sending with initialization
struct tcmi_signal_msg __attribute__ ((__packed__))
struct tcmi_msg * tcmi_signal_msg_new_rx (u_int32_t msg_id)
<<public>> Skeleton message constructor for receiving.
struct tcmi_msg * tcmi_signal_msg_new_tx (struct tcmi_slotvec *transactions)
<<public>> Skeleton message constructor for transferring.
Variables
static struct tcmi_msg_ops skel_msg_ops
Message operations that support polymorphism.
Detailed Description
This class represents a test message and is intended to be used as a skeleton when implementing new messages in the TCMI protocol.
To implement a new message following steps need to be done:
Implement the constructors
new_tx - functionality to allocate a message for transfer based on custom parameters specific to each message type. Use init_tx for initialization of the super class instance data
new_rx - same, but for reception, therefore, no parameters are specified. If needed compare the supplied message ID, with the official message ID assigned to this type of message.
new_rx_err - A custom build of error message can be specified or some generic new_rx_err message constructor can be used.
Choose a message identifier and append it to a proper group in tcmi_messages_id.h
Declare a new message descriptor, append it into tcmi_messages_dsc.h
Implement custom operations if needed.
Data Structure Documentation
struct tcmi_signal_msg
Compound structure, inherits from tcmi_msg_class.
Definition at line 58 of file tcmi_signal_msg.h.
Data Fields
siginfo_t info Siginfo structure (we can use directly this structure as it is padded to be exactly 128 bytes)
pid_t pid Target PID.
struct tcmi_msg super parent class instance
Macro Definition Documentation
#define TCMI_SIGNAL_MSG (m) ((struct tcmi_signal_msg*)m)
Casts to the tcmi_signal_msg instance.
Definition at line 84 of file tcmi_signal_msg.h.
Referenced by tcmi_penmigman_process_msg(), tcmi_signal_msg_new(), tcmi_signal_msg_new_rx(), tcmi_signal_msg_new_tx(), tcmi_signal_msg_recv(), and tcmi_signal_msg_send().
#define TCMI_SIGNAL_MSG_DSC TCMI_MSG_DSC(TCMI_SIGNAL_MSG_ID, tcmi_signal_msg_new_rx, NULL)
Message descriptor for the factory class, there is no error handling as this is the starting request.
Definition at line 79 of file tcmi_signal_msg.h.
#define TCMI_SIGNAL_MSGTIMEOUT 5*HZ
Skeleton message transaction timeout set to 5 seconds.
Definition at line 81 of file tcmi_signal_msg.h.
Referenced by tcmi_signal_msg_new_tx().
Function Documentation
struct tcmi_signal_msg __attribute__ ((__packed__))
struct tcmi_msg * tcmi_signal_msg_new (pid_t pid, siginfo_t * info) read
<<public>> Construktor for sending with initialization
Definition at line 168 of file tcmi_signal_msg.c.
References pid, TCMI_SIGNAL_MSG, and tcmi_signal_msg_new_tx().
Referenced by tcmi_shadowtask_do_signal().
 {
     struct tcmi_msg *self;
     self = tcmi_signal_msg_new_tx(NULL);
     if(self){
         TCMI_SIGNAL_MSG(self)->pid = pid;
         memcpy(&TCMI_SIGNAL_MSG(self)->info, info, sizeof(siginfo_t));
     }
     return self;
 }
struct tcmi_msg* tcmi_signal_msg_new_rx (u_int32_t msg_id) read
<<public>> Skeleton message constructor for receiving.
<<public>> Skeleton message constructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this error message instance.
Returns
a new error message or NULL.
Definition at line 51 of file tcmi_signal_msg.c.
References mdbg, skel_msg_ops, TCMI_MSG, tcmi_msg_init_rx(), TCMI_SIGNAL_MSG, and TCMI_SIGNAL_MSG_ID.
 {
     struct tcmi_signal_msg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_SIGNAL_MSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_SIGNAL_MSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_SIGNAL_MSG(kmalloc(sizeof(struct tcmi_signal_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate signal message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_SIGNAL_MSG_ID, &skel_msg_ops)) {
         mdbg(ERR3, "Error initializing signal message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_signal_msg_new_tx (struct tcmi_slotvec * transactions) read
<<public>> Skeleton message constructor for transferring.
<<public>> Skeleton message constructor for transferring.
The skeleton message can have a transaction associated with it = there is a response expected for this message by the sender. Therefore, the user specifies the transaction slot vector.
When performing the generic tx init, the response message ID is specified (TCMI_RESPSIGNAL_MSG_ID) so that it will be associated with the transaction
Parameters
*transactions - storage for the new transaction(NULL for one-way messages)
Returns
a new error ready for the transfer or NULL.
Definition at line 95 of file tcmi_signal_msg.c.
References mdbg, skel_msg_ops, TCMI_MSG, tcmi_msg_init_tx(), TCMI_SIGNAL_MSG, TCMI_SIGNAL_MSG_ID, TCMI_SIGNAL_MSGTIMEOUT, and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_signal_msg_new().
 {
     struct tcmi_signal_msg *msg;
     if (!(msg = TCMI_SIGNAL_MSG(kmalloc(sizeof(struct tcmi_signal_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate signal message");
         goto exit0;
     }
     /* Initialize the message for transfer */
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_SIGNAL_MSG_ID, &skel_msg_ops,
                  transactions, 0,//TCMI_SIGNALRESP_MSG_ID,
                  TCMI_SIGNAL_MSGTIMEOUT, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing signal message");
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_signal_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 134 of file tcmi_signal_msg.c.
References tcmi_signal_msg::info, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_signal_msg::pid, and TCMI_SIGNAL_MSG.
 {
     struct tcmi_signal_msg *self_msg = TCMI_SIGNAL_MSG(self);
     int err;
     err = kkc_sock_recv(sock, &self_msg->pid,
                 sizeof(self_msg->pid) + sizeof(self_msg->info), KKC_SOCK_BLOCK);
     mdbg(INFO2, "Signal message received(%d)", err);
     return 0;
 }
static int tcmi_signal_msg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 154 of file tcmi_signal_msg.c.
References tcmi_signal_msg::info, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_signal_msg::pid, and TCMI_SIGNAL_MSG.
 {
     struct tcmi_signal_msg *self_msg = TCMI_SIGNAL_MSG(self);
     int err;
     err = kkc_sock_send(sock, &self_msg->pid,
                 sizeof(self_msg->pid) + sizeof(self_msg->info), KKC_SOCK_BLOCK);
     mdbg(INFO2, "Signal message send(%d)", err);
     return 0;
 }
Variable Documentation
struct tcmi_msg_ops skel_msg_ops static
Initial value:
= {
    .recv = tcmi_signal_msg_recv,
    .send = tcmi_signal_msg_send
}
Message operations that support polymorphism.
Definition at line 182 of file tcmi_signal_msg.c.
Referenced by tcmi_signal_msg_new_rx(), and tcmi_signal_msg_new_tx().