Clondike: Signal sending
Signal sending
tcmi_guest_rpc class
A <<singleton>> class that is executing RPC on PEN side.
Functions
long tcmi_guest_rpc_sys_rt_sigqueueinfo (unsigned rpc_num, long params[6])
Rt_sigqueueinfo system call RPC.
Detailed Description
A <<singleton>> class that is executing RPC on PEN side.
Function Documentation
long tcmi_guest_rpc_sys_rt_sigqueueinfo (unsigned rpc_num, long params[6])
Rt_sigqueueinfo system call RPC.
Parameters
rpc_num - RPC number
params - pointer to array with RPC parameters - PID, signal and pointer to siginfo structure
Returns
RPC return value
Definition at line 40 of file tcmi_guest_signal_rpc.c.
References mdbg, tcmi_msg_put(), TCMI_RPCRESP_PROCMSG, tcmi_rpcresp_procmsg_get_response(), and tcmi_rpcresp_procmsg_rtn().
 {
     struct tcmi_msg *r; long rtn;
     r = tcmi_rpcresp_procmsg_get_response(rpc_num,
             2*sizeof(long), params,
             sizeof(siginfo_t), (void*)params[2], 0); // TODO: It was meant like that, not like below, right? (m.s.)
             //sizeof(siginfo_t), (void*)params[3], 0);
     if(r == NULL){
         mdbg(ERR3, "Response message hasn't arrived");
         return -EAGAIN;
     }
     rtn = tcmi_rpcresp_procmsg_rtn( TCMI_RPCRESP_PROCMSG(r) );
     tcmi_msg_put(r);
     return rtn;
 }