Clondike: tcmi_ppm_p_migr_back_shadowreq_procmsg class
tcmi_ppm_p_migr_back_shadowreq_procmsg class
tcmi_procmsg class
This class represents a message that is sent by a shadow task to the guest task as a request to migrate the process back to CCN.
Data Structures
struct tcmi_ppm_p_migr_back_shadowreq_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Macros
#define TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_DSC TCMI_MSG_DSC(TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID, tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
#define TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG(m) ((struct tcmi_ppm_p_migr_back_shadowreq_procmsg*)m)
Casts to the tcmi_ppm_p_migr_back_shadowreq_procmsg instance.
Functions
struct tcmi_msg * tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx (u_int32_t msg_id)
<<public>> Shadow request for migration back rx constructor.
struct tcmi_msg * tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx (pid_t dst_pid)
<<public>> Shadow request for migration back tx constructor.
Detailed Description
This class represents a message that is sent by a shadow task to the guest task as a request to migrate the process back to CCN.
Data Structure Documentation
struct tcmi_ppm_p_migr_back_shadowreq_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Definition at line 21 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.h.
Data Fields
struct tcmi_procmsg super parent class instance
Macro Definition Documentation
#define TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG (m) ((struct tcmi_ppm_p_migr_back_shadowreq_procmsg*)m)
Casts to the tcmi_ppm_p_migr_back_shadowreq_procmsg instance.
Definition at line 37 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.h.
Referenced by tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx(), and tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx().
#define TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_DSC TCMI_MSG_DSC(TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID, tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
Definition at line 33 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.h.
Function Documentation
struct tcmi_msg* tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx (u_int32_t msg_id) read
<<public>> Shadow request for migration back rx constructor.
<<public>> Shadow request for migration back rx constructor.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this error message instance.
Returns
a new error message or NULL.
Definition at line 25 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.c.
References mdbg, ppm_p_migr_back_shadowreq_procmsg_ops, TCMI_MSG, TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG, TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID, TCMI_PROCMSG, and tcmi_procmsg_init_rx().
 {
     struct tcmi_ppm_p_migr_back_shadowreq_procmsg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG(kmalloc(sizeof(struct tcmi_ppm_p_migr_back_shadowreq_procmsg),
                                  GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate migrate back shadow request message");
         goto exit0;
     }
     /* Initialize the message for receiving. */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID,
                  &ppm_p_migr_back_shadowreq_procmsg_ops)) {
         mdbg(ERR3, "Error initializing migrate back shadow request message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx (pid_t dst_pid) read
<<public>> Shadow request for migration back tx constructor.
Generates a one-way request message
Parameters
dst_pid - PID of the target process that will receive this message
Returns
a new message ready for the transfer or NULL.
Definition at line 65 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.c.
References mdbg, ppm_p_migr_back_shadowreq_procmsg_ops, TCMI_MSG, TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG, TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID, TCMI_PROCMSG, tcmi_procmsg_init_tx(), and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_shadowtask_migrateback_ppm_p().
 {
     struct tcmi_ppm_p_migr_back_shadowreq_procmsg *msg;
     if (!(msg = TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG(kmalloc(sizeof(struct tcmi_ppm_p_migr_back_shadowreq_procmsg),
                                  GFP_KERNEL)))) {
         mdbg(ERR3, "Can't create migrate back shadow request message");
         goto exit0;
     }
     /* Initialize the message for transfer, no transaction
      * required, no timout, no response ID */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID,
                  &ppm_p_migr_back_shadowreq_procmsg_ops,
                  dst_pid, 1,
                  NULL, 0, 0, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing migrate back shadow request message");
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }