Clondike: tcmi_ppm_p_migr_back_guestreq_procmsg class
tcmi_ppm_p_migr_back_guestreq_procmsg class
tcmi_procmsg class
This class represents a message that is sent by guest task to the shadow task as a request(announcement) to migrate the process back to CCN.
Data Structures
struct tcmi_ppm_p_migr_back_guestreq_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Macros
#define TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_DSC TCMI_MSG_DSC(TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID, tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
#define TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG(m) ((struct tcmi_ppm_p_migr_back_guestreq_procmsg*)m)
Casts to the tcmi_ppm_p_migr_back_guestreq_procmsg instance.
Functions
static int tcmi_ppm_p_migr_back_guestreq_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_ppm_p_migr_back_guestreq_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Sends the PPM_P migrate back guest request
static void tcmi_ppm_p_migr_back_guestreq_procmsg_free (struct tcmi_procmsg *self)
<<private>> Frees custom message resources.
struct tcmi_msg * tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx (u_int32_t msg_id)
<<public>> Guest request for migration back rx constructor.
struct tcmi_msg * tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx (pid_t dst_pid, char *ckpt_name)
<<public>> Guest request for migration back tx constructor.
static char * tcmi_ppm_p_migr_back_guestreq_procmsg_ckpt_name (struct tcmi_ppm_p_migr_back_guestreq_procmsg *self)
Checkpoint name accessor.
static int tcmi_ppm_p_migr_back_shadowreq_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_ppm_p_migr_back_shadowreq_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Sends the PPM_P migrate back shadow request
Variables
static struct tcmi_procmsg_ops ppm_p_migr_back_guestreq_procmsg_ops
Message operations that support polymorphism.
struct
tcmi_ppm_p_migr_back_guestreq_procmsg __attribute__
static struct tcmi_procmsg_ops ppm_p_migr_back_shadowreq_procmsg_ops
Message operations that support polymorphism.
Detailed Description
This class represents a message that is sent by guest task to the shadow task as a request(announcement) to migrate the process back to CCN.
Data Structure Documentation
struct tcmi_ppm_p_migr_back_guestreq_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Definition at line 48 of file tcmi_ppm_p_migr_back_guestreq_procmsg.h.
Data Fields
char * ckpt_name name of the checkpoint file.
int32_t size size of the checkpoint name in bytes (including trailing zero)
struct tcmi_procmsg super parent class instance
Macro Definition Documentation
#define TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG (m) ((struct tcmi_ppm_p_migr_back_guestreq_procmsg*)m)
Casts to the tcmi_ppm_p_migr_back_guestreq_procmsg instance.
Definition at line 74 of file tcmi_ppm_p_migr_back_guestreq_procmsg.h.
Referenced by tcmi_ppm_p_migr_back_guestreq_procmsg_free(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx(), tcmi_ppm_p_migr_back_guestreq_procmsg_recv(), tcmi_ppm_p_migr_back_guestreq_procmsg_send(), and tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg().
#define TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_DSC TCMI_MSG_DSC(TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID, tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
Definition at line 70 of file tcmi_ppm_p_migr_back_guestreq_procmsg.h.
Function Documentation
static char* tcmi_ppm_p_migr_back_guestreq_procmsg_ckpt_name (struct tcmi_ppm_p_migr_back_guestreq_procmsg * self) inline static
Checkpoint name accessor.
Parameters
*self - this message instance
Returns
checkpoint name string
Definition at line 82 of file tcmi_ppm_p_migr_back_guestreq_procmsg.h.
Referenced by tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg().
 {
     return self->ckpt_name;
 }
static void tcmi_ppm_p_migr_back_guestreq_procmsg_free (struct tcmi_procmsg * self) static
<<private>> Frees custom message resources.
The checkpoint image name string is released from memory.
Parameters
*self - this message instance
Definition at line 227 of file tcmi_ppm_p_migr_back_guestreq_procmsg.c.
References tcmi_ppm_p_migr_back_guestreq_procmsg::ckpt_name, mdbg, tcmi_ppm_p_migr_back_guestreq_procmsg::size, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG, TCMI_PROCMSG, and tcmi_procmsg_dst_pid().
 {
     struct tcmi_ppm_p_migr_back_guestreq_procmsg *self_msg = TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG(self);
     mdbg(INFO3, "Freeing PPM guest migrate back message PID=%d, size=%d, ckptname='%s'",
          tcmi_procmsg_dst_pid(TCMI_PROCMSG(self)), self_msg->size, self_msg->ckpt_name);
     kfree(self_msg->ckpt_name);
 }
struct tcmi_msg* tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx (u_int32_t msg_id) read
<<public>> Guest request for migration back rx constructor.
<<public>> Guest request for migration back rx constructor.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this error message instance.
Returns
a new error message or NULL.
Definition at line 53 of file tcmi_ppm_p_migr_back_guestreq_procmsg.c.
References mdbg, ppm_p_migr_back_guestreq_procmsg_ops, TCMI_MSG, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID, TCMI_PROCMSG, and tcmi_procmsg_init_rx().
 {
     struct tcmi_ppm_p_migr_back_guestreq_procmsg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG(kmalloc(sizeof(struct tcmi_ppm_p_migr_back_guestreq_procmsg),
                                  GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate test request message");
         goto exit0;
     }
     /* Initialize the message for receiving. */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID,
                  &ppm_p_migr_back_guestreq_procmsg_ops)) {
         mdbg(ERR3, "Error initializing test request message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx (pid_t dst_pid, char * ckpt_name) read
<<public>> Guest request for migration back tx constructor.
Generates a one-way request message that contains the checkpoint name.
Parameters
dst_pid - PID of the target process that will receive this message
*ckpt_name - checkpoint name that will be wrapped in the message
Returns
a new error ready for the transfer or NULL.
Definition at line 96 of file tcmi_ppm_p_migr_back_guestreq_procmsg.c.
References tcmi_ppm_p_migr_back_guestreq_procmsg::ckpt_name, mdbg, ppm_p_migr_back_guestreq_procmsg_ops, tcmi_ppm_p_migr_back_guestreq_procmsg::size, TCMI_MSG, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID, TCMI_PROCMSG, tcmi_procmsg_init_tx(), and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_guesttask_migrateback_p().
 {
     struct tcmi_ppm_p_migr_back_guestreq_procmsg *msg;
     if (!(msg = TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG(kmalloc(sizeof(struct tcmi_ppm_p_migr_back_guestreq_procmsg),
                                  GFP_KERNEL)))) {
         mdbg(ERR3, "Can't migrate back guest request message");
         goto exit0;
     }
     msg->size = strlen(ckpt_name) + 1;
     if (!(msg->ckpt_name = (char*)kmalloc(msg->size, GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for checkpoint name");
         goto exit1;
     }
     strcpy(msg->ckpt_name, ckpt_name);
     /* Initialize the message for transfer, no transaction
      * required, no timout, no response ID */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID,
                  &ppm_p_migr_back_guestreq_procmsg_ops,
                  dst_pid, 0,
                  NULL, 0, 0, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing  migrate back guest request message");
         goto exit2;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit2:
     kfree(msg->ckpt_name);
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_ppm_p_migr_back_guestreq_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the message requires reading checkpoint size. Based on the size, it allocates space for the checkpoint name string and reads it from the socket.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 151 of file tcmi_ppm_p_migr_back_guestreq_procmsg.c.
References tcmi_ppm_p_migr_back_guestreq_procmsg::ckpt_name, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_ppm_p_migr_back_guestreq_procmsg::size, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG, and tcmi_procmsg_dst_pid().
 {
     int err = -EINVAL;
     struct tcmi_ppm_p_migr_back_guestreq_procmsg *self_msg = TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG(self);
     /* Receive the remote PID and checkpoint name size */
     if ((err = kkc_sock_recv(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive pid and size");
         goto exit0;
     }
     if (!(self_msg->ckpt_name = (char*)kmalloc(self_msg->size, GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for checkpoint name");
         goto exit0;
     }
     /* Receive the checkpoint name */
     if ((err = kkc_sock_recv(sock, self_msg->ckpt_name,
                  self_msg->size, KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive checkpoint name");
         goto exit0;
     }
     mdbg(INFO2, "PPM_P migrate back guest request received guest PID=%d, size=%d, ckptname='%s'",
          tcmi_procmsg_dst_pid(self), self_msg->size, self_msg->ckpt_name);
     return 0;
     /* error handling*/
  exit0:
     return err;
 }
static int tcmi_ppm_p_migr_back_guestreq_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Sends the PPM_P migrate back guest request
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 191 of file tcmi_ppm_p_migr_back_guestreq_procmsg.c.
References tcmi_ppm_p_migr_back_guestreq_procmsg::ckpt_name, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_ppm_p_migr_back_guestreq_procmsg::size, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG, and tcmi_procmsg_dst_pid().
 {
     int err;
     struct tcmi_ppm_p_migr_back_guestreq_procmsg *self_msg = TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG(self);
     /* Send the checkpoint name size */
     if ((err = kkc_sock_send(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send checkpoint size");
         goto exit0;
     }
     /* Send the checkpoint name */
     if ((err = kkc_sock_send(sock, self_msg->ckpt_name,
                  self_msg->size, KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send checkpoint name");
         goto exit0;
     }
     mdbg(INFO2, "PPM_P migrate back guest request sent guest PID=%d, size=%d, ckptname='%s'",
          tcmi_procmsg_dst_pid(self), self_msg->size, self_msg->ckpt_name);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static int tcmi_ppm_p_migr_back_shadowreq_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 107 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.c.
References mdbg, and tcmi_procmsg_dst_pid().
 {
     mdbg(INFO2, "PPM_P migrate back shadow request received guest PID=%d",
          tcmi_procmsg_dst_pid(self));
     return 0;
 }
static int tcmi_ppm_p_migr_back_shadowreq_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Sends the PPM_P migrate back shadow request
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 122 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.c.
References mdbg, and tcmi_procmsg_dst_pid().
 {
     mdbg(INFO2, "PPM_P migrate back shadow request sent guest PID=%d",
          tcmi_procmsg_dst_pid(self));
     return 0;
 }
Variable Documentation
struct tcmi_ppm_p_migr_back_guestreq_procmsg __attribute__
struct tcmi_procmsg_ops ppm_p_migr_back_guestreq_procmsg_ops static
Initial value:
= {
    .recv = tcmi_ppm_p_migr_back_guestreq_procmsg_recv,
    .send = tcmi_ppm_p_migr_back_guestreq_procmsg_send,
    .free = tcmi_ppm_p_migr_back_guestreq_procmsg_free
}
Message operations that support polymorphism.
Definition at line 238 of file tcmi_ppm_p_migr_back_guestreq_procmsg.c.
Referenced by tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx(), and tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx().
struct tcmi_procmsg_ops ppm_p_migr_back_shadowreq_procmsg_ops static
Initial value:
= {
    .recv = tcmi_ppm_p_migr_back_shadowreq_procmsg_recv,
    .send = tcmi_ppm_p_migr_back_shadowreq_procmsg_send,
}
Message operations that support polymorphism.
Definition at line 131 of file tcmi_ppm_p_migr_back_shadowreq_procmsg.c.
Referenced by tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx(), and tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx().