Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/kkc/kkc.c File Reference
kkc.c File Reference
#include "kkc.h"
#include <dbg.h>
Macros
#define KKC_PRIVATE
Functions
int kkc_connect (struct kkc_sock **sock, const char *where)
<<public>> Creates a connection the destination specified by the user.
int kkc_listen (struct kkc_sock **sock, const char *where)
<<public>> Starts listening on a specified interface.
static int kkc_establish (struct kkc_sock **sock, const char *where, int(*kkc_sock_method)(struct kkc_sock *, char *))
<<private>> Creates an architecture specific socket and starts listening or connects to the destination.
static int kkc_get_architecture (const char *where, struct kkc_arch **arch, char *addr)
<<private>> Helper function for parsing 'where' string and requesting for particular architecture structure.
int __init kkc_init_module (void)
KKC module loading.
void __exit kkc_exit_module (void)
KKC module unloading.
module_init (kkc_init_module)
module_exit (kkc_exit_module)
EXPORT_SYMBOL_GPL (kkc_connect)
EXPORT_SYMBOL_GPL (kkc_listen)
MODULE_LICENSE ("GPL")
MODULE_AUTHOR ("Jan Capek")
MODULE_AUTHOR ("Daniel Langr")
MODULE_DESCRIPTION ("Kernel to Kernel Communication Library")
Macro Definition Documentation
#define KKC_PRIVATE
Definition at line 28 of file kkc.c.
Function Documentation
EXPORT_SYMBOL_GPL (kkc_connect)
EXPORT_SYMBOL_GPL (kkc_listen)
static int kkc_establish (struct kkc_sock ** sock, const char * where, int(*)(struct kkc_sock *, char *) kkc_sock_method) static
<<private>> Creates an architecture specific socket and starts listening or connects to the destination.
First an architecture, based on the prefix in the address, has to be retrieved. The creation of the socket is delegated to the archictecture. If everything goes fine, the socket is asked to perform an operation specified by the user - kkc_sock_method().
Parameters
**sock - ouput parameter - upon successful creation of a connection or listening contains a valid socket
*where - address string with architecture prefix - e.g. tcp:192.168.0.1.2:2000
*kkc_sock_method - method called on the created socket. This would yield a new connection or a listening, depending on what method the user specified
Returns
0 upon success
Definition at line 96 of file kkc.c.
References kkc_arch_obj_new(), kkc_arch_put(), kkc_get_architecture(), KKC_SOCK, KKC_SOCK_MAX_ADDR_LENGTH, kkc_sock_put(), and mdbg.
Referenced by kkc_connect(), and kkc_listen().
 {
     struct kkc_arch *arch;
     int err = 0;
     char addr[KKC_SOCK_MAX_ADDR_LENGTH];
     *sock = NULL;
     mdbg(INFO4, "Requesting architecture structure and network address");
     if ((err = kkc_get_architecture(where, &arch, addr)) < 0) {
         mdbg(ERR4, "Cannot get architecture structure");
         err = -ENOMEM;
         goto exit0;
     }
     /* instantiate the socket */
     if (!((*sock) = KKC_SOCK(kkc_arch_obj_new(arch)))) {
         mdbg(ERR4, "Failed to create a new socket");
         err = -ENOMEM;
         goto exit1;
     }
     if (kkc_sock_method(*sock, addr)) {
         mdbg(ERR4, "KKC socket method failed");
         err = -ENOMEM;
         goto exit2;
     }
     /* release the architecture as the socket has created its own
      * reference */
     kkc_arch_put(arch);
     return 0;
     /* error handling */
  exit2:
     kkc_sock_put(*sock);
     *sock = NULL; /* return no socket to the user */
  exit1:
     kkc_arch_put(arch);
  exit0:
     return err;
 }
void __exit kkc_exit_module (void)
KKC module unloading.
Definition at line 212 of file kkc.c.
References minfo.
 {
     minfo(INFO1, "Unloading KKC");
 }
static int kkc_get_architecture (const char * where, struct kkc_arch ** arch, char * addr) static
<<private>> Helper function for parsing 'where' string and requesting for particular architecture structure.
As side effect fills 'addr' string with address part of 'where'.
Parameters
*where - pointer to the where request string
**arch - output parameter - stores the architecture if one found
*addr - storage for the address string, that gets extracted from the where string
Returns
0 upon success.
Definition at line 148 of file kkc.c.
References kkc_arch_get_by_name(), KKC_MAX_ARCH_LENGTH, KKC_SOCK_MAX_ADDR_LENGTH, and mdbg.
Referenced by kkc_establish().
 {
     char arch_name[KKC_MAX_ARCH_LENGTH];
     char *colon_ptr;
     int colon_pos;
     int err = 0;
     /* find colon */
     if ((colon_ptr = strchr(where, ':')) == NULL) {
         mdbg(ERR4, "Invalid syntax - could not find colon");
         err = -EINVAL;
         goto exit0;
     }
     /* check position */
     colon_pos = colon_ptr - where;
     if (colon_pos > (KKC_MAX_ARCH_LENGTH - 1)) {
         mdbg(ERR4, "Invalid syntax - too long architecture name length");
         err = -EINVAL;
         goto exit0;
     }
     /* get architecture name */
     strncpy(arch_name, where, colon_pos);
     arch_name[colon_pos] = '\0';
     mdbg(INFO4, "Extracted architecture name: ""%s""", arch_name);
     /* get address */
     strncpy(addr, colon_ptr + 1, KKC_SOCK_MAX_ADDR_LENGTH - 1);
     addr[KKC_SOCK_MAX_ADDR_LENGTH - 1] = '\0';
     mdbg(INFO4, "Extracted address: ""%s""", addr);
     if (!(*arch = kkc_arch_get_by_name(arch_name))) {
         mdbg(ERR4, "Could not get architecture for '%s'", arch_name);
         err = -EINVAL;
     }
     /* error handling */
 exit0:
     return err;
 }
int __init kkc_init_module (void)
KKC module loading.
Returns
always 0
Definition at line 202 of file kkc.c.
References minfo.
 {
     minfo(INFO1, "Loading KKC");
     return 0;
 }
MODULE_AUTHOR ("Jan Capek")
MODULE_AUTHOR ("Daniel Langr")
MODULE_DESCRIPTION ("Kernel to Kernel Communication Library")
module_exit (kkc_exit_module)
module_init (kkc_init_module)
MODULE_LICENSE ("GPL")