Clondike: tcmi_comm class
tcmi_comm class
communication
This class provides functionality to receive and deliver messages via a specified connection.
Data Structures
struct tcmi_comm
Compound structure that holds reference to the connection and the user method.
Macros
#define TCMI_COMM(c) ((struct tcmi_comm*)c)
Casts to the tcmi_comm instance.
#define wait_on_should_stop()
This macro implements atomic check for thread stop request and puts the task to sleep until such request arrives.
Typedefs
typedef int deliver_method_t (void *, struct tcmi_msg *)
Message delivery callback method type.
Functions
static int tcmi_comm_thread (void *comm)
<<private>> Messages receiving thread.
struct tcmi_comm * tcmi_comm_new (struct kkc_sock *sock, deliver_method_t *method, void *obj, int msg_group)
<<public>> TCMI communication component constructor.
void tcmi_comm_put (struct tcmi_comm *self)
<<public>> Decrements the reference counter.
static struct tcmi_comm * tcmi_comm_get (struct tcmi_comm *self)
<<public>> Instance accessor, increments the reference count.
Variables
static int tcmi_comm_counter = 0
Thread counter - used for receiving thread naming.
Detailed Description
This class provides functionality to receive and deliver messages via a specified connection.
The base of each instance is a separate thread receiving messages via specified connection. The user also specifies a method along with a parameter to be called upon reception of each message. This method is responsible for message delivery.
Data Structure Documentation
struct tcmi_comm
Compound structure that holds reference to the connection and the user method.
Definition at line 58 of file tcmi_comm.h.
Data Fields
deliver_method_t * deliver message delivery method
int msg_group preferred group of messages that will be received.
void * obj object whose method is to be called for message delivery.
atomic_t ref_count reference counter
struct kkc_sock * sock communication socket used for receiving
struct task_struct * thread message receiving thread
Macro Definition Documentation
#define TCMI_COMM (c) ((struct tcmi_comm*)c)
Casts to the tcmi_comm instance.
Definition at line 80 of file tcmi_comm.h.
Referenced by tcmi_comm_new(), and tcmi_comm_thread().
#define wait_on_should_stop ()
Value:
do {                            \
    do {                        \
        schedule();             \
        set_current_state(TASK_UNINTERRUPTIBLE);\
    } while(!kthread_should_stop());        \
    set_current_state(TASK_RUNNING);        \
} while(0)
This macro implements atomic check for thread stop request and puts the task to sleep until such request arrives.
Note the order of operations, the change of the state must always be prior to checking if it should stop. Any other order is incorrect and might put the task to sleep indefinitely. Also, it is necessary to set the state to uninterruptible, so that the thread won't get woken up rightaway by a pending signal.
Definition at line 112 of file tcmi_comm.h.
Referenced by tcmi_comm_thread(), and tcmi_migman_msg_thread().
Typedef Documentation
typedef int deliver_method_t(void *, struct tcmi_msg *)
Message delivery callback method type.
Definition at line 54 of file tcmi_comm.h.
Function Documentation
static struct tcmi_comm* tcmi_comm_get (struct tcmi_comm * self) static read
<<public>> Instance accessor, increments the reference count.
Parameters
*self - pointer to this comm instance
Definition at line 96 of file tcmi_comm.h.
References self.
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
struct tcmi_comm* tcmi_comm_new (struct kkc_sock * sock, deliver_method_t * deliver, void * obj, int msg_group) read
<<public>> TCMI communication component constructor.
allocates the instance
starts a new message receiving thread thread
Parameters
*sock - pointer to the socket that is to be used for the communication
*deliver - method to be called upon message delivery
*obj - object whose method is to be called
msg_group - preferred group of messages that are to be received - see tcmi_messages
Returns
new communication component or NULL
Definition at line 56 of file tcmi_comm.c.
References comm, tcmi_comm::deliver, kkc_sock_get(), kkc_sock_put(), mdbg, minfo, tcmi_comm::msg_group, tcmi_comm::obj, tcmi_comm::ref_count, tcmi_comm::sock, TCMI_COMM, tcmi_comm_counter, tcmi_comm_thread(), and tcmi_comm::thread.
Referenced by tcmi_migman_init().
 {
     struct tcmi_comm *comm;
     if (!sock || !deliver) {
         mdbg(ERR3, "Missing socket or delivery method");
         goto exit0;
     }
     if (!(comm = TCMI_COMM(kmalloc(sizeof(struct tcmi_comm), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for communication component");
         goto exit0;
     }
     atomic_set(&comm->ref_count, 1);
     comm->sock = kkc_sock_get(sock);
     comm->deliver = deliver;
     comm->obj = obj;
     comm->msg_group = msg_group;
     comm->thread = kthread_run(tcmi_comm_thread, comm,
                    "tcmi_commd_%02d", tcmi_comm_counter++);
     if (IS_ERR(comm->thread)) {
         minfo(ERR2, "Failed to create a message receiving thread!");
         goto exit1;
     }
     mdbg(INFO4, "Created TCMI comm, preferred message group %d, memory=%p",
          comm->msg_group, comm);
     return comm;
     /* error handling */
  exit1:
     kkc_sock_put(sock);
     kfree(comm);
  exit0:
     return NULL;
 }
void tcmi_comm_put (struct tcmi_comm * self)
<<public>> Decrements the reference counter.
<<public>> Decrements the reference counter.
Decrements reference counter and if it reaches 0, it will:
stop the receiving thread by sending it a forced signal. The signal interrupts any blocking receive operation. Then we wait till the thread terminates.
release the socket instance
free the tcmi_comm instance
Parameters
*self - pointer to this instance
Definition at line 109 of file tcmi_comm.c.
References kkc_sock_put(), mdbg, and self.
Referenced by tcmi_migman_free(), and tcmi_migman_init().
 {
     if (self && atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying TCMI comm, preferred message group %d, memory=%p",
              self->msg_group, self);
         /* stop the transaction thread */
         force_sig(SIGTERM, self->thread);
         /* ensures synchronous thread termination */
         kthread_stop(self->thread);
         kkc_sock_put(self->sock);
         kfree(self);
     }
 }
static int tcmi_comm_thread (void * comm) static
<<private>> Messages receiving thread.
receives any messages on the connection that is part of the tcmi_comm instance
as long as no invalid ID or other error occurs or the main thread signals to quit it will be delivering messages to the subscribed object via its delivery method.
messages that are not successfully delivered are discarded
The thread is always stopped synchronously with the instance destruction, therefore there is no need to account an extra reference for the thread.
Parameters
*comm - pointer to this communication instance
Returns
0 upon successful termination.
Definition at line 145 of file tcmi_comm.c.
References KKC_SOCK_BLOCK, kkc_sock_getpeername2(), kkc_sock_getsockname2(), kkc_sock_recv(), mdbg, minfo, tcmi_msg::msg_id, TCMI_COMM, tcmi_msg_factory(), tcmi_msg_put(), tcmi_msg_recv(), and wait_on_should_stop.
Referenced by tcmi_comm_new().
 {
     struct tcmi_comm *self = TCMI_COMM(comm);
     /* make local copies instance attributes, this saves one
      * dereference for each */
     struct kkc_sock *sock = self->sock;
     deliver_method_t *deliver = self->deliver;
     int msg_group = self->msg_group;
     void *obj = self->obj;
     /* pointer to the message received */
     struct tcmi_msg *m;
     u_int32_t msg_id;
     int err = 0;
     minfo(INFO3, "Receiving on socket local: '%s', remote: '%s'",
           kkc_sock_getsockname2(sock), kkc_sock_getpeername2(sock));
     /* receive messages, checking for signals or stop request */
     while (!(kthread_should_stop() || signal_pending(current))) {
         if ((err = kkc_sock_recv(sock, &msg_id, sizeof(msg_id), KKC_SOCK_BLOCK)) < 0) {
             minfo(ERR3, "Error receiving message ID, error code: %d, terminating", err);
             break;
         }
         if (!(m = tcmi_msg_factory(msg_id, msg_group))) {
             minfo(ERR3, "Error building message %x, terminating", msg_id);
             break;
         }
         if ((err = tcmi_msg_recv(m, sock)) < 0) {
             minfo(ERR3, "Error receiving message %x, error %d, terminating", msg_id, err);
             break;
         }
         /* try to deliver, if it fails destroy the message */
         if (deliver(obj, m) < 0)
             tcmi_msg_put(m);
     }
     /* very important to sync with the the thread that is terminating us */
     wait_on_should_stop();
     mdbg(INFO3, "Message receiving thread terminating");
     return err;
 }
Variable Documentation
int tcmi_comm_counter = 0 static
Thread counter - used for receiving thread naming.
Definition at line 186 of file tcmi_comm.c.
Referenced by tcmi_comm_new().