Clondike: tcmi_err_procmsg class
tcmi_err_procmsg class
tcmi_procmsg class
This class represents a generic error process message.
Data Structures
struct tcmi_err_procmsg
Compound structure, inherits from tcmi_msg_class.
Macros
#define TCMI_ERR_PROCMSG(m) ((struct tcmi_err_procmsg*)m)
Casts to the tcmi_err_procmsg instance.
Functions
static int tcmi_err_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_err_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Sends out the error code via specified socket.
struct tcmi_msg * tcmi_err_procmsg_new_rx (u_int32_t msg_id)
<<public>> Error process message, constructor for receiving.
struct tcmi_msg * tcmi_err_procmsg_new_tx (u_int32_t msg_id, u_int32_t trans_id, int err_code, pid_t dst_pid)
<<public>> Error process message, constructor for transferring.
static int tcmi_err_procmsg_code (struct tcmi_procmsg *self)
<<public>> Error code accessor.
Variables
static struct tcmi_procmsg_ops err_procmsg_ops
Message operations that support polymorphism.
Detailed Description
This class represents a generic error process message.
It carries an error code and can be used as response to any regular process message that has registered its rx constructor as the error rx constructor with the message factory. Unlike other messages, it doesn't define a fixed message ID. Instead the transfer message constructor (tcmi_err_procmsg_new_tx()) allows specifying a message ID that would carry the regular response message.
The constructor only sets error flags in the message ID. The receiving party identifies the message based on the regular response ID. The message flags indicating an error make the message factory use the error rx constructor. After delivery, the error message can be processed and the error code extracted.
Data Structure Documentation
struct tcmi_err_procmsg
Compound structure, inherits from tcmi_msg_class.
Definition at line 59 of file tcmi_err_procmsg.h.
Data Fields
int err_code error code that the message is carrying.
struct tcmi_procmsg super parent class instance.
Macro Definition Documentation
#define TCMI_ERR_PROCMSG (m) ((struct tcmi_err_procmsg*)m)
Casts to the tcmi_err_procmsg instance.
Definition at line 75 of file tcmi_err_procmsg.h.
Referenced by tcmi_err_procmsg_code(), tcmi_err_procmsg_new_rx(), tcmi_err_procmsg_new_tx(), tcmi_err_procmsg_recv(), and tcmi_err_procmsg_send().
Function Documentation
static int tcmi_err_procmsg_code (struct tcmi_procmsg * self) inline static
<<public>> Error code accessor.
Parameters
*self - pointer to this message instance
Returns
error code that the message is carrying
Definition at line 83 of file tcmi_err_procmsg.h.
References TCMI_ERR_PROCMSG.
 {
     return TCMI_ERR_PROCMSG(self)->err_code;
 }
struct tcmi_msg* tcmi_err_procmsg_new_rx (u_int32_t msg_id) read
<<public>> Error process message, constructor for receiving.
<<public>> Error process message, constructor for receiving.
This constructor is made available for other process messages, so that they can specify it as their error constructor for the factory class .
Parameters
msg_id - message ID that will be used for this error message instance.
Returns
a new error message or NULL.
Definition at line 51 of file tcmi_err_procmsg.c.
References err_procmsg_ops, mdbg, TCMI_ERR_PROCMSG, TCMI_MSG, TCMI_MSG_FLG_SET_ERR, TCMI_PROCMSG, and tcmi_procmsg_init_rx().
 {
     struct tcmi_err_procmsg *msg;
     if (!(msg = TCMI_ERR_PROCMSG(kmalloc(sizeof(struct tcmi_err_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for error message %x", msg_id);
         goto exit0;
     }
     /* Initialized the message for receiving, message ID is
      * extended with error flags */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_MSG_FLG_SET_ERR(msg_id), &err_procmsg_ops)) {
         mdbg(ERR3, "Error initializing error message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_err_procmsg_new_tx (u_int32_t msg_id, u_int32_t trans_id, int err_code, pid_t dst_pid) read
<<public>> Error process message, constructor for transferring.
<<public>> Error process message, constructor for transferring.
An error message is considered one way only and is usually used as a error response to some other process message. The user thus has to specify the transaction ID of the message that the error message is a response too. Messages with TCMI_TRANSACTION_INVAL_ID are possible too. No search for a matching transaction will be performed at the receiving party and the message will be queued in a regular request queue.
As for any other process message, the destination PID has to be specified
Parameters
msg_id - ID assigned to the error message, it will be extended with error flags, so that the message factory at the receiving party uses the above implemented tcmi_err_procmsg_new_rx() constructor.
trans_id - transaction ID
err_code - error code that will be stored in the message
dst_pid - destination process PID
Returns
a new error ready for the transfer or NULL.
Definition at line 95 of file tcmi_err_procmsg.c.
References tcmi_err_procmsg::err_code, err_procmsg_ops, mdbg, TCMI_ERR_PROCMSG, TCMI_MSG, TCMI_MSG_FLG_SET_ERR, TCMI_PROCMSG, and tcmi_procmsg_init_tx().
Referenced by tcmi_guesttask_process_p_emigrate_msg(), and tcmi_penmigman_process_msg().
 {
     struct tcmi_err_procmsg *msg;
     if (!(msg = TCMI_ERR_PROCMSG(kmalloc(sizeof(struct tcmi_err_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for error message %x", msg_id);
         goto exit0;
     }
     /* Initialize the message for transfer, message ID is
      * extended with error flags, no transaction created or
      * response ID setup. Only the transaction ID, that will get
      * send along with the message, is set. */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_MSG_FLG_SET_ERR(msg_id), &err_procmsg_ops,
                  dst_pid, 0,
                  NULL, 0, 0, trans_id)) {
         mdbg(ERR3, "Error initializing error message %x", msg_id);
         goto exit1;
     }
     msg->err_code = err_code;
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_err_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the error process message requires reading the error code from the specified socket
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 141 of file tcmi_err_procmsg.c.
References tcmi_err_procmsg::err_code, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, and TCMI_ERR_PROCMSG.
 {
     int err;
     struct tcmi_err_procmsg *self_err = TCMI_ERR_PROCMSG(self);
     err = kkc_sock_recv(sock, &self_err->err_code,
                 sizeof(self_err->err_code), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Received error code: %x", self_err->err_code);
     return err;
 }
static int tcmi_err_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Sends out the error code via specified socket.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully sent.
Definition at line 160 of file tcmi_err_procmsg.c.
References tcmi_err_procmsg::err_code, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, and TCMI_ERR_PROCMSG.
 {
     int err;
     struct tcmi_err_procmsg *self_err = TCMI_ERR_PROCMSG(self);
     err = kkc_sock_send(sock, &self_err->err_code,
                 sizeof(self_err->err_code), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Sent error code: %x", self_err->err_code);
     return err;
 }
Variable Documentation
struct tcmi_procmsg_ops err_procmsg_ops static
Initial value:
= {
    .recv = tcmi_err_procmsg_recv,
    .send = tcmi_err_procmsg_send
}
Message operations that support polymorphism.
Definition at line 176 of file tcmi_err_procmsg.c.
Referenced by tcmi_err_procmsg_new_rx(), and tcmi_err_procmsg_new_tx().