Clondike: tcmi_syscallhooks_other class
tcmi_syscallhooks_other class
tcmi_syscallhooks class
A <<singleton>> class that installs syscalls hooks into the kernel.
Functions
int tcmi_syscall_hooks_other_init (void)
<<public>> Registers all hooks with the kernel.
void tcmi_syscall_hooks_other_exit (void)
<<public>> Unregisters all hooks.
Detailed Description
A <<singleton>> class that installs syscalls hooks into the kernel.
Function Documentation
void tcmi_syscall_hooks_other_exit (void)
<<public>> Unregisters all hooks.
Definition at line 71 of file tcmi_syscallhooks_other.c.
References minfo.
Referenced by tcmi_syscall_hooks_exit().
 {
     minfo(INFO1, "Unregistering TCMI other syscalls hooks"
             "(wait)");
     tcmi_hooks_unregister_sys_wait4();
     tcmi_hooks_unregister_pre_fork();
     tcmi_hooks_unregister_in_fork();
     tcmi_hooks_unregister_post_fork();
 }
int tcmi_syscall_hooks_other_init (void)
<<public>> Registers all hooks with the kernel.
<<public>> Registers all hooks with the kernel.
Returns
0 upon success
Definition at line 56 of file tcmi_syscallhooks_other.c.
References minfo, tcmi_syscall_hooks_in_fork(), tcmi_syscall_hooks_post_fork(), tcmi_syscall_hooks_pre_fork(), and tcmi_syscall_hooks_sys_wait4().
Referenced by tcmi_syscall_hooks_init().
 {
     minfo(INFO1, "Registering TCMI other syscalls hooks\n"
             "(wait)");
     tcmi_hooks_register_sys_wait4(tcmi_syscall_hooks_sys_wait4);
     tcmi_hooks_register_pre_fork(tcmi_syscall_hooks_pre_fork);
     tcmi_hooks_register_in_fork(tcmi_syscall_hooks_in_fork);
     tcmi_hooks_register_post_fork(tcmi_syscall_hooks_post_fork);
     return 0;
 }