Clondike: tcmi_rpc class
tcmi_rpc class
syscall forwarding
A <<virtual>> RPC class, used as parent for both guest and shadow side.
Modules
tcmi_guest_rpc class
A <<singleton>> class that is executing RPC on PEN side.
tcmi_shadow_rpc class
A <<singleton>> class that is executing RPC on CCN side.
Macros
#define TCMI_RPC_MAXPARAMS 6
Max remote procedure call parameters.
Functions
long tcmi_rpc_do (struct tcmi_rpc *self, unsigned int rpc_num, long parameters[6])
<<public>> Universal procedure to do RPC
static long tcmi_rpc_call0 (struct tcmi_rpc *self, unsigned int rpc_num)
<<public>> Do a rpc without parameters.
static long tcmi_rpc_call1 (struct tcmi_rpc *self, unsigned int rpc_num, long param1)
<<public>> Do a rpc with 1 parameter.
static long tcmi_rpc_call2 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2)
<<public>> Do a rpc with 2 parameters.
static long tcmi_rpc_call3 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2, long param3)
<<public>> Do a rpc with 3 parameters.
static long tcmi_rpc_call4 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2, long param3, long param4)
<<public>> Do a rpc with 4 parameters.
static long tcmi_rpc_call6 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2, long param3, long param4, long param5, long param6)
<<public>> Do a rpc with 4 parameters.
Detailed Description
A <<virtual>> RPC class, used as parent for both guest and shadow side.
This class is used for calling methods on shadow on guest request. If guest task calls RPC, the remote side is executed by coresponding shadow task. Communication is done using tcmi_rpc_procmsg class for RPC request and tcmi_rpcresp_procmsg class for response.
Macro Definition Documentation
#define TCMI_RPC_MAXPARAMS 6
Max remote procedure call parameters.
Definition at line 50 of file tcmi_rpc.h.
Referenced by tcmi_rpc_call0(), tcmi_rpc_call1(), tcmi_rpc_call2(), tcmi_rpc_call3(), tcmi_rpc_call4(), tcmi_rpc_call6(), tcmi_rpcresp_procmsg_create(), and tcmi_rpcresp_procmsg_get_response().
Function Documentation
static long tcmi_rpc_call0 (struct tcmi_rpc * self, unsigned int rpc_num) inline static
<<public>> Do a rpc without parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
Returns
RPC return code
Definition at line 63 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
Referenced by tcmi_syscall_hooks_sys_getegid(), tcmi_syscall_hooks_sys_geteuid(), tcmi_syscall_hooks_sys_getgid(), tcmi_syscall_hooks_sys_getpgrp(), tcmi_syscall_hooks_sys_getppid(), tcmi_syscall_hooks_sys_getuid(), and tcmi_syscall_hooks_sys_setsid().
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call1 (struct tcmi_rpc * self, unsigned int rpc_num, long param1) inline static
<<public>> Do a rpc with 1 parameter.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
Returns
RPC return code
Definition at line 76 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
Referenced by tcmi_syscall_hooks_sys_getpgid(), tcmi_syscall_hooks_sys_getsid(), tcmi_syscall_hooks_sys_setgid(), and tcmi_syscall_hooks_sys_setuid().
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call2 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2) inline static
<<public>> Do a rpc with 2 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
Returns
RPC return code
Definition at line 91 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
Referenced by tcmi_shadowtask_process_msg(), tcmi_syscall_hooks_sys_getgroups(), tcmi_syscall_hooks_sys_kill(), tcmi_syscall_hooks_sys_setgroups(), tcmi_syscall_hooks_sys_setpgid(), tcmi_syscall_hooks_sys_setregid(), and tcmi_syscall_hooks_sys_setreuid().
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call3 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2, long param3) inline static
<<public>> Do a rpc with 3 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
param3 - Third parametr of called procedure
Returns
RPC return code
Definition at line 108 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
Referenced by tcmi_syscall_hooks_do_tkill(), tcmi_syscall_hooks_sys_getresgid(), tcmi_syscall_hooks_sys_getresuid(), tcmi_syscall_hooks_sys_rt_sigqueueinfo(), tcmi_syscall_hooks_sys_setresgid(), and tcmi_syscall_hooks_sys_setresuid().
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     parameters[2] = param3;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call4 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2, long param3, long param4) inline static
<<public>> Do a rpc with 4 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
param3 - Third parametr of called procedure
param4 - 4th parametr of called procedure
Returns
RPC return code
Definition at line 127 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
Referenced by tcmi_syscall_hooks_sys_wait4().
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     parameters[2] = param3;
     parameters[3] = param4;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call6 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2, long param3, long param4, long param5, long param6) inline static
<<public>> Do a rpc with 4 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
param3 - Third parametr of called procedure
param4 - 4th parametr of called procedure .....
Returns
RPC return code
Definition at line 148 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
Referenced by tcmi_syscall_hooks_pre_fork().
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     parameters[2] = param3;
     parameters[3] = param4;
     parameters[4] = param5;
     parameters[5] = param6;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
long tcmi_rpc_do (struct tcmi_rpc * self, unsigned int rpc_num, long parameters[6])
<<public>> Universal procedure to do RPC
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
parameters[] - Array of RPCs parameters
Returns
RPC return code
Definition at line 44 of file tcmi_rpc.c.
References mdbg, self, and TCMI_MAX_RPC_NUM.
Referenced by tcmi_rpc_call0(), tcmi_rpc_call1(), tcmi_rpc_call2(), tcmi_rpc_call3(), tcmi_rpc_call4(), and tcmi_rpc_call6().
 {
     long ret = -EPERM;
     if( rpc_num > TCMI_MAX_RPC_NUM ){
         mdbg(ERR3, "%d isn't number of procedure", rpc_num);
     }
     else if( self->calltable[rpc_num] != NULL){
         mdbg(INFO2, "Calling RPC#%d(%lx, %lx, %lx, %lx, %lx) at %p", rpc_num,
                 parameters[0], parameters[1], parameters[2],
                 parameters[3], parameters[4], self->calltable[rpc_num]);
         ret = self->calltable[rpc_num](rpc_num, parameters);
         mdbg(INFO2, "RPC#%d returned %ld(%lx)", rpc_num, ret, ret);
     }
     else{
         mdbg(ERR2, "No handler for RPC#%d", rpc_num);
     }
     return ret;
 }