Clondike: kkc_sock_sleeper class
kkc_sock_sleeper class
KKC
The main purpose of this class is to make it easier to create and manage sleeping on KKC sockets.
Data Structures
struct kkc_sock_sleeper
Compound structure allowing external linking socket sleepers.
Functions
static struct kkc_sock_sleeper * kkc_sock_sleeper_add (struct kkc_sock *sock, struct task_struct *tsk)
<<public>> Creates a new sleeper element associated with a particular socket and task.
static void kkc_sock_sleeper_remove (struct kkc_sock_sleeper *self)
<<public>> Removes a sleeper from its socket, from the list and disposes it.
static int kkc_sock_sleeper_remove_match (struct kkc_sock_sleeper *self, struct kkc_sock *sock)
<<public>> Checks if the specified socket matches the socket stored in the sleeper.
Detailed Description
The main purpose of this class is to make it easier to create and manage sleeping on KKC sockets.
Usually when a thread is watching multiple sockets, it needs to create a separate wait_queue_t element for it. The problem is where to store all these queue elements as all its internal linking items are fully used by the kernel wait queue. This class provides a simple solution - a wrapper object.
The object is intentionally designed for single threaded access(no reference counting) as this should be sufficient.
Data Structure Documentation
struct kkc_sock_sleeper
Compound structure allowing external linking socket sleepers.
Definition at line 54 of file kkc_sock_sleeper.h.
Data Fields
struct list_head list linking element for public use.
struct kkc_sock * sock socket associated with the sleeper
wait_queue_t wait wait queue element passed to the socket.
Function Documentation
static struct kkc_sock_sleeper* kkc_sock_sleeper_add (struct kkc_sock * sock, struct task_struct * tsk) static read
<<public>> Creates a new sleeper element associated with a particular socket and task.
The specified task is added to the socket wait queue
Parameters
*sock - target socket where to add new waiting process
*tsk - task that wants to sleep on socket's wait queue
Returns
new sleeper or NULL
Definition at line 72 of file kkc_sock_sleeper.h.
References kkc_sock_add_wait_queue(), kkc_sock_getpeername2(), kkc_sock_getsockname2(), list, mdbg, sock, and wait.
Referenced by tcmi_ccnman_listen().
 {
     struct kkc_sock_sleeper *sleeper;
     if (!(sleeper = (struct kkc_sock_sleeper*)
           kmalloc(sizeof(struct kkc_sock_sleeper), GFP_KERNEL))) {
         mdbg(ERR3, "Failed to allocate KKC sock sleeper");
         goto exit0;
     }
     /* initialize internal data */
     INIT_LIST_HEAD(&sleeper->list);
     init_waitqueue_entry(&sleeper->wait, tsk);
     sleeper->sock = sock;
     /* append the task to socket's wait queue */
     kkc_sock_add_wait_queue(sock, &sleeper->wait);
     mdbg(INFO3, "Added sleeper for socket local: '%s', remote: '%s'",
          kkc_sock_getsockname2(sock), kkc_sock_getpeername2(sock));
     return sleeper;
     /* error handling */
  exit0:
     return NULL;
 }
static void kkc_sock_sleeper_remove (struct kkc_sock_sleeper * self) inline static
<<public>> Removes a sleeper from its socket, from the list and disposes it.
Parameters
*self - this socket sleeper instance
Definition at line 105 of file kkc_sock_sleeper.h.
References kkc_sock_getpeername2(), kkc_sock_getsockname2(), kkc_sock_remove_wait_queue(), mdbg, and self.
Referenced by kkc_sock_sleeper_remove_match(), and tcmi_ccnman_listen().
 {
     list_del_init(&self->list);
     kkc_sock_remove_wait_queue(self->sock, &self->wait);
     mdbg(INFO3, "Removed sleeper from socket local: '%s', remote: '%s'",
          kkc_sock_getsockname2(self->sock), kkc_sock_getpeername2(self->sock));
     kfree(self);
 }
static int kkc_sock_sleeper_remove_match (struct kkc_sock_sleeper * self, struct kkc_sock * sock) inline static
<<public>> Checks if the specified socket matches the socket stored in the sleeper.
If so, the sleeper removes itself from the wait queue.
Parameters
*self - this socket sleeper instance
*sock - socket that is to be removed from a sleeper
Returns
true if successfully removed
Definition at line 124 of file kkc_sock_sleeper.h.
References kkc_sock_sleeper_remove(), mdbg, and self.
Referenced by tcmi_ccnman_remove_sleepers().
 {
     int ret = 0;
     if (self->sock == sock) {
         mdbg(INFO4, "Socket matches, removing..");
         kkc_sock_sleeper_remove(self);
         ret = 1;
     }
     return ret;
 }