Clondike: tcmi_authenticate_resp_msg class
tcmi_authenticate_resp_msg class
tcmi_msg class
This message is send as a response to authentication request by the CCN to PEN.
Data Structures
struct tcmi_authenticate_resp_msg
Authentication response message structure.
Macros
#define TCMI_AUTHENTICATE_RESP_MSG_DSC TCMI_MSG_DSC(TCMI_AUTHENTICATE_RESP_MSG_ID, tcmi_authenticate_resp_msg_new_rx, tcmi_err_msg_new_rx)
<<public>> Message descriptor for the factory class
#define TCMI_AUTHENTICATE_RESP_MSG(m) ((struct tcmi_authenticate_resp_msg*)m)
Casts to the tcmi_authenticate_resp_msg instance.
Functions
static int tcmi_authenticate_resp_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_authenticate_resp_msg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
struct tcmi_msg * tcmi_authenticate_resp_msg_new_rx (u_int32_t msg_id)
<<public>> Authentication response message constructor for receiving.
struct tcmi_msg * tcmi_authenticate_resp_msg_new_tx (u_int32_t trans_id, u_int32_t ccn_id, enum arch_ids ccn_arch, int8_t result_code, struct fs_mount_params *mount_params)
<<public>> Authentication response message constructor for transferring.
static u_int32_t tcmi_authenticate_resp_msg_ccn_id (struct tcmi_authenticate_resp_msg *self)
<<public>> CCN id getter
static enum arch_ids tcmi_authenticate_resp_msg_arch (struct tcmi_authenticate_resp_msg *self)
<<public>> CCN architecture getter
static int8_t tcmi_authenticate_resp_msg_result_code (struct tcmi_authenticate_resp_msg *self)
<<public>> Result code getter
static struct fs_mount_params * tcmi_authenticate_resp_msg_mount_params (struct tcmi_authenticate_resp_msg *self)
<<public>> Mount params getter
Variables
static struct tcmi_msg_ops authenticate_resp_msg_ops
Message operations that support polymorphism.
Detailed Description
This message is send as a response to authentication request by the CCN to PEN.
Data Structure Documentation
struct tcmi_authenticate_resp_msg
Authentication response message structure.
Definition at line 22 of file tcmi_authenticate_resp_msg.h.
Data Fields
enum arch_ids ccn_arch Architecture of ccn.
u_int32_t ccn_id Id of the ccn that was asked for the authentication.
struct fs_mount_params mount_params Parameters of the mount operation to be performed on task execve on PEN side.
int8_t result_code 0 if authentication succeeded, negative otherwise
struct tcmi_msg super parent class instance.
Macro Definition Documentation
#define TCMI_AUTHENTICATE_RESP_MSG (m) ((struct tcmi_authenticate_resp_msg*)m)
Casts to the tcmi_authenticate_resp_msg instance.
Definition at line 50 of file tcmi_authenticate_resp_msg.h.
Referenced by tcmi_authenticate_resp_msg_new_rx(), tcmi_authenticate_resp_msg_new_tx(), tcmi_authenticate_resp_msg_recv(), tcmi_authenticate_resp_msg_send(), and tcmi_penmigman_process_msg().
#define TCMI_AUTHENTICATE_RESP_MSG_DSC TCMI_MSG_DSC(TCMI_AUTHENTICATE_RESP_MSG_ID, tcmi_authenticate_resp_msg_new_rx, tcmi_err_msg_new_rx)
<<public>> Message descriptor for the factory class
Definition at line 47 of file tcmi_authenticate_resp_msg.h.
Function Documentation
static enum arch_ids tcmi_authenticate_resp_msg_arch (struct tcmi_authenticate_resp_msg * self) inline static
<<public>> CCN architecture getter
Parameters
*self - this message instance
Returns
CCN architecture
Definition at line 69 of file tcmi_authenticate_resp_msg.h.
Referenced by tcmi_penmigman_process_msg().
 {
     return self->ccn_arch;
 }
static u_int32_t tcmi_authenticate_resp_msg_ccn_id (struct tcmi_authenticate_resp_msg * self) inline static
<<public>> CCN id getter
Parameters
*self - this message instance
Returns
CCN id
Definition at line 58 of file tcmi_authenticate_resp_msg.h.
Referenced by tcmi_penmigman_process_msg().
 {
     return self->ccn_id;
 }
static struct fs_mount_params* tcmi_authenticate_resp_msg_mount_params (struct tcmi_authenticate_resp_msg * self) static read
<<public>> Mount params getter
Parameters
*self - this message instance
Returns
Mount params
Definition at line 91 of file tcmi_authenticate_resp_msg.h.
Referenced by tcmi_penmigman_process_msg().
{
     return &self->mount_params;
 }
struct tcmi_msg* tcmi_authenticate_resp_msg_new_rx (u_int32_t msg_id) read
<<public>> Authentication response message constructor for receiving.
<<public>> Authentication response message constructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this error message instance.
Returns
a new message or NULL.
Definition at line 24 of file tcmi_authenticate_resp_msg.c.
References authenticate_resp_msg_ops, mdbg, TCMI_AUTHENTICATE_RESP_MSG, TCMI_AUTHENTICATE_RESP_MSG_ID, TCMI_MSG, and tcmi_msg_init_rx().
 {
     struct tcmi_authenticate_resp_msg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_AUTHENTICATE_RESP_MSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_AUTHENTICATE_RESP_MSG_ID);
         goto exit0;
     }
     if (!(msg = TCMI_AUTHENTICATE_RESP_MSG(kmalloc(sizeof(struct tcmi_authenticate_resp_msg),
                         GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate auth resp message");
         goto exit0;
     }
     /* Initialized the message for receiving, message ID is extended with error flags */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_AUTHENTICATE_RESP_MSG_ID, &authenticate_resp_msg_ops)) {
         mdbg(ERR3, "Error initializing auth resp message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_authenticate_resp_msg_new_tx (u_int32_t trans_id, u_int32_t ccn_id, enum arch_ids ccn_arch, int8_t result_code, struct fs_mount_params * mount_params) read
<<public>> Authentication response message constructor for transferring.
<<public>> Authentication response message constructor for transferring.
Parameters
trans_id - transaction ID that this message is replying to.
ccn_id - ID of this CCN
ccn_arch - Architecture of CCN
result_code Result of the authentication
mount_params Paremeters of the distributed FS mount to be performed on PEN side
Returns
a new test response message for the transfer or NULL.
Definition at line 65 of file tcmi_authenticate_resp_msg.c.
References authenticate_resp_msg_ops, tcmi_authenticate_resp_msg::ccn_arch, tcmi_authenticate_resp_msg::ccn_id, mdbg, tcmi_authenticate_resp_msg::mount_params, tcmi_authenticate_resp_msg::result_code, TCMI_AUTHENTICATE_RESP_MSG, TCMI_AUTHENTICATE_RESP_MSG_ID, TCMI_MSG, and tcmi_msg_init_tx().
Referenced by tcmi_ccnmigman_process_msg().
 {
     struct tcmi_authenticate_resp_msg *msg;
     if (!(msg = TCMI_AUTHENTICATE_RESP_MSG(kmalloc(sizeof(struct tcmi_authenticate_resp_msg),
                         GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate auth resp message");
         goto exit0;
     }
     msg->ccn_id = ccn_id;
     msg->ccn_arch = ccn_arch;
     msg->result_code = result_code;
     msg->mount_params = *mount_params;
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_AUTHENTICATE_RESP_MSG_ID, &authenticate_resp_msg_ops,
                  NULL, 0, 0, trans_id)) {
         mdbg(ERR3, "Error initializing authenticate response message");
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_authenticate_resp_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the erro message requires reading the error code from the specified connection
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 110 of file tcmi_authenticate_resp_msg.c.
References tcmi_authenticate_resp_msg::ccn_arch, tcmi_authenticate_resp_msg::ccn_id, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_authenticate_resp_msg::mount_params, tcmi_authenticate_resp_msg::result_code, and TCMI_AUTHENTICATE_RESP_MSG.
 {
     int err;
     struct tcmi_authenticate_resp_msg *self_msg = TCMI_AUTHENTICATE_RESP_MSG(self);
     mdbg(INFO3, "Authenticate response message received");
     if ((err = kkc_sock_recv(sock, &self_msg->ccn_id,
                  sizeof(self_msg->ccn_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive ccn id");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_msg->ccn_arch,
                  sizeof(self_msg->ccn_arch), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive ccn arch");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_msg->result_code,
                  sizeof(self_msg->result_code), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive result_code");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_msg->mount_params,
                  sizeof(self_msg->mount_params), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive mount params");
         goto exit0;
     }
     return 0;
 exit0:
     return err;
 }
static int8_t tcmi_authenticate_resp_msg_result_code (struct tcmi_authenticate_resp_msg * self) inline static
<<public>> Result code getter
Parameters
*self - this message instance
Returns
result code
Definition at line 80 of file tcmi_authenticate_resp_msg.h.
 {
     return self->result_code;
 }
static int tcmi_authenticate_resp_msg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 152 of file tcmi_authenticate_resp_msg.c.
References tcmi_authenticate_resp_msg::ccn_arch, tcmi_authenticate_resp_msg::ccn_id, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_authenticate_resp_msg::mount_params, tcmi_authenticate_resp_msg::result_code, and TCMI_AUTHENTICATE_RESP_MSG.
 {
     int err;
     struct tcmi_authenticate_resp_msg *self_msg = TCMI_AUTHENTICATE_RESP_MSG(self);
     mdbg(INFO3, "Authenticate response message sent");
     if ((err = kkc_sock_send(sock, &self_msg->ccn_id,
                  sizeof(self_msg->ccn_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send ccn id");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_msg->ccn_arch,
                  sizeof(self_msg->ccn_arch), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send ccn arch");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_msg->result_code,
                  sizeof(self_msg->result_code), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send result code");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_msg->mount_params,
                  sizeof(self_msg->mount_params), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send mount_params");
         goto exit0;
     }
     return 0;
 exit0:
     return err;
 }
Variable Documentation
struct tcmi_msg_ops authenticate_resp_msg_ops static
Initial value:
= {
    .recv = tcmi_authenticate_resp_msg_recv,
    .send = tcmi_authenticate_resp_msg_send
}
Message operations that support polymorphism.
Definition at line 190 of file tcmi_authenticate_resp_msg.c.
Referenced by tcmi_authenticate_resp_msg_new_rx(), and tcmi_authenticate_resp_msg_new_tx().