Clondike: proxyfs_tty_real_file class
proxyfs_tty_real_file class
proxyfs_real_file class
This class is used by server task for accessing to TTYs.
Macros
#define PROXYFS_TTY_REAL_FILE(arg) ((struct proxyfs_tty_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Functions
int proxyfs_tty_real_file_init (struct proxyfs_tty_real_file *self)
<<public>> Initialize tty_real_file
void proxyfs_tty_real_file_destroy (struct proxyfs_tty_real_file *self)
<<public>> Deinitialize tty_real_file
struct proxyfs_tty_real_file * proxyfs_tty_real_file_new (void)
<<public>> tty_real_file construktor
Detailed Description
This class is used by server task for accessing to TTYs.
Macro Definition Documentation
#define PROXYFS_TTY_REAL_FILE (arg) ((struct proxyfs_tty_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Definition at line 61 of file proxyfs_tty_real_file.h.
Referenced by proxyfs_tty_real_file_duplicate().
Function Documentation
void proxyfs_tty_real_file_destroy (struct proxyfs_tty_real_file * self)
<<public>> Deinitialize tty_real_file
Parameters
*self - pointer to this file instance
Definition at line 238 of file proxyfs_tty_real_file.c.
References mdbg, PROXYFS_FILE, proxyfs_file_get_file_ident(), PROXYFS_REAL_FILE, and proxyfs_real_file_destroy().
 {
     mdbg(INFO4, "Destroying tty file %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
     proxyfs_real_file_destroy( PROXYFS_REAL_FILE(self) );
 }
int proxyfs_tty_real_file_init (struct proxyfs_tty_real_file * self)
<<public>> Initialize tty_real_file
Parameters
*self - pointer to this file instance
Returns
zero on success
Definition at line 226 of file proxyfs_tty_real_file.c.
References PROXYFS_REAL_FILE, and proxyfs_real_file_init().
Referenced by proxyfs_tty_real_file_duplicate(), and proxyfs_tty_real_file_new().
 {
     int rtn = proxyfs_real_file_init( PROXYFS_REAL_FILE(self) );
     if( rtn == 0 )
         PROXYFS_REAL_FILE(self)->ops = &tty_real_file_ops;
     return rtn;
 }
struct proxyfs_tty_real_file* proxyfs_tty_real_file_new (void) read
<<public>> tty_real_file construktor
<<public>> tty_real_file construktor
Returns
new proxyfs_tty_real_file instance or NULL on error
Definition at line 247 of file proxyfs_tty_real_file.c.
References mdbg, and proxyfs_tty_real_file_init().
Referenced by proxyfs_server_overtake_file().
 {
     struct proxyfs_tty_real_file *self;
     self = (struct proxyfs_tty_real_file*)kmalloc(sizeof(struct proxyfs_tty_real_file), GFP_KERNEL);
     if( self == NULL ){
         mdbg(ERR3, "Allocating new proxyfs_tty_real_file failed");
         goto exit0;
     }
     if( proxyfs_tty_real_file_init( self ) != 0 )
         goto exit1;
     return self;
 exit1:
     kfree(self);
 exit0:
     return NULL;
 }