Clondike: KKC
KKC
KKC is a <<singleton>> class that provides interkernel communication facility.
Modules
kkc_arch class
This class describes a particular network architecture.
kkc_sock class
This is a generic KKC socket.
kkc_sock_sleeper class
The main purpose of this class is to make it easier to create and manage sleeping on KKC sockets.
Macros
#define KKC_MAX_WHERE_LENGTH (KKC_MAX_ARCH_LENGTH + KKC_SOCK_MAX_ADDR_LENGTH)
Maximum where string length.
Functions
static int kkc_establish (struct kkc_sock **sock, const char *where, int(*kkc_sock_method)(struct kkc_sock *, char *))
<<private>> Creates an architecture specific socket and starts listening or connects to the destination.
static int kkc_get_architecture (const char *where, struct kkc_arch **arch, char *addr)
<<private>> Helper function for parsing 'where' string and requesting for particular architecture structure.
int kkc_connect (struct kkc_sock **sock, const char *addr)
<<public>> Creates an architecture specific socket and performs a connection to the destination.
int kkc_listen (struct kkc_sock **sock, const char *addr)
<<public>> Creates an architecture specific socket and starts listening for incoming connnections.
Detailed Description
KKC is a <<singleton>> class that provides interkernel communication facility.
KKC sockets are used as an abstraction of a connection. This component ensures loading architecture specific modules via kkc_arch .
The communication features can be divided into two groups:
Socket creation and connecting to the destination or listening on a specified interface. This is handled by connect/listen operations as follows: Based on the string specified by the user (e.g. tcp:192.168.0.1:2000), it gets the instance of the particular architecture (tcp in this case) and delegates the work to the particular architecture to instantiate the socket. Then, the new socket is asked to setup a connection or listening.
Regular socket operations - to send/receive data, disconnect, append/remove a process to the socket waitqueue. These operations are KKC socket methods and this class provides only aliases.
Macro Definition Documentation
#define KKC_MAX_WHERE_LENGTH (KKC_MAX_ARCH_LENGTH + KKC_SOCK_MAX_ADDR_LENGTH)
Maximum where string length.
Definition at line 65 of file kkc.h.
Referenced by tcmi_ccnman_init_ctlfs_files(), and tcmi_penman_init_ctlfs_files().
Function Documentation
int kkc_connect (struct kkc_sock ** sock, const char * where)
<<public>> Creates an architecture specific socket and performs a connection to the destination.
<<public>> Creates an architecture specific socket and performs a connection to the destination.
The work is delegated to the kkc_establish() method along with the socket method that kkc_establish() should call on the newly created socket. To create new connection - kkc_sock.c::kkc_sock_connect() is used.
Parameters
**sock - ouput parameter - upon successful connection contains a valid socket
*where - address string with architecture prefix - e.g. tcp:192.168.0.1.2:2000
Returns
0 upon success
Definition at line 50 of file kkc.c.
References kkc_establish(), and kkc_sock_connect().
Referenced by proxyfs_peer_connect(), and tcmi_penman_connect().
 {
     return kkc_establish(sock, where, kkc_sock_connect);
 }
static int kkc_establish (struct kkc_sock ** sock, const char * where, int(*)(struct kkc_sock *, char *) kkc_sock_method) static
<<private>> Creates an architecture specific socket and starts listening or connects to the destination.
First an architecture, based on the prefix in the address, has to be retrieved. The creation of the socket is delegated to the archictecture. If everything goes fine, the socket is asked to perform an operation specified by the user - kkc_sock_method().
Parameters
**sock - ouput parameter - upon successful creation of a connection or listening contains a valid socket
*where - address string with architecture prefix - e.g. tcp:192.168.0.1.2:2000
*kkc_sock_method - method called on the created socket. This would yield a new connection or a listening, depending on what method the user specified
Returns
0 upon success
Definition at line 96 of file kkc.c.
References kkc_arch_obj_new(), kkc_arch_put(), kkc_get_architecture(), KKC_SOCK, KKC_SOCK_MAX_ADDR_LENGTH, kkc_sock_put(), and mdbg.
Referenced by kkc_connect(), and kkc_listen().
 {
     struct kkc_arch *arch;
     int err = 0;
     char addr[KKC_SOCK_MAX_ADDR_LENGTH];
     *sock = NULL;
     mdbg(INFO4, "Requesting architecture structure and network address");
     if ((err = kkc_get_architecture(where, &arch, addr)) < 0) {
         mdbg(ERR4, "Cannot get architecture structure");
         err = -ENOMEM;
         goto exit0;
     }
     /* instantiate the socket */
     if (!((*sock) = KKC_SOCK(kkc_arch_obj_new(arch)))) {
         mdbg(ERR4, "Failed to create a new socket");
         err = -ENOMEM;
         goto exit1;
     }
     if (kkc_sock_method(*sock, addr)) {
         mdbg(ERR4, "KKC socket method failed");
         err = -ENOMEM;
         goto exit2;
     }
     /* release the architecture as the socket has created its own
      * reference */
     kkc_arch_put(arch);
     return 0;
     /* error handling */
  exit2:
     kkc_sock_put(*sock);
     *sock = NULL; /* return no socket to the user */
  exit1:
     kkc_arch_put(arch);
  exit0:
     return err;
 }
static int kkc_get_architecture (const char * where, struct kkc_arch ** arch, char * addr) static
<<private>> Helper function for parsing 'where' string and requesting for particular architecture structure.
As side effect fills 'addr' string with address part of 'where'.
Parameters
*where - pointer to the where request string
**arch - output parameter - stores the architecture if one found
*addr - storage for the address string, that gets extracted from the where string
Returns
0 upon success.
Definition at line 148 of file kkc.c.
References kkc_arch_get_by_name(), KKC_MAX_ARCH_LENGTH, KKC_SOCK_MAX_ADDR_LENGTH, and mdbg.
Referenced by kkc_establish().
 {
     char arch_name[KKC_MAX_ARCH_LENGTH];
     char *colon_ptr;
     int colon_pos;
     int err = 0;
     /* find colon */
     if ((colon_ptr = strchr(where, ':')) == NULL) {
         mdbg(ERR4, "Invalid syntax - could not find colon");
         err = -EINVAL;
         goto exit0;
     }
     /* check position */
     colon_pos = colon_ptr - where;
     if (colon_pos > (KKC_MAX_ARCH_LENGTH - 1)) {
         mdbg(ERR4, "Invalid syntax - too long architecture name length");
         err = -EINVAL;
         goto exit0;
     }
     /* get architecture name */
     strncpy(arch_name, where, colon_pos);
     arch_name[colon_pos] = '\0';
     mdbg(INFO4, "Extracted architecture name: ""%s""", arch_name);
     /* get address */
     strncpy(addr, colon_ptr + 1, KKC_SOCK_MAX_ADDR_LENGTH - 1);
     addr[KKC_SOCK_MAX_ADDR_LENGTH - 1] = '\0';
     mdbg(INFO4, "Extracted address: ""%s""", addr);
     if (!(*arch = kkc_arch_get_by_name(arch_name))) {
         mdbg(ERR4, "Could not get architecture for '%s'", arch_name);
         err = -EINVAL;
     }
     /* error handling */
 exit0:
     return err;
 }
int kkc_listen (struct kkc_sock ** sock, const char * where)
<<public>> Creates an architecture specific socket and starts listening for incoming connnections.
<<public>> Creates an architecture specific socket and starts listening for incoming connnections.
The work is delegated to the kkc_establish() method along with the socket method that kkc_establish() should call on the newly created socket. To create new listening - kkc_sock.c::kkc_sock_connect() is used.
Parameters
**sock - ouput parameter - upon successful creation of listening contains a valid socket
*where - address string with architecture prefix - e.g. tcp:192.168.0.1.2:2000
Returns
0 upon success
Definition at line 69 of file kkc.c.
References kkc_establish(), and kkc_sock_listen().
Referenced by proxyfs_server_listen(), and tcmi_ccnman_listen().
 {
     return kkc_establish(sock, where, kkc_sock_listen);
 }