Clondike: tcmi_ctlfs_symlink class
tcmi_ctlfs_symlink class
tcmi_ctlfs_entry class
This class provides a robust solution for symbolic link creation.
Data Structures
struct tcmi_ctlfs_symlink
A symbolic link compound structure, extends the parent entry class.
Macros
#define TCMI_CTLFS_SYMLINK(e) ((struct tcmi_ctlfs_symlink *)e)
Casts an entry to a symlink.
Functions
static void tcmi_ctlfs_symlink_release (struct tcmi_ctlfs_entry *entry)
<<private>> This method is used to free the data associated with the symlink.
static int tcmi_ctlfs_symlink_get_link (struct tcmi_ctlfs_symlink *self, char *path, int length)
<<private>> The path is built as follows:
static void * tcmi_ctlfs_symlink_follow_link (struct dentry *dentry, struct nameidata *nd)
<<private>> Provides symlink resolution.
static void tcmi_ctlfs_symlink_put_link (struct dentry *dentry, struct nameidata *nd, void *vd)
<<private>> This VFS operation is called when the symlink pathname is not needed anymore by VFS.
struct tcmi_ctlfs_entry * tcmi_ctlfs_symlink_new (struct tcmi_ctlfs_entry *parent, struct tcmi_ctlfs_entry *target, const char namefmt[],...)
<<public>> Creates a new symbolic link instance.
Variables
static struct tcmi_ctlfs_ops tcmi_ctlfs_symlink_ops
A symlink requires special entry operations to free all resources.
static struct inode_operations tcmi_ctlfs_symlink_inode_operations
Custom VFS operations.
Detailed Description
This class provides a robust solution for symbolic link creation.
A symbolic link can be made to any entry within the TCMI control file system. The link instantiator provides only the target entry object that the link should point to. The class itself then takes care of creating the pathname to the target on fly as follow link requests come. There are three VFS inode operations that the link must provide:
follow_link - supplies the target object pathname to the VFS
put_link - a notification form VFS that the target pathname is not needed anymore after follow_link operation.
readlink - copies the target pathname to the buffer supplied by VFS
This class implements only the first 2 operations (tcmi_ctlfs_symlink_follow_link() and tcmi_ctlfs_symlink_put_link()). The third one uses VFS generic_readlink() that in turn invokes the custom tcmi_ctlfs_symlink_follow_link()).
Each symbolic link instance retains a reference to the target entry. This reference is released upon symlink destruction.
Data Structure Documentation
struct tcmi_ctlfs_symlink
A symbolic link compound structure, extends the parent entry class.
Contains a reference to the target entry.
Definition at line 69 of file tcmi_ctlfs_symlink.h.
Data Fields
struct tcmi_ctlfs_entry super parent class instance.
struct tcmi_ctlfs_entry * target_entry target entry, that the symbolic link is pointing to.
Macro Definition Documentation
#define TCMI_CTLFS_SYMLINK (e) ((struct tcmi_ctlfs_symlink *)e)
Casts an entry to a symlink.
Definition at line 87 of file tcmi_ctlfs_symlink.h.
Referenced by tcmi_ctlfs_symlink_follow_link(), and tcmi_ctlfs_symlink_release().
Function Documentation
static void* tcmi_ctlfs_symlink_follow_link (struct dentry * dentry, struct nameidata * nd) static
<<private>> Provides symlink resolution.
Supplies the pathname of the target entry that the symlink refers to. This code is adapted from sysfs/symlink.c.
allocates a whole page for the pathname (faster than kmalloc)
extracts the symlink from the dentry
asks the symlink for path resolution
Parameters
*dentry - points to the dentry of the symlink that is to be resolved
*nd - where the pathname is to be stored
Returns
NULL upon success
Definition at line 175 of file tcmi_ctlfs_symlink.c.
References TCMI_CTLFS_DENTRY_TO_ENTRY, TCMI_CTLFS_SYMLINK, and tcmi_ctlfs_symlink_get_link().
 {
     int error = -ENOMEM;
     unsigned long page = get_zeroed_page(GFP_ATOMIC);
     struct tcmi_ctlfs_symlink *symlink;
     if (page) {
         symlink = TCMI_CTLFS_SYMLINK(TCMI_CTLFS_DENTRY_TO_ENTRY(dentry));
         error = tcmi_ctlfs_symlink_get_link(symlink, (char *) page, PAGE_SIZE);
     }
     nd_set_link(nd, error ? ERR_PTR(error) : (char *)page);
     return NULL;
 }
static int tcmi_ctlfs_symlink_get_link (struct tcmi_ctlfs_symlink * self, char * path, int length) static
<<private>> The path is built as follows:
The path needs to be traversed to the root directory first '../', the number of these elements is determined by the depth of the symlink in the tree.
the minimum required buffer length is calculated based on:
symlink depth (see above)
pathname length of the target entry
the buffer is then filled with ../'s
the path of the target entry is then filled in
Should the target entry be invalid, the function terminates with an error access to the target entry is serialized by the lock.
Parameters
*self - pointer to this instance
*path - storage buffer for the path
length - maximum path length (storage buffer size)
Returns
0 upon success
Definition at line 128 of file tcmi_ctlfs_symlink.c.
References mdbg, self, size, TCMI_CTLFS_ENTRY, tcmi_ctlfs_entry_depth(), tcmi_ctlfs_entry_fill_path(), and tcmi_ctlfs_entry_path_length().
Referenced by tcmi_ctlfs_symlink_follow_link().
 {
     char * s;
     int depth, size;
     int err = -EINVAL;
     depth = tcmi_ctlfs_entry_depth(TCMI_CTLFS_ENTRY(self));
     /* we are interested in the depth of the parent entry, this is safe since
      a minimum symlink depth is 1 (when it resides in the root directory) */
     depth--;
     size = tcmi_ctlfs_entry_path_length(self->target_entry) + depth * 3 - 1;
     if (size > length) {
         err = -ENAMETOOLONG;
         goto exit0;
     }
     mdbg(INFO4,"depth = %d, size = %d", depth, size);
     for (s = path; depth--; s += 3)
         strcpy(s,"../");
     if (self->target_entry)
         tcmi_ctlfs_entry_fill_path(self->target_entry, path, size);
     mdbg(INFO3, "path = '%s'\n", path);
     return 0;
     /* error handling */
  exit0:
 /*   tcmi_ctlfs_symlink_unlock(self); */
     return err;
 }
struct tcmi_ctlfs_entry* tcmi_ctlfs_symlink_new (struct tcmi_ctlfs_entry * parent, struct tcmi_ctlfs_entry * target, const char namefmt[], ...) read
<<public>> Creates a new symbolic link instance.
<<public>> Creates a new symbolic link instance.
In addition, it retains an extra reference to the target object.
Parameters
*parent - pointer to the parent entry - has to be a directory
*target - target entry to which link should point to
namefmt - nameformat string (printf style)
Returns
new symlink instance or NULL
Definition at line 53 of file tcmi_ctlfs_symlink.c.
References args, mdbg, tcmi_ctlfs_symlink::target_entry, TCMI_CTLFS_ENTRY, tcmi_ctlfs_entry_get(), tcmi_ctlfs_entry_init(), tcmi_ctlfs_symlink_inode_operations, and tcmi_ctlfs_symlink_ops.
Referenced by tcmi_migman_create_symlink(), and tcmi_task_init().
 {
     struct tcmi_ctlfs_symlink *symlink;
     va_list args;
     va_start(args, namefmt);
     mdbg(INFO4, "Creating new symlink");
     if (!(symlink = kmalloc(sizeof(struct tcmi_ctlfs_symlink), GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate memory for symlink");
         goto exit0;
     }
     if (tcmi_ctlfs_entry_init(TCMI_CTLFS_ENTRY(symlink),
                   TCMI_CTLFS_ENTRY(parent),
                   S_IFLNK|S_IRWXUGO,
                   &tcmi_ctlfs_symlink_ops,
                   &tcmi_ctlfs_symlink_inode_operations,
                   NULL, namefmt, args)) {
         mdbg(ERR3, "Failed to initialize the symlink");
         goto exit1;
     }
     symlink->target_entry = tcmi_ctlfs_entry_get(target);
     va_end(args);
     return TCMI_CTLFS_ENTRY(symlink);
     /* error handling */
  exit1:
     kfree(symlink);
  exit0:
     va_end(args);
     return NULL;
 }
static void tcmi_ctlfs_symlink_put_link (struct dentry * dentry, struct nameidata * nd, void * vd) static
<<private>> This VFS operation is called when the symlink pathname is not needed anymore by VFS.
It allows us to release the memory needed for the pathname.
Parameters
*dentry - points to the dentry of the symlink
*nd - where the pathname resides
Definition at line 195 of file tcmi_ctlfs_symlink.c.
References mdbg.
 {
     char *page = nd_get_link(nd);
     mdbg(INFO4, "Destroying pathname related data");
     if (!IS_ERR(page)) {
         mdbg(INFO4, "Freeing pathname buffer");
         free_page((unsigned long)page);
     }
 }
static void tcmi_ctlfs_symlink_release (struct tcmi_ctlfs_entry * entry) static
<<private>> This method is used to free the data associated with the symlink.
The target entry's reference is decremented as the symlink doesn't need the target entry anymore.
Parameters
*entry - points to the symlink that is to be freed
Returns
0 upon success
Definition at line 101 of file tcmi_ctlfs_symlink.c.
References mdbg, tcmi_ctlfs_symlink::target_entry, tcmi_ctlfs_entry_name(), tcmi_ctlfs_entry_put(), and TCMI_CTLFS_SYMLINK.
 {
     struct tcmi_ctlfs_symlink *symlink = TCMI_CTLFS_SYMLINK(entry);
     mdbg(INFO3, "Target entry '%s' released", tcmi_ctlfs_entry_name(symlink->target_entry));
     tcmi_ctlfs_entry_put(symlink->target_entry);
 }
Variable Documentation
struct inode_operations tcmi_ctlfs_symlink_inode_operations static
Initial value:
= {
    .readlink = generic_readlink,
    .follow_link = tcmi_ctlfs_symlink_follow_link,
    .put_link = tcmi_ctlfs_symlink_put_link,
}
Custom VFS operations.
Readlink operation is reused from VFS (generic_readlink). The generic version in turn uses the follow_symlink() to get the link pathname.
Definition at line 218 of file tcmi_ctlfs_symlink.c.
Referenced by tcmi_ctlfs_symlink_new().
struct tcmi_ctlfs_ops tcmi_ctlfs_symlink_ops static
Initial value:
= {
    .entry_release = tcmi_ctlfs_symlink_release
}
A symlink requires special entry operations to free all resources.
Definition at line 209 of file tcmi_ctlfs_symlink.c.
Referenced by tcmi_ctlfs_symlink_new().