Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ctlfs/tcmi_ctlfs_symlink.c File Reference
tcmi_ctlfs_symlink.c File Reference
#include <linux/module.h>
#include <linux/errno.h>
#include <linux/dcache.h>
#include <linux/namei.h>
#include <linux/fs.h>
#include <asm/page.h>
#include <linux/slab.h>
#include "tcmi_ctlfs_symlink.h"
#include <dbg.h>
Macros
#define TCMI_CTLFS_SYMLINK_PRIVATE
Functions
struct tcmi_ctlfs_entry * tcmi_ctlfs_symlink_new (struct tcmi_ctlfs_entry *parent, struct tcmi_ctlfs_entry *target, const char namefmt[],...)
<<public>> Symbolic link is created as a regular ctlfs entry.
static void tcmi_ctlfs_symlink_release (struct tcmi_ctlfs_entry *entry)
<<private>> This method is used to free the data associated with the symlink.
static int tcmi_ctlfs_symlink_get_link (struct tcmi_ctlfs_symlink *self, char *path, int length)
<<private>> The path is built as follows:
static void * tcmi_ctlfs_symlink_follow_link (struct dentry *dentry, struct nameidata *nd)
<<private>> Provides symlink resolution.
static void tcmi_ctlfs_symlink_put_link (struct dentry *dentry, struct nameidata *nd, void *vd)
<<private>> This VFS operation is called when the symlink pathname is not needed anymore by VFS.
EXPORT_SYMBOL_GPL (tcmi_ctlfs_symlink_new)
Variables
static struct tcmi_ctlfs_ops tcmi_ctlfs_symlink_ops
A symlink requires special entry operations to free all resources.
static struct inode_operations tcmi_ctlfs_symlink_inode_operations
Custom VFS operations.
Macro Definition Documentation
#define TCMI_CTLFS_SYMLINK_PRIVATE
Definition at line 38 of file tcmi_ctlfs_symlink.c.
Function Documentation
EXPORT_SYMBOL_GPL (tcmi_ctlfs_symlink_new)
static void* tcmi_ctlfs_symlink_follow_link (struct dentry * dentry, struct nameidata * nd) static
<<private>> Provides symlink resolution.
Supplies the pathname of the target entry that the symlink refers to. This code is adapted from sysfs/symlink.c.
allocates a whole page for the pathname (faster than kmalloc)
extracts the symlink from the dentry
asks the symlink for path resolution
Parameters
*dentry - points to the dentry of the symlink that is to be resolved
*nd - where the pathname is to be stored
Returns
NULL upon success
Definition at line 176 of file tcmi_ctlfs_symlink.c.
References TCMI_CTLFS_DENTRY_TO_ENTRY, TCMI_CTLFS_SYMLINK, and tcmi_ctlfs_symlink_get_link().
 {
     int error = -ENOMEM;
     unsigned long page = get_zeroed_page(GFP_ATOMIC);
     struct tcmi_ctlfs_symlink *symlink;
     if (page) {
         symlink = TCMI_CTLFS_SYMLINK(TCMI_CTLFS_DENTRY_TO_ENTRY(dentry));
         error = tcmi_ctlfs_symlink_get_link(symlink, (char *) page, PAGE_SIZE);
     }
     nd_set_link(nd, error ? ERR_PTR(error) : (char *)page);
     return NULL;
 }
static int tcmi_ctlfs_symlink_get_link (struct tcmi_ctlfs_symlink * self, char * path, int length) static
<<private>> The path is built as follows:
The path needs to be traversed to the root directory first '../', the number of these elements is determined by the depth of the symlink in the tree.
the minimum required buffer length is calculated based on:
symlink depth (see above)
pathname length of the target entry
the buffer is then filled with ../'s
the path of the target entry is then filled in
Should the target entry be invalid, the function terminates with an error access to the target entry is serialized by the lock.
Parameters
*self - pointer to this instance
*path - storage buffer for the path
length - maximum path length (storage buffer size)
Returns
0 upon success
Definition at line 129 of file tcmi_ctlfs_symlink.c.
References mdbg, self, size, TCMI_CTLFS_ENTRY, tcmi_ctlfs_entry_depth(), tcmi_ctlfs_entry_fill_path(), and tcmi_ctlfs_entry_path_length().
Referenced by tcmi_ctlfs_symlink_follow_link().
 {
     char * s;
     int depth, size;
     int err = -EINVAL;
     depth = tcmi_ctlfs_entry_depth(TCMI_CTLFS_ENTRY(self));
     /* we are interested in the depth of the parent entry, this is safe since
      a minimum symlink depth is 1 (when it resides in the root directory) */
     depth--;
     size = tcmi_ctlfs_entry_path_length(self->target_entry) + depth * 3 - 1;
     if (size > length) {
         err = -ENAMETOOLONG;
         goto exit0;
     }
     mdbg(INFO4,"depth = %d, size = %d", depth, size);
     for (s = path; depth--; s += 3)
         strcpy(s,"../");
     if (self->target_entry)
         tcmi_ctlfs_entry_fill_path(self->target_entry, path, size);
     mdbg(INFO3, "path = '%s'\n", path);
     return 0;
     /* error handling */
  exit0:
 /*   tcmi_ctlfs_symlink_unlock(self); */
     return err;
 }
static void tcmi_ctlfs_symlink_put_link (struct dentry * dentry, struct nameidata * nd, void * vd) static
<<private>> This VFS operation is called when the symlink pathname is not needed anymore by VFS.
It allows us to release the memory needed for the pathname.
Parameters
*dentry - points to the dentry of the symlink
*nd - where the pathname resides
Definition at line 196 of file tcmi_ctlfs_symlink.c.
References mdbg.
 {
     char *page = nd_get_link(nd);
     mdbg(INFO4, "Destroying pathname related data");
     if (!IS_ERR(page)) {
         mdbg(INFO4, "Freeing pathname buffer");
         free_page((unsigned long)page);
     }
 }
static void tcmi_ctlfs_symlink_release (struct tcmi_ctlfs_entry * entry) static
<<private>> This method is used to free the data associated with the symlink.
The target entry's reference is decremented as the symlink doesn't need the target entry anymore.
Parameters
*entry - points to the symlink that is to be freed
Returns
0 upon success
Definition at line 102 of file tcmi_ctlfs_symlink.c.
References mdbg, tcmi_ctlfs_symlink::target_entry, tcmi_ctlfs_entry_name(), tcmi_ctlfs_entry_put(), and TCMI_CTLFS_SYMLINK.
 {
     struct tcmi_ctlfs_symlink *symlink = TCMI_CTLFS_SYMLINK(entry);
     mdbg(INFO3, "Target entry '%s' released", tcmi_ctlfs_entry_name(symlink->target_entry));
     tcmi_ctlfs_entry_put(symlink->target_entry);
 }