Clondike: circ_buf class
circ_buf class
ProxyFS
This class represent circular buffer used as read/write file buffers in ProxyFS.
Data Structures
struct circ_buf
Circular buffer structure.
Macros
#define CIRC_BUF_USE_VMALLOC (4 << 10)
Functions
int circ_buf_write (struct circ_buf *self, const char *buf, unsigned count)
<<public>> Initialize buffer structure
int circ_buf_write_user (struct circ_buf *self, const char *buf, unsigned count)
<<public>> Write to buffer from user space
int circ_buf_read (struct circ_buf *self, char *buf, unsigned count)
<<public>> Destructively read from buffer
int circ_buf_read_user (struct circ_buf *self, char *buf, unsigned count)
<<public>> Destructively read from buffer to userspace
static int circ_buf_init (struct circ_buf *self, unsigned size)
static void circ_buf_destroy (struct circ_buf *self)
<<public>> Opossite function to circ_buf_init
static unsigned circ_buf_get_read_size (const struct circ_buf *self)
<<public>> Returns maximum amount of data which are continuos - can by copied with one memcpy call
static void * circ_buf_get_read_addr (const struct circ_buf *self)
<<public>> Returns base address for reading -
static unsigned circ_buf_get_write_size (const struct circ_buf *self)
<<public>> Returns maximum amount of free space which is continuos - can by filled with one memcpy call
static void * circ_buf_get_write_addr (const struct circ_buf *self)
<<public>> Returns base address for writting -
static void circ_buf_adjust_read_ptr (struct circ_buf *self, const unsigned count)
<<public>> Adjust read pointer
static void circ_buf_adjust_write_ptr (struct circ_buf *self, const unsigned count)
<<public>> Adjust write pointer
static unsigned circ_buf_free_space (struct circ_buf *self)
<<public>> get total free space in buffer
static unsigned circ_buf_count (struct circ_buf *self)
<<public>> get count of total data contained in the buffer
int circ_buf_look_at (struct circ_buf *self, char *buf, unsigned count, size_t offset)
<<public>> Nondestructively read from buffer at offset
void circ_buf_dump (const char *prefix, struct circ_buf *self)
<<public>> Method used for debugging purposes.
Detailed Description
This class represent circular buffer used as read/write file buffers in ProxyFS.
Data Structure Documentation
struct circ_buf
Circular buffer structure.
Definition at line 49 of file buffer.h.
Data Fields
void * buf Pointer to memory which is used for buffering.
int full True if buffer is full.
void * read Read pointer.
unsigned size Memory size.
void * write Write pointer.
Macro Definition Documentation
#define CIRC_BUF_USE_VMALLOC (4 << 10)
Definition at line 46 of file buffer.h.
Referenced by circ_buf_destroy(), and circ_buf_init().
Function Documentation
static void circ_buf_adjust_read_ptr (struct circ_buf * self, const unsigned count) inline static
<<public>> Adjust read pointer
Parameters
self - pointer to this buffer instance
count - how much adjust WARNING: count must be between 0 and data total in buffer
Definition at line 168 of file buffer.h.
References count(), and self.
Referenced by circ_buf_look_at(), circ_buf_read(), circ_buf_read_user(), proxyfs_generic_real_file_write(), proxyfs_pipe_real_file_write(), proxyfs_proxy_file_submit_read_to_peer(), proxyfs_real_file_submit_read_to_peer(), and proxyfs_tty_real_file_write().
 {
     if( count > 0 ){
         self->full = 0;
         self->read += count;
         if( self->read >= self->buf + self->size || self->read < self->buf )
             self->read -= self->size;
     }
 }
static void circ_buf_adjust_write_ptr (struct circ_buf * self, const unsigned count) inline static
<<public>> Adjust write pointer
Parameters
self - pointer to this buffer instance
count - how much adjust WARNING: count must be between 0 and free space in buffer
Definition at line 182 of file buffer.h.
References count(), and self.
Referenced by circ_buf_write(), circ_buf_write_user(), proxyfs_generic_real_file_read(), proxyfs_pipe_real_file_read(), and proxyfs_tty_real_file_read().
 {
     if( count > 0 ){
         self->write += count;
         if( self->write >= self->buf + self->size || self->write < self->buf )
             self->write -= self->size;
         if( self->write == self->read ) self->full = 1;
     }
 }
static unsigned circ_buf_count (struct circ_buf * self) inline static
<<public>> get count of total data contained in the buffer
Parameters
self - pointer to this buffer instance
Returns
total bytes contained by the buffer
Definition at line 214 of file buffer.h.
References circ_buf_free_space().
Referenced by circ_buf_dump(), circ_buf_read(), circ_buf_read_user(), proxyfs_file_get_status(), proxyfs_pipe_real_file_write(), proxyfs_proxy_file_write_buf_info(), and proxyfs_real_file_write_buf_info().
 {
     return self->size - circ_buf_free_space(self);
 }
static void circ_buf_destroy (struct circ_buf * self) inline static
<<public>> Opossite function to circ_buf_init
Parameters
self - pointer to this buffer instance
Definition at line 100 of file buffer.h.
References CIRC_BUF_USE_VMALLOC, and self.
Referenced by proxyfs_file_destroy(), and proxyfs_file_init().
 {
     if( self->size >= CIRC_BUF_USE_VMALLOC )
         vfree(self->buf);
     else
         kfree(self->buf);
     self->size = 0;
     self->read = NULL;
     self->write = NULL;
 }
void circ_buf_dump (const char * prefix, struct circ_buf * self)
<<public>> Method used for debugging purposes.
Dumps content of a circular buffer to debug output
Definition at line 184 of file buffer.c.
References circ_buf_count(), circ_buf_get_read_addr(), circ_buf_get_read_size(), debug_enabled, mdbg, and self.
Referenced by proxyfs_pipe_real_file_read(), proxyfs_pipe_real_file_write(), proxyfs_tty_real_file_read(), and proxyfs_tty_real_file_write().
{
     if ( debug_enabled ) {
         // Size till overlap
         int read_size = circ_buf_get_read_size(self);
         // Maximum read size
         unsigned maximum_read_size = circ_buf_count(self);
         mdbg(INFO3, "%s First part content (%d) %.*s.", prefix, (int)read_size, (int)read_size, (char*)circ_buf_get_read_addr(self));
         if ( read_size < maximum_read_size ) {
             mdbg(INFO3, "%s Second part content (%d) %.*s.", prefix, (int)maximum_read_size-read_size, (int)maximum_read_size-read_size, (char*)self->buf);
         }
     }
 }
static unsigned circ_buf_free_space (struct circ_buf * self) inline static
<<public>> get total free space in buffer
Parameters
self - pointer to this buffer instance
Returns
amount of free bytes in buffer
Definition at line 197 of file buffer.h.
References self.
Referenced by circ_buf_count(), proxyfs_pipe_proxy_file_write_user(), proxyfs_pipe_real_file_read(), and proxyfs_proxy_file_wait_for_space_interruptible().
 {
     if( self->write > self->read )
         return (self->size - (self->write - self->read));
     else if( self->write < self->read )
         return self->read - self->write;
     else if( self->full )
         return 0;
     // buf is empty
     return self->size;
 }
static void* circ_buf_get_read_addr (const struct circ_buf * self) inline static
<<public>> Returns base address for reading -
Parameters
self - pointer to this buffer instance
Returns
address from which read should start
Definition at line 131 of file buffer.h.
Referenced by circ_buf_dump(), circ_buf_read(), circ_buf_read_user(), proxyfs_generic_real_file_write(), proxyfs_pipe_real_file_write(), proxyfs_proxy_file_write_buf_info(), proxyfs_real_file_write_buf_info(), and proxyfs_tty_real_file_write().
 {
     return self->read;
 }
static unsigned circ_buf_get_read_size (const struct circ_buf * self) inline static
<<public>> Returns maximum amount of data which are continuos - can by copied with one memcpy call
Parameters
self - pointer to this buffer instance
Returns
the amount of data
Definition at line 117 of file buffer.h.
References self.
Referenced by circ_buf_dump(), circ_buf_read(), circ_buf_read_user(), proxyfs_file_get_status(), proxyfs_generic_real_file_write(), proxyfs_pipe_real_file_write(), proxyfs_proxy_file_write_buf_info(), proxyfs_real_file_write_buf_info(), and proxyfs_tty_real_file_write().
 {
     if( self->write > self->read )
         return self->write - self->read;
     else if( self->write < self->read || self->full )
         return (self->buf + self->size) - self->read;
     return 0;
 }
static void* circ_buf_get_write_addr (const struct circ_buf * self) inline static
<<public>> Returns base address for writting -
Parameters
self - pointer to this buffer instance
Returns
address from which write should start
Definition at line 159 of file buffer.h.
Referenced by circ_buf_write(), circ_buf_write_user(), proxyfs_generic_real_file_read(), proxyfs_pipe_real_file_read(), and proxyfs_tty_real_file_read().
 {
     return self->write;
 }
static unsigned circ_buf_get_write_size (const struct circ_buf * self) inline static
<<public>> Returns maximum amount of free space which is continuos - can by filled with one memcpy call
Parameters
self - pointer to this buffer instance
Returns
the amount of data
Definition at line 142 of file buffer.h.
References self.
Referenced by circ_buf_write(), circ_buf_write_user(), proxyfs_file_get_status(), proxyfs_generic_real_file_read(), proxyfs_pipe_real_file_read(), and proxyfs_tty_real_file_read().
 {
     if( self->write > self->read )
         return self->buf + self->size - self->write;
     else if( self->write < self->read )
         return self->read - self->write;
     else if( self->full )
         return 0;
     // buf is empty
     return self->buf + self->size - self->write;
 }
static int circ_buf_init (struct circ_buf * self, unsigned size) inline static
Definition at line 81 of file buffer.h.
References CIRC_BUF_USE_VMALLOC, self, and size.
Referenced by proxyfs_file_init().
 {
     if( size >= CIRC_BUF_USE_VMALLOC )
         self->buf = vmalloc( size );
     else
         self->buf = kmalloc( size, GFP_KERNEL );
     if( self->buf == NULL ) return -1;
     self->size = size;
     self->read = self->buf;
     self->write = self->buf;
     self->full = 0;
     return 0;
 }
int circ_buf_look_at (struct circ_buf * self, char * buf, unsigned count, size_t offset)
<<public>> Nondestructively read from buffer at offset
Parameters
self - pointer to this buffer instance
buf - pointer to memory in which will be data written
count - maximum data size. Can be actually more than current content size of buffer, in this case less bytes are read
offset - read offset
Returns
amount of bytes read
Definition at line 168 of file buffer.c.
References circ_buf_adjust_read_ptr(), and circ_buf_read().
Referenced by proxyfs_pipe_real_file_write(), proxyfs_proxy_file_read_to_peer(), and proxyfs_real_file_read_to_peer().
 {
     int rs;
     void *read = self->read;
     int full = self->full;
     circ_buf_adjust_read_ptr(self, offset);
     rs = circ_buf_read(self, buf, count);
     self->read = read;
     self->full = full;
     return rs;
 }
int circ_buf_read (struct circ_buf * self, char * buf, unsigned count)
<<public>> Destructively read from buffer
Parameters
self - pointer to this buffer instance
buf - pointer to memory in which will be data written
count - maximum data size. Can be actually more than current content size of buffer, in this case less bytes are read
Returns
amount of bytes read
Definition at line 103 of file buffer.c.
References circ_buf_adjust_read_ptr(), circ_buf_count(), circ_buf_get_read_addr(), circ_buf_get_read_size(), circ_buf_read(), and count().
Referenced by circ_buf_look_at(), and circ_buf_read().
 {
     unsigned rs;
     unsigned maximum_size = circ_buf_count(self);
     if ( count > maximum_size )
         count = maximum_size;
     rs = circ_buf_get_read_size(self);
     if(rs){
         if( count < rs ){
             memcpy( buf, circ_buf_get_read_addr(self), count );
             circ_buf_adjust_read_ptr(self, count);
             return count;
         }
         else{
             memcpy( buf, circ_buf_get_read_addr(self), rs );
             circ_buf_adjust_read_ptr(self, rs);
             return rs + circ_buf_read( self, buf + rs, count - rs );
         }
     }
     return 0;
 }
int circ_buf_read_user (struct circ_buf * self, char * buf, unsigned count)
<<public>> Destructively read from buffer to userspace
Parameters
self - pointer to this buffer instance
buf - pointer to memory in which will be data written
count - maximum data size
Returns
amount of bytes read
Definition at line 133 of file buffer.c.
References circ_buf_adjust_read_ptr(), circ_buf_count(), circ_buf_get_read_addr(), circ_buf_get_read_size(), circ_buf_read_user(), and count().
Referenced by circ_buf_read_user(), proxyfs_generic_proxy_file_read_user(), and proxyfs_pipe_proxy_file_read_user().
 {
     unsigned rs;
     unsigned maximum_size = circ_buf_count(self);
     if ( count > maximum_size )
         count = maximum_size;
     rs = circ_buf_get_read_size(self);
     if(rs){
         if( count < rs ){
             if ( __copy_to_user( buf, circ_buf_get_read_addr(self), count ) )
                 return -EFAULT;
             circ_buf_adjust_read_ptr(self, count);
             return count;
         }
         else{
             if ( __copy_to_user( buf, circ_buf_get_read_addr(self), rs ) )
                 return -EFAULT;
             circ_buf_adjust_read_ptr(self, rs);
             return rs + circ_buf_read_user( self, buf + rs, count - rs );
         }
     }
     return 0;
 }
int circ_buf_write (struct circ_buf * self, const char * buf, unsigned count)
<<public>> Initialize buffer structure
Parameters
self - pointer to this buffer instance
size - buffer size
Returns
zero on success<<public>> Write to buffer
<<public>> Initialize buffer structure
Parameters
self - pointer to this buffer instance
buf - pointer to data, which will be written
count - data size
Returns
amount of bytes written
Definition at line 46 of file buffer.c.
References circ_buf_adjust_write_ptr(), circ_buf_get_write_addr(), circ_buf_get_write_size(), circ_buf_write(), and count().
Referenced by circ_buf_write(), proxyfs_proxy_file_write_from_peer(), and proxyfs_real_file_write_from_peer().
 {
     unsigned wrs;
     wrs = circ_buf_get_write_size(self);
     if(wrs){
         if( count < wrs ){
             memcpy( circ_buf_get_write_addr(self), buf, count );
             circ_buf_adjust_write_ptr(self, count);
             return count;
         }
         else{
             memcpy( circ_buf_get_write_addr(self), buf, wrs );
             circ_buf_adjust_write_ptr(self, wrs);
             return wrs + circ_buf_write( self, buf + wrs, count - wrs );
         }
     }
     return 0;
 }
int circ_buf_write_user (struct circ_buf * self, const char * buf, unsigned count)
<<public>> Write to buffer from user space
Parameters
self - pointer to this buffer instance
buf - pointer to data in userspace, which will be written
count - data size
Returns
amount of bytes written
Definition at line 72 of file buffer.c.
References circ_buf_adjust_write_ptr(), circ_buf_get_write_addr(), circ_buf_get_write_size(), circ_buf_write_user(), and count().
Referenced by circ_buf_write_user(), proxyfs_generic_proxy_file_write_user(), and proxyfs_pipe_proxy_file_write_user().
 {
     unsigned wrs;
     void *ptr;
     wrs = circ_buf_get_write_size(self);
     if(wrs){
         if( count < wrs ){
             ptr = circ_buf_get_write_addr(self);
             if ( __copy_from_user( ptr, buf, count ) )
                 return -EFAULT;
             circ_buf_adjust_write_ptr(self, count);
             return count;
         }
         else{
             ptr = circ_buf_get_write_addr(self);
             if ( __copy_from_user( ptr, buf, wrs ) )
                 return -EFAULT;
             circ_buf_adjust_write_ptr(self, wrs);
             return wrs + circ_buf_write_user( self, buf + wrs, count - wrs );
         }
     }
     return 0;
 }