Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/migration/fs/fs_mounter_register.h File Reference
fs_mounter_register.h File Reference
Functions
struct fs_mounter * get_new_mounter (struct fs_mount_params *params)
Returns new mounter instance with specified params.
void free_mounter (struct fs_mounter *mounter)
Releases mounter instance.
Function Documentation
void free_mounter (struct fs_mounter * mounter)
Releases mounter instance.
Definition at line 25 of file fs_mounter_register.c.
References fs_mounter::free.
Referenced by tcmi_migcom_immigrate(), and tcmi_migcom_migrated_task().
{
     if ( !mounter )
         return;
     if ( mounter->free )
         mounter->free(mounter);
     kfree(mounter);
 }
struct fs_mounter* get_new_mounter (struct fs_mount_params * params) read
Returns new mounter instance with specified params.
Definition at line 14 of file fs_mounter_register.c.
References fs_mount_params::mount_type, new_9p_fs_mounter(), and new_9p_global_fs_mounter().
Referenced by tcmi_migcom_immigrate(), and tcmi_migcom_migrated_task().
{
     if ( strcmp("9p",params->mount_type) == 0 )
         return new_9p_fs_mounter(params);
     if ( strcmp("9p-global",params->mount_type) == 0 )
         return new_9p_global_fs_mounter(params);
     return NULL;
 }