Clondike: tcmi_queue class
tcmi_queue class
lib
The queue is implemented using a doubly linked list - provided by kernel.
Data Structures
struct tcmi_queue
compound structure
Macros
#define tcmi_queue_remove_entry(self, object, member)
<<public>> Removes an entry from the head of the queue.
#define __tcmi_queue_remove_entry(self, object, member)
<<public>> Removes an entry from the head of the queue.
Enumerations
enum tcmi_queue_type_t { TCMI_QUEUE_STATIC, TCMI_QUEUE_DYNAMIC }
Denotes whether the queue has been staticaly or dynamically created.
Functions
static void tcmi_queue_init (struct tcmi_queue *self)
<<public>> Queue initializer - for static allocation.
static struct tcmi_queue * tcmi_queue_new (void)
<<public>> Queue constructor.
static struct tcmi_queue * tcmi_queue_get (struct tcmi_queue *self)
<<public>> Queue instance accessor.
static void tcmi_queue_put (struct tcmi_queue *self)
<<public>> Decrements the reference counter, when the count reaches 0, the instance is destroyed.
static void tcmi_queue_lock (struct tcmi_queue *self)
<<public>> Locks the instance data.
static void tcmi_queue_unlock (struct tcmi_queue *self)
<<public>> Unlocks the instance data
static int tcmi_queue_empty (struct tcmi_queue *self)
static void __tcmi_queue_add (struct tcmi_queue *self, struct list_head *element)
<<public>> Adds an element to the queue - lock free version, assumes the lock is already held.
static void tcmi_queue_add (struct tcmi_queue *self, struct list_head *element)
<<public>> Locks the queue and appends a new element to the tail.
static struct list_head * __tcmi_queue_remove (struct tcmi_queue *self)
<<public>> Removes an element in the head of the queue, assumes the lock is held already.
static struct list_head * tcmi_queue_remove (struct tcmi_queue *self)
<<public>> Locks the queue and removes removes an element in the head of the queue, assumes the lock is held already.
static int tcmi_queue_wait_on_empty_interruptible (struct tcmi_queue *self)
<<public>> Puts the calling process to sleep as long as the queue is empty.
static int tcmi_queue_wait_on_empty_interruptible_timout (struct tcmi_queue *self, int timeout)
<<public>> Puts the calling process to sleep as long as the queue is empty or the timeout expires.
Detailed Description
The queue is implemented using a doubly linked list - provided by kernel.
In addition, it contains a wait queue for process that want to be notified upon addition of a new element. Basic methods:
add - appends an element to the tail of the queue
empty - true if the queue is empty
remove_head - returns the element from the head of the queue and removes it - this operation is atomic.
wait_on_empty - the calling process is put a sleep, until the queue contains at least 1 element.
Data Structure Documentation
struct tcmi_queue
compound structure
Definition at line 69 of file tcmi_queue.h.
Data Fields
spinlock_t q_lock spin lock - serializes access to the queue
struct list_head queue The actual queue.
atomic_t ref_count reference counter for dynamically created queues
tcmi_queue_type_t type describes how the queue has been created
wait_queue_head_t wq Sleeping processes, that are to be notified upon addition of a new element.
Macro Definition Documentation
#define __tcmi_queue_remove_entry (self, object, member)
Value:
do {                                    \
    struct list_head *__q_entry;                    \
    object = NULL;                          \
    if ((__q_entry = __tcmi_queue_remove(self)))            \
        object = list_entry(__q_entry, typeof(*object), member);    \
} while (0)
<<public>> Removes an entry from the head of the queue.
Assumes the queue has already been locked.
Parameters
self - pointer to this queue instance
object - pointer that will hold the head element
member - name of the member within the object used for queueing
Definition at line 282 of file tcmi_queue.h.
Referenced by tcmi_task_flush_and_submit_method().
#define tcmi_queue_remove_entry (self, object, member)
Value:
do {                                    \
    struct list_head *__q_entry;                    \
    object = NULL;                          \
    if ((__q_entry = tcmi_queue_remove(self)))          \
        object = list_entry(__q_entry, typeof(*object), member);    \
} while (0)
<<public>> Removes an entry from the head of the queue.
Parameters
self - pointer to this queue instance
object - pointer that will hold the head element
member - name of the member within the object used for queueing
Definition at line 266 of file tcmi_queue.h.
Referenced by tcmi_migman_msg_thread(), tcmi_task_process_methods(), tcmi_task_process_msg(), and tcmi_task_put().
Enumeration Type Documentation
enum tcmi_queue_type_t
Denotes whether the queue has been staticaly or dynamically created.
This is needed if somebody issues a put on a static queue, so that no kfree is performed
Enumerator
TCMI_QUEUE_STATIC
TCMI_QUEUE_DYNAMIC
Definition at line 63 of file tcmi_queue.h.
              {
     TCMI_QUEUE_STATIC,
     TCMI_QUEUE_DYNAMIC
 } tcmi_queue_type_t;
Function Documentation
static void __tcmi_queue_add (struct tcmi_queue * self, struct list_head * element) inline static
<<public>> Adds an element to the queue - lock free version, assumes the lock is already held.
Wakes up a task from the wait queue, so that it can pickup the new element.
Parameters
*self - pointer to this queue instance
*element - element to be added to the queue
Definition at line 206 of file tcmi_queue.h.
References self.
Referenced by tcmi_queue_add(), and tcmi_task_flush_and_submit_method().
 {
     list_add_tail(element, &self->queue);
     wake_up(&self->wq);
 }
static struct list_head* __tcmi_queue_remove (struct tcmi_queue * self) static read
<<public>> Removes an element in the head of the queue, assumes the lock is held already.
Parameters
*self - pointer to this queue instance
Returns
- element in the head of the queue
Definition at line 231 of file tcmi_queue.h.
References tcmi_queue_empty().
Referenced by tcmi_queue_remove().
 {
     struct list_head *element;
     if (tcmi_queue_empty(self))
         return NULL;
     else {
         element = self->queue.next;
         list_del_init(element);
         return (element);
     }
 }
static void tcmi_queue_add (struct tcmi_queue * self, struct list_head * element) inline static
<<public>> Locks the queue and appends a new element to the tail.
Parameters
*self - pointer to this queue instance
*element - element to be added to the queue
Definition at line 217 of file tcmi_queue.h.
References __tcmi_queue_add(), tcmi_queue_lock(), and tcmi_queue_unlock().
Referenced by tcmi_msg_deliver().
 {
     tcmi_queue_lock(self);
     __tcmi_queue_add(self, element);
     tcmi_queue_unlock(self);
 }
static int tcmi_queue_empty (struct tcmi_queue * self) inline static
Returns
1 when queue is empty
Definition at line 193 of file tcmi_queue.h.
References self.
Referenced by __tcmi_queue_remove(), tcmi_queue_wait_on_empty_interruptible(), tcmi_queue_wait_on_empty_interruptible_timout(), tcmi_task_deliver_msg(), tcmi_task_flush_and_submit_method(), tcmi_task_process_methods(), tcmi_task_process_msg(), and tcmi_task_put().
 {
     return list_empty(&self->queue);
 }
static struct tcmi_queue* tcmi_queue_get (struct tcmi_queue * self) static read
<<public>> Queue instance accessor.
Increments the reference counter
Parameters
*self - pointer to this queue instance
Returns
- self
Definition at line 138 of file tcmi_queue.h.
References self.
 {
     if (!self)
         return NULL;
     atomic_inc(&self->ref_count);
     return self;
 }
static void tcmi_queue_init (struct tcmi_queue * self) inline static
<<public>> Queue initializer - for static allocation.
The reference counter is set to 1.
Parameters
*self - pointer to this queue instance
Definition at line 97 of file tcmi_queue.h.
References self, and TCMI_QUEUE_STATIC.
Referenced by tcmi_migman_init(), tcmi_queue_new(), and tcmi_task_init().
 {
     atomic_set(&self->ref_count, 1);
     spin_lock_init(&self->q_lock);
     INIT_LIST_HEAD(&self->queue);
     self->type = TCMI_QUEUE_STATIC;
     init_waitqueue_head(&self->wq);
 }
static void tcmi_queue_lock (struct tcmi_queue * self) inline static
<<public>> Locks the instance data.
Spin lock used - no sleeping allowed!
Parameters
*self - pointer to this queue instance
Definition at line 175 of file tcmi_queue.h.
References self.
Referenced by tcmi_queue_add(), tcmi_queue_remove(), and tcmi_task_flush_and_submit_method().
 {
     spin_lock(&self->q_lock);
 }
static struct tcmi_queue* tcmi_queue_new (void) static read
<<public>> Queue constructor.
Returns
a new queue or NULL
Definition at line 112 of file tcmi_queue.h.
References mdbg, TCMI_QUEUE_DYNAMIC, tcmi_queue_init(), and tcmi_queue::type.
 {
     struct tcmi_queue *q;
     q = kmalloc(sizeof(struct tcmi_queue), GFP_ATOMIC);
     if (!q) {
         mdbg(ERR3, "Can't allocated memory for a queue");
         goto exit0;
     }
     tcmi_queue_init(q);
     /* mark the queue dynamic, so that it is released on the last 'put' */
     q->type = TCMI_QUEUE_DYNAMIC;
     mdbg(INFO4, "Allocated new queue %p", q);
     return q;
     /* error handling */
  exit0:
     return NULL;
 }
static void tcmi_queue_put (struct tcmi_queue * self) inline static
<<public>> Decrements the reference counter, when the count reaches 0, the instance is destroyed.
Parameters
*self - pointer to this queue instance
Definition at line 152 of file tcmi_queue.h.
References mdbg, self, and TCMI_QUEUE_STATIC.
 {
     if (!self)
         return;
     if (atomic_dec_and_test(&self->ref_count)) {
         if (self->type == TCMI_QUEUE_STATIC)
             mdbg(INFO4, "Released last reference to a static queue");
         else {
             mdbg(INFO4, "Released last reference to a dynamic queue %p",
                  self);
             kfree(self);
         }
     }
 }
static struct list_head* tcmi_queue_remove (struct tcmi_queue * self) static read
<<public>> Locks the queue and removes removes an element in the head of the queue, assumes the lock is held already.
Parameters
*self - pointer to this queue instance
Returns
- element in the head of the queue
Definition at line 250 of file tcmi_queue.h.
References __tcmi_queue_remove(), tcmi_queue_lock(), and tcmi_queue_unlock().
 {
     struct list_head *element;
     tcmi_queue_lock(self);
     element = __tcmi_queue_remove(self);
     tcmi_queue_unlock(self);
     return element;
 }
static void tcmi_queue_unlock (struct tcmi_queue * self) inline static
<<public>> Unlocks the instance data
Parameters
*self - pointer to this queue instance
Definition at line 185 of file tcmi_queue.h.
References self.
Referenced by tcmi_queue_add(), tcmi_queue_remove(), and tcmi_task_flush_and_submit_method().
 {
     spin_unlock(&self->q_lock);
 }
static int tcmi_queue_wait_on_empty_interruptible (struct tcmi_queue * self) inline static
<<public>> Puts the calling process to sleep as long as the queue is empty.
Parameters
*self - pointer to this queue instance
Returns
-ERESTARTSYS on signal arrival
Definition at line 297 of file tcmi_queue.h.
References self, and tcmi_queue_empty().
Referenced by tcmi_migman_msg_thread(), and tcmi_task_process_msg().
 {
     /* Sleep until the queue is non empty */
     return wait_event_interruptible_exclusive(self->wq, (!tcmi_queue_empty(self)));
 }
static int tcmi_queue_wait_on_empty_interruptible_timout (struct tcmi_queue * self, int timeout) inline static
<<public>> Puts the calling process to sleep as long as the queue is empty or the timeout expires.
Parameters
*self - pointer to this queue instance
timeout - specified timeout
Returns
-ERESTARTSYS on signal arrival or timeout (>0) if the timer went off
Definition at line 312 of file tcmi_queue.h.
References self, and tcmi_queue_empty().
 {
     /* Sleep until the queue is non empty */
     return wait_event_interruptible_timeout(self->wq, (!tcmi_queue_empty(self)),
                         timeout);
 }