Clondike: tcmi_rpcresp_procmsg class
tcmi_rpcresp_procmsg class
tcmi_procmsg class
: Updadate comment
Data Structures
struct tcmi_rpcresp_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Macros
#define TCMI_RPCRESP_PROCMSG_DONTFREE 1
<<public>> Don't free data on put
#define TCMI_RPCRESP_PROCMSG_KFREE 2
<<public>> Free data using kfree on put
#define TCMI_RPCRESP_PROCMSG_VFREE 3
<<public>> Free data usinf vfree on put
#define TCMI_RPCRESP_PROCMSG_DSC TCMI_MSG_DSC(TCMI_RPCRESP_PROCMSG_ID, tcmi_rpcresp_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
#define TCMI_RPCRESP_PROCMSG(m) ((struct tcmi_rpcresp_procmsg*)m)
Casts to the tcmi_rpcresp_procmsg instance.
Functions
static int tcmi_rpcresp_procmsg_recv (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_rpcresp_procmsg_send (struct tcmi_procmsg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static void tcmi_rpcresp_procmsg_free (struct tcmi_procmsg *self)
<<private>> Frees RPC message resources
struct tcmi_rpcresp_procmsg __attribute__ ((__packed__))
struct tcmi_msg * tcmi_rpcresp_procmsg_new_rx (u_int32_t msg_id)
<<public>> RPC response process message rx constructor.
struct tcmi_msg * tcmi_rpcresp_procmsg_new_tx (u_int32_t trans_id, pid_t dst_pid)
<<public>> RPC response process message tx constructor.
static void * tcmi_rpcresp_procmsg_data_base (struct tcmi_rpcresp_procmsg *self, unsigned int index)
<<public>> Get pointer do data
static unsigned long tcmi_rpcresp_procmsg_data_size (struct tcmi_rpcresp_procmsg *self, unsigned int index)
<<public>> Get RPC parameter size.
static void tcmi_rpcresp_procmsg_free_on_put (struct tcmi_rpcresp_procmsg *self, unsigned int index, int action)
<<public>> Set if and how data will be freed on last put
struct tcmi_msg * tcmi_rpcresp_procmsg_get_response (unsigned int rpcnum,...)
<<public>> Creates and sends rpc_proc_msg and returns response
struct tcmi_msg * tcmi_rpcresp_procmsg_create (struct tcmi_msg *m, long rtn_code,...)
<<public>> Create response to rpc message
static long tcmi_rpcresp_procmsg_rtn (struct tcmi_rpcresp_procmsg *self)
<<public>> Return RPC return code.
static int tcmi_rpcresp_procmsg_num (struct tcmi_rpcresp_procmsg *self)
<<public>> Return RPC number.
Variables
static struct tcmi_procmsg_ops rpcresp_procmsg_ops
Message operations that support polymorphism.
Detailed Description
: Updadate comment
Data Structure Documentation
struct tcmi_rpcresp_procmsg
Compound structure, inherits from tcmi_procmsg_class.
Definition at line 45 of file tcmi_rpcresp_procmsg.h.
Data Fields
void ** elem_base Array of pointers to elements.
u_int8_t * elem_free Array describing how to free elements on msg_put.
u_int32_t * elem_size Array with size of elements.
u_int16_t nmemb Number of memory elements.
u_int16_t rpcnum RPC number.
int64_t rtn_code Return code of remote procedure.
struct tcmi_procmsg super parent class instance
Macro Definition Documentation
#define TCMI_RPCRESP_PROCMSG (m) ((struct tcmi_rpcresp_procmsg*)m)
Casts to the tcmi_rpcresp_procmsg instance.
Definition at line 140 of file tcmi_rpcresp_procmsg.h.
Referenced by tcmi_guest_rpc_sys_fork(), tcmi_guest_rpc_sys_getgroups(), tcmi_guest_rpc_sys_getresgid(), tcmi_guest_rpc_sys_getresuid(), tcmi_guest_rpc_sys_rt_sigqueueinfo(), tcmi_guest_rpc_sys_setgroups(), tcmi_guest_rpc_sys_wait4(), tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_free(), tcmi_rpcresp_procmsg_new_rx(), tcmi_rpcresp_procmsg_new_tx(), tcmi_rpcresp_procmsg_recv(), tcmi_rpcresp_procmsg_send(), tcmi_shadow_rpc_do_fork(), tcmi_shadow_rpc_getgroups(), tcmi_shadow_rpc_getresgid(), tcmi_shadow_rpc_getresuid(), and tcmi_shadow_rpc_sys_wait4().
#define TCMI_RPCRESP_PROCMSG_DONTFREE 1
<<public>> Don't free data on put
Definition at line 111 of file tcmi_rpcresp_procmsg.h.
Referenced by tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_free(), and tcmi_rpcresp_procmsg_recv().
#define TCMI_RPCRESP_PROCMSG_DSC TCMI_MSG_DSC(TCMI_RPCRESP_PROCMSG_ID, tcmi_rpcresp_procmsg_new_rx, tcmi_err_procmsg_new_rx)
Message descriptor for the factory class, for error handling we used tcmi_errmsg_class.
Definition at line 136 of file tcmi_rpcresp_procmsg.h.
#define TCMI_RPCRESP_PROCMSG_KFREE 2
<<public>> Free data using kfree on put
Definition at line 113 of file tcmi_rpcresp_procmsg.h.
Referenced by tcmi_rpcresp_procmsg_free(), tcmi_rpcresp_procmsg_recv(), tcmi_shadow_rpc_do_fork(), tcmi_shadow_rpc_getgroups(), tcmi_shadow_rpc_getresgid(), tcmi_shadow_rpc_getresuid(), and tcmi_shadow_rpc_sys_wait4().
#define TCMI_RPCRESP_PROCMSG_VFREE 3
<<public>> Free data usinf vfree on put
Definition at line 115 of file tcmi_rpcresp_procmsg.h.
Referenced by tcmi_rpcresp_procmsg_free().
Function Documentation
struct tcmi_rpcresp_procmsg __attribute__ ((__packed__))
struct tcmi_msg* tcmi_rpcresp_procmsg_create (struct tcmi_msg * m, long rtn_code, ...) read
<<public>> Create response to rpc message
Parameters
m - message we are responding to
rtn_code - value returned by RPC
... - size of the first arg., pointer to the first arg., size of the second arg. pointer to the second arg. etc... ended by 0
Returns
a new rpc response process message or NULL.
Definition at line 98 of file tcmi_rpcresp_procmsg.c.
References args, tcmi_rpcresp_procmsg::elem_base, tcmi_rpcresp_procmsg::elem_free, tcmi_rpcresp_procmsg::elem_size, mdbg, tcmi_rpcresp_procmsg::nmemb, nmemb, tcmi_rpcresp_procmsg::rpcnum, tcmi_rpcresp_procmsg::rtn_code, rtn_code, SIZE_OF_ELEM_BASE, SIZE_OF_ELEM_FREE, SIZE_OF_ELEM_SIZE, TCMI_MSG, tcmi_msg_req_id(), TCMI_RPC_MAXPARAMS, TCMI_RPC_PROCMSG, tcmi_rpc_procmsg_num(), TCMI_RPCRESP_PROCMSG, TCMI_RPCRESP_PROCMSG_DONTFREE, tcmi_rpcresp_procmsg_new_tx(), and tcmi_task_remote_pid().
Referenced by tcmi_shadow_rpc_do_fork(), tcmi_shadow_rpc_getgroups(), tcmi_shadow_rpc_getresgid(), tcmi_shadow_rpc_getresuid(), tcmi_shadow_rpc_rt_sigqueueinfo(), tcmi_shadow_rpc_setgroups(), and tcmi_shadow_rpc_sys_wait4().
{
     struct tcmi_rpcresp_procmsg *self_msg;
     u_int16_t nmemb, i;
     va_list args;
     if ( !(self_msg = TCMI_RPCRESP_PROCMSG( tcmi_rpcresp_procmsg_new_tx(tcmi_msg_req_id(m),
                         tcmi_task_remote_pid(current->tcmi.tcmi_task) ))) ){
         mdbg(ERR3, "Error creating RPC response message");
         return NULL;
     }
     va_start(args, rtn_code);
     for(nmemb = 0; nmemb < TCMI_RPC_MAXPARAMS && va_arg(args, size_t) != 0; nmemb++ ) {
         void* arg = va_arg(args, void*);
         mdbg(INFO3, "Arg addr: %p", arg);
         if ( arg == NULL ) {
             mdbg(ERR3, "Null argument[%d] in RPC!", nmemb);
             return NULL;
         }
     }
     va_end(args);
     mdbg(INFO3, "creating RPC response message nmemb: %u, rtn: %ld", nmemb, rtn_code);
     self_msg->nmemb = nmemb;
     self_msg->rpcnum = tcmi_rpc_procmsg_num( TCMI_RPC_PROCMSG(m) );
     self_msg->rtn_code = rtn_code;
     if(nmemb > 0){
         if( (self_msg->elem_free = kmalloc(SIZE_OF_ELEM_SIZE +
                 SIZE_OF_ELEM_BASE + SIZE_OF_ELEM_FREE, GFP_KERNEL)) == NULL){
             mdbg(ERR3, "Error creating RPC response message");
             return NULL;
         }
         self_msg->elem_size = (void*)(self_msg->elem_free) + SIZE_OF_ELEM_FREE;
         self_msg->elem_base = (void*)(self_msg->elem_size) + SIZE_OF_ELEM_SIZE;
         va_start(args, rtn_code);
         for(i = 0; i < nmemb; i++ ){
             self_msg->elem_size[i] = (unsigned long)va_arg(args, size_t);
             self_msg->elem_base[i] = va_arg(args, void*);
             self_msg->elem_free[i] = TCMI_RPCRESP_PROCMSG_DONTFREE;
             mdbg(INFO3, "Adding parametr #%d: at %p size %lu", i, self_msg->elem_base[i], (unsigned long)self_msg->elem_size[i] );
         }
         va_end(args);
     }
     return TCMI_MSG(self_msg);
 }
static void* tcmi_rpcresp_procmsg_data_base (struct tcmi_rpcresp_procmsg * self, unsigned int index) inline static
<<public>> Get pointer do data
Parameters
*self - this message instance
index - index of data which we want
Returns
pointer to data or NULL if index is out of range
Definition at line 75 of file tcmi_rpcresp_procmsg.h.
References mdbg, and nmemb.
Referenced by tcmi_guest_rpc_sys_fork(), tcmi_guest_rpc_sys_getgroups(), tcmi_guest_rpc_sys_getresgid(), tcmi_guest_rpc_sys_getresuid(), and tcmi_guest_rpc_sys_wait4().
 {
     if(index < self->nmemb)
         return self->elem_base[index];
     mdbg(ERR3, "Trying to acces beyond array boundary");
     return NULL;
 }
static unsigned long tcmi_rpcresp_procmsg_data_size (struct tcmi_rpcresp_procmsg * self, unsigned int index) inline static
<<public>> Get RPC parameter size.
Parameters
*self - this message instance
index - index of data which size we want
Returns
RPC parameter size or 0 if index is out of range
Definition at line 89 of file tcmi_rpcresp_procmsg.h.
References mdbg, and nmemb.
Referenced by tcmi_guest_rpc_sys_getgroups().
 {
     if(index < self->nmemb)
         return self->elem_size[index];
     mdbg(ERR3, "Trying to acces beyond array boundary");
     return 0;
 }
static void tcmi_rpcresp_procmsg_free (struct tcmi_procmsg * self) static
<<private>> Frees RPC message resources
Parameters
*self - this message instance
Definition at line 360 of file tcmi_rpcresp_procmsg.c.
References tcmi_rpcresp_procmsg::elem_base, tcmi_rpcresp_procmsg::elem_free, tcmi_rpcresp_procmsg::elem_size, mdbg, tcmi_rpcresp_procmsg::nmemb, TCMI_RPCRESP_PROCMSG, TCMI_RPCRESP_PROCMSG_DONTFREE, TCMI_RPCRESP_PROCMSG_KFREE, and TCMI_RPCRESP_PROCMSG_VFREE.
 {
     struct tcmi_rpcresp_procmsg *self_msg = TCMI_RPCRESP_PROCMSG(self);
     int i;
     if( self_msg->nmemb ){
         for( i = 0; i < self_msg->nmemb; i++ ){
             switch( self_msg->elem_free[i] ){
                 case TCMI_RPCRESP_PROCMSG_DONTFREE:
                     mdbg(INFO3, "Skipping unallocate of #%d data at %p size %lu",
                             i, self_msg->elem_base[i], (unsigned long)self_msg->elem_size[i]);
                     break;
                 case TCMI_RPCRESP_PROCMSG_KFREE:
                     mdbg(INFO3, "Freeing (kfree) data #%d at %p size %lu",
                             i, self_msg->elem_base[i], (unsigned long)self_msg->elem_size[i]);
                     kfree(self_msg->elem_base[i]);
                     break;
                 case TCMI_RPCRESP_PROCMSG_VFREE:
                     mdbg(INFO3, "Freeing (vfree) data #%d at %p size %lu",
                             i, self_msg->elem_base[i], (unsigned long)self_msg->elem_size[i]);
                     vfree(self_msg->elem_base[i]);
                     break;
                 default:
                     mdbg(ERR3, "Unknown action in %p->elem_free[%d]", self_msg, i);
             }
         }
         kfree(self_msg->elem_free);
     }
 }
static void tcmi_rpcresp_procmsg_free_on_put (struct tcmi_rpcresp_procmsg * self, unsigned int index, int action) inline static
<<public>> Set if and how data will be freed on last put
Parameters
*self - this message instance
index - index of data which put action we are going to set
action - one of TCMI_RPCRESP_PROCMSG_DONTFREE, TCMI_RPCRESP_PROCMSG_KFREE or TCMI_RPCRESP_PROCMSG_VFREE
Definition at line 102 of file tcmi_rpcresp_procmsg.h.
References action, mdbg, and nmemb.
Referenced by tcmi_shadow_rpc_do_fork(), tcmi_shadow_rpc_getgroups(), tcmi_shadow_rpc_getresgid(), tcmi_shadow_rpc_getresuid(), and tcmi_shadow_rpc_sys_wait4().
 {
     if(index < self->nmemb)
         self->elem_free[index] = action;
     else
         mdbg(ERR3, "Trying to acces beyond array boundary");
 }
struct tcmi_msg* tcmi_rpcresp_procmsg_get_response (unsigned int rpcnum, ...) read
<<public>> Creates and sends rpc_proc_msg and returns response
<<public>> Creates and sends rpc_proc_msg and returns response
Parameters
rpcnum - RPC number
... - size of the first arg., pointer to the first arg., size of the second arg. pointer to the second arg. etc... ended by 0
Returns
a new rpc response process message or NULL.
Definition at line 157 of file tcmi_rpcresp_procmsg.c.
References args, elem_base, elem_size, mdbg, nmemb, rpcnum, tcmi_msg_put(), TCMI_RPC_MAXPARAMS, TCMI_RPC_PROCMSG, tcmi_rpc_procmsg_new_tx(), tcmi_task_remote_pid(), tcmi_task_send_and_receive_msg(), and tcmi_task_transactions().
Referenced by tcmi_guest_rpc_sys_fork(), tcmi_guest_rpc_sys_getgroups(), tcmi_guest_rpc_sys_getresgid(), tcmi_guest_rpc_sys_getresuid(), tcmi_guest_rpc_sys_rt_sigqueueinfo(), tcmi_guest_rpc_sys_setgroups(), and tcmi_guest_rpc_sys_wait4().
{
     struct tcmi_msg *m, *r = NULL;
     va_list args;
     size_t arg_size;
     u_int32_t elem_size[TCMI_RPC_MAXPARAMS];
     //unsigned long elem_free[TCMI_RPC_MAXPARAMS];
         void* elem_base[TCMI_RPC_MAXPARAMS];
     u_int16_t nmemb;
     struct tcmi_task* task;
     task = current->tcmi.tcmi_task;
     va_start(args, rpcnum);
     if ( (m = tcmi_rpc_procmsg_new_tx( tcmi_task_transactions(task),
                     tcmi_task_remote_pid(task) )) == NULL )
     {
         mdbg(ERR3, "Can't create rpc message");
         goto exit0;
     }
     for(nmemb = 0; nmemb < TCMI_RPC_MAXPARAMS &&
             (arg_size = va_arg(args, size_t)) != 0; nmemb++ ){
         elem_size[nmemb] = arg_size;
         elem_base[nmemb] = va_arg(args, void*);
         //elem_free[nmemb] = TCMI_RPCRESP_PROCMSG_DONTFREE;
         mdbg(INFO3, "Adding parametr #%d: at %p size %lu", nmemb, elem_base[nmemb], (unsigned long)elem_size[nmemb] );
     }
     TCMI_RPC_PROCMSG(m)->rpcnum = rpcnum;
     TCMI_RPC_PROCMSG(m)->nmemb = nmemb;
     TCMI_RPC_PROCMSG(m)->elem_size = elem_size;
     TCMI_RPC_PROCMSG(m)->elem_base = elem_base;
     //TCMI_RPC_PROCMSG(m)->elem_free = elem_free;
     tcmi_task_send_and_receive_msg(task, m, &r);
     TCMI_RPC_PROCMSG(m)->elem_size = NULL;/* Prevent calling free on staticaly allocated resources*/
     TCMI_RPC_PROCMSG(m)->free_data = false;
     TCMI_RPC_PROCMSG(m)->nmemb = 0;
     tcmi_msg_put(m);
 exit0:  va_end(args);
     return r;
 }
struct tcmi_msg* tcmi_rpcresp_procmsg_new_rx (u_int32_t msg_id) read
<<public>> RPC response process message rx constructor.
<<public>> RPC response process message rx constructor.
Parameters
msg_id - message ID, to check with the actual response process message ID.
Returns
a new rpc response process message or NULL.
Definition at line 56 of file tcmi_rpcresp_procmsg.c.
References tcmi_rpcresp_procmsg::elem_free, mdbg, rpcresp_procmsg_ops, TCMI_MSG, TCMI_PROCMSG, tcmi_procmsg_init_rx(), TCMI_RPCRESP_PROCMSG, and TCMI_RPCRESP_PROCMSG_ID.
 {
     struct tcmi_rpcresp_procmsg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_RPCRESP_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified process message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_RPCRESP_PROCMSG_ID);
         goto exit0;
     }
     if (!(msg = TCMI_RPCRESP_PROCMSG(kmalloc(sizeof(struct tcmi_rpcresp_procmsg),
                           GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate RPC process message");
         goto exit0;
     }
     msg->elem_free = NULL;
     /* Initialized the message for receiving, message ID is extended with error flags */
     if (tcmi_procmsg_init_rx(TCMI_PROCMSG(msg), TCMI_RPCRESP_PROCMSG_ID,
                  &rpcresp_procmsg_ops)) {
         mdbg(ERR3, "Error initializing process message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_rpcresp_procmsg_new_tx (u_int32_t trans_id, pid_t dst_pid) read
<<public>> RPC response process message tx constructor.
Parameters
trans_id - transaction ID that this message is replying to.
dst_pid - destination process PID
Returns
a new test response message for the transfer or NULL.
Definition at line 209 of file tcmi_rpcresp_procmsg.c.
References tcmi_rpcresp_procmsg::elem_free, mdbg, tcmi_rpcresp_procmsg::nmemb, rpcresp_procmsg_ops, TCMI_MSG, TCMI_PROCMSG, tcmi_procmsg_init_tx(), TCMI_RPCRESP_PROCMSG, and TCMI_RPCRESP_PROCMSG_ID.
Referenced by tcmi_rpcresp_procmsg_create().
 {
     struct tcmi_rpcresp_procmsg *msg;
     if (!(msg = TCMI_RPCRESP_PROCMSG(kmalloc(sizeof(struct tcmi_rpcresp_procmsg),
                           GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate RPC response message");
         goto exit0;
     }
     msg->nmemb = 0;
     msg->elem_free = NULL;
     /* Initialize the message for transfer, no transaction
      * required, no timout, no response ID */
     if (tcmi_procmsg_init_tx(TCMI_PROCMSG(msg), TCMI_RPCRESP_PROCMSG_ID, &rpcresp_procmsg_ops,
                  dst_pid, 0,
                  NULL, 0, 0, trans_id)) {
         mdbg(ERR3, "Error initializing RPC response message");
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_rpcresp_procmsg_num (struct tcmi_rpcresp_procmsg * self) inline static
<<public>> Return RPC number.
Definition at line 130 of file tcmi_rpcresp_procmsg.h.
 {
     return self->rpcnum;
 }
static int tcmi_rpcresp_procmsg_recv (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
WARNING: Memory for data is allocated at one time, so when freeing free() must be called on elem_base[0]. It's done automatically in last mdg_put();
Definition at line 254 of file tcmi_rpcresp_procmsg.c.
References tcmi_rpcresp_procmsg::elem_base, tcmi_rpcresp_procmsg::elem_free, tcmi_rpcresp_procmsg::elem_size, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_rpcresp_procmsg::nmemb, tcmi_rpcresp_procmsg::rpcnum, tcmi_rpcresp_procmsg::rtn_code, SIZE_OF_ELEM_BASE, SIZE_OF_ELEM_FREE, SIZE_OF_ELEM_SIZE, TCMI_RPCRESP_PROCMSG, TCMI_RPCRESP_PROCMSG_DONTFREE, and TCMI_RPCRESP_PROCMSG_KFREE.
 {
     /* struct tcmi_rpcresp_procmsg *self_msg = TCMI_RPCRESP_PROCMSG(self); */
     int err, data_size, total, i;
     struct tcmi_rpcresp_procmsg *self_msg = TCMI_RPCRESP_PROCMSG(self);
     err = kkc_sock_recv(sock, &self_msg->rpcnum,
                 sizeof(self_msg->rpcnum) + sizeof(self_msg->nmemb) +
                 sizeof(self_msg->rtn_code), KKC_SOCK_BLOCK);
     if( err < 0 ) {
         mdbg(ERR3, "Error receiving RPC message header. Error code: %d", err);
         return err;
     }
     total = err;
     if( self_msg->nmemb > 0 ){
         /* Allocate memory for array of elements size and array of pointers to elements */
         if( (self_msg->elem_free = kmalloc(SIZE_OF_ELEM_SIZE +
                 SIZE_OF_ELEM_BASE + SIZE_OF_ELEM_FREE, GFP_KERNEL)) == NULL){
             mdbg(ERR3, "Can't create rpc message");
         }
         self_msg->elem_size = (void*)(self_msg->elem_free) + SIZE_OF_ELEM_FREE;
         self_msg->elem_base = (void*)(self_msg->elem_size) + SIZE_OF_ELEM_SIZE;
         self_msg->elem_base[0] = NULL;
         err = kkc_sock_recv(sock, self_msg->elem_size, SIZE_OF_ELEM_SIZE, KKC_SOCK_BLOCK);
         if( err < 0 ) {
             mdbg(ERR3, "Error receiving RPC#%d message elem size. Error code: %d", self_msg->rpcnum, err);
              return err;
         }
         total += err;
         /* Allocate memory for data */
         for(data_size = 0, i = 0; i < self_msg->nmemb; data_size += self_msg->elem_size[i++]);
         if( (self_msg->elem_base[0] = kmalloc( data_size, GFP_KERNEL ) ) == NULL){
             mdbg(ERR3, "Can't create rpc message2");
         }
         self_msg->elem_free[0] = TCMI_RPCRESP_PROCMSG_KFREE; /* We allocated data, so we have to free it */
         err = kkc_sock_recv(sock, self_msg->elem_base[0], data_size, KKC_SOCK_BLOCK);
         if( err < 0 ) {
             mdbg(ERR3, "Error receiving RPC#%d message elements. Error code: %d", self_msg->rpcnum, err);
             return err;
         }
         total += err;
         for( i = 1; i < self_msg->nmemb; i++ ){
             self_msg->elem_base[i] = self_msg->elem_base[i-1] + self_msg->elem_size[i-1];
             self_msg->elem_free[i] = TCMI_RPCRESP_PROCMSG_DONTFREE;
         }
     }
     mdbg(INFO3, "Received RPC#%d response message (%d Bytes)", self_msg->rpcnum, total);
     return 0;
 }
static long tcmi_rpcresp_procmsg_rtn (struct tcmi_rpcresp_procmsg * self) inline static
<<public>> Return RPC return code.
Definition at line 124 of file tcmi_rpcresp_procmsg.h.
Referenced by tcmi_guest_rpc_sys_fork(), tcmi_guest_rpc_sys_getgroups(), tcmi_guest_rpc_sys_getresgid(), tcmi_guest_rpc_sys_getresuid(), tcmi_guest_rpc_sys_rt_sigqueueinfo(), tcmi_guest_rpc_sys_setgroups(), and tcmi_guest_rpc_sys_wait4().
 {
     return self->rtn_code;
 }
static int tcmi_rpcresp_procmsg_send (struct tcmi_procmsg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 317 of file tcmi_rpcresp_procmsg.c.
References tcmi_rpcresp_procmsg::elem_base, tcmi_rpcresp_procmsg::elem_size, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_rpcresp_procmsg::nmemb, tcmi_rpcresp_procmsg::rpcnum, tcmi_rpcresp_procmsg::rtn_code, SIZE_OF_ELEM_SIZE, and TCMI_RPCRESP_PROCMSG.
 {
     int err, total, i;
     struct tcmi_rpcresp_procmsg *self_msg = TCMI_RPCRESP_PROCMSG(self);
     err = kkc_sock_send(sock, &self_msg->rpcnum,
                 sizeof(self_msg->rpcnum) + sizeof(self_msg->nmemb) +
                 sizeof(self_msg->rtn_code), KKC_SOCK_BLOCK);
     if( err < 0 ) {
         mdbg(ERR3, "Error sending RPC#%d message header. Error code: %d", self_msg->rpcnum, err);
         return err;
     }
     total = err;
     if( self_msg->nmemb > 0 ){
         err = kkc_sock_send(sock, self_msg->elem_size, SIZE_OF_ELEM_SIZE, KKC_SOCK_BLOCK);
         if( err < 0 ) {
             mdbg(ERR3, "Error sending RPC#%d message elem size. Error code: %d", self_msg->rpcnum, err);
             return err;
         }
         total += err;
         for( i = 0; i < self_msg->nmemb; i++ ){
             err = kkc_sock_send(sock, self_msg->elem_base[i],
                     self_msg->elem_size[i], KKC_SOCK_BLOCK);
             if( err < 0 ) {
                 mdbg(ERR3, "Error sending RPC#%d message element[%d]. Error code: %d", self_msg->rpcnum, i, err);
                 return err;
             }
             total += err;
         }
     }
     mdbg(INFO3, "Sent RPC#%d message (%d Bytes)", self_msg->rpcnum, total);
     return 0;
 }
Variable Documentation
struct tcmi_procmsg_ops rpcresp_procmsg_ops static
Initial value:
= {
    .recv = tcmi_rpcresp_procmsg_recv,
    .send = tcmi_rpcresp_procmsg_send,
    .free = tcmi_rpcresp_procmsg_free
}
Message operations that support polymorphism.
Definition at line 390 of file tcmi_rpcresp_procmsg.c.
Referenced by tcmi_rpcresp_procmsg_new_rx(), and tcmi_rpcresp_procmsg_new_tx().