Clondike: tcmi_authenticate_msg class
tcmi_authenticate_msg class
tcmi_msg class
This message is send by PEN when it wants authenticate to CCN.
Data Structures
struct tcmi_authenticate_msg
Authentication message structure.
Macros
#define TCMI_AUTHENTICATE_MSG_DSC TCMI_MSG_DSC(TCMI_AUTHENTICATE_MSG_ID, tcmi_authenticate_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
#define TCMI_AUTHENTICATE_MSG(m) ((struct tcmi_authenticate_msg*)m)
Casts to the tcmi_authenticate_msg instance.
Functions
static int tcmi_authenticate_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_authenticate_msg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Sends the message via a specified connection.
static void tcmi_authenticate_msg_send_free (struct tcmi_msg *self)
<<private>> Frees custom message resources.
struct tcmi_msg * tcmi_authenticate_msg_new_rx (u_int32_t msg_id)
<<public>> Authentication message consutructor for receiving.
struct tcmi_msg * tcmi_authenticate_msg_new_tx (struct tcmi_slotvec *transactions, u_int32_t pen_id, enum arch_ids pen_arch, char *auth_data, int size)
<<public>> Authentication message constructor for transferring.
static u_int32_t tcmi_authenticate_msg_pen_id (struct tcmi_authenticate_msg *self)
<<public>> PEN id getter
static enum arch_ids tcmi_authenticate_msg_arch (struct tcmi_authenticate_msg *self)
<<public>> PEN architecture getter
static u_int32_t tcmi_authenticate_msg_auth_data_size (struct tcmi_authenticate_msg *self)
<<public>> PEN authentication data length getter
static char * tcmi_authenticate_msg_auth_data (struct tcmi_authenticate_msg *self)
<<public>> PEN authentication data getter
Variables
static struct tcmi_msg_ops authenticate_msg_ops
Message operations that support polymorphism.
Detailed Description
This message is send by PEN when it wants authenticate to CCN.
Data Structure Documentation
struct tcmi_authenticate_msg
Authentication message structure.
Definition at line 21 of file tcmi_authenticate_msg.h.
Data Fields
char * auth_data Authentication data.
Opaque to the kernel part, this is purely user space responsibilithy to provide and parse those.
enum arch_ids pen_arch Architecture of PEN.
u_int32_t pen_id Id of the requestor PEN.
u_int32_t size Size of authentication data.
struct tcmi_msg super parent class instance.
Macro Definition Documentation
#define TCMI_AUTHENTICATE_MSG (m) ((struct tcmi_authenticate_msg*)m)
Casts to the tcmi_authenticate_msg instance.
Definition at line 51 of file tcmi_authenticate_msg.h.
Referenced by tcmi_authenticate_msg_new_rx(), tcmi_authenticate_msg_new_tx(), tcmi_authenticate_msg_recv(), tcmi_authenticate_msg_send(), tcmi_authenticate_msg_send_free(), and tcmi_ccnmigman_process_msg().
#define TCMI_AUTHENTICATE_MSG_DSC TCMI_MSG_DSC(TCMI_AUTHENTICATE_MSG_ID, tcmi_authenticate_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
Definition at line 48 of file tcmi_authenticate_msg.h.
Function Documentation
static enum arch_ids tcmi_authenticate_msg_arch (struct tcmi_authenticate_msg * self) inline static
<<public>> PEN architecture getter
Parameters
*self - this message instance
Returns
PEN architecture
Definition at line 70 of file tcmi_authenticate_msg.h.
Referenced by tcmi_ccnmigman_process_msg().
 {
     return self->pen_arch;
 }
static char* tcmi_authenticate_msg_auth_data (struct tcmi_authenticate_msg * self) inline static
<<public>> PEN authentication data getter
Parameters
*self - this message instance
Returns
Authentication data
Definition at line 92 of file tcmi_authenticate_msg.h.
Referenced by tcmi_ccnmigman_process_msg().
 {
     return self->auth_data;
 }
static u_int32_t tcmi_authenticate_msg_auth_data_size (struct tcmi_authenticate_msg * self) inline static
<<public>> PEN authentication data length getter
Parameters
*self - this message instance
Returns
Authentication data length
Definition at line 81 of file tcmi_authenticate_msg.h.
Referenced by tcmi_ccnmigman_process_msg().
 {
     return self->size;
 }
struct tcmi_msg* tcmi_authenticate_msg_new_rx (u_int32_t msg_id) read
<<public>> Authentication message consutructor for receiving.
<<public>> Authentication message consutructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this message instance.
Returns
a new message or NULL.
Definition at line 25 of file tcmi_authenticate_msg.c.
References authenticate_msg_ops, mdbg, TCMI_AUTHENTICATE_MSG, TCMI_AUTHENTICATE_MSG_ID, TCMI_MSG, and tcmi_msg_init_rx().
 {
     struct tcmi_authenticate_msg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_AUTHENTICATE_MSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_AUTHENTICATE_MSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_AUTHENTICATE_MSG(kmalloc(sizeof(struct tcmi_authenticate_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate auth request message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_AUTHENTICATE_MSG_ID, &authenticate_msg_ops)) {
         mdbg(ERR3, "Error initializing authenticate request message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_authenticate_msg_new_tx (struct tcmi_slotvec * transactions, u_int32_t pen_id, enum arch_ids pen_arch, char * auth_data, int size) read
<<public>> Authentication message constructor for transferring.
<<public>> Authentication message constructor for transferring.
Parameters
*transactions - storage for the new transaction
pen_id Id of the requesting PEN
pen_arch Architecture of PEN
Returns
a new message ready for the transfer or NULL.
Definition at line 65 of file tcmi_authenticate_msg.c.
References tcmi_authenticate_msg::auth_data, authenticate_msg_ops, mdbg, tcmi_authenticate_msg::pen_arch, tcmi_authenticate_msg::pen_id, tcmi_authenticate_msg::size, size, TCMI_AUTHENTICATE_MSG, TCMI_AUTHENTICATE_MSG_ID, TCMI_AUTHENTICATE_RESP_MSG_ID, TCMI_DEFAULT_MSG_TIMEOUT, TCMI_MSG, tcmi_msg_init_tx(), and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_penmigman_auth_ccn().
 {
     struct tcmi_authenticate_msg *msg;
     if (!(msg = TCMI_AUTHENTICATE_MSG(kmalloc(sizeof(struct tcmi_authenticate_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate authenticate request message");
         goto exit0;
     }
     msg->pen_id = pen_id;
     msg->pen_arch = pen_arch;
     msg->size = size;
     if ( size > 0 ) {
         if (!(msg->auth_data = (char*)kmalloc(size, GFP_KERNEL))) {
             mdbg(ERR3, "Can't allocate memory for checkpoint name");
             goto exit1;
         }
         memcpy(msg->auth_data, auth_data, size);
     } else {
         msg->auth_data = NULL;
     }
     /* Initialize the message for transfer */
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_AUTHENTICATE_MSG_ID, &authenticate_msg_ops,
                  transactions, TCMI_AUTHENTICATE_RESP_MSG_ID,
                  TCMI_DEFAULT_MSG_TIMEOUT, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing authenticate request message message");
         goto exit2;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit2:
     kfree(msg->auth_data);
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static u_int32_t tcmi_authenticate_msg_pen_id (struct tcmi_authenticate_msg * self) inline static
<<public>> PEN id getter
Parameters
*self - this message instance
Returns
PEN id
Definition at line 59 of file tcmi_authenticate_msg.h.
Referenced by tcmi_ccnmigman_process_msg().
 {
     return self->pen_id;
 }
static int tcmi_authenticate_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 120 of file tcmi_authenticate_msg.c.
References tcmi_authenticate_msg::auth_data, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_authenticate_msg::pen_arch, tcmi_authenticate_msg::pen_id, tcmi_authenticate_msg::size, and TCMI_AUTHENTICATE_MSG.
 {
     int err = -EINVAL;
     struct tcmi_authenticate_msg *self_msg = TCMI_AUTHENTICATE_MSG(self);
     mdbg(INFO2, "Authenticate request message received");
     if ((err = kkc_sock_recv(sock, &self_msg->pen_id,
                  sizeof(self_msg->pen_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive pen id");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_msg->pen_arch,
                  sizeof(self_msg->pen_arch), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive pen arch");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive size of auth data");
         goto exit0;
     }
     if ( self_msg->size > 0 ) {
         if (!(self_msg->auth_data = (char*)kmalloc(self_msg->size, GFP_KERNEL))) {
             mdbg(ERR3, "Can't allocate memory for auth data.");
             goto exit0;
         }
         /* Receive the authentication data */
         if ((err = kkc_sock_recv(sock, self_msg->auth_data,
                     self_msg->size, KKC_SOCK_BLOCK)) < 0) {
             mdbg(ERR3, "Failed to receive checkpoint name");
             goto exit0;
         }
     } else {
         self_msg->auth_data = NULL;
     }
     return 0;
     /* error handling*/
  exit0:
     return err;
 }
static int tcmi_authenticate_msg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Sends the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 175 of file tcmi_authenticate_msg.c.
References tcmi_authenticate_msg::auth_data, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_authenticate_msg::pen_arch, tcmi_authenticate_msg::pen_id, tcmi_authenticate_msg::size, and TCMI_AUTHENTICATE_MSG.
 {
     int err;
     struct tcmi_authenticate_msg *self_msg = TCMI_AUTHENTICATE_MSG(self);
     /* Receive the remote PID and checkpoint name size */
     if ((err = kkc_sock_send(sock, &self_msg->pen_id,
                  sizeof(self_msg->pen_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send pen id");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_msg->pen_arch,
                  sizeof(self_msg->pen_arch), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send pen arch");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_msg->size,
                  sizeof(self_msg->size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send auth data size");
         goto exit0;
     }
     if ( self_msg->size > 0 ) {
         /* Send the authentication data */
         if ((err = kkc_sock_send(sock, self_msg->auth_data,
                     self_msg->size, KKC_SOCK_BLOCK)) < 0) {
             mdbg(ERR3, "Failed to send authentication data");
             goto exit0;
         }
     }
     mdbg(INFO2, "Authenticate request message sent. Pen ID=%d Arch=%d Auth data length=%d", self_msg->pen_id, self_msg->pen_arch, self_msg->size);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static void tcmi_authenticate_msg_send_free (struct tcmi_msg * self) static
<<private>> Frees custom message resources.
The checkpoint image name string is released from memory.
Parameters
*self - this message instance
Definition at line 222 of file tcmi_authenticate_msg.c.
References tcmi_authenticate_msg::auth_data, mdbg, and TCMI_AUTHENTICATE_MSG.
 {
     struct tcmi_authenticate_msg *self_msg = TCMI_AUTHENTICATE_MSG(self);
     mdbg(INFO3, "Freeing auth message");
     kfree(self_msg->auth_data);
 }
Variable Documentation
struct tcmi_msg_ops authenticate_msg_ops static
Initial value:
= {
    .recv = tcmi_authenticate_msg_recv,
    .send = tcmi_authenticate_msg_send,
    .free = tcmi_authenticate_msg_send_free
}
Message operations that support polymorphism.
Definition at line 232 of file tcmi_authenticate_msg.c.
Referenced by tcmi_authenticate_msg_new_rx(), and tcmi_authenticate_msg_new_tx().