Clondike: proxyfs_client class
proxyfs_client class
proxyfs_task class
<<class>> representing proxyfs_client task
Macros
#define PROXYFS_CLIENT_TASK(arg) ((struct proxyfs_client_task*)(arg))
<<public>> Cast to struct proxyfs_client_task*
Functions
int proxyfs_client_thread (void *start_struct)
<<public>> Startup function for proxyfs client
struct proxyfs_proxy_file_t * proxyfs_client_open_proxy (struct proxyfs_client_task *self, unsigned long inode_num)
<<public>> Create new proxy file
struct proxyfs_msg * proxyfs_client_do_syscall (struct proxyfs_client_task *self, struct proxyfs_proxy_file_t *file, struct proxyfs_msg *msg)
<<public>> Do syscall
void proxyfs_client_send_message (struct proxyfs_client_task *self, struct proxyfs_proxy_file_t *file, struct proxyfs_msg *msg)
<<public>> Asynchronously sends a message
Detailed Description
<<class>> representing proxyfs_client task
Macro Definition Documentation
#define PROXYFS_CLIENT_TASK (arg) ((struct proxyfs_client_task*)(arg))
<<public>> Cast to struct proxyfs_client_task*
Definition at line 51 of file proxyfs_client.h.
Referenced by get_proxy_file_by_id(), proxyfs_client_handle_dead_peer(), proxyfs_client_handle_msg(), and proxyfs_fs_fdinode_open().
Function Documentation
struct proxyfs_msg* proxyfs_client_do_syscall (struct proxyfs_client_task * self, struct proxyfs_proxy_file_t * file, struct proxyfs_msg * msg) read
<<public>> Do syscall
<<public>> Do syscall
Parameters
*self - pointer to proxyfs_client_task instance
*file - pointer to proxy file. System call will by called on coresponding real file.
*msg - pointer t system call messagge
Returns
response messagge or NULL on error
Definition at line 379 of file proxyfs_client.c.
References check_syscall_done(), mdbg, PROXYFS_FILE, PROXYFS_FILE_IN_SYSCALL, proxyfs_file_set_status(), proxyfs_peer_send_msg(), PROXYFS_TASK, and proxyfs_task_notify_data_ready().
Referenced by proxyfs_pipe_proxy_file_read_user(), proxyfs_proxy_file_close(), proxyfs_proxy_file_fsync(), and proxyfs_proxy_file_ioctl_user().
 {
     struct proxyfs_msg *msg_resp = NULL;
     struct proxyfs_peer_t* peer;
     peer = PROXYFS_FILE(file)->peer;
     file->syscall_resp = &msg_resp;
     // TODO: Does this handle case of multiple simultaneous sys_calls? Not likely..
     proxyfs_file_set_status( PROXYFS_FILE(file), PROXYFS_FILE_IN_SYSCALL );
     proxyfs_peer_send_msg( peer , msg );
     proxyfs_task_notify_data_ready(PROXYFS_TASK(self));
     wait_event( file->waiting_procs, check_syscall_done(file, peer) );
     mdbg(INFO3, "File syscall finished");
     return msg_resp;
 }
struct proxyfs_proxy_file_t* proxyfs_client_open_proxy (struct proxyfs_client_task * self, unsigned long inode_num) read
<<public>> Create new proxy file
<<public>> Create new proxy file
Parameters
self - pointer to proxyfs_client_task instance
inode_num - unique file identification number
Returns
Proxyfile or err ptr
Definition at line 313 of file proxyfs_client.c.
References get_proxy_file_by_id(), mdbg, PROXYFS_FILE, proxyfs_file_destroy(), PROXYFS_FILE_DONT_EXISTS, proxyfs_file_get_status(), PROXYFS_FILE_OPENED, proxyfs_file_set_file_ident(), PROXYFS_PROXY_FILE, proxyfs_proxy_file_init(), PROXYFS_TASK, proxyfs_task_notify_data_ready(), and self.
Referenced by proxyfs_fs_fdinode_open().
{
     struct proxyfs_proxy_file_t *proxy_file;
     down( & self->files_sem);
     proxy_file = PROXYFS_PROXY_FILE(get_proxy_file_by_id(PROXYFS_TASK(self), inode_num));
     up( & self->files_sem);
     if ( proxy_file ) {
         mdbg(ERR3, "File is already open by the same task in this proxy client => cannot open once more!");
         proxy_file = ERR_PTR(-EACCES);
         goto exit0;
     }
     proxy_file = (struct proxyfs_proxy_file_t *)kmalloc(sizeof(struct proxyfs_proxy_file_t), GFP_KERNEL);
     if( proxy_file == NULL ){
         mdbg(ERR3, "Allocating memory for proxy_file failed");
         proxy_file = ERR_PTR(-ENOMEM);
         goto exit0;
     }
     proxyfs_proxy_file_init(proxy_file);
     proxyfs_file_set_file_ident(PROXYFS_FILE(proxy_file), inode_num);
     proxy_file->task = self;
     down( & self->try_open_sem );
     list_add_tail( & PROXYFS_FILE(proxy_file)->files, & self->try_open );
     up( & self->try_open_sem );
     mdbg(INFO3, "Proxyfile (file_ident=%lu) created and added to open queue", inode_num);
     //proxyfs_task_wakeup(PROXYFS_TASK(self));
     proxyfs_task_notify_data_ready(PROXYFS_TASK(self));
     wait_event( proxy_file->waiting_procs, proxyfs_file_get_status( PROXYFS_FILE(proxy_file),
                    PROXYFS_FILE_OPENED | PROXYFS_FILE_DONT_EXISTS ));
     if( proxyfs_file_get_status( PROXYFS_FILE(proxy_file), PROXYFS_FILE_OPENED )){
         mdbg(INFO3, "File opened");
         return proxy_file;
     }
     mdbg(INFO3, "File does not exists");
     proxyfs_file_destroy(PROXYFS_FILE(proxy_file));
     kfree( proxy_file );
     proxy_file = ERR_PTR(-ENOENT);
 exit0:
     return proxy_file;
 }
void proxyfs_client_send_message (struct proxyfs_client_task * self, struct proxyfs_proxy_file_t * file, struct proxyfs_msg * msg)
<<public>> Asynchronously sends a message
Definition at line 400 of file proxyfs_client.c.
References PROXYFS_FILE, and proxyfs_peer_send_msg().
Referenced by proxyfs_proxy_file_read_user().
{
     struct proxyfs_peer_t* peer;
     peer = PROXYFS_FILE(file)->peer;
     proxyfs_peer_send_msg( peer , msg );
 }
int proxyfs_client_thread (void * ss)
<<public>> Startup function for proxyfs client
<<public>> Startup function for proxyfs client
Parameters
start_struct - proxyfs task startup structure
Definition at line 72 of file proxyfs_client.c.
References kkc_sock_register_read_callback(), mdbg, proxyfs_client_loop(), proxyfs_client_new(), proxyfs_peer_connect(), proxyfs_peer_disconnect(), proxyfs_peer_new(), proxyfs_peer_put(), proxyfs_peer_wait(), PROXYFS_TASK, proxyfs_task_complete(), proxyfs_task_data_ready_callback(), proxyfs_task_put(), and self.
Referenced by proxyfs_fs_mount().
 {
     struct proxyfs_client_task *self;
     struct proxyfs_task_start_struct *start_struct = (struct proxyfs_task_start_struct *)ss;
     if( (self = proxyfs_client_new()) == NULL )
         goto exit0;
     PROXYFS_TASK(self)->tsk = current;
     //init_waitqueue_entry( &self.socket_wait, current );
     if( (self->server = proxyfs_peer_new()) == NULL) {
         mdbg(ERR2, "Failed to create a peer");
         goto exit1;
     }
     mdbg(INFO3, "Proxy fs client going to connect");
     if( proxyfs_peer_connect( self->server, start_struct->addr_str) != 0 ) {
         mdbg(ERR2, "Failed to connect a peer");
         goto exit2;
     }
     kkc_sock_register_read_callback(self->server->sock, proxyfs_task_data_ready_callback, self);
     mdbg(INFO3, "Proxy fs client connection wait");
     if( proxyfs_peer_wait( self->server ) != 0 ) {
         mdbg(ERR2, "Failed to wait for a peer");
         goto exit3;
     }
     mdbg(INFO3, "Proxy fs client connected succesfully");
     list_add(&self->server->peers, &PROXYFS_TASK(self)->peers );
     proxyfs_task_complete( PROXYFS_TASK(self), start_struct ); // After this call *start_struct is invalid
     proxyfs_client_loop(self);
     return 0;
 exit3:
     proxyfs_peer_disconnect(self->server);
 exit2:
     proxyfs_peer_put(self->server);
 exit1:
     proxyfs_task_put(PROXYFS_TASK(self));
 exit0:
     mdbg(ERR2, "Failed to start client thread");
     proxyfs_task_complete( NULL, start_struct );
     return -EINVAL;
 }