Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/arch/x86_64/restart_fixup.h File Reference
restart_fixup.h File Reference
#include <asm/processor.h>
Functions
int syscall32_setup_pages (struct linux_binprm *bprm, int exstack)
We need to export this in order to prepare vsyscall page for 32 bit applications.
static long tcmi_restart_fixup (struct restart_block *restart)
This method is used for handling migration restart.
static int tcmi_resolve_restart_block_64bit_app (struct task_struct *task, struct pt_regs *regs)
64 bit apps do not need to use restart block.
static int tcmi_resolve_restart_block_32bit_app (struct task_struct *task, struct pt_regs *regs, enum arch_ids from_arch)
32 bit apps do not need to use restart block
static int tcmi_resolve_restart_block (struct task_struct *task, struct pt_regs *regs, enum arch_ids from_arch, int is_32bit_application)
Registeres restart block and schedules restart syscall to be executed after the process resumes userspace for first time.
Function Documentation
int syscall32_setup_pages (struct linux_binprm * bprm, int exstack)
We need to export this in order to prepare vsyscall page for 32 bit applications.
Referenced by tcmi_resolve_restart_block().
static int tcmi_resolve_restart_block (struct task_struct * task, struct pt_regs * regs, enum arch_ids from_arch, int is_32bit_application) inline static
Registeres restart block and schedules restart syscall to be executed after the process resumes userspace for first time.
The main motivaction for this is to restore original AX register.
Parameters
task Current task
regs Current registers of the task
is_32bit_application 1 if, the application is 32 bit
Returns
0 on success
Definition at line 107 of file restart_fixup.h.
References mdbg, syscall32_setup_pages(), tcmi_resolve_restart_block_32bit_app(), and tcmi_resolve_restart_block_64bit_app().
{
     //struct restart_block* restart = &task->thread_info->restart_block;
     mdbg(INFO3, "Setting tcmi sys restart block. EAX: %08lX (OEAX: %08lX). EBX: %08lX ECX: %08lX EDX: %08lX", regs->ax, regs->orig_ax, regs->bx, regs->cx, regs->dx);
     if ( !is_32bit_application )
         return tcmi_resolve_restart_block_64bit_app(task, regs);
     /* First we have to setup syscall page into 32 process space so that it can do vsyscalls */
     if ( syscall32_setup_pages(NULL,0) ) {
         mdbg(ERR3, "Failed to install syscall page");
         return -EINVAL;
     }
     return tcmi_resolve_restart_block_32bit_app(task, regs, from_arch);
     //return 0;
 }
static int tcmi_resolve_restart_block_32bit_app (struct task_struct * task, struct pt_regs * regs, enum arch_ids from_arch) inline static
32 bit apps do not need to use restart block
Definition at line 68 of file restart_fixup.h.
References is_in_syscall(), and mdbg.
Referenced by tcmi_resolve_restart_block().
{
     if ( is_in_syscall(regs) ) {
         mdbg(INFO3, "Performing restart in 32 bit syscall.");
         regs->ip -= 2;
         regs->ax = regs->orig_ax;
         if ( boot_cpu_data.x86_vendor == X86_VENDOR_AMD) { // Fixup needed on AMD, as it does not support syscall in compat mode
             regs->sp += 8; /* Fixup stack pointer.. */
             *((unsigned int*)(regs->sp)) = regs->bp; // Fixup stack content.. this will be pushed from stack
             regs->bp = regs->cx; // This is normally done by 64 bit syscall, so we have to do it manually
         }
     } else {
         // For 64 bit applications we have a modified execve and we use orig_rax to set application rax, so we do not need to do restart trick
         // Do this only if we are not in syscall, otherwise we want current orig_eax to get into eax register
         regs->orig_ax = regs->ax;
         if ( regs->ip == 0xffffe410 && boot_cpu_data.x86_vendor == X86_VENDOR_AMD) { // Fixup needed on AMD, as it does not support syscall in compat mode
             mdbg(INFO3, "Performing restart in finished 32 bit syscall.");
             /* We were in syscall, but the syscall was not interrupted and so we do not need to restart it */
             regs->bp = *((unsigned int*)(regs->sp)); // Extract real RBP
             mdbg(INFO3, "Real rbp was: %08lx.", regs->bp);
             regs->sp += 8; /* Fixup stack pointer.. */
             *((unsigned int*)(regs->sp)) = regs->bp; // Fixup stack content.. this will be pushed from stack
             regs->bp = regs->cx; // This is normally done by 64 bit syscall, so we have to do it manually
             regs->ip = 0xffffe405; // Modify return address to correct value
         }
     }
     return 0;
 }
static int tcmi_resolve_restart_block_64bit_app (struct task_struct * task, struct pt_regs * regs) inline static
64 bit apps do not need to use restart block.
. TODO: Do this kernel patch also for 32 bit apps?
Definition at line 54 of file restart_fixup.h.
References is_in_syscall(), and mdbg.
Referenced by tcmi_resolve_restart_block().
{
     if ( is_in_syscall(regs) ) {
         mdbg(INFO3, "Performing restart in 64 bit syscall.");
         regs->ip -= 2;
         regs->ax = regs->orig_ax;
     } else {
         // For 64 bit applications we have a modified execve and we use orig_rax to set application rax, so we do not need to do restart trick
         // Do this only if we are not in syscall, otherwise we want current orig_eax to get into eax register
         regs->orig_ax = regs->ax;
     }
     return 0;
 }
static long tcmi_restart_fixup (struct restart_block * restart) static
This method is used for handling migration restart.
There are 2 cases:
Application was in syscall: We cannot directly restart the syscall, because as a part of process restart we do execve. The execve, if it succeeds, will set EAX to 0. This means, the restarted syscall will not be the original syscall, but sys_restartsyscall. Restart syscall is handled by the custom registered method in our case this method.
Application was not in syscall: We cannot simply restart the application, because again the execve will override EAX content! Here we use a special trick. We can assume EAX will contain 0 as in previous case (=execve succeeded, otherwise the program would not start anyway). With EAX == 0 we can set fake EIP just before the vsyscall sysenter (assuming it is mapped in the process on expected address) This way we will get sysretart called immediately and from the special restart function we return proper eax (and eip) in order to make the application working as expected, with all registers set correctly.
Definition at line 29 of file restart_fixup.h.
References mdbg.
{
     struct pt_regs *regs = task_pt_regs(current);
     mdbg(INFO3, "Calling tcmi sys restart. EAX: %08lX (OEAX: %08lX Return EAX: %08lX) SP: %16lX BP: %16lX (Restore BP: %16lX)", regs_return_value(regs), original_ax(regs), restart->arg0, stack_pointer(regs), base_pointer(regs), restart->arg2);
     /*mdbg(INFO3, "Calling tcmi sys restart. EAX: %08lX (OEAX: %08lX Return EAX: %08lX). EBX: %08lX ECX: %08lX EDX: %08lX", regs->eax, regs->orig_eax, restart->arg0, regs->ebx, regs->ecx, regs->edx);*/
     /* TODO: Reset restart_block? */
     /* Reset EIP to original value (either again just before the syscall, or on the other completely unrelated address */
     regs->ip = restart->arg1;
     /* Restore rcx */
     regs->cx = restart->arg2;
     /* To prevent ECX & EDX clobbering via sysexit */
     set_thread_flag(TIF_IRET);
     /*
            This is a trick how to get original EAX onto the stack.. return value of this syscall is what gets onto the stack
        When the syscall gets executed again (as we again set EIP) it will finally use correct EAX. The other registers are unclobbered and so we do not need to restore them
        If we were not originally in syscall, we will simply continue with correct EAX where we finished.
          */
     return restart->arg0;
 }