Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/ccfs/prefetcher.h File Reference
prefetcher.h File Reference
Functions
int initialize_prefetcher (void)
Initializes prefetching service, returns 0 upon success.
void finalize_prefetcher (void)
Synchronously terminates prefetching service.
void submit_for_prefetch (struct file *filp)
Submits file, whose content should be fully prefetched.
Function Documentation
void finalize_prefetcher (void)
Synchronously terminates prefetching service.
Definition at line 182 of file prefetcher.c.
References prefetcher_data::prefetcher_thread.
Referenced by ccfs_exit().
{
     int rc;
     if ( !prefetcher )
         return;
     rc = kthread_stop(prefetcher->prefetcher_thread);
     if ( rc ) {
         printk(KERN_ERR "Prefetcher stop failed with err %d\n", rc);
     }
     prefetcher->prefetcher_thread = NULL;
     kfree(prefetcher);
     prefetcher = NULL;
 }
int initialize_prefetcher (void)
Initializes prefetching service, returns 0 upon success.
Definition at line 154 of file prefetcher.c.
References prefetcher_data::enqueue_lock, prefetcher_run(), prefetcher_data::prefetcher_thread, prefetcher_data::request_wait, and prefetcher_data::requests.
Referenced by ccfs_init().
{
     struct task_struct* new_thread = NULL;
     if ( prefetcher )
         return -EINVAL;
     prefetcher = kmalloc(sizeof(struct prefetcher_data), GFP_KERNEL);
     if ( !prefetcher ) {
         return -EINVAL;
     }
     prefetcher->prefetcher_thread = new_thread;
     INIT_LIST_HEAD( & prefetcher->requests );
     spin_lock_init(&prefetcher->enqueue_lock);
     init_waitqueue_head( & prefetcher->request_wait );
     new_thread = kthread_run(prefetcher_run, NULL, "ccfs prefetching thread");
     if( IS_ERR(new_thread) ) {
         kfree(prefetcher);
         prefetcher = NULL;
         return PTR_ERR(new_thread);
     }
     prefetcher->prefetcher_thread = new_thread;
     return 0;
 }
void submit_for_prefetch (struct file * filp)
Submits file, whose content should be fully prefetched.
One file reference should be hold by the caller and this reference should be left to the prefetcher, who will free it after it is done with the prefetch.
Definition at line 198 of file prefetcher.c.
References prefetcher_data::enqueue_lock, prefetch_info::filp, prefetch_info::head, info, prefetcher_data::request_wait, and prefetcher_data::requests.
{
     struct prefetch_info* info = kmalloc(sizeof(struct prefetch_info), GFP_KERNEL);
     if ( !info ) {
         fput(filp);
         // We can ignore no-mem on prefetch, we simply do not prefetch..
         return;
     }
     info->filp = filp;
     spin_lock(&prefetcher->enqueue_lock);
     list_add(&info->head, &prefetcher->requests);
     spin_unlock(&prefetcher->enqueue_lock);
     wake_up(&prefetcher->request_wait);
 }