Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/syscall/tcmi_syscallhooks_other.c File Reference
tcmi_syscallhooks_other.c File Reference
#include <linux/capability.h>
#include <clondike/tcmi/tcmi_hooks.h>
#include <dbg.h>
#include <tcmi/syscall/tcmi_guest_rpc.h>
#include "tcmi_syscallhooks_other.h"
#include <tcmi/manager/tcmi_man.h>
#include <tcmi/manager/tcmi_penman.h>
#include <tcmi/manager/tcmi_ccnman.h>
#include <tcmi/task/tcmi_guesttask.h>
#include <proxyfs/proxyfs_server.h>
#include <director/director.h>
#include <asm/uaccess.h>
#include <linux/err.h>
Macros
#define TCMI_SYSCALLHOOKS_OTHER_PRIVATE
Functions
int tcmi_syscall_hooks_other_init (void)
<<public>> Registers all syscalls hooks with the kernel.
void tcmi_syscall_hooks_other_exit (void)
<<public>> Unregisters all syscalls hooks.
static long tcmi_syscall_hooks_sys_wait4 (pid_t pid, int __user *stat_addr, int options, struct rusage __user *ru)
<<private>> sys_wait4 system call hook.
static long tcmi_syscall_hooks_pre_fork (unsigned long clone_flags, unsigned long stack_start, struct pt_regs *regs, unsigned long stack_size, int __user *parent_tidptr, int __user *child_tidptr)
<<private>> pre-fork
static long tcmi_syscall_hooks_in_fork (struct task_struct *child)
<<private>> in-fork...
static long tcmi_syscall_hooks_post_fork (struct task_struct *child, long res, pid_t remote_pid, int __user *parent_tidptr, int __user *child_tidptr)
<<private>> post-fork
Macro Definition Documentation
#define TCMI_SYSCALLHOOKS_OTHER_PRIVATE
Definition at line 37 of file tcmi_syscallhooks_other.c.
Function Documentation
static long tcmi_syscall_hooks_in_fork (struct task_struct * child) static
<<private>> in-fork...
performs attachement of guest/shadow task to TCMI
Definition at line 112 of file tcmi_syscallhooks_other.c.
References TCMI_MAN, and tcmi_man_fork().
Referenced by tcmi_syscall_hooks_other_init().
{
     if ( current->tcmi.task_type == guest ) {
         // Parent task is guest => child will be guest
         struct tcmi_penman* pen_man = tcmi_penman_get_instance();
         return tcmi_man_fork(TCMI_MAN(pen_man), current, child);
     } else if ( current->tcmi.task_type == shadow ) {
         // Parent task is shadow => child should be shadow
         struct tcmi_ccnman* ccn_man = tcmi_ccnman_get_instance();
         return tcmi_man_fork(TCMI_MAN(ccn_man), current, child);
     }
     return 0;
 }
static long tcmi_syscall_hooks_post_fork (struct task_struct * child, long res, pid_t remote_pid, int __user * parent_tidptr, int __user * child_tidptr) static
<<private>> post-fork
Definition at line 131 of file tcmi_syscallhooks_other.c.
References director_task_fork(), mdbg, proxyfs_server_duplicate_all_parent(), tcmi_task::remote_pid, tcmi_guesttask_post_fork(), and TCMI_TASK.
Referenced by tcmi_syscall_hooks_other_init().
 {
     if ( current->tcmi.task_type == guest ) {
         // Guest task hook
         struct tcmi_task* child_task = NULL;
         if ( IS_ERR((void*)res) ) {
             mdbg(INFO3, "Resetting fork return values due to error");
             if ( parent_tidptr != NULL )
                 //put_user((int)-1, parent_tidptr);
             if ( child_tidptr != NULL ) {
                 //put_user((int)-1, child_tidptr);
             }
         } else {
             child_task = TCMI_TASK(child->tcmi.tcmi_task);
         }
         tcmi_guesttask_post_fork(TCMI_TASK(current->tcmi.tcmi_task), child_task, res, remote_pid);
         return remote_pid;
     } else if ( current->tcmi.task_type == shadow ) {
         // Shadow task hook
         // We have to duplicate all proxyfs file references for child.. this way we are in a same situation as
         // if the fork happend on CCN before the migration
         if (!IS_ERR((void*)res) ) {
             proxyfs_server_duplicate_all_parent(current, child);
         }
     }
     director_task_fork(res, current->pid);
     return res;
 };
static long tcmi_syscall_hooks_pre_fork (unsigned long clone_flags, unsigned long stack_start, struct pt_regs * regs, unsigned long stack_size, int __user * parent_tidptr, int __user * child_tidptr) static
<<private>> pre-fork
Definition at line 97 of file tcmi_syscallhooks_other.c.
References tcmi_guest_rpc, tcmi_rpc_call6(), and TCMI_RPC_SYS_FORK.
Referenced by tcmi_syscall_hooks_other_init().
   {
     // Pre-fork is hooked only on DN, on CN we fork normally
     if ( current->tcmi.task_type == guest ) {
         return tcmi_rpc_call6(tcmi_guest_rpc, TCMI_RPC_SYS_FORK, clone_flags, stack_start, (unsigned long)regs, stack_size, (unsigned long)parent_tidptr, (unsigned long)child_tidptr);
     }
     return 0;
 };
static long tcmi_syscall_hooks_sys_wait4 (pid_t pid, int __user * stat_addr, int options, struct rusage __user * ru) static
<<private>> sys_wait4 system call hook.
Definition at line 89 of file tcmi_syscallhooks_other.c.
References tcmi_guest_rpc, tcmi_rpc_call4(), and TCMI_RPC_SYS_WAIT4.
Referenced by tcmi_syscall_hooks_other_init().
{
     return tcmi_rpc_call4(tcmi_guest_rpc, TCMI_RPC_SYS_WAIT4, pid, (unsigned long)stat_addr, options, (unsigned long)ru);
 };