Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/syscall/tcmi_syscallhooks_signal.c File Reference
tcmi_syscallhooks_signal.c File Reference
#include <linux/capability.h>
#include <clondike/tcmi/tcmi_hooks.h>
#include <dbg.h>
#include <tcmi/syscall/tcmi_guest_rpc.h>
#include <asm-generic/siginfo.h>
#include "tcmi_syscallhooks_signal.h"
Macros
#define TCMI_SYSCALLHOOKS_SIGNAL_PRIVATE
Functions
int tcmi_syscall_hooks_signal_init (void)
<<public>> Registers all syscalls hooks with the kernel.
void tcmi_syscall_hooks_signal_exit (void)
<<public>> Unregisters all syscalls hooks.
static long tcmi_syscall_hooks_sys_kill (int pid, int sig)
<<private>> Kill system call hook.
static long tcmi_syscall_hooks_do_tkill (int tgid, int pid, int sig)
<<private>> do_tkill hook.
static long tcmi_syscall_hooks_sys_rt_sigqueueinfo (int pid, int sig, siginfo_t *info)
<<private>> sys_rt_sigqueueinfo hook.
Macro Definition Documentation
#define TCMI_SYSCALLHOOKS_SIGNAL_PRIVATE
Definition at line 37 of file tcmi_syscallhooks_signal.c.
Function Documentation
static long tcmi_syscall_hooks_do_tkill (int tgid, int pid, int sig) static
<<private>> do_tkill hook.
Handles both tkill and tgkill system call
Parameters
tgid - the thread group ID of the thread
pid - the PID of the thread
sig - signal to be sent
Returns
- zero on sucess.
Definition at line 95 of file tcmi_syscallhooks_signal.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_TKILL.
Referenced by tcmi_syscall_hooks_signal_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_TKILL, tgid, pid, sig);
 }
static long tcmi_syscall_hooks_sys_kill (int pid, int sig) static
<<private>> Kill system call hook.
Parameters
pid - PID of signal target
sig - what signal
Returns
- zero on sucess.
Definition at line 80 of file tcmi_syscallhooks_signal.c.
References tcmi_guest_rpc, tcmi_rpc_call2(), and TCMI_RPC_SYS_KILL.
Referenced by tcmi_syscall_hooks_signal_init().
 {
     return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_KILL, pid, sig);
 }
static long tcmi_syscall_hooks_sys_rt_sigqueueinfo (int pid, int sig, siginfo_t * info) static
<<private>> sys_rt_sigqueueinfo hook.
Parameters
pid - the PID of the thread
sig - signal to be sent
*info - pointer siginfo struct in kernel space
Returns
- zero on sucess.
Definition at line 109 of file tcmi_syscallhooks_signal.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_SIGQUEUE.
Referenced by tcmi_syscall_hooks_signal_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_SIGQUEUE, pid, sig, (unsigned long)info);
 }