Clondike: kkc_arch class
kkc_arch class
KKC
This class describes a particular network architecture.
Data Structures
struct kkc_arch_ops
Architecture specific operations.
struct kkc_arch
Compound structure, describes one particular architecture.
Macros
#define KKC_MAX_ARCH_LENGTH 20
Maximum architecture string length.
#define KKC_ARCH_PREFIX kkc_arch_
KKC architecture prefix.
#define KKC_ARCH_PREFIX_STR __stringify(KKC_ARCH_PREFIX)
KKC architecture prefix in string form - used when looking up particular architecture.
#define KKC_ARCH(a_name) kkc_arch_##a_name
Constructs the architecture symbol name.
#define KKC_ARCH_OBJ(o) ((kkc_arch_obj_t)o)
Casts to the architecture object.
#define KKC_ARCH_DECLARE(a_name, a_ops, a_data)
Declares a KKC architecture.
Typedefs
typedef void * kkc_arch_obj_t
Describes a generic KKC architecture object.
Functions
static char * kkc_arch_name (struct kkc_arch *self)
<<public>> Architecture name accessor.
static struct kkc_arch * kkc_arch_get (struct kkc_arch *self)
<<public>> Increments the reference counter on the module owning the architecture.
static struct kkc_arch * kkc_arch_get_by_name (char *arch_name)
<<public>> Retrieves an architecture by name.
static void kkc_arch_put (struct kkc_arch *self)
<<public>> Decrements the reference counter on the module owning the architecture.
static kkc_arch_obj_t kkc_arch_obj_new (struct kkc_arch *self)
<<public>> Calls the constructor to build the architecture specific object.
Detailed Description
This class describes a particular network architecture.
Each architecture has its unique name. Based on this name, the main KKC module will lookup a particular architecture to create a user specified object.
The instances of kkc_arch are to be created at compile time by the corresponding architecture socket class(e.g. kkc_sock_tcp). The socket class then provides architecture specific operations. Currently, there is only one operation needed - the socket constructor.
Also each particular architecture instance retains a reference to a module where it has been declared. Each object created via the architecture owns a reference to the architecture. That way, the module can't get unloaded when instance of its sockets still exist.
Data Structure Documentation
struct kkc_arch_ops
Architecture specific operations.
Definition at line 65 of file kkc_arch.h.
Data Fields
kkc_arch_obj_t(* kkc_arch_obj_new)(void)
instantiates a KKC object.
Field Documentation
kkc_arch_obj_t(* kkc_arch_ops::kkc_arch_obj_new)(void)
instantiates a KKC object.
Definition at line 67 of file kkc_arch.h.
struct kkc_arch
Compound structure, describes one particular architecture.
Definition at line 72 of file kkc_arch.h.
Data Fields
struct kkc_arch_ops * arch_ops Architecture specific operations.
void * data Any data needed by particular network architecture.
char name[20] Name of network architecture (e.g.
'tcp').
struct module * owner Module owning this architecture.
Macro Definition Documentation
#define KKC_ARCH (a_name) kkc_arch_##a_name
Constructs the architecture symbol name.
Definition at line 94 of file kkc_arch.h.
Referenced by kkc_sock_tcp_new().
#define KKC_ARCH_DECLARE (a_name, a_ops, a_data)
Value:
struct kkc_arch KKC_ARCH(a_name) = {        \
    .name = #a_name,            \
    .arch_ops = a_ops,          \
    .owner = THIS_MODULE,           \
    .data = a_data              \
};                      \
EXPORT_SYMBOL_GPL(KKC_ARCH(a_name))
Declares a KKC architecture.
This is the preferred way of declaring of a new architecture by specific architecture modules.
Parameters
a_name - name of the kkc architecture identifier (not quoted)
a_ops - pointer to the architecture specific operations
a_data - pointer to the architecture specific data
Definition at line 109 of file kkc_arch.h.
#define KKC_ARCH_OBJ (o) ((kkc_arch_obj_t)o)
Casts to the architecture object.
Definition at line 98 of file kkc_arch.h.
Referenced by kkc_sock_tcp_new().
#define KKC_ARCH_PREFIX kkc_arch_
KKC architecture prefix.
Definition at line 88 of file kkc_arch.h.
#define KKC_ARCH_PREFIX_STR __stringify(KKC_ARCH_PREFIX)
KKC architecture prefix in string form - used when looking up particular architecture.
Definition at line 91 of file kkc_arch.h.
Referenced by kkc_arch_get_by_name().
#define KKC_MAX_ARCH_LENGTH 20
Maximum architecture string length.
Definition at line 59 of file kkc_arch.h.
Referenced by kkc_arch_get_by_name(), kkc_get_architecture(), mount_proxyfs(), tcmi_sock_getarchname(), and tcmi_sock_new().
Typedef Documentation
typedef void* kkc_arch_obj_t
Describes a generic KKC architecture object.
Definition at line 62 of file kkc_arch.h.
Function Documentation
static struct kkc_arch* kkc_arch_get (struct kkc_arch * self) static read
<<public>> Increments the reference counter on the module owning the architecture.
So that he module can't get unloaded when being used.
Parameters
*self - pointer to this architecture instance
Returns
pointer to the architecture if succeeded in getting the module or NULL
Definition at line 138 of file kkc_arch.h.
References self.
Referenced by kkc_sock_tcp_new().
 {
        if (try_module_get(self->owner))
            return self;
        return NULL;
 }
static struct kkc_arch* kkc_arch_get_by_name (char * arch_name) static read
<<public>> Retrieves an architecture by name.
This requires merging the architecture name with the architecture prefix and asking the kernel to retrieve the symbol specified by this string.
This is a class method
Parameters
arch_name - name of the architecture requested (e.g. 'tcp')
Returns
- instance of the kkc_arch that handles the specified type
Definition at line 154 of file kkc_arch.h.
References KKC_ARCH_PREFIX_STR, KKC_MAX_ARCH_LENGTH, and mdbg.
Referenced by kkc_get_architecture().
 {
     char sym[sizeof(KKC_ARCH_PREFIX_STR) + KKC_MAX_ARCH_LENGTH];
     strlcpy(sym, KKC_ARCH_PREFIX_STR, sizeof(KKC_ARCH_PREFIX_STR) + KKC_MAX_ARCH_LENGTH);
     strlcat(sym, arch_name, sizeof(KKC_ARCH_PREFIX_STR) + KKC_MAX_ARCH_LENGTH);
     mdbg(INFO3, "Getting architecture '%s', prefix: '%s'", sym, MODULE_SYMBOL_PREFIX);
     return (struct kkc_arch*) __symbol_get((const char*)sym);
 }
static char* kkc_arch_name (struct kkc_arch * self) inline static
<<public>> Architecture name accessor.
Parameters
*self - pointer to this architecture instance
Returns
pointer to the architecture describing string
Definition at line 125 of file kkc_arch.h.
Referenced by kkc_sock_getarchname().
 {
     return self->name;
 }
static kkc_arch_obj_t kkc_arch_obj_new (struct kkc_arch * self) inline static
<<public>> Calls the constructor to build the architecture specific object.
Parameters
*self - pointer to this architecture instance
Returns
architecture object instance or NULL
Definition at line 183 of file kkc_arch.h.
References self.
Referenced by kkc_establish().
 {
     kkc_arch_obj_t obj = NULL;
     if (self->arch_ops && self->arch_ops->kkc_arch_obj_new)
         obj = self->arch_ops->kkc_arch_obj_new();
     return obj;
 }
static void kkc_arch_put (struct kkc_arch * self) inline static
<<public>> Decrements the reference counter on the module owning the architecture.
Parameters
*self - pointer to this architecture instance
Definition at line 171 of file kkc_arch.h.
References self.
Referenced by kkc_establish(), and kkc_sock_put().
 {
     return module_put(self->owner);
 }