Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/migration/fs/9p_fs_global_mounter.c File Reference
9p_fs_global_mounter.c File Reference
#include <linux/slab.h>
#include "9p_fs_global_mounter.h"
#include "fs_mounter.h"
#include <dbg.h>
#include "9p_fs_helper.h"
#include <tcmi/lib/util.h>
Macros
#define MAX_MOUNT_ROOT_PATH 300
Functions
static void get_mount_root (const char *device, int fsuid, int fsgid, char *mount_root)
static int global_9p_mount (struct fs_mounter *mounter, int16_t fsuid, int16_t fsgid)
static int chroot_to_mount (struct fs_mounter *mounter, int16_t fsuid, int16_t fsgid)
struct fs_mounter * new_9p_global_fs_mounter (struct fs_mount_params *params)
9p mounter handles mounting of Plan9 filesystem in a public namespace.
Macro Definition Documentation
#define MAX_MOUNT_ROOT_PATH 300
Definition at line 8 of file 9p_fs_global_mounter.c.
Referenced by chroot_to_mount(), and global_9p_mount().
Function Documentation
static int chroot_to_mount (struct fs_mounter * mounter, int16_t fsuid, int16_t fsgid) static
Definition at line 48 of file 9p_fs_global_mounter.c.
References chroot_to(), get_mount_root(), MAX_MOUNT_ROOT_PATH, fs_mount_params::mount_device, and fs_mounter::params.
Referenced by new_9p_global_fs_mounter().
{
     int err = 0;
     char mount_buffer[MAX_MOUNT_ROOT_PATH];
     get_mount_root(mounter->params.mount_device, fsuid, fsgid, mount_buffer);
     if ( (err = chroot_to(mount_buffer)) )
         return err;
     return 0;
 }
static void get_mount_root (const char * device, int fsuid, int fsgid, char * mount_root) static
Definition at line 10 of file 9p_fs_global_mounter.c.
Referenced by chroot_to_mount(), and global_9p_mount().
{
     // TODO: Now we have fixed "root" of mount to /mnt/clondike.. maybe we can parametrize that? ;)
     sprintf(mount_root, "/mnt/clondike/%s-%d-%d", device, fsuid, fsgid);
 }
static int global_9p_mount (struct fs_mounter * mounter, int16_t fsuid, int16_t fsgid) static
Definition at line 15 of file 9p_fs_global_mounter.c.
References get_mount_root(), MAX_MOUNT_ROOT_PATH, minfo, mk_dir(), mount_9p_fs(), fs_mount_params::mount_device, and fs_mounter::params.
Referenced by new_9p_global_fs_mounter().
{
     int err = 0;
     char mount_buffer[MAX_MOUNT_ROOT_PATH], root_buffer[MAX_MOUNT_ROOT_PATH+6];
     //struct nameidata nd;  Replaced to struct path for use function kern_path() instead of  path_lookup()
     struct path p;
     get_mount_root(mounter->params.mount_device, fsuid, fsgid, mount_buffer);
     err = kern_path(mount_buffer, LOOKUP_FOLLOW | LOOKUP_DIRECTORY ,&p);
     if ( err ) {
         minfo(ERR1, "Failed to lookup path %s: %d. Trying to create", mount_buffer, err);
         err = mk_dir(mount_buffer, 777);
     }
     if ( err ) {
         // TODO: For now, the dirs for mount have to be precreated.. they can be for example
         // auto created via a user-space controller. In kernel, we do not have access to mkdir, right?
         minfo(ERR1, "Failed to lookup path %s: %d. Creation failed.", mount_buffer, err);
         return err;
     }
     sprintf(root_buffer, "%s/root", mount_buffer);
     // TODO: In critical section so that we do not do multiple mounts
     err = kern_path(root_buffer, LOOKUP_FOLLOW | LOOKUP_DIRECTORY ,&p);
         if ( err ) {
         // We've checked that "root"/root does not exist (We assume existence of a root dir in root of fs
         // => 9p is not yet globally mount => mount
         if ( (err = mount_9p_fs(mount_buffer, mounter, fsuid, fsgid)) ) {
             minfo(ERR1, "Mount failed with err %d", err);
             return err;
         }
     }
     return 0;
 }
struct fs_mounter* new_9p_global_fs_mounter (struct fs_mount_params * params) read
9p mounter handles mounting of Plan9 filesystem in a public namespace.
It does not support any security right not.Creates a new instance of the 9p file system mounter
Definition at line 61 of file 9p_fs_global_mounter.c.
References chroot_to_mount(), fs_mounter::free, global_9p_mount(), fs_mounter::global_mount, fs_mounter::params, and fs_mounter::private_mount.
{
     struct fs_mounter* mounter = kmalloc(sizeof(struct fs_mounter), GFP_KERNEL);
     if ( !mounter )
         return NULL;
     mounter->global_mount = global_9p_mount;
     mounter->private_mount = chroot_to_mount;
     mounter->free = NULL;
     mounter->params = *params;
     return mounter;
 }