Clondike: tcmi_migcom class
tcmi_migcom class
migration
A <<singleton>> class that handles migration requests from user space as well as from migration managers.
Functions
static int tcmi_migcom_migrated_task (void *data)
<<private>> This method represents a kernel thread that will eventually become the 'immigrated' task.
int tcmi_migcom_guest_fork (struct task_struct *parent, struct task_struct *child, struct tcmi_migman *migman)
<<public>> Fork of guest.
int tcmi_migcom_shadow_fork (struct task_struct *parent, struct task_struct *child, struct tcmi_migman *migman)
<<public>> Fork of shadow
static void tcmi_migcom_mig_mode_handler (void)
<<private>> This handler is invoked when the sig_unused hook finds a non-NULL entry in the clondike record in the task_struct.
int tcmi_migcom_emigrate_ccn_ppm_p (pid_t pid, struct tcmi_migman *migman)
<<public>> Migrates a task from a CCN to a PEN
int tcmi_migcom_emigrate_ccn_npm (pid_t pid, struct tcmi_migman *migman, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
<<public>> Migrates non-preemptively a task from a CCN to a PEN
int tcmi_migcom_immigrate (struct tcmi_msg *m, struct tcmi_migman *migman)
<<public>> Immigrates a task - handles accepting the task on the PEN side
int tcmi_migcom_migrate_home_ppm_p (pid_t pid)
<<public>> Migrates task home from PEN (method can be used both on PEN or CCN)
Detailed Description
A <<singleton>> class that handles migration requests from user space as well as from migration managers.
Function Documentation
int tcmi_migcom_emigrate_ccn_npm (pid_t pid, struct tcmi_migman * migman, struct pt_regs * regs, struct tcmi_npm_params * npm_params)
<<public>> Migrates non-preemptively a task from a CCN to a PEN
Definition at line 203 of file tcmi_migcom.c.
References director_emigration_failed(), mdbg, minfo, tcmi_migcom_mig_mode_handler(), tcmi_migman_get(), tcmi_migman_migproc_dir(), tcmi_migman_put(), tcmi_migman_root(), tcmi_migman_sock(), tcmi_shadowtask_new(), tcmi_task_emigrate_npm(), tcmi_task_local_pid(), tcmi_task_put(), tcmi_task_submit_method(), tcmi_taskhelper_attach(), and tcmi_taskhelper_do_mig_mode().
{
     int err = 0;
     struct tcmi_task *shadow;
     /* create a new PPM shadow task for physical ckpt image  */
     if (!(shadow =
           tcmi_shadowtask_new(pid, migman,
                   tcmi_migman_sock(migman),
                   tcmi_migman_migproc_dir(migman),
                   tcmi_migman_root(migman)))) {
         minfo(ERR3, "Error creating a shadow task");
         goto exit0;
     }
     /* submit the emigrate method */
     mdbg(INFO3, "Submitting emigrate_ppm_p");
     tcmi_task_submit_method(shadow, tcmi_task_emigrate_npm, &npm_params, sizeof(void*));
     /* attaches the shadow to its thread. */
     if (tcmi_taskhelper_attach(shadow, tcmi_migcom_mig_mode_handler) < 0) {
         mdbg(ERR3, "Failed attaching shadow PID=%d to its thread",
              tcmi_task_local_pid(shadow));
         goto exit1;
     }
     /* release the shadow instance reference (Reference is now held by the associated task_struct - it got it in attach method)*/
     tcmi_task_put(shadow);
     /* Task now holds its reference to a migman so we can release it */
     tcmi_migman_put(migman);
     /* We are already in migmode so we can directly execute handler here */
     tcmi_taskhelper_do_mig_mode(regs);
     //tcmi_migcom_mig_mode_handler();
     // We get here only if npm migration failed, othewise either of the following happens:
     // - task finishes remotely, so the handler exists
     // - task migrates back, so it must execve to a new checkpoint => we still do not get here
     mdbg(INFO3, "Got after npm migration handler start");
     director_emigration_failed(pid);
     // Ok, the emigration failed. Task is going to release its reference to migman and we've release the reference we got
     // from the manager.. we have to retake this reference so that the release made by manager has matching get
     // TODO: This is incorrect.. task is already freed and has freed its reference! It may happen, that the migman is already freed!
     // How to solve this nicely? .. ;)
     tcmi_migman_get(migman);
     return 0;
     /* error handling */
  exit1:
     tcmi_task_put(shadow);
  exit0:
     return err;
 };
int tcmi_migcom_emigrate_ccn_ppm_p (pid_t pid, struct tcmi_migman * migman)
<<public>> Migrates a task from a CCN to a PEN
<<public>> Migrates a task from a CCN to a PEN
This requires:
instantiating a new shadow task - requires migration manager ID, communication socket, migproc directory(where the shadow will present its information) and root directory of the migration manager(for a symbolic link)
submitting emigration method
attaching the shadow task to the target process that is to be migrated
forcing the target process into migration mode
checking if the process has properly picked up the shadow task
This method exclusively uses preemptive process migration using physical checkpoint image.
Parameters
pid - task that is to be migrated
*migman - migration manager that will provide the communication channel for the migrated task.
Returns
0 upon success;
Definition at line 152 of file tcmi_migcom.c.
References director_emigration_failed(), mdbg, minfo, tcmi_migcom_mig_mode_handler(), tcmi_migman_migproc_dir(), tcmi_migman_root(), tcmi_migman_sock(), tcmi_shadowtask_new(), tcmi_task_emigrate_ppm_p(), tcmi_task_local_pid(), tcmi_task_put(), tcmi_task_submit_method(), tcmi_taskhelper_attach(), tcmi_taskhelper_enter_mig_mode(), and tcmi_taskhelper_wait_for_pick_up_timeout().
 {
     int err = 0;
     struct tcmi_task *shadow;
     /* create a new PPM shadow task for physical ckpt image  */
     if (!(shadow =
           tcmi_shadowtask_new(pid, migman,
                   tcmi_migman_sock(migman),
                   tcmi_migman_migproc_dir(migman),
                   tcmi_migman_root(migman)))) {
         minfo(ERR3, "Error creating a shadow task");
         goto exit0;
     }
     /* submit the emigrate method */
     mdbg(INFO3, "Submitting emigrate_ppm_p");
     tcmi_task_submit_method(shadow, tcmi_task_emigrate_ppm_p, NULL, 0);
     /* attaches the shadow to its thread. */
     if (tcmi_taskhelper_attach(shadow, tcmi_migcom_mig_mode_handler) < 0) {
         mdbg(ERR3, "Failed attaching shadow PID=%d to its thread",
              tcmi_task_local_pid(shadow));
         goto exit1;
     }
     /* switch the task to migration mode */
     tcmi_taskhelper_enter_mig_mode(shadow);
     /* wait for pickup */
     if (tcmi_taskhelper_wait_for_pick_up_timeout(shadow, 2*HZ) < 0) {
         mdbg(INFO1, "Shadow not picked up: %p", shadow);
         director_emigration_failed(pid);
     } else {
         mdbg(INFO1, "Shadow successfully picked up: %p", shadow);
     }
     /* release the shadow instance reference (Reference is now held by the associated task_struct - it got it in attach method)*/
     tcmi_task_put(shadow);
     return 0;
     /* error handling */
  exit1:
     tcmi_task_put(shadow);
  exit0:
     return err;
 }
int tcmi_migcom_guest_fork (struct task_struct * parent, struct task_struct * child, struct tcmi_migman * migman)
<<public>> Fork of guest.
<<public>> Fork of guest
Called in parent process context
Definition at line 533 of file tcmi_migcom.c.
References mdbg, tcmi_guesttask_new(), tcmi_guesttask_post_fork_set_tid(), tcmi_migcom_mig_mode_handler(), tcmi_migman_migproc_dir(), tcmi_migman_root(), tcmi_migman_sock(), tcmi_task_local_pid(), tcmi_task_mount_proxyfs(), tcmi_task_put(), tcmi_task_submit_method(), tcmi_taskhelper_attach_exclusive(), and tcmi_taskhelper_enter_mig_mode_exclusive().
{
     struct tcmi_task *guest;
     struct kkc_sock* sock;
     mdbg(INFO3, "Forking guest process => Making a new child guest as well.");
     // TODO: We have to mount proxyfs&clondike fs in the child context.. schedule method to do that here
     if (!(guest = tcmi_guesttask_new(child->pid, migman,
                     tcmi_migman_sock(migman),
                     tcmi_migman_migproc_dir(migman),
                     tcmi_migman_root(migman)))) {
         mdbg(ERR3, "Error creating a guest task on fork");
         goto exit0;
     }
     sock = tcmi_migman_sock(migman);
     tcmi_task_submit_method(guest, tcmi_task_mount_proxyfs, &sock, sizeof(struct kkc_sock*));
     // Submit method, that will set tid of task into a user context.. it has to be done from that process context!
     tcmi_task_submit_method(guest, tcmi_guesttask_post_fork_set_tid, NULL, 0);
     /* attaches the shadow to its thread. */
     if (tcmi_taskhelper_attach_exclusive(child, guest, tcmi_migcom_mig_mode_handler) < 0) {
         mdbg(ERR3, "Failed attaching guest PID=%d to its thread",
              tcmi_task_local_pid(guest));
         goto exit1;
     }
     /* release the the instance reference (Reference is now held by the associated task_struct - it got it in attach method)*/
     tcmi_task_put(guest);
     /* switch the task to migration mode */
     tcmi_taskhelper_enter_mig_mode_exclusive(child, guest);
     return 0;
 exit1:
     tcmi_task_put(guest);
 exit0:
     return -EINVAL;
 }
int tcmi_migcom_immigrate (struct tcmi_msg * m, struct tcmi_migman * migman)
<<public>> Immigrates a task - handles accepting the task on the PEN side
<<public>> Immigrates a task - handles accepting the task on the PEN side
This method immigrates a new task based on an emigration message that a PEN has received as follows:
creates a new kernel thread that will wait until the new guest process is instantiated (waits with timeout on guest_ready completion)
instantiates a new guest task.
delivers the migration message to it and makes a necessary setup, so that the guest task processes the message as soon as it becomes a regular migrated process
attaches the guest to its new process(thread)
announces that the guest instance is ready to the thread via completion
waits for the thread to pickup the guest and become a migrated process
Parameters
*m - a message based on which we are immigrating the task
*migman - migration manager that will provide the communication channel for the migrated task. migration information
Returns
0 upon success
Definition at line 294 of file tcmi_migcom.c.
References director_immigration_confirmed(), director_immigration_request(), free_mounter(), immigrate_startup_params::fs_ready, immigrate_startup_params::fsgid, immigrate_startup_params::fsuid, get_new_mounter(), fs_mounter::global_mount, mdbg, minfo, immigrate_startup_params::mount_params, pid, immigrate_startup_params::sock, tcmi_guesttask_new(), tcmi_migcom_mig_mode_handler(), tcmi_migcom_migrated_task(), tcmi_migman_migproc_dir(), tcmi_migman_root(), tcmi_migman_slot_index(), tcmi_migman_sock(), tcmi_msg_get(), tcmi_msg_put(), TCMI_P_EMIGRATE_MSG, tcmi_p_emigrate_msg_euid(), tcmi_p_emigrate_msg_exec_name(), tcmi_p_emigrate_msg_fsgid(), tcmi_p_emigrate_msg_fsuid(), tcmi_p_emigrate_msg_reply_pid(), TCMI_PENMIGMAN, tcmi_penmigman_get_mount_params(), tcmi_task_deliver_msg(), tcmi_task_local_pid(), tcmi_task_process_msg(), tcmi_task_put(), tcmi_task_submit_method(), tcmi_taskhelper_attach(), and tcmi_taskhelper_wait_for_pick_up_timeout().
Referenced by tcmi_penmigman_process_msg().
 {
     int err = -EINVAL;
     int pid;
     int wait_for_msg = 0;
     struct fs_mounter* mounter;
     struct immigrate_startup_params startup_params;
     struct tcmi_task *guest;
     struct tcmi_penmigman* penmigman = TCMI_PENMIGMAN(migman);
     struct tcmi_p_emigrate_msg* msg = TCMI_P_EMIGRATE_MSG(m);
     int accept = 0;
     int call_res = director_immigration_request(tcmi_migman_slot_index(migman), tcmi_p_emigrate_msg_euid(msg), tcmi_p_emigrate_msg_exec_name(msg), &accept);
     if ( call_res == 0 ) {
         if ( !accept ) {
             mdbg(INFO2, "Immigration rejected by director.");
             // Rejected immigration
             return -EINVAL;
         }
     }
     init_completion(&startup_params.guest_ready);
     init_completion(&startup_params.fs_ready);
     startup_params.mount_params = tcmi_penmigman_get_mount_params(penmigman);
     startup_params.sock = tcmi_migman_sock(migman);
     startup_params.fsuid = tcmi_p_emigrate_msg_fsuid(msg);
     startup_params.fsgid = tcmi_p_emigrate_msg_fsgid(msg);
     // Global part of mount
     mounter = get_new_mounter(startup_params.mount_params);
     if ( mounter && mounter->global_mount ) {
         /* Some file system mounter is registered => perform the mount */
         mdbg(INFO2, "Doing global mount");
         err = mounter->global_mount(mounter, startup_params.fsuid, startup_params.fsgid);
         if ( err ) {
             free_mounter(mounter);
             goto exit0;
         }
     }
     free_mounter(mounter);
     /* new thread is started with a private namespace so that the mounts in that thread are not global */
     if ((pid = kernel_thread(tcmi_migcom_migrated_task, &startup_params, CLONE_NEWNS)) < 0) {
         mdbg(ERR3, "Cannot start kernel thread for guest process %d", pid);
         goto exit0;
     }
     /* before we proceed with restarting, we have to wait till the file system mount is ready (if it is performed) */
     if ((err = wait_for_completion_interruptible(&startup_params.fs_ready))) {
         minfo(ERR3, "Received signal fs not ready");
         goto exit0;
     }
     if (!(guest = tcmi_guesttask_new(pid, migman,
                     tcmi_migman_sock(migman),
                     tcmi_migman_migproc_dir(migman),
                     tcmi_migman_root(migman)))) {
         mdbg(ERR3, "Error creating a guest task");
         goto exit0;
     }
     /* have the guest task deliver the message to itself, extra message reference is for the guest.*/
     if (tcmi_task_deliver_msg(guest, tcmi_msg_get(m)) < 0) {
         mdbg(ERR3, "Error delivering the message to the guest process");
         tcmi_msg_put(m);
     }
     /* The message will be processed first. Submitted version does not wait for other messages,
     so that it does not block potential processing of other methods later. */
     tcmi_task_submit_method(guest, tcmi_task_process_msg, &wait_for_msg, sizeof(int));
     /* attaches the guest to its thread. */
     if (tcmi_taskhelper_attach(guest, tcmi_migcom_mig_mode_handler) < 0) {
         minfo(ERR3, "Failed attaching guest PID=%d to its thread",
               tcmi_task_local_pid(guest));
         goto exit1;
     }
     /* signal the new thread that the guest is ready. */
     complete(&startup_params.guest_ready);
     /* wait for pickup */
     if (tcmi_taskhelper_wait_for_pick_up_timeout(guest, 2*HZ) < 0) {
         mdbg(ERR1, "Guest not picked up: %p!!!!", guest);
         goto exit1;
     }
     mdbg(INFO2, "Guest successfully picked up: %p", guest);
     director_immigration_confirmed(tcmi_migman_slot_index(migman), tcmi_p_emigrate_msg_euid(msg), tcmi_p_emigrate_msg_exec_name(msg), pid, tcmi_p_emigrate_msg_reply_pid(msg));
     tcmi_task_put(guest);
     return 0;
     /* error handling */
  exit1:
     tcmi_task_put(guest);
  exit0:
     return err;
 }
static void tcmi_migcom_mig_mode_handler (void) static
<<private>> This handler is invoked when the sig_unused hook finds a non-NULL entry in the clondike record in the task_struct.
What needs to be done:
check whether the process in migration mode has a valid TCMI task
launch the method pump
based on its return status:
let's the task return to user mode
detaches the TCMI task from the process and resumes user mode
detaches the TCMI task from the process and kills the process
Definition at line 625 of file tcmi_migcom.c.
References tcmi_task::exit_code, mdbg, TCMI_TASK_EXECVE_FAILED_KILL_ME, tcmi_task_exit_code(), TCMI_TASK_KEEP_PUMPING, TCMI_TASK_KILL_ME, TCMI_TASK_LET_ME_GO, TCMI_TASK_MOVE_ME, tcmi_task_process_methods(), tcmi_task_put(), TCMI_TASK_REMOVE_AND_LET_ME_GO, tcmi_taskhelper_detach(), and tcmi_taskhelper_sanity_check().
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_migcom_guest_fork(), tcmi_migcom_immigrate(), and tcmi_migcom_shadow_fork().
 {
     struct tcmi_task *tmp, *task;
     int res;
     long exit_code;
     mdbg(INFO3, "Migration mode handler for task '%s' stack rp(%p) executing",
          current->comm, &res);
     if (!(task = tcmi_taskhelper_sanity_check())) {
         mdbg(ERR2, "Process %p PID=%d - invalid entry to migration mode",
               current, current->pid);
         goto exit0;
     }
     /* keep moving the task between migration managers */
     while ((res = tcmi_task_process_methods(task)) ==
            TCMI_TASK_MOVE_ME);
     /* check the result of the last method processed */
     switch (res) {
     case TCMI_TASK_KEEP_PUMPING:
         mdbg(INFO2, "KEEP PUMPING - but no methods left %d", res);
         break;
     case TCMI_TASK_LET_ME_GO:
         mdbg(INFO2, "LET ME GO - request %d", res);
         break;
         /* no need for special handling a fall through causes
          * do_exit which invokes the migration handler again. */
     case TCMI_TASK_EXECVE_FAILED_KILL_ME:
         mdbg(INFO2, "EXECVE_FAILED KILL ME - request %d", res);
         break;
     case TCMI_TASK_KILL_ME:
         mdbg(INFO2, "KILL ME - request %d", res);
         tmp = tcmi_taskhelper_detach();
         /* get the exit code prior terminating. */
         exit_code = tcmi_task_exit_code(tmp);
         tcmi_task_put(tmp);
         mdbg(INFO2, "Put done, going to exit %ld", exit_code);
         complete_and_exit(NULL, exit_code);
         break;
     case TCMI_TASK_REMOVE_AND_LET_ME_GO:
         mdbg(INFO2, "REMOVE AND LET ME GO - request %d", res);
         tcmi_task_put(tcmi_taskhelper_detach());
         break;
     default:
         mdbg(ERR2, "Unexpected result %d.", res);
         break;
     }
     /* error handling */
  exit0:
     return;
 }
int tcmi_migcom_migrate_home_ppm_p (pid_t pid)
<<public>> Migrates task home from PEN (method can be used both on PEN or CCN)
<<public>> Migrates task home from PEN (method can be used both on PEN or CCN)
The approach is the same on CCN and PEN:
send a notification to a process with a given PID.
the priority is set to 1 which causes all method from the TCMI task to be flushed from its method queue.
Parameters
pid - task that is to be migrated
Returns
0 upon success;
Definition at line 409 of file tcmi_migcom.c.
References mdbg, tcmi_task_migrateback_ppm_p(), and tcmi_taskhelper_notify_by_pid().
Referenced by tcmi_guesttask_process_msg(), and tcmi_penmigman_migrate_all_home().
 {
     /* set priority for the method - causes all methods to be flushed */
     int prio = 1;
     mdbg(INFO4, "request to migrate home pid %d", pid);
     return tcmi_taskhelper_notify_by_pid(pid, tcmi_task_migrateback_ppm_p,
                          NULL, 0, prio);
 }
static int tcmi_migcom_migrated_task (void * data) static
<<private>> This method represents a kernel thread that will eventually become the 'immigrated' task.
It does following:
tries to mount a distributed filesystem, if required (note, that this must be done by this thread as we are mounting into its private namespace)
mounts a proxyfs into a private namespace
waits until signalled, that the guest is ready
runs its migration mode handler (this picks up the task).
Parameters
*data - pointer to startup parameters
Returns
shouldn't return as the execve will overlay current execution image.
Todo:
process identity should be set according to the the user configuration (tcmi_confman)
Definition at line 439 of file tcmi_migcom.c.
References free_mounter(), immigrate_startup_params::fs_ready, immigrate_startup_params::fsgid, immigrate_startup_params::fsuid, get_new_mounter(), mdbg, minfo, mount_local_procfs(), immigrate_startup_params::mount_params, mount_proxyfs(), fs_mount_params::mount_type, fs_mounter::private_mount, immigrate_startup_params::sock, and tcmi_taskhelper_run_mig_mode_handler().
Referenced by tcmi_migcom_immigrate().
 {
     int err = -EINVAL;
     struct immigrate_startup_params* startup_params = (struct immigrate_startup_params*) data;
     struct completion *guest_ready = &startup_params->guest_ready;
     struct completion *fs_ready = &startup_params->fs_ready;
     struct fs_mounter* mounter;
     struct cred* new_cred;
     mdbg(INFO2, "New potential guest thread started. Pid: %d", current->pid);
     new_cred = prepare_creds();
     if ( !new_cred )
         return -ENOMEM;
     /* set process credentials */
     new_cred->uid = new_cred->euid = new_cred->suid = new_cred->fsuid =
     new_cred->gid = new_cred->egid = new_cred->sgid = new_cred->fsgid = 999;
     commit_creds(new_cred);
 //  current_uid() = current_euid() = current_suid() = current_fsuid() =
 //      current_gid() = current_egid() = current_sgid() =
 //      current_fsgid() = 999;
     /* This part simulates when the process didn't pickup
        the task on time
     set_current_state(TASK_INTERRUPTIBLE);
     schedule_timeout(5*HZ);
     minfo(INFO1, "Task has woken up %p", current);
     */
     // TODO: Close ALL fs.. are there some others? ;)
     sys_close(0);
     sys_close(1);
     sys_close(2);
     mdbg(INFO2, "Creating mounter: %s", startup_params->mount_params->mount_type);
     minfo(ERR1, "Creating mounter: %s", startup_params->mount_params->mount_type);
     mounter = get_new_mounter(startup_params->mount_params);
     mdbg(INFO2, "Created mounter: %p", mounter);
     minfo(ERR1, "Created mounter: %p", mounter);
     if ( mounter ) {
         /* Some file system mounter is registered => perform the mount */
         err = mounter->private_mount(mounter, startup_params->fsuid, startup_params->fsgid);
         if ( !err )
             mdbg(INFO2, "Private Mount succeeded");
         free_mounter(mounter);
         mdbg(INFO2, "Freed mounter");
         minfo(ERR1, "Freed mounter");
         if ( err ) {
             /* We must notify anyway to prevent blocking */
             complete(fs_ready);
             goto exit0;
         }
     }
     minfo(ERR1, "BEFORE mount_proxyfs");
     err = mount_proxyfs(startup_params->sock);
     if ( !err )
         err = mount_local_procfs(startup_params->sock);
     if ( err ) {
         // We must notify anyway to prevent blocking
         complete(fs_ready);
         goto exit0;
     }
     /* Notify about file system mount finished */
     complete(fs_ready);
     minfo(ERR1, "BEFORE Starting new thread for migrating task..");
     mdbg(INFO2, "Starting new thread for migrating task..");
     if ((err = wait_for_completion_interruptible(guest_ready))) {
         minfo(INFO1, "Received signal guest not ready");
         goto exit0;
     }
     mdbg(INFO3, "Guest task is ready by now..");
     /* migration mode handler picks up the task  */
     if (tcmi_taskhelper_run_mig_mode_handler() < 0) {
         mdbg(ERR3, "Failed to run migration mode handler");
         goto exit0;
     }
     return 0;
     /* error handling */
  exit0:
     return err;
 }
int tcmi_migcom_shadow_fork (struct task_struct * parent, struct task_struct * child, struct tcmi_migman * migman)
<<public>> Fork of shadow
Definition at line 573 of file tcmi_migcom.c.
References mdbg, minfo, tcmi_migcom_mig_mode_handler(), tcmi_migman_migproc_dir(), tcmi_migman_root(), tcmi_migman_sock(), tcmi_shadowtask_new(), tcmi_task_local_pid(), tcmi_task_process_msg(), tcmi_task_put(), tcmi_task_submit_method(), tcmi_taskhelper_attach_exclusive(), and tcmi_taskhelper_enter_mig_mode_exclusive().
{
     struct tcmi_task *shadow;
     mdbg(INFO3, "Forking shadow process => Making a new child shadow as well.");
     if (!(shadow =
           tcmi_shadowtask_new(child->pid, migman,
                   tcmi_migman_sock(migman),
                   tcmi_migman_migproc_dir(migman),
                   tcmi_migman_root(migman)))) {
         minfo(ERR3, "Error creating a shadow task for forked child");
         goto exit0;
     }
     // Submit process message so that the task is started in a main waiting loop
     // First expected message to get is either about successful start, or about start failure
     tcmi_task_submit_method(shadow, tcmi_task_process_msg, NULL, 0);
     /* attaches the shadow to its thread. */
     if (tcmi_taskhelper_attach_exclusive(child,shadow, tcmi_migcom_mig_mode_handler) < 0) {
         mdbg(ERR3, "Failed attaching shadow PID=%d to its thread",
              tcmi_task_local_pid(shadow));
         goto exit1;
     }
     /* release the the instance reference (Reference is now held by the associated task_struct - it got it in attach method)*/
     tcmi_task_put(shadow);
     /* switch the task to migration mode */
     tcmi_taskhelper_enter_mig_mode_exclusive(child, shadow);
     return 0;
 exit1:
     tcmi_task_put(shadow);
 exit0:
     return -EINVAL;
 }