Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/proxyfs/proxyfs_proxy_file.c File Reference
proxyfs_proxy_file.c File Reference
Main client file class (used by proxyfs_client_task)
#include <linux/types.h>
#include <linux/wait.h>
#include <asm/uaccess.h>
#include "proxyfs_proxy_file.h"
#include "proxyfs_peer.h"
#include "proxyfs_ioctl.h"
#include "virtual.h"
Macros
#define PROXYFS_PROXY_FILE_PRIVATE
#define PROXYFS_PROXY_FILE_PROTECTED
Functions
int proxyfs_proxy_file_write_user (struct proxyfs_proxy_file_t *self, const char *buf, size_t count)
<<public>> Write to file from user space buffer
static int virtual_proxyfs_proxy_file_read_user (struct proxyfs_proxy_file_t *self, char *buf, size_t count)
int proxyfs_proxy_file_read_user (struct proxyfs_proxy_file_t *self, char *buf, size_t count)
<<public>> Read from file to user space buffer
static int proxyfs_proxy_file_write_from_peer (struct proxyfs_file_t *self, const char *buf, size_t count)
<<private>> Writes to file from peer - writes to read buffer
static int proxyfs_proxy_file_read_to_peer (struct proxyfs_file_t *self, char *buf, size_t count)
<<private>> Reads from file to peer - reads from write buffer
static void proxyfs_proxy_file_submit_read_to_peer (struct proxyfs_file_t *self, size_t count)
<<private>> Submit that data was written to file on other side (can be safely deleted from proxyfs_file buffer)
unsigned proxyfs_proxy_file_wait_interruptible (struct proxyfs_proxy_file_t *self, unsigned status)
<<public>> Interruptible wait on file
unsigned proxyfs_proxy_file_wait_for_space_interruptible (struct proxyfs_proxy_file_t *self, unsigned space)
<<public>> Interruptible wait for space in file
long proxyfs_proxy_file_ioctl_user (struct proxyfs_proxy_file_t *self, unsigned int cmd, unsigned long arg)
<<public>> Do ioctl on remote file
int proxyfs_proxy_file_close (struct proxyfs_proxy_file_t *self)
<<public>> Close proxyfile
int proxyfs_proxy_file_fsync (struct proxyfs_proxy_file_t *self)
<<public>> Fsync proxyfile and coresponding real file
unsigned int proxyfs_file_poll (struct file *file, struct poll_table_struct *wait)
<<public>> Poll call for VFS
static void proxyfs_proxy_file_write_buf_info (struct proxyfs_file_t *self, size_t *total_size, size_t *size, void **addr)
<<private>> Get maximum amount and address of data, that can be read at one time
int proxyfs_proxy_file_init (struct proxyfs_proxy_file_t *self)
<<public>> Initialize proxyfs_file struct
void proxyfs_proxy_file_destroy (struct proxyfs_proxy_file_t *self)
<<public>> Deinitialize proxyfs_file struct
Detailed Description
Main client file class (used by proxyfs_client_task)
Date: 08/02/2007
Author: Petr Malat
Id:
proxyfs_proxy_file.c,v 1.7 2008/05/02 19:59:20 stavam2 Exp
This file is part of Proxy filesystem (ProxyFS) Copyleft (C) 2007 Petr Malat
ProxyFS is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
ProxyFS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file proxyfs_proxy_file.c.
Macro Definition Documentation
#define PROXYFS_PROXY_FILE_PRIVATE
Definition at line 34 of file proxyfs_proxy_file.c.
#define PROXYFS_PROXY_FILE_PROTECTED
Definition at line 35 of file proxyfs_proxy_file.c.
Function Documentation
static int proxyfs_proxy_file_read_to_peer (struct proxyfs_file_t * self, char * buf, size_t count) static
<<private>> Reads from file to peer - reads from write buffer
Parameters
*self - pointer to this file instance
*buf - pointer to buffer in kernelspace
count - size of data
: This is never used, is it correct? The functionality is done directly in task buffer sending..
Returns
the number of bytes read or error (negative number)
Definition at line 109 of file proxyfs_proxy_file.c.
References circ_buf_look_at(), PROXYFS_PROXY_FILE, and self.
 {
     int lenght;
     down( & PROXYFS_PROXY_FILE(self)->write_buf_sem );
     lenght = circ_buf_look_at( & self->write_buf, buf, count, self->write_buf_unconfirmed);
     if( lenght > 0 )
         self->write_buf_unconfirmed += lenght;
     up( & PROXYFS_PROXY_FILE(self)->write_buf_sem );
     return lenght;
 }
static void proxyfs_proxy_file_submit_read_to_peer (struct proxyfs_file_t * self, size_t count) static
<<private>> Submit that data was written to file on other side (can be safely deleted from proxyfs_file buffer)
Parameters
*self - pointer to this file instance
count - amount of submited data
Definition at line 128 of file proxyfs_proxy_file.c.
References circ_buf_adjust_read_ptr(), count(), mdbg, PROXYFS_PROXY_FILE, and self.
 {
     down( & PROXYFS_PROXY_FILE(self)->write_buf_sem );
     circ_buf_adjust_read_ptr( & self->write_buf, count);
     self->write_buf_unconfirmed -= count;
     up( & PROXYFS_PROXY_FILE(self)->write_buf_sem );
     mdbg(INFO3, "Waking up file after peer read (%lu). Unconfirmed size : %lu", (unsigned long)count, (unsigned long) self->write_buf_unconfirmed);
     wake_up( & PROXYFS_PROXY_FILE(self)->waiting_procs );
 }
static void proxyfs_proxy_file_write_buf_info (struct proxyfs_file_t * self, size_t * total_size, size_t * size, void ** addr) static
<<private>> Get maximum amount and address of data, that can be read at one time
Parameters
*self - pointer to this file instance
*total_size - pointer to size_t into which a total available data count will be written
*size - pointer to size_t into which the data size will be written
**addr - pointer to void* into which the data address will be written
Definition at line 367 of file proxyfs_proxy_file.c.
References circ_buf_count(), circ_buf_get_read_addr(), circ_buf_get_read_size(), PROXYFS_PROXY_FILE, and self.
 {
     down( & PROXYFS_PROXY_FILE(self)->write_buf_sem );
     *total_size = circ_buf_count( & self->write_buf );
     *size = circ_buf_get_read_size( & self->write_buf );
     *addr = circ_buf_get_read_addr( & self->write_buf );
     up( & PROXYFS_PROXY_FILE(self)->write_buf_sem );
 }
static int proxyfs_proxy_file_write_from_peer (struct proxyfs_file_t * self, const char * buf, size_t count) static
<<private>> Writes to file from peer - writes to read buffer
Parameters
*self - pointer to this file instance
*buf - pointer to data in kernelspace
count - size of data
Returns
the number of bytes written
Definition at line 84 of file proxyfs_proxy_file.c.
References circ_buf_write(), mdbg, proxyfs_file_get_file_ident(), PROXYFS_FILE_READ_EOF, proxyfs_file_set_status(), PROXYFS_PROXY_FILE, and self.
 {
     int lenght = 0;
     down( & PROXYFS_PROXY_FILE(self)->read_buf_sem );
     if( count == 0 ){
         proxyfs_file_set_status( self, PROXYFS_FILE_READ_EOF );
         mdbg(INFO2, "EOF on file %lu", proxyfs_file_get_file_ident(self));
     }
     else
         lenght = circ_buf_write( & self->read_buf, buf, count );
     up( & PROXYFS_PROXY_FILE(self)->read_buf_sem );
     mdbg(INFO4, "Waking up sleepers on %lu", proxyfs_file_get_file_ident(self));
     wake_up( &PROXYFS_PROXY_FILE(self)->waiting_procs );
     return lenght;
 }
static int virtual_proxyfs_proxy_file_read_user (struct proxyfs_proxy_file_t * self, char * buf, size_t count) inline static
Definition at line 54 of file proxyfs_proxy_file.c.
References VIRTUAL_FUNC.
Referenced by proxyfs_proxy_file_read_user().
{
     VIRTUAL_FUNC(read_user, buf, count);
 }