Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/ccfs/super.c File Reference
super.c File Reference
#include <linux/fs.h>
#include <linux/mount.h>
#include <linux/key.h>
#include <linux/seq_file.h>
#include <linux/file.h>
#include <linux/crypto.h>
#include "ccfs.h"
#include <dbg.h>
Functions
static struct inode * ccfs_alloc_inode (struct super_block *sb)
static void ccfs_destroy_inode (struct inode *inode)
void ccfs_init_inode (struct inode *inode, struct inode *lower_inode)
static void ccfs_put_super (struct super_block *sb)
static int ccfs_statfs (struct dentry *dentry, struct kstatfs *buf)
static void ccfs_clear_inode (struct inode *inode)
static void ccfs_drop_inode (struct inode *inode)
static int ccfs_show_options (struct seq_file *m, struct vfsmount *mnt)
Variables
struct kmem_cache * ccfs_inode_cache
struct super_operations ccfs_sops
Function Documentation
static struct inode* ccfs_alloc_inode (struct super_block * sb) static read
Definition at line 13 of file super.c.
References ccfs_inode_cache, ccfs_inode::link, ccfs_inode::lower_file, ccfs_inode::lower_file_mutex, mdbg, ccfs_inode::stat, and ccfs_inode::vfs_inode.
 {
     struct ccfs_inode *c_inode;
     struct inode *inode = NULL;
     c_inode = kmem_cache_alloc(ccfs_inode_cache, GFP_KERNEL);
     mdbg(INFO3,  "Allocated inode: %p", c_inode);
     if (unlikely(!c_inode))
         goto out;
     mutex_init(&c_inode->lower_file_mutex);
     c_inode->lower_file = NULL;
     inode = &c_inode->vfs_inode;
     c_inode->link = NULL;
     c_inode->stat = NULL;
 out:
     return inode;
 }
static void ccfs_clear_inode (struct inode * inode) static
Definition at line 86 of file super.c.
References ccfs_get_nested_inode(), and mdbg.
 {
     mdbg(INFO3, "Clearing inode: %p", inode);
     iput(ccfs_get_nested_inode(inode));
 }
static void ccfs_destroy_inode (struct inode * inode) static
Definition at line 32 of file super.c.
References ccfs_inode_cache, ccfs_inode_to_private(), ccfs_inode::link, ccfs_inode::lower_file, ccfs_inode::lower_file_mutex, mdbg, and ccfs_inode::stat.
 {
     struct ccfs_inode *c_inode;
     c_inode = ccfs_inode_to_private(inode);
     mdbg(INFO3,  "Destroying inode: %p Lower file: %p", c_inode, c_inode->lower_file);
     mutex_lock(&c_inode->lower_file_mutex);
     if (c_inode->lower_file) {
         struct dentry *lower_dentry =
             c_inode->lower_file->f_dentry;
         BUG_ON(!lower_dentry);
         mdbg(INFO3,  "Destroying nested dentry: %s", lower_dentry->d_iname);
         if (lower_dentry->d_inode) {
             mdbg(INFO3,  "Puting lower file: %p (%ld)", c_inode->lower_file, atomic_long_read(&c_inode->lower_file->f_count));
             fput(c_inode->lower_file);
             c_inode->lower_file = NULL;
             //d_drop(lower_dentry); This is likely not neccesary, but worse it is a race as the lower dentry is not held at this time
         }
         kfree(c_inode->link);
         kfree(c_inode->stat);
     }
     mutex_unlock(&c_inode->lower_file_mutex);
     kmem_cache_free(ccfs_inode_cache, c_inode);
     mdbg(INFO3, "Destroy done");
 }
static void ccfs_drop_inode (struct inode * inode) static
Definition at line 92 of file super.c.
References ccfs_is_inode_cacheable(), and mdbg.
 {
     if ( !ccfs_is_inode_cacheable(inode) ) {
         mdbg(INFO3, "Dropping non-cacheable inode: %p", inode);
         generic_delete_inode(inode);
     } else {
         generic_drop_inode(inode);
     }
 }
void ccfs_init_inode (struct inode * inode, struct inode * lower_inode)
Definition at line 60 of file super.c.
References ccfs_inode::cacheable, ccfs_aops, ccfs_inode_to_private(), ccfs_main_fops, ccfs_main_iops, ccfs_set_nested_inode(), and mdbg.
Referenced by ccfs_inode_set().
 {
     mdbg(INFO3, "Initializing inode: %p with lower inode: %p", inode, lower_inode);
     ccfs_set_nested_inode(inode, lower_inode);
     inode->i_ino = lower_inode->i_ino;
     inode->i_version++;
     inode->i_op = &ccfs_main_iops;
     inode->i_fop = &ccfs_main_fops;
     inode->i_mapping->a_ops = &ccfs_aops;
     ccfs_inode_to_private(inode)->cacheable = 1;
 }
static void ccfs_put_super (struct super_block * sb) static
Definition at line 72 of file super.c.
References ccfs_super::cacheable_filter, ccfs_sb_cache, ccfs_set_superblock_private(), ccfs_superblock_to_private(), and destroy_filter().
 {
     struct ccfs_super *sb_info = ccfs_superblock_to_private(sb);
     destroy_filter(sb_info->cacheable_filter);
     kmem_cache_free(ccfs_sb_cache, sb_info);
     ccfs_set_superblock_private(sb, NULL);
 }
static int ccfs_show_options (struct seq_file * m, struct vfsmount * mnt) static
Definition at line 103 of file super.c.
References ccfs_dentry_to_nested_mnt(), and ccfs_get_nested_dentry().
 {
     struct super_block *sb = mnt->mnt_sb;
     struct dentry *lower_root_dentry = ccfs_get_nested_dentry(sb->s_root);
     struct vfsmount *lower_mnt = ccfs_dentry_to_nested_mnt(sb->s_root);
     struct path tmp_path;
     char *tmp_page;
     char *path;
     int rc = 0;
     tmp_path.dentry = lower_root_dentry;
     tmp_path.mnt = lower_mnt;
     tmp_page = (char *)__get_free_page(GFP_KERNEL);
     if (!tmp_page) {
         rc = -ENOMEM;
         goto out;
     }
     path = d_path(&tmp_path, tmp_page, PAGE_SIZE);
     if (IS_ERR(path)) {
         rc = PTR_ERR(path);
         goto out;
     }
     seq_printf(m, ",dir=%s", path);
     free_page((unsigned long)tmp_page);
 out:
     return rc;
 }
static int ccfs_statfs (struct dentry * dentry, struct kstatfs * buf) static
Definition at line 81 of file super.c.
References ccfs_get_nested_dentry().
 {
     return vfs_statfs(ccfs_get_nested_dentry(dentry), buf);
 }
Variable Documentation
struct kmem_cache* ccfs_inode_cache
Definition at line 11 of file super.c.
Referenced by ccfs_alloc_inode(), and ccfs_destroy_inode().
struct super_operations ccfs_sops
Initial value:
= {
    .alloc_inode = ccfs_alloc_inode,
    .destroy_inode = ccfs_destroy_inode,
    .drop_inode = ccfs_drop_inode,
    .put_super = ccfs_put_super,
    .statfs = ccfs_statfs,
    .remount_fs = NULL,
    .clear_inode = ccfs_clear_inode,
    .show_options = ccfs_show_options
}
Definition at line 132 of file super.c.
Referenced by ccfs_fill_super().