Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ctlfs/tcmi_ctlfs_entry.h File Reference
tcmi_ctlfs_entry.h File Reference
#include <linux/dcache.h>
#include <linux/types.h>
#include <linux/fs.h>
#include <dbg.h>
Data Structures
struct tcmi_ctlfs_entry
An entry compound structure.
struct tcmi_ctlfs_ops
entry operations that support polymorphism
Macros
#define MAX_ENTRY_NAME_LEN 256
Maximum entry name length.
#define TCMI_CTLFS_DENTRY_TO_ENTRY(dentry) TCMI_CTLFS_ENTRY(dentry->d_fsdata)
Extracts the entry object from the dentry.
#define TCMI_CTLFS_ENTRY(e) ((struct tcmi_ctlfs_entry *)e)
Casts a child entry to the super class.
Typedefs
typedef void callback (struct tcmi_ctlfs_entry *, void *)
Callback method of an object when traversing through predecessors.
Functions
int tcmi_ctlfs_entry_init (struct tcmi_ctlfs_entry *self, struct tcmi_ctlfs_entry *parent, mode_t mode, struct tcmi_ctlfs_ops *entry_ops, const struct inode_operations *i_ops, const struct file_operations *f_ops, const char namefmt[], va_list args)
<<public>> Initializes an instance.
int tcmi_ctlfs_rootentry_init (struct tcmi_ctlfs_entry *self, struct super_block *sb, mode_t mode, struct tcmi_ctlfs_ops *entry_ops, const struct inode_operations *i_ops, const struct file_operations *f_ops)
<<public>> Initializes a root entry instance.
void tcmi_ctlfs_entry_traverse_pred (struct tcmi_ctlfs_entry *self, callback *func, void *data)
<<public>> Iterator through entry predecessors.
int tcmi_ctlfs_entry_depth (struct tcmi_ctlfs_entry *entry)
<<public>> Calculates the current depth of the entry in the tree.
int tcmi_ctlfs_entry_path_length (struct tcmi_ctlfs_entry *self)
<<public>> Calculates the length of the pathname string.
void tcmi_ctlfs_entry_fill_path (struct tcmi_ctlfs_entry *self, char *buffer, int length)
<<public>> Fills in the entry's pathname.
static void tcmi_ctlfs_entry_inc_links (struct tcmi_ctlfs_entry *self)
<<public>> Increments the number of links referencing this entry's inode.
static const char * tcmi_ctlfs_entry_name (struct tcmi_ctlfs_entry *self)
<<public>> Entry name accessor.
static int tcmi_ctlfs_entry_isroot (struct tcmi_ctlfs_entry *self)
<<public>> Checks whether a given entry is the root of the TCMI ctlfs tree.
static struct tcmi_ctlfs_entry * tcmi_ctlfs_entry_get (struct tcmi_ctlfs_entry *self)
<<public>> Instance accessor, Calls instance custom get method and increments the reference counter.
static struct tcmi_ctlfs_entry * tcmi_ctlfs_entry_get_parent (struct tcmi_ctlfs_entry *self)
<<public>> Returns parent entry, reference counter is incremented.
static void tcmi_ctlfs_entry_put (struct tcmi_ctlfs_entry *self)
<<public>> Calls the instance custom put method(if any) and Decrements the reference counter of the dentry that the instance uses to carry it through out the file system.
Function Documentation
static struct tcmi_ctlfs_entry* tcmi_ctlfs_entry_get (struct tcmi_ctlfs_entry * self) static read
<<public>> Instance accessor, Calls instance custom get method and increments the reference counter.
The user is now guaranteed, that the instance stays in memory while he is using it.
Parameters
*self - pointer to this instance
Returns
tcmi_ctlfs_entry instance
Definition at line 178 of file tcmi_ctlfs_entry.h.
References mdbg, self, and tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_entry_get_parent().
 {
     if (self) {
         mdbg(INFO4, "Incrementing ref. count of '%s'(%p)",
              tcmi_ctlfs_entry_name(self), self);
         dget(self->dentry);
     }
     return self;
 }
static struct tcmi_ctlfs_entry* tcmi_ctlfs_entry_get_parent (struct tcmi_ctlfs_entry * self) static read
<<public>> Returns parent entry, reference counter is incremented.
Parameters
*self - pointer to this instance
Returns
- parent entry.
Definition at line 195 of file tcmi_ctlfs_entry.h.
References self, TCMI_CTLFS_DENTRY_TO_ENTRY, and tcmi_ctlfs_entry_get().
 {
     return tcmi_ctlfs_entry_get(TCMI_CTLFS_DENTRY_TO_ENTRY(self->dentry->d_parent));
 }
static void tcmi_ctlfs_entry_inc_links (struct tcmi_ctlfs_entry * self) inline static
<<public>> Increments the number of links referencing this entry's inode.
This method is used by directory entries. When a new child entry is added to the directory, the number of links in the inode->i_nlink needs to be adjusted as well as its parent's inode->i_nlink also needs to be incremented
Parameters
*self - pointer to this instance
Definition at line 138 of file tcmi_ctlfs_entry.h.
References self.
 {
     inc_nlink(self->dentry->d_inode); //Changed direct increment to inc_nlink function which it does atomic. | by Jiri Rakosnik
 }
static int tcmi_ctlfs_entry_isroot (struct tcmi_ctlfs_entry * self) inline static
<<public>> Checks whether a given entry is the root of the TCMI ctlfs tree.
This is when the d_parent of the dentry of this tcmi_ctlfs_entry points back to the dentry
Parameters
*self - pointer to this instance
Returns
- 1 if it is root
Definition at line 163 of file tcmi_ctlfs_entry.h.
 {
     struct dentry *dentry = self->dentry;
     return (dentry == dentry->d_parent);
 }
static const char* tcmi_ctlfs_entry_name (struct tcmi_ctlfs_entry * self) inline static
<<public>> Entry name accessor.
Parameters
*self - pointer to this instance
Returns
- entry name
Definition at line 149 of file tcmi_ctlfs_entry.h.
Referenced by tcmi_ctlfs_entry_get(), and tcmi_ctlfs_entry_put().
 {
     return self->dentry->d_name.name;
 }
static void tcmi_ctlfs_entry_put (struct tcmi_ctlfs_entry * self) inline static
<<public>> Calls the instance custom put method(if any) and Decrements the reference counter of the dentry that the instance uses to carry it through out the file system.
If the reference count reaches 0, the dentry will be released from the dentry cache and the instance of tcmi_ctlfs_entry will be freed. (VFS calls the d_delete() method of the dentry that we have customized
See Also
tcmi_ctlfs_dentry_delete and d_release() that is also customized in tcmi_ctlfs_dentry_release())
Parameters
*self - pointer to this instance
Definition at line 212 of file tcmi_ctlfs_entry.h.
References mdbg, self, and tcmi_ctlfs_entry_name().
 {
     if (self) {
         mdbg(INFO4, "Decrementing ref. count of '%s'(%p) (dentry: %p). Count before dec: %d",
              tcmi_ctlfs_entry_name(self), self, self->dentry, self->dentry->d_count); //Removed function atomic_read for bad usage | by Jiri Rakosnik
         dput(self->dentry);
     }
 }