Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/manager/tcmi_penman.c File Reference
tcmi_penman.c File Reference
Implementation of TCMI cluster process execution manager - a class that controls the process execution node
#include <linux/kthread.h>
#include <tcmi/migration/tcmi_migcom.h>
#include <tcmi/ctlfs/tcmi_ctlfs.h>
#include "tcmi_penmigman.h"
#include <tcmi/task/tcmi_task.h>
#include <tcmi/task/tcmi_taskhelper.h>
#include <tcmi/migration/tcmi_npm_params.h>
#include <kkc/kkc.h>
#include "tcmi_penman.h"
#include <dbg.h>
Macros
#define TCMI_PENMAN_PRIVATE
Functions
int tcmi_penman_init (struct tcmi_ctlfs_entry *root)
<<public>> Singleton instance initializer.
void tcmi_penman_shutdown (void)
<<public>> The manager is shutdown exactly in this order:
static int tcmi_penman_init_ctlfs_files (void)
<<private>> Creates the static files described here .
static void tcmi_penman_stop_ctlfs_files (void)
<<private>> Unregisters all control files.
static int check_duplicates (const char *address, int address_len)
static int tcmi_penman_connect (void *obj, void *str)
<<private>> Creates a new connection and instantiates a new migration manager that will be responsible for handling it.
static void tcmi_penman_stop (void)
<<private>> Stops the PEN manager.
int tcmi_penman_migrateback_npm (struct tcmi_man *self, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
Performs non-preemtive migration back from PEN.
Variables
static struct tcmi_penman self
Singleton instance pre-initialization.
static struct tcmi_man_ops penman_ops
Migration manager operations that support polymorphism.
Detailed Description
Implementation of TCMI cluster process execution manager - a class that controls the process execution node
Date: 04/17/2005
Author: Jan Capek
Id:
tcmi_penman.c,v 1.5 2009-04-06 21:48:46 stavam2 Exp
This file is part of Task Checkpointing and Migration Infrastructure(TCMI) Copyleft (C) 2005 Jan Capek
TCMI is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
TCMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file tcmi_penman.c.
Macro Definition Documentation
#define TCMI_PENMAN_PRIVATE
Definition at line 45 of file tcmi_penman.c.
Function Documentation
int tcmi_penman_init (struct tcmi_ctlfs_entry * root)
<<public>> Singleton instance initializer.
The initialization is accomplished exactly in this order:
delegate rest of initialization to TCMI generic manager
Parameters
*root - root directory of the filesystem, where all entries are to be created
Returns
0 upon success
Definition at line 59 of file tcmi_penman.c.
References mdbg, minfo, penman_ops, TCMI_MAN, and tcmi_man_init().
Referenced by tcmi_module_init().
 {
     minfo(INFO1, "Initializing TCMI PEN manager");
     if (tcmi_man_init(TCMI_MAN(&self), root, &penman_ops, "pen") < 0) {
         mdbg(ERR3, "TCMI PEN manager - generic init failed");
         goto exit0;
     }
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
void tcmi_penman_shutdown (void)
<<public>> The manager is shutdown exactly in this order:
unregister all ctlfs files as we don't want anymore requests from users.
shutdown the migration framework. This includes migrating all processes back and terminating all migration managers
unregister all ctlfs directories
Definition at line 83 of file tcmi_penman.c.
References minfo, TCMI_MAN, and tcmi_man_shutdown().
Referenced by tcmi_module_exit(), and tcmi_module_init().
 {
     minfo(INFO1, "Shutting down the TCMI PEN manager");
     tcmi_man_shutdown(TCMI_MAN(&self));
 }