Clondike: tcmi_msg class
tcmi_msg class
communication
This class represents a generic message in TCMI communication protocol.
Modules
tcmi_authenticate_msg class
This message is send by PEN when it wants authenticate to CCN.
tcmi_authenticate_resp_msg class
This message is send as a response to authentication request by the CCN to PEN.
tcmi_disconnect_msg class
This message is send by PEN or CCN when it is going to disconnect from its peer.
tcmi_err_msg class
This class represents a generic error message.
tcmi_generic_user_msg class
This message can be send both by PEN or CCN.
tcmi_p_emigrate_msg class
This class represents a message for preemptive/non-preemtive process migration via a physical checkpoint image.
tcmi_ppm_p_emigrate_msg class
This class represents a message for preemptive process migration via a physical checkpoint image.
tcmi_procmsg class
This class represents a generic process message.
tcmi_signal_msg class
This class represents a test message and is intended to be used as a skeleton when implementing new messages in the TCMI protocol.
tcmi_skel_msg class
This class represents a test message and is intended to be used as a skeleton when implementing new messages in the TCMI protocol.
tcmi_skelresp_msg class
This class represents a test message and is intended to be used as a skeleton when implementing new messages in the TCMI protocol.
Data Structures
struct tcmi_msg
A coumpound structure that carries a generic TCMI message.
struct tcmi_msg_ops
Message operations that support polymorphism.
struct tcmi_msg_dsc
This descriptor is to be provided by every individual message class for the factory .
Macros
#define TCMI_MSG_DSC(id, new_rx_m, new_rx_err_m) {.msg_id = id, .new_rx = new_rx_m, .new_rx_err = new_rx_err_m}
Macro that fills the descriptor.
#define TCMI_DEFAULT_MSG_TIMEOUT 60*HZ
Message transaction default timeout set to 60 seconds.
#define TCMI_MSG(m) ((struct tcmi_msg*)m)
Casts to the tcmi_msg instance.
Functions
static int tcmi_msg_send (struct tcmi_msg *self, struct kkc_sock *sock, int flags)
<<private>> Sends a message via a specified connection.
int tcmi_msg_init_rx (struct tcmi_msg *self, u_int32_t msg_id, struct tcmi_msg_ops *msg_ops)
<<public>> Initializes the message for receiving.
int tcmi_msg_init_tx (struct tcmi_msg *self, u_int32_t msg_id, struct tcmi_msg_ops *msg_ops, struct tcmi_slotvec *transactions, u_int32_t resp_msg_id, u_int timeout, u_int32_t resp_trans_id)
<<public>> Initializes the message for transferring.
int tcmi_msg_recv (struct tcmi_msg *, struct kkc_sock *sock)
<<public>> Receives the message via a specified connection.
int tcmi_msg_send_anonymous (struct tcmi_msg *self, struct kkc_sock *sock)
<<public>> Sends a message via a specified connection.
int tcmi_msg_send_and_receive (struct tcmi_msg *self, struct kkc_sock *sock, struct tcmi_msg **resp)
<<public>> Sends a message via a specified connection and waits for the response.
int tcmi_msg_deliver (struct tcmi_msg *self, struct tcmi_queue *requests, struct tcmi_slotvec *transactions)
<<public>> Message delivers itself.
struct tcmi_msg * tcmi_msg_new_rx (u_int32_t msg_id, struct tcmi_msg_dsc *dsc)
<<public>> Class method - creates a message based on a descriptor.
static struct tcmi_msg * tcmi_msg_get (struct tcmi_msg *self)
<<public>> Instance accessor, increments the reference count.
static void tcmi_msg_put (struct tcmi_msg *self)
<<public>> Decrements reference counter, if it reaches 0 the custom free method is called if defined.
static u_int32_t tcmi_msg_id (struct tcmi_msg *self)
<<public>> Message ID accessor.
static u_int32_t tcmi_msg_errid (struct tcmi_msg *self)
<<public>> Message error ID accessor.
static u_int32_t tcmi_msg_req_id (struct tcmi_msg *self)
<<public>> Request transaction ID accessor.
Detailed Description
This class represents a generic message in TCMI communication protocol.
A message can be part of a transaction. For that reason it carries two extra ID's
a transaction request ID - identifies a transaction started by the sending party. The sending party expects a message with response transaction ID set to this value. This ID is assigned automatically upon message creation depending on a particular messagere type.
a transaction response ID - this value comes from the transaction request ID of the original request message that the new message is replying to. This ID has to be specified explicitely when building the response message.
A message is instantiated always twice during its lifetime:
the sender builds the message based on parameters specified by the message instantiator.
the receiver performs message materialization from the data stream.
These two cases are substantially different. In the first case the instantiator knows what message is to be built. While the receiver is left to the very last moment upon discovery of the message ID to build the message. A suitable solution to this problem is provided by a a <<factory>> design pattern. The message instantiation on the receiver side is carried out by message factory .
A generic message consists of following parts:
message id - unique identifier that describes a particular message type. This is specified by particular subclasses.
transaction request ID - explained above
transaction response ID - explained above
Generic message methods:
init_rx - initializes a new message so that it is ready to be received.
init_tx - initializes a new message for sending based on parameters specified by the user.
recv - receives a message via a communication channel
send - sends out a message via a communication channel
deliver - delivers a request message to a queue or delivers a response message to a transaction and completes the transaction.
A particular message of the protocol then provides following interface:
new_rx - this method is registered with the factory class, so that the build process is fully automated.
new_rx_err - also registered with the factory class, provides an alternate(error) version of the message.
new_tx - builds a message based on parameters specified by the user
Data Structure Documentation
struct tcmi_msg
A coumpound structure that carries a generic TCMI message.
Definition at line 103 of file tcmi_msg.h.
Public Member Functions
struct {
u_int32_t req
request transaction ID
u_int32_t resp
response transaction ID
} __attribute__ ((__packed__))
Data Fields
u_int32_t msg_id
message id
struct tcmi_transaction * transaction
transaction associated with the message
struct tcmi_msg_ops * msg_ops
message operations
atomic_t ref_count
reference counter
struct list_head node
list entry for the message queue
Member Function Documentation
struct tcmi_msg::@6 tcmi_msg::__attribute__ ((__packed__))
Field Documentation
u_int32_t tcmi_msg::msg_id
message id
Definition at line 105 of file tcmi_msg.h.
Referenced by tcmi_comm_thread().
struct tcmi_msg_ops* tcmi_msg::msg_ops
message operations
Definition at line 117 of file tcmi_msg.h.
struct list_head tcmi_msg::node
list entry for the message queue
Definition at line 122 of file tcmi_msg.h.
atomic_t tcmi_msg::ref_count
reference counter
Definition at line 120 of file tcmi_msg.h.
struct tcmi_transaction* tcmi_msg::transaction
transaction associated with the message
Definition at line 114 of file tcmi_msg.h.
struct tcmi_msg_ops
Message operations that support polymorphism.
Definition at line 127 of file tcmi_msg.h.
Data Fields
int(* recv)(struct tcmi_msg *, struct kkc_sock *)
Receives the message via a specified connection.
int(* send)(struct tcmi_msg *, struct kkc_sock *)
Sends the message via a specified connection.
void(* free)(struct tcmi_msg *)
Frees custom message resources.
Field Documentation
void(* tcmi_msg_ops::free)(struct tcmi_msg *)
Frees custom message resources.
The destruction of the actual message instance is handled internally by this class
Definition at line 135 of file tcmi_msg.h.
int(* tcmi_msg_ops::recv)(struct tcmi_msg *, struct kkc_sock *)
Receives the message via a specified connection.
Definition at line 129 of file tcmi_msg.h.
Referenced by tcmi_msg_recv().
int(* tcmi_msg_ops::send)(struct tcmi_msg *, struct kkc_sock *)
Sends the message via a specified connection.
Definition at line 131 of file tcmi_msg.h.
Referenced by tcmi_msg_send().
struct tcmi_msg_dsc
This descriptor is to be provided by every individual message class for the factory .
Definition at line 140 of file tcmi_msg.h.
Data Fields
u_int32_t msg_id
message id
struct tcmi_msg *(* new_rx)(u_int32_t msg_id)
Builds the regular version of the message.
struct tcmi_msg *(* new_rx_err)(u_int32_t msg_id)
Builds the error version of the message.
Field Documentation
u_int32_t tcmi_msg_dsc::msg_id
message id
Definition at line 142 of file tcmi_msg.h.
Referenced by tcmi_msg_new_rx().
struct tcmi_msg*(* tcmi_msg_dsc::new_rx)(u_int32_t msg_id) read
Builds the regular version of the message.
Definition at line 144 of file tcmi_msg.h.
Referenced by tcmi_msg_new_rx().
struct tcmi_msg*(* tcmi_msg_dsc::new_rx_err)(u_int32_t msg_id) read
Builds the error version of the message.
Definition at line 146 of file tcmi_msg.h.
Referenced by tcmi_msg_new_rx().
Macro Definition Documentation
#define TCMI_DEFAULT_MSG_TIMEOUT 60*HZ
Message transaction default timeout set to 60 seconds.
Definition at line 156 of file tcmi_msg.h.
Referenced by tcmi_authenticate_msg_new_tx().
#define TCMI_MSG (m) ((struct tcmi_msg*)m)
Casts to the tcmi_msg instance.
Definition at line 159 of file tcmi_msg.h.
Referenced by tcmi_authenticate_msg_new_rx(), tcmi_authenticate_msg_new_tx(), tcmi_authenticate_resp_msg_new_rx(), tcmi_authenticate_resp_msg_new_tx(), tcmi_disconnect_msg_new_rx(), tcmi_disconnect_msg_new_tx(), tcmi_err_msg_new_rx(), tcmi_err_msg_new_tx(), tcmi_err_procmsg_new_rx(), tcmi_err_procmsg_new_tx(), tcmi_exit_procmsg_new_rx(), tcmi_exit_procmsg_new_tx(), tcmi_generic_user_msg_new_rx(), tcmi_generic_user_msg_new_tx(), tcmi_generic_user_procmsg_new_rx(), tcmi_generic_user_procmsg_new_tx(), tcmi_guest_started_procmsg_new_rx(), tcmi_guest_started_procmsg_new_tx(), tcmi_man_do_send_generic_user_message(), tcmi_migman_notify_peer_disconnect(), tcmi_msg_send_and_receive(), tcmi_p_emigrate_msg_new_rx(), tcmi_p_emigrate_msg_new_tx(), tcmi_ppm_p_emigrate_msg_new_rx(), tcmi_ppm_p_emigrate_msg_new_tx(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx(), tcmi_procmsg_init_rx(), tcmi_procmsg_init_tx(), tcmi_rpc_procmsg_new_rx(), tcmi_rpc_procmsg_new_tx(), tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_new_rx(), tcmi_rpcresp_procmsg_new_tx(), tcmi_signal_msg_new_rx(), tcmi_signal_msg_new_tx(), tcmi_skel_msg_new_rx(), tcmi_skel_msg_new_tx(), tcmi_skel_procmsg_new_rx(), tcmi_skel_procmsg_new_tx(), tcmi_skelresp_msg_new_rx(), tcmi_skelresp_msg_new_tx(), tcmi_skelresp_procmsg_new_rx(), tcmi_skelresp_procmsg_new_tx(), tcmi_vfork_done_procmsg_new_rx(), and tcmi_vfork_done_procmsg_new_tx().
#define TCMI_MSG_DSC (id, new_rx_m, new_rx_err_m) {.msg_id = id, .new_rx = new_rx_m, .new_rx_err = new_rx_err_m}
Macro that fills the descriptor.
Definition at line 150 of file tcmi_msg.h.
Function Documentation
int tcmi_msg_deliver (struct tcmi_msg * self, struct tcmi_queue * requests, struct tcmi_slotvec * transactions)
<<public>> Message delivers itself.
<<public>> Message delivers itself.
A delivery of a message depends on the message type. If it is the request part of the message or a one-way message, then the receiving party/thread wants to have it in the associated message queue. If it is a response to a previously sent message and the receiving party/thread expects it, it will get associated with its transaction.
a message is of request type if it has a request transaction ID. In that case, it will be appended to the regular request queue and the queue processing thread will pick it up.
a message is of response type - has a response transaction ID. In that case, it will find its transaction. On success, it will associate itself with the transaction and complete it. Completing the transaction is handled by the transaction class internally.
in addition, if the transaction is marked anonymous (nobody is synchronously waiting for the response), the message will also be delivered into the regular message queue.
Parameters
*self - pointer to this message instance
*requests - queue where the message is stored if it is not a response to other message.
*transactions - contains all active transactions, the message tries to find its matching transaction.
Returns
0 upon success
Definition at line 297 of file tcmi_msg.c.
References mdbg, self, TCMI_MSG_TYPE, tcmi_queue_add(), tcmi_transaction_complete(), tcmi_transaction_id(), TCMI_TRANSACTION_INVAL_ID, tcmi_transaction_is_anon(), and tcmi_transaction_lookup().
Referenced by tcmi_migman_deliver_msg(), and tcmi_task_deliver_msg().
 {
     int error = 0;
     /* storage for the potential transaction associated with the message */
     struct tcmi_transaction *tran;
     /* request message handling */
     if (self->trans_id.resp == TCMI_TRANSACTION_INVAL_ID) {
         mdbg(INFO3, "Adding message(ID=%x req=%x resp=%x) to the request queue",
              self->msg_id, self->trans_id.req, self->trans_id.resp);
         tcmi_queue_add(requests, &self->node);
     }
     /* response message handling */
     else {
         /* search for the transaction */
         if (!(tran = tcmi_transaction_lookup(transactions, self->trans_id.resp))) {
             mdbg(ERR3, "Message(ID=%x req=%x resp=%x) - "
                  "can't find response transaction ID among transactions",
                  self->msg_id, self->trans_id.req, self->trans_id.resp);
             error = -1;
             goto exit0;
         }
         /* store the transaction in the message, reference
          * counter has been increased by the successful
          * lookup */
         self->transaction = tran;
         /* try completing it - only message type from the
         * message ID is taken, to verify that the message
         * being delivered matches the message expected by the
         * transaction */
         if (tcmi_transaction_complete(tran, self, TCMI_MSG_TYPE(self->msg_id))) {
             mdbg(ERR3, "Error completing transaction %x",
                  tcmi_transaction_id(tran));
             error = -EINVAL;
             goto exit0;
         }
         if (tcmi_transaction_is_anon(tran)) {
             mdbg(INFO3, "Detected anonymous transaction, queueing the message too..");
             tcmi_queue_add(requests, &self->node);
         }
         mdbg(INFO3, "Message (ID=%x req=%x resp=%x) delivered, transaction completed",
              self->msg_id, self->trans_id.req, self->trans_id.resp);
     }
     /* error handling */
  exit0:
     return error;
 }
static u_int32_t tcmi_msg_errid (struct tcmi_msg * self) inline static
<<public>> Message error ID accessor.
Parameters
*self - pointer to this message instance
Returns
message ID extended with error flags
Definition at line 242 of file tcmi_msg.h.
References self, and TCMI_MSG_FLG_SET_ERR.
 {
     return TCMI_MSG_FLG_SET_ERR(self->msg_id);
 }
static struct tcmi_msg* tcmi_msg_get (struct tcmi_msg * self) static read
<<public>> Instance accessor, increments the reference count.
Parameters
*self - pointer to this message instance
Definition at line 194 of file tcmi_msg.h.
References self.
Referenced by tcmi_migcom_immigrate(), tcmi_shadowtask_process_msg(), and tcmi_task_send_message().
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static u_int32_t tcmi_msg_id (struct tcmi_msg * self) inline static
<<public>> Message ID accessor.
Parameters
*self - pointer to this message instance
Returns
message ID
Definition at line 231 of file tcmi_msg.h.
Referenced by tcmi_ccnmigman_process_msg(), tcmi_guesttask_process_msg(), tcmi_migman_deliver_msg(), tcmi_migman_msg_thread(), tcmi_penmigman_process_msg(), tcmi_shadowtask_process_msg(), tcmi_shadowtask_verify_migration(), tcmi_task_deliver_msg(), tcmi_task_process_msg(), and tcmi_task_put().
 {
     return self->msg_id;
 }
int tcmi_msg_init_rx (struct tcmi_msg * self, u_int32_t msg_id, struct tcmi_msg_ops * msg_ops)
<<public>> Initializes the message for receiving.
Parameters
*self - pointer to this message instance
msg_id - ID of a particular message type
*msg_ops - pointer to the message operations
Returns
0 upon success
Definition at line 65 of file tcmi_msg.c.
References tcmi_msg_init_shared().
Referenced by tcmi_authenticate_msg_new_rx(), tcmi_authenticate_resp_msg_new_rx(), tcmi_disconnect_msg_new_rx(), tcmi_err_msg_new_rx(), tcmi_generic_user_msg_new_rx(), tcmi_generic_user_procmsg_new_rx(), tcmi_p_emigrate_msg_new_rx(), tcmi_ppm_p_emigrate_msg_new_rx(), tcmi_procmsg_init_rx(), tcmi_signal_msg_new_rx(), tcmi_skel_msg_new_rx(), and tcmi_skelresp_msg_new_rx().
 {
   return tcmi_msg_init_shared(self, msg_id, msg_ops);
 }
int tcmi_msg_init_tx (struct tcmi_msg * self, u_int32_t msg_id, struct tcmi_msg_ops * msg_ops, struct tcmi_slotvec * transactions, u_int32_t resp_msg_id, u_int timeout, u_int32_t resp_trans_id)
<<public>> Initializes the message for transferring.
For oneway messages sets only message ID and message operations and associated transaction ID (for responses). If there is a response expected, sets up a new transaction.
Parameters
*self - pointer to this message instance
msg_id - ID of a particular message type
*msg_ops - pointer to the message specific operations
*transactions - storage for the new transaction(NULL for one-way messages)
resp_msg_id - response message ID - required for the transaction if the transaction expires(NULL for one-way messages)
timeout - transaction time out (0 for one-way messages)
resp_trans_id - response transaction ID - used when this message is a response to a particular request. The user must set this ID based on the value ofr req_trans_id of the previously received message.
Returns
0 upon success
Definition at line 89 of file tcmi_msg.c.
References mdbg, self, tcmi_msg_init_shared(), TCMI_MSG_TYPE, tcmi_transaction_id(), and tcmi_transaction_new().
Referenced by tcmi_authenticate_msg_new_tx(), tcmi_authenticate_resp_msg_new_tx(), tcmi_disconnect_msg_new_tx(), tcmi_err_msg_new_tx(), tcmi_generic_user_msg_new_tx(), tcmi_generic_user_procmsg_new_tx(), tcmi_p_emigrate_msg_new_tx(), tcmi_ppm_p_emigrate_msg_new_tx(), tcmi_procmsg_init_tx(), tcmi_signal_msg_new_tx(), tcmi_skel_msg_new_tx(), and tcmi_skelresp_msg_new_tx().
 {
     int error = 0;
     /* basic init is the same as when receiving a message */
     tcmi_msg_init_shared(self, msg_id, msg_ops);
     /* transaction ID, needed if this message is a response to a previously sent message */
     self->trans_id.resp = resp_trans_id;
     /* setup transaction when needed */
     if (transactions) {
         if (!(self->transaction =
               tcmi_transaction_new(transactions,
                        TCMI_MSG_TYPE(resp_msg_id), timeout))) {
             mdbg(ERR3, "Can't create a new transaction for message(ID=%x)", msg_id);
             error = -1;
         }
         /* when a transaction was requested, set proper
          * request ID, so that the receiving is able to reply
          */
         else
             self->trans_id.req = tcmi_transaction_id(self->transaction);
     }
     return error;
 }
struct tcmi_msg* tcmi_msg_new_rx (u_int32_t msg_id, struct tcmi_msg_dsc * dsc) read
<<public>> Class method - creates a message based on a descriptor.
Verifies, that the message type in the message ID matches the one in the selected descriptor. Then, based on message ID flags calles the regular rx constructor or error rx constructor. This method is meant to be called by the message factory.
Parameters
msg_id - this message ID is for verification
*dsc - descriptor of a message that is to be built
Returns
new message instance or NULL
Definition at line 357 of file tcmi_msg.c.
References mdbg, tcmi_msg_dsc::msg_id, tcmi_msg_dsc::new_rx, tcmi_msg_dsc::new_rx_err, TCMI_MSG_ERRFLGS, TCMI_MSG_FLG, TCMI_MSG_REGFLGS, and TCMI_MSG_TYPE.
Referenced by tcmi_msg_factory().
 {
     struct tcmi_msg *msg = NULL;
     if (TCMI_MSG_TYPE(msg_id) != TCMI_MSG_TYPE(dsc->msg_id)) {
         mdbg(ERR3, "Requested message ID type(%x) doesn't match the descriptor(%x)",
              TCMI_MSG_TYPE(msg_id), TCMI_MSG_TYPE(dsc->msg_id));
         goto exit0;
     }
     /* based on message flags call the regular or error rx constructor */
     switch (TCMI_MSG_FLG(msg_id)) {
     case TCMI_MSG_REGFLGS:
         if (!dsc->new_rx) {
             mdbg(ERR3, "Regular rx message constructor not present, bailing out..");
             goto exit0;
         }
         msg = dsc->new_rx(msg_id);
         break;
     case TCMI_MSG_ERRFLGS:
         if (!dsc->new_rx_err) {
             mdbg(ERR3, "Error rx message constructor not present, bailing out..");
             goto exit0;
         }
         msg = dsc->new_rx_err(msg_id);
         break;
     default:
         mdbg(ERR3, "Unexpected message flags value in message ID %x", msg_id);
     }
     return msg;
     /* error handling */
  exit0:
     return NULL;
 }
static void tcmi_msg_put (struct tcmi_msg * self) inline static
<<public>> Decrements reference counter, if it reaches 0 the custom free method is called if defined.
Eventually, the instance is destroyed.
The user is responsible for taking the message out of the message queue or detaching it from the transaction when needed.
Parameters
*self - pointer to this message instance
Definition at line 212 of file tcmi_msg.h.
References mdbg, self, and tcmi_transaction_put().
Referenced by tcmi_ccnmigman_process_msg(), tcmi_comm_thread(), tcmi_guest_rpc_sys_fork(), tcmi_guest_rpc_sys_getgroups(), tcmi_guest_rpc_sys_getresgid(), tcmi_guest_rpc_sys_getresuid(), tcmi_guest_rpc_sys_rt_sigqueueinfo(), tcmi_guest_rpc_sys_setgroups(), tcmi_guest_rpc_sys_wait4(), tcmi_guesttask_exit(), tcmi_guesttask_migrateback_p(), tcmi_guesttask_post_fork(), tcmi_guesttask_process_msg(), tcmi_guesttask_process_p_emigrate_msg(), tcmi_man_do_send_generic_user_message(), tcmi_migcom_immigrate(), tcmi_mighooks_execve(), tcmi_migman_notify_peer_disconnect(), tcmi_penmigman_auth_ccn(), tcmi_penmigman_process_msg(), tcmi_rpcresp_procmsg_get_response(), tcmi_shadowtask_emigrate_p(), tcmi_shadowtask_migrateback_ppm_p(), tcmi_shadowtask_process_msg(), tcmi_task_process_msg(), tcmi_task_put(), and tcmi_task_send_message().
 {
     if (!self)
         return;
     if (atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying message ID %x, %p", self->msg_id, self);
         if(self->msg_ops && self->msg_ops->free)
             self->msg_ops->free(self);
         tcmi_transaction_put(self->transaction);
         kfree(self);
     }
 }
int tcmi_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock)
<<public>> Receives the message via a specified connection.
<<public>> Receives the message via a specified connection.
reads the transaction ID from the connection
calls the receive method of the child class
The transaction ID is temporarily stored in the instance and will be used upon delivery when searching for the corresponding transaction.
Parameters
*self - pointer to this message instance
*sock - KKC socket used for receiving message data
Returns
>=0 upon success.Unlike tcmi_msg_send() we don't convert a >=0 result to 0 as this will never get communicated to the user. The receiving thread is the only component that should use this method.
Definition at line 237 of file tcmi_msg.c.
References KKC_SOCK_BLOCK, kkc_sock_rcv_lock_interruptible(), kkc_sock_rcv_unlock(), kkc_sock_recv(), mdbg, tcmi_msg_ops::recv, and self.
Referenced by tcmi_comm_thread().
 {
     int err = 0;
     struct tcmi_msg_ops *ops = self->msg_ops;
     if ((err = kkc_sock_rcv_lock_interruptible(sock))) {
         mdbg(ERR3, "Socket lock - interrupted by a signal %d", err);
         goto exit0;
     }
     /* Receive the transaction ID part */
     if ((err = kkc_sock_recv(sock, &self->trans_id,
                  sizeof(self->trans_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive transaction ID's");
         goto exit1;
     }
     mdbg(INFO3, "Receiving message(ID=%x req=%x resp=%x)",
          self->msg_id, self->trans_id.req, self->trans_id.resp);
     /* */
     if (ops && ops->recv)
         err = ops->recv(self, sock);
     kkc_sock_rcv_unlock(sock);
     return err;
     /* error handling */
  exit1:
     kkc_sock_rcv_unlock(sock);
  exit0:
     return err;
 }
static u_int32_t tcmi_msg_req_id (struct tcmi_msg * self) inline static
<<public>> Request transaction ID accessor.
This is needed when constructing reply messages to set a proper response transaction ID.
Parameters
*self - pointer to this message instance
Returns
message ID extended with error flags
Definition at line 255 of file tcmi_msg.h.
Referenced by tcmi_ccnmigman_process_msg(), tcmi_guesttask_process_p_emigrate_msg(), tcmi_penmigman_process_msg(), and tcmi_rpcresp_procmsg_create().
 {
     return self->trans_id.req;
 }
static int tcmi_msg_send (struct tcmi_msg * self, struct kkc_sock * sock, int flags) static
<<private>> Sends a message via a specified connection.
Sending a message requires following steps:
activate the transaction(if any)
send message ID,
send transaction ID(or TCMI_TRANSACTION_INVAL_ID for oneway messages)
call a specific message method
It is necessary to lock the socket, so that the message won't get intermixed with some other.
Parameters
*self - pointer to this message instance
*sock - KKC socket used for sending message data
flags - if the message has a transaction, these are additional flags to be set in the transaction.
Returns
0 upon success
try to start the transaction
Definition at line 413 of file tcmi_msg.c.
References KKC_SOCK_BLOCK, kkc_sock_send(), kkc_sock_snd_lock_interruptible(), kkc_sock_snd_unlock(), mdbg, self, tcmi_msg_ops::send, and tcmi_transaction_start().
Referenced by tcmi_msg_send_and_receive(), and tcmi_msg_send_anonymous().
 {
     int err = 0;
     struct tcmi_msg_ops *ops = self->msg_ops;
     struct tcmi_transaction *trans = self->transaction;
     /** try to start the transaction */
     if (trans && (err = tcmi_transaction_start(trans, flags))) {
         mdbg(ERR3, "Failed to start the transaction %d", err);
         goto exit0;
     }
     /* Send message ID*/
     mdbg(INFO3, "Sending message(Msg=%p ID=%x req=%x resp=%x), transaction started: %d",
          self, self->msg_id, self->trans_id.req, self->trans_id.resp, (trans!=NULL));
     if ((err = kkc_sock_snd_lock_interruptible(sock))) {
         mdbg(ERR3, "Socket lock - interrupted by a signal %d", err);
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self->msg_id,
                  sizeof(self->msg_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send message ID: %d. Err: %d", self->msg_id, err);
         goto exit1;
     }
     /* Send transaction ID's */
     if ((err = kkc_sock_send(sock, &self->trans_id,
                  sizeof(self->trans_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send transaction ID's");
         goto exit1;
     }
     /* Send the actual message content */
     if (ops && ops->send) {
         err = ops->send(self, sock);
     }
     /* convert the result to 0 if no error has occured this is
      * because the number of bytes sent has no meaning for us anymore */
     err = min(err, 0);
     kkc_sock_snd_unlock(sock);
     return err;
     /* error handling */
  exit1:
     kkc_sock_snd_unlock(sock);
  exit0:
     return err;
 }
int tcmi_msg_send_and_receive (struct tcmi_msg * self, struct kkc_sock * sock, struct tcmi_msg ** resp)
<<public>> Sends a message via a specified connection and waits for the response.
This method is used when the message being sent out has a transaction and a response is expected. The calling thread blocks until a valid response arrives or the transaction expires.
The actual work is delegated to tcmi_msg_send() specifying no extra flags for the transaction. The thread is then put to sleep waiting for completion of the transaction. When its woken up again, the transaction has:
been aborted - the user gets NULL in the response message parameter OR
been completed - the response is extracted from the transaction context OR
a signal has arrived, in that case the transaction will be aborted, but there is still a chance that the response has arrived in the mean time and completed the transaction. In that rare case, the abort fails and returns a valid transaction context, which is our response message. The transaction stays marked as complete.
The transaction is eventually released.
The case when there is no transaction associated with the message is handled correctly - method terminates right after sending out the message.
Parameters
*self - pointer to this message instance
*sock - KKC socket used for sending message data
**resp - contains response message or NULL if the transaction is aborted
Returns
0 upon success
Definition at line 178 of file tcmi_msg.c.
References mdbg, self, TCMI_MSG, tcmi_msg_send(), tcmi_transaction_abort(), TCMI_TRANSACTION_ABORTED, TCMI_TRANSACTION_COMPLETE, tcmi_transaction_context(), and tcmi_transaction_wait_interruptible().
Referenced by tcmi_penmigman_auth_ccn(), and tcmi_task_send_and_receive_msg().
 {
     int err = 0;
     int ret;
     /* increment the reference counter, does nothing when NULL */
     struct tcmi_transaction *trans = self->transaction;
     *resp = NULL;
     /* try sending the data first, quit on error or no transaction */
     err = tcmi_msg_send(self, sock, 0);
     if (!self->transaction || err < 0)
         goto exit0;
     /* wait till the transaction expires */
     ret = tcmi_transaction_wait_interruptible(trans);
     switch (ret) {
     case TCMI_TRANSACTION_ABORTED:
             mdbg(INFO3, "Transaction has been aborted, no response arrived");
         break;
     case TCMI_TRANSACTION_COMPLETE:
             mdbg(INFO3, "Transaction complete, picking up the response");
             *resp = TCMI_MSG(tcmi_transaction_context(trans));
         break;
         /* Aborting a transaction upon a signal arrival must
          * be atomic, it will fail if the transaction has been
          * completed in the meantime and thus the method returns a valid
          * transaction context and transaction stays in 'COMPLETE' state */
     case -ERESTARTSYS:
     default:
         mdbg(INFO3, "Signal arrived, result %d. Check if we abort the transaction..", ret);
         *resp = TCMI_MSG(tcmi_transaction_abort(trans));
         /* communicate the -ERESTARTSYS to the caller */
         err = ret;
         break;
     }
  exit0:
     return err;
 }
int tcmi_msg_send_anonymous (struct tcmi_msg * self, struct kkc_sock * sock)
<<public>> Sends a message via a specified connection.
Sending an anonymous message means, that if there is a transaction associated with the message, the response message will be delivered into regular message queue. This is typically used when the sending thread doesn't want to process the response message itself, but still wants the response to be checked against the transaction.
The actual work is delegated to tcmi_msg_send() specifying the anonymous flag. Then the transaction instance is released as the sending thread doesn't needed it. The status of the send operation is communicated to the user.
This method is also to be used for sending one-way request messages.
Parameters
*self - pointer to this message instance
*sock - KKC socket used for sending message data be set in the transaction.
Returns
0 upon success
Definition at line 138 of file tcmi_msg.c.
References tcmi_msg_send(), and TCMI_TRANS_FLAGS_ANONYMOUS.
Referenced by tcmi_ccnmigman_process_msg(), tcmi_man_do_send_generic_user_message(), tcmi_migman_notify_peer_disconnect(), tcmi_penmigman_process_msg(), tcmi_shadowtask_do_signal(), and tcmi_task_send_anonymous_msg().
 {
     int err;
     err = tcmi_msg_send(self, sock, TCMI_TRANS_FLAGS_ANONYMOUS);
     return err;
 }