Clondike: tcmi_migman class
tcmi_migman class
managers
TCMI migration manager controls migrating tasks for a particular CCN-PEN pair.
Modules
tcmi_ccnmigman class
TCMI CCN migration manager controls migrating tasks for a particular CCN-PEN pair and resides as the name describes - on a CCN.
tcmi_penmigman class
TCMI PEN migration manager controls migrating tasks for a particular CCN-PEN pair and resides as the name describes - on a PEN.
Data Structures
struct tcmi_migman
A compound structure that holds all current shadow processes and other migration related data.
struct tcmi_migman_ops
Migration manager operations that support polymorphism.
Macros
#define TCMI_MIGMAN(migman) ((struct tcmi_migman*)migman)
Casts to the migration manager.
Typedefs
typedef void process_msg_t (struct tcmi_migman *, struct tcmi_msg *)
Message processing method type for the message processing thread.
Enumerations
enum tcmi_migman_state_t {
TCMI_MIGMAN_INIT, TCMI_MIGMAN_CONNECTED, TCMI_MIGMAN_SHUTTING_DOWN, TCMI_MIGMAN_SHUT_DOWN,
TCMI_MIGMAN_STATE_COUNT
}
Describes the current state of the TCMI migration manager.
Functions
static void tcmi_migman_unhash (struct tcmi_migman *self)
Removes migman from a list of migration managers of the associated manager.
static void tcmi_migman_free (struct tcmi_migman *self)
<<private>> Free method is has two purposes:
when the last reference is released, it will free all instance resources, except for the instance itself.
void tcmi_migman_stop (struct tcmi_migman *self)
Requests asynchronous shutdown of connection with peer.
static void tcmi_migman_notify_peer_disconnect (struct tcmi_migman *self)
static int tcmi_migman_stop_perform (struct tcmi_migman *self, int remote_requested)
Actual implementation of stop, see tcmi_migman_stop.
static void kill_all_tasks (struct tcmi_migman *self)
Sends a kill signal to all tasks managed by this manager.
int tcmi_migman_kill (struct tcmi_migman *self)
Kills all tasks associated with this migman and drops reference to the migman (in case it was not already shutting down).
static int tcmi_migman_init_ctlfs_dirs (struct tcmi_migman *self, struct tcmi_ctlfs_entry *root, struct tcmi_ctlfs_entry *migproc, const char namefmt[], va_list args)
<<private>> Creates the directories as described in here .
static int tcmi_migman_init_ctlfs_files (struct tcmi_migman *self)
<<private>> Creates the static files described here .
static void tcmi_migman_stop_ctlfs_dirs (struct tcmi_migman *self)
<<private>> Destroys all TCMI ctlfs directories
static void tcmi_migman_stop_ctlfs_files (struct tcmi_migman *self)
<<private>> Unregisters and releases all control files.
static int tcmi_migman_stop_request (void *obj, void *data)
<<private>> Requests asynchronous shutdown of this migration manager
static int tcmi_migman_kill_request (void *obj, void *data)
<<private>> Requests asynchronous kill of this migration manager
static int tcmi_migman_show_state (void *obj, void *data)
<<private>> Read method for the TCMI ctlfs - reports migration manager state.
static int tcmi_migman_start_thread (struct tcmi_migman *self)
<<private>> Starts the listening thread.
static void tcmi_migman_stop_thread (struct tcmi_migman *self)
<<private>> The TCMI manager listening thread is to be terminated by forcing a signal and waiting for it to terminate.
static int tcmi_migman_deliver_msg (void *obj, struct tcmi_msg *m)
<<private>> Message delivering method that is called back from the receiving thread of TCMI comm component instance.
static int tcmi_migman_msg_thread (void *data)
<<private>> Message processing thread.
int tcmi_migman_add_task (struct tcmi_migman *self, struct tcmi_task *task)
<<public>> Registers tcmi task into the migration manager tasks slotvec
int tcmi_migman_remove_task (struct tcmi_migman *self, struct tcmi_task *task)
<<public>> Removes tcmi task from the migration manager tasks slotvec
int tcmi_migman_create_symlink (struct tcmi_migman *self, struct tcmi_ctlfs_entry *root, struct kkc_sock *sock)
int tcmi_migman_init (struct tcmi_migman *self, struct kkc_sock *sock, u_int32_t ccn_id, u_int32_t pen_id, enum arch_ids peer_arch_type, struct tcmi_slot *manager_slot, struct tcmi_ctlfs_entry *root, struct tcmi_ctlfs_entry *migproc, struct tcmi_migman_ops *ops, const char namefmt[], va_list args)
<<public>> TCMI migration manager initializer.
static struct tcmi_migman * tcmi_migman_get (struct tcmi_migman *self)
<<public>> Instance accessor, increments the reference counter.
int tcmi_migman_put (struct tcmi_migman *self)
Releases the instance.
static tcmi_migman_state_t tcmi_migman_set_state (struct tcmi_migman *self, tcmi_migman_state_t state)
<<public>> Set atomically a new state of the migration manager.
static int tcmi_migman_change_state (struct tcmi_migman *self, tcmi_migman_state_t old_state, tcmi_migman_state_t state)
<<public>> Set atomically a new state of the migration manager, assuming current state == old_state
static tcmi_migman_state_t tcmi_migman_state (struct tcmi_migman *self)
<<public>> Migration manager state accessor.
static u_int tcmi_migman_slot_index (struct tcmi_migman *self)
<<public>> Migration manager slot index getter
static struct tcmi_ctlfs_entry * tcmi_migman_root (struct tcmi_migman *self)
<<public>> Migration manager root directory accessor.
static struct tcmi_slotvec * tcmi_migman_transactions (struct tcmi_migman *self)
<<public>> Transactions accessor.
static struct tcmi_queue * tcmi_migman_msg_queue (struct tcmi_migman *self)
<<public>> Message queue accesor.
static struct kkc_sock * tcmi_migman_sock (struct tcmi_migman *self)
<<public>> Communication socket accesor.
static tcmi_slot_node_t * tcmi_migman_node (struct tcmi_migman *self)
<<public>> Slot node accessor.
static u_int32_t tcmi_migman_id (struct tcmi_migman *self)
<<public>> Migration manager ID accessor.
static struct tcmi_ctlfs_entry * tcmi_migman_migproc_dir (struct tcmi_migman *self)
<<public>> Migproc directory accessor.
static enum arch_ids tcmi_migman_peer_arch (struct tcmi_migman *self)
<<public>> Getter of peer architecture type
Variables
static char * tcmi_migman_states []
String descriptor for the states of migration manager.
Detailed Description
TCMI migration manager controls migrating tasks for a particular CCN-PEN pair.
This is abstract class that gathers all common functionality required for CCN and PEN resp. Node specific implementation is carried out in CCN migration manager and PEN migration manager
Node specific migration manager supplies only methods to:
release all its resources
initialize and destroy TCMI ctlfs directories
initialize and destroy TCMI ctlfs files
process an incoming message from the message queue
deliver a message to the message queue.
Data Structure Documentation
struct tcmi_migman
A compound structure that holds all current shadow processes and other migration related data.
Definition at line 94 of file tcmi_migman.h.
Data Fields
u_int32_t ccn_id CCN ID - supplied by the instantiator(for CCN mig manager) or sent by the CCN(for PEN mig manager)
struct tcmi_comm * comm Communication component used for message receiving and delivery.
struct tcmi_ctlfs_entry * d_conns TCMI ctlfs - directory for active connections.
struct tcmi_ctlfs_entry * d_migman TCMI ctlfs - directory where all migration control files/directories reside.
struct tcmi_ctlfs_entry * d_migproc TCMI ctlfs - reference to the migproc directory - needed when immigrating a process.
struct tcmi_ctlfs_entry * f_kill TCMI ctlfs - request kill of this migration manager.
struct tcmi_ctlfs_entry * f_state TCMI ctlfs - reports current state of the manager.
struct tcmi_ctlfs_entry * f_stop TCMI ctlfs - request shutdown of this migration manager.
u_int32_t id Unique, randomly generated ID.
struct tcmi_slot * manager_slot Reference to slot in an associated manager migmans vector.
Required when performing dequeueing.
struct tcmi_queue msg_queue Message queue for transaction-less messages.
struct task_struct * msg_thread Message processing thread.
tcmi_slot_node_t node A slot node, used for insertion of the manager into a slot.
struct tcmi_migman_ops * ops Operations specific to CCN/PEN migration manager resp.
enum arch_ids peer_arch_type Architecture of corresponding migration manager peer (communicated on registration)
u_int32_t pen_id PEN ID - vica versa to how CCN ID is setup.
atomic_t ref_count Instance reference counter.
struct tcmi_ctlfs_entry * s_migman
struct tcmi_sock * sock TCMI socket that represents an active connection to the PEN.
atomic_t state Denotes the current state of the manager.
struct tcmi_slotvec * tasks slot container for TCMI tasks(shadows on CCN /guests on PEN) that it controls.
struct tcmi_slotvec * transactions Message transactions.
struct tcmi_migman_ops
Migration manager operations that support polymorphism.
Definition at line 158 of file tcmi_migman.h.
Data Fields
int(* init_ctlfs_dirs)(struct tcmi_migman *)
Initializes TCMI ctlfs directories.
int(* init_ctlfs_files)(struct tcmi_migman *)
Initializes TCMI ctlfs files.
void(* stop_ctlfs_dirs)(struct tcmi_migman *)
Destroys all TCMI ctlfs directories.
void(* stop_ctlfs_files)(struct tcmi_migman *)
Destroys all TCMI ctlfs files.
void(* free)(struct tcmi_migman *)
Releases the instance specific resources.
void(* process_msg)(struct tcmi_migman *, struct tcmi_msg *)
Processes a TCMI message m.
void(* stop)(struct tcmi_migman *, int)
Request to stop this migration manager and terminate its connection with peer.
Field Documentation
void(* tcmi_migman_ops::free)(struct tcmi_migman *)
Releases the instance specific resources.
Definition at line 168 of file tcmi_migman.h.
int(* tcmi_migman_ops::init_ctlfs_dirs)(struct tcmi_migman *)
Initializes TCMI ctlfs directories.
Definition at line 160 of file tcmi_migman.h.
int(* tcmi_migman_ops::init_ctlfs_files)(struct tcmi_migman *)
Initializes TCMI ctlfs files.
Definition at line 162 of file tcmi_migman.h.
void(* tcmi_migman_ops::process_msg)(struct tcmi_migman *, struct tcmi_msg *)
Processes a TCMI message m.
Definition at line 170 of file tcmi_migman.h.
Referenced by tcmi_migman_init().
void(* tcmi_migman_ops::stop)(struct tcmi_migman *, int)
Request to stop this migration manager and terminate its connection with peer.
Definition at line 173 of file tcmi_migman.h.
void(* tcmi_migman_ops::stop_ctlfs_dirs)(struct tcmi_migman *)
Destroys all TCMI ctlfs directories.
Definition at line 164 of file tcmi_migman.h.
void(* tcmi_migman_ops::stop_ctlfs_files)(struct tcmi_migman *)
Destroys all TCMI ctlfs files.
Definition at line 166 of file tcmi_migman.h.
Macro Definition Documentation
#define TCMI_MIGMAN (migman) ((struct tcmi_migman*)migman)
Casts to the migration manager.
Definition at line 180 of file tcmi_migman.h.
Referenced by tcmi_ccnmigman_auth_pen(), tcmi_ccnmigman_new(), tcmi_migman_deliver_msg(), tcmi_migman_kill_request(), tcmi_migman_msg_thread(), tcmi_migman_show_state(), tcmi_migman_stop_request(), tcmi_penmigman_auth_ccn(), tcmi_penmigman_migrate_all_home(), and tcmi_penmigman_new().
Typedef Documentation
typedef void process_msg_t(struct tcmi_migman *, struct tcmi_msg *)
Message processing method type for the message processing thread.
Definition at line 178 of file tcmi_migman.h.
Enumeration Type Documentation
enum tcmi_migman_state_t
Describes the current state of the TCMI migration manager.
The states have following meaning:
INIT - the system is being brought up
CONNECTED - PEN has been succesfully authenticated and is now connected
SHUTTING_DOWN - no more migration requests will be accepted, migrated should be moved back or to other PEN
SHUT_DOWN - all connections are closed, component is ready for destruction.
Enumerator
TCMI_MIGMAN_INIT
TCMI_MIGMAN_CONNECTED
TCMI_MIGMAN_SHUTTING_DOWN
TCMI_MIGMAN_SHUT_DOWN
TCMI_MIGMAN_STATE_COUNT
Definition at line 80 of file tcmi_migman.h.
              {
     TCMI_MIGMAN_INIT,
     TCMI_MIGMAN_CONNECTED,
     TCMI_MIGMAN_SHUTTING_DOWN,
     TCMI_MIGMAN_SHUT_DOWN,
     /* number of states, not a special state */
     TCMI_MIGMAN_STATE_COUNT
 } tcmi_migman_state_t;
Function Documentation
static void kill_all_tasks (struct tcmi_migman * self) static
Sends a kill signal to all tasks managed by this manager.
Definition at line 307 of file tcmi_migman.c.
References mdbg, self, tcmi_slot_entry, tcmi_slot_for_each, tcmi_slotvec_for_each_used_slot, tcmi_slotvec_lock(), tcmi_slotvec_unlock(), tcmi_task_local_pid(), and tcmi_task_signal_peer_lost().
Referenced by tcmi_migman_kill().
{
     struct tcmi_task* task;
     struct tcmi_slot *slot;
     tcmi_slot_node_t* node;
     tcmi_slotvec_lock(self->tasks);
     /* Iterate over all managed tasks */
     tcmi_slotvec_for_each_used_slot(slot, self->tasks) {
         tcmi_slot_for_each(node, slot) {
             task = tcmi_slot_entry(node, struct tcmi_task, node);
             mdbg(INFO3, "Killing task: local_pid=%d", tcmi_task_local_pid(task));
             tcmi_task_signal_peer_lost(task);
         };
     };
     tcmi_slotvec_unlock(self->tasks);
 }
int tcmi_migman_add_task (struct tcmi_migman * self, struct tcmi_task * task)
<<public>> Registers tcmi task into the migration manager tasks slotvec
Definition at line 709 of file tcmi_migman.c.
References mdbg, minfo, tcmi_task::node, self, tcmi_slotvec_hashmask(), tcmi_slotvec_insert_at(), tcmi_task_hash(), and tcmi_task_local_pid().
Referenced by tcmi_task_init().
{
     u_int hash;
     hash = tcmi_task_hash(tcmi_task_local_pid(task), tcmi_slotvec_hashmask(self->tasks));
     //tcmi_slotvec_lock(self->tasks);
     if ( !tcmi_slotvec_insert_at(self->tasks, hash, &task->node) ) {
         //tcmi_slotvec_unlock(self->tasks);
         minfo(ERR3, "Can't insert task into a migration manager slot vector!");
         return -EINVAL;
     }
     //tcmi_slotvec_unlock(self->tasks);
     mdbg(INFO3, "Inserted task PID=%d into slot with hash %d", tcmi_task_local_pid(task), hash);
     return 0;
 }
static int tcmi_migman_change_state (struct tcmi_migman * self, tcmi_migman_state_t old_state, tcmi_migman_state_t state) inline static
<<public>> Set atomically a new state of the migration manager, assuming current state == old_state
Parameters
*self - pointer to this instance
old_state - old state, that must hold in order to succeed in change
state - new state to be set
Returns
Non zero, in case change was performed
Definition at line 235 of file tcmi_migman.h.
References self.
Referenced by tcmi_migman_kill(), and tcmi_migman_stop_perform().
 {
     tcmi_migman_state_t current_state = (tcmi_migman_state_t)atomic_cmpxchg(&self->state, (int)old_state, (int)state);
     return current_state == old_state;
 }
int tcmi_migman_create_symlink (struct tcmi_migman * self, struct tcmi_ctlfs_entry * root, struct kkc_sock * sock)
Definition at line 751 of file tcmi_migman.c.
References kkc_sock_getpeername(), KKC_SOCK_MAX_ADDR_LENGTH, mdbg, self, and tcmi_ctlfs_symlink_new().
Referenced by tcmi_migman_init().
 {
         char n[KKC_SOCK_MAX_ADDR_LENGTH];
         //char * n = kmalloc(KKC_SOCK_MAX_ADDR_LENGTH,GFP_KERNEL);
         int i = KKC_SOCK_MAX_ADDR_LENGTH;
         mdbg(INFO4,"tcmi_migman_create_symlink");
         kkc_sock_getpeername(sock,n,KKC_SOCK_MAX_ADDR_LENGTH);
         while(i>-1 && n[i]!=':')i--;
         if(i>-1 && n[i] == ':')n[i]=0;
         if(!(self->s_migman=tcmi_ctlfs_symlink_new(root,self->d_migman,n))){
                 return -EINVAL;
         }
         return 0;
 }
static int tcmi_migman_deliver_msg (void * obj, struct tcmi_msg * m) static
<<private>> Message delivering method that is called back from the receiving thread of TCMI comm component instance.
This method is reponsible for delivering the message reliably to its destination which can be:
local migration manager message queue
local migration manager transaction slot vector
TCMI task message queue
TCMI task transaction slot vector
Parameters
*obj - pointer to the migration manager instance. passed to the TCMI comm component upon creation
*m - points to the message that is to be delivered.
Returns
0 upon successful delivery
Definition at line 604 of file tcmi_migman.c.
References mdbg, pid, self, TCMI_MIGMAN, tcmi_migman_id(), tcmi_msg_deliver(), TCMI_MSG_GROUP, TCMI_MSG_GROUP_PROC, tcmi_msg_id(), TCMI_PROCMSG, tcmi_procmsg_dst_pid(), tcmi_task_deliver_msg(), tcmi_task_local_pid(), tcmi_task_migman_id(), tcmi_task_put(), and tcmi_taskhelper_find_by_pid().
Referenced by tcmi_migman_init().
 {
     int err = 0;
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     struct tcmi_task *task;
     if (TCMI_MSG_GROUP(tcmi_msg_id(m)) == TCMI_MSG_GROUP_PROC) {
         /* try finding the task based on PID  in the message */
         pid_t pid = tcmi_procmsg_dst_pid(TCMI_PROCMSG(m));
         mdbg(INFO3, "Process message %08x arrived as expected for PID=%d",
              tcmi_msg_id(m), pid);
         /* find task by PID */
         if (!(task = tcmi_taskhelper_find_by_pid(pid))) {
             mdbg(ERR2, "Can't find dest. task for msg ID=%08x",
                  tcmi_msg_id(m));
             goto exit0;
         }
         /* Verify it belongs to us */
         if (tcmi_task_migman_id(task) != tcmi_migman_id(self)) {
             mdbg(ERR2, "Task(PID=%d, migman ID=%08x) doesn't belong"
                  "to migration manager ID=%08x", tcmi_task_local_pid(task),
                  tcmi_task_migman_id(task), tcmi_migman_id(self));
             goto exit1;
         }
         err = tcmi_task_deliver_msg(task, m);
         tcmi_task_put(task);
     }
     else {
         mdbg(INFO3, "Delivering regular migration message %08x",
              tcmi_msg_id(m));
         err = tcmi_msg_deliver(m, &self->msg_queue, self->transactions);
     }
     return err;
     /* error handling */
  exit1:
     tcmi_task_put(task);
  exit0:
     return -EINVAL;
 }
static void tcmi_migman_free (struct tcmi_migman * self) static
<<private>> Free method is has two purposes:
when the last reference is released, it will free all instance resources, except for the instance itself.
calls the child class free method if defined
Note: It is important to free communication channels first, i.e. communication socket, processing thread and files. This ensures, that no new messages that may require reference to migman for processing will arrive. File operations are synchronized with releasing so it may be possible that some file works with the migman during the free method, but only until the file is ''synchronously'' released.
Definition at line 228 of file tcmi_migman.c.
References self, tcmi_comm_put(), tcmi_migman_stop_ctlfs_dirs(), tcmi_migman_stop_ctlfs_files(), tcmi_migman_stop_thread(), tcmi_migman_unhash(), tcmi_slotvec_put(), and tcmi_sock_put().
Referenced by tcmi_migman_put().
 {
     /* terminate the processing thread first to prevent any
      * message processing */
     tcmi_migman_stop_thread(self);
     /* also stop receiving all messages */
     tcmi_comm_put(self->comm);
     tcmi_migman_stop_ctlfs_files(self);
     tcmi_migman_stop_ctlfs_dirs(self);
     tcmi_sock_put(self->sock);
     tcmi_migman_unhash(self);
     /* now we are safe and we can start cleaning the rest */
     if (self->ops->free)
         self->ops->free(self);
     /* TODO: check for stale transactions.. */
     tcmi_slotvec_put(self->transactions);
     /* Note: Assumes, all tasks are already migrated back. */
     tcmi_slotvec_put(self->tasks);
 }
static struct tcmi_migman* tcmi_migman_get (struct tcmi_migman * self) static read
<<public>> Instance accessor, increments the reference counter.
Parameters
*self - pointer to this instance
Returns
tcmi_migman instance
Definition at line 201 of file tcmi_migman.h.
References self.
Referenced by tcmi_man_emig_npm(), tcmi_man_emig_ppm_p(), tcmi_man_fork(), tcmi_man_send_generic_user_message(), tcmi_migcom_emigrate_ccn_npm(), and tcmi_task_init().
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static u_int32_t tcmi_migman_id (struct tcmi_migman * self) inline static
<<public>> Migration manager ID accessor.
Parameters
*self - pointer to this instance
Returns
tcmi_slot_node
Definition at line 332 of file tcmi_migman.h.
Referenced by tcmi_migman_deliver_msg(), and tcmi_task_migman_id().
 {
     return self->id;
 }
int tcmi_migman_init (struct tcmi_migman * self, struct kkc_sock * sock, u_int32_t ccn_id, u_int32_t pen_id, enum arch_ids peer_arch_type, struct tcmi_slot * manager_slot, struct tcmi_ctlfs_entry * root, struct tcmi_ctlfs_entry * migproc, struct tcmi_migman_ops * ops, const char namefmt[], va_list args)
<<public>> TCMI migration manager initializer.
<<public>> TCMI migration manager initializer.
<<public>> TCMI migration manager initializer. The initialization is accomplished exactly in this order:
set ID's and initial state
initialize message queue and the transaction vector
choose a unique ID for the manager.
store a reference to a mig proc directory - it's required when immigrating a process.
start TCMI communication component
create TCMI ctlfs directories
create TCMI ctlfs control files
create a TCMI socket to represent the connection in filesystem
run the message processing thread.
Parameters
*self - this migration manager instance
*sock - socket where the control connection between CCN/PEN is running
ccn_id - CCN identifier - valid when initializing a CCN mig. manager
pen_id - PEN identifier - valid when initializing a PEN mig. manager
peer_arch_type - Architecture of the peer node
*root - directory where the migration manager should create its files and directories
*migproc - directory where the migrated process will have their info
*ops - instance specific operations
namefmt - nameformat string for the main manager directory name (printf style)
args - variable arguments list
Returns
0 upon success
Definition at line 81 of file tcmi_migman.c.
References mdbg, minfo, tcmi_migman_ops::process_msg, self, TASK_ORDER, tcmi_comm_new(), tcmi_comm_put(), tcmi_migman_create_symlink(), tcmi_migman_deliver_msg(), TCMI_MIGMAN_INIT, tcmi_migman_init_ctlfs_dirs(), tcmi_migman_init_ctlfs_files(), tcmi_migman_start_thread(), tcmi_migman_stop_ctlfs_dirs(), tcmi_migman_stop_ctlfs_files(), TCMI_MSG_GROUP_ANY, tcmi_queue_init(), tcmi_slotvec_hnew(), tcmi_slotvec_put(), tcmi_sock_new(), tcmi_sock_put(), and TRANSACTION_ORDER.
Referenced by tcmi_ccnmigman_new(), and tcmi_penmigman_new().
 {
     int err = -EINVAL;
     minfo(INFO2, "Creating new TCMI migration manager");
     atomic_set(&self->state, TCMI_MIGMAN_INIT);
     self->ccn_id = ccn_id;
     self->pen_id = pen_id;
     self->manager_slot = manager_slot;
     self->peer_arch_type = peer_arch_type;
     atomic_set(&self->ref_count, 1);
     tcmi_queue_init(&self->msg_queue);
     get_random_bytes(&self->id, sizeof(u_int32_t));
     self->ops = ops;
     if (!ops) {
         mdbg(ERR3, "Missing migration manager operations!");
         goto exit0;
     }
     if (!ops->process_msg) {
         mdbg(ERR3, "Missing process message operation!");
         goto exit0;
     }
     if (!(self->transactions = tcmi_slotvec_hnew(TRANSACTION_ORDER))) {
         mdbg(ERR3, "Can't create transactions slotvector!");
         goto exit0;
     }
     if (!(self->tasks = tcmi_slotvec_hnew(TASK_ORDER))) {
         mdbg(ERR3, "Can't create tasks slotvector!");
         goto exit1;
     }
     /* TCMI comm that accepts all types of messages */
     if (!(self->comm = tcmi_comm_new(sock, tcmi_migman_deliver_msg, self,
                      TCMI_MSG_GROUP_ANY))) {
         mdbg(ERR3, "Failed to create TCMI comm component!");
         goto exit2;
     }
     if (tcmi_migman_init_ctlfs_dirs(self, root, migproc, namefmt, args) < 0) {
         mdbg(ERR3, "Failed to create ctlfs directories!");
         goto exit3;
     }
     mdbg(INFO4, "Creating symlink: self: %p root: %p sock %p",self, root, sock);
         if (tcmi_migman_create_symlink(self, root, sock) < 0){
                 mdbg(ERR3, "Failed to create ctlfs symlink!");
                 goto exit4;
         }
     if (tcmi_migman_init_ctlfs_files(self) < 0) {
         mdbg(ERR3, "Failed to create ctlfs files!");
         goto exit4;
     }
     if (!(self->sock = tcmi_sock_new(self->d_conns, sock, "ctrlconn"))) {
         mdbg(ERR3, "Failed to create a TCMI socket!");
         goto exit5;
     }
     if (tcmi_migman_start_thread(self) < 0) {
         mdbg(ERR3, "Failed to create message processing thread!");
         goto exit6;
     }
     return 0;
     /* error handling */
  exit6:
     tcmi_sock_put(self->sock);
  exit5:
     tcmi_migman_stop_ctlfs_files(self);
  exit4:
     tcmi_migman_stop_ctlfs_dirs(self);
  exit3:
     tcmi_comm_put(self->comm);
  exit2:
     tcmi_slotvec_put(self->tasks);
  exit1:
     tcmi_slotvec_put(self->transactions);
  exit0:
     return err;
 }
static int tcmi_migman_init_ctlfs_dirs (struct tcmi_migman * self, struct tcmi_ctlfs_entry * root, struct tcmi_ctlfs_entry * migproc, const char namefmt[], va_list args) static
<<private>> Creates the directories as described in here .
Parameters
*self - pointer to this migration manager instance
*root - root directory where to create TCMI ctlfs entries
*migproc - directory where the migrated process will have their info
namefmt - nameformat string for the main manager directory name (printf style)
args - arguments to the format string
Returns
0 upon success
Definition at line 358 of file tcmi_migman.c.
References mdbg, self, tcmi_ctlfs_dir_new(), tcmi_ctlfs_dir_vnew(), tcmi_ctlfs_entry_get(), tcmi_ctlfs_entry_put(), and TCMI_PERMS_DIR.
Referenced by tcmi_migman_init().
 {
     mdbg(INFO4, "Creating directories");
     if (!(self->d_migman = tcmi_ctlfs_dir_vnew(root, TCMI_PERMS_DIR, namefmt, args)))
         goto exit0;
     if (!(self->d_conns =
           tcmi_ctlfs_dir_new(self->d_migman, TCMI_PERMS_DIR, "connections")))
         goto exit1;
     if (!(self->d_migproc = tcmi_ctlfs_entry_get(migproc))) {
         mdbg(ERR3, "Missing migproc directory for migration manager!");
         goto exit2;
     }
     if (self->ops->init_ctlfs_dirs && self->ops->init_ctlfs_dirs(self)) {
         mdbg(ERR3, "Failed to create specific ctlfs directories!");
         goto exit3;
     }
     return 0;
     /* error handling */
  exit3:
     tcmi_ctlfs_entry_put(self->d_migproc);
  exit2:
     tcmi_ctlfs_entry_put(self->d_conns);
  exit1:
     tcmi_ctlfs_entry_put(self->d_migman);
  exit0:
     return -EINVAL;
 }
static int tcmi_migman_init_ctlfs_files (struct tcmi_migman * self) static
<<private>> Creates the static files described here .
Parameters
*self - pointer to this migration manager instance
Returns
0 upon success
Definition at line 404 of file tcmi_migman.c.
References mdbg, self, tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), tcmi_ctlfs_intfile_new(), tcmi_ctlfs_strfile_new(), tcmi_migman_kill_request(), tcmi_migman_show_state(), TCMI_MIGMAN_STATE_LENGTH, tcmi_migman_stop_request(), TCMI_PERMS_FILE_R, and TCMI_PERMS_FILE_W.
Referenced by tcmi_migman_init().
 {
     mdbg(INFO4, "Creating files");
     if (!(self->f_state =
           tcmi_ctlfs_strfile_new(self->d_migman, TCMI_PERMS_FILE_R,
                      self, tcmi_migman_show_state, NULL,
                      TCMI_MIGMAN_STATE_LENGTH, "state")))
         goto exit0;
     if (!(self->f_stop =
           tcmi_ctlfs_intfile_new(self->d_migman, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_migman_stop_request,
                      sizeof(int), "stop")))
         goto exit1;
     if (!(self->f_kill =
           tcmi_ctlfs_intfile_new(self->d_migman, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_migman_kill_request,
                      sizeof(int), "kill")))
         goto exit2;
     if (self->ops->init_ctlfs_files && self->ops->init_ctlfs_files(self)) {
         mdbg(ERR3, "Failed to create specific ctlfs files!");
         goto exit3;
     }
     return 0;
     /* error handling */
  exit3:
     tcmi_ctlfs_file_unregister(self->f_kill);
     tcmi_ctlfs_entry_put(self->f_kill);
  exit2:
     tcmi_ctlfs_file_unregister(self->f_stop);
     tcmi_ctlfs_entry_put(self->f_stop);
  exit1:
     tcmi_ctlfs_file_unregister(self->f_state);
     tcmi_ctlfs_entry_put(self->f_state);
  exit0:
     return -EINVAL;
 }
int tcmi_migman_kill (struct tcmi_migman * self)
Kills all tasks associated with this migman and drops reference to the migman (in case it was not already shutting down).
The method is useful in case peer died without cleaning up its own tasks, because we need to clean them up before we can release reference to peer.
Returns
1, if the migman instance was destroyed in context of this method
Definition at line 330 of file tcmi_migman.c.
References kill_all_tasks(), minfo, tcmi_migman_change_state(), TCMI_MIGMAN_CONNECTED, tcmi_migman_put(), TCMI_MIGMAN_SHUTTING_DOWN, tcmi_migman_slot_index(), and tcmi_migman_state().
Referenced by tcmi_migman_kill_request().
{
      minfo(INFO3, "Requesting kill of migration manager: %d", tcmi_migman_slot_index(self));
      kill_all_tasks(self);
      if ( tcmi_migman_change_state(self, TCMI_MIGMAN_CONNECTED, TCMI_MIGMAN_SHUTTING_DOWN) ) {
     /* Stop operation was not yet requested -> request it. */
     return tcmi_migman_put(self);
      } else {
     minfo(INFO3, "Migration manager stop was already requested -> Do not perform release this call. Manager state is: %d", tcmi_migman_state(self));
      }
      return 0;
 }
static int tcmi_migman_kill_request (void * obj, void * data) static
<<private>> Requests asynchronous kill of this migration manager
Parameters
*obj - this migration manager instance
*data - ignored
Returns
0 upon success
Definition at line 511 of file tcmi_migman.c.
References TCMI_MIGMAN, and tcmi_migman_kill().
Referenced by tcmi_migman_init_ctlfs_files().
{
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     tcmi_migman_kill(self);
     return 0;
 }
static struct tcmi_ctlfs_entry* tcmi_migman_migproc_dir (struct tcmi_migman * self) static read
<<public>> Migproc directory accessor.
Parameters
*self - pointer to this instance
Returns
migproc directory where the migrated process publishes its info
Definition at line 344 of file tcmi_migman.h.
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_migcom_guest_fork(), tcmi_migcom_immigrate(), and tcmi_migcom_shadow_fork().
 {
     return self->d_migproc;
 }
static struct tcmi_queue* tcmi_migman_msg_queue (struct tcmi_migman * self) static read
<<public>> Message queue accesor.
Parameters
*self - pointer to this instance
Returns
message queue reference
Definition at line 293 of file tcmi_migman.h.
 {
     return &self->msg_queue;
 }
static int tcmi_migman_msg_thread (void * data) static
<<private>> Message processing thread.
Sleeps on the message queue and notifies the migration manager instance to process each incoming message.
Parameters
*data - migration manager instance
Returns
0 upon successful thread termination.
Definition at line 654 of file tcmi_migman.c.
References mdbg, minfo, tcmi_migman::node, self, TCMI_DISCONNECT_MSG_ID, TCMI_MIGMAN, tcmi_migman_stop_perform(), tcmi_msg_id(), tcmi_queue_remove_entry, tcmi_queue_wait_on_empty_interruptible(), and wait_on_should_stop.
Referenced by tcmi_migman_start_thread().
 {
     int err = 0;
     int migman_freed = 0;
     struct tcmi_msg *m;
     struct tcmi_migman *self = TCMI_MIGMAN(data);
     /* saves 2 derefences when calling the process msg method */
     process_msg_t *process_msg = self->ops->process_msg;
     if (!process_msg) {
         mdbg(ERR3, "Missing method to process messages!");
         goto exit0;
     }
     mdbg(INFO3, "Message processing thread up and running %p", current);
     while (!(kthread_should_stop() || signal_pending(current))) {
         if ((err = tcmi_queue_wait_on_empty_interruptible(&self->msg_queue)) < 0) {
             minfo(INFO1, "Signal arrived %d", err);
             break;
         }
         tcmi_queue_remove_entry(&self->msg_queue, m, node);
         if (m) {
             mdbg(INFO3, "Processing message..");
             switch(tcmi_msg_id(m)) {
                 default:
                 process_msg(self, m);
                 break;
                 case TCMI_DISCONNECT_MSG_ID:
                     minfo(INFO3, "Received disconnect message");
                 /*
                   Initiate shutdown upon reception of disconnect message
                   Note: It is important not to touch self after this call and before should_stop is checked again, because self reference may be already invalid!
                 */
                 migman_freed = tcmi_migman_stop_perform(self, 1);
                 break;
             }
         }
         else {
             mdbg(ERR3, "Processing thread woken up, queue is still empty..");
         }
     }
  exit0:
     /* In case the migman was freed by this thread, no should_stop sync is performed */
     if ( !migman_freed ) {
         /* We have to wait for thread terminating us as it is going to call stop at some tim */
         wait_on_should_stop();
     }
     mdbg(INFO3, "Message processing thread terminating");
     return 0;
 }
static tcmi_slot_node_t* tcmi_migman_node (struct tcmi_migman * self) inline static
<<public>> Slot node accessor.
Parameters
*self - pointer to this instance
Returns
tcmi_slot_node
Definition at line 319 of file tcmi_migman.h.
Referenced by tcmi_ccnman_process_sock(), and tcmi_penman_connect().
 {
     if (!self)
         return NULL;
     return &self->node;
 }
static void tcmi_migman_notify_peer_disconnect (struct tcmi_migman * self) static
Definition at line 262 of file tcmi_migman.c.
References minfo, tcmi_disconnect_msg_new_tx(), tcmi_migman_sock(), TCMI_MSG, tcmi_msg_put(), and tcmi_msg_send_anonymous().
Referenced by tcmi_migman_stop_perform().
{
     struct tcmi_msg* msg;
     int err;
     if ( !( msg = TCMI_MSG(tcmi_disconnect_msg_new_tx()) ) ) {
         minfo(ERR3, "Error creating disconnect message");
     } else {
     if ((err = tcmi_msg_send_anonymous(msg, tcmi_migman_sock(self)))) {
         minfo(ERR3, "Error sending disconnect message %d", err);
     }
     tcmi_msg_put(msg);
     }
 }
static enum arch_ids tcmi_migman_peer_arch (struct tcmi_migman * self) inline static
<<public>> Getter of peer architecture type
Parameters
*self - pointer to this instance
Returns
architecture of peer computer
Definition at line 355 of file tcmi_migman.h.
 {
     return self->peer_arch_type;
 }
int tcmi_migman_put (struct tcmi_migman * self)
Releases the instance.
Releases the instance.
calls the free method specific to a particular migration manager
stop message receiving thread
destroy TCMI socket
unregister all ctlfs files as we don't want anymore requests from users.
unregister all ctlfs directories
release the communication component
release the transaction slot vector - check for stale transactions
release the shadows slot vector
Parameters
*self - pointer to this migration manager instance
Returns
Returns 1, if the instance was destroyed as a result of this call
Definition at line 189 of file tcmi_migman.c.
References mdbg, self, and tcmi_migman_free().
Referenced by tcmi_ccnman_process_sock(), tcmi_man_emig_npm(), tcmi_man_emig_ppm_p(), tcmi_man_fork(), tcmi_man_send_generic_user_message(), tcmi_migcom_emigrate_ccn_npm(), tcmi_migman_kill(), tcmi_migman_stop_perform(), tcmi_penman_connect(), tcmi_task_init(), and tcmi_task_put().
 {
     if (self && atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO3, "Shutting down the TCMI migration manager %p", self);
         tcmi_migman_free(self);
         kfree(self);
         return 1;
     }
     return 0;
 }
int tcmi_migman_remove_task (struct tcmi_migman * self, struct tcmi_task * task)
<<public>> Removes tcmi task from the migration manager tasks slotvec
Definition at line 728 of file tcmi_migman.c.
References mdbg, minfo, tcmi_task::node, self, tcmi_slot_remove(), tcmi_slotvec_at(), tcmi_slotvec_hashmask(), tcmi_task_hash(), and tcmi_task_local_pid().
Referenced by tcmi_task_put().
{
     u_int hash;
     struct tcmi_slot* slot;
     hash = tcmi_task_hash(tcmi_task_local_pid(task), tcmi_slotvec_hashmask(self->tasks));
     //tcmi_slotvec_lock(self->tasks);
     slot = tcmi_slotvec_at(self->tasks, hash);
     if ( !slot ) {
         //tcmi_slotvec_unlock(self->tasks);
         minfo(ERR3, "Failed to remove task slotvec in migman tasks");
         return -EINVAL;
     }
     tcmi_slot_remove(slot, &task->node);
     //tcmi_slotvec_unlock(self->tasks);
     mdbg(INFO3, "Removed task PID=%d from slot with hash %d", tcmi_task_local_pid(task), hash);
     return 0;
 }
static struct tcmi_ctlfs_entry* tcmi_migman_root (struct tcmi_migman * self) static read
<<public>> Migration manager root directory accessor.
Parameters
*self - pointer to this instance
Returns
current state of the manager
Definition at line 271 of file tcmi_migman.h.
Referenced by tcmi_ccnmigman_init_ctlfs_files(), tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_migcom_guest_fork(), tcmi_migcom_immigrate(), and tcmi_migcom_shadow_fork().
 {
     return self->d_migman;
 }
static tcmi_migman_state_t tcmi_migman_set_state (struct tcmi_migman * self, tcmi_migman_state_t state) inline static
<<public>> Set atomically a new state of the migration manager.
Parameters
*self - pointer to this instance
state - new state to be set
Returns
Last state, i.e. state before the state change was performed
Definition at line 221 of file tcmi_migman.h.
References self.
Referenced by tcmi_ccnmigman_process_msg(), and tcmi_penmigman_process_msg().
 {
     return (tcmi_migman_state_t)atomic_xchg(&self->state, (int)state);
 }
static int tcmi_migman_show_state (void * obj, void * data) static
<<private>> Read method for the TCMI ctlfs - reports migration manager state.
Parameters
*obj - this migration manager instance
*data - pointer to this migration manager instance
Returns
0 upon success
Definition at line 526 of file tcmi_migman.c.
References mdbg, TCMI_MIGMAN, tcmi_migman_state(), TCMI_MIGMAN_STATE_COUNT, TCMI_MIGMAN_STATE_LENGTH, and tcmi_migman_states.
Referenced by tcmi_migman_init_ctlfs_files().
 {
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     mdbg(INFO3, "state %d, maxcount %d", tcmi_migman_state(self), TCMI_MIGMAN_STATE_COUNT);
     if (tcmi_migman_state(self) < TCMI_MIGMAN_STATE_COUNT) {
         strncpy((char*)data,
             tcmi_migman_states[tcmi_migman_state(self)],
             TCMI_MIGMAN_STATE_LENGTH);
         mdbg(INFO3, "Displaying state %s", tcmi_migman_states[tcmi_migman_state(self)]);
     }
     return 0;
 }
static u_int tcmi_migman_slot_index (struct tcmi_migman * self) inline static
<<public>> Migration manager slot index getter
Parameters
*self - pointer to this instance
Returns
Index of slot in manager migmans vector
Definition at line 259 of file tcmi_migman.h.
References self, and tcmi_slot_index().
Referenced by tcmi_ccnmigman_process_msg(), tcmi_ccnmigman_stop(), tcmi_migcom_immigrate(), tcmi_migman_kill(), tcmi_migman_stop_perform(), tcmi_penmigman_process_msg(), tcmi_penmigman_stop(), and tcmi_task_migman_slot_index().
 {
     return tcmi_slot_index(self->manager_slot);
 }
static struct kkc_sock* tcmi_migman_sock (struct tcmi_migman * self) static read
<<public>> Communication socket accesor.
Reference counter is not adjusted as the socket is part of the tcmi_sock instance. The caller is expected to have a valid reference to the tcmi_migman which in turn guarantees a reference to tcmi_sock.
Parameters
*self - pointer to this instance
Returns
pointer to KKC socket.
Definition at line 307 of file tcmi_migman.h.
References self, and tcmi_sock_kkc_sock_get().
Referenced by check_duplicates(), tcmi_ccnmigman_process_msg(), tcmi_man_do_send_generic_user_message(), tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), tcmi_migcom_guest_fork(), tcmi_migcom_immigrate(), tcmi_migcom_shadow_fork(), tcmi_migman_notify_peer_disconnect(), tcmi_penmigman_auth_ccn(), tcmi_penmigman_process_msg(), and tcmi_shadowtask_do_signal().
 {
     return tcmi_sock_kkc_sock_get(self->sock);
 }
static int tcmi_migman_start_thread (struct tcmi_migman * self) static
<<private>> Starts the listening thread.
The kernel thread is started by using kernel services. No additional actions are needed.
Parameters
*self - pointer to this migration manager instance
Returns
0 upon sucessful thread creation
Definition at line 547 of file tcmi_migman.c.
References mdbg, self, and tcmi_migman_msg_thread().
Referenced by tcmi_migman_init().
 {
     int err = 0;
     self->msg_thread = kthread_run(tcmi_migman_msg_thread, self,
                        "tcmi_migmsgd");
     if (IS_ERR(self->msg_thread)) {
         err = -EINVAL;
         goto exit0;
     }
     mdbg(INFO3, "Created message processing thread %p", self->msg_thread);
     /* error hanlding */
  exit0:
     return err;
 }
static tcmi_migman_state_t tcmi_migman_state (struct tcmi_migman * self) inline static
<<public>> Migration manager state accessor.
Parameters
*self - pointer to this instance
Returns
current state of the manager
Definition at line 248 of file tcmi_migman.h.
References self.
Referenced by tcmi_ccnmigman_auth_pen(), tcmi_man_get_non_shutdowning_migman(), tcmi_migman_kill(), tcmi_migman_show_state(), tcmi_migman_stop_perform(), and tcmi_penmigman_auth_ccn().
 {
     return (tcmi_migman_state_t)atomic_read(&self->state);
 }
void tcmi_migman_stop (struct tcmi_migman * self)
Requests asynchronous shutdown of connection with peer.
Asynchronous request to stop migration manager, migrate all process back to hom and terminate connection with peer.
First, it asynchronously requests emigration of tasks to their home node, in case we are on detached node. Then it notifies peer about current node being disconnected. Finally, a self reference is dropped so that the migman is free to be destroyed when all tasks are finished
Definition at line 258 of file tcmi_migman.c.
References tcmi_migman_stop_perform().
Referenced by tcmi_man_stop_migration(), and tcmi_migman_stop_request().
{
     tcmi_migman_stop_perform(self, 0);
 }
static void tcmi_migman_stop_ctlfs_dirs (struct tcmi_migman * self) static
<<private>> Destroys all TCMI ctlfs directories
Parameters
*self - pointer to this migration manager instance
Definition at line 454 of file tcmi_migman.c.
References mdbg, self, and tcmi_ctlfs_entry_put().
Referenced by tcmi_migman_free(), and tcmi_migman_init().
 {
     mdbg(INFO3, "Destroying  TCMI migmanager ctlfs directories");
     if (self->ops->stop_ctlfs_dirs)
         self->ops->stop_ctlfs_dirs(self);
     tcmi_ctlfs_entry_put(self->d_migman);
     tcmi_ctlfs_entry_put(self->s_migman);
     tcmi_ctlfs_entry_put(self->d_conns);
     tcmi_ctlfs_entry_put(self->d_migproc);
 }
static void tcmi_migman_stop_ctlfs_files (struct tcmi_migman * self) static
<<private>> Unregisters and releases all control files.
Parameters
*self - pointer to this migration manager instance
Definition at line 472 of file tcmi_migman.c.
References mdbg, self, tcmi_ctlfs_entry_put(), TCMI_CTLFS_FILE_FROM_METHOD, tcmi_ctlfs_file_unregister(), and tcmi_ctlfs_file_unregister2().
Referenced by tcmi_migman_free(), and tcmi_migman_init().
 {
     mdbg(INFO3, "Destroying  TCMI migmanager ctlfs files");
     if (self->ops->stop_ctlfs_files)
         self->ops->stop_ctlfs_files(self);
     /* We have to use non-locking unregister, because the unregister could be called from this file's write method */
     tcmi_ctlfs_file_unregister2(self->f_stop, TCMI_CTLFS_FILE_FROM_METHOD);
     tcmi_ctlfs_entry_put(self->f_stop);
     /* We have to use non-locking unregister, because the unregister could be called from this file's write method */
     tcmi_ctlfs_file_unregister2(self->f_kill, TCMI_CTLFS_FILE_FROM_METHOD);
     tcmi_ctlfs_entry_put(self->f_kill);
     tcmi_ctlfs_file_unregister(self->f_state);
     tcmi_ctlfs_entry_put(self->f_state);
 }
static int tcmi_migman_stop_perform (struct tcmi_migman * self, int remote_requested) static
Actual implementation of stop, see tcmi_migman_stop.
Parameters
remote_requested True, if stop request was initiated as a response to received disconnect message 1, if the migman instance was destroyed in context of this method
Definition at line 282 of file tcmi_migman.c.
References minfo, self, tcmi_migman_change_state(), TCMI_MIGMAN_CONNECTED, tcmi_migman_notify_peer_disconnect(), tcmi_migman_put(), TCMI_MIGMAN_SHUTTING_DOWN, tcmi_migman_slot_index(), and tcmi_migman_state().
Referenced by tcmi_migman_msg_thread(), and tcmi_migman_stop().
{
      minfo(INFO3, "Requesting stop of migration manager: %d Remote requested: %d", tcmi_migman_slot_index(self), remote_requested);
      if ( tcmi_migman_change_state(self, TCMI_MIGMAN_CONNECTED, TCMI_MIGMAN_SHUTTING_DOWN) ) {
     /* We are the first to request stop operation */
     if (self->ops->stop)
         self->ops->stop(self, remote_requested);
     if ( !remote_requested ) {
         /* Sent notification to peer about disconnection being performed.. even if this fails (peer may be dead already), we proceed further */
         tcmi_migman_notify_peer_disconnect(self);
     }
     /* Finally drop the reference to "self". If this is the last reference, the instance is going to be unhased and deleted.
        At this phase it is possible some tasks are still running and so they have reference to this instance. Asynchronous emigration requests were already issued */
     return tcmi_migman_put(self);
      } else {
     minfo(INFO3, "Migration manager stop was already requested -> Ignoring this call. Manager state is: %d", tcmi_migman_state(self));
      }
      return 0;
 }
static int tcmi_migman_stop_request (void * obj, void * data) static
<<private>> Requests asynchronous shutdown of this migration manager
Parameters
*obj - this migration manager instance
*data - ignored
Returns
0 upon success
Definition at line 497 of file tcmi_migman.c.
References TCMI_MIGMAN, and tcmi_migman_stop().
Referenced by tcmi_migman_init_ctlfs_files().
{
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     tcmi_migman_stop(self);
     return 0;
 }
static void tcmi_migman_stop_thread (struct tcmi_migman * self) static
<<private>> The TCMI manager listening thread is to be terminated by forcing a signal and waiting for it to terminate.
The thread notices the request from the manager and terminates.
Parameters
*self - pointer to this migration manager instance
Definition at line 572 of file tcmi_migman.c.
References mdbg, and self.
Referenced by tcmi_migman_free().
 {
     if (self->msg_thread) {
         mdbg(INFO3, "Stopping message processing thread");
         force_sig(SIGTERM, self->msg_thread);
         if ( self->msg_thread != current ) {
           /* We can only call stop if we are not actually the thread being stopped! */
           kthread_stop(self->msg_thread);
         }
     }
 }
static struct tcmi_slotvec* tcmi_migman_transactions (struct tcmi_migman * self) static read
<<public>> Transactions accessor.
Parameters
*self - pointer to this instance
Returns
transactions slot vector
Definition at line 282 of file tcmi_migman.h.
Referenced by tcmi_penmigman_auth_ccn().
 {
     return self->transactions;
 }
static void tcmi_migman_unhash (struct tcmi_migman * self) static
Removes migman from a list of migration managers of the associated manager.
Check if we were not already unhashed
Definition at line 208 of file tcmi_migman.c.
References self, tcmi_slot_lock(), tcmi_slot_node_unhashed, tcmi_slot_remove_first, and tcmi_slot_unlock().
Referenced by tcmi_migman_free().
{
       /** Check if we were not already unhashed */
       if ( !tcmi_slot_node_unhashed(&self->node) ) {
       tcmi_slot_lock(self->manager_slot);
       tcmi_slot_remove_first(self, self->manager_slot, node);
       tcmi_slot_unlock(self->manager_slot);
       }
 }
Variable Documentation
char* tcmi_migman_states[] static
Initial value:
= {
    "Init",
    "Connected",
    "Shutting down",
    "Shutdown"
}
String descriptor for the states of migration manager.
Definition at line 768 of file tcmi_migman.c.
Referenced by tcmi_migman_show_state().