Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/director/netlink/npm_msg.c File Reference
npm_msg.c File Reference
#include "npm_msg.h"
#include "msgs.h"
#include "genl_ext.h"
#include "comm.h"
#include <dbg.h>
#include <linux/skbuff.h>
#include <linux/resource.h>
Data Structures
struct npm_check_params
Functions
static int npm_check_create_request (struct sk_buff *skb, void *params)
Creates npm check request.
static int npm_check_read_response (struct genl_info *info, void *params)
int npm_check (pid_t pid, uid_t uid, int is_guest, const char *name, int *decision, int *decision_value, struct rusage *rusage)
Checks, whether the process should be non-preemptively migrated to some other node.
static int put_char_array (struct sk_buff *skb, char **chars, int type, int nested_type)
static int npm_check_full_create_request (struct sk_buff *skb, void *params)
int npm_check_full (pid_t pid, uid_t uid, int is_guest, const char *name, char __user *__user *args, char __user *__user *envp, int *decision, int *decision_value)
Checks, whether the process should be non-preemptively migrated to some other node.
Variables
static struct msg_transaction_ops npm_check_msg_ops
static struct msg_transaction_ops npm_check_full_msg_ops
Data Structure Documentation
struct npm_check_params
Definition at line 11 of file npm_msg.c.
Data Fields
char __user *__user * args
int decision User mode helper decision.
. one of npm_msg_response enum
int decision_value If the decision has some target value, this will hold it.
char __user *__user * envp
int is_guest
const char * name
int name_length
pid_t pid
struct rusage * rusage
uid_t uid
Function Documentation
int npm_check (pid_t pid, uid_t uid, int is_guest, const char * name, int * decision, int * decision_value, struct rusage * rusage)
Checks, whether the process should be non-preemptively migrated to some other node.
Parameters
pid Pid of the process
uid Effective user ID of the process being executed
is_guest 1 if the process is guest
name File name, that is being executed
decision Output parameter.. element of "npm_msg_response" enum
decision_value Output param .. if result is to perform migration, this will contain slot of the migration manager to be used
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 94 of file npm_msg.c.
References npm_check_params::args, npm_check_params::decision, npm_check_params::decision_value, DIRECTOR_CHECK_NPM, npm_check_params::envp, npm_check_params::is_guest, msg_transaction_do(), npm_check_params::name, npm_check_params::name_length, npm_check_params::pid, pid, npm_check_params::rusage, and npm_check_params::uid.
Referenced by director_npm_check().
{
     struct npm_check_params params;
     int ret;
     params.pid = pid;
     params.uid = uid;
     params.is_guest = is_guest;
     params.name = name;
     params.name_length = strlen(name);
     params.args = NULL;
     params.envp = NULL;
     params.rusage = rusage;
     ret = msg_transaction_do(DIRECTOR_CHECK_NPM, &npm_check_msg_ops, &params, 0);
     if ( ret )
         return ret;
     *decision = params.decision;
     *decision_value = params.decision_value;
     return 0;
 }
static int npm_check_create_request (struct sk_buff * skb, void * params) static
Creates npm check request.
Definition at line 31 of file npm_msg.c.
References DIRECTOR_A_LENGTH, DIRECTOR_A_NAME, DIRECTOR_A_PID, DIRECTOR_A_RUSAGE, DIRECTOR_A_TASK_TYPE, DIRECTOR_A_UID, npm_check_params::is_guest, npm_check_params::name, npm_check_params::name_length, npm_check_params::pid, npm_check_params::rusage, and npm_check_params::uid.
{
     int ret = 0;
     struct npm_check_params* check_params = params;
     ret = nla_put_u32(skb, DIRECTOR_A_PID, check_params->pid);
     if (ret != 0)
             goto failure;
     ret = nla_put_u32(skb, DIRECTOR_A_UID, check_params->uid);
     if (ret != 0)
             goto failure;
     ret = nla_put_u32(skb, DIRECTOR_A_TASK_TYPE, check_params->is_guest ? 1 : 0);
     if (ret != 0)
             goto failure;
     ret = nla_put_string(skb, DIRECTOR_A_NAME, check_params->name);
     if (ret != 0)
             goto failure;
     ret = nla_put_u32(skb, DIRECTOR_A_LENGTH, check_params->name_length);
     if (ret != 0)
         goto failure;
     if (check_params->rusage) {
         ret = nla_put(skb, DIRECTOR_A_RUSAGE, sizeof *check_params->rusage, check_params->rusage);
         if (ret != 0)
                 goto failure;
     }
 failure:
     return ret;
 }
int npm_check_full (pid_t pid, uid_t uid, int is_guest, const char * name, char __user *__user * args, char __user *__user * envp, int * decision, int * decision_value)
Checks, whether the process should be non-preemptively migrated to some other node.
This version in addition passes args & envp
Parameters
pid Pid of the process
uid Effective user ID of the process being executed
is_guest 1 if the process is guest
name File name, that is being executed
args Args, or NULL if no args are provided
envp Envinromental properties, or NULL if no envs are provided
decision Output parameter.. element of "npm_msg_response" enum
decision_value Output param .. if result is to perform migration, this will contain slot of the migration manager to be used
Returns
0 on success, error code otherwise. In case of error, output params are not valid!
Definition at line 198 of file npm_msg.c.
References npm_check_params::args, args, npm_check_params::decision, npm_check_params::decision_value, DIRECTOR_CHECK_FULL_NPM, npm_check_params::envp, envp, npm_check_params::is_guest, msg_transaction_do(), npm_check_params::name, npm_check_params::name_length, npm_check_params::pid, pid, npm_check_params::rusage, and npm_check_params::uid.
Referenced by director_npm_check().
{
     struct npm_check_params params;
     int ret;
     params.pid = pid;
     params.uid = uid;
     params.is_guest = is_guest;
     params.name = name;
     params.name_length = strlen(name);
     params.args = args;
     params.envp = envp;
     params.rusage = NULL;
     ret = msg_transaction_do(DIRECTOR_CHECK_FULL_NPM, &npm_check_full_msg_ops, &params, 0);
     if ( ret )
         return ret;
     *decision = params.decision;
     *decision_value = params.decision_value;
     return 0;
 }
static int npm_check_full_create_request (struct sk_buff * skb, void * params) static
Definition at line 155 of file npm_msg.c.
References npm_check_params::args, DIRECTOR_A_ARG, DIRECTOR_A_ARGS, DIRECTOR_A_ENV, DIRECTOR_A_ENVS, DIRECTOR_A_NAME, DIRECTOR_A_PID, DIRECTOR_A_TASK_TYPE, DIRECTOR_A_UID, npm_check_params::envp, npm_check_params::is_guest, npm_check_params::name, npm_check_params::pid, put_char_array(), and npm_check_params::uid.
{
     int ret = 0;
     struct npm_check_params* check_params = params;
     ret = nla_put_u32(skb, DIRECTOR_A_PID, check_params->pid);
     if (ret != 0)
             goto failure;
     ret = nla_put_u32(skb, DIRECTOR_A_UID, check_params->uid);
     if (ret != 0)
             goto failure;
     ret = nla_put_u32(skb, DIRECTOR_A_TASK_TYPE, check_params->is_guest ? 1 : 0);
     if (ret != 0)
             goto failure;
     ret = nla_put_string(skb, DIRECTOR_A_NAME, check_params->name);
     if (ret != 0)
             goto failure;
 //      ret = nla_put_u32(skb, DIRECTOR_A_LENGTH, check_params->name_length);
 //  if (ret != 0)
 //      goto failure;
     ret = put_char_array(skb, check_params->args, DIRECTOR_A_ARGS, DIRECTOR_A_ARG);
     if (ret != 0)
         goto failure;
     ret = put_char_array(skb, check_params->envp, DIRECTOR_A_ENVS, DIRECTOR_A_ENV);
     if (ret != 0)
         goto failure;
 failure:
     return ret;
 }
static int npm_check_read_response (struct genl_info * info, void * params) static
Definition at line 66 of file npm_msg.c.
References npm_check_params::decision, npm_check_params::decision_value, DIRECTOR_A_DECISION, and DIRECTOR_A_DECISION_VALUE.
{
     int ret = 0;
     struct nlattr* attr;
     struct npm_check_params* check_params = params;
     attr = nlmsg_find_attr(info->nlhdr, sizeof(struct genlmsghdr), DIRECTOR_A_DECISION);
     if ( attr == NULL ) {
         ret = -EBADMSG;
         goto done;
     }
     check_params->decision = nla_get_u32(attr);
     attr = nlmsg_find_attr(info->nlhdr, sizeof(struct genlmsghdr), DIRECTOR_A_DECISION_VALUE);
     if ( attr != NULL ) {
         check_params->decision_value = nla_get_u32(attr);
     } else {
         check_params->decision_value = 0;
     }
 done:
     return ret;
 }
static int put_char_array (struct sk_buff * skb, char ** chars, int type, int nested_type) static
Definition at line 118 of file npm_msg.c.
References DIRECTOR_A_LENGTH, and minfo.
Referenced by npm_check_full_create_request().
{
     struct nlattr* nest_attr;
     int ret = 0;
     if ( chars ) {
         int i=0;
         nest_attr = nla_nest_start(skb, type);
                 if ( !nest_attr ) {
             ret = -EMSGSIZE;
             goto failure;
         }
         while ( chars[i] ) {
 //          printk("Putting arg\n");
             ret = nla_put_string(skb, nested_type, chars[i]);
             if (ret != 0)
                 goto failure;
             i++;
         }
 //      printk("Putting length: %d\n", i);
         ret = nla_put_u32(skb, DIRECTOR_A_LENGTH, i); // Count of elements
         if (ret != 0)
             goto failure;
         nla_nest_end(skb, nest_attr);
     }
     return ret;
 failure:
     minfo(ERR1, "Putting of char array has failed: %d", ret);
     return ret;
 }
Variable Documentation
struct msg_transaction_ops npm_check_full_msg_ops static
Initial value:
= {
    .create_request = npm_check_full_create_request,
    .read_response = npm_check_read_response
}
Definition at line 192 of file npm_msg.c.
struct msg_transaction_ops npm_check_msg_ops static
Initial value:
= {
    .create_request = npm_check_create_request,
    .read_response = npm_check_read_response
}
Definition at line 89 of file npm_msg.c.