Clondike: tcmi_transaction class
tcmi_transaction class
communication
A transaction in communication is setup when a request message expects a certain response from the receiving party.
Data Structures
struct tcmi_transaction
Compound structure holding transaction attributes.
Macros
#define TCMI_TRANSACTION_INVAL_ID 0
denotes an invalid transaction ID
#define TCMI_TRANS_FLAGS_ANONYMOUS 0x00000001
Denotes a transaction, where nobody is waiting for the response.
#define TCMI_TRANS_FLAGS_EXPIRED 0x00000002
Denotes an expired transaction that hasn't been completed.
Enumerations
enum tcmi_trans_state_t { TCMI_TRANSACTION_INIT, TCMI_TRANSACTION_RUNNING, TCMI_TRANSACTION_COMPLETE, TCMI_TRANSACTION_ABORTED }
Describes the current state of the transaction:
Functions
static void tcmi_transaction_gen_id (struct tcmi_transaction *self)
<<private>> Generates a transaction ID.
static void tcmi_transaction_timer (unsigned long trans)
<<private>> Callback for the kernel timer that handles transaction timeouts.
struct tcmi_transaction * tcmi_transaction_new (struct tcmi_slotvec *transactions, u_int32_t resp_id, unsigned long timeout)
<<public>> Creates a new transaction.
int tcmi_transaction_start (struct tcmi_transaction *self, int flags)
<<public>> Starts a transaction.
void * tcmi_transaction_abort (struct tcmi_transaction *self)
<<public>> Aborting the transaction.
int tcmi_transaction_complete (struct tcmi_transaction *self, void *context, u_int32_t type_id)
<<public>> Completes a transaction and wakes up the processing thread.
struct tcmi_transaction * tcmi_transaction_lookup (struct tcmi_slotvec *transactions, u_int32_t trans_id)
<<public>> Tries to find a transaction based on its ID.
void tcmi_transaction_put (struct tcmi_transaction *self)
<<public>> Releases the instance - serialized version.
static void tcmi_transaction_lock (struct tcmi_transaction *self)
<<public>> Locks the instance data.
static void tcmi_transaction_unlock (struct tcmi_transaction *self)
<<public>> Unlocks the instance data
static struct tcmi_transaction * tcmi_transaction_get (struct tcmi_transaction *self)
<<public>> Instance accessor.
static u_int32_t tcmi_transaction_id (struct tcmi_transaction *self)
<<public>> Transaction ID accessor.
static tcmi_trans_state_t tcmi_transaction_state (struct tcmi_transaction *self)
<<public>> Transaction state accessor.
static void * tcmi_transaction_context (struct tcmi_transaction *self)
<<public>> Transaction context accessor.
static void tcmi_transaction_set_flags (struct tcmi_transaction *self, int flags)
<<public>> Sets flags in the transaction that denote additional transaction attributes.
static int tcmi_transaction_is_complete (struct tcmi_transaction *self)
<<public>> Checks on a complete transaction.
static int tcmi_transaction_is_aborted (struct tcmi_transaction *self)
<<public>> Checks on aborted transaction.
static int tcmi_transaction_is_running (struct tcmi_transaction *self)
<<public>> Checks on a running transaction.
static int tcmi_transaction_is_anon (struct tcmi_transaction *self)
<<public>> Checks on an anonymous transaction.
static int tcmi_transaction_wait (struct tcmi_transaction *self)
<<public>> Waits on a transaction till it expires or is completed.
static int tcmi_transaction_wait_interruptible (struct tcmi_transaction *self)
<<public>> Waits on a transaction till it expires or is completed, the task can be prematurely woken up by a signal.
Detailed Description
A transaction in communication is setup when a request message expects a certain response from the receiving party.
This class provides the functionality to create, start and complete such transaction.
An example: A PEN node wants to register with a CCN. It will send a registration request towards the CCN. A new transaction is started on the PEN side by the thread creating the initial message. The transaction is assigned following attributes:
transaction ID
response message ID
response timeout
flags -
anonymous - setting an anonymous flag means that the user doesn't wait for the response synchronously. This flag is checked by tcmi_msg.c::tcmi_msg_deliver() - see for details.
expired - the timer upon timout marks the transaction expired and sets it to aborted state. This flag is used when checking whether the timer went off or not (needed for transaction destruction).
The CCN receives the registration request performs some authentication tasks and sends a reply back. The response message will carry the transaction ID. On PEN, the message is identified based on the transaction ID and successfully received. The message then completes the transaction, which in turn wakes up the thread waiting for the message. Message delivery is closely coupled to transactions. See tcmi_msg.c::tcmi_msg_deliver().
There are few stages in transaction lifetime:
INIT - this is the phase when the transaction is instantiated and inserted into a transaction slot vector, but not active yet
RUNNING - transaction is activated and the timout timer is running.
COMPLETE - transaction has been successfully finished, the context data is ready to be picked up by the transaction owner
ABORTED - if the transaction times out, the timer handler marks it aborted. The transaction owner is supposed to discard such transaction
Data Structure Documentation
struct tcmi_transaction
Compound structure holding transaction attributes.
Definition at line 108 of file tcmi_transaction.h.
Data Fields
void * context pointer to the transaction context data - assigned upon successful completion.
atomic_t flags Flags describe additional attributes of the transaction.
u_int32_t id transaction ID.
tcmi_slot_node_t node link for storing the transaction in a slot.
atomic_t ref_count reference counter.
u_int32_t resp_id response ID - verified upon transaction completion.
struct tcmi_slot * slot Slot where the transaction resides.
tcmi_trans_state_t state transaction state.
spinlock_t t_lock spin lock - serializes access to the transaction.
struct timer_list timer timer used for transaction timeouts.
struct tcmi_slotvec * transactions Back-references to slotvec where the transaction is present.
. used to get access to slotvec lock to guard agains lookup/put races.
wait_queue_head_t wq Sleeping processes, that are to be notified upon transaction time out or completion.
Macro Definition Documentation
#define TCMI_TRANS_FLAGS_ANONYMOUS 0x00000001
Denotes a transaction, where nobody is waiting for the response.
Definition at line 102 of file tcmi_transaction.h.
Referenced by tcmi_msg_send_anonymous(), and tcmi_transaction_is_anon().
#define TCMI_TRANS_FLAGS_EXPIRED 0x00000002
Denotes an expired transaction that hasn't been completed.
Definition at line 104 of file tcmi_transaction.h.
#define TCMI_TRANSACTION_INVAL_ID 0
denotes an invalid transaction ID
Definition at line 99 of file tcmi_transaction.h.
Referenced by tcmi_authenticate_msg_new_tx(), tcmi_disconnect_msg_new_tx(), tcmi_exit_procmsg_new_tx(), tcmi_generic_user_msg_new_tx(), tcmi_generic_user_procmsg_new_tx(), tcmi_guesttask_post_fork(), tcmi_msg_deliver(), tcmi_msg_init_shared(), tcmi_p_emigrate_msg_new_tx(), tcmi_ppm_p_emigrate_msg_new_tx(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx(), tcmi_rpc_procmsg_new_tx(), tcmi_signal_msg_new_tx(), tcmi_skel_msg_new_tx(), tcmi_skel_procmsg_new_tx(), tcmi_transaction_gen_id(), and tcmi_vfork_done_procmsg_new_tx().
Enumeration Type Documentation
enum tcmi_trans_state_t
Describes the current state of the transaction:
Enumerator
TCMI_TRANSACTION_INIT
TCMI_TRANSACTION_RUNNING
TCMI_TRANSACTION_COMPLETE
TCMI_TRANSACTION_ABORTED
Definition at line 91 of file tcmi_transaction.h.
              {
     TCMI_TRANSACTION_INIT,
     TCMI_TRANSACTION_RUNNING,
     TCMI_TRANSACTION_COMPLETE,
     TCMI_TRANSACTION_ABORTED,
 } tcmi_trans_state_t;
Function Documentation
void* tcmi_transaction_abort (struct tcmi_transaction * self)
<<public>> Aborting the transaction.
<<public>> Aborting the transaction.
deleting the timer and checking if it hasn't expired
if the timer has been deleted without expiring, it is necessary to drop the reference that the timer was retaining
proceed further if the transaction is in INIT or RUNNING state and change the state to ABORTED.
notifying the transaction owner
Parameters
*self - pointer to this transaction instance
Returns
if the transaction has already been completed, it will return a valid context and doesn't change the transaction state. An aborted transaction has still its context set to NULL.
Definition at line 168 of file tcmi_transaction.c.
References mdbg, self, TCMI_TRANSACTION_ABORTED, tcmi_transaction_is_complete(), tcmi_transaction_lock(), tcmi_transaction_put(), and tcmi_transaction_unlock().
Referenced by tcmi_msg_send_and_receive().
 {
     int put_needed = 0;
     del_timer_sync(&self->timer);
     tcmi_transaction_lock(self);
     if (!tcmi_transaction_is_expired(self)) {
         mdbg(INFO3, "Transaction hasn't expired yet, dropping timer reference.");
         tcmi_transaction_set_expired(self);
         put_needed = 1;
     }
     /* Transaction can be aborted from RUNNING as well as from
      * INIT state. */
     if (!tcmi_transaction_is_complete(self)) {
         mdbg(INFO3, "Aborting..");
         self->state = TCMI_TRANSACTION_ABORTED;
         tcmi_transaction_notify_owner(self);
     }
     tcmi_transaction_unlock(self);
     if ( put_needed ) {
         tcmi_transaction_put(self);
         return NULL;
     }
     return self->context;
 }
int tcmi_transaction_complete (struct tcmi_transaction * self, void * context, u_int32_t resp_id)
<<public>> Completes a transaction and wakes up the processing thread.
The completion requires:
deleting the running timer and checking if it hasn't expired
if the timer has been deleted without expiring, it is necessary to drop the reference that the timer was retaining
proceed further if the transaction is in running state ONLY
verifying, that the response ID in the transaction matches caller's expected response ID. The transaction is aborted if those two ID's don't match as apparently a wrong response has arrived.
upon successful completion, the context specified by the user, is associated with the transaction. That way, the transaction owner can read any data related to a particular transaction, when it picks up the completed transaction.
notifying the transaction owner
Completing a transaction is performed under transaction lock being held.
Parameters
*self - this transaction instance
*context - context that is to be assigned to the transaction upon successful completion.
resp_id - response message ID that must match the ID set initially in the transaction.
Returns
0 when sucessfully completed
Definition at line 223 of file tcmi_transaction.c.
References tcmi_transaction::context, mdbg, self, TCMI_TRANSACTION_ABORTED, TCMI_TRANSACTION_COMPLETE, tcmi_transaction_is_running(), tcmi_transaction_lock(), tcmi_transaction_put(), tcmi_transaction_state(), and tcmi_transaction_unlock().
Referenced by tcmi_msg_deliver().
 {
     /* default is error */
     int err = -EINVAL;
     int put_needed = 0;
     del_timer_sync(&self->timer);
     tcmi_transaction_lock(self);
     if (!tcmi_transaction_is_expired(self)) {
         mdbg(INFO3, "Transaction hasn't expired yet, dropping timer reference.");
         tcmi_transaction_set_expired(self);
         put_needed = 1;
     }
     mdbg(INFO3, "Transaction state: %d", tcmi_transaction_state(self));
     if (!tcmi_transaction_is_running(self)) {
         mdbg(INFO3, "Can't complete-transaction ID %x is not running!", self->id);
         goto exit0;
     }
     if (self->resp_id == resp_id) {
         mdbg(INFO3, "Successfully completing transaction ID %x", self->id);
         self->state = TCMI_TRANSACTION_COMPLETE;
         self->context = context;
         err = 0;
     }
     else {
         self->state = TCMI_TRANSACTION_ABORTED;
         mdbg(ERR4, "Aborting transaction ID %x, resp_id(%x)"
              "doesn't match the expected resp_id(%x)!",
              self->id, resp_id, self->resp_id);
     }
     /* In every case notify the transaction owner*/
     tcmi_transaction_notify_owner(self);
  exit0:
     tcmi_transaction_unlock(self);
     if ( put_needed )
         tcmi_transaction_put(self);
     return err;
 }
static void* tcmi_transaction_context (struct tcmi_transaction * self) inline static
<<public>> Transaction context accessor.
Parameters
*self - pointer to this transaction instance
Returns
pointer to the context associated with the transaction
Definition at line 238 of file tcmi_transaction.h.
Referenced by tcmi_msg_send_and_receive().
 {
     return self->context;
 }
static void tcmi_transaction_gen_id (struct tcmi_transaction * self) static
<<private>> Generates a transaction ID.
Parameters
*self - this transaction instance
Definition at line 360 of file tcmi_transaction.c.
References mdbg, and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_transaction_new().
 {
     u_int32_t id = TCMI_TRANSACTION_INVAL_ID;
     while (id == TCMI_TRANSACTION_INVAL_ID) {
         get_random_bytes(&id, sizeof(u_int32_t));
     }
     self->id = id;
     mdbg(INFO4, "Generated new transaction ID: %x", id);
 }
static struct tcmi_transaction* tcmi_transaction_get (struct tcmi_transaction * self) static read
<<public>> Instance accessor.
increments the reference counter. The user is now guaranteed, that the instance stays in memory while he is using it. Assumes, the access is serialized by means of locking the slot where the instance resides.
Parameters
*self - pointer to this instance
Returns
tcmi_transaction instance
Definition at line 199 of file tcmi_transaction.h.
References self.
Referenced by tcmi_transaction_lookup(), and tcmi_transaction_start().
 {
     if (self)
         atomic_inc(&self->ref_count);
     return self;
 }
static u_int32_t tcmi_transaction_id (struct tcmi_transaction * self) inline static
<<public>> Transaction ID accessor.
Parameters
*self - pointer to this transaction instance
Returns
transaction ID
Definition at line 213 of file tcmi_transaction.h.
Referenced by tcmi_msg_deliver(), tcmi_msg_init_tx(), tcmi_transaction_lookup(), tcmi_transaction_new(), and tcmi_transaction_put().
 {
     return self->id;
 }
static int tcmi_transaction_is_aborted (struct tcmi_transaction * self) inline static
<<public>> Checks on aborted transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction has been aborted
Definition at line 275 of file tcmi_transaction.h.
References self, and TCMI_TRANSACTION_ABORTED.
Referenced by tcmi_transaction_wait(), and tcmi_transaction_wait_interruptible().
 {
     return (self->state == TCMI_TRANSACTION_ABORTED);
 }
static int tcmi_transaction_is_anon (struct tcmi_transaction * self) inline static
<<public>> Checks on an anonymous transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction is marked as anonymous.
Definition at line 297 of file tcmi_transaction.h.
References self, and TCMI_TRANS_FLAGS_ANONYMOUS.
Referenced by tcmi_msg_deliver().
 {
     return atomic_read(&self->flags) & TCMI_TRANS_FLAGS_ANONYMOUS;
 }
static int tcmi_transaction_is_complete (struct tcmi_transaction * self) inline static
<<public>> Checks on a complete transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction has been successfully finished
Definition at line 264 of file tcmi_transaction.h.
References self, and TCMI_TRANSACTION_COMPLETE.
Referenced by tcmi_transaction_abort(), tcmi_transaction_wait(), and tcmi_transaction_wait_interruptible().
 {
     return (self->state == TCMI_TRANSACTION_COMPLETE);
 }
static int tcmi_transaction_is_running (struct tcmi_transaction * self) inline static
<<public>> Checks on a running transaction.
Parameters
*self - pointer to this transaction instance
Returns
true if transaction is still running..
Definition at line 286 of file tcmi_transaction.h.
References self, and TCMI_TRANSACTION_RUNNING.
Referenced by tcmi_transaction_complete().
 {
     return (self->state == TCMI_TRANSACTION_RUNNING);
 }
static void tcmi_transaction_lock (struct tcmi_transaction * self) inline static
<<public>> Locks the instance data.
Spin lock used - no sleeping allowed!
Parameters
*self - pointer to this transaction instance
Definition at line 174 of file tcmi_transaction.h.
References self.
Referenced by tcmi_transaction_abort(), tcmi_transaction_complete(), and tcmi_transaction_start().
 {
     spin_lock(&self->t_lock);
 }
struct tcmi_transaction* tcmi_transaction_lookup (struct tcmi_slotvec * transactions, u_int32_t trans_id) read
<<public>> Tries to find a transaction based on its ID.
This is a class method that tries to find a transaction instance. It computes a hash of the transaction ID and searches the slot at index equal to the hash value.
The access to the transaction is serialized via the slotvector that is being searched.
Parameters
*transactions - slot vector where to perform the search
trans_id - ID used when searching for the transaction.
Returns
transaction if found or NULL
Definition at line 279 of file tcmi_transaction.c.
References mdbg, minfo, tcmi_transaction::node, tcmi_slot_for_each_entry, tcmi_slotvec_at(), tcmi_slotvec_hashmask(), tcmi_slotvec_lock(), tcmi_slotvec_unlock(), tcmi_transaction_get(), and tcmi_transaction_id().
Referenced by tcmi_msg_deliver().
 {
     u_int hash;
     /* slot where the hash of the transaction ID points to */
     struct tcmi_slot *slot;
     struct tcmi_transaction *tran = NULL;
     /* temporary storage for the slot elements, needed by the iterator */
     tcmi_slot_node_t *nd;
     hash = tcmi_transaction_hash(trans_id, tcmi_slotvec_hashmask(transactions));
     tcmi_slotvec_lock(transactions);
     /* get the slot, the hash is pointing too */
     if (!(slot = tcmi_slotvec_at(transactions, hash))) {
         mdbg(ERR3, "Can't locate slot");
         goto exit0;
     }
     /* Search the slot for matching transaction */
     tcmi_slot_for_each_entry(tran, nd, slot, node) {
         if (tcmi_transaction_id(tran) == trans_id) {
             minfo(INFO4,"Found matching transaction ID %x", trans_id);
             break;
         }
     }
     /* succesfully found a transaction, adjust its reference counter */
     if (tran)
         tcmi_transaction_get(tran);
     tcmi_slotvec_unlock(transactions);
     return tran;
 /* error handling */
  exit0:
     tcmi_slotvec_unlock(transactions);
     return NULL;
 }
struct tcmi_transaction* tcmi_transaction_new (struct tcmi_slotvec * transactions, u_int32_t resp_id, unsigned long timeout) read
<<public>> Creates a new transaction.
Instance is created as follows:
allocate the instance
generate a transaction ID (random number)
initilialize wait queue for process(es) that is/are to be woken up when:
the transaction times out or
when it is sucessfully completed
store timeout that will be activated when the transaction is started.
store the transaction in the transaction slot vector specified by the user
setup reference counter
clear transaction flags - the transaction owner will adjust the flags afterwards
one instance reference is for the timer and one instance reference is returned to the instantiator
Parameters
*transactions - storage for the transactions
resp_id - response message ID - required for the transaction so that match the response upon completion.
timeout - transaction time out
Returns
new transaction or NULL
Definition at line 67 of file tcmi_transaction.c.
References tcmi_transaction::context, tcmi_transaction::flags, tcmi_transaction::id, mdbg, minfo, tcmi_transaction::node, tcmi_transaction::ref_count, tcmi_transaction::resp_id, tcmi_transaction::slot, tcmi_transaction::state, tcmi_transaction::t_lock, tcmi_slotvec_hashmask(), tcmi_slotvec_insert_at(), tcmi_transaction_gen_id(), tcmi_transaction_id(), TCMI_TRANSACTION_INIT, tcmi_transaction_timer(), tcmi_transaction::timer, tcmi_transaction::transactions, and tcmi_transaction::wq.
Referenced by tcmi_msg_init_tx().
 {
     struct tcmi_transaction *trans;
     /* hash of the transaction ID */
     u_int hash;
     if (!(trans = kmalloc(sizeof(struct tcmi_transaction), GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for a transaction");
         goto exit0;
     }
     tcmi_transaction_gen_id(trans);
     hash = tcmi_transaction_hash(trans->id, tcmi_slotvec_hashmask(transactions));
     trans->resp_id = resp_id;
     trans->state = TCMI_TRANSACTION_INIT;
     trans->transactions = transactions;
     init_waitqueue_head(&trans->wq);
     /* setup the timer that handles transaction timeout */
     init_timer(&trans->timer);
     /* the expiration has to be added the current value of jiffies
      * when the timer is started, but this is upon transaction start */
     trans->timer.expires = timeout;
     trans->timer.data = (unsigned long) trans;
     trans->timer.function = tcmi_transaction_timer;
     /* context will be filled in upon response arrival */
     trans->context = NULL;
     /* one reference goes the the transaction instantiator */
     atomic_set(&trans->ref_count, 1);
     atomic_set(&trans->flags, 0);
     spin_lock_init(&trans->t_lock);
     /* now, the transaction is ready to be inserted into the slot vector */
     if (!(trans->slot = tcmi_slotvec_insert_at(transactions, hash, &trans->node))) {
         minfo(ERR3, "Can't insert transaction into slot vector!");
         goto exit1;
     }
     mdbg(INFO4, "Allocated transaction ID=%x, memory=%p",
          tcmi_transaction_id(trans), trans);
     return trans;
     /* error handling */
  exit1:
     kfree(trans);
  exit0:
     return NULL;
 }
void tcmi_transaction_put (struct tcmi_transaction * self)
<<public>> Releases the instance - serialized version.
<<public>> Releases the instance - serialized version.
Decrements reference counter and if it reaches 0, the transaction is removed from its slot and freed.
Parameters
*self - pointer to this instance
Definition at line 328 of file tcmi_transaction.c.
References mdbg, self, tcmi_slot_remove(), tcmi_slotvec_lock(), tcmi_slotvec_unlock(), and tcmi_transaction_id().
Referenced by tcmi_msg_put(), tcmi_transaction_abort(), tcmi_transaction_complete(), and tcmi_transaction_timer().
 {
     struct tcmi_slotvec *transactions;
     if ( !self )
         return;
     transactions = self->transactions;
     // Transactions slotvec lock used to guard against lookup/put races
     tcmi_slotvec_lock(transactions);
     if (self && atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying transaction ID=%x, memory=%p",
              tcmi_transaction_id(self), self);
         tcmi_slot_remove(self->slot, &self->node);
         kfree(self);
     }
     tcmi_slotvec_unlock(transactions);
 }
static void tcmi_transaction_set_flags (struct tcmi_transaction * self, int flags) inline static
<<public>> Sets flags in the transaction that denote additional transaction attributes.
Valid flags are:
TCMI_TRANS_FLAGS_DELETED - transaction marked for deletion
TCMI_TRANS_FLAGS_ANONYMOUS - transaction is anonymous,
TCMI_TRANS_FLAGS_EXPIRED - timer has expired.
Parameters
*self - pointer to this transaction instance
flags - additional flag setting
Definition at line 253 of file tcmi_transaction.h.
References self.
Referenced by tcmi_transaction_start().
 {
     atomic_set_mask(flags, &self->flags);
 }
int tcmi_transaction_start (struct tcmi_transaction * self, int flags)
<<public>> Starts a transaction.
The transaction is started only if it is in INIT state. The timer is started, so that a timeout can be handled automatically. The timer is assigned an extra reference for the transaction to prevent destruction of the transaction before the timer goes off in case of timeout.
Parameters
*self - this transaction instance
flags - flags to be set on the running transaction
Returns
0 upon successful start of the transaction
Definition at line 130 of file tcmi_transaction.c.
References mdbg, self, tcmi_transaction_get(), TCMI_TRANSACTION_INIT, tcmi_transaction_lock(), TCMI_TRANSACTION_RUNNING, tcmi_transaction_set_flags(), and tcmi_transaction_unlock().
Referenced by tcmi_msg_send().
 {
     int err = 0;
     tcmi_transaction_lock(self);
     if (self->state != TCMI_TRANSACTION_INIT) {
         mdbg(ERR3, "Can't start - transaction (ID=%x),"
              " not in INIT state! state=%d", self->id, self->state);
         err = -EINVAL;
         goto exit0;
     }
     /* reference counter for the timer */
     tcmi_transaction_get(self);
     tcmi_transaction_set_flags(self, flags);
     self->timer.expires += jiffies;
     self->state = TCMI_TRANSACTION_RUNNING;
     mdbg(INFO3, "Starting transaction ID %x, response ID %x",
          self->id, self->resp_id);
     add_timer(&self->timer);
  exit0:
     tcmi_transaction_unlock(self);
     return err;
 }
static tcmi_trans_state_t tcmi_transaction_state (struct tcmi_transaction * self) inline static
<<public>> Transaction state accessor.
The transaction should be locked by the caller, so that the transaction state doesn't change when making decisions based on it.
Parameters
*self - pointer to this transaction instance
Returns
curren transaction state
Definition at line 226 of file tcmi_transaction.h.
Referenced by tcmi_transaction_complete(), tcmi_transaction_wait(), and tcmi_transaction_wait_interruptible().
 {
     return self->state;
 }
static void tcmi_transaction_timer (unsigned long trans) static
<<private>> Callback for the kernel timer that handles transaction timeouts.
This method is called upon timer expiration and means that no response has arrived so far, the transaction needs to be aborted. Expired flag is set to indicate that the timer has executed. This means that the 'complete' or 'abort' operations won't try to release the timer reference.
Also, the thread that handles the transaction is woken up.
Other transaction operations (complete, abort) are serialized with this method by means of del_timer_sync() - they cannot proceed any further until this method finishes.
Parameters
trans - pointer to the transaction instance
Definition at line 387 of file tcmi_transaction.c.
References mdbg, self, tcmi_transaction::state, TCMI_TRANSACTION_ABORTED, and tcmi_transaction_put().
Referenced by tcmi_transaction_new().
 {
     struct tcmi_transaction *self = (struct tcmi_transaction*) trans;
     self->state = TCMI_TRANSACTION_ABORTED;
     mdbg(INFO3, "Transaction ID %x expired, aborting..", self->id);
     tcmi_transaction_set_expired(self);
     tcmi_transaction_notify_owner(self);
     tcmi_transaction_put(self);
 }
static void tcmi_transaction_unlock (struct tcmi_transaction * self) inline static
<<public>> Unlocks the instance data
Parameters
*self - pointer to this transaction instance
Definition at line 184 of file tcmi_transaction.h.
References self.
Referenced by tcmi_transaction_abort(), tcmi_transaction_complete(), and tcmi_transaction_start().
 {
     spin_unlock(&self->t_lock);
 }
static int tcmi_transaction_wait (struct tcmi_transaction * self) inline static
<<public>> Waits on a transaction till it expires or is completed.
Parameters
*self - pointer to this transaction instance
Returns
transaction status
Definition at line 310 of file tcmi_transaction.h.
References self, tcmi_transaction_is_aborted(), tcmi_transaction_is_complete(), and tcmi_transaction_state().
 {
     int ret;
     /* Sleep until the transaction times out or completes (response arrival) */
     wait_event(self->wq, (tcmi_transaction_is_aborted(self) ||
                   tcmi_transaction_is_complete(self)));
     ret = tcmi_transaction_state(self);
     return ret;
 }
static int tcmi_transaction_wait_interruptible (struct tcmi_transaction * self) inline static
<<public>> Waits on a transaction till it expires or is completed, the task can be prematurely woken up by a signal.
Parameters
*self - pointer to this transaction instance
Returns
transaction status or -ERESTARTSYS on signal arrival
Definition at line 328 of file tcmi_transaction.h.
References mdbg, self, tcmi_transaction_is_aborted(), tcmi_transaction_is_complete(), and tcmi_transaction_state().
Referenced by tcmi_msg_send_and_receive().
 {
     int ret = 0;
     /* Sleep until the transaction times out or completes (response arrival) */
     ret = wait_event_interruptible(self->wq, (tcmi_transaction_is_aborted(self) ||
                           tcmi_transaction_is_complete(self)));
     if (ret < 0)
         mdbg(INFO3, "Signal arrived");
     else
         ret = tcmi_transaction_state(self);
     return ret;
 }