Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/task/tcmi_task.h File Reference
tcmi_task.h File Reference
#include <asm/atomic.h>
#include <linux/types.h>
#include <linux/completion.h>
#include <clondike/tcmi/tcmi_struct.h>
#include "tcmi_method_wrapper.h"
#include <tcmi/ctlfs/tcmi_ctlfs.h>
#include <tcmi/ctlfs/tcmi_ctlfs_dir.h>
#include <tcmi/ctlfs/tcmi_ctlfs_file.h>
#include <tcmi/ctlfs/tcmi_ctlfs_symlink.h>
#include <kkc/kkc.h>
#include <tcmi/lib/tcmi_queue.h>
#include <tcmi/lib/tcmi_slotvec.h>
#include <tcmi/comm/tcmi_msg.h>
#include <arch/current/make_syscall.h>
#include <tcmi/lib/util.h>
#include <linux/sched.h>
Data Structures
struct tcmi_task
Compound structure that gathers necessary process information.
struct tcmi_task_ops
TCMI task operations that support polymorphism.
Macros
#define TCMI_TASK(t) ((struct tcmi_task*)t)
Casts to the task instance.
Enumerations
enum tcmi_task_method_status_t {
TCMI_TASK_KEEP_PUMPING, TCMI_TASK_MOVE_ME, TCMI_TASK_EXECVE_FAILED_KILL_ME, TCMI_TASK_KILL_ME,
TCMI_TASK_LET_ME_GO, TCMI_TASK_REMOVE_AND_LET_ME_GO, TCMI_TASK_KEEP_PUMPING, TCMI_TASK_MOVE_ME,
TCMI_TASK_EXECVE_FAILED_KILL_ME, TCMI_TASK_KILL_ME, TCMI_TASK_LET_ME_GO, TCMI_TASK_REMOVE_AND_LET_ME_GO
}
Describes the status returned by task methods that are executed from the method queue.
Functions
int tcmi_task_init (struct tcmi_task *self, pid_t local_pid, struct tcmi_migman *migman, struct kkc_sock *sock, struct tcmi_ctlfs_entry *d_migproc, struct tcmi_ctlfs_entry *d_migman, struct tcmi_task_ops *ops)
Initializes the task.
static struct tcmi_task * tcmi_task_get (struct tcmi_task *self)
<<public>> Instance accessor, increments the reference counter.
void tcmi_task_put (struct tcmi_task *self)
<<public>> Releases the instance.
void tcmi_task_submit_method (struct tcmi_task *self, tcmi_method_t *method, void *data, int size)
<<public>> Submits a method for execution.
void tcmi_task_flush_and_submit_method (struct tcmi_task *self, tcmi_method_t *method, void *data, int size)
<<public>> Prior to submitting, atomically flushes the method queue.
int tcmi_task_process_methods (struct tcmi_task *self)
<<public>> Processes all methods in the queue.
int tcmi_task_process_msg (void *self, struct tcmi_method_wrapper *wr)
<<public>> Processes message in the message queue.
int tcmi_task_send_message (void *self, struct tcmi_method_wrapper *wr)
<<public>> Sends a message to peer.
int tcmi_task_emigrate_ppm_p (void *self, struct tcmi_method_wrapper *wr)
<<public>> Emigrates a task to a PEN - PPM w/ physical checkpoint.
int tcmi_task_migrateback_ppm_p (void *self, struct tcmi_method_wrapper *wr)
<<public>> Migrates a task back to CCN - PPM w/ physical checkpoint.
int tcmi_task_emigrate_ppm_v (void *self, struct tcmi_method_wrapper *wr)
<<public>> Emigrates a task to a PEN - PPM w/ virtual checkpoint.
int tcmi_task_migrateback_ppm_v (void *self, struct tcmi_method_wrapper *wr)
<<public>> Migrates a task back to CCN - PPM w/ virtual checkpoint.
int tcmi_task_emigrate_npm (void *self, struct tcmi_method_wrapper *wr)
<<public>> Emigrates a task to a PEN - NPM.
int tcmi_task_migrateback_npm (void *self, struct tcmi_method_wrapper *wr)
<<public>> Migrates a task back to CCN - NPM.
int tcmi_task_exit (void *self, struct tcmi_method_wrapper *wr)
<<public>> Exits a task.
int tcmi_task_prepare_execve (struct tcmi_task *self, char *file, char **argv, char **envp)
<<public>> Prepares execution of a file given the arrays of arguments and environment.
int tcmi_task_execve (void *self, struct tcmi_method_wrapper *wr)
<<public>> Executes the file that has been previously setup for execution.
int tcmi_task_deliver_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<public>> Delivers a specified message.
static struct tcmi_slotvec * tcmi_task_transactions (struct tcmi_task *self)
<<public>> Transactions accessor - needed when tasks construct their own messages.
static long tcmi_task_exit_code (struct tcmi_task *self)
<<public>> Exit code accessor.
static void tcmi_task_set_exit_code (struct tcmi_task *self, long code)
<<public>> Exit code setter.
static void * tcmi_task_context (struct tcmi_task *self)
<<public>> Process context accessor.
static void tcmi_task_set_context (struct tcmi_task *self, void *context)
<<public>> Process context setter.
static char * tcmi_task_ckpt_name (struct tcmi_task *self)
<<public>> Task checkpoint pathname accessor.
static pid_t tcmi_task_local_pid (struct tcmi_task *self)
<<public>> Local PID accessor.
static pid_t tcmi_task_remote_pid (struct tcmi_task *self)
<<public>> Remote PID accessor.
static void tcmi_task_set_local_pid (struct tcmi_task *self, pid_t local_pid)
<<public>> Local PID setter.
static int tcmi_task_show_remote_pid_rev (void *obj, void *data)
static void tcmi_task_set_remote_pid (struct tcmi_task *self, pid_t remote_pid)
<<public>> Remote PID setter.
u_int32_t tcmi_task_migman_id (struct tcmi_task *self)
<<public>> Accessor of id of the migration manager associated with this task.
u_int tcmi_task_migman_slot_index (struct tcmi_task *self)
<<public>> Accessor of vector slot index of the migration manager associated with this task.
static unsigned long tcmi_task_wait_for_pick_up_timeout (struct tcmi_task *self, unsigned long timeout)
<<public>> Waits until the task is picked up, by the associated process.
static void tcmi_task_pick_up (struct tcmi_task *self)
<<public>> Signals, the tcmi task has been pickedup by the associated process.n
static int tcmi_task_picked_up (struct tcmi_task *self)
<<public>> Checks whether the task has been picked up.
static int tcmi_task_send_anonymous_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<public>> Sends a specified message.
static int tcmi_task_get_execve_count (struct tcmi_task *self)
static void tcmi_task_inc_execve_count (struct tcmi_task *self)
static struct task_struct * tcmi_task_to_task_struct (struct tcmi_task *self)
Returns a task_struct associated with the tcmi_task.
static int tcmi_task_send_and_receive_msg (struct tcmi_task *self, struct tcmi_msg *req, struct tcmi_msg **resp)
<<public>> Sends a specified message and waits for a response.
static void tcmi_task_signal_peer_lost (struct tcmi_task *self)
Notifies task that it peer is lost and sends a kill signal to that task.
static int tcmi_task_do_signal (struct tcmi_task *self, unsigned long signr, siginfo_t *info)
<<public>> Processes a specified signal.
static enum tcmi_task_type tcmi_task_get_type (struct tcmi_task *self)
<<public>> Get task type
static u_int tcmi_task_hash (pid_t local_pid, u_int hashmask)
<<public>> Computes the hash value of the task (to be used in tasks slotvec of migman)
static int tcmi_task_check_peer_lost (struct tcmi_task *self, int err)
Simple error checking method to be used after communication operations to detect lost peer.
Function Documentation
static int tcmi_task_check_peer_lost (struct tcmi_task * self, int err) inline static
Simple error checking method to be used after communication operations to detect lost peer.
In case err indicates broken connection, peer is considered dead for us.
Returns
Returns passed err param, so that it can be easily used for call chaining
Definition at line 648 of file tcmi_task.h.
References tcmi_task_signal_peer_lost().
{
       // For now, we react only on broken pipe, but we may react on more cases, right?
       if ( err == -EPIPE )
       tcmi_task_signal_peer_lost(self);
       return err;
 }
static char* tcmi_task_ckpt_name (struct tcmi_task * self) inline static
<<public>> Task checkpoint pathname accessor.
Parameters
*self - pointer to this task instance
Returns
the most recent checkpoint pathname.
Definition at line 400 of file tcmi_task.h.
 {
     return self->ckpt_pathname;
 }
static void* tcmi_task_context (struct tcmi_task * self) inline static
<<public>> Process context accessor.
Parameters
*self - pointer to this task instance
Returns
process context.
Definition at line 378 of file tcmi_task.h.
 {
     return self->context;
 }
static int tcmi_task_do_signal (struct tcmi_task * self, unsigned long signr, siginfo_t * info) inline static
<<public>> Processes a specified signal.
The work is delegated to the task specific method if one is specified. This allows the shadow and guest processes to handle the signal differently. In fact, they have to: - shadow process takes appropriate actions and forwards the signal to the guest using signal forwarding component(since the guest might not be in migration mode) - guest process takes only appropriate actions and is able to communicate with the shadow directly.
Parameters
*self - pointer to this task instance
signr - signal that is to be processed
*info - info for signal to be processed
Returns
result of the task specific signal handling method or TCMI_TASK_KEEP_PUMPING
Definition at line 599 of file tcmi_task.h.
References mdbg, self, TCMI_TASK_KEEP_PUMPING, and TCMI_TASK_KILL_ME.
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     mdbg(INFO2, "Processing signal %lu", signr);
     if ( self->peer_lost && signr == SIGKILL ) {
         mdbg(INFO2, "Peer task is dead, killing current task");
         return TCMI_TASK_KILL_ME;
     }
     if (self->ops->do_signal)
         res = self->ops->do_signal(self, signr, info);
     return res;
 }
static long tcmi_task_exit_code (struct tcmi_task * self) inline static
<<public>> Exit code accessor.
Parameters
*self - pointer to this task instance
Returns
task exit code.
Definition at line 356 of file tcmi_task.h.
 {
     return self->exit_code;
 }
static struct tcmi_task* tcmi_task_get (struct tcmi_task * self) static read
<<public>> Instance accessor, increments the reference counter.
Parameters
*self - pointer to this task instance
Returns
tcmi_task instance
Definition at line 275 of file tcmi_task.h.
References self.
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static int tcmi_task_get_execve_count (struct tcmi_task * self) inline static
Definition at line 529 of file tcmi_task.h.
 {
     return self->execve_count;
 }
static enum tcmi_task_type tcmi_task_get_type (struct tcmi_task * self) inline static
<<public>> Get task type
Parameters
*self - pointer to this task instance
Returns
(tcmi_task_type)shadow or (tcmi_task_type)guest (or unresolved if not defined).
Definition at line 624 of file tcmi_task.h.
References self.
 {
     enum tcmi_task_type res = unresolved_type;
     if (self->ops->get_type)
         res = self->ops->get_type();
     return res;
 }
static u_int tcmi_task_hash (pid_t local_pid, u_int hashmask) inline static
<<public>> Computes the hash value of the task (to be used in tasks slotvec of migman)
Parameters
local_pid - local pid of the task
hashmask - hashmask limiting the maximum hash value.
Definition at line 638 of file tcmi_task.h.
 {
     return (local_pid & hashmask);
 }
static void tcmi_task_inc_execve_count (struct tcmi_task * self) inline static
Definition at line 535 of file tcmi_task.h.
 {
     self->execve_count++;
 }
static pid_t tcmi_task_local_pid (struct tcmi_task * self) inline static
<<public>> Local PID accessor.
Parameters
*self - pointer to this task instance
Returns
local PID of the task
Definition at line 411 of file tcmi_task.h.
Referenced by tcmi_task_show_remote_pid_rev(), and tcmi_task_to_task_struct().
 {
     return self->local_pid;
 }
static void tcmi_task_pick_up (struct tcmi_task * self) inline static
<<public>> Signals, the tcmi task has been pickedup by the associated process.n
Parameters
*self - pointer to this task instance
Returns
0 when successfully completed
Definition at line 496 of file tcmi_task.h.
References self.
 {
     complete(&self->picked_up);
     self->picked_up_flag = 1;
 }
static int tcmi_task_picked_up (struct tcmi_task * self) inline static
<<public>> Checks whether the task has been picked up.
Parameters
*self - pointer to this task instance
Returns
true when it has already been picked up
Definition at line 509 of file tcmi_task.h.
 {
     return self->picked_up_flag > 0;
 }
static pid_t tcmi_task_remote_pid (struct tcmi_task * self) inline static
<<public>> Remote PID accessor.
Parameters
*self - pointer to this task instance
Returns
remote PID of the task
Definition at line 422 of file tcmi_task.h.
 {
     return self->remote_pid;
 }
static int tcmi_task_send_and_receive_msg (struct tcmi_task * self, struct tcmi_msg * req, struct tcmi_msg ** resp) inline static
<<public>> Sends a specified message and waits for a response.
All work is delegate to tcmi_msg.c::tcmi_msg_send_and_receive() method
Parameters
*self - pointer to this task instance
*req - request message to be sent.
**resp - output parameter, stores the response message or NULL
Returns
0 when the message has been sent.
Definition at line 567 of file tcmi_task.h.
References self, and tcmi_msg_send_and_receive().
 {
     return tcmi_msg_send_and_receive(req, self->sock, resp);
 }
static int tcmi_task_send_anonymous_msg (struct tcmi_task * self, struct tcmi_msg * m) inline static
<<public>> Sends a specified message.
The message is sent as anonymous, so that any potential responses will be delivered to the message queue.
Parameters
*self - pointer to this task instance
*m - message to be sent.
Returns
0 when the message has been successfully sent
Definition at line 524 of file tcmi_task.h.
References self, and tcmi_msg_send_anonymous().
 {
     return tcmi_msg_send_anonymous(m, self->sock);
 }
static void tcmi_task_set_context (struct tcmi_task * self, void * context) inline static
<<public>> Process context setter.
Parameters
*self - pointer to this task instance
*context - pointer to the context stored in the task
Definition at line 389 of file tcmi_task.h.
 {
     self->context = context;
 }
static void tcmi_task_set_exit_code (struct tcmi_task * self, long code) inline static
<<public>> Exit code setter.
Parameters
*self - pointer to this task instance
code - exit code that is to be set for the task
Definition at line 367 of file tcmi_task.h.
 {
     self->exit_code = code;
 }
static void tcmi_task_set_local_pid (struct tcmi_task * self, pid_t local_pid) inline static
<<public>> Local PID setter.
Parameters
*self - pointer to this task instance
local_pid - new local PID of the task
Definition at line 433 of file tcmi_task.h.
 {
     self->local_pid = local_pid;
 }
static void tcmi_task_set_remote_pid (struct tcmi_task * self, pid_t remote_pid) inline static
<<public>> Remote PID setter.
Parameters
*self - pointer to this task instance
remote_pid - new remote PID of the task
Definition at line 453 of file tcmi_task.h.
References tcmi_task::remote_pid, self, tcmi_ctlfs_intfile_new(), TCMI_PERMS_FILE_R, and tcmi_task_show_remote_pid_rev().
 {
     self->remote_pid = remote_pid;
     self->f_remote_pid_rev = tcmi_ctlfs_intfile_new(self->d_migman_root, TCMI_PERMS_FILE_R,
                                      self, tcmi_task_show_remote_pid_rev, NULL,
                                      sizeof(pid_t),"%d" , self->remote_pid);
 }
static int tcmi_task_show_remote_pid_rev (void * obj, void * data) static
Definition at line 439 of file tcmi_task.h.
References tcmi_task::local_pid, TCMI_TASK, and tcmi_task_local_pid().
Referenced by tcmi_task_set_remote_pid().
 {
     struct tcmi_task *self = TCMI_TASK(obj);
     int * local_pid = (int*) data;
     *local_pid = tcmi_task_local_pid(self);
     return 0;
 }
static void tcmi_task_signal_peer_lost (struct tcmi_task * self) inline static
Notifies task that it peer is lost and sends a kill signal to that task.
The method is used for termination of tasks with lost peers.
Definition at line 577 of file tcmi_task.h.
References tcmi_task_to_task_struct().
Referenced by tcmi_task_check_peer_lost().
{
       self->peer_lost = 1;
       force_sig(SIGKILL, tcmi_task_to_task_struct(self));
 }
static struct task_struct* tcmi_task_to_task_struct (struct tcmi_task * self) static read
Returns a task_struct associated with the tcmi_task.
Definition at line 542 of file tcmi_task.h.
References mdbg, task_find_by_pid(), and tcmi_task_local_pid().
Referenced by tcmi_task_signal_peer_lost().
{
     struct task_struct *task;
     /* try finding the target kernel task for our TCMI task by PID */
     read_lock_irq(&tasklist_lock);
     if (!(task = task_find_by_pid(tcmi_task_local_pid(self)))) {
         mdbg(ERR3, "Can't find corresponding task_struct for PID: %d",
              tcmi_task_local_pid(self));
     }
     read_unlock_irq(&tasklist_lock);
     return task;
 }
static struct tcmi_slotvec* tcmi_task_transactions (struct tcmi_task * self) static read
<<public>> Transactions accessor - needed when tasks construct their own messages.
Parameters
*self - pointer to this task instance
Returns
transactions slot vector.
Definition at line 344 of file tcmi_task.h.
 {
     return self->transactions;
 }
static unsigned long tcmi_task_wait_for_pick_up_timeout (struct tcmi_task * self, unsigned long timeout) inline static
<<public>> Waits until the task is picked up, by the associated process.
Returns also when the timer expires. This method is meant to be used by the task helper, that provides tcmi_taskhelper_wait_for_pickup_timeout() .
Parameters
*self - pointer to this task instance
timeout - time out limit in ticks to wait for pickup
Returns
0 when successfully completed
Definition at line 483 of file tcmi_task.h.
References self.
 {
     return wait_for_completion_interruptible_timeout(&self->picked_up, timeout);
 }