Clondike: tcmi_p_emigrate_msg class
tcmi_p_emigrate_msg class
tcmi_msg class
This class represents a message for preemptive/non-preemtive process migration via a physical checkpoint image.
Data Structures
struct tcmi_p_emigrate_msg
Compound structure, inherits from tcmi_msg_class.
Macros
#define TCMI_P_EMIGRATE_MSG_DSC TCMI_MSG_DSC(TCMI_P_EMIGRATE_MSG_ID, tcmi_p_emigrate_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
#define TCMI_P_EMIGRATE_MSGTIMEOUT (10*HZ)
Response time out is set to 10 seconds.
#define TCMI_P_EMIGRATE_MSG(m) ((struct tcmi_p_emigrate_msg*)m)
Casts to the tcmi_p_emigrate_msg instance.
Functions
static int tcmi_p_emigrate_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_p_emigrate_msg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Sends the physical emigration message
static void tcmi_p_emigrate_msg_free (struct tcmi_msg *self)
<<private>> Frees custom message resources.
struct tcmi_msg * tcmi_p_emigrate_msg_new_rx (u_int32_t msg_id)
<<public>> Phys.
struct tcmi_msg * tcmi_p_emigrate_msg_new_tx (struct tcmi_slotvec *transactions, pid_t reply_pid, char *exec_name, char *ckpt_name, int16_t euid, int16_t egid, int16_t fsuid, int16_t fsgid)
<<public>> Phys.
static pid_t tcmi_p_emigrate_msg_reply_pid (struct tcmi_p_emigrate_msg *self)
<<public>> Remote PID accessor.
static char * tcmi_p_emigrate_msg_exec_name (struct tcmi_p_emigrate_msg *self)
<<public>> Executable name accessor.
static char * tcmi_p_emigrate_msg_ckpt_name (struct tcmi_p_emigrate_msg *self)
<<public>> Checkpoint name accessor.
static int16_t tcmi_p_emigrate_msg_fsuid (struct tcmi_p_emigrate_msg *self)
<<public>> Fsuid accesses
static int16_t tcmi_p_emigrate_msg_fsgid (struct tcmi_p_emigrate_msg *self)
<<public>> Fsgid accesses
static int16_t tcmi_p_emigrate_msg_euid (struct tcmi_p_emigrate_msg *self)
<<public>> Fsuid accesses
static int16_t tcmi_p_emigrate_msg_egid (struct tcmi_p_emigrate_msg *self)
<<public>> Fsgid accesses
Variables
static struct tcmi_msg_ops p_emigrate_msg_ops
Message operations that support polymorphism.
struct tcmi_p_emigrate_msg __attribute__
Detailed Description
This class represents a message for preemptive/non-preemtive process migration via a physical checkpoint image.
The migrating process sends this message to the PEN, that is responsible for creation of a guest process and finishing the migration. Should the migration fail, an error is generated and sent back as a reply. This is a migration control message that will be received by the migration manager and passed onto the newly created guest. The response to this message is however a process control message (TCMI_GUEST_STARTED_PROCMSG) that will be directly routed to the sending task.
The sending task specifies it's PID, so that the receiving guest can use it for further communication via process control connection. Also, the checkpoint file name is specified as part of the message.
Data Structure Documentation
struct tcmi_p_emigrate_msg
Compound structure, inherits from tcmi_msg_class.
Definition at line 59 of file tcmi_p_emigrate_msg.h.
Public Member Functions
struct {
pid_t reply_pid
remote PID, used for further communication.
int32_t size
size of the checkpoint name in bytes (including trailing zero)
int32_t exec_name_size
size of the exec name in bytes (including trailing zero)
int16_t euid
effective user id of a process as seen by the node where it is running
int16_t egid
effective group id of a process as seen by the node where it is running
int16_t fsuid
fsuid of the process on the core node.
int16_t fsgid
fsgid of the process on the core node.
} __attribute__ ((__packed__))
Data Fields
struct tcmi_msg super
parent class instance.
char * exec_name
name of the executable of the process.
char * ckpt_name
name of the checkpoint file.
Member Function Documentation
struct tcmi_p_emigrate_msg::@7 tcmi_p_emigrate_msg::__attribute__ ((__packed__))
Field Documentation
char* tcmi_p_emigrate_msg::ckpt_name
name of the checkpoint file.
Definition at line 85 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_p_emigrate_msg_free(), tcmi_p_emigrate_msg_new_tx(), tcmi_p_emigrate_msg_recv(), and tcmi_p_emigrate_msg_send().
char* tcmi_p_emigrate_msg::exec_name
name of the executable of the process.
Definition at line 83 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_p_emigrate_msg_free(), tcmi_p_emigrate_msg_new_tx(), tcmi_p_emigrate_msg_recv(), and tcmi_p_emigrate_msg_send().
struct tcmi_msg tcmi_p_emigrate_msg::super
parent class instance.
Definition at line 61 of file tcmi_p_emigrate_msg.h.
Macro Definition Documentation
#define TCMI_P_EMIGRATE_MSG (m) ((struct tcmi_p_emigrate_msg*)m)
Casts to the tcmi_p_emigrate_msg instance.
Definition at line 106 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_guesttask_process_p_emigrate_msg(), tcmi_migcom_immigrate(), tcmi_p_emigrate_msg_free(), tcmi_p_emigrate_msg_new_rx(), tcmi_p_emigrate_msg_new_tx(), tcmi_p_emigrate_msg_recv(), tcmi_p_emigrate_msg_send(), and tcmi_penmigman_process_msg().
#define TCMI_P_EMIGRATE_MSG_DSC TCMI_MSG_DSC(TCMI_P_EMIGRATE_MSG_ID, tcmi_p_emigrate_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
Definition at line 101 of file tcmi_p_emigrate_msg.h.
#define TCMI_P_EMIGRATE_MSGTIMEOUT (10*HZ)
Response time out is set to 10 seconds.
Definition at line 103 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_p_emigrate_msg_new_tx().
Function Documentation
static char* tcmi_p_emigrate_msg_ckpt_name (struct tcmi_p_emigrate_msg * self) inline static
<<public>> Checkpoint name accessor.
Parameters
*self - this message instance
Returns
checkpoint name string
Definition at line 136 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_guesttask_process_p_emigrate_msg().
 {
     return self->ckpt_name;
 }
static int16_t tcmi_p_emigrate_msg_egid (struct tcmi_p_emigrate_msg * self) inline static
<<public>> Fsgid accesses
Parameters
*self - this message instance
Returns
egid
Definition at line 180 of file tcmi_p_emigrate_msg.h.
 {
     return self->pid_and_size.egid;
 }
static int16_t tcmi_p_emigrate_msg_euid (struct tcmi_p_emigrate_msg * self) inline static
<<public>> Fsuid accesses
Parameters
*self - this message instance
Returns
euid
Definition at line 169 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_migcom_immigrate().
 {
     return self->pid_and_size.euid;
 }
static char* tcmi_p_emigrate_msg_exec_name (struct tcmi_p_emigrate_msg * self) inline static
<<public>> Executable name accessor.
Parameters
*self - this message instance
Returns
executable name string
Definition at line 125 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_migcom_immigrate().
 {
     return self->exec_name;
 }
static void tcmi_p_emigrate_msg_free (struct tcmi_msg * self) static
<<private>> Frees custom message resources.
The checkpoint image name string is released from memory.
Parameters
*self - this message instance
Definition at line 264 of file tcmi_p_emigrate_msg.c.
References tcmi_p_emigrate_msg::ckpt_name, tcmi_p_emigrate_msg::exec_name, mdbg, and TCMI_P_EMIGRATE_MSG.
 {
     struct tcmi_p_emigrate_msg *self_msg = TCMI_P_EMIGRATE_MSG(self);
     mdbg(INFO3, "Freeing physical emigrate message PID=%d, size=%d, ckptname='%s'",
          self_msg->pid_and_size.reply_pid, self_msg->pid_and_size.size, self_msg->ckpt_name);
     kfree(self_msg->ckpt_name);
     kfree(self_msg->exec_name);
 }
static int16_t tcmi_p_emigrate_msg_fsgid (struct tcmi_p_emigrate_msg * self) inline static
<<public>> Fsgid accesses
Parameters
*self - this message instance
Returns
fsgid
Definition at line 158 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_migcom_immigrate().
 {
     return self->pid_and_size.fsgid;
 }
static int16_t tcmi_p_emigrate_msg_fsuid (struct tcmi_p_emigrate_msg * self) inline static
<<public>> Fsuid accesses
Parameters
*self - this message instance
Returns
fsuid
Definition at line 147 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_migcom_immigrate().
 {
     return self->pid_and_size.fsuid;
 }
struct tcmi_msg* tcmi_p_emigrate_msg_new_rx (u_int32_t msg_id) read
<<public>> Phys.
emigrate message constructor for receiving.
<<public>> Phys.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this error message instance.
Returns
a new error message or NULL.
Definition at line 53 of file tcmi_p_emigrate_msg.c.
References mdbg, p_emigrate_msg_ops, TCMI_MSG, tcmi_msg_init_rx(), TCMI_P_EMIGRATE_MSG, and TCMI_P_EMIGRATE_MSG_ID.
 {
     struct tcmi_p_emigrate_msg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_P_EMIGRATE_MSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_P_EMIGRATE_MSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_P_EMIGRATE_MSG(kmalloc(sizeof(struct tcmi_p_emigrate_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate test request message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_P_EMIGRATE_MSG_ID, &p_emigrate_msg_ops)) {
         mdbg(ERR3, "Error initializing test request message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_p_emigrate_msg_new_tx (struct tcmi_slotvec * transactions, pid_t reply_pid, char * exec_name, char * ckpt_name, int16_t euid, int16_t egid, int16_t fsuid, int16_t fsgid) read
<<public>> Phys.
emigrate message constructor for transferring.
<<public>> Phys.
An emigration message expects a response that will be delivered back to the originating task (usually a shadow process on CCN). Therefore, there has to be a transaction associated with it.
Response message ID is TCMI_GUEST_STARTED_PROCMSG_ID.
Parameters
*transactions - storage for the new transaction
reply_pid - denotes the pid that the reply to this message should be directed to. It is a key information for the receiving party in order to compose a valid response
ckpt_name - checkpoint pathname - this has to be a valid location in the network filesystem, so that the receiving party can restart the process
Returns
a new error ready for the transfer or NULL.
Definition at line 102 of file tcmi_p_emigrate_msg.c.
References tcmi_p_emigrate_msg::ckpt_name, egid, euid, tcmi_p_emigrate_msg::exec_name, fsgid, fsuid, mdbg, p_emigrate_msg_ops, reply_pid, TCMI_GUEST_STARTED_PROCMSG_ID, TCMI_MSG, tcmi_msg_init_tx(), TCMI_P_EMIGRATE_MSG, TCMI_P_EMIGRATE_MSG_ID, TCMI_P_EMIGRATE_MSGTIMEOUT, and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_shadowtask_emigrate_p().
 {
     struct tcmi_p_emigrate_msg *msg;
     if (!(msg = TCMI_P_EMIGRATE_MSG(kmalloc(sizeof(struct tcmi_p_emigrate_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate test request message");
         goto exit0;
     }
     msg->pid_and_size.reply_pid = reply_pid;
     msg->pid_and_size.euid = euid;
     msg->pid_and_size.egid = egid;
     msg->pid_and_size.fsuid = fsuid;
     msg->pid_and_size.fsgid = fsgid;
     msg->pid_and_size.size = strlen(ckpt_name) + 1;
     msg->pid_and_size.exec_name_size = strlen(exec_name) + 1;
     if (!(msg->ckpt_name = (char*)kmalloc(msg->pid_and_size.size, GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for checkpoint name");
         goto exit1;
     }
     if (!(msg->exec_name = (char*)kmalloc(msg->pid_and_size.exec_name_size, GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for exec name");
         goto exit2;
     }
     strcpy(msg->ckpt_name, ckpt_name);
     strcpy(msg->exec_name, exec_name);
     /* Initialize the message for transfer */
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_P_EMIGRATE_MSG_ID, &p_emigrate_msg_ops,
                  transactions, TCMI_GUEST_STARTED_PROCMSG_ID,
                  TCMI_P_EMIGRATE_MSGTIMEOUT, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing test request message message");
         goto exit3;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit3:
     kfree(msg->exec_name);
  exit2:
     kfree(msg->ckpt_name);
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_p_emigrate_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the message requires reading the remote PID and checkpoint size. Based on the size, allocate space for the checkpoint name string and read it to from the specified connection
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 168 of file tcmi_p_emigrate_msg.c.
References tcmi_p_emigrate_msg::ckpt_name, tcmi_p_emigrate_msg::exec_name, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, and TCMI_P_EMIGRATE_MSG.
 {
     int err = -EINVAL;
     struct tcmi_p_emigrate_msg *self_msg = TCMI_P_EMIGRATE_MSG(self);
     /* Receive the remote PID and checkpoint name size */
     if ((err = kkc_sock_recv(sock, &self_msg->pid_and_size,
                  sizeof(self_msg->pid_and_size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive pid and size");
         goto exit0;
     }
     if (!(self_msg->ckpt_name = (char*)kmalloc(self_msg->pid_and_size.size, GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for checkpoint name");
         goto exit0;
     }
     if (!(self_msg->exec_name = (char*)kmalloc(self_msg->pid_and_size.exec_name_size, GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for checkpoint name");
         goto exit0;
     }
     /* Receive the checkpoint name */
     if ((err = kkc_sock_recv(sock, self_msg->ckpt_name,
                  self_msg->pid_and_size.size, KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive checkpoint name");
         goto exit0;
     }
     /* Receive the exec name */
     if ((err = kkc_sock_recv(sock, self_msg->exec_name,
                  self_msg->pid_and_size.exec_name_size, KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive exec name");
         goto exit0;
     }
     mdbg(INFO2, "Physical emigrate message received PID=%d, size=%d, ckptname='%s'",
          self_msg->pid_and_size.reply_pid, self_msg->pid_and_size.size, self_msg->ckpt_name);
     return 0;
     /* error handling*/
  exit0:
     return err;
 }
static pid_t tcmi_p_emigrate_msg_reply_pid (struct tcmi_p_emigrate_msg * self) inline static
<<public>> Remote PID accessor.
Parameters
*self - this message instance
Returns
remote PID
Definition at line 114 of file tcmi_p_emigrate_msg.h.
Referenced by tcmi_guesttask_process_p_emigrate_msg(), tcmi_migcom_immigrate(), and tcmi_penmigman_process_msg().
 {
     return self->pid_and_size.reply_pid;
 }
static int tcmi_p_emigrate_msg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Sends the physical emigration message
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 221 of file tcmi_p_emigrate_msg.c.
References tcmi_p_emigrate_msg::ckpt_name, tcmi_p_emigrate_msg::exec_name, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, and TCMI_P_EMIGRATE_MSG.
 {
     int err;
     struct tcmi_p_emigrate_msg *self_msg = TCMI_P_EMIGRATE_MSG(self);
     /* Receive the remote PID and checkpoint name size */
     if ((err = kkc_sock_send(sock, &self_msg->pid_and_size,
                  sizeof(self_msg->pid_and_size), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send pid and size");
         goto exit0;
     }
     /* Send the checkpoint name */
     if ((err = kkc_sock_send(sock, self_msg->ckpt_name,
                  self_msg->pid_and_size.size, KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send checkpoint name");
         goto exit0;
     }
     /* Send the exec name */
     if ((err = kkc_sock_send(sock, self_msg->exec_name,
                  self_msg->pid_and_size.exec_name_size, KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send exec name");
         goto exit0;
     }
     mdbg(INFO2, "Physical emigrate message sent PID=%d, size=%d, ckptname='%s'",
          self_msg->pid_and_size.reply_pid, self_msg->pid_and_size.size, self_msg->ckpt_name);
     return 0;
     /* error handling */
  exit0:
     return err;
 }
Variable Documentation
struct tcmi_p_emigrate_msg __attribute__
struct tcmi_msg_ops p_emigrate_msg_ops static
Initial value:
= {
    .recv = tcmi_p_emigrate_msg_recv,
    .send = tcmi_p_emigrate_msg_send,
    .free = tcmi_p_emigrate_msg_free
}
Message operations that support polymorphism.
Definition at line 276 of file tcmi_p_emigrate_msg.c.
Referenced by tcmi_p_emigrate_msg_new_rx(), and tcmi_p_emigrate_msg_new_tx().