Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ctlfs/tcmi_ctlfs.c File Reference
tcmi_ctlfs.c File Reference
#include <linux/sched.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/pagemap.h>
#include <linux/slab.h>
#include "tcmi_ctlfs_dir.h"
#include "tcmi_ctlfs.h"
#include <dbg.h>
Macros
#define TCMI_CTLFS_PRIVATE
#define TCMI_CTLFS_MAGIC 0x20050326
Magic number identifies the fs super block.
Functions
struct tcmi_ctlfs_entry * tcmi_ctlfs_get_root (void)
<<public>> Root entry accessor.
void tcmi_ctlfs_put_root (void)
<<public>> Releases the root directory and then the mount object.
static void init_once (void *foo)
static int init_inodecache (void)
static void destroy_inodecache (void)
static int tcmi_ctlfs_fill_super (struct super_block *sb, void *data, int silent)
<<private>> Sets up super block and instantiates the root directory.
static struct dentry * tcmi_ctlfs_get_super (struct file_system_type *fst, int flags, const char *devname, void *data)
<<private>> Super block as assigned a nonexistent device and the super block is obtained via mount_single().
static int __init tcmi_ctlfs_init (void)
Module initialization.
static void __exit tcmi_ctlfs_exit (void)
module cleanup
module_init (tcmi_ctlfs_init)
module_exit (tcmi_ctlfs_exit)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_get_root)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_put_root)
MODULE_LICENSE ("GPL")
MODULE_AUTHOR ("Jan Capek")
Variables
static struct kmem_cache * ctlfs_inode_cachep
static struct super_operations s_ops
static struct tcmi_ctlfs self
<<singleton>> instance initialization
Macro Definition Documentation
#define TCMI_CTLFS_MAGIC 0x20050326
Magic number identifies the fs super block.
Definition at line 48 of file tcmi_ctlfs.c.
Referenced by tcmi_ctlfs_fill_super().
#define TCMI_CTLFS_PRIVATE
Definition at line 40 of file tcmi_ctlfs.c.
Function Documentation
static void destroy_inodecache (void) static
Definition at line 192 of file tcmi_ctlfs.c.
References ctlfs_inode_cachep.
Referenced by tcmi_ctlfs_exit().
 {
     kmem_cache_destroy(ctlfs_inode_cachep);
 }
EXPORT_SYMBOL_GPL (tcmi_ctlfs_get_root)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_put_root)
static int init_inodecache (void) static
Definition at line 183 of file tcmi_ctlfs.c.
References ctlfs_inode_cachep, and init_once().
Referenced by tcmi_ctlfs_init().
 {
     ctlfs_inode_cachep = kmem_cache_create("ctlfs_inode_cache", sizeof(struct inode), 0, (SLAB_RECLAIM_ACCOUNT| SLAB_MEM_SPREAD), init_once);
     if (ctlfs_inode_cachep == NULL)
         return -ENOMEM;
     return 0;
 }
static void init_once (void * foo) static
Definition at line 151 of file tcmi_ctlfs.c.
Referenced by init_inodecache().
{
          struct inode *inode = (struct inode *) foo;
          inode_init_once(inode);
  }
MODULE_AUTHOR ("Jan Capek")
module_exit (tcmi_ctlfs_exit)
module_init (tcmi_ctlfs_init)
MODULE_LICENSE ("GPL")
static void __exit tcmi_ctlfs_exit (void) static
module cleanup
Definition at line 270 of file tcmi_ctlfs.c.
References destroy_inodecache(), and minfo.
 {
     minfo(INFO3, "Unregistering TCMI control filesystem");
     destroy_inodecache();
     unregister_filesystem(&self.fs_type);
 }
static int tcmi_ctlfs_fill_super (struct super_block * sb, void * data, int silent) static
<<private>> Sets up super block and instantiates the root directory.
This method is called only once through out the super block life.
Parameters
sb - pointer to the super block
*data - custom data supplied when reading the superblock(not used)
silent - required by VFS, no idea what it means.
Returns
0 upon success
Definition at line 215 of file tcmi_ctlfs.c.
References mdbg, s_ops, TCMI_CTLFS_MAGIC, and tcmi_ctlfs_rootdir_new().
Referenced by tcmi_ctlfs_get_super().
 {
     sb->s_blocksize = PAGE_CACHE_SIZE;
     sb->s_blocksize_bits = PAGE_CACHE_SHIFT;
     sb->s_magic = TCMI_CTLFS_MAGIC;
     sb->s_op = &s_ops;
     self.sb = sb;
 mdbg(INFO4, "TMPDBG: GOING TO REQUEST ROOT");
     self.root_dir = tcmi_ctlfs_rootdir_new(sb);
 mdbg(INFO4, "TMPDBG: ROOT SUCCEEDED");
     return 0;
 }
static int __init tcmi_ctlfs_init (void) static
Module initialization.
Returns
- status of the register_filesystem() call
Definition at line 254 of file tcmi_ctlfs.c.
References init_inodecache(), and minfo.
 {
     int error;
     minfo(INFO3, "Registering TCMI control filesystem");
     error = init_inodecache();
     if (error)
         return error;
     error = register_filesystem(&self.fs_type);
     return error;
 }