Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/manager/tcmi_migman.c File Reference
tcmi_migman.c File Reference
#include <linux/types.h>
#include <linux/random.h>
#include <linux/kthread.h>
#include <linux/string.h>
#include <linux/sched.h>
#include <tcmi/task/tcmi_taskhelper.h>
#include <tcmi/task/tcmi_task.h>
#include "tcmi_migman.h"
#include <dbg.h>
Macros
#define TCMI_MIGMAN_PRIVATE
#define TRANSACTION_ORDER 8
2^8 elements in the transaction process hash
#define TASK_ORDER 9
2^9 elements in the process hash
#define TCMI_MIGMAN_STATE_LENGTH 40
Max length of the state description.
Functions
int tcmi_migman_init (struct tcmi_migman *self, struct kkc_sock *sock, u_int32_t ccn_id, u_int32_t pen_id, enum arch_ids peer_arch_type, struct tcmi_slot *manager_slot, struct tcmi_ctlfs_entry *root, struct tcmi_ctlfs_entry *migproc, struct tcmi_migman_ops *ops, const char namefmt[], va_list args)
TCMI migration manager initializer.
int tcmi_migman_put (struct tcmi_migman *self)
<<public>> The manager is shutdown exactly in this order:
static void tcmi_migman_unhash (struct tcmi_migman *self)
Removes migman from a list of migration managers of the associated manager.
static void tcmi_migman_free (struct tcmi_migman *self)
<<private>> Free method is has two purposes:
when the last reference is released, it will free all instance resources, except for the instance itself.
void tcmi_migman_stop (struct tcmi_migman *self)
Requests asynchronous shutdown of connection with peer.
static void tcmi_migman_notify_peer_disconnect (struct tcmi_migman *self)
static int tcmi_migman_stop_perform (struct tcmi_migman *self, int remote_requested)
Actual implementation of stop, see tcmi_migman_stop.
static void kill_all_tasks (struct tcmi_migman *self)
Sends a kill signal to all tasks managed by this manager.
int tcmi_migman_kill (struct tcmi_migman *self)
Kills all tasks associated with this migman and drops reference to the migman (in case it was not already shutting down).
static int tcmi_migman_init_ctlfs_dirs (struct tcmi_migman *self, struct tcmi_ctlfs_entry *root, struct tcmi_ctlfs_entry *migproc, const char namefmt[], va_list args)
<<private>> Creates the directories as described in here .
static int tcmi_migman_init_ctlfs_files (struct tcmi_migman *self)
<<private>> Creates the static files described here .
static void tcmi_migman_stop_ctlfs_dirs (struct tcmi_migman *self)
<<private>> Destroys all TCMI ctlfs directories
static void tcmi_migman_stop_ctlfs_files (struct tcmi_migman *self)
<<private>> Unregisters and releases all control files.
static int tcmi_migman_stop_request (void *obj, void *data)
<<private>> Requests asynchronous shutdown of this migration manager
static int tcmi_migman_kill_request (void *obj, void *data)
<<private>> Requests asynchronous kill of this migration manager
static int tcmi_migman_show_state (void *obj, void *data)
<<private>> Read method for the TCMI ctlfs - reports migration manager state.
static int tcmi_migman_start_thread (struct tcmi_migman *self)
<<private>> Starts the listening thread.
static void tcmi_migman_stop_thread (struct tcmi_migman *self)
<<private>> The TCMI manager listening thread is to be terminated by forcing a signal and waiting for it to terminate.
static int tcmi_migman_deliver_msg (void *obj, struct tcmi_msg *m)
<<private>> Message delivering method that is called back from the receiving thread of TCMI comm component instance.
static int tcmi_migman_msg_thread (void *data)
<<private>> Message processing thread.
int tcmi_migman_add_task (struct tcmi_migman *self, struct tcmi_task *task)
<<public>> Registers tcmi task into the migration manager tasks slotvec
int tcmi_migman_remove_task (struct tcmi_migman *self, struct tcmi_task *task)
<<public>> Removes tcmi task from the migration manager tasks slotvec
int tcmi_migman_create_symlink (struct tcmi_migman *self, struct tcmi_ctlfs_entry *root, struct kkc_sock *sock)
Variables
static char * tcmi_migman_states []
String descriptor for the states of migration manager.
Macro Definition Documentation
#define TASK_ORDER 9
2^9 elements in the process hash
Definition at line 49 of file tcmi_migman.c.
Referenced by tcmi_migman_init().
#define TCMI_MIGMAN_PRIVATE
Definition at line 41 of file tcmi_migman.c.
#define TCMI_MIGMAN_STATE_LENGTH 40
Max length of the state description.
Definition at line 51 of file tcmi_migman.c.
Referenced by tcmi_migman_init_ctlfs_files(), and tcmi_migman_show_state().
#define TRANSACTION_ORDER 8
2^8 elements in the transaction process hash
Definition at line 47 of file tcmi_migman.c.
Referenced by tcmi_migman_init().
Function Documentation
static void kill_all_tasks (struct tcmi_migman * self) static
Sends a kill signal to all tasks managed by this manager.
Definition at line 307 of file tcmi_migman.c.
References mdbg, self, tcmi_slot_entry, tcmi_slot_for_each, tcmi_slotvec_for_each_used_slot, tcmi_slotvec_lock(), tcmi_slotvec_unlock(), tcmi_task_local_pid(), and tcmi_task_signal_peer_lost().
{
     struct tcmi_task* task;
     struct tcmi_slot *slot;
     tcmi_slot_node_t* node;
     tcmi_slotvec_lock(self->tasks);
     /* Iterate over all managed tasks */
     tcmi_slotvec_for_each_used_slot(slot, self->tasks) {
         tcmi_slot_for_each(node, slot) {
             task = tcmi_slot_entry(node, struct tcmi_task, node);
             mdbg(INFO3, "Killing task: local_pid=%d", tcmi_task_local_pid(task));
             tcmi_task_signal_peer_lost(task);
         };
     };
     tcmi_slotvec_unlock(self->tasks);
 }
static int tcmi_migman_deliver_msg (void * obj, struct tcmi_msg * m) static
<<private>> Message delivering method that is called back from the receiving thread of TCMI comm component instance.
This method is reponsible for delivering the message reliably to its destination which can be:
local migration manager message queue
local migration manager transaction slot vector
TCMI task message queue
TCMI task transaction slot vector
Parameters
*obj - pointer to the migration manager instance. passed to the TCMI comm component upon creation
*m - points to the message that is to be delivered.
Returns
0 upon successful delivery
Definition at line 604 of file tcmi_migman.c.
References mdbg, pid, self, TCMI_MIGMAN, tcmi_migman_id(), tcmi_msg_deliver(), TCMI_MSG_GROUP, TCMI_MSG_GROUP_PROC, tcmi_msg_id(), TCMI_PROCMSG, tcmi_procmsg_dst_pid(), tcmi_task_deliver_msg(), tcmi_task_local_pid(), tcmi_task_migman_id(), tcmi_task_put(), and tcmi_taskhelper_find_by_pid().
Referenced by tcmi_migman_init().
 {
     int err = 0;
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     struct tcmi_task *task;
     if (TCMI_MSG_GROUP(tcmi_msg_id(m)) == TCMI_MSG_GROUP_PROC) {
         /* try finding the task based on PID  in the message */
         pid_t pid = tcmi_procmsg_dst_pid(TCMI_PROCMSG(m));
         mdbg(INFO3, "Process message %08x arrived as expected for PID=%d",
              tcmi_msg_id(m), pid);
         /* find task by PID */
         if (!(task = tcmi_taskhelper_find_by_pid(pid))) {
             mdbg(ERR2, "Can't find dest. task for msg ID=%08x",
                  tcmi_msg_id(m));
             goto exit0;
         }
         /* Verify it belongs to us */
         if (tcmi_task_migman_id(task) != tcmi_migman_id(self)) {
             mdbg(ERR2, "Task(PID=%d, migman ID=%08x) doesn't belong"
                  "to migration manager ID=%08x", tcmi_task_local_pid(task),
                  tcmi_task_migman_id(task), tcmi_migman_id(self));
             goto exit1;
         }
         err = tcmi_task_deliver_msg(task, m);
         tcmi_task_put(task);
     }
     else {
         mdbg(INFO3, "Delivering regular migration message %08x",
              tcmi_msg_id(m));
         err = tcmi_msg_deliver(m, &self->msg_queue, self->transactions);
     }
     return err;
     /* error handling */
  exit1:
     tcmi_task_put(task);
  exit0:
     return -EINVAL;
 }
static void tcmi_migman_free (struct tcmi_migman * self) static
<<private>> Free method is has two purposes:
when the last reference is released, it will free all instance resources, except for the instance itself.
calls the child class free method if defined
Note: It is important to free communication channels first, i.e. communication socket, processing thread and files. This ensures, that no new messages that may require reference to migman for processing will arrive. File operations are synchronized with releasing so it may be possible that some file works with the migman during the free method, but only until the file is ''synchronously'' released.
Definition at line 228 of file tcmi_migman.c.
References self, tcmi_comm_put(), tcmi_migman_stop_ctlfs_dirs(), tcmi_migman_stop_ctlfs_files(), tcmi_migman_stop_thread(), tcmi_migman_unhash(), tcmi_slotvec_put(), and tcmi_sock_put().
Referenced by tcmi_migman_put().
 {
     /* terminate the processing thread first to prevent any
      * message processing */
     tcmi_migman_stop_thread(self);
     /* also stop receiving all messages */
     tcmi_comm_put(self->comm);
     tcmi_migman_stop_ctlfs_files(self);
     tcmi_migman_stop_ctlfs_dirs(self);
     tcmi_sock_put(self->sock);
     tcmi_migman_unhash(self);
     /* now we are safe and we can start cleaning the rest */
     if (self->ops->free)
         self->ops->free(self);
     /* TODO: check for stale transactions.. */
     tcmi_slotvec_put(self->transactions);
     /* Note: Assumes, all tasks are already migrated back. */
     tcmi_slotvec_put(self->tasks);
 }
static int tcmi_migman_init_ctlfs_dirs (struct tcmi_migman * self, struct tcmi_ctlfs_entry * root, struct tcmi_ctlfs_entry * migproc, const char namefmt[], va_list args) static
<<private>> Creates the directories as described in here .
Parameters
*self - pointer to this migration manager instance
*root - root directory where to create TCMI ctlfs entries
*migproc - directory where the migrated process will have their info
namefmt - nameformat string for the main manager directory name (printf style)
args - arguments to the format string
Returns
0 upon success
Definition at line 358 of file tcmi_migman.c.
References mdbg, self, tcmi_ctlfs_dir_new(), tcmi_ctlfs_dir_vnew(), tcmi_ctlfs_entry_get(), tcmi_ctlfs_entry_put(), and TCMI_PERMS_DIR.
Referenced by tcmi_migman_init().
 {
     mdbg(INFO4, "Creating directories");
     if (!(self->d_migman = tcmi_ctlfs_dir_vnew(root, TCMI_PERMS_DIR, namefmt, args)))
         goto exit0;
     if (!(self->d_conns =
           tcmi_ctlfs_dir_new(self->d_migman, TCMI_PERMS_DIR, "connections")))
         goto exit1;
     if (!(self->d_migproc = tcmi_ctlfs_entry_get(migproc))) {
         mdbg(ERR3, "Missing migproc directory for migration manager!");
         goto exit2;
     }
     if (self->ops->init_ctlfs_dirs && self->ops->init_ctlfs_dirs(self)) {
         mdbg(ERR3, "Failed to create specific ctlfs directories!");
         goto exit3;
     }
     return 0;
     /* error handling */
  exit3:
     tcmi_ctlfs_entry_put(self->d_migproc);
  exit2:
     tcmi_ctlfs_entry_put(self->d_conns);
  exit1:
     tcmi_ctlfs_entry_put(self->d_migman);
  exit0:
     return -EINVAL;
 }
static int tcmi_migman_init_ctlfs_files (struct tcmi_migman * self) static
<<private>> Creates the static files described here .
Parameters
*self - pointer to this migration manager instance
Returns
0 upon success
Definition at line 404 of file tcmi_migman.c.
References mdbg, self, tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), tcmi_ctlfs_intfile_new(), tcmi_ctlfs_strfile_new(), tcmi_migman_kill_request(), tcmi_migman_show_state(), TCMI_MIGMAN_STATE_LENGTH, tcmi_migman_stop_request(), TCMI_PERMS_FILE_R, and TCMI_PERMS_FILE_W.
Referenced by tcmi_migman_init().
 {
     mdbg(INFO4, "Creating files");
     if (!(self->f_state =
           tcmi_ctlfs_strfile_new(self->d_migman, TCMI_PERMS_FILE_R,
                      self, tcmi_migman_show_state, NULL,
                      TCMI_MIGMAN_STATE_LENGTH, "state")))
         goto exit0;
     if (!(self->f_stop =
           tcmi_ctlfs_intfile_new(self->d_migman, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_migman_stop_request,
                      sizeof(int), "stop")))
         goto exit1;
     if (!(self->f_kill =
           tcmi_ctlfs_intfile_new(self->d_migman, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_migman_kill_request,
                      sizeof(int), "kill")))
         goto exit2;
     if (self->ops->init_ctlfs_files && self->ops->init_ctlfs_files(self)) {
         mdbg(ERR3, "Failed to create specific ctlfs files!");
         goto exit3;
     }
     return 0;
     /* error handling */
  exit3:
     tcmi_ctlfs_file_unregister(self->f_kill);
     tcmi_ctlfs_entry_put(self->f_kill);
  exit2:
     tcmi_ctlfs_file_unregister(self->f_stop);
     tcmi_ctlfs_entry_put(self->f_stop);
  exit1:
     tcmi_ctlfs_file_unregister(self->f_state);
     tcmi_ctlfs_entry_put(self->f_state);
  exit0:
     return -EINVAL;
 }
static int tcmi_migman_kill_request (void * obj, void * data) static
<<private>> Requests asynchronous kill of this migration manager
Parameters
*obj - this migration manager instance
*data - ignored
Returns
0 upon success
Definition at line 511 of file tcmi_migman.c.
References TCMI_MIGMAN, and tcmi_migman_kill().
Referenced by tcmi_migman_init_ctlfs_files().
{
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     tcmi_migman_kill(self);
     return 0;
 }
static int tcmi_migman_msg_thread (void * data) static
<<private>> Message processing thread.
Sleeps on the message queue and notifies the migration manager instance to process each incoming message.
Parameters
*data - migration manager instance
Returns
0 upon successful thread termination.
Definition at line 654 of file tcmi_migman.c.
References mdbg, minfo, tcmi_migman::node, self, TCMI_DISCONNECT_MSG_ID, TCMI_MIGMAN, tcmi_migman_stop_perform(), tcmi_msg_id(), tcmi_queue_remove_entry, tcmi_queue_wait_on_empty_interruptible(), and wait_on_should_stop.
Referenced by tcmi_migman_start_thread().
 {
     int err = 0;
     int migman_freed = 0;
     struct tcmi_msg *m;
     struct tcmi_migman *self = TCMI_MIGMAN(data);
     /* saves 2 derefences when calling the process msg method */
     process_msg_t *process_msg = self->ops->process_msg;
     if (!process_msg) {
         mdbg(ERR3, "Missing method to process messages!");
         goto exit0;
     }
     mdbg(INFO3, "Message processing thread up and running %p", current);
     while (!(kthread_should_stop() || signal_pending(current))) {
         if ((err = tcmi_queue_wait_on_empty_interruptible(&self->msg_queue)) < 0) {
             minfo(INFO1, "Signal arrived %d", err);
             break;
         }
         tcmi_queue_remove_entry(&self->msg_queue, m, node);
         if (m) {
             mdbg(INFO3, "Processing message..");
             switch(tcmi_msg_id(m)) {
                 default:
                 process_msg(self, m);
                 break;
                 case TCMI_DISCONNECT_MSG_ID:
                     minfo(INFO3, "Received disconnect message");
                 /*
                   Initiate shutdown upon reception of disconnect message
                   Note: It is important not to touch self after this call and before should_stop is checked again, because self reference may be already invalid!
                 */
                 migman_freed = tcmi_migman_stop_perform(self, 1);
                 break;
             }
         }
         else {
             mdbg(ERR3, "Processing thread woken up, queue is still empty..");
         }
     }
  exit0:
     /* In case the migman was freed by this thread, no should_stop sync is performed */
     if ( !migman_freed ) {
         /* We have to wait for thread terminating us as it is going to call stop at some tim */
         wait_on_should_stop();
     }
     mdbg(INFO3, "Message processing thread terminating");
     return 0;
 }
static void tcmi_migman_notify_peer_disconnect (struct tcmi_migman * self) static
Definition at line 262 of file tcmi_migman.c.
References minfo, tcmi_disconnect_msg_new_tx(), tcmi_migman_sock(), TCMI_MSG, tcmi_msg_put(), and tcmi_msg_send_anonymous().
Referenced by tcmi_migman_stop_perform().
{
     struct tcmi_msg* msg;
     int err;
     if ( !( msg = TCMI_MSG(tcmi_disconnect_msg_new_tx()) ) ) {
         minfo(ERR3, "Error creating disconnect message");
     } else {
     if ((err = tcmi_msg_send_anonymous(msg, tcmi_migman_sock(self)))) {
         minfo(ERR3, "Error sending disconnect message %d", err);
     }
     tcmi_msg_put(msg);
     }
 }
static int tcmi_migman_show_state (void * obj, void * data) static
<<private>> Read method for the TCMI ctlfs - reports migration manager state.
Parameters
*obj - this migration manager instance
*data - pointer to this migration manager instance
Returns
0 upon success
Definition at line 526 of file tcmi_migman.c.
References mdbg, TCMI_MIGMAN, tcmi_migman_state(), TCMI_MIGMAN_STATE_COUNT, TCMI_MIGMAN_STATE_LENGTH, and tcmi_migman_states.
Referenced by tcmi_migman_init_ctlfs_files().
 {
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     mdbg(INFO3, "state %d, maxcount %d", tcmi_migman_state(self), TCMI_MIGMAN_STATE_COUNT);
     if (tcmi_migman_state(self) < TCMI_MIGMAN_STATE_COUNT) {
         strncpy((char*)data,
             tcmi_migman_states[tcmi_migman_state(self)],
             TCMI_MIGMAN_STATE_LENGTH);
         mdbg(INFO3, "Displaying state %s", tcmi_migman_states[tcmi_migman_state(self)]);
     }
     return 0;
 }
static int tcmi_migman_start_thread (struct tcmi_migman * self) static
<<private>> Starts the listening thread.
The kernel thread is started by using kernel services. No additional actions are needed.
Parameters
*self - pointer to this migration manager instance
Returns
0 upon sucessful thread creation
Definition at line 547 of file tcmi_migman.c.
References mdbg, self, and tcmi_migman_msg_thread().
Referenced by tcmi_migman_init().
 {
     int err = 0;
     self->msg_thread = kthread_run(tcmi_migman_msg_thread, self,
                        "tcmi_migmsgd");
     if (IS_ERR(self->msg_thread)) {
         err = -EINVAL;
         goto exit0;
     }
     mdbg(INFO3, "Created message processing thread %p", self->msg_thread);
     /* error hanlding */
  exit0:
     return err;
 }
static void tcmi_migman_stop_ctlfs_dirs (struct tcmi_migman * self) static
<<private>> Destroys all TCMI ctlfs directories
Parameters
*self - pointer to this migration manager instance
Definition at line 454 of file tcmi_migman.c.
References mdbg, self, and tcmi_ctlfs_entry_put().
Referenced by tcmi_migman_free(), and tcmi_migman_init().
 {
     mdbg(INFO3, "Destroying  TCMI migmanager ctlfs directories");
     if (self->ops->stop_ctlfs_dirs)
         self->ops->stop_ctlfs_dirs(self);
     tcmi_ctlfs_entry_put(self->d_migman);
     tcmi_ctlfs_entry_put(self->s_migman);
     tcmi_ctlfs_entry_put(self->d_conns);
     tcmi_ctlfs_entry_put(self->d_migproc);
 }
static void tcmi_migman_stop_ctlfs_files (struct tcmi_migman * self) static
<<private>> Unregisters and releases all control files.
Parameters
*self - pointer to this migration manager instance
Definition at line 472 of file tcmi_migman.c.
References mdbg, self, tcmi_ctlfs_entry_put(), TCMI_CTLFS_FILE_FROM_METHOD, tcmi_ctlfs_file_unregister(), and tcmi_ctlfs_file_unregister2().
Referenced by tcmi_migman_free(), and tcmi_migman_init().
 {
     mdbg(INFO3, "Destroying  TCMI migmanager ctlfs files");
     if (self->ops->stop_ctlfs_files)
         self->ops->stop_ctlfs_files(self);
     /* We have to use non-locking unregister, because the unregister could be called from this file's write method */
     tcmi_ctlfs_file_unregister2(self->f_stop, TCMI_CTLFS_FILE_FROM_METHOD);
     tcmi_ctlfs_entry_put(self->f_stop);
     /* We have to use non-locking unregister, because the unregister could be called from this file's write method */
     tcmi_ctlfs_file_unregister2(self->f_kill, TCMI_CTLFS_FILE_FROM_METHOD);
     tcmi_ctlfs_entry_put(self->f_kill);
     tcmi_ctlfs_file_unregister(self->f_state);
     tcmi_ctlfs_entry_put(self->f_state);
 }
static int tcmi_migman_stop_perform (struct tcmi_migman * self, int remote_requested) static
Actual implementation of stop, see tcmi_migman_stop.
Parameters
remote_requested True, if stop request was initiated as a response to received disconnect message 1, if the migman instance was destroyed in context of this method
Definition at line 282 of file tcmi_migman.c.
References minfo, self, tcmi_migman_change_state(), TCMI_MIGMAN_CONNECTED, tcmi_migman_notify_peer_disconnect(), tcmi_migman_put(), TCMI_MIGMAN_SHUTTING_DOWN, tcmi_migman_slot_index(), and tcmi_migman_state().
Referenced by tcmi_migman_msg_thread().
{
      minfo(INFO3, "Requesting stop of migration manager: %d Remote requested: %d", tcmi_migman_slot_index(self), remote_requested);
      if ( tcmi_migman_change_state(self, TCMI_MIGMAN_CONNECTED, TCMI_MIGMAN_SHUTTING_DOWN) ) {
     /* We are the first to request stop operation */
     if (self->ops->stop)
         self->ops->stop(self, remote_requested);
     if ( !remote_requested ) {
         /* Sent notification to peer about disconnection being performed.. even if this fails (peer may be dead already), we proceed further */
         tcmi_migman_notify_peer_disconnect(self);
     }
     /* Finally drop the reference to "self". If this is the last reference, the instance is going to be unhased and deleted.
        At this phase it is possible some tasks are still running and so they have reference to this instance. Asynchronous emigration requests were already issued */
     return tcmi_migman_put(self);
      } else {
     minfo(INFO3, "Migration manager stop was already requested -> Ignoring this call. Manager state is: %d", tcmi_migman_state(self));
      }
      return 0;
 }
static int tcmi_migman_stop_request (void * obj, void * data) static
<<private>> Requests asynchronous shutdown of this migration manager
Parameters
*obj - this migration manager instance
*data - ignored
Returns
0 upon success
Definition at line 497 of file tcmi_migman.c.
References TCMI_MIGMAN, and tcmi_migman_stop().
Referenced by tcmi_migman_init_ctlfs_files().
{
     struct tcmi_migman *self = TCMI_MIGMAN(obj);
     tcmi_migman_stop(self);
     return 0;
 }
static void tcmi_migman_stop_thread (struct tcmi_migman * self) static
<<private>> The TCMI manager listening thread is to be terminated by forcing a signal and waiting for it to terminate.
The thread notices the request from the manager and terminates.
Parameters
*self - pointer to this migration manager instance
Definition at line 572 of file tcmi_migman.c.
References mdbg, and self.
Referenced by tcmi_migman_free().
 {
     if (self->msg_thread) {
         mdbg(INFO3, "Stopping message processing thread");
         force_sig(SIGTERM, self->msg_thread);
         if ( self->msg_thread != current ) {
           /* We can only call stop if we are not actually the thread being stopped! */
           kthread_stop(self->msg_thread);
         }
     }
 }
static void tcmi_migman_unhash (struct tcmi_migman * self) static
Removes migman from a list of migration managers of the associated manager.
Check if we were not already unhashed
Definition at line 208 of file tcmi_migman.c.
References self, tcmi_slot_lock(), tcmi_slot_node_unhashed, tcmi_slot_remove_first, and tcmi_slot_unlock().
Referenced by tcmi_migman_free().
{
       /** Check if we were not already unhashed */
       if ( !tcmi_slot_node_unhashed(&self->node) ) {
       tcmi_slot_lock(self->manager_slot);
       tcmi_slot_remove_first(self, self->manager_slot, node);
       tcmi_slot_unlock(self->manager_slot);
       }
 }