Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/lib/tcmi_slot.h File Reference
tcmi_slot.h File Reference
#include <linux/list.h>
#include <linux/types.h>
#include <linux/spinlock.h>
#include <dbg.h>
Data Structures
struct tcmi_slot
A slot compound structure.
Macros
#define tcmi_slot_entry(ptr, type, member) hlist_entry(ptr, type, member)
<<public>> Extracts the actual entry from a slot node
#define tcmi_slot_for_each(node, slot) hlist_for_each(node, &slot->head)
<<public>> Iterates through all nodes in the slot.
#define tcmi_slot_for_each_entry(object, node, slot, member) hlist_for_each_entry(object, node, &slot->head, member)
<<public>> Iterates through all nodes in the slot.
#define tcmi_slot_for_each_entry_safe(object, node, node2, slot, member) hlist_for_each_entry_safe(object, node, node2, &slot->head, member)
<<public>> Iterates through all nodes in the slot - safe version.
#define tcmi_slot_find_first(object, slot, member)
<<public>> Returns the first object in the slot.
#define tcmi_slot_remove_first(object, slot, member)
<<public>> Removes the first object in the slot.
#define tcmi_slot_node_unhashed(n) hlist_unhashed(n)
Check for node being removed from the hlist.
Typedefs
typedef struct hlist_node tcmi_slot_node_t
A slot node is in fact a hlist node.
Functions
static void tcmi_slot_init (struct tcmi_slot *self, u_int index, struct list_head *unused_slots, struct list_head *used_slots, spinlock_t *lock)
Initializes a slot.
static int tcmi_slot_empty (struct tcmi_slot *self)
<<public>> Checks if the slot is empty.
static u_int tcmi_slot_index (struct tcmi_slot *self)
<<public>> Slot index accessor.
static void tcmi_slot_lock (struct tcmi_slot *self)
<<public>> Locks the slot data.
static void tcmi_slot_unlock (struct tcmi_slot *self)
<<public>> Unlocks the instance data
static void tcmi_slot_move (struct tcmi_slot *self, struct list_head *head)
<<private>> Moves a slot into the specified list.
static void tcmi_slot_move_tail (struct tcmi_slot *self, struct list_head *head)
<<private>> Moves a slot to the tail of the specified list.
static void tcmi_slot_insert (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Inserts a new node into the slot.
static void tcmi_slot_move_unused (struct tcmi_slot *self)
<<public>> Moves a slot among unused_slots.
static void __tcmi_slot_remove (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Removes a given node from a slot.
static void tcmi_slot_remove (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Removes a given node from a slot.
static void tcmi_slot_remove_safe (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Removes a given node from a slot.
Function Documentation
static void __tcmi_slot_remove (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Removes a given node from a slot.
No check is performed, whether the node belongs to this slot. If the slot becomes empty by removeing the node, it will be moved to the unused slot list.
Note
This method assumes the s_lock is held.
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be removed
Definition at line 321 of file tcmi_slot.h.
References mdbg, self, tcmi_slot_empty(), and tcmi_slot_move_unused().
Referenced by tcmi_slot_remove(), and tcmi_slot_remove_safe().
 {
     hlist_del_init(node);
     if (tcmi_slot_empty(self)) {
         tcmi_slot_move_unused(self);
         mdbg(INFO4, "Slot %d is now empty, moving to unused slots", self->index);
     }
 }
static int tcmi_slot_empty (struct tcmi_slot * self) inline static
<<public>> Checks if the slot is empty.
Parameters
*self - pointer to this slot instance
Returns
1 - when the slot is empty
Definition at line 217 of file tcmi_slot.h.
References self.
Referenced by __tcmi_slot_remove().
 {
     return hlist_empty(&self->head);
 }
static u_int tcmi_slot_index (struct tcmi_slot * self) inline static
<<public>> Slot index accessor.
Parameters
*self - pointer to this slot instance
Returns
slot index
Definition at line 228 of file tcmi_slot.h.
 {
     return self->index;
 }
static void tcmi_slot_init (struct tcmi_slot * self, u_int index, struct list_head * unused_slots, struct list_head * used_slots, spinlock_t * lock) inline static
Initializes a slot.
Assigns it an index and appends it to the tail of the unused_slots list. The slot keeps track whether it is empty or not on its own. That's why we store the unused_slots and used_slots heads inside the slot. The spinlock protects those lists from concurrent modification.
Parameters
*self - pointer to this slot instance
index - slot index
unused_slots - head of the list of unused slots
used_slots - head of the list of used slots
*lock - pointer to the lock that will be used when synchronizing access to the slotvector where the slot resides.
Definition at line 198 of file tcmi_slot.h.
References self.
 {
     self->index = index;
     INIT_LIST_HEAD(&self->slot_list);
     INIT_HLIST_HEAD(&self->head);
     self->unused_slots = unused_slots;
     self->used_slots = used_slots;
     self->s_lock = lock;
     list_add_tail(&self->slot_list, unused_slots);
 }
static void tcmi_slot_insert (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Inserts a new node into the slot.
It is necessary to acquire a lock to prevent races with other threads. The slot is also moved into the used_slots list. This might be considered as overhead operation if the slot is already in that list, but it simplifies the design. Otherwise we would need an extra flag indicating which list it is currently in. Also the operation is O(1), so the penalty is rather small.
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be added
Definition at line 290 of file tcmi_slot.h.
References mdbg, self, tcmi_slot_lock(), tcmi_slot_move(), and tcmi_slot_unlock().
 {
     tcmi_slot_lock(self);
     mdbg(INFO4, "Inserted node %p into slot %d", node, self->index);
     INIT_HLIST_NODE(node);
     hlist_add_head(node, &self->head);
     tcmi_slot_move(self, self->used_slots);
     tcmi_slot_unlock(self);
 }
static void tcmi_slot_lock (struct tcmi_slot * self) inline static
<<public>> Locks the slot data.
Spin lock used - no sleeping allowed!
Parameters
*self - pointer to this slot instance
Definition at line 239 of file tcmi_slot.h.
References self.
Referenced by tcmi_slot_insert(), tcmi_slot_remove(), and tcmi_slot_remove_safe().
 {
     // Have to be irqsave to avoid possible safe->unsafe conflict in forks
     spin_lock_irqsave(self->s_lock, self->lock_flags);
 }
static void tcmi_slot_move (struct tcmi_slot * self, struct list_head * head) inline static
<<private>> Moves a slot into the specified list.
Parameters
*self - pointer to this slot instance
head - list where the slot should be moved
Definition at line 261 of file tcmi_slot.h.
References self.
Referenced by tcmi_slot_insert(), and tcmi_slot_move_unused().
 {
     list_move(&self->slot_list, head);
 }
static void tcmi_slot_move_tail (struct tcmi_slot * self, struct list_head * head) inline static
<<private>> Moves a slot to the tail of the specified list.
Parameters
*self - pointer to this slot instance
head - list where the slot should be moved
Definition at line 272 of file tcmi_slot.h.
References self.
 {
     list_move_tail(&self->slot_list, head);
 }
static void tcmi_slot_move_unused (struct tcmi_slot * self) inline static
<<public>> Moves a slot among unused_slots.
Parameters
*self - pointer to this slot instance
Definition at line 306 of file tcmi_slot.h.
References self, and tcmi_slot_move().
Referenced by __tcmi_slot_remove().
 {
     tcmi_slot_move(self, self->unused_slots);
 }
static void tcmi_slot_remove (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Removes a given node from a slot.
No check is performed, whether the node belongs to this slot. After locking the slot, the work is delegated to __tcmi_slot_remove().
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be removed
Definition at line 339 of file tcmi_slot.h.
References __tcmi_slot_remove(), self, tcmi_slot_lock(), and tcmi_slot_unlock().
 {
     if (self) {
         if ( spin_is_locked(self->s_lock) ) {
             __tcmi_slot_remove(self, node);
         } else {
             tcmi_slot_lock(self);
             __tcmi_slot_remove(self, node);
             tcmi_slot_unlock(self);
         }
     }
 }
static void tcmi_slot_remove_safe (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Removes a given node from a slot.
A check is performed whether the node belongs to this slot. The work is then delegated to tcmi_slot_remove().
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be removed
Definition at line 361 of file tcmi_slot.h.
References __tcmi_slot_remove(), mdbg, self, tcmi_slot_for_each, tcmi_slot_lock(), and tcmi_slot_unlock().
 {
     struct hlist_node *slot_node;
     int found = 0;
     if (self) {
         tcmi_slot_lock(self);
         tcmi_slot_for_each(slot_node, self) {
             if (slot_node == node) {
                 found = 1;
                 break;
             }
         }
         if (found) {
             mdbg(INFO4, "Found the node %p in slot %d", node, self->index);
             __tcmi_slot_remove(self, node);
         }
         tcmi_slot_unlock(self);
     }
 }
static void tcmi_slot_unlock (struct tcmi_slot * self) inline static
<<public>> Unlocks the instance data
Parameters
*self - pointer to this slot instance
Definition at line 250 of file tcmi_slot.h.
References self.
Referenced by tcmi_slot_insert(), tcmi_slot_remove(), and tcmi_slot_remove_safe().
 {
     spin_unlock_irqrestore(self->s_lock, self->lock_flags);
 }