Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/tcmi/migration/fs/9p_fs_mounter.c File Reference
9p_fs_mounter.c File Reference
#include "9p_fs_mounter.h"
#include "fs_mounter.h"
#include <dbg.h>
#include "9p_fs_helper.h"
#include <tcmi/lib/util.h>
Functions
static int do_private_9p_mount (struct fs_mounter *mounter, int16_t fsuid, int16_t fsgid)
struct fs_mounter * new_9p_fs_mounter (struct fs_mount_params *params)
9p mounter handles mounting of Plan9 filesystem in the private namespace.
Function Documentation
static int do_private_9p_mount (struct fs_mounter * mounter, int16_t fsuid, int16_t fsgid) static
Definition at line 7 of file 9p_fs_mounter.c.
References chroot_to(), and mount_9p_fs().
Referenced by new_9p_fs_mounter().
{
     int err = 0;
     /*
        TODO: improvement would be to find some existing dir, currently /mnt/test is assumed to exist, perhaps just /mnt would be better..
     */
     if ( (err = mount_9p_fs("/mnt/test", mounter, fsuid, fsgid)) )
         return err;
     if ( (err = chroot_to("/mnt/test")) )
         // TODO: Unmount?
         return err;
     return 0;
 }
struct fs_mounter* new_9p_fs_mounter (struct fs_mount_params * params) read
9p mounter handles mounting of Plan9 filesystem in the private namespace.
It does not support any security right not.Creates a new instance of the 9p file system mounter
Definition at line 22 of file 9p_fs_mounter.c.
References do_private_9p_mount(), fs_mounter::free, fs_mounter::global_mount, fs_mounter::params, and fs_mounter::private_mount.
Referenced by get_new_mounter().
{
     struct fs_mounter* mounter = kmalloc(sizeof(struct fs_mounter), GFP_ATOMIC);
     if ( !mounter )
         return NULL;
     mounter->global_mount = NULL;
     mounter->private_mount = do_private_9p_mount;
     mounter->free = NULL;
     mounter->params = *params;
     return mounter;
 }