Clondike: tcmi_procmsg class
tcmi_procmsg class
tcmi_msg class
This class represents a generic process message.
Modules
tcmi_err_procmsg class
This class represents a generic error process message.
tcmi_exit_procmsg class
This class represents an exit message that will be sent out by a guest process upon exit.
tcmi_guest_started_procmsg class
This class represents a message that is sent to the migration initiator as a response to a migration request.
tcmi_ppm_p_migr_back_guestreq_procmsg class
This class represents a message that is sent by guest task to the shadow task as a request(announcement) to migrate the process back to CCN.
tcmi_ppm_p_migr_back_shadowreq_procmsg class
This class represents a message that is sent by a shadow task to the guest task as a request to migrate the process back to CCN.
tcmi_rpc_procmsg class
tcmi_rpcresp_procmsg class
: Updadate comment
tcmi_skel_procmsg class
This class represents a test process control message and is intended to be used as a skeleton when implementing new process control messages in the TCMI protocol.
tcmi_skelresp_procmsg class
This class represents a test process message and is intended to be used as a skeleton response when implementing new response process messages in the TCMI protocol.
tcmi_vfork_done_procmsg class
This class represents an vfork done notification message.
Data Structures
struct tcmi_procmsg
Compound structure, inherits from tcmi_msg_class.
struct tcmi_procmsg_ops
Process message operations that support polymorphism.
Macros
#define TCMI_PROCMSG(m) ((struct tcmi_procmsg*)m)
Casts to the tcmi_procmsg instance.
Functions
static int tcmi_procmsg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_procmsg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Sends the message via a specified connection.
static void tcmi_procmsg_free (struct tcmi_msg *self)
<<private>> Frees custom message resources All work is delegated to a specific process message method
int tcmi_procmsg_init_rx (struct tcmi_procmsg *self, u_int32_t msg_id, struct tcmi_procmsg_ops *procmsg_ops)
<<public>> Initializes the process message for receiving.
int tcmi_procmsg_init_tx (struct tcmi_procmsg *self, u_int32_t msg_id, struct tcmi_procmsg_ops *procmsg_ops, pid_t dst_pid, u_int8_t enforce_migmode, struct tcmi_slotvec *transactions, u_int32_t resp_msg_id, u_int timeout, u_int32_t resp_trans_id)
<<public>> Initializes the process message for transferring.
static pid_t tcmi_procmsg_dst_pid (struct tcmi_procmsg *self)
<<public>> Destination PID accessor.
static pid_t tcmi_procmsg_enforce_migmode (struct tcmi_procmsg *self)
<<public>> Getter of flag idicating whether we should switch to migmode or not
Variables
static struct tcmi_msg_ops procmsg_ops
Message operations that support polymorphism.
Detailed Description
This class represents a generic process message.
Process message, in addition to regular migration message, carries a target process PID. This PID will be used by the receiving party for message delivery. The only functionality provided by this class is to send/receive the process ID and notify the specific procmsg via send/receive/free operations.
Data Structure Documentation
struct tcmi_procmsg
Compound structure, inherits from tcmi_msg_class.
Definition at line 54 of file tcmi_procmsg.h.
Data Fields
pid_t dst_pid destination process PID
u_int8_t enforce_migmode == 1, if the we should switch to migration mode after recieving this message
struct tcmi_procmsg_ops * msg_ops proc message operations
struct tcmi_msg super parent class instance
struct tcmi_procmsg_ops
Process message operations that support polymorphism.
Definition at line 67 of file tcmi_procmsg.h.
Data Fields
int(* recv)(struct tcmi_procmsg *, struct kkc_sock *)
Receives the message via a specified connection.
int(* send)(struct tcmi_procmsg *, struct kkc_sock *)
Sends the message via a specified connection.
void(* free)(struct tcmi_procmsg *)
Frees custom message resources.
Field Documentation
void(* tcmi_procmsg_ops::free)(struct tcmi_procmsg *)
Frees custom message resources.
The destruction of the actual message instance is handled internally by this class
Definition at line 75 of file tcmi_procmsg.h.
Referenced by tcmi_procmsg_free().
int(* tcmi_procmsg_ops::recv)(struct tcmi_procmsg *, struct kkc_sock *)
Receives the message via a specified connection.
Definition at line 69 of file tcmi_procmsg.h.
Referenced by tcmi_procmsg_recv().
int(* tcmi_procmsg_ops::send)(struct tcmi_procmsg *, struct kkc_sock *)
Sends the message via a specified connection.
Definition at line 71 of file tcmi_procmsg.h.
Referenced by tcmi_procmsg_send().
Macro Definition Documentation
#define TCMI_PROCMSG (m) ((struct tcmi_procmsg*)m)
Casts to the tcmi_procmsg instance.
Definition at line 115 of file tcmi_procmsg.h.
Referenced by tcmi_err_procmsg_new_rx(), tcmi_err_procmsg_new_tx(), tcmi_exit_procmsg_new_rx(), tcmi_exit_procmsg_new_tx(), tcmi_guest_started_procmsg_new_rx(), tcmi_guest_started_procmsg_new_tx(), tcmi_migman_deliver_msg(), tcmi_ppm_p_migr_back_guestreq_procmsg_free(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx(), tcmi_procmsg_free(), tcmi_procmsg_recv(), tcmi_procmsg_send(), tcmi_rpc_procmsg_new_rx(), tcmi_rpc_procmsg_new_tx(), tcmi_rpcresp_procmsg_new_rx(), tcmi_rpcresp_procmsg_new_tx(), tcmi_skel_procmsg_new_rx(), tcmi_skel_procmsg_new_tx(), tcmi_skelresp_procmsg_new_rx(), tcmi_skelresp_procmsg_new_tx(), tcmi_task_deliver_msg(), tcmi_vfork_done_procmsg_new_rx(), and tcmi_vfork_done_procmsg_new_tx().
Function Documentation
static pid_t tcmi_procmsg_dst_pid (struct tcmi_procmsg * self) inline static
<<public>> Destination PID accessor.
Parameters
*self - this proc message instance
Returns
destination PID
Definition at line 97 of file tcmi_procmsg.h.
Referenced by tcmi_migman_deliver_msg(), tcmi_ppm_p_migr_back_guestreq_procmsg_free(), tcmi_ppm_p_migr_back_guestreq_procmsg_recv(), tcmi_ppm_p_migr_back_guestreq_procmsg_send(), tcmi_ppm_p_migr_back_shadowreq_procmsg_recv(), and tcmi_ppm_p_migr_back_shadowreq_procmsg_send().
 {
     return self->dst_pid;
 }
static pid_t tcmi_procmsg_enforce_migmode (struct tcmi_procmsg * self) inline static
<<public>> Getter of flag idicating whether we should switch to migmode or not
Parameters
*self - this proc message instance
Returns
1 if we should switch to migmode, 0 otherwise
Definition at line 108 of file tcmi_procmsg.h.
Referenced by tcmi_task_deliver_msg().
 {
     return self->enforce_migmode;
 }
static void tcmi_procmsg_free (struct tcmi_msg * self) static
<<private>> Frees custom message resources All work is delegated to a specific process message method
Parameters
*self - this message instance
Definition at line 184 of file tcmi_procmsg.c.
References tcmi_procmsg::dst_pid, tcmi_procmsg_ops::free, mdbg, tcmi_procmsg::msg_ops, and TCMI_PROCMSG.
 {
     struct tcmi_procmsg *self_proc = TCMI_PROCMSG(self);
     struct tcmi_procmsg_ops *ops = self_proc->msg_ops;
     mdbg(INFO3, "Freeing process message (PID=%u)", self_proc->dst_pid);
     if (ops && ops->free)
         ops->free(self_proc);
 }
int tcmi_procmsg_init_rx (struct tcmi_procmsg * self, u_int32_t msg_id, struct tcmi_procmsg_ops * msg_ops)
<<public>> Initializes the process message for receiving.
The message operations specific to a particular process message class are stored in the instance, Regular tcmi message is supplied with generic proc message operations that handle the polymorphism further.
Parameters
*self - pointer to this message instance
msg_id - ID of a particular message type
*msg_ops - pointer to a particular process message operations
Returns
0 upon success
Definition at line 53 of file tcmi_procmsg.c.
References procmsg_ops, TCMI_MSG, and tcmi_msg_init_rx().
Referenced by tcmi_err_procmsg_new_rx(), tcmi_exit_procmsg_new_rx(), tcmi_guest_started_procmsg_new_rx(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_rx(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_rx(), tcmi_rpc_procmsg_new_rx(), tcmi_rpcresp_procmsg_new_rx(), tcmi_skel_procmsg_new_rx(), tcmi_skelresp_procmsg_new_rx(), and tcmi_vfork_done_procmsg_new_rx().
 {
     self->msg_ops = msg_ops;
     /* Initialized the message for receiving. */
     return tcmi_msg_init_rx(TCMI_MSG(self), msg_id, &procmsg_ops);
 }
int tcmi_procmsg_init_tx (struct tcmi_procmsg * self, u_int32_t msg_id, struct tcmi_procmsg_ops * msg_ops, pid_t dst_pid, u_int8_t enforce_migmode, struct tcmi_slotvec * transactions, u_int32_t resp_msg_id, u_int timeout, u_int32_t resp_trans_id)
<<public>> Initializes the process message for transferring.
<<public>> Initializes the process message for transferring.
Similar to rx version - the message operations specific to a particular process message class are stored in the instance, Regular tcmi message is supplied with generic proc message operations that handle the polymorphism further.
Parameters
*self - pointer to this message instance
msg_id - ID of a particular message type
*msg_ops - pointer to a particular process message specific operations
dst_pid - destination process ID - filled in the header
enfoce_migmode - do we require switch to migration mode upon recieving of this message?
*transactions - storage for the new transaction(NULL for one-way messages)
resp_msg_id - response message ID - required for the transaction if the transaction expires(NULL for one-way messages)
timeout - transaction time out (0 for one-way messages)
resp_trans_id - response transaction ID - used when this message is a response to a particular request. The user must set this ID based on the value ofr req_trans_id of the previously received message.
Returns
0 upon success
Definition at line 82 of file tcmi_procmsg.c.
References procmsg_ops, TCMI_MSG, and tcmi_msg_init_tx().
Referenced by tcmi_err_procmsg_new_tx(), tcmi_exit_procmsg_new_tx(), tcmi_guest_started_procmsg_new_tx(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx(), tcmi_rpc_procmsg_new_tx(), tcmi_rpcresp_procmsg_new_tx(), tcmi_skel_procmsg_new_tx(), tcmi_skelresp_procmsg_new_tx(), and tcmi_vfork_done_procmsg_new_tx().
 {
     self->dst_pid = dst_pid;
     self->msg_ops = msg_ops;
     self->enforce_migmode = enforce_migmode;
     /* Initialize the message for transfer */
     return tcmi_msg_init_tx(TCMI_MSG(self), msg_id, &procmsg_ops,
                 transactions, resp_msg_id,
                 timeout, resp_trans_id);
 }
static int tcmi_procmsg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the erro message requires reading the error code from the specified connection
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 113 of file tcmi_procmsg.c.
References tcmi_procmsg::dst_pid, tcmi_procmsg::enforce_migmode, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, tcmi_procmsg::msg_ops, tcmi_procmsg_ops::recv, and TCMI_PROCMSG.
 {
     int err;
     struct tcmi_procmsg *self_proc = TCMI_PROCMSG(self);
     struct tcmi_procmsg_ops *ops = self_proc->msg_ops;
     if ((err = kkc_sock_recv(sock, &self_proc->dst_pid,
                  sizeof(self_proc->dst_pid),
                  KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive dest. PID");
         goto exit0;
     }
     if ((err = kkc_sock_recv(sock, &self_proc->enforce_migmode,
                  sizeof(self_proc->enforce_migmode),
                  KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to receive enforce migmode flag");
         goto exit0;
     }
     mdbg(INFO3, "Received process message (PID=%u)", self_proc->dst_pid);
     if (ops && ops->recv)
         err = ops->recv(self_proc, sock);
     /* error handling */
  exit0:
     return err;
 }
static int tcmi_procmsg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Sends the message via a specified connection.
Parameters
*self - this message instance
*sock - KKC socket used for sending message data
Returns
0 when successfully sent.
Definition at line 149 of file tcmi_procmsg.c.
References tcmi_procmsg::dst_pid, tcmi_procmsg::enforce_migmode, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, tcmi_procmsg::msg_ops, tcmi_procmsg_ops::send, and TCMI_PROCMSG.
 {
     int err;
     struct tcmi_procmsg *self_proc = TCMI_PROCMSG(self);
     struct tcmi_procmsg_ops *ops = self_proc->msg_ops;
     if ((err = kkc_sock_send(sock, &self_proc->dst_pid,
                  sizeof(self_proc->dst_pid),
                  KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send dest. PID");
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self_proc->enforce_migmode,
                  sizeof(self_proc->enforce_migmode),
                  KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send enforce migmode flag");
         goto exit0;
     }
     mdbg(INFO3, "Sent process message (PID=%u)", self_proc->dst_pid);
     if (ops && ops->send)
         err = ops->send(self_proc, sock);
     /* error handling */
  exit0:
     return err;
 }
Variable Documentation
struct tcmi_msg_ops procmsg_ops static
Initial value:
= {
    .recv = tcmi_procmsg_recv,
    .send = tcmi_procmsg_send,
    .free = tcmi_procmsg_free
}
Message operations that support polymorphism.
Definition at line 196 of file tcmi_procmsg.c.
Referenced by tcmi_procmsg_init_rx(), and tcmi_procmsg_init_tx().