Clondike: tcmi_shadowtask class
tcmi_shadowtask class
tcmi_task class
This class is an abstraction for a migrated process on CCN.
Data Structures
struct tcmi_shadowtask
Compound structure for the shadow task.
Macros
#define TCMI_SHADOWTASK(t) ((struct tcmi_shadowtask*)t)
Casts to the task instance.
Functions
static int tcmi_shadowtask_process_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<private>> Processes a message specified by the caller.
static void tcmi_shadowtask_vfork_done (struct tcmi_task *self)
static int tcmi_shadowtask_emigrate_p (struct tcmi_task *self, struct tcmi_npm_params *npm_params)
Internal helper method that can perform both NPM and PPM physical emigration.
static int tcmi_shadowtask_emigrate_ppm_p (struct tcmi_task *self)
<<private>> Emigrates a task to a PEN.
static int tcmi_shadowtask_emigrate_npm (struct tcmi_task *self, struct tcmi_npm_params *npm_params)
static int tcmi_shadowtask_migrateback_ppm_p (struct tcmi_task *self)
<<private>> Migrates a task back to CCN.
static int tcmi_shadowtask_execve (struct tcmi_task *self)
<<private>> Execve notification when merging shadow with migrating process on CCN.
static int tcmi_shadowtask_do_signal (struct tcmi_task *self, unsigned long signr, siginfo_t *info)
<<private>> Processes a specified signal.
static int tcmi_shadowtask_verify_migration (struct tcmi_task *self, struct tcmi_msg *resp)
<<private>> Verifies, that the task has been successfully migrated.
static int tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg (struct tcmi_task *self, struct tcmi_msg *m)
<<private>> Processes the PPM_P emigrate process message.
static void tcmi_shadowtask_free (struct tcmi_task *self)
<<private>> Custom free method
enum tcmi_task_type tcmi_shadowtask_get_type (void)
Return type of task.
struct tcmi_task * tcmi_shadowtask_new (pid_t local_pid, struct tcmi_migman *migman, struct kkc_sock *sock, struct tcmi_ctlfs_entry *d_migproc, struct tcmi_ctlfs_entry *d_migman)
<<public>> Creates a new shadow task.
Variables
static struct tcmi_task_ops shadowtask_ops
TCMI task operations that support polymorphism.
Detailed Description
This class is an abstraction for a migrated process on CCN.
It represents the residual dependency that the migrated process has towards its originating node(CCN). This class also does all the migration work including migration back to CCN (merging the shadow with the process migrating home). For this purpose, there are various methods that implement various types of migration:
preemptive migration using physical checkpoint image (tcmi_shadowtask_*_ppm_p())
preemptive migration using virtual checkpoint image (tcmi_shadowtask_*_ppm_v())
non-preemptive migration via execve hook (tcmi_shadowtask_*_npm())
Data Structure Documentation
struct tcmi_shadowtask
Compound structure for the shadow task.
Definition at line 56 of file tcmi_shadowtask.h.
Data Fields
struct tcmi_task super parent class instance.
Macro Definition Documentation
#define TCMI_SHADOWTASK (t) ((struct tcmi_shadowtask*)t)
Casts to the task instance.
Definition at line 63 of file tcmi_shadowtask.h.
Referenced by tcmi_shadowtask_new().
Function Documentation
static int tcmi_shadowtask_do_signal (struct tcmi_task * self, unsigned long signr, siginfo_t * info) static
<<private>> Processes a specified signal.
All signals are forwared to the guest task.
Parameters
*self - pointer to this task instance
signr - signal that is to be processed
*info - info for signal to be processed
Returns
TCMI_TASK_KEEP_PUMPING on any signal but second or more SIGKILL
Definition at line 384 of file tcmi_shadowtask.c.
References mdbg, self, tcmi_migman_sock(), tcmi_msg_send_anonymous(), tcmi_signal_msg_new(), tcmi_task_check_peer_lost(), TCMI_TASK_KEEP_PUMPING, and tcmi_task_remote_pid().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_msg *msg;
     mdbg(INFO2, "Shadow is processing signal %lu", signr);
     msg = tcmi_signal_msg_new(tcmi_task_remote_pid(self), info);
     if( msg ){
         tcmi_task_check_peer_lost(self, tcmi_msg_send_anonymous(msg, tcmi_migman_sock(self->migman)));
         mdbg(INFO2, "Signal message send");
     }
     return res;
 }
static int tcmi_shadowtask_emigrate_npm (struct tcmi_task * self, struct tcmi_npm_params * npm_params) static
Definition at line 313 of file tcmi_shadowtask.c.
References tcmi_shadowtask_emigrate_p().
 {
     return tcmi_shadowtask_emigrate_p(self, npm_params);
 }
static int tcmi_shadowtask_emigrate_p (struct tcmi_task * self, struct tcmi_npm_params * npm_params) static
Internal helper method that can perform both NPM and PPM physical emigration.
Definition at line 205 of file tcmi_shadowtask.c.
References tcmi_npm_params::file_name, mdbg, req, resp, signal_action, tcmi_msg_put(), tcmi_p_emigrate_msg_new_tx(), tcmi_shadowtask_verify_migration(), tcmi_task_check_peer_lost(), tcmi_task_ckpt_name(), TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), tcmi_task_process_msg(), TCMI_TASK_REMOVE_AND_LET_ME_GO, tcmi_task_send_and_receive_msg(), tcmi_task_submit_method(), tcmi_task_transactions(), tcmi_taskhelper_catch_all_signals(), tcmi_taskhelper_checkpoint(), and tcmi_taskhelper_flushfiles().
Referenced by tcmi_shadowtask_emigrate_npm(), and tcmi_shadowtask_emigrate_ppm_p().
{
     struct tcmi_msg *req, *resp;
     char* exec_name;
     u64 beg_time, end_time;
     beg_time = cpu_clock(smp_processor_id());
     if ( npm_params ) {
         // For NPM, the exec name is name of the file being executed
         exec_name = npm_params->file_name;
     } else {
         // TODO: Detect this from current in case of PPM.. how? ;)
         exec_name = current->comm;
     }
     mdbg(INFO2, "Process '%s' - local PID %d, emigrating",
          current->comm, tcmi_task_local_pid(self));
     if (tcmi_taskhelper_checkpoint(self, npm_params) < 0) {
         mdbg(ERR3, "Failed to create a checkpoint");
         goto exit0;
     }
     if (!(req = tcmi_p_emigrate_msg_new_tx(tcmi_task_transactions(self),
                            tcmi_task_local_pid(self),
                            exec_name,
                            tcmi_task_ckpt_name(self),
                            current_euid(),
                            current_egid(),
                            current_fsuid(),
                            current_fsgid()))) {
         mdbg(ERR3, "Error creating an emigration message");
         goto exit0;
     }
     if ( tcmi_task_check_peer_lost(self, tcmi_task_send_and_receive_msg(self, req, &resp)) < 0) {
         mdbg(ERR3, "Failed to send message!!");
         goto exit1;
     }
     if (tcmi_shadowtask_verify_migration(self, resp) < 0) {
         mdbg(ERR3, "Failed to migrate the task '%s'", current->comm);
         goto exit2;
     }
     end_time = cpu_clock(smp_processor_id());
     mdbg(INFO3, "Emigration (npm: %d) took '%llu' ms.'", npm_params != NULL, (end_time - beg_time) / 1000000);
     printk("Emigration (npm: %d) took '%llu' ms.\n'", npm_params != NULL, (end_time - beg_time) / 1000000);
     /*
        Files are flushed only after we have confirmation that the migration have succeeded.
        Otherwise we keep them open so that we can eventually continue execution of the current
            process.
          */
     tcmi_taskhelper_flushfiles();
     tcmi_taskhelper_catch_all_signals(&signal_action);
     mdbg(INFO3, "Submitting process_msg");
     tcmi_task_submit_method(self, tcmi_task_process_msg, NULL, 0);
     /* release the message */
     tcmi_msg_put(req);
     tcmi_msg_put(resp);
     // In case the emigration succeeded, we are responsible for freeing of npm params, as the caller won't ever get chance
     if ( npm_params )
         vfree(npm_params);
     return TCMI_TASK_KEEP_PUMPING;
     /* error handling */
  exit2:
     tcmi_msg_put(resp);
  exit1:
     tcmi_msg_put(req);
  exit0:
     /* either checkpointing,communication or restart has failed. In either case we simply continue execution of the current task */
     return TCMI_TASK_REMOVE_AND_LET_ME_GO;
 };
static int tcmi_shadowtask_emigrate_ppm_p (struct tcmi_task * self) static
<<private>> Emigrates a task to a PEN.
create a new checkpoint
flush open files of the current process (prevents write conflicts after checkpoint restart)
creates a new emigration message specifying latest checkpoint name and shadow task PID
send the message waiting for a response
if the guest has been succesfully started submit process_msg method into the method queue and quit (migration verification). The submitted method will keep on processing any message that will arrive on the queue.
Parameters
*self - pointer to this task instance
Returns
TCMI_TASK_KEEP_PUMPING, if the shadow has received a positive response and the task has been successfully migrated.
Todo:
after creating a checkpoint and preparing the emigration message there a few things that need to be done:
some component should scan all open files and close all regular files as they will be accessed from the network filesystem.
character, block devices, pipes, sockets should stay open so that remote operations can be forwarded locally.
the current execution image should be flushed as it is not needed anymore
Definition at line 308 of file tcmi_shadowtask.c.
References tcmi_shadowtask_emigrate_p().
 {
     return tcmi_shadowtask_emigrate_p(self, NULL);
 }
static int tcmi_shadowtask_execve (struct tcmi_task * self) static
<<private>> Execve notification when merging shadow with migrating process on CCN.
This method is called right before issuing the actual execve on the checkpoint image of the migrated task. Since the task will be merged with the original process, it needs to be remove from the TCMI. All that needs to be done is scheduling a tcmi_task_exit() method. The migration mode handler takes care of the rest.
Parameters
*self - pointer to this task instance
Returns
0 upon success
Definition at line 365 of file tcmi_shadowtask.c.
References tcmi_task_exit(), tcmi_task_flush_and_submit_method(), and tcmi_taskhelper_enter_mig_mode().
 {
     tcmi_task_flush_and_submit_method(self, tcmi_task_exit, NULL, 0);
     /* migration mode is entered when the actual execve resumes to
      * user mode */
     tcmi_taskhelper_enter_mig_mode(self);
     return 0;
 }
static void tcmi_shadowtask_free (struct tcmi_task * self) static
<<private>> Custom free method
Definition at line 495 of file tcmi_shadowtask.c.
 {
 }
enum tcmi_task_type tcmi_shadowtask_get_type (void)
Return type of task.
Only for setting task type to kernel task_struct. Polymorphism cannot be used in kernel, bacause tcmi_task is defined outside of kernel.
Definition at line 502 of file tcmi_shadowtask.c.
 {
     return shadow;
 }
static int tcmi_shadowtask_migrateback_ppm_p (struct tcmi_task * self) static
<<private>> Migrates a task back to CCN.
This is done simply by sending a migrate back request to the associated ghost task, which will handle its migration home the same way as if it was requested on PEN
Parameters
*self - pointer to this task instance
Returns
result of the task specific migrate back method or TCMI_TASK_KEEP_PUMPING
Definition at line 328 of file tcmi_shadowtask.c.
References mdbg, tcmi_msg_put(), tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx(), tcmi_task_check_peer_lost(), TCMI_TASK_KEEP_PUMPING, tcmi_task_local_pid(), tcmi_task_remote_pid(), and tcmi_task_send_anonymous_msg().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_msg *msg;
     /* struct tcmi_shadowtask *self_tsk = TCMI_SHADOWTASK(self); */
     mdbg(INFO2, "Process '%s' - local PID %d, remote PID %d, migrate home requested",
          current->comm, tcmi_task_local_pid(self), tcmi_task_remote_pid(self));
     if ( !(msg = tcmi_ppm_p_migr_back_shadowreq_procmsg_new_tx(tcmi_task_remote_pid(self))) ) {
         mdbg(ERR3, "Error creating a migrate back message");
         goto exit0;
     }
     if ( tcmi_task_check_peer_lost(self, tcmi_task_send_anonymous_msg(self, msg)) < 0) {
         mdbg(ERR3, "Failed to send message!!");
         goto exit1;
     }
 exit1:
     tcmi_msg_put(msg);
 exit0:
     return res;
 }
struct tcmi_task* tcmi_shadowtask_new (pid_t local_pid, struct tcmi_migman * migman, struct kkc_sock * sock, struct tcmi_ctlfs_entry * d_migproc, struct tcmi_ctlfs_entry * d_migman) read
<<public>> Creates a new shadow task.
<<public>> Creates a new shadow task.
allocates a new instance.
delegates its initialization to the super class.
Parameters
local_pid - local PID on CCN
migman - The migration manager that maintains this task
*sock - socket used for communication with guest task on PEN
*d_migproc - directory where ctlfs entries of migrated processes reside
*d_migman - TCMI ctlfs directory of the migration manager responsible for this task
Returns
0 upon success
Definition at line 89 of file tcmi_shadowtask.c.
References minfo, shadowtask_ops, TCMI_SHADOWTASK, TCMI_TASK, and tcmi_task_init().
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), and tcmi_migcom_shadow_fork().
 {
     struct tcmi_shadowtask *task;
     minfo(INFO2, "Creating new shadow task for local PID=%d", local_pid);
     if (!(task = TCMI_SHADOWTASK(kmalloc(sizeof(struct tcmi_shadowtask),
                          GFP_ATOMIC)))) {
         minfo(ERR3, "Can't allocate memory for TCMI shadow task");
         goto exit0;
     }
     if (tcmi_task_init(TCMI_TASK(task), local_pid, migman, sock, d_migproc,
                d_migman, &shadowtask_ops) < 0) {
         minfo(ERR3, "TCMI shadow task initialization failed!");
         goto exit1;
     }
     return TCMI_TASK(task);
     /* error handling */
  exit1:
     kfree(task);
  exit0:
     return NULL;
 }
static int tcmi_shadowtask_process_msg (struct tcmi_task * self, struct tcmi_msg * m) static
<<private>> Processes a message specified by the caller.
Parameters
*self - pointer to this task instance
*m - message to be processed
Returns
depends on the type of message that has been processed
Definition at line 127 of file tcmi_shadowtask.c.
References mdbg, minfo, resp, TCMI_EXIT_PROCMSG, tcmi_exit_procmsg_code(), TCMI_EXIT_PROCMSG_ID, TCMI_GUEST_STARTED_PROCMSG, tcmi_guest_started_procmsg_guest_pid(), TCMI_GUEST_STARTED_PROCMSG_ID, tcmi_msg_get(), tcmi_msg_id(), tcmi_msg_put(), TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID, tcmi_rpc_call2(), TCMI_RPC_PROCMSG, TCMI_RPC_PROCMSG_ID, tcmi_rpc_procmsg_num(), tcmi_shadow_rpc, tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg(), tcmi_shadowtask_vfork_done(), tcmi_task_check_peer_lost(), TCMI_TASK_KEEP_PUMPING, TCMI_TASK_KILL_ME, tcmi_task_local_pid(), tcmi_task_remote_pid(), tcmi_task_send_anonymous_msg(), tcmi_task_send_message(), tcmi_task_set_exit_code(), tcmi_task_set_remote_pid(), tcmi_task_submit_method(), and TCMI_VFORK_DONE_PROCMSG_ID.
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     struct tcmi_msg *resp = NULL;
     pid_t remote_pid;
     int err;
     /* struct tcmi_shadowtask *self_tsk = TCMI_SHADOWTASK(self); */
     switch (tcmi_msg_id(m)) {
         case TCMI_RPC_PROCMSG_ID:
             mdbg(INFO1, "Receiced RPC message: %x", tcmi_msg_id(m));
             tcmi_rpc_call2(tcmi_shadow_rpc, tcmi_rpc_procmsg_num(TCMI_RPC_PROCMSG(m)), (long)m, (long)(&resp));
             if ( resp == NULL ) {
                 minfo(ERR3, "RPC#%d didn't returned rpc response message",
                         tcmi_rpc_procmsg_num(TCMI_RPC_PROCMSG(m)));
                 break;
             }
             if ( tcmi_task_check_peer_lost(self, (err = tcmi_task_send_anonymous_msg(self, resp)) ) ){
                 minfo(ERR3, "Error sending RPC response message %d", err);
                 if ( err == -ERESTARTSYS ) {
                     minfo(INFO3, "Scheduling message for resubmission");
                     /* Protect response reference, retransmission method will be responsible for releasing of the msg */
                     tcmi_msg_get(resp);
                     tcmi_task_submit_method(self, tcmi_task_send_message, resp, sizeof(struct tcmi_msg));
                 }
             }
             tcmi_msg_put( resp );
             break;
         /* exit request */
         case TCMI_EXIT_PROCMSG_ID:
             mdbg(INFO2, "Process '%s' local PID=%d, remote PID=%d terminating, "
                     "code: %ld, anounced by guest",
                     current->comm, tcmi_task_local_pid(self),
                     tcmi_task_remote_pid(self),
                     (long)tcmi_exit_procmsg_code(TCMI_EXIT_PROCMSG(m)));
             tcmi_task_set_exit_code(self, tcmi_exit_procmsg_code(TCMI_EXIT_PROCMSG(m)));
             res = TCMI_TASK_KILL_ME;
             break;
         /* vfork done on guest side */
         case TCMI_VFORK_DONE_PROCMSG_ID:
             mdbg(INFO2, "Process '%s' local PID=%d, remote PID=%d vfork done",
                     current->comm, tcmi_task_local_pid(self),
                     tcmi_task_remote_pid(self));
             tcmi_shadowtask_vfork_done(self);
             break;
             /* migrate back request */
         case TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG_ID:
             res = tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg(self, m);
             break;
         case TCMI_GUEST_STARTED_PROCMSG_ID: // We can get here only in double-fork
             remote_pid = tcmi_guest_started_procmsg_guest_pid(TCMI_GUEST_STARTED_PROCMSG(m));
             mdbg(INFO3, "Fork confirmation from guesttask - task migrated, local PID %d, guest PID %d", tcmi_task_local_pid(self), remote_pid);
             tcmi_task_set_remote_pid(self, remote_pid);
             break;
         default:
             mdbg(ERR3, "Unexpected message from the guest task: %x", tcmi_msg_id(m));
             break;
     }
     return res;
 }
static int tcmi_shadowtask_process_ppm_p_migr_back_guestreq_procmsg (struct tcmi_task * self, struct tcmi_msg * m) static
<<private>> Processes the PPM_P emigrate process message.
The remote PID is extracted from the emigration message and stored in the guest task. The checkpoint name is also extracted and passed to the task helper to schedule a restart. This also sets the checkpoint image as the most recent checkpoint of the task.
A response is sent back that will contain the guest task local PID. This PID is needed for further communication between the shadow and guest tasks.
The restart is only scheduled and will be processed upon next iteration of the method pump.
Parameters
*self - this guest task instance
*m - PPM_P migrate back guest request
Returns
TASK_KEEP_PUMPING if the restart has been successfully scheduled
Definition at line 467 of file tcmi_shadowtask.c.
References director_migrated_home(), mdbg, TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG, tcmi_ppm_p_migr_back_guestreq_procmsg_ckpt_name(), TCMI_TASK_KEEP_PUMPING, TCMI_TASK_KILL_ME, tcmi_task_local_pid(), tcmi_task_remote_pid(), and tcmi_taskhelper_restart().
Referenced by tcmi_shadowtask_process_msg().
 {
     char *ckpt_name;
     /* extract the checkpoint name */
     ckpt_name =  tcmi_ppm_p_migr_back_guestreq_procmsg_ckpt_name
         (TCMI_PPM_P_MIGR_BACK_GUESTREQ_PROCMSG(m));
     mdbg(INFO2, "Processing migrate back request, remote PID=%d, checkpoint: '%s'",
              tcmi_task_remote_pid(self), ckpt_name);
     director_migrated_home(tcmi_task_local_pid(self));
     /* schedules process restart from a checkpoint image */
     if (tcmi_taskhelper_restart(self, ckpt_name) < 0) {
         mdbg(ERR3, "Cannot setup task restart!!");
         goto exit0;
     }
     return TCMI_TASK_KEEP_PUMPING;
     /* error handling */
  exit0:
     return TCMI_TASK_KILL_ME;
 }
static int tcmi_shadowtask_verify_migration (struct tcmi_task * self, struct tcmi_msg * resp) static
<<private>> Verifies, that the task has been successfully migrated.
The verification is done based on response message the has to be TCMI_GUEST_STARTED_PROCMSG and has to carry a non-zero guest PID. If the verification is positive, the guest PID is stored inside this shadow instance. It will be used for further communication with the guest.
Parameters
*self - pointer to this task instance
*resp - pointer to the response to be processed
Returns
0 if the task has been successfully migrated
Definition at line 412 of file tcmi_shadowtask.c.
References mdbg, TCMI_GUEST_STARTED_PROCMSG, tcmi_guest_started_procmsg_guest_pid(), TCMI_GUEST_STARTED_PROCMSG_ID, TCMI_MSG_FLG_SET_ERR, tcmi_msg_id(), tcmi_task_local_pid(), and tcmi_task_set_remote_pid().
Referenced by tcmi_shadowtask_emigrate_p().
 {
     int err = -EINVAL;
     pid_t remote_pid;
     if (!resp) {
         mdbg(ERR3, "No response from guest task has arrived..");
         goto exit0;
     }
     switch (tcmi_msg_id(resp)) {
         /* regular version */
     case TCMI_GUEST_STARTED_PROCMSG_ID:
         remote_pid = tcmi_guest_started_procmsg_guest_pid(TCMI_GUEST_STARTED_PROCMSG(resp));
         mdbg(INFO3, "Confirmation from guesttask - task migrated, local PID %d, guest PID %d", tcmi_task_local_pid(self), remote_pid);
         if ( remote_pid == -1 ) {
             err = -EINVAL;
         } else {
           tcmi_task_set_remote_pid(self, remote_pid);
           err = 0;
         }
         break;
         /* error version */
     case TCMI_MSG_FLG_SET_ERR(TCMI_GUEST_STARTED_PROCMSG_ID):
         mdbg(ERR3, "Stub hasn't been started, migration failed..");
         break;
     default:
         mdbg(ERR3, "Unexpected response from the guest task: %x", tcmi_msg_id(resp));
         break;
     }
     /* error handling */
  exit0:
     return err;
 }
static void tcmi_shadowtask_vfork_done (struct tcmi_task * self) static
Definition at line 196 of file tcmi_shadowtask.c.
Referenced by tcmi_shadowtask_process_msg().
{
     struct completion *vfork_done = current->vfork_done;
     if ( current->vfork_done ) {
         current->vfork_done = NULL;
         complete(vfork_done);
     }
 }
Variable Documentation
struct tcmi_task_ops shadowtask_ops static
Initial value:
= {
    .process_msg = tcmi_shadowtask_process_msg,
    .emigrate_ppm_p = tcmi_shadowtask_emigrate_ppm_p,
    .emigrate_npm = tcmi_shadowtask_emigrate_npm,
    .migrateback_ppm_p = tcmi_shadowtask_migrateback_ppm_p,
    .execve = tcmi_shadowtask_execve,
    .get_type = tcmi_shadowtask_get_type,
    .do_signal = tcmi_shadowtask_do_signal,
    .free = tcmi_shadowtask_free
}
TCMI task operations that support polymorphism.
Definition at line 508 of file tcmi_shadowtask.c.
Referenced by tcmi_shadowtask_new().