Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/arch/common/regs.h File Reference
regs.h File Reference
#include <arch/arch_ids.h>
#include <dbg.h>
Functions
static void get_registers (struct pt_regs *regs, struct tcmi_regs *tcmi_regs)
Loads value of pt_regs into the current architecture type specific regs.
static void load_registers (struct tcmi_regs *tcmi_regs, struct pt_regs *regs)
Loads value of tcmi_regs into the regs.
void * get_target_platform_registers (struct pt_regs *regs, enum arch_ids target_arch)
Generic method that converts current registers to target platform registers and returns pointer to those registers.
void load_from_platform_registers (void *platform_registers, struct pt_regs *regs, enum arch_ids from_arch, int is_32bit_app)
Loads registers from checkpointed registers.
void debug_registers (struct pt_regs *regs)
Dumps debug information about current platform registers.
int is_in_syscall (struct pt_regs *regs)
Checks whether a process with specified registers has been in system call.
Function Documentation
void debug_registers (struct pt_regs * regs)
Dumps debug information about current platform registers.
Parameters
regs Current platform registers to be dumped
Referenced by tcmi_ckpt_regs_read(), tcmi_ckpt_regs_write(), and tcmi_core_dump().
static void get_registers (struct pt_regs * regs, struct tcmi_regs * tcmi_regs) inline static
Loads value of pt_regs into the current architecture type specific regs.
It can be done directly by copying as both structures are same.
Parameters
regs Current registers
tcmi_regs Target registers
Definition at line 14 of file regs.h.
References mdbg.
Referenced by tcmi_ckpt_regs_write().
{
     mdbg(INFO4, "Regs size: %lu TCMI regs size: %lu:", (unsigned long)sizeof(struct pt_regs), (unsigned long)sizeof(struct tcmi_regs));
     BUG_ON(sizeof(struct pt_regs) != sizeof(struct tcmi_regs));
     memcpy(tcmi_regs, regs, sizeof(struct tcmi_regs));
 };
void* get_target_platform_registers (struct pt_regs * regs, enum arch_ids target_arch)
Generic method that converts current registers to target platform registers and returns pointer to those registers.
The whole flow of checkpoint/restart is as follow.
First application that is being checkpointed determines if it is able to migrate to the target_arch
If so, it creates target arch registers
Application that is being restarted simply loads registers of its own native type.
Parameters
regs Current registers
target_arch target architecture for which we want to have the registers
Returns
Pointer to target architecture specific registers. Caller is responsible for freeing these registers!
int is_in_syscall (struct pt_regs * regs)
Checks whether a process with specified registers has been in system call.
A process in system call has:
orig_eax >=0 which denotes the original system call number
eax has one of the error values that describes why the process has terminated the system call prematurely.
Referenced by tcmi_resolve_restart_block(), tcmi_resolve_restart_block_32bit_app(), and tcmi_resolve_restart_block_64bit_app().
void load_from_platform_registers (void * platform_registers, struct pt_regs * regs, enum arch_ids from_arch, int is_32bit_app)
Loads registers from checkpointed registers.
Parameters
platform_registers tcmi_regs structure of the "from_arch"
regs Registers to be filled
from_arch Architecture used for creating provided tcmi_regs
is_32bit_app 1 if the application being restored is 32 bit
Referenced by tcmi_ckpt_regs_read().
static void load_registers (struct tcmi_regs * tcmi_regs, struct pt_regs * regs) inline static
Loads value of tcmi_regs into the regs.
Used for restoring register context. It can be done directly by copying as both structures are same.
Parameters
tcmi_regs Source registers
regs Target registers
Definition at line 28 of file regs.h.
{
     BUG_ON(sizeof(struct pt_regs) != sizeof(struct tcmi_regs));
     memcpy(regs, tcmi_regs, sizeof(struct tcmi_regs));
 };