Clondike: proxyfs_server class
proxyfs_server class
proxyfs_task class
<<singleton>> representing proxyfs_server task
Functions
struct proxyfs_file_identifier * proxyfs_server_overtake_file (int fd)
<<public>> "Steal" file to server
void proxyfs_server_release_all (void)
<<public>> <<exported>> Release all files
void proxyfs_server_duplicate_all_parent (struct task_struct *parent, struct task_struct *child)
<<public>> <<exported>> Duplicates all file that were overtaken by a "parent" process and makes child as a owner of duplicates.
int proxyfs_server_thread (void *start_struct)
<<public>> Main server thread
Detailed Description
<<singleton>> representing proxyfs_server task
Function Documentation
void proxyfs_server_duplicate_all_parent (struct task_struct * parent, struct task_struct * child)
<<public>> <<exported>> Duplicates all file that were overtaken by a "parent" process and makes child as a owner of duplicates.
Definition at line 472 of file proxyfs_server.c.
References mdbg, proxyfs_file_get_file_ident(), PROXYFS_REAL_FILE, proxyfs_real_file_has_shadow(), proxyfs_server_duplicate_overtaken_file(), PROXYFS_TASK, and self.
Referenced by tcmi_syscall_hooks_post_fork().
 {
     struct proxyfs_file_t *file;
     struct list_head *l, *nxt;
     if ( !self )
         return;
     if ( task_tgid_vnr(parent) == task_tgid_vnr(child) ) {
         mdbg(INFO2, "No duplication performed as tasks are from a same group (task %d in group %d)", child->pid, task_tgid_vnr(child));
         return;
     }
     down( & self->files_sem );
     list_for_each_safe( l, nxt, &PROXYFS_TASK(self)->files ) {
         file = list_entry(l, struct proxyfs_file_t, files);
         if( proxyfs_real_file_has_shadow(PROXYFS_REAL_FILE(file),parent) ){
             mdbg(INFO2, "Going to duplicate file %lu (for task %d)", proxyfs_file_get_file_ident(file), child->pid);
             proxyfs_server_duplicate_overtaken_file(PROXYFS_REAL_FILE(file), child);
         }
     }
     up( & self->files_sem );
     mdbg(INFO2, "File duplicating done");
 }
struct proxyfs_file_identifier* proxyfs_server_overtake_file (int fd) read
<<public>> "Steal" file to server
<<public>> "Steal" file to server
Parameters
fd - file descriptor of a file, which will be proxied
Returns
File identifier or null
Definition at line 371 of file proxyfs_server.c.
References mdbg, PROXYFS_FILE, proxyfs_pipe_real_file_new(), PROXYFS_REAL_FILE, proxyfs_real_file_add_shadow(), proxyfs_real_file_destroy(), proxyfs_server_register_poll_callback(), PROXYFS_TASK, proxyfs_tty_real_file_new(), and self.
Referenced by tcmi_ckpt_openfile_write_newfd().
{
     struct file *filp;
     struct proxyfs_real_file *file_row;
     static int ident = 1;
     //struct termios termios_buf;
     mm_segment_t old_fs;
     if ( !self )
         goto exit0;
     filp = fget(fd);
     if( filp == NULL ){
         goto exit0;
     }
     if( S_ISCHR(filp->f_dentry->d_inode->i_mode) ){
         old_fs = get_fs();
         set_fs(KERNEL_DS);
         // Does not work on 64 bit :( => commented out
         //if( ioctl(fd, TCGETS, (unsigned long)&termios_buf) == -ENOTTY )
         //  file_row = PROXYFS_REAL_FILE( proxyfs_generic_real_file_new() );
         //else
             file_row = PROXYFS_REAL_FILE( proxyfs_tty_real_file_new()  );
         set_fs(old_fs);
     }
     else if( S_ISFIFO(filp->f_dentry->d_inode->i_mode) ){
         file_row = PROXYFS_REAL_FILE( proxyfs_pipe_real_file_new() );
     }
     else{
         mdbg(ERR3, "Unsupported file type!");
         goto exit1;
     }
     if( file_row == NULL ){
         mdbg(ERR3, "File allocation failed!");
         goto exit1;
     }
     down( & self->files_sem );
     PROXYFS_FILE(file_row)->file_identifier.file_ident = ++ident;
     PROXYFS_FILE(file_row)->file_identifier.file_owner_pid = task_tgid_vnr(current);
     file_row->file = filp;
     proxyfs_real_file_add_shadow(file_row, current);
     //file_row->shadow_current = current;
     // DO NOT DO THIS! The file structure is (potentially) shared among multiple process and it will change behavior of the other processes!
     //filp->f_flags |= O_NONBLOCK; // Force nonblocking asynchronous mode
     if ( proxyfs_server_register_poll_callback(file_row) )
         goto exit2;
     list_add_tail( & PROXYFS_FILE(file_row)->files, &PROXYFS_TASK(self)->files );
     up( & self->files_sem );
     mdbg(INFO3, "Added file %d", ident);
     return &PROXYFS_FILE(file_row)->file_identifier;
 exit2:
     proxyfs_real_file_destroy( file_row );
 exit1:
     fput(filp);
 exit0:
     return NULL;
 }
void proxyfs_server_release_all (void)
<<public>> <<exported>> Release all files
Definition at line 325 of file proxyfs_server.c.
References mdbg, PROXYFS_FILE_CLOSED, proxyfs_file_get_file_ident(), proxyfs_file_set_status(), PROXYFS_REAL_FILE, proxyfs_real_file_remove_shadow(), PROXYFS_TASK, and self.
Referenced by tcmi_mighooks_do_exit().
 {
     struct proxyfs_file_t *file;
     struct list_head *l;
     if ( !self )
         return;
     down( & self->files_sem );
     list_for_each( l, &PROXYFS_TASK(self)->files ){
         file = list_entry(l, struct proxyfs_file_t, files);
         if( proxyfs_real_file_remove_shadow(PROXYFS_REAL_FILE(file),current) == 1 ){ // Did we remove last shadow reference?
             proxyfs_file_set_status( file, PROXYFS_FILE_CLOSED );
             mdbg(INFO2, "Releasing %lu (from task %d)", proxyfs_file_get_file_ident(file), current->pid);
         }
     }
     up( & self->files_sem );
 }
int proxyfs_server_thread (void * ss)
<<public>> Main server thread
Definition at line 62 of file proxyfs_server.c.
References proxyfs_server_listen(), proxyfs_server_loop(), PROXYFS_TASK, proxyfs_task_complete(), proxyfs_task_init(), and self.
Referenced by proxyfs_module_init().
 {
     struct proxyfs_task_start_struct *start_struct = (struct proxyfs_task_start_struct*)ss;
     self = kmalloc(sizeof(struct proxyfs_server), GFP_KERNEL);
     if ( !self )
         return -EINVAL;
     proxyfs_task_init( PROXYFS_TASK(self) );
     PROXYFS_TASK(self)->tsk = current;
     PROXYFS_TASK(self)->ops = &server_ops;
     init_MUTEX(&self->files_sem );
     if( proxyfs_server_listen(start_struct->addr_str) != 0 ){
         proxyfs_task_complete( NULL, start_struct );
         kfree(self);
         return -EINVAL;
     }
     proxyfs_task_complete( PROXYFS_TASK(self), start_struct );
     proxyfs_server_loop();
     return 0;
 }