Clondike: tcmi_ckpt_openfile class
tcmi_ckpt_openfile class
tcmi_ckpt class
This is a helper <<singleton>> class used by the checkpoint and provides functionality to:
Data Structures
struct tcmi_ckpt_openfile_generic_hdr
Describes generic header that consists of a file type only - the options are new or dup file.
struct tcmi_ckpt_openfile_newfile_hdr
Describes a file occurs in the checkpoint for the first time.
struct tcmi_ckpt_openfile_dupfile_hdr
Describes a duplicate file.
Enumerations
enum tcmi_ckpt_openfile_chunk_t { TCMI_CKPT_OPENFILE_NEWFILE = 0, TCMI_CKPT_OPENFILE_DUPFILE }
describes various chunks of the checkpoint file
Functions
static int tcmi_ckpt_openfile_write_dupfd (struct tcmi_ckpt *ckpt, int fd, int dup_fd)
<<private>> Writes a duplicate file descriptor chunk into the checkpoint file.
static int tcmi_ckpt_openfile_write_newfd (struct tcmi_ckpt *ckpt, int fd, struct file *file)
<<private>> Writes a new file chunk into the checkpoint file.
static int tcmi_ckpt_openfile_read_dupfd (struct tcmi_ckpt *ckpt)
<<private>> Reads a duplicate file descriptor chunk from the checkpoint file.
static int tcmi_ckpt_openfile_read_newfd (struct tcmi_ckpt *ckpt)
<<private>> Reads a new file chunk from the checkpoint file.
struct
tcmi_ckpt_openfile_generic_hdr __attribute__ ((__packed__))
int tcmi_ckpt_openfile_write (struct tcmi_ckpt *ckpt, int fd, struct file *file)
<<public>> Writes an open file information into the checkpoint file.
int tcmi_ckpt_openfile_read (struct tcmi_ckpt *ckpt)
<<public>> Reads and restores an open file from the checkpoint file.
static int tcmi_ckpt_openfile_supported (struct inode *inode)
<<public>> Class method - checks if the specified file(represented by its inode) is supported by checkpoint.
Variables
typedef __attribute__
Detailed Description
This is a helper <<singleton>> class used by the checkpoint and provides functionality to:
write an information about an open file into the checkpoint
restore/reopen a file based on information in the checkpoint
The checkpoint instance during checkpoint image creation passes each file along with its file descriptor and current file descriptor cache to this component. The are two separate cases:
the file information has already been written into the checkpoint - this is indicated by a file object being already present in the file descriptor cache . In this case only a short information about a file is written into the checkpoint file - it's current file descriptor and the file descriptor that it's duplicating
the file information hasn't been written into the checkpoint (not present in the fd cache). In this case a full record is required:
file descriptor
current position in file
file flags used when opening the file
file access mode
file type(regular/directory/char/block device/pipe/socket/symlink)
full pathname
Initial implementation supports checkpointing of regular files and directories only. There is a limited support when checkpointing open character devices - seek operation is omitted. Future implementation when restoring the open files should consider the circumstances and decided to reopen the original file or special proxy file. The main purpose of the proxy file will be to forward all requests to the original node.
Todo:
Implement handling of special files (character devices/block devices, pipes, sockets)
Data Structure Documentation
struct tcmi_ckpt_openfile_generic_hdr
Describes generic header that consists of a file type only - the options are new or dup file.
Definition at line 101 of file tcmi_ckpt_openfile.h.
Data Fields
tcmi_ckpt_openfile_chunk_t restore_type type of the open file
struct tcmi_ckpt_openfile_newfile_hdr
Describes a file occurs in the checkpoint for the first time.
Definition at line 108 of file tcmi_ckpt_openfile.h.
Data Fields
int32_t fd file descriptor
u_int32_t flags flags specified by the user when opening the file
u_int32_t mode access mode for the file
int32_t pathname_size length of the pathname string (including trailing zero)
u_int64_t pos current position in the file.
u_int32_t type file type
struct tcmi_ckpt_openfile_dupfile_hdr
Describes a duplicate file.
The duplicate file descriptor refers to the original file object that has been open for the first time. That is: 'dup_fd' has to be duplicated into 'fd' upon checkpoint restart.
Definition at line 128 of file tcmi_ckpt_openfile.h.
Data Fields
int32_t dup_fd file descriptor that refers to the actual file.
int32_t fd file descriptor
Enumeration Type Documentation
enum tcmi_ckpt_openfile_chunk_t
describes various chunks of the checkpoint file
Enumerator
TCMI_CKPT_OPENFILE_NEWFILE
TCMI_CKPT_OPENFILE_DUPFILE
Definition at line 92 of file tcmi_ckpt_openfile.h.
              {
     /* new file */
     TCMI_CKPT_OPENFILE_NEWFILE = 0,
     /* duplicate file descriptor, refers to some regular file */
     TCMI_CKPT_OPENFILE_DUPFILE
 } tcmi_ckpt_openfile_chunk_t;
Function Documentation
struct tcmi_ckpt_openfile_generic_hdr __attribute__ ((__packed__))
int tcmi_ckpt_openfile_read (struct tcmi_ckpt * ckpt)
<<public>> Reads and restores an open file from the checkpoint file.
Restoring the open file requires:
detecting whether the file to be restored requires only duplication of an existing file descriptor or reopening the file from scratch.
after reading the header, the work is delegated to corresponding method.
Parameters
*ckpt - checkpoint instance, that we are restoring from
Returns
0 upon succes
Definition at line 87 of file tcmi_ckpt_openfile.c.
References mdbg, tcmi_ckpt_openfile_generic_hdr::restore_type, TCMI_CKPT_OPENFILE_DUPFILE, TCMI_CKPT_OPENFILE_NEWFILE, tcmi_ckpt_openfile_read_dupfd(), tcmi_ckpt_openfile_read_newfd(), and tcmi_ckpt_read().
Referenced by tcmi_ckpt_read_files().
 {
     int err = -EINVAL;
     struct tcmi_ckpt_openfile_generic_hdr hdr;
     if (tcmi_ckpt_read(ckpt, &hdr, sizeof(hdr)) < 0) {
             mdbg(ERR3, "Error reading file generic header");
             err = -EINVAL;
             goto exit0;
     }
     mdbg(INFO3, "Read generic file header restore type: %08x", hdr.restore_type);
     switch (hdr.restore_type) {
         case TCMI_CKPT_OPENFILE_NEWFILE:
             err = tcmi_ckpt_openfile_read_newfd(ckpt);
             break;
         case TCMI_CKPT_OPENFILE_DUPFILE:
             err = tcmi_ckpt_openfile_read_dupfd(ckpt);
             break;
         default:
             mdbg(ERR3, "Unknown restore type %x", hdr.restore_type);
             err = -EINVAL;
             break;
     }
     return err;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_openfile_read_dupfd (struct tcmi_ckpt * ckpt) static
<<private>> Reads a duplicate file descriptor chunk from the checkpoint file.
The original file descriptor (dup_fd) is duplicated into the file descriptor of this chunk (fd). Both then refer to the same file.
Parameters
*ckpt - checkpoint instance
Returns
0 upon succes
Definition at line 256 of file tcmi_ckpt_openfile.c.
References tcmi_ckpt_openfile_dupfile_hdr::dup_fd, tcmi_ckpt_openfile_dupfile_hdr::fd, mdbg, and tcmi_ckpt_read().
Referenced by tcmi_ckpt_openfile_read().
 {
     struct tcmi_ckpt_openfile_dupfile_hdr dup_hdr;
     int err = 0;
     if (tcmi_ckpt_read(ckpt, &dup_hdr, sizeof(dup_hdr)) < 0) {
         mdbg(ERR3, "Error reading dupfd chunk");
         goto exit0;
     }
     if ((err = sys_dup2(dup_hdr.dup_fd, dup_hdr.fd)) != dup_hdr.fd) {
         mdbg(ERR3, "Error duplicating file descriptor %d into %d, error=%d!",
              dup_hdr.dup_fd, dup_hdr.fd, err);
         goto exit0;
     }
     mdbg(INFO4, "Restored duplicate file descriptor fd=%d, dup_fd=%d", dup_hdr.fd, dup_hdr.dup_fd);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_openfile_read_newfd (struct tcmi_ckpt * ckpt) static
<<private>> Reads a new file chunk from the checkpoint file.
This includes:
file descriptor
current position in the file
length of the file pathname
filepathname Opens the file with the same descriptor(might require using dup2 system call) and seeks to the specified position. Since the stdin/stdout/stderr might appear in the checkpoint image, we skip those for now - they are of type character device.
Parameters
*ckpt - checkpoint instance
Definition at line 293 of file tcmi_ckpt_openfile.c.
References tcmi_ckpt_openfile_newfile_hdr::fd, fd, tcmi_ckpt_openfile_newfile_hdr::flags, mdbg, tcmi_ckpt_openfile_newfile_hdr::mode, tcmi_ckpt_openfile_newfile_hdr::pathname_size, tcmi_ckpt_openfile_newfile_hdr::pos, tcmi_ckpt_read(), and tcmi_ckpt_openfile_newfile_hdr::type.
Referenced by tcmi_ckpt_openfile_read().
 {
     struct tcmi_ckpt_openfile_newfile_hdr new_hdr;
     mm_segment_t old_fs;
     int fd = -1;
     /* page for the filepathname */
     unsigned long page;
     old_fs = get_fs();
     set_fs(get_ds());
     if (tcmi_ckpt_read(ckpt, &new_hdr, sizeof(new_hdr)) < 0) {
         mdbg(ERR3, "Error reading newfd chunk");
         goto exit0;
     }
     mdbg(INFO3, "Read: Fd: %ld, Pos %llu, File name size: %lu, Flags: %08lo, Mode: %08lo", (long)new_hdr.fd, (unsigned long long)new_hdr.pos, (unsigned long)new_hdr.pathname_size, (unsigned long)new_hdr.flags, (unsigned long)new_hdr.mode);
     if ( new_hdr.pathname_size >= PAGE_SIZE )
         goto exit0;
     /* resolve the path name. */
     if (!(page = __get_free_page(GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate page for file pathname!");
         goto exit0;
     }
     if (tcmi_ckpt_read(ckpt, (char *)page, new_hdr.pathname_size) < 0) {
         mdbg(ERR3, "Error reading file pathname chunk");
         goto exit1;
     }
     /* reopen directory and regular files  */
     if ((S_ISDIR(new_hdr.type) || S_ISREG(new_hdr.type) || S_ISCHR(new_hdr.type) || S_ISFIFO(new_hdr.type))) {
         /* open */
         if ((fd = do_sys_open(AT_FDCWD, (char*)page, (int)new_hdr.flags, (int)new_hdr.mode)) < 0) {
             mdbg(ERR3, "Error opening file '%s', err=%d", (char*)page, fd);
             goto exit1;
         }
         /* setup the file position */
         if (new_hdr.pos != vfs_llseek(current->files->fdt->fd[fd], new_hdr.pos, 0)) {
             mdbg(ERR3, "Failed to set position %Lx in file '%s'", new_hdr.pos, (char*)page);
             goto exit1;
         }
     }
     /*
     if ( S_ISCHR(new_hdr.type) || S_ISFIFO(new_hdr.type) ){ // Forward operations via proxyfile
         mdbg(INFO3, "File '%s' fd = %d will be accesed trought proxyfile", (char*)page, new_hdr.fd);
         tcmi_ckpt_proxy_path((char*)page, (char*)page);
         mdbg(INFO3, "Opening file '%s' fd = %d", (char*)page, new_hdr.fd);
         if ((fd = sys_open((char*)page, new_hdr.flags, new_hdr.mode)) < 0) {
             mdbg(ERR3, "Error opening file '%s', err=%d", (char*)page, fd);
             goto exit1;
         }
     }
     */
     /* set the original descriptor of the file */
     if (new_hdr.fd != fd) {
         mdbg(INFO3, "Duplicating file descriptor %d into %d!", fd, new_hdr.fd);
         if (sys_dup2(fd, new_hdr.fd) != new_hdr.fd) {
             mdbg(ERR3, "Error duplicating file descriptor %d into %d!", fd, new_hdr.fd);
             goto exit1;
         }
         sys_close(fd);
     }
     mdbg(INFO4, "Restored new file descriptor fd=%d, pos=%Lx, type=%0o, "
          "pathname_size=%d, pathname='%s'",
          new_hdr.fd, new_hdr.pos, new_hdr.type, new_hdr.pathname_size, (char*)page);
     free_page(page);
     set_fs(old_fs);
     return 0;
     /* error handling */
  exit1:
     free_page(page);
  exit0:
     set_fs(old_fs);
     return -EINVAL;
 }
static int tcmi_ckpt_openfile_supported (struct inode * inode) inline static
<<public>> Class method - checks if the specified file(represented by its inode) is supported by checkpoint.
Parameters
*inode - inode to be checked
Definition at line 147 of file tcmi_ckpt_openfile.h.
Referenced by tcmi_ckpt_file_count().
 {
     return (S_ISREG(inode->i_mode) || S_ISDIR(inode->i_mode) || S_ISCHR(inode->i_mode) || S_ISFIFO(inode->i_mode) );
 }
int tcmi_ckpt_openfile_write (struct tcmi_ckpt * ckpt, int fd, struct file * file)
<<public>> Writes an open file information into the checkpoint file.
Writing the information about an open file requires:
checking if there is the same file object already stored in the file descriptor cache of the checkpoint. This indicates that such file has already been written into the checkpoint. In that case we delegate the work to write_dupfd.
othewise we delegate the work to write_newfd method that stores the full file information in about the file.
Parameters
*ckpt - checkpoint instance, that we are writing into
fd - file descriptor of associated with the file object
*file - file whose information is be written
Returns
0 upon succes
Definition at line 60 of file tcmi_ckpt_openfile.c.
References dup_fd, tcmi_ckpt_fdcache_lookup(), tcmi_ckpt_openfile_write_dupfd(), and tcmi_ckpt_openfile_write_newfd().
Referenced by tcmi_ckpt_write_files().
 {
     int dup_fd;
     int err;
     /* search for the file descriptor in the cache first */
     if ( (dup_fd = tcmi_ckpt_fdcache_lookup(ckpt, file)) >= 0)
         err = tcmi_ckpt_openfile_write_dupfd(ckpt, fd, dup_fd);
     /* not found, write the whole file details. */
     else
         err = tcmi_ckpt_openfile_write_newfd(ckpt, fd, file);
     return err;
 }
static int tcmi_ckpt_openfile_write_dupfd (struct tcmi_ckpt * ckpt, int fd, int dup_fd) static
<<private>> Writes a duplicate file descriptor chunk into the checkpoint file.
Parameters
*ckpt - this checkpoint instance
fd - original file descriptor
dup_fd - duplicate file descriptor that references the same file as fds
Returns
0 upon succes
Definition at line 133 of file tcmi_ckpt_openfile.c.
References tcmi_ckpt_openfile_dupfile_hdr::dup_fd, dup_fd, fd, tcmi_ckpt_openfile_dupfile_hdr::fd, mdbg, tcmi_ckpt_openfile_generic_hdr::restore_type, TCMI_CKPT_OPENFILE_DUPFILE, and tcmi_ckpt_write().
Referenced by tcmi_ckpt_openfile_write().
 {
     struct tcmi_ckpt_openfile_generic_hdr gen_hdr;
     struct tcmi_ckpt_openfile_dupfile_hdr dup_hdr;
     gen_hdr.restore_type = TCMI_CKPT_OPENFILE_DUPFILE;
     /* restore type identifier header */
     if (tcmi_ckpt_write(ckpt, &gen_hdr, sizeof(gen_hdr)) < 0) {
         mdbg(ERR3, "Error writing file generic header");
         goto exit0;
     }
     dup_hdr.fd = fd;
     dup_hdr.dup_fd = dup_fd;
     if (tcmi_ckpt_write(ckpt, &dup_hdr, sizeof(dup_hdr)) < 0) {
         mdbg(ERR3, "Error writing dupfd chunk");
         goto exit0;
     }
     mdbg(INFO3, "Written dupfd  fd=%d, dup_fd=%d", fd, dup_fd);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_openfile_write_newfd (struct tcmi_ckpt * ckpt, int fd, struct file * file) static
<<private>> Writes a new file chunk into the checkpoint file.
This includes:
file descriptor
current position in the file
length of the file pathname
filepathname
Parameters
*ckpt - this checkpoint instance
fd - file descriptor
*file - file object to be written into the checkpoint
Returns
0 upon succes
Definition at line 170 of file tcmi_ckpt_openfile.c.
References create_proxyfs_name(), tcmi_ckpt_openfile_newfile_hdr::fd, fd, proxyfs_file_identifier::file_ident, tcmi_ckpt_openfile_newfile_hdr::flags, is_dev_null(), is_proxyfs_file(), mdbg, tcmi_ckpt_openfile_newfile_hdr::mode, tcmi_ckpt_openfile_newfile_hdr::pathname_size, tcmi_ckpt_openfile_newfile_hdr::pos, proxyfs_server_overtake_file(), tcmi_ckpt_openfile_generic_hdr::restore_type, tcmi_ckpt_fdcache_add(), TCMI_CKPT_OPENFILE_NEWFILE, tcmi_ckpt_write(), and tcmi_ckpt_openfile_newfile_hdr::type.
Referenced by tcmi_ckpt_openfile_write().
 {
     struct tcmi_ckpt_openfile_generic_hdr gen_hdr;
     struct tcmi_ckpt_openfile_newfile_hdr new_hdr;
     /* page for the filepathname */
     unsigned long page;
     char *pathname;
     gen_hdr.restore_type = TCMI_CKPT_OPENFILE_NEWFILE;
     /* write the generic header first */
     if (tcmi_ckpt_write(ckpt, &gen_hdr, sizeof(gen_hdr)) < 0) {
         mdbg(ERR3, "Error writing file generic header");
         goto exit0;
     }
     new_hdr.fd = fd;
     new_hdr.pos = file->f_pos;
     new_hdr.flags = file->f_flags;
     new_hdr.mode = file->f_mode;
     new_hdr.type = file->f_dentry->d_inode->i_mode;
     new_hdr.pathname_size = 0;
     mdbg(INFO3, "File pos: %llu", (unsigned long long)file->f_pos);
     mdbg(INFO3, "Write: Fd: %ld, Pos %llu, File name size: %lu, Flags: %08lo, Mode: %08lo", (long)new_hdr.fd, (unsigned long long)new_hdr.pos, (unsigned long)new_hdr.pathname_size, (unsigned long)new_hdr.flags, (unsigned long)new_hdr.mode);
     /* resolve the path name. */
     if (!(page = __get_free_page(GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate page for file pathname!");
         goto exit0;
     }
     // By default files are simply reopened
     // WARNING: Very important! Buffer length is returned as a PAGE_SIZE - 1000. THe d_path fills in path from the end of the buffer
     // and if we return full buffer size, we are not able to append anything to the string, but we want to do that for the proxy files!
     if (IS_ERR(pathname = d_path(&file->f_path, (char*)page, PAGE_SIZE - 1000))) {
         mdbg(ERR3, "Can't resolve pathname for '%s'", file->f_dentry->d_name.name);
         goto exit1;
     }
     if ( !is_proxyfs_file(pathname) && ((S_ISCHR(new_hdr.type) || S_ISFIFO(new_hdr.type))) ){ // Special file, use proxyfs
         // Overtake only for shadow tasks and exclude dev-null
         if( current->tcmi.tcmi_task && current->tcmi.task_type == shadow && !is_dev_null(pathname) ){
             struct proxyfs_file_identifier* fileident = proxyfs_server_overtake_file(fd);
             if( fileident == NULL ){
                 mdbg(ERR3, "Registering file in proxyfs_server failed!");
                 goto exit1;
             }
             mdbg(INFO3, "BEFORE PROXY FS NAME: %s", pathname);
             create_proxyfs_name(current, pathname, fileident->file_ident);
             mdbg(INFO3, "AFTER PROXY FS NAME: %s", pathname);
         }
     }
     new_hdr.pathname_size = strlen(pathname) + 1;
     /* write the header and the pathname into the checkpoint */
     if (tcmi_ckpt_write(ckpt, &new_hdr, sizeof(new_hdr)) < 0) {
         mdbg(ERR3, "Error writing newfd chunk");
         goto exit1;
     }
     if (tcmi_ckpt_write(ckpt, pathname, new_hdr.pathname_size) < 0) {
         mdbg(ERR3, "Error writing file pathname chunk");
         goto exit1;
     }
     tcmi_ckpt_fdcache_add(ckpt, fd, file);
     mdbg(INFO4, "Written new file descriptor fd=%d, type=%0o '%s'", fd, new_hdr.type, pathname);
     free_page(page);
     return 0;
     /* error handling */
  exit1:
     free_page(page);
  exit0:
     return -EINVAL;
 }
Variable Documentation
struct tcmi_ckpt_sig_hdr __attribute__