Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/tcmi/migration/tcmi_migcom.c File Reference
tcmi_migcom.c File Reference
#include <tcmi/task/tcmi_taskhelper.h>
#include <tcmi/task/tcmi_shadowtask.h>
#include <tcmi/task/tcmi_guesttask.h>
#include <tcmi/lib/util.h>
#include "tcmi_migcom.h"
#include <tcmi/manager/tcmi_penmigman.h>
#include <tcmi/migration/fs/fs_mounter_register.h>
#include <tcmi/migration/fs/fs_mounter.h>
#include "tcmi_npm_params.h"
#include <director/director.h>
#include <dbg.h>
Data Structures
struct immigrate_startup_params
Helper struct to be passed to immigration statup thread.
Macros
#define TCMI_MIGCOM_PRIVATE
Functions
static int mount_proxyfs (struct kkc_sock *sock)
static int mount_local_procfs (struct kkc_sock *sock)
Mounts local machine procfs into some directory in chrooted env, so that it can be later accessed if required.
static int tcmi_task_mount_proxyfs (void *self, struct tcmi_method_wrapper *wr)
int tcmi_migcom_emigrate_ccn_ppm_p (pid_t pid, struct tcmi_migman *migman)
<<public>> Migrates a task from a CCN to a PEN.
int tcmi_migcom_emigrate_ccn_npm (pid_t pid, struct tcmi_migman *migman, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
<<public>> Migrates non-preemptively a task from a CCN to a PEN
int tcmi_migcom_immigrate (struct tcmi_msg *m, struct tcmi_migman *migman)
<<public>> Immigrates a task - handles accepting the task on the PEN side.
int tcmi_migcom_migrate_home_ppm_p (pid_t pid)
<<public>> Migrates a task back to its home node using preemptive migration with physical checkpoint file.
static int tcmi_migcom_migrated_task (void *data)
<<private>> This method represents a kernel thread that will eventually become the 'immigrated' task.
int tcmi_migcom_guest_fork (struct task_struct *parent, struct task_struct *child, struct tcmi_migman *migman)
<<public>> Fork of guest.
int tcmi_migcom_shadow_fork (struct task_struct *parent, struct task_struct *child, struct tcmi_migman *migman)
<<public>> Fork of shadow
static void tcmi_migcom_mig_mode_handler (void)
<<private>> This handler is invoked when the sig_unused hook finds a non-NULL entry in the clondike record in the task_struct.
Variables
static const char proc_path [] = "/mnt/local/proc"
Data Structure Documentation
struct immigrate_startup_params
Helper struct to be passed to immigration statup thread.
Definition at line 259 of file tcmi_migcom.c.
Data Fields
struct completion guest_ready fs_ready used to signal the thread the guest(or fs mount respectively) is ready
int16_t fsgid
int16_t fsuid Credentials that can be used for fs mounting.
struct fs_mount_params * mount_params Params for mounting of distributed fs.
struct kkc_sock * sock Migman socket.
. used to determine peers address so that we can mount its proxyfs
Macro Definition Documentation
#define TCMI_MIGCOM_PRIVATE
Definition at line 36 of file tcmi_migcom.c.
Function Documentation
static int mount_local_procfs (struct kkc_sock * sock) static
Mounts local machine procfs into some directory in chrooted env, so that it can be later accessed if required.
Definition at line 95 of file tcmi_migcom.c.
References mdbg, minfo, mk_dir(), and proc_path.
Referenced by tcmi_migcom_migrated_task().
{
     struct nameidata nd;
     int err;
     err = path_lookup(proc_path, LOOKUP_FOLLOW | LOOKUP_DIRECTORY, &nd);
     if ( err ) {
         minfo(ERR1, "Failed to lookup path %s: %d. Trying to create", proc_path, err);
         err = mk_dir(proc_path, 777);
         if (err) {
             goto exit0;
         }
     }
     err = do_mount("none", proc_path, "proc", 0, NULL);
     mdbg(INFO2, "Procfs mount result: %d", err);
     if ( err ) {
         minfo(ERR1, "Failed to mount filesystem: %d", err);
         goto exit0;
     }
 exit0:
     return err;
 }
static int mount_proxyfs (struct kkc_sock * sock) static
Definition at line 48 of file tcmi_migcom.c.
References KKC_MAX_ARCH_LENGTH, kkc_sock_getarchname(), kkc_sock_getpeername(), KKC_SOCK_MAX_ADDR_LENGTH, mdbg, and minfo.
Referenced by tcmi_migcom_migrated_task(), and tcmi_task_mount_proxyfs().
{
     int err = 0, len;
     char buffer[KKC_MAX_ARCH_LENGTH + KKC_SOCK_MAX_ADDR_LENGTH + 2];
     char* last_colon_char;
     struct cred* new_cred;
     new_cred = prepare_creds();
     if ( !new_cred )
         return -ENOMEM;
     // TODO: Make mount dir configurable?
     memset(buffer, 0, KKC_MAX_ARCH_LENGTH + KKC_SOCK_MAX_ADDR_LENGTH + 2);
     kkc_sock_getarchname(sock, buffer, KKC_MAX_ARCH_LENGTH);
     len = strlen(buffer);
     buffer[len] = ':';
     kkc_sock_getpeername(sock, buffer + len + 1, KKC_SOCK_MAX_ADDR_LENGTH);
     // TODO: Ugly ugly... works only for specific format of string and in addition port is hardcoded here
     last_colon_char = strrchr(buffer, ':');
     sprintf(last_colon_char+1, "%d", 1112);
     mdbg(INFO2, "Going to mount proxyfs on dev: %s fsuid: %d euid: %d csa: %d euid: %d uid: %d, suid: %d", buffer, current_fsuid(), current_euid(), capable(CAP_SYS_ADMIN), current_euid(), current_uid(), current_suid() );
     // TODO: Ohh man.. this is something terrible.. we should fiddle better with the fs rights, so that we do not need this
     // The problem is, that all works fine for newly created immigrated processes, since they have these capabilities, but
     // when we start using forked processes, they do not and they have a lot of problems with FS access, for example to proxy-fs
     cap_raise (new_cred->cap_effective, CAP_SYS_ADMIN);
     cap_raise (new_cred->cap_effective, CAP_DAC_READ_SEARCH);
     cap_raise (new_cred->cap_effective, CAP_DAC_OVERRIDE);
     cap_raise (new_cred->cap_effective, CAP_FOWNER);
     cap_raise (new_cred->cap_effective, CAP_FSETID);
     commit_creds(new_cred);
     err = do_mount(buffer, "/mnt/proxy", "proxyfs", 0, NULL);
     mdbg(INFO2, "After Proxyfs mount: %d", err);
     if ( err ) {
         minfo(ERR1, "Failed to mount filesystem: %d", err);
         goto exit0;
     }
 exit0:
     return err;
 }
static int tcmi_task_mount_proxyfs (void * self, struct tcmi_method_wrapper * wr) static
Definition at line 119 of file tcmi_migcom.c.
References minfo, mount_proxyfs(), tcmi_method_wrapper_data(), and TCMI_TASK_KEEP_PUMPING.
Referenced by tcmi_migcom_guest_fork().
{
     int res;
     struct kkc_sock* sock = *(struct kkc_sock**)tcmi_method_wrapper_data(wr);
     if ( (res =mount_proxyfs(sock)) ) {
         minfo(ERR1, "Failed to mount proxy filesystem: %d", res);
         // Kill current process.. do not exit via kill me as it does not invoke exit hook
         force_sig(SIGKILL, current);
     }
     return TCMI_TASK_KEEP_PUMPING;
 }
Variable Documentation
const char proc_path[] = "/mnt/local/proc" static
Definition at line 93 of file tcmi_migcom.c.
Referenced by mount_local_procfs().