Clondike: tcmi_ctlfs_entry class
tcmi_ctlfs_entry class
control filesystem
This class represents a generic entry in the tcmi control file system.
Modules
tcmi_ctlfs_dir class
This class represents a directory in the tcmi control file system.
tcmi_ctlfs_file class
A file in the TCMI control file system is used to export object interfaces.
tcmi_ctlfs_symlink class
This class provides a robust solution for symbolic link creation.
Data Structures
struct tcmi_ctlfs_entry
An entry compound structure.
struct tcmi_ctlfs_ops
entry operations that support polymorphism
Macros
#define MAX_ENTRY_NAME_LEN 256
Maximum entry name length.
#define TCMI_CTLFS_DENTRY_TO_ENTRY(dentry) TCMI_CTLFS_ENTRY(dentry->d_fsdata)
Extracts the entry object from the dentry.
#define TCMI_CTLFS_ENTRY(e) ((struct tcmi_ctlfs_entry *)e)
Casts a child entry to the super class.
Typedefs
typedef void callback (struct tcmi_ctlfs_entry *, void *)
Callback method of an object when traversing through predecessors.
Functions
static void tcmi_ctlfs_add_depth (struct tcmi_ctlfs_entry *self, void *curr_depth)
<<private>> Helper callback function when calculating entry depth.
static void tcmi_ctlfs_add_length (struct tcmi_ctlfs_entry *self, void *curr_length)
<<private>> Helper callback function when calculating entry pathname length.
static void tcmi_ctlfs_add_path (struct tcmi_ctlfs_entry *self, void *buf_data)
<<private>> Helper callback method when filling the entry's pathname The entry fills in its name and the '/' as prefix to the current end of the buffer.
static void tcmi_ctlfs_entry_release (struct tcmi_ctlfs_entry *self)
<<private>> This private method is responsible for freeing any resources the entry is currently using(currently nothing).
static struct inode * tcmi_ctlfs_get_inode (struct inode *dir, struct super_block *sb, mode_t mode, const struct inode_operations *i_ops, const struct file_operations *f_ops)
<<private>> A method for inode allocation.
static int tcmi_ctlfs_entry_alloc_dentry (struct tcmi_ctlfs_entry *self, struct tcmi_ctlfs_entry *parent, struct inode *inode)
<<private>> The new dentry is allocated based on the parent's dentry and the current name of the ctlfs entry.
static int tcmi_ctlfs_entry_exists (struct tcmi_ctlfs_entry *self, const char *name)
<<private>> Checks whether a directory entry contains entry of the specified name
static int tcmi_ctlfs_dentry_delete (struct dentry *dentry)
<<private>> This class method is a custom implementation of a VFS delete_dentry operation.
static void tcmi_ctlfs_dentry_release (struct dentry *dentry)
<<private>> This class method is a custom implementation of a VFS release_dentry operation.
int tcmi_ctlfs_entry_init (struct tcmi_ctlfs_entry *self, struct tcmi_ctlfs_entry *parent, mode_t mode, struct tcmi_ctlfs_ops *entry_ops, const struct inode_operations *i_ops, const struct file_operations *f_ops, const char namefmt[], va_list args)
<<public>> Initializes an instance.
int tcmi_ctlfs_rootentry_init (struct tcmi_ctlfs_entry *self, struct super_block *sb, mode_t mode, struct tcmi_ctlfs_ops *entry_ops, const struct inode_operations *i_ops, const struct file_operations *f_ops)
<<public>> Initializes a root entry instance.
void tcmi_ctlfs_entry_traverse_pred (struct tcmi_ctlfs_entry *self, callback *func, void *data)
<<public>> Iterator through entry predecessors.
int tcmi_ctlfs_entry_depth (struct tcmi_ctlfs_entry *entry)
<<public>> Calculates the current depth of the entry in the tree.
int tcmi_ctlfs_entry_path_length (struct tcmi_ctlfs_entry *self)
<<public>> Calculates the length of the pathname string.
void tcmi_ctlfs_entry_fill_path (struct tcmi_ctlfs_entry *self, char *buffer, int length)
<<public>> Fills in the entry's pathname.
static void tcmi_ctlfs_entry_inc_links (struct tcmi_ctlfs_entry *self)
<<public>> Increments the number of links referencing this entry's inode.
static const char * tcmi_ctlfs_entry_name (struct tcmi_ctlfs_entry *self)
<<public>> Entry name accessor.
static int tcmi_ctlfs_entry_isroot (struct tcmi_ctlfs_entry *self)
<<public>> Checks whether a given entry is the root of the TCMI ctlfs tree.
static struct tcmi_ctlfs_entry * tcmi_ctlfs_entry_get (struct tcmi_ctlfs_entry *self)
<<public>> Instance accessor, Calls instance custom get method and increments the reference counter.
static struct tcmi_ctlfs_entry * tcmi_ctlfs_entry_get_parent (struct tcmi_ctlfs_entry *self)
<<public>> Returns parent entry, reference counter is incremented.
static void tcmi_ctlfs_entry_put (struct tcmi_ctlfs_entry *self)
<<public>> Calls the instance custom put method(if any) and Decrements the reference counter of the dentry that the instance uses to carry it through out the file system.
Variables
static struct dentry_operations tcmi_ctlfs_dentry_ops
Custom dentry delete operation for VFS.
Detailed Description
This class represents a generic entry in the tcmi control file system.
No instances of this class can be made. The goal is to provide generic functionality that can be used by specific file system entries:
Initialization/deletion/freeing of instances.
Instance reference counting - this is needed as we expect multiple threads of execution to access one entry at a time. This ensures no memory leaks will occur. The reference counting is not implemented from scratch. Each entry is associated with a VFS dentry. These are VFS objects that already have a reference counter. Each instance registers with VFS and receives a notification when the reference counter reaches 0 (tcmi_ctlfs_dentry_release()) and the associated dentry is to be freed. This approach provides a safe access to the entry instances from multiple threads of execution without writing an extra reference couting code.
entry location methods - a generic method that iterates through all predecessors of an entry is provided. This is used when determining the depth of the entry in the filesystem tree.
Data Structure Documentation
struct tcmi_ctlfs_entry
An entry compound structure.
Contains the associated dentry.
Definition at line 75 of file tcmi_ctlfs_entry.h.
Data Fields
struct dentry * dentry VFS directory entry(dentry) that is associated with an instance.
struct tcmi_ctlfs_ops * entry_ops custom operations
char name[256] current entry name
struct tcmi_ctlfs_ops
entry operations that support polymorphism
Definition at line 86 of file tcmi_ctlfs_entry.h.
Data Fields
void(* entry_release)(struct tcmi_ctlfs_entry *)
child class method, that frees all instance resources (but keeps the instance).
Field Documentation
void(* tcmi_ctlfs_ops::entry_release)(struct tcmi_ctlfs_entry *)
child class method, that frees all instance resources (but keeps the instance).
Definition at line 90 of file tcmi_ctlfs_entry.h.
Macro Definition Documentation
#define MAX_ENTRY_NAME_LEN 256
Maximum entry name length.
Definition at line 70 of file tcmi_ctlfs_entry.h.
#define TCMI_CTLFS_DENTRY_TO_ENTRY (dentry) TCMI_CTLFS_ENTRY(dentry->d_fsdata)
Extracts the entry object from the dentry.
Definition at line 124 of file tcmi_ctlfs_entry.h.
Referenced by tcmi_ctlfs_dentry_release(), tcmi_ctlfs_entry_get_parent(), tcmi_ctlfs_file_read(), tcmi_ctlfs_file_write(), and tcmi_ctlfs_symlink_follow_link().
#define TCMI_CTLFS_ENTRY (e) ((struct tcmi_ctlfs_entry *)e)
Casts a child entry to the super class.
Definition at line 126 of file tcmi_ctlfs_entry.h.
Referenced by tcmi_ctlfs_dir_vnew(), tcmi_ctlfs_genericfile_new(), tcmi_ctlfs_rootdir_new(), tcmi_ctlfs_symlink_get_link(), and tcmi_ctlfs_symlink_new().
Typedef Documentation
typedef void callback(struct tcmi_ctlfs_entry *, void *)
Callback method of an object when traversing through predecessors.
Definition at line 111 of file tcmi_ctlfs_entry.h.
Function Documentation
static void tcmi_ctlfs_add_depth (struct tcmi_ctlfs_entry * self, void * curr_depth) static
<<private>> Helper callback function when calculating entry depth.
Parameters
*self - pointer to this instance
*curr_depth - pointer to the current depth
Definition at line 267 of file tcmi_ctlfs_entry.c.
Referenced by tcmi_ctlfs_entry_depth().
 {
     (*((int *)curr_depth))++;
 }
static void tcmi_ctlfs_add_length (struct tcmi_ctlfs_entry * self, void * curr_length) static
<<private>> Helper callback function when calculating entry pathname length.
Parameters
*self - pointer to this instance
*curr_length - pointer to the current length
Definition at line 280 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_entry_path_length().
 {
     /* + 1 accounts for '/' */
     (*((int *)curr_length)) += strlen(tcmi_ctlfs_entry_name(self)) + 1;
 }
static void tcmi_ctlfs_add_path (struct tcmi_ctlfs_entry * self, void * buf_data) static
<<private>> Helper callback method when filling the entry's pathname The entry fills in its name and the '/' as prefix to the current end of the buffer.
Parameters
*self - pointer to this instance
*buf_data - buffer data that contain pointer to the buffer and its current length.
Definition at line 296 of file tcmi_ctlfs_entry.c.
References mdbg, and tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_entry_fill_path().
 {
     struct {
         char *buffer;
         int length;
     } *buf = buf_data;
     int cur = strlen(tcmi_ctlfs_entry_name(self));
     mdbg(INFO4, "Adding.. %s, buffer length=%d", tcmi_ctlfs_entry_name(self), buf->length);
     /* back up enough to print entry name with '/' prefix */
     buf->length -= cur;
     strncpy(buf->buffer + buf->length, tcmi_ctlfs_entry_name(self), cur);
     *(buf->buffer + --(buf->length)) = '/';
     mdbg(INFO4, "New buffer length=%d", buf->length);
 }
static int tcmi_ctlfs_dentry_delete (struct dentry * dentry) static
<<private>> This class method is a custom implementation of a VFS delete_dentry operation.
The delete_dentry is called by VFS when destroying the dentry associated with a particular tcmi_ctlfs_entry object. This happens when the dentry's reference counter reaches 0.
Parameters
*dentry - pointer to the dentry that is to be deleted
Returns
- always 1 since we don't want the VFS to put the dentry into the dentry_unused. This way the dentry will be unhashed and removed right away
Definition at line 462 of file tcmi_ctlfs_entry.c.
 {
     return 1;
 }
static void tcmi_ctlfs_dentry_release (struct dentry * dentry) static
<<private>> This class method is a custom implementation of a VFS release_dentry operation.
The release_dentry is called by VFS when releasing the dentry associated with a particular tcmi_ctlfs_entry object. This happens when the dentry's reference counter reaches 0.
Unlike previous VFS method, we are allowed to sleep as the dcache lock and dentry lock are not held anymore (see fs/dcache.c)
Parameters
*dentry - pointer to the dentry that is to be deleted
Returns
- always 1 since we don't want the VFS to put the dentry into the dentry_unused. This way the dentry will be unhashed and removed right away
Definition at line 482 of file tcmi_ctlfs_entry.c.
References minfo, TCMI_CTLFS_DENTRY_TO_ENTRY, and tcmi_ctlfs_entry_release().
 {
     /* get the instance first */
     struct tcmi_ctlfs_entry *self = TCMI_CTLFS_DENTRY_TO_ENTRY(dentry);
     if (self)
         tcmi_ctlfs_entry_release(self);
     else
         minfo(ERR2, "VFS issued dentry_release on a dentry without tcmi_ctlfs_instance!!");
 }
static int tcmi_ctlfs_entry_alloc_dentry (struct tcmi_ctlfs_entry * self, struct tcmi_ctlfs_entry * parent, struct inode * inode) static
<<private>> The new dentry is allocated based on the parent's dentry and the current name of the ctlfs entry.
The dentry is associated with the specified inode. The dentry is assigned our custom operations vector, so that we are informed about dentry destruction.
Parameters
*self - pointer to this instance
*parent - pointer to the parent entry - has to be a directory
*inode - pointer to the inode, that is to be associated with the new dentry.
Returns
0 upon success.
Definition at line 404 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_entry::dentry, mdbg, self, and tcmi_ctlfs_dentry_ops.
Referenced by tcmi_ctlfs_entry_init().
 {
     struct dentry *dentry;
     int error = 1;
     /* try allocating the dentry */
     if ((dentry = d_alloc_name(parent->dentry, self->name))) {
         d_add(dentry, inode); /* enters the dentry into hash queues */
         dentry->d_fsdata = (void *)self;
         dentry->d_op = &tcmi_ctlfs_dentry_ops;
         self->dentry = dentry;
         /* dget(dentry); Extra count - pin the dentry in core - not needed */
         error = 0;
     }
     else
         mdbg(ERR3, "Failed to allocate a new dentry for %s", self->name);
     return error;
 }
int tcmi_ctlfs_entry_depth (struct tcmi_ctlfs_entry * self)
<<public>> Calculates the current depth of the entry in the tree.
<<public>> Calculates the current depth of the entry in the tree.
Parameters
*self - pointer to this instance
Returns
- depth (0 denotes root entry)
Definition at line 208 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_add_depth(), and tcmi_ctlfs_entry_traverse_pred().
Referenced by tcmi_ctlfs_symlink_get_link().
 {
     int depth = 0;
     tcmi_ctlfs_entry_traverse_pred(self, tcmi_ctlfs_add_depth, &depth);
     return depth;
 }
static int tcmi_ctlfs_entry_exists (struct tcmi_ctlfs_entry * self, const char * name) static
<<private>> Checks whether a directory entry contains entry of the specified name
Parameters
*self - pointer to this instance
*name - pointer to the name to be checked
Returns
1 - if the entry of the specified name exists
Definition at line 432 of file tcmi_ctlfs_entry.c.
References self.
Referenced by tcmi_ctlfs_entry_init().
 {
     struct dentry *dentry;
     struct qstr q;
     int exists = 0;
     q.name = name;
     q.len = strlen(name);
     q.hash = full_name_hash(q.name, q.len);
     dentry = d_lookup(self->dentry, &q);
     /* dentry already exists, decrement its reference counter since lookup
      incremented it */
     if (dentry) {
         dput(dentry);
             exists = 1;
     }
     return exists;
 }
void tcmi_ctlfs_entry_fill_path (struct tcmi_ctlfs_entry * self, char * buffer, int length)
<<public>> Fills in the entry's pathname.
<<public>> Fills in the entry's pathname.
The pathname is being filled in reverse order starting from the end of the buffer.
Parameters
*self - pointer to this symlink instance
*buffer - buffer where store the pathname
length - size of the buffer allocated for the pathname - this is can be > pathname length, as the user might want to add some prefix to the pathname (e.g. ../'s)
Definition at line 241 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_add_path(), and tcmi_ctlfs_entry_traverse_pred().
Referenced by tcmi_ctlfs_symlink_get_link().
 {
     struct {
         char *buffer;
         int length;
     } buf_data;
     buf_data.buffer = buffer;
     /* account for terminating \0 */
     buf_data.length = --length;
     tcmi_ctlfs_entry_traverse_pred(self, tcmi_ctlfs_add_path, &buf_data);
 }
static struct tcmi_ctlfs_entry* tcmi_ctlfs_entry_get (struct tcmi_ctlfs_entry * self) static read
<<public>> Instance accessor, Calls instance custom get method and increments the reference counter.
The user is now guaranteed, that the instance stays in memory while he is using it.
Parameters
*self - pointer to this instance
Returns
tcmi_ctlfs_entry instance
Definition at line 180 of file tcmi_ctlfs_entry.h.
References mdbg, self, and tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_entry_get_parent(), tcmi_ctlfs_entry_traverse_pred(), tcmi_ctlfs_get_root(), tcmi_ctlfs_symlink_new(), and tcmi_migman_init_ctlfs_dirs().
 {
     if (self) {
         mdbg(INFO4, "Incrementing ref. count of '%s'(%p)",
              tcmi_ctlfs_entry_name(self), self);
         dget(self->dentry);
     }
     return self;
 }
static struct tcmi_ctlfs_entry* tcmi_ctlfs_entry_get_parent (struct tcmi_ctlfs_entry * self) static read
<<public>> Returns parent entry, reference counter is incremented.
Parameters
*self - pointer to this instance
Returns
- parent entry.
Definition at line 197 of file tcmi_ctlfs_entry.h.
References self, TCMI_CTLFS_DENTRY_TO_ENTRY, and tcmi_ctlfs_entry_get().
Referenced by tcmi_ctlfs_entry_traverse_pred().
 {
     return tcmi_ctlfs_entry_get(TCMI_CTLFS_DENTRY_TO_ENTRY(self->dentry->d_parent));
 }
static void tcmi_ctlfs_entry_inc_links (struct tcmi_ctlfs_entry * self) inline static
<<public>> Increments the number of links referencing this entry's inode.
This method is used by directory entries. When a new child entry is added to the directory, the number of links in the inode->i_nlink needs to be adjusted as well as its parent's inode->i_nlink also needs to be incremented
Parameters
*self - pointer to this instance
Definition at line 138 of file tcmi_ctlfs_entry.h.
Referenced by tcmi_ctlfs_dir_vnew(), and tcmi_ctlfs_rootdir_new().
 {
     /* FIX ME: down i_sem */
     self->dentry->d_inode->i_nlink++;
     /* up i_sem */
 }
int tcmi_ctlfs_entry_init (struct tcmi_ctlfs_entry * self, struct tcmi_ctlfs_entry * parent, mode_t mode, struct tcmi_ctlfs_ops * entry_ops, const struct inode_operations * i_ops, const struct file_operations * f_ops, const char namefmt[], va_list args)
<<public>> Initializes an instance.
<<public>> Initializes an instance.
It follows these steps:
converts the nameformat string and the args into a regular string This will be the name assigned to the dentry
checks whether we have a valid parent directory
check whether an entry with the same name already exists in the parent directory entry(if so, an error is returned)
creates a new inode with the specified super block and operations
creates a new dentry associated with the inode.
sets a entry_operations specific to this particular entry type This supports polymorphism.
Parameters
*self - pointer to this instance
*parent - pointer to the parent entry - has to be a directory
*mode - file type and access rights for the inode
*entry_ops - custom operations of the child class
*i_ops - inode operations
*f_ops - file operations(also stored in the new inode)
namefmt - nameformat string (printf style)
args - arguments to the format string
Returns
0 upon success
Definition at line 66 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_entry::dentry, mdbg, self, tcmi_ctlfs_entry_alloc_dentry(), tcmi_ctlfs_entry_exists(), tcmi_ctlfs_entry_name(), and tcmi_ctlfs_get_inode().
Referenced by tcmi_ctlfs_dir_vnew(), tcmi_ctlfs_genericfile_new(), and tcmi_ctlfs_symlink_new().
 {
     struct inode *dir;
     struct inode *inode;
     vsnprintf(self->name, sizeof(self->name), namefmt, args);
     mdbg(INFO4, "Initializing a new tcmi_ctlfs_entry, '%s'(%p)", self->name, self);
     if (!parent) {
         mdbg(ERR4, "Can't initialized new entry '%s', no parent specified! ", self->name);
         goto exit0;
     }
     mdbg(INFO4, "Parent entry='%s'", tcmi_ctlfs_entry_name(parent));
     /* */
     dir = parent->dentry->d_inode;
     if (!S_ISDIR(dir->i_mode)) {
         mdbg(ERR3, "Can't initialize new entry '%s', parent entry is not a directory!", self->name);
         goto exit0;
     }
     /* check parent for an entry with 'name' */
     if (tcmi_ctlfs_entry_exists(parent, self->name)) {
         mdbg(ERR3,"Can't initialize new entry '%s', parent entry contains an entry of the same name!",
              self->name);
         goto exit0;
     }
     /* allocate a new inode */
     if (!(inode = tcmi_ctlfs_get_inode(dir, dir->i_sb, mode, i_ops, f_ops))) {
         mdbg(ERR3, "Failed to allocate an inode for '%s'", self->name);
         goto exit0;
     }
     /* allocate a new dentry, associated with the inode */
     if (tcmi_ctlfs_entry_alloc_dentry(self, parent, inode)) {
         mdbg(ERR3, "Failed to allocate a new dentry for %s", self->name);
         goto exit1;
     }
     /* Custom operations of the child class */
     self->entry_ops = entry_ops;
     return 0;
     /* error handling */
  exit1:
     iput(inode);
  exit0:
     return -ENOSPC;
 }
static int tcmi_ctlfs_entry_isroot (struct tcmi_ctlfs_entry * self) inline static
<<public>> Checks whether a given entry is the root of the TCMI ctlfs tree.
This is when the d_parent of the dentry of this tcmi_ctlfs_entry points back to the dentry
Parameters
*self - pointer to this instance
Returns
- 1 if it is root
Definition at line 165 of file tcmi_ctlfs_entry.h.
Referenced by tcmi_ctlfs_entry_traverse_pred().
 {
     struct dentry *dentry = self->dentry;
     return (dentry == dentry->d_parent);
 }
static const char* tcmi_ctlfs_entry_name (struct tcmi_ctlfs_entry * self) inline static
<<public>> Entry name accessor.
Parameters
*self - pointer to this instance
Returns
- entry name
Definition at line 151 of file tcmi_ctlfs_entry.h.
Referenced by tcmi_ctlfs_add_length(), tcmi_ctlfs_add_path(), tcmi_ctlfs_entry_get(), tcmi_ctlfs_entry_init(), tcmi_ctlfs_entry_put(), tcmi_ctlfs_entry_release(), and tcmi_ctlfs_symlink_release().
 {
     return self->dentry->d_name.name;
 }
int tcmi_ctlfs_entry_path_length (struct tcmi_ctlfs_entry * self)
<<public>> Calculates the length of the pathname string.
<<public>> Calculates the length of the pathname string.
Parameters
*self - pointer to this instance
Returns
pathname length
Definition at line 223 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_add_length(), and tcmi_ctlfs_entry_traverse_pred().
Referenced by tcmi_ctlfs_symlink_get_link().
 {
     int length = 1;
     tcmi_ctlfs_entry_traverse_pred(self, tcmi_ctlfs_add_length, &length);
     return length;
 }
static void tcmi_ctlfs_entry_put (struct tcmi_ctlfs_entry * self) inline static
<<public>> Calls the instance custom put method(if any) and Decrements the reference counter of the dentry that the instance uses to carry it through out the file system.
If the reference count reaches 0, the dentry will be released from the dentry cache and the instance of tcmi_ctlfs_entry will be freed. (VFS calls the d_delete() method of the dentry that we have customized
See Also
tcmi_ctlfs_dentry_delete and d_release() that is also customized in tcmi_ctlfs_dentry_release())
Parameters
*self - pointer to this instance
Definition at line 214 of file tcmi_ctlfs_entry.h.
References mdbg, self, and tcmi_ctlfs_entry_name().
Referenced by tcmi_ccnman_init_ctlfs_dirs(), tcmi_ccnman_stop_ctlfs_dirs(), tcmi_ccnman_stop_ctlfs_files(), tcmi_ccnmigman_stop_ctlfs_files(), tcmi_ctlfs_entry_traverse_pred(), tcmi_ctlfs_put_root(), tcmi_ctlfs_symlink_release(), tcmi_man_init_ctlfs_dirs(), tcmi_man_init_ctlfs_files(), tcmi_man_stop_ctlfs_dirs(), tcmi_man_stop_ctlfs_files(), tcmi_migman_init_ctlfs_dirs(), tcmi_migman_init_ctlfs_files(), tcmi_migman_stop_ctlfs_dirs(), tcmi_migman_stop_ctlfs_files(), tcmi_module_exit(), tcmi_penman_stop_ctlfs_files(), tcmi_penmigman_stop_ctlfs_files(), tcmi_sock_new(), tcmi_sock_put(), tcmi_task_init(), and tcmi_task_put().
 {
     if (self) {
         mdbg(INFO4, "Decrementing ref. count of '%s'(%p) (dentry: %p). Count before dec: %d",
              tcmi_ctlfs_entry_name(self), self, self->dentry, atomic_read(&self->dentry->d_count));
         dput(self->dentry);
     }
 }
static void tcmi_ctlfs_entry_release (struct tcmi_ctlfs_entry * self) inline static
<<private>> This private method is responsible for freeing any resources the entry is currently using(currently nothing).
When possible the child class is also notified. The instance is eventually destroyed.
Parameters
*self - pointer to this instance
Returns
0
Definition at line 324 of file tcmi_ctlfs_entry.c.
References mdbg, self, and tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_dentry_release().
 {
     mdbg(INFO4, "entry '%s' is being freed(%p)",
          tcmi_ctlfs_entry_name(self), self);
     /* free child class instance data? */
     if (self->entry_ops && self->entry_ops->entry_release) {
         self->entry_ops->entry_release(self);
     }
     kfree(self);
 }
void tcmi_ctlfs_entry_traverse_pred (struct tcmi_ctlfs_entry * self, callback * func, void * data)
<<public>> Iterator through entry predecessors.
<<public>> Iterator through entry predecessors.
The root entry is omitted. The callback function is supplied with the pointer to data that the users specified as parameter. This provides a safe way of iterating through all predecessors. The reference counters are used to control the access from multiple threads.
Parameters
*self - pointer to this instance
*func - pointer to the callback function
*data - pointer to the data that is passed the callback.
Definition at line 180 of file tcmi_ctlfs_entry.c.
References data, tcmi_ctlfs_entry_get(), tcmi_ctlfs_entry_get_parent(), tcmi_ctlfs_entry_isroot(), and tcmi_ctlfs_entry_put().
Referenced by tcmi_ctlfs_entry_depth(), tcmi_ctlfs_entry_fill_path(), and tcmi_ctlfs_entry_path_length().
 {
     struct tcmi_ctlfs_entry *parent;
     struct tcmi_ctlfs_entry *entry = self;
     /* increment the ref counter and get the instance */
     parent = tcmi_ctlfs_entry_get(entry);
     /* mdbg(INFO4, "getting %s", tcmi_ctlfs_entry_name(entry)); */
     while (!tcmi_ctlfs_entry_isroot(parent)) {
         entry = parent;
         parent = tcmi_ctlfs_entry_get_parent(entry);
         /* mdbg(INFO4, "getting %s", tcmi_ctlfs_entry_name(parent)); */
         (*func)(entry, data); /* notify the next entry */
         tcmi_ctlfs_entry_put(entry);
         /* mdbg(INFO4, "putting %s", tcmi_ctlfs_entry_name(entry)); */
     }
     /* decrement the root's reference counter too */
     tcmi_ctlfs_entry_put(parent);
     /* mdbg(INFO4, "putting %s", tcmi_ctlfs_entry_name(parent)); */
 }
static struct inode* tcmi_ctlfs_get_inode (struct inode * dir, struct super_block * sb, mode_t mode, const struct inode_operations * i_ops, const struct file_operations * f_ops) static read
<<private>> A method for inode allocation.
Currently the uid and gid is assigned based on the current's fsuid and fsgid. Block size is not relevant, set to page size. If the user doesn't specify any inode or file operations, the default(empty operations, but not NULL) assigned by the VFS will be kept.
If the user specified a parent directory inode, it's access rights are investigated and inherited by the new inode as follows:
if the parent has the SGID bit set, parent's gid is assigned to the new inode.
a parent SGID bit is set on the new inode, if the new inode is a directory
Parameters
*dir - inode of the parent directory for the new inode
*sb - super block of the filesystem where the inode is to be allocated
*mode - file type and access rights for the inode
*i_ops - inode operations
*f_ops - file operations (also stored in the new inode)
Returns
a pointer to the new inode or NULL
Definition at line 360 of file tcmi_ctlfs_entry.c.
References mdbg, minfo, and mode.
Referenced by tcmi_ctlfs_entry_init(), and tcmi_ctlfs_rootentry_init().
 {
     struct inode *inode = new_inode(sb);
     if (inode) {
         inode->i_mode = mode;
         inode->i_uid = current_fsuid();
         inode->i_gid = current_fsgid();
         inode->i_blocks = 0;
         inode->i_op  = (i_ops ? i_ops : inode->i_op);
         inode->i_fop = (f_ops ? f_ops : inode->i_fop);
         inode->i_atime = inode->i_mtime = inode->i_ctime = CURRENT_TIME;
         mdbg(INFO4, "New inode allocated, inode number = %ld", inode->i_ino);
         /* check parent inode's(if any) access rights */
         if (dir && (dir->i_mode & S_ISGID)) {
             inode->i_gid = dir->i_gid;
             if (S_ISDIR(mode))
                 inode->i_mode |= S_ISGID;
         }
     }
     else
         minfo(ERR3, "Failed to allocate a new inode");
     return inode;
 }
int tcmi_ctlfs_rootentry_init (struct tcmi_ctlfs_entry * self, struct super_block * sb, mode_t mode, struct tcmi_ctlfs_ops * entry_ops, const struct inode_operations * i_ops, const struct file_operations * f_ops)
<<public>> Initializes a root entry instance.
Parameters
*self - pointer to this instance
*sb - pointer to the super block of the filesystem
*mode - file type and access rights for the inode
*entry_ops - custom operations of the child class
*i_ops - inode operations
*f_ops - file operations(also stored in the new inode)
Returns
0 upon success
Definition at line 130 of file tcmi_ctlfs_entry.c.
References mdbg, tcmi_ctlfs_dentry_ops, and tcmi_ctlfs_get_inode().
Referenced by tcmi_ctlfs_rootdir_new().
 {
     struct dentry *root;
     struct inode *inode;
     mdbg(INFO3, "Initializing a root entry");
     if (!(inode = tcmi_ctlfs_get_inode(NULL, sb, mode, i_ops, f_ops))) {
         mdbg(ERR1, "Failed to allocate inode for root dentry!");
         goto exit0;
     }
     /* try allocating the dentry */
     if (!(root = d_alloc_root(inode))) {
         mdbg(ERR1, "Failed to allocate a root dentry!");
         goto exit1;
     }
     /* Initialize the dentry */
     root->d_fsdata = (void *)self;
     root->d_op = &tcmi_ctlfs_dentry_ops;
     self->dentry = root;
     sb->s_root = root;
     /* Custom operations of the child class */
     self->entry_ops = entry_ops;
     return 0;
     /* error handling*/
  exit1:
     iput(inode);
  exit0:
     return -ENOSPC;
 }
Variable Documentation
struct dentry_operations tcmi_ctlfs_dentry_ops static
Initial value:
=
{
    .d_delete   = tcmi_ctlfs_dentry_delete,
    .d_release      = tcmi_ctlfs_dentry_release,
}
Custom dentry delete operation for VFS.
Definition at line 493 of file tcmi_ctlfs_entry.c.
Referenced by tcmi_ctlfs_entry_alloc_dentry(), and tcmi_ctlfs_rootentry_init().