Clondike: tcmi_ckpt class
tcmi_ckpt class
checkpointing component
This is a helper class used by the checkpointing component that provides functionality to:
Modules
tcmi_ckpt_mm class
This is a <<singleton>> that takes care of (re)storing a process memory descriptor.
tcmi_ckpt_openfile class
This is a helper <<singleton>> class used by the checkpoint and provides functionality to:
tcmi_ckpt_vm_area class
This is a <<singleton>> that takes care of (re)storing a particular memory segment (VM area) into the checkpoint file.
tcmi_fdcache class
This is a helper class used by the checkpoint to keep track of already open file descriptors.
Data Structures
struct tcmi_ckpt_hdr
Describes the checkpoint header.
struct tcmi_ckpt
Compound structure that gathers necessary process information.
Macros
#define TCMI_CKPT(ckpt) ((struct tcmi_ckpt*)ckpt)
Casts to the checkpoint instance.
#define TCMI_CKPT_MAGIC 0xdeadbeef
a magic number for the header
#define tcmi_ckpt_foreach_openfile(file, fd)
<<public>> Iterates through all open files
Typedefs
typedef ssize_t vfs_method_t (struct file *, char __user *, size_t, loff_t *)
Describes the signature of the VFS method (typically vfs_read or vfs_write.
Functions
static int tcmi_ckpt_map_count (struct tcmi_ckpt *self)
<<private>> Calculates the number of memory regions of the current process.
static int tcmi_ckpt_file_count (struct tcmi_ckpt *self)
<<private>> Calculates the number of open files of the current process.
struct tcmi_ckpt_hdr __attribute__ ((__packed__))
struct tcmi_ckpt * tcmi_ckpt_new (struct file *file)
<<public>> Checkpoint constructor.
int tcmi_ckpt_write_hdr (struct tcmi_ckpt *self, int is_npm)
<<public>> Writes a checkpoint header.
int tcmi_ckpt_read_hdr (struct tcmi_ckpt *self)
<<public>> Reads a checkpoint header.
int tcmi_ckpt_write_files (struct tcmi_ckpt *self)
<<public>> Writes open files into the checkpoint.
int tcmi_ckpt_read_files (struct tcmi_ckpt *self)
<<public>> Reads open files from the checkpoint.
int tcmi_ckpt_write_vmas (struct tcmi_ckpt *self, int heavy)
<<public>> Writes process memory regions into the checkpoint.
int tcmi_ckpt_read_vmas (struct tcmi_ckpt *self)
<<public>> Reads process memory regions from the checkpoint.
int tcmi_ckpt_write_regs (struct tcmi_ckpt *self, struct pt_regs *regs)
<<public>> Writes process CPU registers into the checkpoint.
int tcmi_ckpt_read_regs (struct tcmi_ckpt *self, struct pt_regs *regs)
<<public>> Reads process CPU registers from the checkpoint.
static int tcmi_ckpt_check_magic (void *buf)
<<public>> Writes signals related stuff into the checkpoint.
static struct tcmi_ckpt * tcmi_ckpt_get (struct tcmi_ckpt *self)
<<public>> Instance accessor, increments the reference counter.
static void tcmi_ckpt_put (struct tcmi_ckpt *self)
<<public>> Releases the instance.
static int tcmi_ckpt_read_write (struct tcmi_ckpt *self, void *data, int count, vfs_method_t *vfs_method)
<<private>> Executes a specified VFS method on the checkpoint file.
static int tcmi_ckpt_write (struct tcmi_ckpt *self, void *data, int count)
<<public>> Writes a specified number of bytes into a checkpoint file.
static int tcmi_ckpt_read (struct tcmi_ckpt *self, void *data, int count)
<<public>> Reads a specified number of bytes from a checkpoint file.
static loff_t tcmi_ckpt_seek (struct tcmi_ckpt *self, loff_t offset, int origin)
<<public>> Seeks in the checkpoint file based on specified offset.
static unsigned long tcmi_ckpt_do_mmap (struct tcmi_ckpt *self, unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags)
<<public>> Helper method that performs a memory mapping on the checkpoint file at its current offset.
static loff_t tcmi_ckpt_page_align (struct tcmi_ckpt *self)
<<public>> Aligns the position in the checkpoint file to page boundary.
static int tcmi_ckpt_fdcache_add (struct tcmi_ckpt *self, int fd, struct file *file)
<<public>> Adds a file descriptor - file object pair into the fd cache.
static int tcmi_ckpt_fdcache_lookup (struct tcmi_ckpt *self, struct file *file)
<<public>> Searches the file descriptor cache for a file.
Variables
struct tcmi_ckpt __attribute__
Detailed Description
This is a helper class used by the checkpointing component that provides functionality to:
write current process into a checkpoint file
restore a current process from a checkpoint file
It doesn't do the whole job at once, it relies on its controlling class (checkpointing component). The checkpointing component instructs the checkpoint instance what to do in each step (this applies to creating the checkpoint as well as restoring the process execution).
Implementation is Linux kernel specific.
Data Structure Documentation
struct tcmi_ckpt_hdr
Describes the checkpoint header.
Definition at line 69 of file tcmi_ckpt.h.
Data Fields
enum arch_ids checkpoint_arch Architecture (hw) of the checkpointed data.
char comm[TASK_COMM_LEN] Process executable name.
int32_t file_count total count of open files.
int8_t is_32bit_application Flag, indicating whether the checkpointed application was 32 bit application (otherwise 64 bit is assumed)
int8_t is_npm 1, if this is checkpoint created as a result of non-preemptive migration request (0 otherwise)
int32_t magic magic number identifying the checkpoint file.
int32_t map_count total count of virtual memory areas.
struct tcmi_ckpt
Compound structure that gathers necessary process information.
Definition at line 87 of file tcmi_ckpt.h.
Data Fields
struct tcmi_fdcache * fdcache File descriptor cache - used when indentifying descriptors referencing the same file.
struct file * file Actual file used create/restore the process checkpoint.
struct tcmi_ckpt_hdr hdr Checkpoint header.
atomic_t ref_count Instance reference counter.
Macro Definition Documentation
#define TCMI_CKPT (ckpt) ((struct tcmi_ckpt*)ckpt)
Casts to the checkpoint instance.
Definition at line 103 of file tcmi_ckpt.h.
Referenced by tcmi_ckpt_new().
#define tcmi_ckpt_foreach_openfile (file, fd)
Value:
for (fd = 0, file = current->files->fdt->fd[fd];                    \
         fd < current->files->fdt->max_fds; fd++, file = current->files->fdt->fd[fd])       \
        if (test_bit(fd, current->files->fdt->open_fds))
<<public>> Iterates through all open files
Parameters
file - current file
fd - descriptor of the file Replaced macro FD_ISSET to function test_bit | by Jiri Rakosnik
Definition at line 336 of file tcmi_ckpt.h.
Referenced by tcmi_ckpt_file_count(), tcmi_ckpt_write_files(), and tcmi_taskhelper_flushfiles().
#define TCMI_CKPT_MAGIC 0xdeadbeef
a magic number for the header
Definition at line 106 of file tcmi_ckpt.h.
Referenced by tcmi_ckpt_check_magic(), tcmi_ckpt_read_hdr(), and tcmi_ckpt_write_hdr().
Typedef Documentation
typedef ssize_t vfs_method_t(struct file *, char __user *, size_t, loff_t *)
Describes the signature of the VFS method (typically vfs_read or vfs_write.
Definition at line 181 of file tcmi_ckpt.h.
Function Documentation
struct tcmi_ckpt_hdr __attribute__ ((__packed__))
static int tcmi_ckpt_check_magic (void * buf) inline static
<<public>> Writes signals related stuff into the checkpoint.
<<public>> Reads signals related stuff from the checkpoint. <<public>> Performs a quick check if the specified buffer contains a valid magic number of the checkpoint file.
Parameters
*buf - buffer containing the magic number
Returns
true when valid.
Definition at line 143 of file tcmi_ckpt.h.
References TCMI_CKPT_MAGIC.
Referenced by tcmi_ckptcom_restart().
 {
     return ((struct tcmi_ckpt_hdr*)buf)->magic == TCMI_CKPT_MAGIC;
 }
static unsigned long tcmi_ckpt_do_mmap (struct tcmi_ckpt * self, unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags) inline static
<<public>> Helper method that performs a memory mapping on the checkpoint file at its current offset.
After that the position is advanced by len bytes.
Parameters
*self - this checkpoint instance
addr - starting address where the
len - length of the region
prot - access rights of the pages included in the memory region
flags - memory region flags (see mm.h)
Returns
new file position or error (< 0)
Definition at line 271 of file tcmi_ckpt.h.
References mdbg, self, and tcmi_ckpt_seek().
Referenced by tcmi_ckpt_vm_area_read_h().
 {
     mdbg(INFO4, "Mapping VMA start:%08lx, len %08lx, prot: %08lx, flags: %08lx, pgoff: %08Lx",
          addr, len, prot, flags, self->file->f_pos >> PAGE_SHIFT);
     down_write(&current->mm->mmap_sem);
     addr = do_mmap_pgoff(self->file, addr, len, prot, flags, self->file->f_pos);  //Replaced function do_mmap to do_mmap_pgoff for kernel 3.7.x by Jiri Rakosnik
     up_write(&current->mm->mmap_sem);
     tcmi_ckpt_seek(self, len, 1);
     mdbg(INFO4, "Memory mapping at %08lx, new off %08Lx", addr, self->file->f_pos);
     return addr;
 }
static int tcmi_ckpt_fdcache_add (struct tcmi_ckpt * self, int fd, struct file * file) inline static
<<public>> Adds a file descriptor - file object pair into the fd cache.
This information will be used for later lookup of duplicate file descriptors.
Parameters
*self - this checkpoint instance
fd - file descriptor of the file
*file - file object - used for duplicate file descriptor lookup
Returns
0 upon success
Definition at line 312 of file tcmi_ckpt.h.
References self, and tcmi_fdcache_add().
Referenced by tcmi_ckpt_openfile_write_newfd().
 {
     return tcmi_fdcache_add(self->fdcache, fd, file);
 }
static int tcmi_ckpt_fdcache_lookup (struct tcmi_ckpt * self, struct file * file) inline static
<<public>> Searches the file descriptor cache for a file.
Parameters
*self - this checkpoint instance
*file - file object to be looked up
Returns
file descriptor of the file or error (< 0)
Definition at line 324 of file tcmi_ckpt.h.
References self, and tcmi_fdcache_lookup().
Referenced by tcmi_ckpt_openfile_write().
 {
     return tcmi_fdcache_lookup(self->fdcache, file);
 }
static int tcmi_ckpt_file_count (struct tcmi_ckpt * self) static
<<private>> Calculates the number of open files of the current process.
For each file check if the file is supported if so, adjust the counter.
An error is indicated if any of the files is:
socket
pipe
symlink
special file
Parameters
*self - this checkpoint instance
Returns
number of open files, or error (< 0)
Definition at line 345 of file tcmi_ckpt.c.
References count(), fd, mdbg, tcmi_ckpt_foreach_openfile, and tcmi_ckpt_openfile_supported().
Referenced by tcmi_ckpt_read_files(), tcmi_ckpt_read_hdr(), and tcmi_ckpt_write_hdr().
 {
     /* file descriptor count */
     int fd;
     int count = 0;
     int err = 0;
     struct file *file;
     struct inode *inode;
     /* Check each open file */
     tcmi_ckpt_foreach_openfile(file, fd) {
         inode = file->f_dentry->d_inode;
         if (!tcmi_ckpt_openfile_supported(inode)) {
             mdbg(ERR3, "Unsupported file mode detected %o [FD: %d]", inode->i_mode, fd);
             err = -EINVAL;
             goto exit0;
         }
         count++;
         /*mdbg(INFO4, "Scanned file fd=%d, type=%0o '%s'", fd, file->f_flags,
           file->f_dentry->d_name.name); */
     }
     mdbg(INFO4, "Found %d files, err=%d", count, err);
     return count;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static struct tcmi_ckpt* tcmi_ckpt_get (struct tcmi_ckpt * self) static read
<<public>> Instance accessor, increments the reference counter.
Parameters
*self - pointer to this checkpoint instance
Returns
tcmi_ckpt instance
Definition at line 154 of file tcmi_ckpt.h.
References self.
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static int tcmi_ckpt_map_count (struct tcmi_ckpt * self) static
<<private>> Calculates the number of memory regions of the current process.
We can't simply return current->map_count. We need to check for special regions that would prevent creating a valid checkpoint
For now, we have to verify that the memory region is not:
VM_IO - I/O mapped devices
VM_SHARED - shared memory - this will be included later on, when we support checkpointing and migration of LWP's
VM_RESERVED - special mappings
Parameters
*self - this checkpoint instance
Returns
number of memory regions, or error (< 0)
Definition at line 310 of file tcmi_ckpt.c.
References count(), mdbg, and vma_ignore.
Referenced by tcmi_ckpt_read_vmas(), and tcmi_ckpt_write_hdr().
 {
     struct vm_area_struct *vma;
     int count = 0;
     int err = 0;
     tcmi_ckpt_foreach_vma(vma) {
         if ( vma_ignore(self, vma) )
             continue;
         count++;
         /* Do not dump I/O mapped devices, shared memory, or special mappings */
         if (vma->vm_flags & (VM_IO | VM_SHARED | VM_RESERVED))
             err = -EINVAL;
         mdbg(INFO4, "Scanning area start:%08lx, end: %08lx, flags: %08lx, pageprot %08lx",
              vma->vm_start, vma->vm_end, vma->vm_flags, vma->vm_page_prot.pgprot);
     }
     mdbg(INFO4, "Found %d areas, mm indicates: %d", count, current->mm->map_count);
     return (err ? err : count);
 }
struct tcmi_ckpt* tcmi_ckpt_new (struct file * file) read
<<public>> Checkpoint constructor.
allocates a new instance
resets the byte counter
reserves an extra reference for the file
reset position in the file to the beginning
Parameters
*file - points to the file where the checkpoint is to be written/read
Returns
tcmi_ckpt instance or NULL
Definition at line 63 of file tcmi_ckpt.c.
References tcmi_ckpt::fdcache, tcmi_ckpt::file, mdbg, tcmi_ckpt::ref_count, TCMI_CKPT, and tcmi_ckpt_seek().
Referenced by tcmi_ckptcom_checkpoint(), and tcmi_ckptcom_restart().
 {
     struct tcmi_ckpt *ckpt;
     loff_t seek_res;
     if (!(ckpt = TCMI_CKPT(kmalloc(sizeof(struct tcmi_ckpt),
                        GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for TCMI ckpt");
         goto exit0;
     }
     get_file(file);
     ckpt->file = file;
     ckpt->fdcache = NULL;
     atomic_set(&ckpt->ref_count, 1);
     mdbg(INFO2, "Created new checkpoint %p", ckpt);
     /* reset the file position */
     seek_res = tcmi_ckpt_seek(ckpt, 0, 0);
     if ( seek_res < 0 ) {
         kfree(ckpt);
         return ERR_PTR(seek_res);
     }
     return ckpt;
     /* error handling */
  exit0:
     return NULL;
 }
static loff_t tcmi_ckpt_page_align (struct tcmi_ckpt * self) inline static
<<public>> Aligns the position in the checkpoint file to page boundary.
This is needed when reading or writing pages.
Parameters
*self - this checkpoint instance
Returns
new file position or error (< 0)
Definition at line 296 of file tcmi_ckpt.h.
References self.
Referenced by tcmi_ckpt_vm_area_read_h(), and tcmi_ckpt_vm_area_write_h().
 {
     return vfs_llseek(self->file, (self->file->f_pos + PAGE_SIZE - 1) & PAGE_MASK, 0);
 }
static void tcmi_ckpt_put (struct tcmi_ckpt * self) inline static
<<public>> Releases the instance.
Parameters
*self - pointer to this instance
Definition at line 168 of file tcmi_ckpt.h.
References mdbg, self, and tcmi_fdcache_put().
Referenced by tcmi_ckptcom_checkpoint(), and tcmi_ckptcom_restart().
 {
     if (self && atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying TCMI ckpt, %p", self);
         fput(self->file);
         tcmi_fdcache_put(self->fdcache);
         kfree(self);
     }
 }
static int tcmi_ckpt_read (struct tcmi_ckpt * self, void * data, int count) inline static
<<public>> Reads a specified number of bytes from a checkpoint file.
Parameters
*self - this checkpoint instance
*data - buffer for the data
count - number of bytes to be read
Returns
0 upon successful write of count bytes
Definition at line 234 of file tcmi_ckpt.h.
References mdbg, and tcmi_ckpt_read_write().
Referenced by tcmi_ckpt_fsstruct_read(), tcmi_ckpt_mm_read(), tcmi_ckpt_npm_params_read(), tcmi_ckpt_openfile_read(), tcmi_ckpt_openfile_read_dupfd(), tcmi_ckpt_openfile_read_newfd(), tcmi_ckpt_read_hdr(), tcmi_ckpt_read_rlimit(), tcmi_ckpt_regs_read(), tcmi_ckpt_sig_read(), tcmi_ckpt_tls_read(), tcmi_ckpt_vm_area_read(), tcmi_ckpt_vm_area_read_l(), and tcmi_ckpt_vm_area_stack_fixup().
 {
     mdbg(INFO3, "CKPT read to %p, count %d bytes", data, count);
     return tcmi_ckpt_read_write(self, data, count, (vfs_method_t*)vfs_read);
 }
int tcmi_ckpt_read_files (struct tcmi_ckpt * self)
<<public>> Reads open files from the checkpoint.
Parameters
*self - this checkpoint instance
Returns
0 upon success
Definition at line 223 of file tcmi_ckpt.c.
References tcmi_ckpt_file_count(), and tcmi_ckpt_openfile_read().
Referenced by tcmi_ckptcom_restart().
 {
     int err = 0;
     int i = 0;
     while ((i < self->hdr.file_count) && !err) {
         err = tcmi_ckpt_openfile_read(self);
         i++;
     }
     tcmi_ckpt_file_count(self);
     return err;
 }
int tcmi_ckpt_read_hdr (struct tcmi_ckpt * self)
<<public>> Reads a checkpoint header.
<<public>> Reads a checkpoint header.
The magic number has to match TCMI_CKPT_MAGIC.
Parameters
*self - this checkpoint instance
Returns
0 upon success
Definition at line 143 of file tcmi_ckpt.c.
References ARCH_I386, mdbg, self, tcmi_ckpt_file_count(), TCMI_CKPT_MAGIC, and tcmi_ckpt_read().
Referenced by tcmi_ckptcom_restart().
 {
     int err;
     if ((err = tcmi_ckpt_read(self, &self->hdr, sizeof(self->hdr))) < 0) {
         mdbg(ERR3, "Can't read checkpoint header %d", err);
         goto exit0;
     }
     if (self->hdr.magic != TCMI_CKPT_MAGIC) {
         mdbg(ERR3, "Invalid checkpoint magic: %08x, expected: %08x",
              self->hdr.magic, TCMI_CKPT_MAGIC);
         goto exit0;
     }
     mdbg(INFO4, "Read ckpt header - magic: %08x, map_count: %d, files: %d (Header size: %lu)",
          self->hdr.magic, self->hdr.map_count, self->hdr.file_count, (unsigned long)sizeof(self->hdr));
     if (tcmi_ckpt_fdcache_init(self) < 0) {
         mdbg(ERR3, "Error initializing file descriptor cache!!");
         goto exit0;
     }
     tcmi_ckpt_file_count(self);
     strncpy(current->comm, self->hdr.comm, sizeof(current->comm));
     /* TODO: To some arch file ? */
     #if defined(__x86_64__)
     if ( self->hdr.is_32bit_application )
         set_thread_flag(TIF_IA32); /* This flag must be set for 32bit applications running on 64 bit kernel */
     if ( self->hdr.checkpoint_arch == ARCH_I386 )
         set_personality(PER_LINUX32_3GB); /* Address space must be limited by 3GB, so that we are possibly able to migrate back */
     #endif
     mdbg(INFO3, "Read header. Architecture of checkpoint %d Is 32 bit app: %d", self->hdr.checkpoint_arch, self->hdr.is_32bit_application);
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
int tcmi_ckpt_read_regs (struct tcmi_ckpt * self, struct pt_regs * regs)
<<public>> Reads process CPU registers from the checkpoint.
int tcmi_ckpt_read_vmas (struct tcmi_ckpt * self)
<<public>> Reads process memory regions from the checkpoint.
<<public>> Reads process memory regions from the checkpoint.
Parameters
*self - this checkpoint instance
Returns
0 upon success
Definition at line 276 of file tcmi_ckpt.c.
References tcmi_ckpt_map_count(), and tcmi_ckpt_vm_area_read().
Referenced by tcmi_ckptcom_restart().
 {
     int err = 0;
     int i = 0;
     while ((i < self->hdr.map_count) && !err) {
         err = tcmi_ckpt_vm_area_read(self);
         i++;
     }
     tcmi_ckpt_map_count(self);
     return err;
 }
static int tcmi_ckpt_read_write (struct tcmi_ckpt * self, void * data, int count, vfs_method_t * vfs_method) inline static
<<private>> Executes a specified VFS method on the checkpoint file.
Parameters
*self - this checkpoint instance
*data - buffer for the data
count - number of bytes to be processed
*vfs_method - VFS method to be executed on the checkpoint and data
Returns
0 upon successful vfs method execution or an error (< 0)
Definition at line 194 of file tcmi_ckpt.h.
References mdbg, and self.
Referenced by tcmi_ckpt_read(), and tcmi_ckpt_write().
 {
     mm_segment_t old_fs;
     int result = 0;
     old_fs = get_fs();
     set_fs(get_ds());
     /* The cast to a user pointer is valid due to the set_fs() */
     result = vfs_method(self->file, (void __user *)data, count, &self->file->f_pos);
     mdbg(ERR3, "DEBUG read vfs method return = %d", result);
     set_fs(old_fs);
     return (result == count ? 0 : -EINVAL);
 }
static loff_t tcmi_ckpt_seek (struct tcmi_ckpt * self, loff_t offset, int origin) inline static
<<public>> Seeks in the checkpoint file based on specified offset.
Parameters
*self - this checkpoint instance
*offset - relative offset
origin - 0 - offset is absolute from file start 1 - offset is relative from current file position 2 - offset is relative from end of file
Returns
new file position or error (< 0)
Definition at line 252 of file tcmi_ckpt.h.
References self.
Referenced by tcmi_ckpt_do_mmap(), tcmi_ckpt_new(), and tcmi_ckpt_vm_area_write_h().
 {
     return vfs_llseek(self->file, offset, origin);
 }
static int tcmi_ckpt_write (struct tcmi_ckpt * self, void * data, int count) inline static
<<public>> Writes a specified number of bytes into a checkpoint file.
Parameters
*self - this checkpoint instance
*data - data to be written
count - number of bytes to be written
Returns
0 upon successful write of count bytes
Definition at line 220 of file tcmi_ckpt.h.
References tcmi_ckpt_read_write().
Referenced by tcmi_ckpt_fsstruct_write(), tcmi_ckpt_mm_write(), tcmi_ckpt_npm_params_write(), tcmi_ckpt_openfile_write_dupfd(), tcmi_ckpt_openfile_write_newfd(), tcmi_ckpt_regs_write(), tcmi_ckpt_tls_write(), tcmi_ckpt_vm_area_write_h(), tcmi_ckpt_vm_area_write_l(), tcmi_ckpt_write_hdr(), and tcmi_ckpt_write_rlimit().
 {
     return tcmi_ckpt_read_write(self, data, count, (vfs_method_t*)vfs_write);
 }
int tcmi_ckpt_write_files (struct tcmi_ckpt * self)
<<public>> Writes open files into the checkpoint.
Iterates through all open files of the current process and writes each file details into the checkpoint. Since some files might be just a duplicate file descriptor, we always check with the file descriptor cache. For duplicate file descriptors only simplified record is needed.
Parameters
*self - this checkpoint instance
Returns
0 upon success
Definition at line 194 of file tcmi_ckpt.c.
References fd, mdbg, tcmi_ckpt_foreach_openfile, and tcmi_ckpt_openfile_write().
Referenced by tcmi_ckptcom_checkpoint().
 {
     int fd = 0;
     int err = 0;
     struct file *file;
     /* Check each open file */
     tcmi_ckpt_foreach_openfile(file, fd) {
         mdbg(INFO4, "Processing '%s' fd=%d, type=%0o flags %08o, mode %08o, %p",
              file->f_dentry->d_name.name, fd, file->f_dentry->d_inode->i_mode & S_IFMT,
              file->f_flags, file->f_mode, file);
         if ( (err = tcmi_ckpt_openfile_write(self, fd, file)) < 0) {
             mdbg(INFO3, "Error writing file into checkpoint. Error %d", err);
             goto exit0;
         }
     }
     return 0;
     /* error handling */
  exit0:
     return err;
 }
int tcmi_ckpt_write_hdr (struct tcmi_ckpt * self, int is_npm)
<<public>> Writes a checkpoint header.
The checkpoint header consists of:
a magic number
total VM area count
total file count
Parameters
*self - this checkpoint instance
is_npm - Is this a non-preemptive checkpoint (otherwise preemptive is assumed)
Returns
0 upon success
Definition at line 105 of file tcmi_ckpt.c.
References is_npm, mdbg, self, tcmi_ckpt_file_count(), TCMI_CKPT_MAGIC, tcmi_ckpt_map_count(), and tcmi_ckpt_write().
Referenced by tcmi_ckptcom_checkpoint().
 {
     self->hdr.checkpoint_arch = ARCH_CURRENT;
     self->hdr.is_32bit_application = check_is_application_32bit();
     self->hdr.magic = TCMI_CKPT_MAGIC;
     self->hdr.is_npm = is_npm;
     if ((self->hdr.map_count = tcmi_ckpt_map_count(self)) < 0) {
         mdbg(ERR3, "Failed counting mmap's");
         goto exit0;
     }
     if ((self->hdr.file_count = tcmi_ckpt_file_count(self)) < 0) {
         mdbg(ERR3, "Failed counting open files");
         goto exit0;
     }
     if (tcmi_ckpt_fdcache_init(self) < 0) {
         mdbg(ERR3, "Error initializing file descriptor cache!!");
         goto exit0;
     }
     // No need to lock, exclusive access
     strncpy(self->hdr.comm, current->comm, sizeof(current->comm));
     mdbg(INFO3, "Writing header of size: %lu Address: %p First 4 bytes: %8x", (unsigned long)sizeof(self->hdr), &self->hdr, ((uint32_t*)(&self->hdr))[0]);
     return tcmi_ckpt_write(self, &self->hdr, sizeof(self->hdr));
     /* error handling */
  exit0:
     return -EINVAL;
 }
int tcmi_ckpt_write_regs (struct tcmi_ckpt * self, struct pt_regs * regs)
<<public>> Writes process CPU registers into the checkpoint.
int tcmi_ckpt_write_vmas (struct tcmi_ckpt * self, int heavy)
<<public>> Writes process memory regions into the checkpoint.
<<public>> Writes process memory regions into the checkpoint.
Parameters
*self - this checkpoint instance
heavy - if set a full checkpoint of all memory areas is made(see tcmi_ckptcom.c::tcmi_ckptcom_checkpoint()).
Returns
0 upon success
Definition at line 244 of file tcmi_ckpt.c.
References mdbg, TCMI_CKPT_VM_AREA_HEAVY, TCMI_CKPT_VM_AREA_LIGHT, tcmi_ckpt_vm_area_write(), type, and vma_ignore.
Referenced by tcmi_ckptcom_checkpoint().
 {
     struct vm_area_struct *vma;
     int err = 0;
     tcmi_ckpt_vm_area_t type;
     /* select the checkpoint type*/
     type = (heavy ? TCMI_CKPT_VM_AREA_HEAVY : TCMI_CKPT_VM_AREA_LIGHT);
     tcmi_ckpt_foreach_vma(vma) {
         if ( vma_ignore(self, vma) )
             continue;
         if ((err = tcmi_ckpt_vm_area_write(self, vma, type)) < 0) {
         mdbg(ERR3, "Can't write vm area start:%08lx, end: %08lx, flags: %08lx, pageprot %08lx",
              vma->vm_start, vma->vm_end, vma->vm_flags, vma->vm_page_prot.pgprot);
         goto exit0;
         }
     }
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
Variable Documentation
struct tcmi_ckpt __attribute__