Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/proxyfs/proxyfs_task.c File Reference
proxyfs_task.c File Reference
proxyfs task.
#include <asm/uaccess.h>
#include <linux/fs.h>
#include <linux/jiffies.h>
#include "proxyfs_task.h"
#include "proxyfs_peer.h"
#include "proxyfs_file.h"
Macros
#define PROXYFS_TASK_PROTECTED
#define PROXYFS_TASK_PRIVATE
#define PROXYFS_TASK_PROTECTED
#define PROXYFS_FILE_PROTECTED
Functions
struct proxyfs_task * proxyfs_task_run (int(*func)(void *), const char *addr_str)
<<public>> Run new task
void proxyfs_task_complete (struct proxyfs_task *self, struct proxyfs_task_start_struct *start_struct)
<<protected>> This is used by thread func, to tell caller, that we are ready with inicialization
struct proxyfs_task * proxyfs_task_get (struct proxyfs_task *task)
Get reference and increase reference counter.
void proxyfs_task_put (struct proxyfs_task *task)
Releases reference and if it was the last reference, frees the task.
int proxyfs_task_init (struct proxyfs_task *self)
<<public>> Initialize task
void proxyfs_task_notify_data_ready (struct proxyfs_task *self)
<<public>> Notifies task that there are data ready (either for writing/reading/both)
void proxyfs_task_data_ready_callback (void *data, int bytes)
Callback function that should be registered to all associated sockets.
void proxyfs_task_wait_for_data_ready (struct proxyfs_task *self)
This method will wait till there are some data ready to be read, or the thread is requested to stop.
void proxyfs_task_release_files (struct list_head *files)
<<protected>> Releases task files.
void proxyfs_task_free (struct proxyfs_task *self)
<<protected>> Releases task resources
void proxyfs_task_recv_peers (struct proxyfs_task *self)
<<protected>> Try to receive data from all peers
void proxyfs_task_send_peers (struct proxyfs_task *self)
<<protected>> Try to send data to all peers
void proxyfs_task_handle_dead_peers (struct proxyfs_task *self)
Iterates over all peers and if the peer is marked as dead, handle its removal.
void proxyfs_task_handle_msg (struct proxyfs_task *self, struct proxyfs_peer_t *peer)
<<protected>> Handle receive messagge
void proxyfs_task_send_buffers (struct proxyfs_task *self)
<<protected>> Try to create new messages from data in all file buffers
int proxyfs_task_send_write_buf (struct proxyfs_task *self, struct proxyfs_file_t *file)
<<protected>> Try to create new messages from data in buffer
void proxyfs_task_wakeup (struct proxyfs_task *self)
<<public>> Wake up task
struct proxyfs_peer_t * proxyfs_task_add_to_peers (struct proxyfs_task *self, struct kkc_sock *peer_sock)
<<private>> Create new peer from socket and add it to peers list
struct proxyfs_file_t * proxyfs_task_find_file (struct proxyfs_task *task, unsigned long ident)
Detailed Description
proxyfs task.
Date: 08/12/2007
Author: Petr Malat
Id:
proxyfs_task.c,v 1.10 2008/05/05 19:50:44 stavam2 Exp
This file is part of Proxy filesystem (ProxyFS) Copyleft (C) 2007 Petr Malat
ProxyFS is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
ProxyFS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file proxyfs_task.c.
Macro Definition Documentation
#define PROXYFS_FILE_PROTECTED
Definition at line 41 of file proxyfs_task.c.
#define PROXYFS_TASK_PRIVATE
Definition at line 35 of file proxyfs_task.c.
#define PROXYFS_TASK_PROTECTED
Definition at line 38 of file proxyfs_task.c.
#define PROXYFS_TASK_PROTECTED
Definition at line 38 of file proxyfs_task.c.
Function Documentation
struct proxyfs_peer_t* proxyfs_task_add_to_peers (struct proxyfs_task * self, struct kkc_sock * peer_sock) read
<<private>> Create new peer from socket and add it to peers list
Parameters
*self - pointer to self instance
*peer_sock - peer socket instance
Returns
new proxyfs_peer instance or NULL on error
Definition at line 444 of file proxyfs_task.c.
References mdbg, proxyfs_peer_t::peers, proxyfs_peer_new(), self, and proxyfs_peer_t::sock.
Referenced by proxyfs_server_accept().
{
     struct proxyfs_peer_t *peer;
     if((peer = proxyfs_peer_new() ) == NULL){
                 mdbg(ERR2, "Couldn't add socket to peers");
         return NULL;
     }
     peer->sock = peer_sock;
     list_add( &peer->peers, &self->peers );
     return peer;
 }
void proxyfs_task_complete (struct proxyfs_task * self, struct proxyfs_task_start_struct * start_struct)
<<protected>> This is used by thread func, to tell caller, that we are ready with inicialization
Parameters
*self - pointer to self instance or NULL
<em>start_struct - proxyfs_thread_start_struct that was used as thread parameter
Definition at line 67 of file proxyfs_task.c.
Referenced by proxyfs_client_thread(), and proxyfs_server_thread().
 {
     start_struct->task = self;
     complete( & start_struct->startup_done ); // After this call *start_struct is invalid
 }
void proxyfs_task_data_ready_callback (void * data, int bytes)
Callback function that should be registered to all associated sockets.
It will notify task about pending data to be read
Definition at line 134 of file proxyfs_task.c.
References data, mdbg, and proxyfs_task_notify_data_ready().
Referenced by proxyfs_client_thread(), proxyfs_server_accept(), and proxyfs_server_listen().
{
     struct proxyfs_task* self = data;
     mdbg(INFO3, "Task: %p Data arrived: %d", self, bytes);
     proxyfs_task_notify_data_ready(self);
 }
struct proxyfs_file_t* proxyfs_task_find_file (struct proxyfs_task * task, unsigned long ident) read
Definition at line 458 of file proxyfs_task.c.
References mdbg, and proxyfs_file_get_file_ident().
Referenced by proxyfs_server_handle_msg(), and proxyfs_task_handle_msg().
 {
     struct proxyfs_file_t *file = NULL;
     struct list_head *l;
     list_for_each( l, &((task)->files) ){
         mdbg(INFO3, "Checking file with id %lu", proxyfs_file_get_file_ident(list_entry(l, struct proxyfs_file_t, files)) );
         if( proxyfs_file_get_file_ident(list_entry(l, struct proxyfs_file_t, files)) == (ident) ){
             file = list_entry(l, struct proxyfs_file_t, files);
             break;
         }
     }
     return file;
 }
void proxyfs_task_free (struct proxyfs_task * self)
<<protected>> Releases task resources
Parameters
*self - pointer to self instance
Definition at line 178 of file proxyfs_task.c.
References mdbg, proxyfs_peer_t::peers, proxyfs_peer_disconnect(), proxyfs_peer_put(), proxyfs_task_release_files(), and self.
Referenced by proxyfs_task_put().
{
     struct list_head *l, *nxt;
     struct proxyfs_peer_t *peer;
     // First stop the processing thread
     int result;
     if ( current == self->tsk ) { // Special case when we are invoked from the proxyfs task thread directly
         result = -EINVAL;
         mdbg(INFO3, "Failed to startup proxyfs task listening => release it");
     } else {
         mdbg(INFO3, "Proxy task requesting thread stop");
         result = kthread_stop(self->tsk);
     }
     mdbg(INFO3, "Proxy task kthread stop result: %d Task: %p", result, self->tsk);
     if ( result )
         return;
     // Process custom freeing
     if ( self->ops && self->ops->free )
         self->ops->free(self);
     // TODO: We can do this also in client free for open&open send files, right?
     proxyfs_task_release_files(&self->files);
     // Finally free all peers (we do this after custom free as custom free will first stop possible server listening)
     list_for_each_safe( l, nxt, &self->peers ){
         peer = list_entry(l, struct proxyfs_peer_t, peers);
         proxyfs_peer_disconnect(peer);
         proxyfs_peer_put(peer);
     }
 }
void proxyfs_task_handle_dead_peers (struct proxyfs_task * self)
Iterates over all peers and if the peer is marked as dead, handle its removal.
Definition at line 262 of file proxyfs_task.c.
References kkc_sock_getpeername2(), mdbg, PEER_DEAD, proxyfs_peer_t::peers, proxyfs_peer_disconnect(), proxyfs_peer_get_state(), proxyfs_peer_put(), self, and proxyfs_peer_t::sock.
Referenced by proxyfs_client_loop(), and proxyfs_server_loop().
{
     struct list_head *l, *tmp;
     struct proxyfs_peer_t *peer;
     //int recv_res;
     list_for_each_safe( l, tmp, &self->peers ){
         peer = list_entry(l, struct proxyfs_peer_t, peers);
         if ( proxyfs_peer_get_state(peer) == PEER_DEAD ) {
             mdbg(INFO2, "Removing dead peer %s (%p)", kkc_sock_getpeername2(peer->sock), peer);
             list_del(l);
             proxyfs_peer_disconnect(peer);
             if ( self->ops && self->ops->handle_peer_dead )
                 self->ops->handle_peer_dead(self, peer);
             proxyfs_peer_put(peer);
         }
     }
 };
void proxyfs_task_handle_msg (struct proxyfs_task * self, struct proxyfs_peer_t * peer)
<<protected>> Handle receive messagge
Parameters
*self - pointer to self instance
*peer - peer instance with message we wanted to handle
Definition at line 284 of file proxyfs_task.c.
References proxyfs_msg_header::data, proxyfs_msg_header::data_size, proxyfs_msg_header::file_ident, proxyfs_msg::header, mdbg, proxyfs_msg_header::msg_num, MSG_WRITE, MSG_WRITE_RESP, proxyfs_file_get_file_ident(), proxyfs_file_submit_read_to_peer(), proxyfs_file_write_from_peer(), proxyfs_peer_get_msg(), proxyfs_task_find_file(), and self.
Referenced by proxyfs_task_recv_peers().
 {
     struct proxyfs_file_t *file;
     struct proxyfs_msg *msg = proxyfs_peer_get_msg(peer);
     if ( !msg ) // Case, when we had incomplete message in the buffer
         return;
     mdbg(INFO1, "Msg for identifier has arrived: %lu",msg->header.file_ident);
     switch( msg->header.msg_num ){
         case MSG_WRITE_RESP:
             if(( file = proxyfs_task_find_file(self, msg->header.file_ident)) != NULL){
                 if( msg->header.data[0] <= 0 ){
                     mdbg(ERR3, "Read must be > 0 but it is %lu", (unsigned long)msg->header.data[0]);
                     break;
                 }
                 else{
                     mdbg(INFO3, "Peer reads %lu bytes from file %lu buffer",
                             (unsigned long)msg->header.data[0], proxyfs_file_get_file_ident(file));
                     /*if( self->ops && self->ops->file_read )
                         self->ops->file_read(file, msg->header.data[0]);*/
                     proxyfs_file_submit_read_to_peer( file, msg->header.data[0]);
                     break;
                 }
             }
             mdbg(ERR3, "WRITE_RESP: Unknown file identificator %lu", msg->header.file_ident);
             break;
         case MSG_WRITE:
             if(( file = proxyfs_task_find_file(self, msg->header.file_ident)) != NULL){
                 mdbg(INFO3, "Peer writes %lu bytes to file %lu", msg->header.data_size, proxyfs_file_get_file_ident(file));
                 if( msg->header.data_size >= 0 ){
                     proxyfs_file_write_from_peer( file, (void*)msg->header.data, msg->header.data_size);
                 }
                 break;
             }
             mdbg(ERR3, "WRITE: Unknown file identificator %lu", msg->header.file_ident);
             break;
         default:
             mdbg(INFO3, "Calling task specific msg handler");
             if( self->ops && self->ops->handle_msg )
                 self->ops->handle_msg(self, peer);
     }
     // Do not free message here. Incoming messages are kept only in rcv buffer and the buffer is always reused, so no need to free
 }
void proxyfs_task_recv_peers (struct proxyfs_task * self)
<<protected>> Try to receive data from all peers
Parameters
*self - pointer to self instance
Definition at line 216 of file proxyfs_task.c.
References mdbg, PEER_DEAD, proxyfs_peer_t::peers, proxyfs_peer_clear_msg(), proxyfs_peer_real_recv(), proxyfs_peer_set_state(), proxyfs_task_handle_msg(), and self.
Referenced by proxyfs_client_loop(), and proxyfs_server_loop().
 {
     struct list_head *l;
     struct proxyfs_peer_t *peer;
     int recv_res;
     list_for_each( l,  &self->peers ){
         peer = list_entry(l, struct proxyfs_peer_t, peers);
 recv_next:  recv_res = proxyfs_peer_real_recv(peer);
         if ( recv_res == 1 ){ // Message received
             mdbg(INFO3, "Message received");
             proxyfs_task_handle_msg( self, peer );
             proxyfs_peer_clear_msg(peer);
             // Consider adding protection from receiving from only one peer
             goto recv_next;
         } else if ( recv_res == -ECONNRESET || recv_res == -ECONNABORTED ) {
             // TODO: Some nicer general solution for removing (and detecting) lost peers.. but for now we need at least this
             proxyfs_peer_set_state(peer, PEER_DEAD);
             mdbg(INFO1, "Peer marked dead");
         } else if (recv_res == -EAGAIN ) {
             // Do nothing, repeat
         } else {
             mdbg(INFO1, "Unknown return code: %d", recv_res);
         }
     }
 }
void proxyfs_task_release_files (struct list_head * files)
<<protected>> Releases task files.
. in fact they all should be already release we do just a consistency check at this place
Parameters
*self - pointer to self instance
Definition at line 160 of file proxyfs_task.c.
References mdbg, PROXYFS_FILE_CLOSED, proxyfs_file_get_file_ident(), and proxyfs_file_get_status().
Referenced by proxyfs_task_free().
{
     struct list_head *l;
     struct proxyfs_file_t *proxy_file;
     list_for_each( l, files ) {
         proxy_file = list_entry(l, struct proxyfs_file_t, files);
         if ( !proxyfs_file_get_status( proxy_file, PROXYFS_FILE_CLOSED ) ) {
             mdbg(WARN3, "Proxy file not closed on release: %lu", proxyfs_file_get_file_ident(proxy_file));
         }
     }
 }
void proxyfs_task_send_buffers (struct proxyfs_task * self)
<<protected>> Try to create new messages from data in all file buffers
Parameters
*self - pointer to self instance
Definition at line 334 of file proxyfs_task.c.
References proxyfs_task_send_write_buf(), and self.
Referenced by proxyfs_client_loop(), and proxyfs_server_loop().
 {
     struct proxyfs_file_t *proxy_file;
     struct list_head *l;
     int res;
     list_for_each( l, &self->files ){
         proxy_file = list_entry(l, struct proxyfs_file_t, files);
         // Send as long as there are some data
         // We can consider some "starvation" prevention here. In this case, we have to notify task about "data_ready" if we do not send all data, so that we ensure a next iteration in a main processing loop is started
         while ( (res = proxyfs_task_send_write_buf( self, proxy_file )) == -EAGAIN ) {};
     }
 }
void proxyfs_task_send_peers (struct proxyfs_task * self)
<<protected>> Try to send data to all peers
Parameters
*self - pointer to self instance
Definition at line 247 of file proxyfs_task.c.
References proxyfs_peer_t::peers, proxyfs_peer_real_send(), and self.
Referenced by proxyfs_server_loop().
 {
     struct list_head *l;
     struct proxyfs_peer_t *peer;
     list_for_each( l, &self->peers ){
         peer =  list_entry(l, struct proxyfs_peer_t, peers);
         proxyfs_peer_real_send(peer);
     }
 }
int proxyfs_task_send_write_buf (struct proxyfs_task * self, struct proxyfs_file_t * file)
<<protected>> Try to create new messages from data in buffer
Parameters
*self - pointer to self instance
*file - proxyfs_file instance which data we wanted to send
Returns
0, if all required data were written, -EAGAIN if there are still some pending data
Definition at line 355 of file proxyfs_task.c.
References mdbg, MSG_HDR_SIZE, MSG_MAX_SIZE, MSG_WRITE, proxyfs_file_get_file_ident(), proxyfs_file_read_to_peer(), proxyfs_file_write_buf_info(), proxyfs_msg_new_takeover_ownership(), and proxyfs_peer_send_msg().
Referenced by proxyfs_task_send_buffers().
 {
     struct proxyfs_msg *msg;
     size_t total_size, data_size, send;
     void *data_ptr;
     char* read_buffer = NULL;
     int res = 0;
         mdbg(INFO3, "Proccessing file %lu", proxyfs_file_get_file_ident(file));
     if( file->peer == NULL ){
             mdbg(INFO3, "No peer, skiping");
         return 0;
     }
     proxyfs_file_write_buf_info(file, &total_size, &data_size, &data_ptr);
         mdbg(INFO3, "(Total size %lu, Data size %lu, Data addr %p, Unconfirmed size %lu)", (unsigned long)total_size, (unsigned long)data_size, data_ptr, (unsigned long)file->write_buf_unconfirmed);
     send = total_size - file->write_buf_unconfirmed;
     if ( send == 0 )
         return 0;
     if( send > MSG_MAX_SIZE - MSG_HDR_SIZE ) {
         send = MSG_MAX_SIZE - MSG_HDR_SIZE;
         res = -EAGAIN;
     }
     read_buffer = kmalloc(send, GFP_KERNEL);
     if ( !read_buffer )
         goto exit0;
     send = proxyfs_file_read_to_peer(file, read_buffer, send);
     mdbg(INFO3, "Real send size: %lu", (unsigned long)send);
     if ( send == 0 )
         goto exit0;
     msg = proxyfs_msg_new_takeover_ownership(MSG_WRITE, proxyfs_file_get_file_ident(file), send, read_buffer);
     if ( !msg )
         goto exit0;
     proxyfs_peer_send_msg( file->peer, msg );
     return res;
 exit0:
     kfree(read_buffer);
     return -ENOMEM;
 /*
         mdbg(INFO3, "(Data size %lu, Data addr %p, Unconfirmed size %lu)", (unsigned long)data_size, data_ptr, (unsigned long)file->write_buf_unconfirmed);
     if( data_size > file->write_buf_unconfirmed ){
         if( data_size - file->write_buf_unconfirmed > MSG_MAX_SIZE - MSG_HDR_SIZE )
             send = MSG_MAX_SIZE - MSG_HDR_SIZE;
         else
             send = data_size - file->write_buf_unconfirmed;
             mdbg(INFO3, "Data pending for file %lu (%d bytes at %p)(%d)",
                 file->file_ident, data_size, data_ptr, file->write_buf_unconfirmed);
         msg = proxyfs_msg_new(MSG_WRITE, file->file_ident, send, data_ptr + file->write_buf_unconfirmed );
             mdbg(INFO3, "Message created %p", msg);
         if ( file->peer ) {
             proxyfs_peer_send_msg( file->peer, msg );
             file->write_buf_unconfirmed += send;
         } else {
             mdbg(INFO3, "Msg ignored, peer NULL"); // TODO: Where is the msg free?
         }
     }
 */
 }
void proxyfs_task_wait_for_data_ready (struct proxyfs_task * self)
This method will wait till there are some data ready to be read, or the thread is requested to stop.
Definition at line 144 of file proxyfs_task.c.
References flags, and self.
Referenced by proxyfs_client_loop(), and proxyfs_server_loop().
{
     unsigned long flags;
     // TODO: There is 100ms timeout.. it seems we are missing some events still.. I suspect it is file data ready event
     // When we solve this, remove this timeout, it should not be required.. but can be kept as a "fallback" bulgarian fix
     wait_event_timeout( self->data_ready_wait, self->data_ready || kthread_should_stop(), msecs_to_jiffies(100));
     // Note: Here we assume, that all already arrived data will be read before next wait call.
     // If this is not the case, the mechanism must be changed
     spin_lock_irqsave(&self->data_ready_lock, flags);
     self->data_ready = 0;
     spin_unlock_irqrestore(&self->data_ready_lock, flags);
 }