Clondike: tcmi_err_msg class
tcmi_err_msg class
tcmi_msg class
This class represents a generic error message.
Data Structures
struct tcmi_err_msg
Compound structure, inherits from tcmi_msg_class.
Macros
#define TCMI_ERR_MSG(m) ((struct tcmi_err_msg*)m)
Casts to the tcmi_err_msg instance.
Functions
static int tcmi_err_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Receives the message via a specified connection.
static int tcmi_err_msg_send (struct tcmi_msg *self, struct kkc_sock *sock)
<<private>> Sends out the error code via specified socket.
struct tcmi_msg * tcmi_err_msg_new_rx (u_int32_t msg_id)
<<public>> Error message, constructor for receiving.
struct tcmi_msg * tcmi_err_msg_new_tx (u_int32_t msg_id, u_int32_t trans_id, int32_t err_code)
<<public>> Error message, constructor for transferring.
static int32_t tcmi_err_msg_code (struct tcmi_msg *self)
<<public>> Error code accessor.
Variables
static struct tcmi_msg_ops err_msg_ops
Message operations that support polymorphism.
Detailed Description
This class represents a generic error message.
It carries an error code and can be used as response to any regular message that has registered its rx constructor as the error rx constructor with the message factory. Unlike other messages, it doesn't define a fixed message ID. Instead the transfer message constructor (tcmi_err_msg_new_tx()) allows specifying a message ID that would carry the regular response message.
The constructor only sets error flags in the message ID. The receiving party identifies the message based on the regular response ID. The message flags indicating an error make the message factory use the error rx constructor. After delivery, the error message can be processed and the error code extracted.
Data Structure Documentation
struct tcmi_err_msg
Compound structure, inherits from tcmi_msg_class.
Definition at line 59 of file tcmi_err_msg.h.
Data Fields
int32_t err_code error code that the message is carrying.
struct tcmi_msg super parent class instance.
Macro Definition Documentation
#define TCMI_ERR_MSG (m) ((struct tcmi_err_msg*)m)
Casts to the tcmi_err_msg instance.
Definition at line 74 of file tcmi_err_msg.h.
Referenced by tcmi_err_msg_code(), tcmi_err_msg_new_rx(), tcmi_err_msg_new_tx(), tcmi_err_msg_recv(), and tcmi_err_msg_send().
Function Documentation
static int32_t tcmi_err_msg_code (struct tcmi_msg * self) inline static
<<public>> Error code accessor.
Parameters
*self - pointer to this message instance
Returns
error code that the message is carrying
Definition at line 82 of file tcmi_err_msg.h.
References TCMI_ERR_MSG.
 {
     return TCMI_ERR_MSG(self)->err_code;
 }
struct tcmi_msg* tcmi_err_msg_new_rx (u_int32_t msg_id) read
<<public>> Error message, constructor for receiving.
<<public>> Error message, constructor for receiving.
This constructor is made available for other messages, so that they can specify it as their error constructor for the factory class .
Parameters
msg_id - message ID that will be used for this error message instance.
Returns
a new error message or NULL.
Definition at line 51 of file tcmi_err_msg.c.
References err_msg_ops, mdbg, TCMI_ERR_MSG, TCMI_MSG, TCMI_MSG_FLG_SET_ERR, and tcmi_msg_init_rx().
 {
     struct tcmi_err_msg *msg;
     if (!(msg = TCMI_ERR_MSG(kmalloc(sizeof(struct tcmi_err_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for error message %x", msg_id);
         goto exit0;
     }
     /* Initialized the message for receiving, message ID is
      * extended with error flags */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_MSG_FLG_SET_ERR(msg_id), &err_msg_ops)) {
         mdbg(ERR3, "Error initializing error message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_err_msg_new_tx (u_int32_t msg_id, u_int32_t trans_id, int32_t err_code) read
<<public>> Error message, constructor for transferring.
<<public>> Error message, constructor for transferring.
An error message is considered one way only and is usually used as a error response to some other message. The user thus has to specify the transaction ID of the message that the error message is a response too. Messages with TCMI_TRANSACTION_INVAL_ID are possible too. No search for a matching transaction will be performed at the receiving party and the message will be queued in a regular request queue.
Basic part of instantation is the same as when creating an Rx version.
Parameters
msg_id - ID assigned to the error message, it will be extended with error flags, so that the message factory at the receiving party uses the above implemented tcmi_err_msg_new_rx() constructor.
trans_id - transaction ID
err_code - error code that will be stored in the message
Returns
a new error ready for the transfer or NULL.
Definition at line 96 of file tcmi_err_msg.c.
References tcmi_err_msg::err_code, err_msg_ops, mdbg, TCMI_ERR_MSG, TCMI_MSG, TCMI_MSG_FLG_SET_ERR, and tcmi_msg_init_tx().
 {
     struct tcmi_err_msg *msg;
     if (!(msg = TCMI_ERR_MSG(kmalloc(sizeof(struct tcmi_err_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate memory for error message %x", msg_id);
         goto exit0;
     }
     /* Initialize the message for transfer, message ID is
      * extended with error flags, no transaction created or
      * response ID setup. Only the transaction ID, that will get
      * send along with the message, is set. */
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_MSG_FLG_SET_ERR(msg_id), &err_msg_ops,
                  NULL, 0, 0, trans_id)) {
         mdbg(ERR3, "Error initializing error message %x", msg_id);
         goto exit1;
     }
     msg->err_code = err_code;
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static int tcmi_err_msg_recv (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Receives the message via a specified connection.
Receiving the error message requires reading the error code from the specified socket
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully received.
Definition at line 140 of file tcmi_err_msg.c.
References tcmi_err_msg::err_code, KKC_SOCK_BLOCK, kkc_sock_recv(), mdbg, and TCMI_ERR_MSG.
 {
     int err;
     struct tcmi_err_msg *self_err = TCMI_ERR_MSG(self);
     err = kkc_sock_recv(sock, &self_err->err_code,
                 sizeof(self_err->err_code), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Received error code: %x", self_err->err_code);
     return err;
 }
static int tcmi_err_msg_send (struct tcmi_msg * self, struct kkc_sock * sock) static
<<private>> Sends out the error code via specified socket.
Parameters
*self - this message instance
*sock - KKC socket used for receiving message data
Returns
0 when successfully sent.
Definition at line 159 of file tcmi_err_msg.c.
References tcmi_err_msg::err_code, KKC_SOCK_BLOCK, kkc_sock_send(), mdbg, and TCMI_ERR_MSG.
 {
     int err;
     struct tcmi_err_msg *self_err = TCMI_ERR_MSG(self);
     err = kkc_sock_send(sock, &self_err->err_code,
                 sizeof(self_err->err_code), KKC_SOCK_BLOCK);
     mdbg(INFO3, "Sent error code: %x", self_err->err_code);
     return err;
 }
Variable Documentation
struct tcmi_msg_ops err_msg_ops static
Initial value:
= {
    .recv = tcmi_err_msg_recv,
    .send = tcmi_err_msg_send
}
Message operations that support polymorphism.
Definition at line 175 of file tcmi_err_msg.c.
Referenced by tcmi_err_msg_new_rx(), and tcmi_err_msg_new_tx().