#!/bin/bash

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/configuration.sh

until echo $MY_IP | grep '[0-9]*\.[0-9]*\.' > /dev/null ; do
	MY_IP=`$CLONDIKE_SCRIPTS/parse-interface-ip.sh eth0.91`
done
$CLONDIKE_SCRIPTS/listen.sh $MY_IP

(cd $CLONDIKE_HOME/userspace/simple-ruby-director; ruby Director.rb > /tmp/director.log 2>&1)
