#!/bin/bash

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/configuration.sh

MY_IP_COMMAND="$CLONDIKE_SCRIPTS/parse-interface-ip.sh eth0.91 2> /dev/null"
MY_IP="`$MY_IP_COMMAND`"
until echo "$MY_IP" | grep '[0-9]*\.[0-9]*\.' 2> /dev/null ; do
    sleep 3
    MY_IP="`$MY_IP_COMMAND`"
done
$CLONDIKE_SCRIPTS/clear-current-config.sh
$CLONDIKE_SCRIPTS/listen.sh "$MY_IP"

(cd $CLONDIKE_HOME/userspace/simple-ruby-director; EMIG=1 ruby1.8 -w -I $CLONDIKE_SIMPLE_RUBY_DIRECTOR Director.rb >/tmp/director.log 2>&1 )
