Clondike: Group identification
Group identification
tcmi_syscallhooks class
A part of tcmi_syscallhooks class that installs group identity manipulation syscalls hooks into the kernel.
Functions
int tcmi_syscall_hooks_groupident_init (void)
<<public>> Registers all PID manipolation hooks with the kernel.
void tcmi_syscall_hooks_groupident_exit (void)
<<public>> Unregisters all PID manipolation hooks.
Detailed Description
A part of tcmi_syscallhooks class that installs group identity manipulation syscalls hooks into the kernel.
Function Documentation
void tcmi_syscall_hooks_groupident_exit (void)
<<public>> Unregisters all PID manipolation hooks.
Definition at line 66 of file tcmi_syscallhooks_groupident.c.
References minfo.
Referenced by tcmi_syscall_hooks_exit().
 {
     minfo(INFO3, "Unregistering TCMI group identification syscalls hooks");
     tcmi_hooks_unregister_sys_getegid();
     tcmi_hooks_unregister_sys_getgid();
     tcmi_hooks_unregister_sys_setgid();
     tcmi_hooks_unregister_sys_setregid();
     tcmi_hooks_unregister_sys_setresgid();
     tcmi_hooks_unregister_sys_getresgid();
     tcmi_hooks_unregister_sys_getgroups();
     tcmi_hooks_unregister_sys_setgroups();
 }
int tcmi_syscall_hooks_groupident_init (void)
<<public>> Registers all PID manipolation hooks with the kernel.
<<public>> Registers all PID manipolation hooks with the kernel.
Returns
0 upon success
Definition at line 48 of file tcmi_syscallhooks_groupident.c.
References minfo, tcmi_syscall_hooks_sys_getegid(), tcmi_syscall_hooks_sys_getgid(), tcmi_syscall_hooks_sys_getgroups(), tcmi_syscall_hooks_sys_getresgid(), tcmi_syscall_hooks_sys_setgid(), tcmi_syscall_hooks_sys_setgroups(), tcmi_syscall_hooks_sys_setregid(), and tcmi_syscall_hooks_sys_setresgid().
Referenced by tcmi_syscall_hooks_init().
 {
     minfo(INFO3, "Registering TCMI group identification syscalls hooks\n"
              "For: getgid, setgid, getegid, setregid, setresgid, getgroups, setgroups");
     tcmi_hooks_register_sys_getegid(   tcmi_syscall_hooks_sys_getegid   );
     tcmi_hooks_register_sys_getgid(    tcmi_syscall_hooks_sys_getgid    );
     tcmi_hooks_register_sys_setgid(    tcmi_syscall_hooks_sys_setgid    );
     tcmi_hooks_register_sys_setregid(  tcmi_syscall_hooks_sys_setregid  );
     tcmi_hooks_register_sys_setresgid( tcmi_syscall_hooks_sys_setresgid );
     tcmi_hooks_register_sys_getresgid( tcmi_syscall_hooks_sys_getresgid );
     tcmi_hooks_register_sys_getgroups( tcmi_syscall_hooks_sys_getgroups );
     tcmi_hooks_register_sys_setgroups( tcmi_syscall_hooks_sys_setgroups );
     return 0;
 }