Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/syscall/tcmi_rpc.h File Reference
tcmi_rpc.h File Reference
#include "tcmi_rpc_numbers.h"
Macros
#define TCMI_RPC_MAXPARAMS 6
Max remote procedure call parameters.
Functions
long tcmi_rpc_do (struct tcmi_rpc *self, unsigned int rpc_num, long parameters[6])
<<public>> Universal procedure to do RPC
static long tcmi_rpc_call0 (struct tcmi_rpc *self, unsigned int rpc_num)
<<public>> Do a rpc without parameters.
static long tcmi_rpc_call1 (struct tcmi_rpc *self, unsigned int rpc_num, long param1)
<<public>> Do a rpc with 1 parameter.
static long tcmi_rpc_call2 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2)
<<public>> Do a rpc with 2 parameters.
static long tcmi_rpc_call3 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2, long param3)
<<public>> Do a rpc with 3 parameters.
static long tcmi_rpc_call4 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2, long param3, long param4)
<<public>> Do a rpc with 4 parameters.
static long tcmi_rpc_call6 (struct tcmi_rpc *self, unsigned int rpc_num, long param1, long param2, long param3, long param4, long param5, long param6)
<<public>> Do a rpc with 4 parameters.
Function Documentation
static long tcmi_rpc_call0 (struct tcmi_rpc * self, unsigned int rpc_num) inline static
<<public>> Do a rpc without parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
Returns
RPC return code
Definition at line 63 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call1 (struct tcmi_rpc * self, unsigned int rpc_num, long param1) inline static
<<public>> Do a rpc with 1 parameter.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
Returns
RPC return code
Definition at line 76 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call2 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2) inline static
<<public>> Do a rpc with 2 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
Returns
RPC return code
Definition at line 91 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call3 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2, long param3) inline static
<<public>> Do a rpc with 3 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
param3 - Third parametr of called procedure
Returns
RPC return code
Definition at line 108 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     parameters[2] = param3;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call4 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2, long param3, long param4) inline static
<<public>> Do a rpc with 4 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
param3 - Third parametr of called procedure
param4 - 4th parametr of called procedure
Returns
RPC return code
Definition at line 127 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     parameters[2] = param3;
     parameters[3] = param4;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }
static long tcmi_rpc_call6 (struct tcmi_rpc * self, unsigned int rpc_num, long param1, long param2, long param3, long param4, long param5, long param6) inline static
<<public>> Do a rpc with 4 parameters.
Parameters
*self - pointer to this tcmi_rpc class instance
rpc_num - Identification number of called procedure
param1 - First parametr of called procedure
param2 - Second parametr of called procedure
param3 - Third parametr of called procedure
param4 - 4th parametr of called procedure .....
Returns
RPC return code
Definition at line 148 of file tcmi_rpc.h.
References tcmi_rpc_do(), and TCMI_RPC_MAXPARAMS.
 {
     long parameters[TCMI_RPC_MAXPARAMS] = {0, 0, 0, 0, 0, 0};
     parameters[0] = param1;
     parameters[1] = param2;
     parameters[2] = param3;
     parameters[3] = param4;
     parameters[4] = param5;
     parameters[5] = param6;
     return tcmi_rpc_do(self, rpc_num, parameters);
 }