Clondike: C:/CLONDIKE/clondike/sources/kernel_2.6.33.1/src/proxyfs/proxyfs_module.c File Reference
proxyfs_module.c File Reference
#include <linux/sched.h>
#include <linux/init.h>
#include <linux/module.h>
#include <dbg.h>
#include <proxyfs/proxyfs_fs.h>
#include <proxyfs/proxyfs_server.h>
Functions
module_param (server, charp, S_IRUGO)
static int proxyfs_module_init (void)
static void proxyfs_module_exit (void)
module_init (proxyfs_module_init)
module_exit (proxyfs_module_exit)
MODULE_LICENSE ("GPL")
MODULE_AUTHOR ("Petr Malat")
Variables
static struct proxyfs_task * proxy_server_task
Reference to proxy server task.
static char * server = "no_server"
Function Documentation
MODULE_AUTHOR ("Petr Malat")
module_exit (proxyfs_module_exit)
module_init (proxyfs_module_init)
MODULE_LICENSE ("GPL")
module_param (server , charp , S_IRUGO)
static void proxyfs_module_exit (void) static
Definition at line 30 of file proxyfs_module.c.
References mdbg, proxy_server_task, proxyfs_fs_exit(), and proxyfs_task_put().
{
     mdbg(INFO3, "ProxyFS unloading");
     proxyfs_task_put(proxy_server_task);
     proxyfs_fs_exit();
     mdbg(INFO3, "ProxyFS unloaded");
 }
static int proxyfs_module_init (void) static
Definition at line 16 of file proxyfs_module.c.
References mdbg, proxy_server_task, proxyfs_fs_init(), proxyfs_server_thread(), proxyfs_task_run(), and server.
{
     mdbg(INFO3, "ProxyFS loading");
     if( strncmp(server, "no_server", 20) != 0 ){
         mdbg(INFO3, "Request to start server on %s", server);
         if ( (proxy_server_task = proxyfs_task_run( proxyfs_server_thread, server )) == NULL ){
             mdbg(ERR1, "Failed to start server on %s", server);
             return -EINVAL;
         }
     }
     return proxyfs_fs_init();
 }
Variable Documentation
struct proxyfs_task* proxy_server_task static
Reference to proxy server task.
Definition at line 10 of file proxyfs_module.c.
Referenced by proxyfs_module_exit(), and proxyfs_module_init().
char* server = "no_server" static
Definition at line 12 of file proxyfs_module.c.
Referenced by proxyfs_client_handle_dead_peer(), and proxyfs_module_init().