Clondike: proxyfs_task class
proxyfs_task class
ProxyFS
<<class>> representing proxyfs task
Modules
proxyfs_client class
<<class>> representing proxyfs_client task
proxyfs_server class
<<singleton>> representing proxyfs_server task
Macros
#define PROXYFS_TASK(arg) ((struct proxyfs_task*)(arg))
<<public>> Cast to struct proxyfs_task*
Functions
int proxyfs_task_init (struct proxyfs_task *self)
<<public>> Initialize task
void proxyfs_task_wakeup (struct proxyfs_task *self)
<<public>> Wake up client TODO: Obsolete, remove
void proxyfs_task_notify_data_ready (struct proxyfs_task *self)
<<public>> Notifies task that there are data ready (either for writing/reading/both)
struct proxyfs_task * proxyfs_task_run (int(*func)(void *), const char *addr_str)
<<public>> Run new task
void proxyfs_task_put (struct proxyfs_task *task)
<<public>> Releases reference and if it was the last reference, frees the task
struct proxyfs_task * proxyfs_task_get (struct proxyfs_task *task)
<<public>> Get reference and increase reference counter
Detailed Description
<<class>> representing proxyfs task
Macro Definition Documentation
#define PROXYFS_TASK (arg) ((struct proxyfs_task*)(arg))
<<public>> Cast to struct proxyfs_task*
Definition at line 57 of file proxyfs_task.h.
Referenced by proxyfs_client_do_syscall(), proxyfs_client_loop(), proxyfs_client_new(), proxyfs_client_open_proxy(), proxyfs_client_thread(), proxyfs_fs_fdinode_write(), proxyfs_fs_kill_sb(), proxyfs_server_accept(), proxyfs_server_duplicate_all_parent(), proxyfs_server_duplicate_overtaken_file(), proxyfs_server_loop(), proxyfs_server_overtake_file(), proxyfs_server_poll_queue_proc(), proxyfs_server_read_and_write_real_files(), proxyfs_server_release_all(), and proxyfs_server_thread().
Function Documentation
struct proxyfs_task* proxyfs_task_get (struct proxyfs_task * task) read
<<public>> Get reference and increase reference counter
<<public>> Get reference and increase reference counter
Parameters
*self - pointer to self instance
Returns
reference to proxyfs_task
Definition at line 78 of file proxyfs_task.c.
{
     if ( task )
         atomic_inc(&task->ref_count);
     return task;
 }
int proxyfs_task_init (struct proxyfs_task * self)
<<public>> Initialize task
Parameters
*self - pointer to self instance
Returns
zero on success
Definition at line 105 of file proxyfs_task.c.
References mdbg, and self.
Referenced by proxyfs_client_new(), and proxyfs_server_thread().
 {
     INIT_LIST_HEAD( & self->files );
     INIT_LIST_HEAD( & self->peers );
     self->ops = NULL;
     atomic_set(&self->ref_count, 1);
     self->data_ready = 0;
     spin_lock_init(&self->data_ready_lock);
     init_waitqueue_head( & self->data_ready_wait );
     mdbg(INFO3, "Created proxy task: %p Current: %p", self, current);
     return 0;
 }
void proxyfs_task_notify_data_ready (struct proxyfs_task * self)
<<public>> Notifies task that there are data ready (either for writing/reading/both)
Definition at line 122 of file proxyfs_task.c.
References flags, mdbg, and self.
Referenced by proxyfs_client_do_syscall(), proxyfs_client_open_proxy(), proxyfs_fs_fdinode_write(), and proxyfs_task_data_ready_callback().
{
     unsigned long flags;
     spin_lock_irqsave(&self->data_ready_lock, flags);
     self->data_ready = 1;
     spin_unlock_irqrestore(&self->data_ready_lock,flags);
     wake_up( &self->data_ready_wait );
     mdbg(INFO3, "Task: %p Data ready done", self);
 }
void proxyfs_task_put (struct proxyfs_task * task)
<<public>> Releases reference and if it was the last reference, frees the task
<<public>> Releases reference and if it was the last reference, frees the task
Parameters
*self - pointer to self instance
Definition at line 89 of file proxyfs_task.c.
References mdbg, and proxyfs_task_free().
Referenced by proxyfs_client_thread(), proxyfs_fs_kill_sb(), and proxyfs_module_exit().
{
     if ( !task )
         return;
     if (atomic_dec_and_test(&task->ref_count)) {
         mdbg(INFO3, "Destroying proxy task: %p", task);
         proxyfs_task_free(task);
         kfree(task);
     }
 }
struct proxyfs_task* proxyfs_task_run (int(*)(void *) func, const char * addr_str) read
<<public>> Run new task
Parameters
*func - pointer to thread function (proxyfs_client_thread or proxyfs_server_thread)
*addr_str - server address for listenning or to connect to
Returns
new task or NULL on error
Definition at line 51 of file proxyfs_task.c.
Referenced by proxyfs_fs_mount(), and proxyfs_module_init().
 {
     struct proxyfs_task_start_struct start_struct;
     start_struct.addr_str = addr_str;
     init_completion( & start_struct.startup_done );
     if( kthread_run( func, (void*)&start_struct, "ProxyFS %s", addr_str ) == ERR_PTR(-ENOMEM) )
         return NULL;
     wait_for_completion( & start_struct.startup_done );
     return start_struct.task;
 }
void proxyfs_task_wakeup (struct proxyfs_task * self)
<<public>> Wake up client TODO: Obsolete, remove
<<public>> Wake up client TODO: Obsolete, remove
Parameters
*self - pointer to self instance
Definition at line 431 of file proxyfs_task.c.
References self.
{
     if( current == self->tsk )
         set_current_state(TASK_RUNNING);
     else
         wake_up_process(self->tsk);
 }