Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/ccfs/file.c File Reference
file.c File Reference
#include <linux/file.h>
#include <linux/poll.h>
#include <linux/mount.h>
#include <linux/pagemap.h>
#include <linux/security.h>
#include <linux/compat.h>
#include <linux/fs_stack.h>
#include "ccfs.h"
#include "prefetcher.h"
#include <dbg.h>
Functions
int ccfs_readdir (struct file *filp, void *dirent, filldir_t filldir)
static long ccfs_ioctl (struct file *file, unsigned int cmd, unsigned long arg)
int ccfs_close_lower_file (struct file *lower_file)
static int ccfs_open (struct inode *inode, struct file *file)
static int ccfs_release (struct inode *inode, struct file *file)
static int ccfs_flush (struct file *file, fl_owner_t td)
static int ccfs_fsync (struct file *file, loff_t start, loff_t end, int datasync)
static int ccfs_fasync (int fd, struct file *file, int flag)
static ssize_t ccfs_splice_read (struct file *file, loff_t *ppos, struct pipe_inode_info *pipe, size_t count, unsigned int flags)
static int ccfs_file_mmap (struct file *file, struct vm_area_struct *vma)
static ssize_t ccfs_do_sync_read (struct file *filp, char __user *buf, size_t len, loff_t *ppos)
static ssize_t ccfs_generic_file_aio_read (struct kiocb *iocb, const struct iovec *iov, unsigned long nr_segs, loff_t pos)
Variables
struct kmem_cache * ccfs_file_cache
struct file_operations ccfs_dir_fops
struct file_operations ccfs_main_fops
Function Documentation
int ccfs_close_lower_file (struct file * lower_file)
Definition at line 54 of file file.c.
References mdbg.
 {
     mdbg(INFO3,"Closing lower file file %p", lower_file);
     fput(lower_file);
     return 0;
 }
static ssize_t ccfs_do_sync_read (struct file * filp, char __user * buf, size_t len, loff_t * ppos) static
Definition at line 198 of file file.c.
References mdbg.
{
   ssize_t res;
   res = do_sync_read(filp, buf, len, ppos);
   mdbg(INFO3,"Read file %p [%s] -> Len: %ld, Res: %ld", filp, filp->f_dentry->d_name.name, len, res);
   return res;
 }
static int ccfs_fasync (int fd, struct file * file, int flag) static
Definition at line 164 of file file.c.
References ccfs_get_nested_file(), and mdbg.
 {
     int rc = 0;
     struct file *lower_file = NULL;
     mdbg(INFO3,"Fasync file %p", file);
     lower_file = ccfs_get_nested_file(file);
     if (lower_file->f_op && lower_file->f_op->fasync)
         rc = lower_file->f_op->fasync(fd, lower_file, flag);
     return rc;
 }
static int ccfs_file_mmap (struct file * file, struct vm_area_struct * vma) static
Definition at line 192 of file file.c.
References mdbg.
{
     mdbg(INFO3,"Mmap file %p [%s]", file, file->f_dentry->d_name.name);
     return generic_file_mmap(file, vma);
 }
static int ccfs_flush (struct file * file, fl_owner_t td) static
Definition at line 125 of file file.c.
References ccfs_get_nested_file(), and mdbg.
 {
     int rc = 0;
     struct file *lower_file = NULL;
     mdbg(INFO3,"Flush file %p", file);
     lower_file = ccfs_get_nested_file(file);
     mdbg(INFO3,"Flush lower file %p (%ld)", lower_file, atomic_long_read(&lower_file->f_count));
     BUG_ON(!lower_file);
     if (lower_file->f_op && lower_file->f_op->flush)
         rc = lower_file->f_op->flush(lower_file, td);
     return rc;
 }
static int ccfs_fsync (struct file * file, loff_t start, loff_t end, int datasync) static
Definition at line 142 of file file.c.
References ccfs_get_nested_file(), and mdbg.
 {
     struct file *lower_file = ccfs_get_nested_file(file);
     //struct dentry *lower_dentry = ccfs_get_nested_dentry(dentry);          Commented for kernel 3.7.1 by Jiri Rakosnik
     //struct inode *lower_inode = lower_dentry != NULL ? lower_dentry->d_inode : NULL;
     struct inode *lower_inode = NULL;
     int rc = -EINVAL;
     //BUG_ON(!lower_dentry);
     BUG_ON(!lower_inode);
     mdbg(INFO3,"Fsync file %p", file);
     if (lower_inode->i_fop->fsync) {
         mutex_lock(&lower_inode->i_mutex);
         rc = lower_inode->i_fop->fsync(lower_file, 0, 0,
                            datasync);
         mutex_unlock(&lower_inode->i_mutex);
     }
     return rc;
 }
static ssize_t ccfs_generic_file_aio_read (struct kiocb * iocb, const struct iovec * iov, unsigned long nr_segs, loff_t pos) static
Definition at line 205 of file file.c.
References mdbg.
{
   ssize_t res;
   res = generic_file_aio_read(iocb, iov, nr_segs, pos);
   mdbg(INFO3,"Async Read ... Pos: %lld, Res: %ld",(long long) pos, res);
   return res;
 }
static long ccfs_ioctl (struct file * file, unsigned int cmd, unsigned long arg) static
Definition at line 38 of file file.c.
References ccfs_get_nested_file().
 {
     long rc = 0;
     struct file *lower_file = NULL;
     if (ccfs_get_nested_file(file))
         lower_file = ccfs_get_nested_file(file);
     if (lower_file && lower_file->f_op && lower_file->f_op->compat_ioctl)
         rc = lower_file->f_op->compat_ioctl(lower_file, cmd, arg);
     else
         rc = -ENOTTY;
     return rc;
 }
static int ccfs_open (struct inode * inode, struct file * file) static
Definition at line 61 of file file.c.
References ccfs_file_cache, ccfs_inode_to_private(), ccfs_set_file_private(), ccfs_set_nested_file(), ccfs_superblock_to_private(), ccfs_inode::lower_file, mdbg, minfo, and ccfs_super::prefetch.
 {
     struct file *lower_file = NULL;
     struct ccfs_file* file_info = NULL;
     int rc = 0;
     struct ccfs_super* sb_info = ccfs_superblock_to_private(inode->i_sb);
     file_info = kmem_cache_zalloc(ccfs_file_cache, GFP_KERNEL);
     if ( !file_info ) {
         rc = -ENOMEM;
         goto out;
     }
     ccfs_set_file_private(file, file_info);
     if ( !ccfs_inode_to_private(inode)->cacheable ) {
         // Haven't found a reason why would we reopen file here, we just wait let the file close and invalidate when nobody is using it. It is not 100% correct thing in cases of races
         // but since this is just a toy FS for experimental measurements, we can leave it as it is (unless we want to measure something with races in FS;)
         // TODO: This is a hack to reopen "root" dentry, it is not required for other entries. Moreover, we can now reset cacheable flag, but do we need to?
         // TODO: The comment above is really cryptic and not sure what I was trying to say :(... Generally, the files are refreshed when they are non-cacheable and
         // last reference to them is dropped which seems like a safe behaviour.. my suspition is, the comment was saying it does not happen for root node, which is always
         // held, but not sure.. for now disable due to caused races and if I find what is the real reason for this call I'll update this code/comment
         // ccfs_reopen_persistent_file(file->f_path.dentry, inode);
 //      if ( !invalidate_inode_pages2(inode->i_mapping) ) {
 //          minfo(ERR3, "Cache invalidation has failed");
 //      }
     }
     lower_file = ccfs_inode_to_private(inode)->lower_file;
     mdbg(INFO3, "Opening inode %p (file %p) associated with lower file: %p (dname: [%s]) - cacheable: %d", inode, file, lower_file, file->f_dentry->d_name.name, ccfs_inode_to_private(inode)->cacheable);
     if ( !lower_file ) {
         minfo(ERR3, "Assertion failed! Lower file does not exist!");
         kmem_cache_free(ccfs_file_cache, file_info);
         rc = -ENOENT;
         goto out;
     }
     ccfs_set_nested_file(file, lower_file);
     if ( sb_info->prefetch && S_ISREG(inode->i_mode) ) { // TODO: Schedule this only on first open of file?
         mdbg(INFO3,"Scheduling prefetch for inode %p", inode);
         // TODO: Uncommented as there seems to be some problem with prefetcher.. on freeing pages we usually got
         // General protection fault.. it is probably caused by allocation of pages in context of a different proces?
         //atomic_inc(&file->f_count); // Get reference that'll be freed by prefetcher after the prefetch is done
         //submit_for_prefetch(file);
     }
 out:
     return rc;
 }
int ccfs_readdir (struct file * filp, void * dirent, filldir_t filldir)
Definition at line 15 of file file.c.
References ccfs_get_nested_file(), and mdbg.
{
     int rc;
     struct file *lower_file;
     struct inode *inode;
     lower_file = ccfs_get_nested_file(filp);
     mdbg(INFO3, "Read filp %p with lower file: %p Pos: %lu (Upper pos: %lu)", filp, lower_file, (unsigned long)lower_file->f_pos, (unsigned long)filp->f_pos);
     lower_file->f_pos = filp->f_pos;
     inode = filp->f_path.dentry->d_inode;
     rc = vfs_readdir(lower_file, filldir, dirent);
     mdbg(INFO3, "Read return code: %d", rc);
     filp->f_pos = lower_file->f_pos;
     if (rc >= 0)
         fsstack_copy_attr_atime(inode, lower_file->f_path.dentry->d_inode);
     // The following does not seem to be true at least with kernel 2.6.33.1, so we leave dirs cacheable again
     // We need to disable file caching after readdir, as some filesystems (9P) are not able to repear readdirs on a same file!
     //ccfs_inode_to_private(inode)->cacheable = 0;
     return rc;
 }
static int ccfs_release (struct inode * inode, struct file * file) static
Definition at line 114 of file file.c.
References ccfs_file_cache, ccfs_get_file_private(), ccfs_set_nested_file(), and mdbg.
 {
     struct ccfs_file *file_info = ccfs_get_file_private(file);
     mdbg(INFO3,"Release file %p", file);
     ccfs_set_nested_file(file, NULL); // Improve error catching ;)
     kmem_cache_free(ccfs_file_cache, file_info);
     return 0;
 }
static ssize_t ccfs_splice_read (struct file * file, loff_t * ppos, struct pipe_inode_info * pipe, size_t count, unsigned int flags) static
Definition at line 177 of file file.c.
References ccfs_get_nested_file().
 {
     struct file *lower_file = NULL;
     int rc = -EINVAL;
     lower_file = ccfs_get_nested_file(file);
     if (lower_file->f_op && lower_file->f_op->splice_read)
         rc = lower_file->f_op->splice_read(lower_file, ppos, pipe,
                         count, flags);
     return rc;
 }
Variable Documentation
struct file_operations ccfs_dir_fops
Initial value:
= {
    .readdir = ccfs_readdir,
    .compat_ioctl = ccfs_ioctl,
    .mmap = ccfs_file_mmap,
    .open = ccfs_open,
    .flush = ccfs_flush,
    .release = ccfs_release,
    .fsync = ccfs_fsync,
    .fasync = ccfs_fasync,
    .splice_read = ccfs_splice_read,
}
Definition at line 212 of file file.c.
Referenced by ccfs_interpose().
struct kmem_cache* ccfs_file_cache
Definition at line 13 of file file.c.
Referenced by ccfs_open(), and ccfs_release().
struct file_operations ccfs_main_fops
Initial value:
= {
    .llseek = generic_file_llseek,
    .read = ccfs_do_sync_read,
    .aio_read = ccfs_generic_file_aio_read,
    .write = do_sync_write,
    .aio_write = generic_file_aio_write,
    .readdir = ccfs_readdir,
    .compat_ioctl = ccfs_ioctl,
    .mmap = ccfs_file_mmap,
    .open = ccfs_open,
    .flush = ccfs_flush,
    .release = ccfs_release,
    .fsync = ccfs_fsync,
    .fasync = ccfs_fasync,
    .splice_read = ccfs_splice_read,
}
Definition at line 224 of file file.c.
Referenced by ccfs_init_inode().