Clondike: proxyfs_real_file class
proxyfs_real_file class
proxyfs_file class
This is used on real file and proxyfs_server task.
Modules
proxyfs_generic_real_file class
This class is used by server task for accessing generic files.
proxyfs_pipe_real_file class
This class is used by server task for accessing pipe files.
proxyfs_tty_real_file class
This class is used by server task for accessing to TTYs.
Macros
#define PROXYFS_REAL_FILE(arg) ((struct proxyfs_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Functions
long proxyfs_real_file_do_ioctl (struct proxyfs_real_file *self, unsigned int cmd, unsigned long arg)
<<public>> Do ioctl
int proxyfs_real_file_write (struct proxyfs_real_file *self)
<<public>> Write to real file
int proxyfs_real_file_read (struct proxyfs_real_file *self)
<<public>> Read from real file
int proxyfs_real_file_open (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> "Open" file and send response message
int proxyfs_real_file_close (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> "Close" file
int proxyfs_real_file_mark_read_request (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> Marks file as read requested.
int proxyfs_real_file_init (struct proxyfs_real_file *self)
<<public>> Initialize real_file
void proxyfs_real_file_destroy (struct proxyfs_real_file *self)
<<public>> Deinitialize real_file
int proxyfs_real_file_fsync (struct proxyfs_real_file *self, struct proxyfs_peer_t *peer)
<<public>> fsync file
Detailed Description
This is used on real file and proxyfs_server task.
Macro Definition Documentation
#define PROXYFS_REAL_FILE (arg) ((struct proxyfs_real_file*)(arg))
<<public>> Casts to struct proxyfs_real_file_t *
Definition at line 74 of file proxyfs_real_file.h.
Referenced by proxyfs_generic_real_file_init(), proxyfs_generic_real_file_new(), proxyfs_pipe_real_file_duplicate(), proxyfs_pipe_real_file_init(), proxyfs_pipe_real_file_new(), proxyfs_server_duplicate_all_parent(), proxyfs_server_handle_msg(), proxyfs_server_overtake_file(), proxyfs_server_read_and_write_real_files(), proxyfs_server_release_all(), proxyfs_tty_real_file_destroy(), proxyfs_tty_real_file_duplicate(), and proxyfs_tty_real_file_init().
Function Documentation
int proxyfs_real_file_close (struct proxyfs_real_file * self, struct proxyfs_peer_t * peer)
<<public>> "Close" file
Parameters
*self - pointer to this file instance
*peer - instance of peer which is closing this file
Returns
zero on success
Definition at line 155 of file proxyfs_real_file.c.
References mdbg, MSG_CLOSE_RESP, PROXYFS_FILE, proxyfs_file_get_file_ident(), proxyfs_file_set_peer(), proxyfs_msg_new(), and proxyfs_peer_send_msg().
Referenced by proxyfs_server_handle_msg().
 {
     struct proxyfs_msg *msg;
     int rtn = 0;
     if( PROXYFS_FILE(self)->peer == peer ){
         msg = proxyfs_msg_new(MSG_CLOSE_RESP, proxyfs_file_get_file_ident(PROXYFS_FILE(self)), 0, NULL );
         if ( !msg )
             return -ENOMEM;
         proxyfs_peer_send_msg( peer, msg );
         proxyfs_file_set_peer(PROXYFS_FILE(self),NULL);
         PROXYFS_FILE(self)->write_buf_unconfirmed = 0;
     }
     else{
         mdbg(ERR3, "Close message come from peer which hasn't opened the file");
         rtn = -1;
     }
     return rtn;
 }
void proxyfs_real_file_destroy (struct proxyfs_real_file * self)
<<public>> Deinitialize real_file
Parameters
*self - pointer to this file instance
Definition at line 222 of file proxyfs_real_file.c.
References mdbg, PROXYFS_FILE, proxyfs_file_destroy(), proxyfs_file_get_file_ident(), and self.
Referenced by proxyfs_generic_real_file_new(), proxyfs_pipe_real_file_duplicate(), proxyfs_pipe_real_file_new(), proxyfs_server_duplicate_overtaken_file(), proxyfs_server_overtake_file(), proxyfs_server_read_and_write_real_files(), and proxyfs_tty_real_file_destroy().
 {
     struct list_head *l, *nxt;
     struct proxyfs_real_file_waiter* waiter;
     mdbg(INFO3, "Destroying real file: %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
     list_for_each_safe( l, nxt, &self->waiters_list ){
         waiter = list_entry(l, struct proxyfs_real_file_waiter, waiters_list);
         remove_wait_queue(waiter->wait_head, &waiter->wait);
         mdbg(INFO3, "Remove from waitqueue: %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
         kfree(waiter);
     }
     proxyfs_file_destroy( PROXYFS_FILE( self ) );
 }
long proxyfs_real_file_do_ioctl (struct proxyfs_real_file * self, unsigned int cmd, unsigned long arg)
<<public>> Do ioctl
Parameters
*self - pointer to this file instance
cmd - ioctl cmd
arg - ioctl arg
Returns
- return code of ioctl
Definition at line 51 of file proxyfs_real_file.c.
References mdbg, PROXYFS_FILE, proxyfs_file_get_file_ident(), and self.
Referenced by proxyfs_server_handle_msg().
 {
     int error = -ENOTTY;
     mm_segment_t old_fs;
     old_fs = get_fs();
     if (S_ISREG(self->file->f_path.dentry->d_inode->i_mode))
         goto out;
     if (!self->file->f_op)
         goto out;
     set_fs(KERNEL_DS);
     if (self->file->f_op->unlocked_ioctl) {
         error = self->file->f_op->unlocked_ioctl(self->file, cmd, arg);
         if (error == -ENOIOCTLCMD) {
             error = -EINVAL;
             mdbg(ERR2, "No ioctl cmd %d for file %lu", cmd, proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
         }
         goto out;
     } else if (self->file->f_op->ioctl) {
         lock_kernel();
         error = self->file->f_op->ioctl(self->file->f_path.dentry->d_inode,
                 self->file, cmd, arg);
         unlock_kernel();
     }
 out:
     set_fs(old_fs);
     return error;
 }
int proxyfs_real_file_fsync (struct proxyfs_real_file * self, struct proxyfs_peer_t * peer)
<<public>> fsync file
Parameters
*self - pointer to this file instance
*peer - instance of peer which is fsyncing this file
Returns
zero on success
Definition at line 183 of file proxyfs_real_file.c.
References mdbg, MSG_FSYNC_RESP, PROXYFS_FILE, proxyfs_file_get_file_ident(), proxyfs_msg_new(), proxyfs_peer_send_msg(), and self.
Referenced by proxyfs_server_handle_msg().
 {
     struct proxyfs_msg *msg;
     int rtn;
     if( PROXYFS_FILE(self)->peer == peer ){
         rtn = vfs_fsync( self->file, self->file->f_path.dentry, 0 );
         // TODO: How do we send the result of fsync back? Or is there some fsync failed msg to be sent?
         msg = proxyfs_msg_new(MSG_FSYNC_RESP, proxyfs_file_get_file_ident(PROXYFS_FILE(self)), 0, NULL );
         if ( !msg )
             return -ENOMEM;
         proxyfs_peer_send_msg( peer, msg );
     }
     else{
         mdbg(ERR3, "Fsync message come from peer which hasn't opened the file");
         rtn = -1;
     }
     return rtn;
 }
int proxyfs_real_file_init (struct proxyfs_real_file * self)
<<public>> Initialize real_file
Parameters
*self - pointer to this file instance
Returns
zero on success
Definition at line 119 of file proxyfs_real_file.c.
References PROXYFS_FILE, proxyfs_file_init(), and self.
Referenced by proxyfs_generic_real_file_new(), proxyfs_pipe_real_file_duplicate(), proxyfs_pipe_real_file_new(), and proxyfs_tty_real_file_init().
 {
     int rtn = proxyfs_file_init( PROXYFS_FILE( self ) );
     if( rtn == 0 ) {
         PROXYFS_FILE( self )->ops = &real_file_ops;
         INIT_LIST_HEAD( & self->shadow_list );
     }
     return rtn;
 }
int proxyfs_real_file_mark_read_request (struct proxyfs_real_file * self, struct proxyfs_peer_t * peer)
<<public>> Marks file as read requested.
. see MSG_READ_REQUEST comment for details
Definition at line 205 of file proxyfs_real_file.c.
References MSG_READ_REQUEST_RESP, PROXYFS_FILE, proxyfs_file_get_file_ident(), proxyfs_file_mark_read_requested(), proxyfs_msg_new(), and proxyfs_peer_send_msg().
Referenced by proxyfs_server_handle_msg().
{
     struct proxyfs_msg *msg;
     msg = proxyfs_msg_new(MSG_READ_REQUEST_RESP, proxyfs_file_get_file_ident(PROXYFS_FILE(self)), 0, NULL );
     if ( !msg )
         return -ENOMEM;
     proxyfs_file_mark_read_requested(PROXYFS_FILE(self));
     proxyfs_peer_send_msg( peer, msg );
     return 0;
 }
int proxyfs_real_file_open (struct proxyfs_real_file * self, struct proxyfs_peer_t * peer)
<<public>> "Open" file and send response message
Parameters
*self - pointer to this file instance
*peer - instance of peer which is opening this file
Returns
zero on success
Definition at line 135 of file proxyfs_real_file.c.
References mdbg, PROXYFS_FILE, proxyfs_file_set_peer(), and self.
Referenced by proxyfs_server_handle_msg().
 {
     int res;
     if( self->ops && self->ops->open ) {
         res = self->ops->open(self, peer);
         if ( !res )
             proxyfs_file_set_peer(PROXYFS_FILE(self),peer);
         return res;
     } else{
         mdbg(ERR3, "No open method");
         return -EINVAL;
     }
 }
int proxyfs_real_file_read (struct proxyfs_real_file * self)
<<public>> Read from real file
Parameters
*self - pointer to this file instance
Returns
amount of bytes read
Definition at line 104 of file proxyfs_real_file.c.
References mdbg, and self.
Referenced by proxyfs_server_read_and_write_real_files().
 {
     if( self->ops && self->ops->read )
         return self->ops->read(self);
     else{
         mdbg(ERR3, "No read method");
         return -1;
     }
 }
int proxyfs_real_file_write (struct proxyfs_real_file * self)
<<public>> Write to real file
Parameters
*self - pointer to this file instance
Returns
amount of bytes written
Definition at line 89 of file proxyfs_real_file.c.
References mdbg, and self.
Referenced by proxyfs_server_read_and_write_real_files().
 {
     if( self->ops && self->ops->write )
         return self->ops->write(self);
     else{
         mdbg(ERR3, "No write method");
         return -1;
     }
 }