Clondike: tcmi_man class
tcmi_man class
managers
This template <<singleton>> class implements a generic cluster node manager - TCMI manager.
Data Structures
struct tcmi_man
A compound structure that holds all current listenings and migration managers.
struct tcmi_man_ops
Migration manager operations that support polymorphism.
Macros
#define TCMI_MAN(man) ((struct tcmi_man *)man)
Casts to the TCMI manager.
Functions
static int tcmi_man_init_ctlfs_dirs (struct tcmi_man *self, struct tcmi_ctlfs_entry *root, const char *man_dirname)
<<private>> Creates the directories as described in here .
static int tcmi_man_init_ctlfs_files (struct tcmi_man *self)
<<private>> Creates the static files described here .
static void tcmi_man_stop_ctlfs_dirs (struct tcmi_man *self)
<<private>> Destroys all ctlfs directories, first the singleton instance specific directories are destroyed
static void tcmi_man_stop_ctlfs_files (struct tcmi_man *self)
<<private>> Unregisters and releases all control files.
static int tcmi_man_init_migration (struct tcmi_man *self)
<<private>>.
static struct tcmi_migman * tcmi_man_get_non_shutdowning_migman (struct tcmi_man *self)
Finds and returns arbitrary migration manager that is either in INIT or CONNECTED state.
static void tcmi_man_stop_migration (struct tcmi_man *self)
<<private>> Stops all migration components.
static int tcmi_man_stop (void *obj, void *data)
<<private>> If the user called this method with parameter > 0, the TCMI manager stops the migration framework.
static int tcmi_man_emig_ppm_p (void *obj, void *data)
<<private>> TCMI ctlfs write method - emigration PPM P What needs to be done:
int tcmi_man_emig_npm (struct tcmi_man *self, pid_t pid, u_int32_t migman_id, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
<<public>> Method that performs non-preemtive migration
int tcmi_man_fork (struct tcmi_man *self, struct task_struct *parent, struct task_struct *child)
<<public>> Method that performs task fork
static int tcmi_man_mig_home_ppm_p (void *obj, void *data)
<<private>> TCMI ctlfs write method - migration home.
int tcmi_man_init (struct tcmi_man *self, struct tcmi_ctlfs_entry *root, struct tcmi_man_ops *ops, const char *man_dirname)
<<public>> Initializes the TCMI manager
void tcmi_man_shutdown (struct tcmi_man *self)
<<public>> Shuts down TCMI manager
int tcmi_man_send_generic_user_message (struct tcmi_man *self, int target_slot_index, int user_data_size, char *user_data)
<<public>> Send generic user message
static struct tcmi_slot * tcmi_man_reserve_migmanslot (struct tcmi_man *self)
<<public>> Reserves an empty slot for a new migration manager.
static void tcmi_man_release_migmanslot (struct tcmi_man *self, struct tcmi_slot *slot)
<<public>> Releases a migration slot that has been previously reserved.
static struct tcmi_ctlfs_entry * tcmi_man_root (struct tcmi_man *self)
<<public>> Accessor for a main(root) directory of a particular TCMI manager.
static struct tcmi_ctlfs_entry * tcmi_man_nodes_dir (struct tcmi_man *self)
<<public>> Accessor for a cluster nodes directory of a particular TCMI manager.
static struct tcmi_ctlfs_entry * tcmi_man_migproc_dir (struct tcmi_man *self)
<<public>> Accessor for migproc directory.
static u_int32_t tcmi_man_id (struct tcmi_man *self)
<<public>> TCMI manager ID accessor.
Detailed Description
This template <<singleton>> class implements a generic cluster node manager - TCMI manager.
It provides generic functionality to control migration managers.
Each migration manager is associated with one registered PEN. The user controls the cluster node(PEN,CCN or both) by manipulating TCMI control file system . The directory/file layout can be divided into three groups of files/directories based on their maintainers, which can be:
TCMI manager
TCMI migration manager
TCMI preemptive migration component
TCMI non-preemtive migration component
TCMI tasks
Description of a particular layout is detailed at TCMI CCN manager and TCMI PEN manager
There is an upper bound on the number of registered nodes. This is a very common approach in UNIX design as it prevents problems with overloading the CCN. This parameter is currently set at compile time. but might be made configurable via ctlfs from user space.
The core datastructure for keeping track of migration managers(=registered cluster nodes) is a slot vector .
The TCMI manager carries a unique identifier that is generated randomly upon initialization. This ID then identifies a node in cluster.
Data Structure Documentation
struct tcmi_man
A compound structure that holds all current listenings and migration managers.
This is for internal use only.
Definition at line 92 of file tcmi_man.h.
Data Fields
struct tcmi_ctlfs_entry * d_man root directory of CCN or PEN where all control files/directories reside
struct tcmi_ctlfs_entry * d_mig TCMI ctlfs - migration directory.
struct tcmi_ctlfs_entry * d_migproc TCMI ctlfs - migproc directory for migrated processes.
struct tcmi_ctlfs_entry * d_nodes directory where all registered nodes (CCN's or PEN's) reside
struct tcmi_ctlfs_entry * f_emig_ppm_p TCMI ctlfs - migration control file (PPM physical ckpt.)
struct tcmi_ctlfs_entry * f_mig_home_ppm_p TCMI ctlfs - migration control file (PPM physical ckpt.)
struct tcmi_ctlfs_entry * f_stop TCMI ctlfs - stop control file.
u_int32_t id Unique manager ID.
struct tcmi_slotvec * mig_mans slot container for migration managers, 1 manager per slot
struct tcmi_man_ops * ops Operations specific to a CCN/PEN manager resp.
atomic_t ready indicates the manager is ready - used for proper shutdown
struct tcmi_man_ops
Migration manager operations that support polymorphism.
Definition at line 128 of file tcmi_man.h.
Data Fields
int(* init_ctlfs_dirs)(void)
Initializes TCMI ctlfs directories.
int(* init_ctlfs_files)(void)
Initializes TCMI ctlfs files.
void(* stop_ctlfs_dirs)(void)
Destroys all TCMI ctlfs directories.
void(* stop_ctlfs_files)(void)
Destroys all TCMI ctlfs files.
int(* emigrate_ppm_p)(pid_t, struct tcmi_migman *)
Preemptive emigration method.
int(* emigrate_npm)(pid_t, struct tcmi_migman *, struct pt_regs *regs, struct tcmi_npm_params *)
Non-preemptive emigration method.
int(* migrate_home_ppm_p)(pid_t)
Migrate home method.
int(* fork)(struct task_struct *parent, struct task_struct *child, struct tcmi_migman *)
Transforms forked process to a same type of task as parent and assigns it with a same manager.
void(* stop)(void)
Instance specific stop method.
Field Documentation
int(* tcmi_man_ops::emigrate_npm)(pid_t, struct tcmi_migman *, struct pt_regs *regs, struct tcmi_npm_params *)
Non-preemptive emigration method.
Definition at line 140 of file tcmi_man.h.
int(* tcmi_man_ops::emigrate_ppm_p)(pid_t, struct tcmi_migman *)
Preemptive emigration method.
Definition at line 138 of file tcmi_man.h.
int(* tcmi_man_ops::fork)(struct task_struct *parent, struct task_struct *child, struct tcmi_migman *)
Transforms forked process to a same type of task as parent and assigns it with a same manager.
Definition at line 144 of file tcmi_man.h.
int(* tcmi_man_ops::init_ctlfs_dirs)(void)
Initializes TCMI ctlfs directories.
Definition at line 130 of file tcmi_man.h.
int(* tcmi_man_ops::init_ctlfs_files)(void)
Initializes TCMI ctlfs files.
Definition at line 132 of file tcmi_man.h.
int(* tcmi_man_ops::migrate_home_ppm_p)(pid_t)
Migrate home method.
Definition at line 142 of file tcmi_man.h.
void(* tcmi_man_ops::stop)(void)
Instance specific stop method.
Definition at line 147 of file tcmi_man.h.
void(* tcmi_man_ops::stop_ctlfs_dirs)(void)
Destroys all TCMI ctlfs directories.
Definition at line 134 of file tcmi_man.h.
void(* tcmi_man_ops::stop_ctlfs_files)(void)
Destroys all TCMI ctlfs files.
Definition at line 136 of file tcmi_man.h.
Macro Definition Documentation
#define TCMI_MAN (man) ((struct tcmi_man *)man)
Casts to the TCMI manager.
Definition at line 151 of file tcmi_man.h.
Referenced by check_duplicates(), tcmi_ccnman_init(), tcmi_ccnman_init_ctlfs_dirs(), tcmi_ccnman_init_ctlfs_files(), tcmi_ccnman_process_sock(), tcmi_ccnman_shutdown(), tcmi_man_emig_ppm_p(), tcmi_man_mig_home_ppm_p(), tcmi_man_stop(), tcmi_mighooks_execve(), tcmi_penman_connect(), tcmi_penman_init(), tcmi_penman_init_ctlfs_files(), tcmi_penman_shutdown(), tcmi_send_generic_user_message_handler(), and tcmi_syscall_hooks_in_fork().
Function Documentation
int tcmi_man_emig_npm (struct tcmi_man * self, pid_t pid, u_int32_t migman_id, struct pt_regs * regs, struct tcmi_npm_params * npm_params)
<<public>> Method that performs non-preemtive migration
Parameters
pid Pid of the process to be migrated
migman_id Id of the migration manager to be used for the migration
npm_params Params of the non-preemptive migration
Definition at line 504 of file tcmi_man.c.
References mdbg, tcmi_migman::node, self, tcmi_migman_get(), tcmi_migman_put(), tcmi_slot_find_first, tcmi_slot_index(), tcmi_slotvec_at(), tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_try_npm_on_exec().
 {
     int err = 0;
     struct tcmi_slot *slot;
     struct tcmi_migman *migman = NULL;
     mdbg(INFO2, "Non preemptive emigration request PID %d, migration manager %d",
          pid, migman_id);
     /* lookup the migration manager first */
     tcmi_slotvec_lock(self->mig_mans);
     if (!(slot = tcmi_slotvec_at(self->mig_mans, migman_id))) {
         mdbg(ERR3, "Invalid migration manager identifier %d", migman_id);
         goto exit0;
     }
     /* there is always only one mig man per slot */
     tcmi_slot_find_first(migman, slot, node);
     /* Slot might exist, but it might still be empty*/
     if (!tcmi_migman_get(migman)) {
         mdbg(ERR3, "No migration manager in the slot(%d)", tcmi_slot_index(slot));
         goto exit0;
     }
     tcmi_slotvec_unlock(self->mig_mans);
     if (self->ops->emigrate_npm)
         err = self->ops->emigrate_npm(pid, migman, regs, npm_params);
     /* release the migration manager */
     tcmi_migman_put(migman);
     return err;
     /* error handling */
  exit0:
     tcmi_slotvec_unlock(self->mig_mans);
     return -EINVAL;
 }
static int tcmi_man_emig_ppm_p (void * obj, void * data) static
<<private>> TCMI ctlfs write method - emigration PPM P What needs to be done:
find the requested migration manager
call instance specific emigration method.
Parameters
*obj - pointer to a particular TCMI manager singleton instance
*data - an array of two integers first contains PID, second one contains the desired manager identifier as it appears in ctlfs. It is the name of its directory.
Returns
0 upon success
Definition at line 455 of file tcmi_man.c.
References mdbg, tcmi_migman::node, pid, self, TCMI_MAN, tcmi_migman_get(), tcmi_migman_put(), tcmi_slot_find_first, tcmi_slot_index(), tcmi_slotvec_at(), tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_man_init_ctlfs_files().
 {
     int err = 0;
     pid_t pid = *((int *)data);
     u_int32_t migman_id = *(((int *)data) + 1);
     struct tcmi_man *self = TCMI_MAN(obj);
     struct tcmi_slot *slot;
     struct tcmi_migman *migman = NULL;
     mdbg(INFO2, "Emigration request PID %d, migration manager %d",
          pid, migman_id);
     /* lookup the migration manager first */
     tcmi_slotvec_lock(self->mig_mans);
     if (!(slot = tcmi_slotvec_at(self->mig_mans, migman_id))) {
         mdbg(ERR3, "Invalid migration manager identifier %d", migman_id);
         goto exit0;
     }
     /* there is always only one mig man per slot */
     tcmi_slot_find_first(migman, slot, node);
     /* Slot might exist, but it might still be empty*/
     if (!tcmi_migman_get(migman)) {
         mdbg(ERR3, "No migration manager in the slot(%d)", tcmi_slot_index(slot));
         goto exit0;
     }
     tcmi_slotvec_unlock(self->mig_mans);
     if (self->ops->emigrate_ppm_p)
         err = self->ops->emigrate_ppm_p(pid, migman);
     /* release the migration manager */
     tcmi_migman_put(migman);
     return err;
     /* error handling */
  exit0:
     tcmi_slotvec_unlock(self->mig_mans);
     return -EINVAL;
 }
int tcmi_man_fork (struct tcmi_man * self, struct task_struct * parent, struct task_struct * child)
<<public>> Method that performs task fork
Definition at line 542 of file tcmi_man.c.
References tcmi_migman::ccn_id, flags, mdbg, tcmi_task::migman, tcmi_task::node, tcmi_migman::pen_id, self, tcmi_migman_get(), tcmi_migman_put(), tcmi_slot_find_first, tcmi_slot_index(), tcmi_slotvec_at(), tcmi_slotvec_lock(), tcmi_slotvec_unlock(), TCMI_TASK, and tcmi_task_migman_slot_index().
Referenced by tcmi_syscall_hooks_in_fork().
{
     int err = 0;
     struct tcmi_slot *slot;
     struct tcmi_migman *migman = NULL;
     u_int migman_slot_index;
     struct tcmi_task* tcmi_parent;
     unsigned long flags;
     // We perform all manager fork operation with interrupts disabled to prevent possible lock inversion problems
     // Not sure what the intention was, but it does not work well.. interfere with getinode on ccfs initialization
     // (there are actually more interferences and we ideally need to get rid of getinode in this call chain altoghether)
 //  raw_local_irq_save(flags);
     tcmi_parent = TCMI_TASK(parent->tcmi.tcmi_task);
     migman_slot_index = tcmi_task_migman_slot_index(tcmi_parent);
     BUG_ON(parent->tcmi.task_type != shadow && parent->tcmi.task_type != guest);
     BUG_ON(tcmi_parent->migman->ccn_id != self->id && tcmi_parent->migman->pen_id != self->id);
     mdbg(INFO2, "Performing fork of task pid: %d to child: %d (mig manager %u)", parent->pid, child->pid, migman_slot_index);
     if ( child->tcmi.tcmi_task != parent->tcmi.tcmi_task ) { // This should hold, since the task struts were simply copied
         mdbg(ERR3, "Assertion error! Tasks after fork should have same tcmi task");
         return -EINVAL;
     }
     // We've verified the task is really copied and now we need to prepare it to be attached.. for that we need to reset its TCMI structures first
     child->tcmi.tcmi_task = NULL;
     child->tcmi.mig_mode_handler = NULL;
     /* lookup the migration manager first */
     tcmi_slotvec_lock(self->mig_mans);
     if (!(slot = tcmi_slotvec_at(self->mig_mans, migman_slot_index))) {
         mdbg(ERR3, "Invalid migration manager identifier %lu", (unsigned long)migman_slot_index);
         goto exit0;
     }
     /* there is always only one mig man per slot */
     tcmi_slot_find_first(migman, slot, node);
     /* Slot might exist, but it might still be empty*/
     if (!tcmi_migman_get(migman)) {
         mdbg(ERR3, "No migration manager in the slot(%d)", tcmi_slot_index(slot));
         goto exit0;
     }
     tcmi_slotvec_unlock(self->mig_mans);
     if (self->ops->fork)
         err = self->ops->fork(parent, child, migman);
 //  raw_local_irq_restore(flags);
     /* release the migration manager, task has now its own reference to it */
     tcmi_migman_put(migman);
     return err;
     /* error handling */
 exit0:
     raw_local_irq_restore(flags);
     tcmi_slotvec_unlock(self->mig_mans);
     return -EINVAL;
 }
static struct tcmi_migman* tcmi_man_get_non_shutdowning_migman (struct tcmi_man * self) static read
Finds and returns arbitrary migration manager that is either in INIT or CONNECTED state.
Definition at line 372 of file tcmi_man.c.
References self, TCMI_MIGMAN_CONNECTED, TCMI_MIGMAN_INIT, tcmi_migman_state(), tcmi_slot_entry, tcmi_slot_for_each, tcmi_slotvec_for_each_used_slot, tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_man_stop_migration().
{
     struct tcmi_slot *slot;
     tcmi_slot_node_t* node;
     struct tcmi_migman *migman = NULL;
     tcmi_migman_state_t migman_state;
     tcmi_slotvec_lock(self->mig_mans);
     tcmi_slotvec_for_each_used_slot(slot, self->mig_mans) {
         tcmi_slot_for_each(node, slot) {
             migman = tcmi_slot_entry(node, struct tcmi_migman, node);
             migman_state = tcmi_migman_state(migman);
             if ( migman_state == TCMI_MIGMAN_INIT || migman_state == TCMI_MIGMAN_CONNECTED ) {
             goto found;
             }
             migman = NULL;
         };
     };
 found:
     tcmi_slotvec_unlock(self->mig_mans);
     return migman;
 }
static u_int32_t tcmi_man_id (struct tcmi_man * self) inline static
<<public>> TCMI manager ID accessor.
Parameters
*self - a particular manager singleton instance
Returns
manager ID
Definition at line 234 of file tcmi_man.h.
Referenced by tcmi_ccnman_process_sock(), and tcmi_penman_connect().
 {
     return self->id;
 }
int tcmi_man_init (struct tcmi_man * self, struct tcmi_ctlfs_entry * root, struct tcmi_man_ops * ops, const char * man_dirname)
<<public>> Initializes the TCMI manager
<<public>> Initializes the TCMI manager
This generic init method, initializes basic singleton instance items common for both TCMI managers (CCN and PEN). The initialization is done in this order:
create a slot vector for migration managers
create TCMI ctlfs directories
create TCMI ctlfs control files
Parameters
*self - a particular singleton instance to be initialized
*root - root directory of the filesystem, where all entries are to be created
*ops - instance specific operations
*man_dirname - name for the main directory of the manager (e.g. ccn or pen) also represent connected nodes (e.g. all PEN's from CCN prospective)
Returns
0 upon success
Definition at line 69 of file tcmi_man.c.
References MAX_NODES, mdbg, self, tcmi_man_init_ctlfs_dirs(), tcmi_man_init_ctlfs_files(), tcmi_man_init_migration(), tcmi_man_stop_ctlfs_dirs(), tcmi_man_stop_migration(), tcmi_slotvec_new(), and tcmi_slotvec_put().
Referenced by tcmi_ccnman_init(), and tcmi_penman_init().
 {
     if (!ops) {
         mdbg(ERR3, "Missing migration manager operations!");
         goto exit0;
     }
     atomic_set(&self->ready, 0);
     self->ops = ops;
     if (!(self->mig_mans = tcmi_slotvec_new(MAX_NODES)))
         goto exit0;
     if (tcmi_man_init_ctlfs_dirs(self, root, man_dirname) < 0)
         goto exit1;
     if (tcmi_man_init_migration(self) < 0)
         goto exit2;
     if (tcmi_man_init_ctlfs_files(self) < 0)
         goto exit3;
     atomic_set(&self->ready, 1);
     get_random_bytes(&self->id, sizeof(u_int32_t));
     return 0;
     /* error handling */
  exit3:
     tcmi_man_stop_migration(self);
  exit2:
     tcmi_man_stop_ctlfs_dirs(self);
  exit1:
     tcmi_slotvec_put(self->mig_mans);
  exit0:
     return -EINVAL;
 }
static int tcmi_man_init_ctlfs_dirs (struct tcmi_man * self, struct tcmi_ctlfs_entry * root, const char * man_dirname) static
<<private>> Creates the directories as described in here .
It is necessary to get the current root directory of the TCMI ctlfs first. So that it won't get unlinked under us.
Parameters
*self - a particular manager singleton instance
*root - root directory of the filesystem, where all entries are to be created
*man_dirname - name for the main directory of the manager (e.g. ccn or pen)
Returns
0 upon success
Definition at line 227 of file tcmi_man.c.
References mdbg, self, tcmi_ctlfs_dir_new(), tcmi_ctlfs_entry_put(), and TCMI_PERMS_DIR.
Referenced by tcmi_man_init().
 {
     mdbg(INFO4, "Creating directories");
     if (!root)
         goto exit0;
     if (!(self->d_man = tcmi_ctlfs_dir_new(root, TCMI_PERMS_DIR, man_dirname)))
         goto exit0;
     if (!(self->d_nodes =
           tcmi_ctlfs_dir_new(self->d_man, TCMI_PERMS_DIR, "nodes")))
         goto exit1;
     if (!(self->d_mig =
           tcmi_ctlfs_dir_new(self->d_man, TCMI_PERMS_DIR, "mig")))
         goto exit2;
     if (!(self->d_migproc =
           tcmi_ctlfs_dir_new(self->d_mig, TCMI_PERMS_DIR, "migproc")))
         goto exit3;
     if (self->ops->init_ctlfs_dirs && self->ops->init_ctlfs_dirs()) {
         mdbg(ERR3, "Failed to create specific ctlfs directories!");
         goto exit4;
     }
     return 0;
     /* error handling */
  exit4:
     tcmi_ctlfs_entry_put(self->d_migproc);
  exit3:
     tcmi_ctlfs_entry_put(self->d_mig);
  exit2:
     tcmi_ctlfs_entry_put(self->d_nodes);
  exit1:
     tcmi_ctlfs_entry_put(self->d_man);
  exit0:
     return -EINVAL;
 }
static int tcmi_man_init_ctlfs_files (struct tcmi_man * self) static
<<private>> Creates the static files described here .
Parameters
*self - a particular manager singleton instance
Returns
0 upon success
Definition at line 276 of file tcmi_man.c.
References mdbg, self, tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), tcmi_ctlfs_intfile_new(), tcmi_man_emig_ppm_p(), tcmi_man_mig_home_ppm_p(), tcmi_man_stop(), and TCMI_PERMS_FILE_W.
Referenced by tcmi_man_init().
 {
     mdbg(INFO4, "Creating files");
     if (!(self->f_stop =
           tcmi_ctlfs_intfile_new(self->d_man, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_man_stop,
                      sizeof(int), "stop")))
         goto exit0;
     if (!(self->f_emig_ppm_p =
           tcmi_ctlfs_intfile_new(self->d_mig, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_man_emig_ppm_p,
                      sizeof(int) * 2, "emigrate-ppm-p")))
         goto exit1;
     if (!(self->f_mig_home_ppm_p =
           tcmi_ctlfs_intfile_new(self->d_mig, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_man_mig_home_ppm_p,
                      sizeof(int), "migrate-home")))
         goto exit2;
     if (self->ops->init_ctlfs_files && self->ops->init_ctlfs_files()) {
         mdbg(ERR3, "Failed to create specific ctlfs files!");
         goto exit3;
     }
     return 0;
     /* error handling */
  exit3:
     tcmi_ctlfs_file_unregister(self->f_mig_home_ppm_p);
     tcmi_ctlfs_entry_put(self->f_mig_home_ppm_p);
  exit2:
     tcmi_ctlfs_file_unregister(self->f_emig_ppm_p);
     tcmi_ctlfs_entry_put(self->f_emig_ppm_p);
  exit1:
     tcmi_ctlfs_file_unregister(self->f_stop);
     tcmi_ctlfs_entry_put(self->f_stop);
  exit0:
     return -EINVAL;
 }
static int tcmi_man_init_migration (struct tcmi_man * self) static
<<private>>.
Parameters
*self - a particular manager singleton instance
Returns
0 upon success
Definition at line 364 of file tcmi_man.c.
References mdbg.
Referenced by tcmi_man_init().
 {
     mdbg(INFO3, "Initializing migration components");
     return 0;
 }
static int tcmi_man_mig_home_ppm_p (void * obj, void * data) static
<<private>> TCMI ctlfs write method - migration home.
Migration home requires delegating work to the instance specific method once we extract the requested PID.
Parameters
*obj - pointer to a particular TCMI manager singleton instance
*data - contains PID that is to be migrated home
Returns
0 upon success
Definition at line 614 of file tcmi_man.c.
References mdbg, pid, self, and TCMI_MAN.
Referenced by tcmi_man_init_ctlfs_files().
 {
     int err = 0;
     pid_t pid = *((int *)data);
     struct tcmi_man *self = TCMI_MAN(obj);
     mdbg(INFO2, "Migration home request for PID %d", pid);
     if (self->ops->migrate_home_ppm_p)
         err = self->ops->migrate_home_ppm_p(pid);
     return err;
 }
static struct tcmi_ctlfs_entry* tcmi_man_migproc_dir (struct tcmi_man * self) static read
<<public>> Accessor for migproc directory.
Parameters
*self - a particular manager singleton instance
Returns
migproc directory
Definition at line 223 of file tcmi_man.h.
Referenced by tcmi_ccnman_process_sock(), and tcmi_penman_connect().
 {
     return self->d_migproc;
 }
static struct tcmi_ctlfs_entry* tcmi_man_nodes_dir (struct tcmi_man * self) static read
<<public>> Accessor for a cluster nodes directory of a particular TCMI manager.
Parameters
*self - a particular manager singleton instance
Returns
nodesdirectory
Definition at line 212 of file tcmi_man.h.
Referenced by tcmi_ccnman_process_sock(), and tcmi_penman_connect().
 {
     return self->d_nodes;
 }
static void tcmi_man_release_migmanslot (struct tcmi_man * self, struct tcmi_slot * slot) inline static
<<public>> Releases a migration slot that has been previously reserved.
It is needed when new migration manager fails and won't inserted into the slot. The user that returns the slot back to the vector.
Parameters
*self - a particular manager singleton instance
*slot thatis to be release back to the vector
Definition at line 187 of file tcmi_man.h.
References tcmi_slot_move_unused().
Referenced by tcmi_ccnman_process_sock(), and tcmi_penman_connect().
 {
     tcmi_slot_move_unused(slot);
 }
static struct tcmi_slot* tcmi_man_reserve_migmanslot (struct tcmi_man * self) static read
<<public>> Reserves an empty slot for a new migration manager.
Parameters
*self - a particular manager singleton instance
Returns
an empty slot(if available) or NULL
Definition at line 172 of file tcmi_man.h.
References self, and tcmi_slotvec_reserve_empty().
Referenced by tcmi_ccnman_process_sock(), and tcmi_penman_connect().
 {
     return tcmi_slotvec_reserve_empty(self->mig_mans);
 }
static struct tcmi_ctlfs_entry* tcmi_man_root (struct tcmi_man * self) static read
<<public>> Accessor for a main(root) directory of a particular TCMI manager.
Parameters
*self - a particular manager singleton instance
Returns
main manager directory
Definition at line 200 of file tcmi_man.h.
Referenced by tcmi_ccnman_init_ctlfs_dirs(), tcmi_ccnman_init_ctlfs_files(), and tcmi_penman_init_ctlfs_files().
 {
     return self->d_man;
 }
int tcmi_man_send_generic_user_message (struct tcmi_man * self, int target_slot_index, int user_data_size, char * user_data)
<<public>> Send generic user message
Definition at line 173 of file tcmi_man.c.
References mdbg, tcmi_migman::node, self, tcmi_man_do_send_generic_user_message(), tcmi_migman_get(), tcmi_migman_put(), tcmi_slot_find_first, tcmi_slot_index(), tcmi_slotvec_at(), tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_send_generic_user_message_handler().
{
     int err;
     struct tcmi_slot *slot;
     struct tcmi_migman *migman = NULL;
     /* lookup the migration manager first */
     tcmi_slotvec_lock(self->mig_mans);
     if (!(slot = tcmi_slotvec_at(self->mig_mans, target_slot_index))) {
         mdbg(ERR3, "Invalid migration manager identifier %d", target_slot_index);
         err = -ENOENT;
         goto exit0;
     }
     /* there is always only one mig man per slot */
     tcmi_slot_find_first(migman, slot, node);
     /* Slot might exist, but it might still be empty*/
     if (!tcmi_migman_get(migman)) {
         mdbg(ERR3, "No migration manager in the slot(%d)", tcmi_slot_index(slot));
         err = -ENOENT;
         goto exit0;
     }
     tcmi_slotvec_unlock(self->mig_mans);
     err = tcmi_man_do_send_generic_user_message(self, target_slot_index, user_data_size, user_data, migman);
     /* release the migration manager */
     tcmi_migman_put(migman);
     return err;
     /* error handling */
  exit0:
     tcmi_slotvec_unlock(self->mig_mans);
     return err;
 }
void tcmi_man_shutdown (struct tcmi_man * self)
<<public>> Shuts down TCMI manager
<<public>> Shuts down TCMI manager
unregister all ctlfs files as we don't want anymore requests from users.
shutdown the migration framework. This requires terminating all migration managers(results in termination or migration back of all processes)
unregister all ctlfs directories
Parameters
*self - a particular manager singleton instance to be shutdown
Definition at line 142 of file tcmi_man.c.
References self, tcmi_man_stop_ctlfs_dirs(), tcmi_man_stop_ctlfs_files(), tcmi_man_stop_migration(), tcmi_man_wait_for_migmans_termination(), and tcmi_slotvec_put().
Referenced by tcmi_ccnman_shutdown(), and tcmi_penman_shutdown().
 {
     if ( atomic_cmpxchg(&self->ready, 1, 0) == 1 ) {
         tcmi_man_stop_ctlfs_files(self);
         tcmi_man_stop_ctlfs_dirs(self);
         /* Request async mig mans shutdown */
         tcmi_man_stop_migration(self);
         /* Wait for migmans to terminate */
         tcmi_man_wait_for_migmans_termination(self);
         tcmi_slotvec_put(self->mig_mans);
     }
 }
static int tcmi_man_stop (void * obj, void * data) static
<<private>> If the user called this method with parameter > 0, the TCMI manager stops the migration framework.
This results in migrating all processes back to CCN and terminating all migration managers.
Parameters
*obj - pointer to a particular TCMI manager singleton instance
*data - if the value that it points to is >0, the action is taken
Returns
always 0 (success)
NOTE: What is a purpose of this method? There is no inverse operation to stop, so is that essentially different from shutdown? ms
Definition at line 428 of file tcmi_man.c.
References mdbg, self, TCMI_MAN, and tcmi_man_stop_migration().
Referenced by tcmi_man_init_ctlfs_files().
 {
     int stop = *((int *)data);
     struct tcmi_man *self = TCMI_MAN(obj);
     mdbg(INFO3, "TCMI manager stop request, action = %d", stop);
     if (stop) {
         /* TODO: Stop operations are called just here, but shouldn't we call them as well on shutdown? */
         if (self->ops->stop)
             self->ops->stop();
         tcmi_man_stop_migration(self);
     }
     return 0;
 }
static void tcmi_man_stop_ctlfs_dirs (struct tcmi_man * self) static
<<private>> Destroys all ctlfs directories, first the singleton instance specific directories are destroyed
Parameters
*self - a particular manager singleton instance
Definition at line 324 of file tcmi_man.c.
References mdbg, self, and tcmi_ctlfs_entry_put().
Referenced by tcmi_man_init(), and tcmi_man_shutdown().
 {
     mdbg(INFO3, "Destroying  TCMI manager ctlfs directories");
     if (self->ops->stop_ctlfs_dirs)
         self->ops->stop_ctlfs_dirs();
     tcmi_ctlfs_entry_put(self->d_migproc);
     tcmi_ctlfs_entry_put(self->d_mig);
     tcmi_ctlfs_entry_put(self->d_nodes);
     tcmi_ctlfs_entry_put(self->d_man);
 }
static void tcmi_man_stop_ctlfs_files (struct tcmi_man * self) static
<<private>> Unregisters and releases all control files.
Parameters
*self - a particular manager singleton instance
Definition at line 341 of file tcmi_man.c.
References mdbg, self, tcmi_ctlfs_entry_put(), and tcmi_ctlfs_file_unregister().
Referenced by tcmi_man_shutdown().
 {
     mdbg(INFO3, "Destroying  TCMI manager ctlfs files");
     if (self->ops->stop_ctlfs_files)
         self->ops->stop_ctlfs_files();
     tcmi_ctlfs_file_unregister(self->f_stop);
     tcmi_ctlfs_entry_put(self->f_stop);
     tcmi_ctlfs_file_unregister(self->f_emig_ppm_p);
     tcmi_ctlfs_entry_put(self->f_emig_ppm_p);
     tcmi_ctlfs_file_unregister(self->f_mig_home_ppm_p);
     tcmi_ctlfs_entry_put(self->f_mig_home_ppm_p);
 }
static void tcmi_man_stop_migration (struct tcmi_man * self) static
<<private>> Stops all migration components.
Terminates all migration managers, they are responsible for migrating all processes to the home node or a another execution node.
Parameters
*self - a particular manager singleton instance
Definition at line 404 of file tcmi_man.c.
References mdbg, tcmi_man_get_non_shutdowning_migman(), and tcmi_migman_stop().
Referenced by tcmi_man_init(), tcmi_man_shutdown(), and tcmi_man_stop().
 {
     struct tcmi_migman *migman = tcmi_man_get_non_shutdowning_migman(self);
     while (migman) {
         mdbg(INFO3, "Requesting migration manager shutdown.");
         tcmi_migman_stop(migman);
         migman = tcmi_man_get_non_shutdowning_migman(self);
     }
 }