Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/tcmi/migration/fs/9p_fs_global_mounter.h File Reference
9p_fs_global_mounter.h File Reference
Functions
struct fs_mounter * new_9p_global_fs_mounter (struct fs_mount_params *params)
9p mounter handles mounting of Plan9 filesystem in a public namespace.
Function Documentation
struct fs_mounter* new_9p_global_fs_mounter (struct fs_mount_params * params) read
9p mounter handles mounting of Plan9 filesystem in a public namespace.
It does not support any security right not.Creates a new instance of the 9p file system mounter
Definition at line 61 of file 9p_fs_global_mounter.c.
References chroot_to_mount(), fs_mounter::free, global_9p_mount(), fs_mounter::global_mount, fs_mounter::params, and fs_mounter::private_mount.
Referenced by get_new_mounter().
{
     struct fs_mounter* mounter = kmalloc(sizeof(struct fs_mounter), GFP_KERNEL);
     if ( !mounter )
         return NULL;
     mounter->global_mount = global_9p_mount;
     mounter->private_mount = chroot_to_mount;
     mounter->free = NULL;
     mounter->params = *params;
     return mounter;
 }