Clondike: kkc_sock class
kkc_sock class
KKC
This is a generic KKC socket.
Modules
kkc_sock_tcp class
This class is a TCP socket.
Data Structures
struct kkc_sock
A coumpound structure that contains generic information about a KKC socket.
struct kkc_sock_ops
Socket operations that support polymorphism.
Macros
#define KKC_SOCK_MAX_ADDR_LENGTH 100
Maximum address length.
#define KKC_SOCK(s) ((struct kkc_sock*)s)
Casts to the kkc_sock instance.
Typedefs
typedef void(* kkc_data_ready)(void *data, int bytes)
Callback function prototype, that can be registered to be notified about in case there are some data ready to be read on a socket.
Enumerations
enum kkc_sock_flags_t { KKC_SOCK_BLOCK, KKC_SOCK_NONBLOCK }
Flags for receive and accept operations.
Functions
static int kkc_sock_send_recv (struct kkc_sock *self, void *buf, int buflen, kkc_sock_flags_t flags, int(*kkc_sock_method)(struct kkc_sock *, void *, int, kkc_sock_flags_t))
<<private>> Transfers a required number of bytes.
int kkc_sock_init (struct kkc_sock *self, struct kkc_arch *arch, struct kkc_sock_ops *sock_ops)
<<public>> Initializes generic socket.
int kkc_sock_connect (struct kkc_sock *self, char *addr)
<<public>> Connects to the given address
int kkc_sock_listen (struct kkc_sock *self, char *addr)
<<public>> Starts listening on a specified address
int kkc_sock_accept (struct kkc_sock *self, struct kkc_sock **new_kkc_sock, kkc_sock_flags_t flags)
<<public>> Creates a new socket by accepting the incoming socket.
int kkc_sock_send (struct kkc_sock *self, void *buf, int buflen, kkc_sock_flags_t flags)
<<public>> Sends out specified data.
int kkc_sock_recv (struct kkc_sock *self, void *buf, int buflen, kkc_sock_flags_t flags)
<<public>> Receives requested number of bytes of data.
int kkc_sock_shutdown (struct kkc_sock *self)
<<public>> Disconnects the socket.
int kkc_sock_add_wait_queue (struct kkc_sock *self, wait_queue_t *wait)
<<public>> Adds a task to the queue of processes sleeping on the socket.
int kkc_sock_remove_wait_queue (struct kkc_sock *self, wait_queue_t *wait)
<<public>> Removes a task from the queue of processes sleeping on the socket.
int kkc_sock_register_read_callback (struct kkc_sock *, kkc_data_ready callback, void *callback_data)
<<public>> Registers data_ready callback function, that should be called when there are some data read to be read on the socket
static int kkc_sock_is_address_equal_to (struct kkc_sock *self, const char *addr, int addr_length, int local)
<<public>> Checks, whether an address passed as string is equal to this socket local/peer port.
static int kkc_sock_getsockname (struct kkc_sock *self, char *sockname, int size)
<<public>> Local socket name accessor.
static int kkc_sock_getpeername (struct kkc_sock *self, char *sockname, int size)
<<public>> Peer socket name accessor.
static void kkc_sock_getarchname (struct kkc_sock *self, char *archname, int size)
<<public>> Architecture name accessor.
static const char * kkc_sock_getsockname2 (struct kkc_sock *self)
<<public>> Socket name accessor.
static const char * kkc_sock_getpeername2 (struct kkc_sock *self)
<<public>> Socket name accessor.
static struct kkc_sock * kkc_sock_get (struct kkc_sock *self)
<<public>> Instance accessor, increments the reference count.
static void kkc_sock_put (struct kkc_sock *self)
<<public>> Decrements reference counter, if it reaches 0 the custom free method is called if defined.
static int kkc_sock_snd_lock_interruptible (struct kkc_sock *self)
<<public>> Locks this socket instance for sending, interruptible version, the process can be woken up by a signal.
static void kkc_sock_snd_lock (struct kkc_sock *self)
<<public>> Locks this socket instance for sending.
static void kkc_sock_snd_unlock (struct kkc_sock *self)
<<public>> Unlocks this socket instance for sending.
static int kkc_sock_rcv_lock_interruptible (struct kkc_sock *self)
<<public>> Locks this socket instance for receiving, interruptible version, the process can be woken up by a signal.
static void kkc_sock_rcv_lock (struct kkc_sock *self)
<<public>> Locks this socket instance for receiving.
static void kkc_sock_rcv_unlock (struct kkc_sock *self)
<<public>> Unlocks this socket instance for receiving.
Detailed Description
This is a generic KKC socket.
It handles basic administration of the generic socket, initialization of common socket parameters, and releasing the socket instance. It is questionable if a regular BSD socket should be included into the compound structure or not. Currently, there is no other communication abstraction in Linux other than sockets. For now, the BSD socket handling functionality will be in child classes (e.g. kkc_sock_tcp). For the common part for all network architectures, we will keep only the address in string form in the kkc_socket super class.
KKC socket is meant for full duplex communication. In addition, it provides locking mechanism that allows separate serialization of send and receive requests.
Data Structure Documentation
struct kkc_sock
A coumpound structure that contains generic information about a KKC socket.
Definition at line 73 of file kkc_sock.h.
Data Fields
struct kkc_arch * arch architecture for this socket - the reason why we keep the reference is the release the reference to the architecture, if the socket has been created based on user string.
char peername[100] remote address ('name') of the socket object - temporary storage.
struct list_head pub_list general purpose list entry for storing sockets
atomic_t ref_count reference counter
struct kkc_sock_ops * sock_ops message operations
struct semaphore sock_recv_sem mutex semaphore to serialize receiving from the socket.
struct semaphore sock_send_sem mutex semaphore to serialize sending via the socket.
char sockname[100] local address ('name') of the socket object - temporary storage.
struct kkc_sock_ops
Socket operations that support polymorphism.
Definition at line 106 of file kkc_sock.h.
Data Fields
int(* connect)(struct kkc_sock *, char *)
Connects to the given address.
int(* listen)(struct kkc_sock *, char *)
Connects to the given address.
int(* accept)(struct kkc_sock *, struct kkc_sock **, kkc_sock_flags_t)
Accepts an incoming socket.
int(* send)(struct kkc_sock *, void *, int, kkc_sock_flags_t)
Sends out specified data.
int(* recv)(struct kkc_sock *, void *, int, kkc_sock_flags_t)
Receives requested number of bytes of data.
int(* add_wait_queue)(struct kkc_sock *, wait_queue_t *)
Adds a task to the queue of processes waiting on incoming data.
int(* remove_wait_queue)(struct kkc_sock *, wait_queue_t *)
Removes a task from the queue of processes waiting on incoming data.
int(* register_read_callback)(struct kkc_sock *, kkc_data_ready callback, void *callback_data)
Registers read callback.
int(* shutdown)(struct kkc_sock *)
Disconnects the socket.
void(* free)(struct kkc_sock *)
Frees socket architecture specific resources.
int(* getname)(struct kkc_sock *, char *, int, int)
Socket name/peer name accessor.
int(* is_address_equal_to)(struct kkc_sock *, const char *, int, int)
Compare addresses.
Field Documentation
int(* kkc_sock_ops::accept)(struct kkc_sock *, struct kkc_sock **, kkc_sock_flags_t)
Accepts an incoming socket.
Definition at line 112 of file kkc_sock.h.
int(* kkc_sock_ops::add_wait_queue)(struct kkc_sock *, wait_queue_t *)
Adds a task to the queue of processes waiting on incoming data.
Definition at line 118 of file kkc_sock.h.
int(* kkc_sock_ops::connect)(struct kkc_sock *, char *)
Connects to the given address.
Definition at line 108 of file kkc_sock.h.
void(* kkc_sock_ops::free)(struct kkc_sock *)
Frees socket architecture specific resources.
Definition at line 126 of file kkc_sock.h.
int(* kkc_sock_ops::getname)(struct kkc_sock *, char *, int, int)
Socket name/peer name accessor.
Definition at line 128 of file kkc_sock.h.
int(* kkc_sock_ops::is_address_equal_to)(struct kkc_sock *, const char *, int, int)
Compare addresses.
Definition at line 130 of file kkc_sock.h.
int(* kkc_sock_ops::listen)(struct kkc_sock *, char *)
Connects to the given address.
Definition at line 110 of file kkc_sock.h.
int(* kkc_sock_ops::recv)(struct kkc_sock *, void *, int, kkc_sock_flags_t)
Receives requested number of bytes of data.
Definition at line 116 of file kkc_sock.h.
int(* kkc_sock_ops::register_read_callback)(struct kkc_sock *, kkc_data_ready callback, void *callback_data)
Registers read callback.
Definition at line 122 of file kkc_sock.h.
int(* kkc_sock_ops::remove_wait_queue)(struct kkc_sock *, wait_queue_t *)
Removes a task from the queue of processes waiting on incoming data.
Definition at line 120 of file kkc_sock.h.
int(* kkc_sock_ops::send)(struct kkc_sock *, void *, int, kkc_sock_flags_t)
Sends out specified data.
Definition at line 114 of file kkc_sock.h.
int(* kkc_sock_ops::shutdown)(struct kkc_sock *)
Disconnects the socket.
Definition at line 124 of file kkc_sock.h.
Macro Definition Documentation
#define KKC_SOCK (s) ((struct kkc_sock*)s)
Casts to the kkc_sock instance.
Definition at line 353 of file kkc_sock.h.
Referenced by kkc_establish(), kkc_sock_tcp_accept(), and kkc_sock_tcp_new().
#define KKC_SOCK_MAX_ADDR_LENGTH 100
Maximum address length.
Definition at line 60 of file kkc_sock.h.
Referenced by kkc_establish(), kkc_get_architecture(), kkc_sock_getpeername2(), kkc_sock_getsockname2(), kkc_sock_tcp_is_address_equal_to(), mount_proxyfs(), tcmi_migman_create_symlink(), tcmi_sock_getpeername(), tcmi_sock_getsockname(), and tcmi_sock_new().
Typedef Documentation
typedef void(* kkc_data_ready)(void *data, int bytes)
Callback function prototype, that can be registered to be notified about in case there are some data ready to be read on a socket.
Definition at line 103 of file kkc_sock.h.
Enumeration Type Documentation
enum kkc_sock_flags_t
Flags for receive and accept operations.
Enumerator
KKC_SOCK_BLOCK
KKC_SOCK_NONBLOCK
Definition at line 64 of file kkc_sock.h.
              {
     /* blocking mode operation */
     KKC_SOCK_BLOCK,
     /* non-blocking mode operation */
     KKC_SOCK_NONBLOCK
 } kkc_sock_flags_t;
Function Documentation
int kkc_sock_accept (struct kkc_sock * self, struct kkc_sock ** new_kkc_sock, kkc_sock_flags_t flags)
<<public>> Creates a new socket by accepting the incoming socket.
<<public>> Creates a new socket by accepting the incoming socket.
Delegates work to the architecture specific class.
Parameters
*self - pointer to this socket instance
**new_kkc_sock - storage for the new socket created for the incoming connection.
flags - specify blocking/nonblocking mode
Returns
0 upon successful connection
Definition at line 113 of file kkc_sock.c.
References mdbg, and self.
Referenced by proxyfs_server_accept(), and tcmi_ccnman_process_sock().
 {
     int error = 0;
     mdbg(INFO4, "Accepting connection..");
     if (self->sock_ops && self->sock_ops->accept)
         error = self->sock_ops->accept(self, new_kkc_sock, flags);
     return error;
 }
int kkc_sock_add_wait_queue (struct kkc_sock * self, wait_queue_t * wait)
<<public>> Adds a task to the queue of processes sleeping on the socket.
Delegates work to the specific socket class.
Parameters
*self - pointer to this socket instance
*wait - pointer to the waitqueue element with the task that wants to sleep on this socket.
Returns
0 upon success
Definition at line 207 of file kkc_sock.c.
References self.
Referenced by kkc_sock_sleeper_add(), proxyfs_peer_wait(), and proxyfs_server_listen().
 {
     int error = 0;
     if (self->sock_ops && self->sock_ops->add_wait_queue)
         error = self->sock_ops->add_wait_queue(self, wait);
     return error;
 }
int kkc_sock_connect (struct kkc_sock * self, char * addr)
<<public>> Connects to the given address
<<public>> Connects to the given address
Delegates all work to the architecture specific socket operation.
Parameters
*self - pointer to this socket instance
*addr - address where to connect to.
Returns
0 upon successful connection
Definition at line 74 of file kkc_sock.c.
References mdbg, and self.
Referenced by kkc_connect().
 {
     int error = 0;
     mdbg(INFO4, "Connecting to '%s' ..", addr);
     if (self->sock_ops && self->sock_ops->connect)
         error = self->sock_ops->connect(self, addr);
     return error;
 }
static struct kkc_sock* kkc_sock_get (struct kkc_sock * self) static read
<<public>> Instance accessor, increments the reference count.
Parameters
*self - pointer to this message instance
Definition at line 253 of file kkc_sock.h.
References self.
Referenced by tcmi_comm_new(), tcmi_sock_new(), and tcmi_task_init().
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static void kkc_sock_getarchname (struct kkc_sock * self, char * archname, int size) inline static
<<public>> Architecture name accessor.
Asks the architecture to fill in its name.
Parameters
*self - pointer to this socket instance
*archname - pointer to the buffer where the architecture name is to be stored
size - maximum string length that fits into the sockname buffer
Definition at line 212 of file kkc_sock.h.
References kkc_arch_name(), and self.
Referenced by mount_proxyfs(), and tcmi_sock_getarchname().
 {
     strncpy(archname, kkc_arch_name(self->arch), size);
 }
static int kkc_sock_getpeername (struct kkc_sock * self, char * sockname, int size) inline static
<<public>> Peer socket name accessor.
Asks the architecture specific socket to fill in its remote name (destination address). The generic socket operation getname() is used, passing 1 selects the peer name.
Parameters
*self - pointer to this socket instance
*sockname - pointer to the buffer where the sockname is to be stored
size - maximum string length that fits into the sockname buffer
Returns
0 upon success
Definition at line 196 of file kkc_sock.h.
References self.
Referenced by kkc_sock_getpeername2(), mount_proxyfs(), tcmi_migman_create_symlink(), and tcmi_sock_getpeername().
 {
     int err = 0;
     if (self->sock_ops && self->sock_ops->getname)
         err = self->sock_ops->getname(self, sockname, size, 1);
     return err;
 }
static const char* kkc_sock_getpeername2 (struct kkc_sock * self) inline static
<<public>> Socket name accessor.
Unlike the previous version, returns pointer to the socket local name. The socket local name is stored inside the instance. Having this method makes it easier to use it inside print statements.
Parameters
*self - pointer to this socket instance
Returns
to the local socket name
Definition at line 241 of file kkc_sock.h.
References kkc_sock_getpeername(), KKC_SOCK_MAX_ADDR_LENGTH, and self.
Referenced by kkc_sock_put(), kkc_sock_sleeper_add(), kkc_sock_sleeper_remove(), proxyfs_msg_real_send(), proxyfs_peer_put(), proxyfs_peer_real_recv(), proxyfs_peer_real_send(), proxyfs_task_handle_dead_peers(), tcmi_ccnman_process_sock(), tcmi_ccnman_thread(), tcmi_ccnmigman_process_msg(), tcmi_comm_thread(), and tcmi_penman_connect().
 {
     memset(self->peername, 0, KKC_SOCK_MAX_ADDR_LENGTH);
     kkc_sock_getpeername(self, self->peername, KKC_SOCK_MAX_ADDR_LENGTH);
     return self->peername;
 }
static int kkc_sock_getsockname (struct kkc_sock * self, char * sockname, int size) inline static
<<public>> Local socket name accessor.
Asks the architecture specific socket to fill in its local name (address). The generic socket operation getname() is used, passing 0 selects the local name.
Parameters
*self - pointer to this socket instance
*sockname - pointer to the buffer where the sockname is to be stored
size - maximum string length that fits into the sockname buffer
Returns
0 upon success
Definition at line 178 of file kkc_sock.h.
References self.
Referenced by kkc_sock_getsockname2(), and tcmi_sock_getsockname().
 {
     int err = 0;
     if (self->sock_ops && self->sock_ops->getname)
         err = self->sock_ops->getname(self, sockname, size, 0);
     return err;
 }
static const char* kkc_sock_getsockname2 (struct kkc_sock * self) inline static
<<public>> Socket name accessor.
Unlike the previous version, returns pointer to the socket local name. The socket local name is stored inside the instance. Having this method makes it easier to use it inside print statements.
Parameters
*self - pointer to this socket instance
Returns
to the local socket name
Definition at line 226 of file kkc_sock.h.
References kkc_sock_getsockname(), KKC_SOCK_MAX_ADDR_LENGTH, and self.
Referenced by kkc_sock_put(), kkc_sock_sleeper_add(), kkc_sock_sleeper_remove(), tcmi_ccnman_process_sock(), tcmi_ccnman_thread(), tcmi_comm_thread(), tcmi_penman_connect(), and tcmi_sock_new().
 {
     memset(self->sockname, 0, KKC_SOCK_MAX_ADDR_LENGTH);
     kkc_sock_getsockname(self, self->sockname, KKC_SOCK_MAX_ADDR_LENGTH);
     return self->sockname;
 }
int kkc_sock_init (struct kkc_sock * self, struct kkc_arch * arch, struct kkc_sock_ops * sock_ops)
<<public>> Initializes generic socket.
This method should be called back from the architecture specific constructor to initialize common socket fields. Architecture is set.
Parameters
*self - pointer to this socket instance
*sock_ops - operations vector of the architecture specific socket
*arch - socket specific architecture. This allows the user to read architecture name.
Returns
0 upon successful connection
Definition at line 47 of file kkc_sock.c.
References mdbg, and self.
Referenced by kkc_sock_tcp_new().
 {
     if (!arch) {
         mdbg(ERR4, "No architecture specified, can't init socket");
         return -EINVAL;
     }
     self->arch = arch;
     self->sock_ops = sock_ops;
     atomic_set(&self->ref_count, 1);
     sema_init(&self->sock_send_sem, 1);     // Change macro init_MUTEX to contain of original macro sema_init(sem,1) for kernel 3.x.x by Jiri Rakosnik
     sema_init(&self->sock_recv_sem, 1);
     INIT_LIST_HEAD(&self->pub_list);
     mdbg(INFO4, "Initialized KKC socket: %p", self);
     return 0;
 }
static int kkc_sock_is_address_equal_to (struct kkc_sock * self, const char * addr, int addr_length, int local) inline static
<<public>> Checks, whether an address passed as string is equal to this socket local/peer port.
Can return true only if current socket is connected.
Definition at line 160 of file kkc_sock.h.
References self.
Referenced by check_duplicates().
{
     int err = 0;
     if (self->sock_ops && self->sock_ops->is_address_equal_to)
         err = self->sock_ops->is_address_equal_to(self, addr, addr_length, local);
     return err;
 }
int kkc_sock_listen (struct kkc_sock * self, char * addr)
<<public>> Starts listening on a specified address
<<public>> Starts listening on a specified address
Delegates all work to the architecture specific socket operation.
Parameters
*self - pointer to this socket instance
*addr - address where to connect to.
Returns
0 upon successfully establishing the listening
Definition at line 93 of file kkc_sock.c.
References mdbg, and self.
Referenced by kkc_listen().
 {
     int error = 0;
     mdbg(INFO4, "Listening on '%s' ..", addr);
     if (self->sock_ops && self->sock_ops->listen)
         error = self->sock_ops->listen(self, addr);
     return error;
 }
static void kkc_sock_put (struct kkc_sock * self) inline static
<<public>> Decrements reference counter, if it reaches 0 the custom free method is called if defined.
Also the architecture is released.
The user is responsible for taking the socket out of any lists where he had stored it.
Parameters
*self - pointer to this socket instance
Definition at line 271 of file kkc_sock.h.
References kkc_arch_put(), kkc_sock_getpeername2(), kkc_sock_getsockname2(), mdbg, and self.
Referenced by kkc_establish(), kkc_sock_tcp_accept(), proxyfs_peer_put(), proxyfs_server_free(), tcmi_ccnman_listen(), tcmi_ccnman_process_sock(), tcmi_comm_new(), tcmi_comm_put(), tcmi_penman_connect(), tcmi_sock_new(), tcmi_sock_put(), tcmi_task_init(), and tcmi_task_put().
 {
     if (!self)
         return;
     if (atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying KKC socket local: '%s', remote: '%s', %p",
              kkc_sock_getsockname2(self),
              kkc_sock_getpeername2(self), self);
         if (self->sock_ops && self->sock_ops->free)
             self->sock_ops->free(self);
         /* release the architecture */
         kkc_arch_put(self->arch);
         kfree(self);
     }
 }
static void kkc_sock_rcv_lock (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for receiving.
Parameters
*self - pointer to this socket instance
Definition at line 337 of file kkc_sock.h.
References self.
 {
         down(&self->sock_recv_sem);
 }
static int kkc_sock_rcv_lock_interruptible (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for receiving, interruptible version, the process can be woken up by a signal.
Parameters
*self - pointer to this file instance
Definition at line 327 of file kkc_sock.h.
References self.
Referenced by tcmi_msg_recv().
 {
     return (down_interruptible(&self->sock_recv_sem));
 }
static void kkc_sock_rcv_unlock (struct kkc_sock * self) inline static
<<public>> Unlocks this socket instance for receiving.
Parameters
*self - pointer to this socket instance
Definition at line 347 of file kkc_sock.h.
References self.
Referenced by tcmi_msg_recv().
 {
         up(&self->sock_recv_sem);
 }
int kkc_sock_recv (struct kkc_sock * self, void * buf, int buflen, kkc_sock_flags_t flags)
<<public>> Receives requested number of bytes of data.
The behavior of the function depends on the mode. In blocking mode, it will try to receive all buflen bytes via kkc_sock_send_recv(). In non-blocking mode it will perform only 1 attempt to receive data, using the receive operation of the socket instance directly.
Parameters
*self - pointer to this socket instance
*buf - buffer where to store received data.
buflen - length of the buffer to be sent
flags - specify blocking or non-blocking mode.
Returns
number of bytes actually received or error when < 0
Definition at line 162 of file kkc_sock.c.
References KKC_SOCK_BLOCK, kkc_sock_send_recv(), mdbg, and self.
Referenced by proxyfs_peer_real_recv(), tcmi_authenticate_msg_recv(), tcmi_authenticate_resp_msg_recv(), tcmi_comm_thread(), tcmi_err_msg_recv(), tcmi_err_procmsg_recv(), tcmi_exit_procmsg_recv(), tcmi_generic_user_msg_recv(), tcmi_generic_user_procmsg_recv(), tcmi_guest_started_procmsg_recv(), tcmi_msg_recv(), tcmi_p_emigrate_msg_recv(), tcmi_ppm_p_emigrate_msg_recv(), tcmi_ppm_p_migr_back_guestreq_procmsg_recv(), tcmi_procmsg_recv(), tcmi_rpc_procmsg_recv(), tcmi_rpcresp_procmsg_recv(), and tcmi_signal_msg_recv().
 {
     int result = 0;
     mdbg(INFO4, "Receiving into buffer %p length: %d bytes", buf, buflen);
     if (self->sock_ops && self->sock_ops->recv) {
         if (flags == KKC_SOCK_BLOCK)
             result = kkc_sock_send_recv(self, buf, buflen, flags,
                             self->sock_ops->recv);
         else
             result = self->sock_ops->recv(self, buf, buflen, flags);
     }
     return result;
 }
int kkc_sock_register_read_callback (struct kkc_sock * , kkc_data_ready callback, void * callback_data)
<<public>> Registers data_ready callback function, that should be called when there are some data read to be read on the socket
Definition at line 237 of file kkc_sock.c.
References self.
Referenced by proxyfs_client_thread(), proxyfs_server_accept(), and proxyfs_server_listen().
{
     int error = 0;
     if (self->sock_ops && self->sock_ops->register_read_callback)
         error = self->sock_ops->register_read_callback(self, callback, callback_data);
     return error;
 };
int kkc_sock_remove_wait_queue (struct kkc_sock * self, wait_queue_t * wait)
<<public>> Removes a task from the queue of processes sleeping on the socket.
Delegates work to the specific socket class.
Parameters
*self - pointer to this socket instance
*wait - pointer to the waitqueue element with the task that wants to sleep on this socket.
Returns
0 upon success
Definition at line 225 of file kkc_sock.c.
References self.
Referenced by kkc_sock_sleeper_remove().
 {
     int error = 0;
     if (self->sock_ops && self->sock_ops->remove_wait_queue)
         error = self->sock_ops->remove_wait_queue(self, wait);
     return error;
 }
int kkc_sock_send (struct kkc_sock * self, void * buf, int buflen, kkc_sock_flags_t flags)
<<public>> Sends out specified data.
Sends the entire content of the specified buffer. This might require multiple iterations - the method will try until all data is sent or an error occurs.
Parameters
*self - pointer to this socket instance
*buf - buffer with the data to be sent
buflen - length of the buffer to be sent
*buflen - number of bytes actually sent
flags - specify blocking or non-blocking mode.
Returns
number of bytes actually sent or error when < 0
Definition at line 135 of file kkc_sock.c.
References kkc_sock_send_recv(), mdbg, and self.
Referenced by proxyfs_msg_real_send(), tcmi_authenticate_msg_send(), tcmi_authenticate_resp_msg_send(), tcmi_err_msg_send(), tcmi_err_procmsg_send(), tcmi_exit_procmsg_send(), tcmi_generic_user_msg_send(), tcmi_generic_user_procmsg_send(), tcmi_guest_started_procmsg_send(), tcmi_msg_send(), tcmi_p_emigrate_msg_send(), tcmi_ppm_p_emigrate_msg_send(), tcmi_ppm_p_migr_back_guestreq_procmsg_send(), tcmi_procmsg_send(), tcmi_rpc_procmsg_send(), tcmi_rpcresp_procmsg_send(), and tcmi_signal_msg_send().
 {
     int result = 0;
     mdbg(INFO4, "Sending buffer %p length: %d bytes", buf, buflen);
     if (self->sock_ops && self->sock_ops->send) {
         result = kkc_sock_send_recv(self, buf, buflen, flags,
                         self->sock_ops->send);
     }
     return result;
 }
static int kkc_sock_send_recv (struct kkc_sock * self, void * buf, int buflen, kkc_sock_flags_t flags, int(*)(struct kkc_sock *, void *, int, kkc_sock_flags_t) kkc_sock_method) static
<<private>> Transfers a required number of bytes.
This method is intended for receiving and sending in blocking mode. The caller specifies only which method should be used. The method tries to transfer all the requested bytes until an error occurs.
Parameters
*self - pointer to this socket instance
*buf - buffer for transferred data (received or sent)
buflen - length of the buffer to be sent/received
flags - specify blocking or non-blocking mode.
*kkc_sock_method - send or receive method to be executed
Returns
number of bytes actually sent or received or error when < 0
Definition at line 264 of file kkc_sock.c.
References mdbg.
Referenced by kkc_sock_recv(), and kkc_sock_send().
 {
     int error = 0;
     int total = 0;
     while ((buflen > 0) && (error >= 0)) {
         error = kkc_sock_method(self, buf, buflen, flags);
         mdbg(INFO4, "Buffer starting at %p, xferred %d bytes", buf, error);
         buf += error;
         buflen -= error;
         total += error;
     }
     /* When error occured, return error code, otherwise the total */
     return  ((error >= 0) ? total : error);
 }
int kkc_sock_shutdown (struct kkc_sock * self)
<<public>> Disconnects the socket.
Delegates work to the specific socket class.
Parameters
*self - pointer to this socket instance
Returns
0 upon success
Definition at line 187 of file kkc_sock.c.
References self.
Referenced by proxyfs_peer_disconnect().
 {
     int error = 0;
     if (self->sock_ops && self->sock_ops->shutdown) {
         error = self->sock_ops->shutdown(self);
     }
     return error;
 }
static void kkc_sock_snd_lock (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for sending.
Parameters
*self - pointer to this socket instance
Definition at line 306 of file kkc_sock.h.
References self.
 {
         down(&self->sock_send_sem);
 }
static int kkc_sock_snd_lock_interruptible (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for sending, interruptible version, the process can be woken up by a signal.
Parameters
*self - pointer to this file instance
Definition at line 296 of file kkc_sock.h.
References self.
Referenced by tcmi_msg_send().
 {
     return (down_interruptible(&self->sock_send_sem));
 }
static void kkc_sock_snd_unlock (struct kkc_sock * self) inline static
<<public>> Unlocks this socket instance for sending.
Parameters
*self - pointer to this socket instance
Definition at line 316 of file kkc_sock.h.
References self.
Referenced by tcmi_msg_send().
 {
         up(&self->sock_send_sem);
 }