Clondike: C:/CLONDIKE/clondike/sources/kernel_3.6.11/src/tcmi/syscall/tcmi_syscallhooks_userident.c File Reference
tcmi_syscallhooks_userident.c File Reference
syscalls hooks for proces identification manipulation.
#include <asm/uaccess.h>
#include <linux/capability.h>
#include <clondike/tcmi/tcmi_hooks.h>
#include <dbg.h>
#include <tcmi/syscall/tcmi_guest_rpc.h>
#include "tcmi_syscallhooks_userident.h"
Macros
#define TCMI_SYSCALLHOOKS_USERIDENT_PRIVATE
Functions
int tcmi_syscall_hooks_userident_init (void)
<<public>> Registers all user identification syscalls hooks with the kernel.
void tcmi_syscall_hooks_userident_exit (void)
<<public>> Unregisters all user identifikation syscalls hooks.
static long tcmi_syscall_hooks_sys_getuid (void)
<<private>> Getuid system call hook
static long tcmi_syscall_hooks_sys_setresuid (uid_t ruid, uid_t euid, uid_t suid)
<<private>> Setresuid system call hook
static long tcmi_syscall_hooks_sys_geteuid (void)
<<private>> Geteuid system call hook
static long tcmi_syscall_hooks_sys_setuid (uid_t uid)
<<private>> Setuid system call hook
static long tcmi_syscall_hooks_sys_setreuid (uid_t ruid, uid_t euid)
<<private>> Setreuid system call hook
static long tcmi_syscall_hooks_sys_getresuid (uid_t *ruid, uid_t *euid, uid_t *suid)
<<private>> Getresuid system call hook (all pointers points to userspace)
Detailed Description
syscalls hooks for proces identification manipulation.
Date: 13/06/2007
Author: Petr Malat
Id:
tcmi_syscallhooks_userident.c,v 1.3 2007/09/02 15:40:39 malatp1 Exp
This file is part of Task Checkpointing and Migration Infrastructure(TCMI) Copyleft (C) 2007 Petr Malat
TCMI is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
TCMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file tcmi_syscallhooks_userident.c.
Macro Definition Documentation
#define TCMI_SYSCALLHOOKS_USERIDENT_PRIVATE
Definition at line 39 of file tcmi_syscallhooks_userident.c.
Function Documentation
static long tcmi_syscall_hooks_sys_geteuid (void) static
<<private>> Geteuid system call hook
Returns
efective uid of current process
Definition at line 103 of file tcmi_syscallhooks_userident.c.
References tcmi_guest_rpc, tcmi_rpc_call0(), and TCMI_RPC_SYS_GETEUID.
Referenced by tcmi_syscall_hooks_userident_init().
 {
     return tcmi_rpc_call0(tcmi_guest_rpc, TCMI_RPC_SYS_GETEUID);
 }
static long tcmi_syscall_hooks_sys_getresuid (uid_t * ruid, uid_t * euid, uid_t * suid) static
<<private>> Getresuid system call hook (all pointers points to userspace)
Parameters
*ruid - pointer to uid_t for real user id
*euid - pointer to uid_t for efective user id
*suid - pointer to uid_t for saved set-user id
Returns
zero on success
Definition at line 136 of file tcmi_syscallhooks_userident.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_GETRESUID.
Referenced by tcmi_syscall_hooks_userident_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_GETRESUID, (unsigned long)ruid, (unsigned long)euid, (unsigned long)suid);
 }
static long tcmi_syscall_hooks_sys_getuid (void) static
<<private>> Getuid system call hook
Returns
- uid of current process
Definition at line 80 of file tcmi_syscallhooks_userident.c.
References tcmi_guest_rpc, tcmi_rpc_call0(), and TCMI_RPC_SYS_GETUID.
Referenced by tcmi_syscall_hooks_userident_init().
 {
     return tcmi_rpc_call0(tcmi_guest_rpc, TCMI_RPC_SYS_GETUID);
 }
static long tcmi_syscall_hooks_sys_setresuid (uid_t ruid, uid_t euid, uid_t suid) static
<<private>> Setresuid system call hook
Parameters
ruid - real user id
euid - efective user id
suid - saved set-user id
Returns
zero on success
Definition at line 93 of file tcmi_syscallhooks_userident.c.
References tcmi_guest_rpc, tcmi_rpc_call3(), and TCMI_RPC_SYS_SETRESUID.
Referenced by tcmi_syscall_hooks_userident_init().
 {
     return tcmi_rpc_call3(tcmi_guest_rpc, TCMI_RPC_SYS_SETRESUID, ruid, euid, suid);
 }
static long tcmi_syscall_hooks_sys_setreuid (uid_t ruid, uid_t euid) static
<<private>> Setreuid system call hook
Parameters
ruid - real user id
euid - efective user id
Returns
zero on success
Definition at line 124 of file tcmi_syscallhooks_userident.c.
References tcmi_guest_rpc, tcmi_rpc_call2(), and TCMI_RPC_SYS_SETREUID.
Referenced by tcmi_syscall_hooks_userident_init().
 {
     return tcmi_rpc_call2(tcmi_guest_rpc, TCMI_RPC_SYS_SETREUID, ruid, euid);
 }
static long tcmi_syscall_hooks_sys_setuid (uid_t uid) static
<<private>> Setuid system call hook
Parameters
uid - efective user id
Returns
zero on success
Definition at line 113 of file tcmi_syscallhooks_userident.c.
References tcmi_guest_rpc, tcmi_rpc_call1(), and TCMI_RPC_SYS_SETUID.
Referenced by tcmi_syscall_hooks_userident_init().
 {
     return tcmi_rpc_call1(tcmi_guest_rpc, TCMI_RPC_SYS_SETUID, uid);
 }