Clondike: Group identification
Group identification
tcmi_shadow_rpc class
A part of tcmi_shadow_rpc with RPCs for group identification.
Functions
long tcmi_shadow_rpc_getegid (unsigned rpc_num, long params[6])
Getegid() system call.
long tcmi_shadow_rpc_getgid (unsigned rpc_num, long params[6])
Getgid() system call.
long tcmi_shadow_rpc_getgroups (unsigned rpc_num, long params[6])
Getgroups() system call.
long tcmi_shadow_rpc_getresgid (unsigned rpc_num, long params[6])
Getresgid() system call.
long tcmi_shadow_rpc_setgid (unsigned rpc_num, long params[6])
Setgid() system call.
long tcmi_shadow_rpc_setgroups (unsigned rpc_num, long params[6])
Setgroups() system call.
long tcmi_shadow_rpc_setregid (unsigned rpc_num, long params[6])
Setregid() system call.
long tcmi_shadow_rpc_setresgid (unsigned rpc_num, long params[6])
Setresgid() system call.
Detailed Description
A part of tcmi_shadow_rpc with RPCs for group identification.
Function Documentation
long tcmi_shadow_rpc_getegid (unsigned rpc_num, long params[6])
Getegid() system call.
Definition at line 44 of file tcmi_shadow_groupident_rpc.c.
 {
long tcmi_shadow_rpc_getgid (unsigned rpc_num, long params[6])
Getgid() system call.
Definition at line 45 of file tcmi_shadow_groupident_rpc.c.
 {
long tcmi_shadow_rpc_getgroups (unsigned rpc_num, long params[6])
Getgroups() system call.
Definition at line 108 of file tcmi_shadow_groupident_rpc.c.
References count(), mdbg, resp, TCMI_RPC_PROCMSG, tcmi_rpc_procmsg_data_base(), TCMI_RPCRESP_PROCMSG, tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_free_on_put(), and TCMI_RPCRESP_PROCMSG_KFREE.
 {
     struct tcmi_msg **resp, *m;
     long* rpc_params;
     long rtn, numb_of_groups;
     unsigned int i, count;
     gid_t *ker_buf;
     m = (struct tcmi_msg*) params[0];
     resp = (struct tcmi_msg**) params[1];
     rpc_params = (long*)tcmi_rpc_procmsg_data_base( TCMI_RPC_PROCMSG(m), 0);
     numb_of_groups = current_cred()->group_info->ngroups;
     if( rpc_params[0] == 0 )
         *resp = tcmi_rpcresp_procmsg_create(m, numb_of_groups, 0 );
     else if( rpc_params[0] < numb_of_groups )
         *resp = tcmi_rpcresp_procmsg_create(m, -EINVAL, 0 );
     else{
         if( (ker_buf = (gid_t*)kmalloc( numb_of_groups * sizeof(gid_t), GFP_KERNEL ) ) == NULL ){
             mdbg(ERR3, "Buffer allocation failed");
             return -1;
         }
         rtn = count = numb_of_groups;
         for (i = 0; i < count; i++) {
             int cp_count = min(NGROUPS_PER_BLOCK, count);
             int off = i * NGROUPS_PER_BLOCK;
             int len = cp_count * sizeof(*ker_buf);
             memcpy(ker_buf+off, current_cred()->group_info->blocks[i], len);
             count -= cp_count;
         }
         *resp = tcmi_rpcresp_procmsg_create(m, rtn, sizeof(gid_t)*numb_of_groups, ker_buf, 0 );
         tcmi_rpcresp_procmsg_free_on_put( TCMI_RPCRESP_PROCMSG(*resp), 0, TCMI_RPCRESP_PROCMSG_KFREE );
     }
     if( *resp == NULL )
         return -1;
     return 0;
 }
long tcmi_shadow_rpc_getresgid (unsigned rpc_num, long params[6])
Getresgid() system call.
Definition at line 50 of file tcmi_shadow_groupident_rpc.c.
References errno, mdbg, resp, TCMI_RPCRESP_PROCMSG, tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_free_on_put(), and TCMI_RPCRESP_PROCMSG_KFREE.
 {
     struct tcmi_msg **resp, *m;
     long rtn;
     uid_t *gids;
     mm_segment_t old_fs;
     m = (struct tcmi_msg*) params[0];
     resp = (struct tcmi_msg**) params[1];
     if( (gids = kmalloc( 3 * sizeof(gid_t), GFP_KERNEL ) ) == NULL ){
             mdbg(ERR3, "Buffer allocation failed");
             return -1;
     }
     old_fs = get_fs();
     set_fs(KERNEL_DS);
     rtn = getresgid( gids, gids + 1, gids + 2 );
     set_fs(old_fs);
     if( rtn == -1) // Should be never true
         rtn = errno;
     else{
         if( (*resp = tcmi_rpcresp_procmsg_create(m, rtn, 3 * sizeof(gid_t), gids, (size_t)0 )) == NULL ){
             kfree( gids );
             return -1;
         }
         tcmi_rpcresp_procmsg_free_on_put( TCMI_RPCRESP_PROCMSG(*resp), 0, TCMI_RPCRESP_PROCMSG_KFREE );
     }
     return 0;
 }
long tcmi_shadow_rpc_setgid (unsigned rpc_num, long params[6])
Setgid() system call.
Definition at line 46 of file tcmi_shadow_groupident_rpc.c.
 {
long tcmi_shadow_rpc_setgroups (unsigned rpc_num, long params[6])
Setgroups() system call.
Definition at line 83 of file tcmi_shadow_groupident_rpc.c.
References errno, resp, TCMI_RPC_PROCMSG, tcmi_rpc_procmsg_data_base(), and tcmi_rpcresp_procmsg_create().
 {
     struct tcmi_msg **resp, *m;
     long* rpc_params, rtn;
     void *ker_buf;
     mm_segment_t old_fs;
     m = (struct tcmi_msg*) params[0];
     resp = (struct tcmi_msg**) params[1];
     rpc_params = (long*)tcmi_rpc_procmsg_data_base( TCMI_RPC_PROCMSG(m), 0);
     ker_buf = (long*)tcmi_rpc_procmsg_data_base( TCMI_RPC_PROCMSG(m), 1);
     old_fs = get_fs();
     set_fs(KERNEL_DS);
     rtn = setgroups( rpc_params[0], ker_buf );
     set_fs(old_fs);
     if( rtn == -1)
         rtn = errno;
     *resp = tcmi_rpcresp_procmsg_create(m, rtn, 0 );
     if( *resp == NULL )
         return -1;
     return 0;
 }
long tcmi_shadow_rpc_setregid (unsigned rpc_num, long params[6])
Setregid() system call.
Definition at line 47 of file tcmi_shadow_groupident_rpc.c.
 {
long tcmi_shadow_rpc_setresgid (unsigned rpc_num, long params[6])
Setresgid() system call.
Definition at line 48 of file tcmi_shadow_groupident_rpc.c.
 {