Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/manager/tcmi_penman.c File Reference
tcmi_penman.c File Reference
#include <linux/kthread.h>
#include <tcmi/migration/tcmi_migcom.h>
#include <tcmi/ctlfs/tcmi_ctlfs.h>
#include "tcmi_penmigman.h"
#include <tcmi/task/tcmi_task.h>
#include <tcmi/task/tcmi_taskhelper.h>
#include <tcmi/migration/tcmi_npm_params.h>
#include <kkc/kkc.h>
#include "tcmi_penman.h"
#include <dbg.h>
Macros
#define TCMI_PENMAN_PRIVATE
Functions
int tcmi_penman_init (struct tcmi_ctlfs_entry *root)
<<public>> Singleton instance initializer.
void tcmi_penman_shutdown (void)
<<public>> The manager is shutdown exactly in this order:
static int tcmi_penman_init_ctlfs_files (void)
<<private>> Creates the static files described here .
static void tcmi_penman_stop_ctlfs_files (void)
<<private>> Unregisters all control files.
static int check_duplicates (const char *address, int address_len)
static int tcmi_penman_connect (void *obj, void *str)
<<private>> Creates a new connection and instantiates a new migration manager that will be responsible for handling it.
static void tcmi_penman_stop (void)
<<private>> Stops the PEN manager.
int tcmi_penman_migrateback_npm (struct tcmi_man *self, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
Performs non-preemtive migration back from PEN.
Variables
static struct tcmi_penman self
Singleton instance pre-initialization.
static struct tcmi_man_ops penman_ops
Migration manager operations that support polymorphism.
Macro Definition Documentation
#define TCMI_PENMAN_PRIVATE
Definition at line 45 of file tcmi_penman.c.
Function Documentation
static int check_duplicates (const char * address, int address_len) static
Returns
1, if there is a duplicate address for some of the peers
Definition at line 134 of file tcmi_penman.c.
References kkc_sock_is_address_equal_to(), TCMI_MAN, tcmi_migman_sock(), tcmi_slot_entry, tcmi_slot_for_each, tcmi_slotvec_for_each_used_slot, tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_penman_connect().
{
     int ret = 0;
     struct tcmi_slot *slot;
     tcmi_slot_node_t* node;
     struct tcmi_migman *migman = NULL;
     tcmi_slotvec_lock(TCMI_MAN(&self)->mig_mans);
     tcmi_slotvec_for_each_used_slot(slot, TCMI_MAN(&self)->mig_mans) {
         tcmi_slot_for_each(node, slot) {
             migman = tcmi_slot_entry(node, struct tcmi_migman, node);
             if ( kkc_sock_is_address_equal_to(tcmi_migman_sock(migman),address,address_len, 1) ) {
             ret = 1;
             goto found;
             }
         };
     };
 found:
     tcmi_slotvec_unlock(TCMI_MAN(&self)->mig_mans);
     return ret;
 }
static int tcmi_penman_connect (void * obj, void * str) static
<<private>> Creates a new connection and instantiates a new migration manager that will be responsible for handling it.
Parameters
*obj - pointer to an object - NULL is expected as TCMI PEN manager is a singleton class.
*str - connection string - It is architecture dependent and passed further on tcmi_listen class. "@" char is used to separate address of the remote node and optional authentication data
Returns
0 upon success
Definition at line 167 of file tcmi_penman.c.
References check_duplicates(), kkc_connect(), kkc_sock_getpeername2(), kkc_sock_getsockname2(), kkc_sock_put(), mdbg, minfo, TCMI_MAN, tcmi_man_id(), tcmi_man_migproc_dir(), tcmi_man_nodes_dir(), tcmi_man_release_migmanslot(), tcmi_man_reserve_migmanslot(), tcmi_migman_node(), tcmi_migman_put(), TCMI_PENMIGMAN, tcmi_penmigman_auth_ccn(), tcmi_penmigman_new(), tcmi_slot_index(), and tcmi_slot_insert().
Referenced by tcmi_penman_init_ctlfs_files().
 {
     int err, separation_index, auth_data_size = 0;
     char *connect_str = (char *) str;
     char *auth_data = NULL;
     char *separation_char = NULL;
     struct tcmi_migman *migman;
     struct tcmi_slot *slot;
     struct kkc_sock *sock;
     mdbg(INFO3, "Connection request with param: %s", connect_str);
     // @ serves as a special separator of "node address" from "authentication data
     if ( (separation_char=strchr(connect_str, '@')) != NULL ) {
         separation_index = separation_char - connect_str;
         // TODO: Here we use strlen on auth data length calculation, which means we loose a capability of passing pure binary data.. improve it if possible
         auth_data_size = strlen(connect_str) - separation_index - 1;
         // We separate the string by zero so that it is internally threated as a short string for kkc soct
         connect_str[separation_index] = '\0';
         auth_data = connect_str + separation_index + 1;
     }
     if ( check_duplicates(connect_str, strlen(connect_str)) ) {
         mdbg(ERR3, "Duplicate peer, already connected:'%s' ", connect_str);
         goto exit0;
     }
     /* check if there is incoming connection */
     if (kkc_connect(&sock, connect_str)) {
         mdbg(ERR3, "Failed connecting to '%s' ", connect_str);
         goto exit0;
     }
     mdbg(INFO3, "Connected to local: '%s', remote: '%s', auth_data_size: %d",
          kkc_sock_getsockname2(sock), kkc_sock_getpeername2(sock), auth_data_size);
     /* Reserve an empty slot */
     if (!(slot = tcmi_man_reserve_migmanslot(TCMI_MAN(&self)))) {
         mdbg(ERR3, "Failed allocating an empty slot for PEN migman");
         goto exit1;
     }
     /* Accept the first incoming connection */
     if (!(migman = tcmi_penmigman_new(sock,
                       tcmi_man_id(TCMI_MAN(&self)),
                       slot,
                       tcmi_man_nodes_dir(TCMI_MAN(&self)),
                       tcmi_man_migproc_dir(TCMI_MAN(&self)),
                       "%d", tcmi_slot_index(slot)))) {
         minfo(ERR1, "Failed to instantiate the PEN migration manager");
         goto exit2;
     }
     if ((err = tcmi_penmigman_auth_ccn(TCMI_PENMIGMAN(migman), auth_data_size, auth_data)) < 0) {
         minfo(ERR1, "Failed to authenticate the CCN! %d", err);
         goto exit3;
     }
     tcmi_slot_insert(slot, tcmi_migman_node(migman));
     kkc_sock_put(sock);
     return 0;
 /* error handling */
  exit3:
     tcmi_migman_put(migman);
  exit2:
     tcmi_man_release_migmanslot(TCMI_MAN(&self), slot);
  exit1:
     kkc_sock_put(sock);
  exit0:
     return -EINVAL;
 }
int tcmi_penman_init (struct tcmi_ctlfs_entry * root)
<<public>> Singleton instance initializer.
The initialization is accomplished exactly in this order:
delegate rest of initialization to TCMI generic manager
Parameters
*root - root directory of the filesystem, where all entries are to be created
Returns
0 upon success
Definition at line 59 of file tcmi_penman.c.
References mdbg, minfo, penman_ops, TCMI_MAN, and tcmi_man_init().
 {
     minfo(INFO1, "Initializing TCMI PEN manager");
     if (tcmi_man_init(TCMI_MAN(&self), root, &penman_ops, "pen") < 0) {
         mdbg(ERR3, "TCMI PEN manager - generic init failed");
         goto exit0;
     }
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_penman_init_ctlfs_files (void) static
<<private>> Creates the static files described here .
Returns
0 upon success
Definition at line 103 of file tcmi_penman.c.
References KKC_MAX_WHERE_LENGTH, mdbg, tcmi_ctlfs_strfile_new(), TCMI_MAN, tcmi_man_root(), tcmi_penman_connect(), and TCMI_PERMS_FILE_W.
 {
     mdbg(INFO4, "Creating files");
     if (!(self.f_connect =
           tcmi_ctlfs_strfile_new(tcmi_man_root(TCMI_MAN(&self)), TCMI_PERMS_FILE_W,
                      NULL, NULL, tcmi_penman_connect,
                      KKC_MAX_WHERE_LENGTH, "connect")))
         goto exit0;
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
void tcmi_penman_shutdown (void)
<<public>> The manager is shutdown exactly in this order:
unregister all ctlfs files as we don't want anymore requests from users.
shutdown the migration framework. This includes migrating all processes back and terminating all migration managers
unregister all ctlfs directories
Definition at line 83 of file tcmi_penman.c.
References minfo, TCMI_MAN, and tcmi_man_shutdown().
 {
     minfo(INFO1, "Shutting down the TCMI PEN manager");
     tcmi_man_shutdown(TCMI_MAN(&self));
 }
static void tcmi_penman_stop (void) static
<<private>> Stops the PEN manager.
Definition at line 244 of file tcmi_penman.c.
 {
     /* Nothing to be done for now.. */
 }
static void tcmi_penman_stop_ctlfs_files (void) static
<<private>> Unregisters all control files.
Definition at line 123 of file tcmi_penman.c.
References mdbg, tcmi_ctlfs_entry_put(), and tcmi_ctlfs_file_unregister().
 {
     mdbg(INFO3, "Destroying  TCMI PEN manager ctlfs files");
     tcmi_ctlfs_file_unregister(self.f_connect);
     tcmi_ctlfs_entry_put(self.f_connect);
 }