Clondike: tcmi_slotvec class
tcmi_slotvec class
lib
This class represents a data structure widely used in implementation of TCMI.
Data Structures
struct tcmi_slotvec
A slot vector compound structure.
Macros
#define tcmi_slotvec_for_each_used_slot(slot, slotvec) list_for_each_entry(slot, &slotvec->used_slots, slot_list)
Iterates through all used slots in the slot vector.
#define tcmi_slotvec_for_each_used_slot_safe(slot, slot2, slotvec) list_for_each_entry_safe(slot, slot2, &slotvec->used_slots, slot_list)
<<public>> Iterates through all used slots in the slot vector - safe version.
#define tcmi_slotvec_entry(ptr, type, member) list_entry(ptr, type, member)
Extracts the actual slot from the list.
#define tcmi_slotvec_remove_one_entry(slotvec, obj, member)
<<public>> Removes one entry from the slotvector and returns it.
Functions
struct tcmi_slotvec * tcmi_slotvec_new (u_int size)
Allocates a new slot vector.
struct tcmi_slotvec * tcmi_slotvec_hnew (u_int order)
Allocates a new slot vector with 2^order buckets.
static struct tcmi_slotvec * tcmi_slotvec_get (struct tcmi_slotvec *self)
Slot vector instance accessor.
void tcmi_slotvec_put (struct tcmi_slotvec *self)
<<public>> Releases the instance.
struct tcmi_slot * tcmi_slotvec_at (struct tcmi_slotvec *self, u_int index)
<<public>> Accesses a slot at a given index.
struct tcmi_slot * tcmi_slotvec_reserve_empty (struct tcmi_slotvec *self)
<<public>> Finds the first empty slot.
struct tcmi_slot * tcmi_slotvec_insert_at (struct tcmi_slotvec *self, u_int index, struct hlist_node *node)
<<public>> Inserts an item in a slot at a given index.
struct tcmi_slot * tcmi_slotvec_insert_at_empty (struct tcmi_slotvec *self, struct hlist_node *node)
<<public>> Inserts an item into an empty slot at a given index.
static int tcmi_slotvec_empty (struct tcmi_slotvec *self)
<<public>> Tester method for slotvec emptyness
static void tcmi_slotvec_lock (struct tcmi_slotvec *self)
<<public>> Locks the instance data.
static void tcmi_slotvec_unlock (struct tcmi_slotvec *self)
<<public>> Unlocks the instance data.
static u_int tcmi_slotvec_hashmask (struct tcmi_slotvec *self)
<<public>> Hashmask accessor.
Detailed Description
This class represents a data structure widely used in implementation of TCMI.
It is a vector of slots where each slot is head of a doubly linked list of the respective objects.
   +-------+
  0| slot  | -> object1 -> object 2 -> object 3...
   +-------+
  1| slot  | empty
   +-------+
  2| slot  | -> object 5 -> object 6...
   +-------+
  3| slot  | empty
   +-------+
   .       .
   .       .
   .       .
   +-------+
   | slot  | -> objectX
   +-------+
  n| slot  | empty
   +-------+
The vector has limited size specified during initialization by the user. The benefit is that it provides O(1) access to all its slots based on index.
Allows iterating through non-empty slots
Allows allocating an empty slot with O(1) time complexity
The data structure internally keeps track of used and unused slots. The user can exclusively insert objects into empty slots only. This way, it can be used as a data structure describing some limited resource. On the other hand(as seen in the figure), the user is able to insert new elements into any slots, thus yielding a hashtable. The user needs to select only a suitable hashing function. The general requirement on the hash function is to yield the index 0 to n-1 with an approximately uniform distribution.
Since the datastructure is expected to be accessed from multiple threads of execution a reference counting is implemented. The user should always access the slot vector by means of tcmi_slotvec_get() method and release the instance by means of tcmi_slotvec_put(). The last accessing thread causes the slot vector to be freed from memory.
Data Structure Documentation
struct tcmi_slotvec
A slot vector compound structure.
Contains the used/unused slot lists and the actual vector.
Definition at line 145 of file tcmi_slotvec.h.
Data Fields
u_int hashmsk Hash mask - valid only when slot_count is $2^order$ and the slot vector has been created by tcmi_slotvec_hnew().
unsigned long lock_flags Technical field used for irq safe spinlocks.
atomic_t ref_count reference counter
spinlock_t s_lock current instance reference - used when freeing
Protects the slotvector from concurrent modification
u_int slot_count Number of slots in the vector.
struct tcmi_slot * slots The actual slot vector.
struct list_head unused_slots list of unused slots
struct list_head used_slots list of used slots
Macro Definition Documentation
#define tcmi_slotvec_entry (ptr, type, member) list_entry(ptr, type, member)
Extracts the actual slot from the list.
Definition at line 118 of file tcmi_slotvec.h.
#define tcmi_slotvec_for_each_used_slot (slot, slotvec) list_for_each_entry(slot, &slotvec->used_slots, slot_list)
Iterates through all used slots in the slot vector.
This is intended for traversals only, no removals should take place. We still need to ensure the slot vector protection against concurrent manipulation from other threads.
Parameters
slot - every iteration points to a new object
slotvec - slot vector we are iterating through
Definition at line 100 of file tcmi_slotvec.h.
Referenced by check_duplicates(), kill_all_tasks(), tcmi_ccnman_thread(), tcmi_man_get_non_shutdowning_migman(), and tcmi_penmigman_migrate_all_home().
#define tcmi_slotvec_for_each_used_slot_safe (slot, slot2, slotvec) list_for_each_entry_safe(slot, slot2, &slotvec->used_slots, slot_list)
<<public>> Iterates through all used slots in the slot vector - safe version.
This is a version safe against removals. If the current slot, will be removed during the iteration, no issues will arise. We still need to ensure the slot vector protection against concurrent manipulation from other threads.
Parameters
slot - every iteration points to a new object
slot2 - temporary storage for the current slot
slotvec - slot vector we are iterating through
Definition at line 114 of file tcmi_slotvec.h.
#define tcmi_slotvec_remove_one_entry (slotvec, obj, member)
Value:
do {                                \
    struct tcmi_slot *__slot;               \
    obj = NULL;                     \
    tcmi_slotvec_for_each_used_slot(__slot, slotvec) {  \
        tcmi_slot_remove_first(obj, __slot, member);    \
        break;                      \
    }                           \
} while(0)
<<public>> Removes one entry from the slotvector and returns it.
Takes first used slot and obtains first element from it. Removes the element from the slot.
Parameters
slotvec - slotvector where the removal is to be done
obj - a pointer where to store the object retrieved from
member - name of the object member used for linking into the slot.
Definition at line 131 of file tcmi_slotvec.h.
Referenced by tcmi_ccnman_stop_listen_all().
Function Documentation
struct tcmi_slot* tcmi_slotvec_at (struct tcmi_slotvec * self, u_int index) read
<<public>> Accesses a slot at a given index.
If the index is not valid (exceeds the vector length), NULL is returned.
Parameters
*self - pointer to this vector instance
index - index of a slot to be accessed.
Returns
pointer to a slot at a given index or NULL
Definition at line 148 of file tcmi_slotvec.c.
References tcmi_slot::index.
Referenced by tcmi_ccnman_stop_listen_one(), tcmi_man_emig_npm(), tcmi_man_emig_ppm_p(), tcmi_man_fork(), tcmi_man_send_generic_user_message(), tcmi_migman_remove_task(), tcmi_slotvec_insert_at(), and tcmi_transaction_lookup().
 {
     struct tcmi_slot *slot = NULL;
     if (index < self->slot_count)
         slot = &self->slots[index];
     return slot;
 }
static int tcmi_slotvec_empty (struct tcmi_slotvec * self) inline static
<<public>> Tester method for slotvec emptyness
Parameters
*self - pointer to this vector instance
Returns
1 if the slotvector is empty
Definition at line 215 of file tcmi_slotvec.h.
References self.
Referenced by tcmi_ccnman_stop_listen_all(), tcmi_man_wait_for_migmans_termination(), and tcmi_task_put().
 {
     return list_empty(&self->used_slots);
 }
static struct tcmi_slotvec* tcmi_slotvec_get (struct tcmi_slotvec * self) static read
Slot vector instance accessor.
Checks whether the instance is not currently being freed - if so, returns NULL. Otherwise increments the reference counter and returns self.
Parameters
*self - pointer to this vector instance
Returns
- self
Definition at line 185 of file tcmi_slotvec.h.
References self.
 {
     if (!self)
         return NULL;
     atomic_inc(&self->ref_count);
     return self;
 }
static u_int tcmi_slotvec_hashmask (struct tcmi_slotvec * self) inline static
<<public>> Hashmask accessor.
This method is to be used only if the slot vector has been created by tcmi_slotvec_hnew() and is intented to be used as a hashtable. Otherwise the hashmask is not valid and defaults to 0.
Returns
hashmask of the slot vector
Definition at line 250 of file tcmi_slotvec.h.
Referenced by tcmi_migman_add_task(), tcmi_migman_remove_task(), tcmi_transaction_lookup(), and tcmi_transaction_new().
 {
     return self->hashmsk;
 }
struct tcmi_slotvec* tcmi_slotvec_hnew (u_int order) read
Allocates a new slot vector with 2^order buckets.
Allocates a new slot vector with 2^order buckets.
It is intended when using the slot vector as a hashtable with $2^{order}$ buckets. A hashmask is calculated as the vector size - 1.
Parameters
order - $log_2(buckets)$
Returns
a new slot vector or NULL
Definition at line 95 of file tcmi_slotvec.c.
References tcmi_slotvec::hashmsk, mdbg, tcmi_slotvec::slot_count, and tcmi_slotvec_new().
Referenced by tcmi_migman_init(), and tcmi_task_init().
 {
     struct tcmi_slotvec *vec;
     if (!(vec = tcmi_slotvec_new(1 << order))) {
         mdbg(ERR3, "Error creating a slot vector hashtable with 2^%d buckets", order);
         goto exit0;
     }
     /* precompute the hashmask */
     vec->hashmsk = vec->slot_count - 1;
     return vec;
     /* error handling */
  exit0:
     return NULL;
 }
struct tcmi_slot* tcmi_slotvec_insert_at (struct tcmi_slotvec * self, u_int index, struct hlist_node * node) read
<<public>> Inserts an item in a slot at a given index.
<<public>> Inserts an item in a slot at a given index.
The work is then delegated to the slot.
Parameters
*self - pointer to this vector instance
index - index of a slot to be accessed.
*node - item to be inserted into an empty slot
Returns
pointer to a slot at a given index where the node has been inserted or NULL
Definition at line 199 of file tcmi_slotvec.c.
References tcmi_slot_insert(), and tcmi_slotvec_at().
Referenced by tcmi_migman_add_task(), and tcmi_transaction_new().
 {
     struct tcmi_slot *slot = tcmi_slotvec_at(self, index);
     if (slot)
         tcmi_slot_insert(slot, node);
     return slot;
 }
struct tcmi_slot* tcmi_slotvec_insert_at_empty (struct tcmi_slotvec * self, struct hlist_node * node) read
<<public>> Inserts an item into an empty slot at a given index.
<<public>> Inserts an item into an empty slot at a given index.
The slot is then asked to insert the new node.
Parameters
*self - pointer to this vector instance
*node - item to be inserted into an empty slot
Returns
a pointer to the slot where the insertion took place or NULL
Definition at line 217 of file tcmi_slotvec.c.
References tcmi_slot_insert(), and tcmi_slotvec_reserve_empty().
 {
     struct tcmi_slot *slot = tcmi_slotvec_reserve_empty(self);
     if (slot)
         tcmi_slot_insert(slot, node);
     return slot;
 }
static void tcmi_slotvec_lock (struct tcmi_slotvec * self) inline static
<<public>> Locks the instance data.
Spin lock used - no sleeping allowed!
Parameters
*self - pointer to this vector instance
Definition at line 226 of file tcmi_slotvec.h.
References self.
Referenced by check_duplicates(), kill_all_tasks(), tcmi_ccnman_stop_listen_all(), tcmi_ccnman_stop_listen_one(), tcmi_ccnman_thread(), tcmi_man_emig_npm(), tcmi_man_emig_ppm_p(), tcmi_man_fork(), tcmi_man_get_non_shutdowning_migman(), tcmi_man_send_generic_user_message(), tcmi_man_wait_for_migmans_termination(), tcmi_penmigman_migrate_all_home(), tcmi_slotvec_reserve_empty(), tcmi_transaction_lookup(), and tcmi_transaction_put().
 {
     // Have to be irqsave to avoid possible safe->unsafe conflict in forks
     spin_lock_irqsave(&self->s_lock, self->lock_flags);
 }
struct tcmi_slotvec* tcmi_slotvec_new (u_int size) read
Allocates a new slot vector.
Allocates a new slot vector.
Vector of slots is allocated and all slots are initialized. Since we want the slot to do the management of unused/used lists on their own, we pass the vector lock as well as both list heads to the init method.
reference counter is initialized to 1 - the instantiator owns this slot vector now
Parameters
size - number of slots to be allocated in the vector.
Returns
a new slot vector or NULL
Definition at line 50 of file tcmi_slotvec.c.
References mdbg, tcmi_slotvec::ref_count, tcmi_slotvec::s_lock, size, tcmi_slotvec::slot_count, tcmi_slotvec::slots, tcmi_slot_init(), tcmi_slotvec::unused_slots, and tcmi_slotvec::used_slots.
Referenced by tcmi_ccnman_init(), tcmi_man_init(), and tcmi_slotvec_hnew().
 {
     struct tcmi_slotvec *vec;
     struct tcmi_slot *slots;
     int i;
     if (!(vec = kmalloc(sizeof(struct tcmi_slotvec), GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate a slotvector");
         goto exit0;
     }
     if (!(slots = kmalloc(sizeof(struct tcmi_slot) * size, GFP_ATOMIC))) {
         mdbg(ERR3, "Failed to allocate a %d slots", size);
         goto exit1;
     }
     vec->slots = slots;
     vec->slot_count = size;
     INIT_LIST_HEAD(&vec->unused_slots);
     INIT_LIST_HEAD(&vec->used_slots);
     atomic_set(&vec->ref_count, 1);
     spin_lock_init(&vec->s_lock);
     /* initialize all slots */
     for (i = 0; i < size; i++) {
         tcmi_slot_init(slots, i, &vec->unused_slots,
                    &vec->used_slots, &vec->s_lock);
         slots++;
     }
     mdbg(INFO4, "Allocated %d slots (%lu bytes), memory=%p", size,
          (unsigned long)(sizeof(struct tcmi_slot) * size), vec);
     return vec;
     /* error handling */
  exit1:
     kfree(vec);
  exit0:
     return NULL;
 }
void tcmi_slotvec_put (struct tcmi_slotvec * self)
<<public>> Releases the instance.
<<public>> Releases the instance.
This requires releasing all slots and eventually releasing the instance itself.
Parameters
*self - pointer to this vector instance
Definition at line 117 of file tcmi_slotvec.c.
References mdbg, self, and tcmi_slot_empty().
Referenced by tcmi_ccnman_init(), tcmi_ccnman_shutdown(), tcmi_man_init(), tcmi_man_shutdown(), tcmi_migman_free(), tcmi_migman_init(), tcmi_task_init(), and tcmi_task_put().
 {
     struct tcmi_slot *slots;
     int i;
     if (!self)
         return;
     mdbg(INFO3, "Putting ref. count=%d (%p)",
          atomic_read(&self->ref_count), self);
     if (atomic_dec_and_test(&self->ref_count)) {
         slots = self->slots;
         for (i = 0; i < self->slot_count; i++, slots++) {
             if (!(tcmi_slot_empty(slots)))
                 mdbg(WARN3, "Warning - non empty slot %d", i);
         }
         mdbg(INFO4, "Released %d slots (%lu bytes), memory=%p",
              self->slot_count,
              (unsigned long)(sizeof(struct tcmi_slot) * self->slot_count), self);
         kfree(self->slots);
         kfree(self);
     }
 }
struct tcmi_slot* tcmi_slotvec_reserve_empty (struct tcmi_slotvec * self) read
<<public>> Finds the first empty slot.
<<public>> Finds the first empty slot.
The slot is removed from the unused list, so that other threads won't consider it when searching for empty slots. The user of this method is responsible for either filling the slot with some data or releasing the slot back to unused list by means of tcmi_slot.h::tcmi_slot_move_unused()
Parameters
*self - pointer to this vector instance
Returns
pointer to an empty slot or NULL
Definition at line 168 of file tcmi_slotvec.c.
References tcmi_slot::index, mdbg, self, tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_ccnman_listen(), tcmi_man_reserve_migmanslot(), and tcmi_slotvec_insert_at_empty().
 {
     struct tcmi_slot *slot = NULL;
     struct list_head *list;
     tcmi_slotvec_lock(self);
     if (!list_empty(&self->unused_slots)) {
         /* get the first slot */
         list_for_each(list, &self->unused_slots)
             break;
         slot = list_entry(list, struct tcmi_slot, slot_list);
         /* remove the slot, from the unused list */
         list_del_init(list);
         mdbg(INFO4, "Found empty slot index = %d", slot->index);
     }
     tcmi_slotvec_unlock(self);
     return slot;
 }
static void tcmi_slotvec_unlock (struct tcmi_slotvec * self) inline static
<<public>> Unlocks the instance data.
Parameters
*self - pointer to this vector instance
Definition at line 237 of file tcmi_slotvec.h.
References self.
Referenced by check_duplicates(), kill_all_tasks(), tcmi_ccnman_stop_listen_all(), tcmi_ccnman_stop_listen_one(), tcmi_ccnman_thread(), tcmi_man_emig_npm(), tcmi_man_emig_ppm_p(), tcmi_man_fork(), tcmi_man_get_non_shutdowning_migman(), tcmi_man_send_generic_user_message(), tcmi_man_wait_for_migmans_termination(), tcmi_penmigman_migrate_all_home(), tcmi_slotvec_reserve_empty(), tcmi_transaction_lookup(), and tcmi_transaction_put().
 {
     spin_unlock_irqrestore(&self->s_lock, self->lock_flags);
 }