Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ctlfs/tcmi_ctlfs_entry.c File Reference
tcmi_ctlfs_entry.c File Reference
#include <linux/module.h>
#include <linux/pagemap.h>
#include <linux/slab.h>
#include "tcmi_ctlfs_entry.h"
#include <dbg.h>
Macros
#define TCMI_CTLFS_ENTRY_PRIVATE
Functions
int tcmi_ctlfs_entry_init (struct tcmi_ctlfs_entry *self, struct tcmi_ctlfs_entry *parent, mode_t mode, struct tcmi_ctlfs_ops *entry_ops, const struct inode_operations *i_ops, const struct file_operations *f_ops, const char namefmt[], va_list args)
<<public>> This method is used when initializing a new entry.
int tcmi_ctlfs_rootentry_init (struct tcmi_ctlfs_entry *self, struct super_block *sb, mode_t mode, struct tcmi_ctlfs_ops *entry_ops, const struct inode_operations *i_ops, const struct file_operations *f_ops)
<<public>> Initializes a root entry instance.
void tcmi_ctlfs_entry_traverse_pred (struct tcmi_ctlfs_entry *self, callback *func, void *data)
<<public>> Iterates through all entry predecessors and calls the specified method for each entry (including self).
int tcmi_ctlfs_entry_depth (struct tcmi_ctlfs_entry *self)
<<public>> Calculates the depth of the entry in the tree.
int tcmi_ctlfs_entry_path_length (struct tcmi_ctlfs_entry *self)
<<public>> Calculates the length of the pathname string (including '/' for every path element).
void tcmi_ctlfs_entry_fill_path (struct tcmi_ctlfs_entry *self, char *buffer, int length)
<<public>> Fills in the entry's pathname into the specified buffer.
static void tcmi_ctlfs_add_depth (struct tcmi_ctlfs_entry *self, void *curr_depth)
<<private>> Helper callback function when calculating entry depth.
static void tcmi_ctlfs_add_length (struct tcmi_ctlfs_entry *self, void *curr_length)
<<private>> Helper callback function when calculating entry pathname length.
static void tcmi_ctlfs_add_path (struct tcmi_ctlfs_entry *self, void *buf_data)
<<private>> Helper callback method when filling the entry's pathname The entry fills in its name and the '/' as prefix to the current end of the buffer.
static void tcmi_ctlfs_entry_release (struct tcmi_ctlfs_entry *self)
<<private>> This private method is responsible for freeing any resources the entry is currently using(currently nothing).
static struct inode * tcmi_ctlfs_get_inode (struct inode *dir, struct super_block *sb, mode_t mode, const struct inode_operations *i_ops, const struct file_operations *f_ops)
<<private>> A method for inode allocation.
static int tcmi_ctlfs_entry_alloc_dentry (struct tcmi_ctlfs_entry *self, struct tcmi_ctlfs_entry *parent, struct inode *inode)
<<private>> The new dentry is allocated based on the parent's dentry and the current name of the ctlfs entry.
static int tcmi_ctlfs_entry_exists (struct tcmi_ctlfs_entry *self, const char *name)
<<private>> Checks whether a directory entry contains entry of the specified name
static int tcmi_ctlfs_dentry_delete (const struct dentry *dentry)
<<private>> This class method is a custom implementation of a VFS delete_dentry operation.
static void tcmi_ctlfs_dentry_release (struct dentry *dentry)
<<private>> This class method is a custom implementation of a VFS release_dentry operation.
EXPORT_SYMBOL_GPL (tcmi_ctlfs_entry_depth)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_entry_traverse_pred)
Variables
static struct dentry_operations tcmi_ctlfs_dentry_ops
Custom dentry delete operation for VFS.
Macro Definition Documentation
#define TCMI_CTLFS_ENTRY_PRIVATE
Definition at line 37 of file tcmi_ctlfs_entry.c.
Function Documentation
EXPORT_SYMBOL_GPL (tcmi_ctlfs_entry_depth)
EXPORT_SYMBOL_GPL (tcmi_ctlfs_entry_traverse_pred)
static void tcmi_ctlfs_add_depth (struct tcmi_ctlfs_entry * self, void * curr_depth) static
<<private>> Helper callback function when calculating entry depth.
Parameters
*self - pointer to this instance
*curr_depth - pointer to the current depth
Definition at line 268 of file tcmi_ctlfs_entry.c.
Referenced by tcmi_ctlfs_entry_depth().
 {
     (*((int *)curr_depth))++;
 }
static void tcmi_ctlfs_add_length (struct tcmi_ctlfs_entry * self, void * curr_length) static
<<private>> Helper callback function when calculating entry pathname length.
Parameters
*self - pointer to this instance
*curr_length - pointer to the current length
Definition at line 281 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_entry_path_length().
 {
     /* + 1 accounts for '/' */
     (*((int *)curr_length)) += strlen(tcmi_ctlfs_entry_name(self)) + 1;
 }
static void tcmi_ctlfs_add_path (struct tcmi_ctlfs_entry * self, void * buf_data) static
<<private>> Helper callback method when filling the entry's pathname The entry fills in its name and the '/' as prefix to the current end of the buffer.
Parameters
*self - pointer to this instance
*buf_data - buffer data that contain pointer to the buffer and its current length.
Definition at line 297 of file tcmi_ctlfs_entry.c.
References mdbg, and tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_entry_fill_path().
 {
     struct {
         char *buffer;
         int length;
     } *buf = buf_data;
     int cur = strlen(tcmi_ctlfs_entry_name(self));
     mdbg(INFO4, "Adding.. %s, buffer length=%d", tcmi_ctlfs_entry_name(self), buf->length);
     /* back up enough to print entry name with '/' prefix */
     buf->length -= cur;
     strncpy(buf->buffer + buf->length, tcmi_ctlfs_entry_name(self), cur);
     *(buf->buffer + --(buf->length)) = '/';
     mdbg(INFO4, "New buffer length=%d", buf->length);
 }
static void tcmi_ctlfs_dentry_release (struct dentry * dentry) static
<<private>> This class method is a custom implementation of a VFS release_dentry operation.
The release_dentry is called by VFS when releasing the dentry associated with a particular tcmi_ctlfs_entry object. This happens when the dentry's reference counter reaches 0.
Unlike previous VFS method, we are allowed to sleep as the dcache lock and dentry lock are not held anymore (see fs/dcache.c)
Parameters
*dentry - pointer to the dentry that is to be deleted
Returns
- always 1 since we don't want the VFS to put the dentry into the dentry_unused. This way the dentry will be unhashed and removed right away
Definition at line 484 of file tcmi_ctlfs_entry.c.
References minfo, TCMI_CTLFS_DENTRY_TO_ENTRY, and tcmi_ctlfs_entry_release().
 {
     /* get the instance first */
     struct tcmi_ctlfs_entry *self = TCMI_CTLFS_DENTRY_TO_ENTRY(dentry);
     if (self)
         tcmi_ctlfs_entry_release(self);
     else
         minfo(ERR2, "VFS issued dentry_release on a dentry without tcmi_ctlfs_instance!!");
 }
static int tcmi_ctlfs_entry_alloc_dentry (struct tcmi_ctlfs_entry * self, struct tcmi_ctlfs_entry * parent, struct inode * inode) static
<<private>> The new dentry is allocated based on the parent's dentry and the current name of the ctlfs entry.
The dentry is associated with the specified inode. The dentry is assigned our custom operations vector, so that we are informed about dentry destruction.
Parameters
*self - pointer to this instance
*parent - pointer to the parent entry - has to be a directory
*inode - pointer to the inode, that is to be associated with the new dentry.
Returns
0 upon success.
Definition at line 406 of file tcmi_ctlfs_entry.c.
References tcmi_ctlfs_entry::dentry, mdbg, self, and tcmi_ctlfs_dentry_ops.
Referenced by tcmi_ctlfs_entry_init().
 {
     struct dentry *dentry;
     int error = 1;
     /* try allocating the dentry */
     if ((dentry = d_alloc_name(parent->dentry, self->name))) {
         d_add(dentry, inode); /* enters the dentry into hash queues */
         dentry->d_fsdata = (void *)self;
         dentry->d_op = &tcmi_ctlfs_dentry_ops;
         self->dentry = dentry;
         /* dget(dentry); Extra count - pin the dentry in core - not needed */
         error = 0;
     }
     else
         mdbg(ERR3, "Failed to allocate a new dentry for %s", self->name);
     return error;
 }
static int tcmi_ctlfs_entry_exists (struct tcmi_ctlfs_entry * self, const char * name) static
<<private>> Checks whether a directory entry contains entry of the specified name
Parameters
*self - pointer to this instance
*name - pointer to the name to be checked
Returns
1 - if the entry of the specified name exists
Definition at line 434 of file tcmi_ctlfs_entry.c.
References self.
Referenced by tcmi_ctlfs_entry_init().
 {
     struct dentry *dentry;
     struct qstr q;
     int exists = 0;
     q.name = name;
     q.len = strlen(name);
     q.hash = full_name_hash(q.name, q.len);
     dentry = d_lookup(self->dentry, &q);
     /* dentry already exists, decrement its reference counter since lookup
      incremented it */
     if (dentry) {
         dput(dentry);
             exists = 1;
     }
     return exists;
 }
static void tcmi_ctlfs_entry_release (struct tcmi_ctlfs_entry * self) inline static
<<private>> This private method is responsible for freeing any resources the entry is currently using(currently nothing).
When possible the child class is also notified. The instance is eventually destroyed.
Parameters
*self - pointer to this instance
Returns
0
Definition at line 325 of file tcmi_ctlfs_entry.c.
References mdbg, self, and tcmi_ctlfs_entry_name().
Referenced by tcmi_ctlfs_dentry_release().
 {
     mdbg(INFO4, "entry '%s' is being freed(%p)",
          tcmi_ctlfs_entry_name(self), self);
     /* free child class instance data? */
     if (self->entry_ops && self->entry_ops->entry_release) {
         self->entry_ops->entry_release(self);
     }
     kfree(self);
 }
static struct inode* tcmi_ctlfs_get_inode (struct inode * dir, struct super_block * sb, mode_t mode, const struct inode_operations * i_ops, const struct file_operations * f_ops) static read
<<private>> A method for inode allocation.
Currently the uid and gid is assigned based on the current's fsuid and fsgid. Block size is not relevant, set to page size. If the user doesn't specify any inode or file operations, the default(empty operations, but not NULL) assigned by the VFS will be kept.
If the user specified a parent directory inode, it's access rights are investigated and inherited by the new inode as follows:
if the parent has the SGID bit set, parent's gid is assigned to the new inode.
a parent SGID bit is set on the new inode, if the new inode is a directory
Parameters
*dir - inode of the parent directory for the new inode
*sb - super block of the filesystem where the inode is to be allocated
*mode - file type and access rights for the inode
*i_ops - inode operations
*f_ops - file operations (also stored in the new inode)
Returns
a pointer to the new inode or NULL
Definition at line 361 of file tcmi_ctlfs_entry.c.
References mdbg, minfo, and mode.
Referenced by tcmi_ctlfs_entry_init(), and tcmi_ctlfs_rootentry_init().
 {
     struct inode *inode = new_inode(sb);
   if (inode) {
         inode->i_mode = mode;
         inode->i_uid = current_fsuid();
         inode->i_gid = current_fsgid();
         inode->i_blocks = 0;
         inode->i_op  = (i_ops ? i_ops : inode->i_op);
         inode->i_fop = (f_ops ? f_ops : inode->i_fop);
         inode->i_atime = inode->i_mtime = inode->i_ctime = CURRENT_TIME;
     inode->i_ino = get_next_ino();    //Added number inode i_no in new kernel it must be assigned from return value function get_next_ino() which returns next number inode | by Jiri Rakosnik
         mdbg(INFO4, "New inode allocated, inode number = %ld", inode->i_ino);
         /* check parent inode's(if any) access rights */
         if (dir && (dir->i_mode & S_ISGID)) {
             inode->i_gid = dir->i_gid;
             if (S_ISDIR(mode))
                 inode->i_mode |= S_ISGID;
         }
     }
     else
         minfo(ERR3, "Failed to allocate a new inode");
     return inode;
 }