Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/kkc/kkc_sock.h File Reference
kkc_sock.h File Reference
#include <linux/list.h>
#include <asm/atomic.h>
#include <linux/semaphore.h>
#include <linux/mutex.h>
#include <linux/slab.h>
#include "kkc_arch.h"
Data Structures
struct kkc_sock
A coumpound structure that contains generic information about a KKC socket.
struct kkc_sock_ops
Socket operations that support polymorphism.
Macros
#define KKC_SOCK_MAX_ADDR_LENGTH 100
Maximum address length.
#define KKC_SOCK(s) ((struct kkc_sock*)s)
Casts to the kkc_sock instance.
Typedefs
typedef void(* kkc_data_ready)(void *data, int bytes)
Callback function prototype, that can be registered to be notified about in case there are some data ready to be read on a socket.
Enumerations
enum kkc_sock_flags_t { KKC_SOCK_BLOCK, KKC_SOCK_NONBLOCK, KKC_SOCK_BLOCK, KKC_SOCK_NONBLOCK }
Flags for receive and accept operations.
Functions
int kkc_sock_init (struct kkc_sock *self, struct kkc_arch *arch, struct kkc_sock_ops *sock_ops)
<<public>> Initializes generic socket.
int kkc_sock_connect (struct kkc_sock *self, char *addr)
<<public>> Connects to the given address
int kkc_sock_listen (struct kkc_sock *self, char *addr)
<<public>> Starts listening on a specified address
int kkc_sock_accept (struct kkc_sock *self, struct kkc_sock **new_kkc_sock, kkc_sock_flags_t flags)
<<public>> Creates a new socket by accepting the incoming socket.
int kkc_sock_send (struct kkc_sock *self, void *buf, int buflen, kkc_sock_flags_t flags)
<<public>> Sends out specified data.
int kkc_sock_recv (struct kkc_sock *self, void *buf, int buflen, kkc_sock_flags_t flags)
<<public>> Receives requested number of bytes of data.
int kkc_sock_shutdown (struct kkc_sock *self)
<<public>> Disconnects the socket.
int kkc_sock_add_wait_queue (struct kkc_sock *self, wait_queue_t *wait)
<<public>> Adds a task to the queue of processes sleeping on the socket.
int kkc_sock_remove_wait_queue (struct kkc_sock *self, wait_queue_t *wait)
<<public>> Removes a task from the queue of processes sleeping on the socket.
int kkc_sock_register_read_callback (struct kkc_sock *, kkc_data_ready callback, void *callback_data)
<<public>> Registers data_ready callback function, that should be called when there are some data read to be read on the socket
static int kkc_sock_is_address_equal_to (struct kkc_sock *self, const char *addr, int addr_length, int local)
<<public>> Checks, whether an address passed as string is equal to this socket local/peer port.
static int kkc_sock_getsockname (struct kkc_sock *self, char *sockname, int size)
<<public>> Local socket name accessor.
static int kkc_sock_getpeername (struct kkc_sock *self, char *sockname, int size)
<<public>> Peer socket name accessor.
static void kkc_sock_getarchname (struct kkc_sock *self, char *archname, int size)
<<public>> Architecture name accessor.
static const char * kkc_sock_getsockname2 (struct kkc_sock *self)
<<public>> Socket name accessor.
static const char * kkc_sock_getpeername2 (struct kkc_sock *self)
<<public>> Socket name accessor.
static struct kkc_sock * kkc_sock_get (struct kkc_sock *self)
<<public>> Instance accessor, increments the reference count.
static void kkc_sock_put (struct kkc_sock *self)
<<public>> Decrements reference counter, if it reaches 0 the custom free method is called if defined.
static int kkc_sock_snd_lock_interruptible (struct kkc_sock *self)
<<public>> Locks this socket instance for sending, interruptible version, the process can be woken up by a signal.
static void kkc_sock_snd_lock (struct kkc_sock *self)
<<public>> Locks this socket instance for sending.
static void kkc_sock_snd_unlock (struct kkc_sock *self)
<<public>> Unlocks this socket instance for sending.
static int kkc_sock_rcv_lock_interruptible (struct kkc_sock *self)
<<public>> Locks this socket instance for receiving, interruptible version, the process can be woken up by a signal.
static void kkc_sock_rcv_lock (struct kkc_sock *self)
<<public>> Locks this socket instance for receiving.
static void kkc_sock_rcv_unlock (struct kkc_sock *self)
<<public>> Unlocks this socket instance for receiving.
Function Documentation
static struct kkc_sock* kkc_sock_get (struct kkc_sock * self) static read
<<public>> Instance accessor, increments the reference count.
Parameters
*self - pointer to this message instance
Definition at line 253 of file kkc_sock.h.
References self.
 {
     if (self) {
         atomic_inc(&self->ref_count);
     }
     return self;
 }
static void kkc_sock_getarchname (struct kkc_sock * self, char * archname, int size) inline static
<<public>> Architecture name accessor.
Asks the architecture to fill in its name.
Parameters
*self - pointer to this socket instance
*archname - pointer to the buffer where the architecture name is to be stored
size - maximum string length that fits into the sockname buffer
Definition at line 212 of file kkc_sock.h.
References kkc_arch_name(), and self.
 {
     strncpy(archname, kkc_arch_name(self->arch), size);
 }
static int kkc_sock_getpeername (struct kkc_sock * self, char * sockname, int size) inline static
<<public>> Peer socket name accessor.
Asks the architecture specific socket to fill in its remote name (destination address). The generic socket operation getname() is used, passing 1 selects the peer name.
Parameters
*self - pointer to this socket instance
*sockname - pointer to the buffer where the sockname is to be stored
size - maximum string length that fits into the sockname buffer
Returns
0 upon success
Definition at line 196 of file kkc_sock.h.
References self.
Referenced by kkc_sock_getpeername2().
 {
     int err = 0;
     if (self->sock_ops && self->sock_ops->getname)
         err = self->sock_ops->getname(self, sockname, size, 1);
     return err;
 }
static const char* kkc_sock_getpeername2 (struct kkc_sock * self) inline static
<<public>> Socket name accessor.
Unlike the previous version, returns pointer to the socket local name. The socket local name is stored inside the instance. Having this method makes it easier to use it inside print statements.
Parameters
*self - pointer to this socket instance
Returns
to the local socket name
Definition at line 241 of file kkc_sock.h.
References kkc_sock_getpeername(), KKC_SOCK_MAX_ADDR_LENGTH, and self.
Referenced by kkc_sock_put().
 {
     memset(self->peername, 0, KKC_SOCK_MAX_ADDR_LENGTH);
     kkc_sock_getpeername(self, self->peername, KKC_SOCK_MAX_ADDR_LENGTH);
     return self->peername;
 }
static int kkc_sock_getsockname (struct kkc_sock * self, char * sockname, int size) inline static
<<public>> Local socket name accessor.
Asks the architecture specific socket to fill in its local name (address). The generic socket operation getname() is used, passing 0 selects the local name.
Parameters
*self - pointer to this socket instance
*sockname - pointer to the buffer where the sockname is to be stored
size - maximum string length that fits into the sockname buffer
Returns
0 upon success
Definition at line 178 of file kkc_sock.h.
References self.
Referenced by kkc_sock_getsockname2().
 {
     int err = 0;
     if (self->sock_ops && self->sock_ops->getname)
         err = self->sock_ops->getname(self, sockname, size, 0);
     return err;
 }
static const char* kkc_sock_getsockname2 (struct kkc_sock * self) inline static
<<public>> Socket name accessor.
Unlike the previous version, returns pointer to the socket local name. The socket local name is stored inside the instance. Having this method makes it easier to use it inside print statements.
Parameters
*self - pointer to this socket instance
Returns
to the local socket name
Definition at line 226 of file kkc_sock.h.
References kkc_sock_getsockname(), KKC_SOCK_MAX_ADDR_LENGTH, and self.
Referenced by kkc_sock_put().
 {
     memset(self->sockname, 0, KKC_SOCK_MAX_ADDR_LENGTH);
     kkc_sock_getsockname(self, self->sockname, KKC_SOCK_MAX_ADDR_LENGTH);
     return self->sockname;
 }
static int kkc_sock_is_address_equal_to (struct kkc_sock * self, const char * addr, int addr_length, int local) inline static
<<public>> Checks, whether an address passed as string is equal to this socket local/peer port.
Can return true only if current socket is connected.
Definition at line 160 of file kkc_sock.h.
References self.
{
     int err = 0;
     if (self->sock_ops && self->sock_ops->is_address_equal_to)
         err = self->sock_ops->is_address_equal_to(self, addr, addr_length, local);
     return err;
 }
static void kkc_sock_put (struct kkc_sock * self) inline static
<<public>> Decrements reference counter, if it reaches 0 the custom free method is called if defined.
Also the architecture is released.
The user is responsible for taking the socket out of any lists where he had stored it.
Parameters
*self - pointer to this socket instance
Definition at line 271 of file kkc_sock.h.
References kkc_arch_put(), kkc_sock_getpeername2(), kkc_sock_getsockname2(), mdbg, and self.
 {
     if (!self)
         return;
     if (atomic_dec_and_test(&self->ref_count)) {
         mdbg(INFO4, "Destroying KKC socket local: '%s', remote: '%s', %p",
              kkc_sock_getsockname2(self),
              kkc_sock_getpeername2(self), self);
         if (self->sock_ops && self->sock_ops->free)
             self->sock_ops->free(self);
         /* release the architecture */
         kkc_arch_put(self->arch);
         kfree(self);
     }
 }
static void kkc_sock_rcv_lock (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for receiving.
Parameters
*self - pointer to this socket instance
Definition at line 337 of file kkc_sock.h.
References self.
 {
         down(&self->sock_recv_sem);
 }
static int kkc_sock_rcv_lock_interruptible (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for receiving, interruptible version, the process can be woken up by a signal.
Parameters
*self - pointer to this file instance
Definition at line 327 of file kkc_sock.h.
References self.
 {
     return (down_interruptible(&self->sock_recv_sem));
 }
static void kkc_sock_rcv_unlock (struct kkc_sock * self) inline static
<<public>> Unlocks this socket instance for receiving.
Parameters
*self - pointer to this socket instance
Definition at line 347 of file kkc_sock.h.
References self.
 {
         up(&self->sock_recv_sem);
 }
static void kkc_sock_snd_lock (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for sending.
Parameters
*self - pointer to this socket instance
Definition at line 306 of file kkc_sock.h.
References self.
 {
         down(&self->sock_send_sem);
 }
static int kkc_sock_snd_lock_interruptible (struct kkc_sock * self) inline static
<<public>> Locks this socket instance for sending, interruptible version, the process can be woken up by a signal.
Parameters
*self - pointer to this file instance
Definition at line 296 of file kkc_sock.h.
References self.
 {
     return (down_interruptible(&self->sock_send_sem));
 }
static void kkc_sock_snd_unlock (struct kkc_sock * self) inline static
<<public>> Unlocks this socket instance for sending.
Parameters
*self - pointer to this socket instance
Definition at line 316 of file kkc_sock.h.
References self.
 {
         up(&self->sock_send_sem);
 }