Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/comm/tcmi_msg.c File Reference
tcmi_msg.c File Reference
#include <linux/kernel.h>
#include "tcmi_msg.h"
#include <dbg.h>
Macros
#define TCMI_MSG_PRIVATE
Functions
static int tcmi_msg_init_shared (struct tcmi_msg *self, u_int32_t msg_id, struct tcmi_msg_ops *msg_ops)
Shared initialization fuction of both rx and tx messages.
int tcmi_msg_init_rx (struct tcmi_msg *self, u_int32_t msg_id, struct tcmi_msg_ops *msg_ops)
<<public>> Initializes the message for receiving.
int tcmi_msg_init_tx (struct tcmi_msg *self, u_int32_t msg_id, struct tcmi_msg_ops *msg_ops, struct tcmi_slotvec *transactions, u_int32_t resp_msg_id, u_int timeout, u_int32_t resp_trans_id)
<<public>> Initializes the message for transferring.
int tcmi_msg_send_anonymous (struct tcmi_msg *self, struct kkc_sock *sock)
<<public>> Sends a message via a specified connection.
int tcmi_msg_send_and_receive (struct tcmi_msg *self, struct kkc_sock *sock, struct tcmi_msg **resp)
<<public>> Sends a message via a specified connection and waits for the response.
int tcmi_msg_recv (struct tcmi_msg *self, struct kkc_sock *sock)
<<public>> Receives a message via a specified connection.
int tcmi_msg_deliver (struct tcmi_msg *self, struct tcmi_queue *requests, struct tcmi_slotvec *transactions)
<<public>> A message always delivers itself.
struct tcmi_msg * tcmi_msg_new_rx (u_int32_t msg_id, struct tcmi_msg_dsc *dsc)
<<public>> Class method - creates a message based on a descriptor.
static int tcmi_msg_send (struct tcmi_msg *self, struct kkc_sock *sock, int flags)
<<private>> Sends a message via a specified connection.
Macro Definition Documentation
#define TCMI_MSG_PRIVATE
Definition at line 34 of file tcmi_msg.c.
Function Documentation
static int tcmi_msg_init_shared (struct tcmi_msg * self, u_int32_t msg_id, struct tcmi_msg_ops * msg_ops) static
Shared initialization fuction of both rx and tx messages.
Definition at line 41 of file tcmi_msg.c.
References mdbg, self, and TCMI_TRANSACTION_INVAL_ID.
Referenced by tcmi_msg_init_rx(), and tcmi_msg_init_tx().
{
     mdbg(INFO4, "Initialized message ID=%u, %p", msg_id, self);
     self->msg_id = msg_id;
     /* initially no transaction associated with the message */
     self->trans_id.req = TCMI_TRANSACTION_INVAL_ID;
     self->trans_id.resp = TCMI_TRANSACTION_INVAL_ID;
     self->transaction = NULL;
     self->msg_ops = msg_ops;
     atomic_set(&self->ref_count, 1);
     /* initialize list head for message queueing */
     INIT_LIST_HEAD(&self->node);
     return 0;
 }
static int tcmi_msg_send (struct tcmi_msg * self, struct kkc_sock * sock, int flags) static
<<private>> Sends a message via a specified connection.
Sending a message requires following steps:
activate the transaction(if any)
send message ID,
send transaction ID(or TCMI_TRANSACTION_INVAL_ID for oneway messages)
call a specific message method
It is necessary to lock the socket, so that the message won't get intermixed with some other.
Parameters
*self - pointer to this message instance
*sock - KKC socket used for sending message data
flags - if the message has a transaction, these are additional flags to be set in the transaction.
Returns
0 upon success
try to start the transaction
Definition at line 413 of file tcmi_msg.c.
References KKC_SOCK_BLOCK, kkc_sock_send(), kkc_sock_snd_lock_interruptible(), kkc_sock_snd_unlock(), mdbg, self, tcmi_msg_ops::send, and tcmi_transaction_start().
Referenced by tcmi_msg_send_and_receive(), and tcmi_msg_send_anonymous().
 {
     int err = 0;
     struct tcmi_msg_ops *ops = self->msg_ops;
     struct tcmi_transaction *trans = self->transaction;
     /** try to start the transaction */
     if (trans && (err = tcmi_transaction_start(trans, flags))) {
         mdbg(ERR3, "Failed to start the transaction %d", err);
         goto exit0;
     }
     /* Send message ID*/
     mdbg(INFO3, "Sending message(Msg=%p ID=%x req=%x resp=%x), transaction started: %d",
          self, self->msg_id, self->trans_id.req, self->trans_id.resp, (trans!=NULL));
     if ((err = kkc_sock_snd_lock_interruptible(sock))) {
         mdbg(ERR3, "Socket lock - interrupted by a signal %d", err);
         goto exit0;
     }
     if ((err = kkc_sock_send(sock, &self->msg_id,
                  sizeof(self->msg_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send message ID: %d. Err: %d", self->msg_id, err);
         goto exit1;
     }
     /* Send transaction ID's */
     if ((err = kkc_sock_send(sock, &self->trans_id,
                  sizeof(self->trans_id), KKC_SOCK_BLOCK)) < 0) {
         mdbg(ERR3, "Failed to send transaction ID's");
         goto exit1;
     }
     /* Send the actual message content */
     if (ops && ops->send) {
         err = ops->send(self, sock);
     }
     /* convert the result to 0 if no error has occured this is
      * because the number of bytes sent has no meaning for us anymore */
     err = min(err, 0);
     kkc_sock_snd_unlock(sock);
     return err;
     /* error handling */
  exit1:
     kkc_sock_snd_unlock(sock);
  exit0:
     return err;
 }