Clondike: Processing sys_wait4
Processing sys_wait4
tcmi_shadow_rpc class
A <<singleton>> class that is executing RPC on CCN side.
Functions
long tcmi_shadow_rpc_sys_wait4 (unsigned rpc_num, long params[6])
Declaration of tcmi_shadow_rpc_sys_wait4()
Detailed Description
A <<singleton>> class that is executing RPC on CCN side.
Function Documentation
long tcmi_shadow_rpc_sys_wait4 (unsigned rpc_num, long params[6])
Declaration of tcmi_shadow_rpc_sys_wait4()
Definition at line 14 of file tcmi_shadow_wait_rpc.c.
References mdbg, pid, resp, rusage_to_ind(), sys_wait4(), TCMI_RPC_PROCMSG, tcmi_rpc_procmsg_data_base(), TCMI_RPCRESP_PROCMSG, tcmi_rpcresp_procmsg_create(), tcmi_rpcresp_procmsg_free_on_put(), and TCMI_RPCRESP_PROCMSG_KFREE.
 {
     struct tcmi_msg **resp, *m;
     long rtn;
     mm_segment_t old_fs;
     // Platform independend params
     int32_t pid;
     int32_t options;
     // Platform independend return values
     struct rusage_ind* result_usage_ind;
     int32_t* result_stats_ind;
     // Return values
     struct rusage* result_usage;
     int result_stats;
     mdbg(INFO3, "Forwarded wait syscall being processed");
     result_usage = kmalloc(sizeof(*result_usage), GFP_KERNEL);
     if ( !result_usage )
         return -ENOMEM;
     m = (struct tcmi_msg*) params[0];
     resp = (struct tcmi_msg**) params[1];
     // Extract params
     pid = *(int32_t*)tcmi_rpc_procmsg_data_base( TCMI_RPC_PROCMSG(m), 0);
     options = *(int32_t*)tcmi_rpc_procmsg_data_base( TCMI_RPC_PROCMSG(m), 1);
     mdbg(INFO3, "Waiting for pid: %d", pid);
     // Perform the call
     old_fs = get_fs();
     set_fs(KERNEL_DS);
     rtn = sys_wait4(pid, &result_stats , options, result_usage);
     set_fs(old_fs);
     // Convert resuls to platform independend values
     result_usage_ind = kmalloc(sizeof(*result_usage_ind), GFP_KERNEL);
     if ( !result_usage_ind ) {
         kfree(result_usage);
         return -ENOMEM;
     }
     result_stats_ind = kmalloc(sizeof(int32_t), GFP_KERNEL);
     if ( !result_stats_ind ) {
         kfree(result_usage);
         kfree(result_usage_ind);
         return -ENOMEM;
     }
     rusage_to_ind(result_usage, result_usage_ind);
     *result_stats_ind = result_stats;
     mdbg(INFO3, "Forwarded wait syscall wait finished. Status: %d (ind: %d) res: %ld", result_stats, *result_stats_ind, rtn);
     // Create response with the results
     *resp = tcmi_rpcresp_procmsg_create(m, rtn, sizeof(*result_usage_ind), result_usage_ind,
                             sizeof(*result_stats_ind), result_stats_ind,
                         (size_t)0 );
     kfree(result_usage);
     if( *resp == NULL ) {
         kfree(result_usage_ind);
         kfree(result_stats_ind);
         return -1;
     }
     tcmi_rpcresp_procmsg_free_on_put( TCMI_RPCRESP_PROCMSG(*resp), 0, TCMI_RPCRESP_PROCMSG_KFREE );
     tcmi_rpcresp_procmsg_free_on_put( TCMI_RPCRESP_PROCMSG(*resp), 1, TCMI_RPCRESP_PROCMSG_KFREE );
     return 0;
 }