Clondike: tcmi_slot class
tcmi_slot class
lib
This class represents a slot that is part of a slot vector.
Data Structures
struct tcmi_slot
A slot compound structure.
Macros
#define tcmi_slot_entry(ptr, type, member) hlist_entry(ptr, type, member)
<<public>> Extracts the actual entry from a slot node
#define tcmi_slot_for_each(node, slot) hlist_for_each(node, &slot->head)
<<public>> Iterates through all nodes in the slot.
#define tcmi_slot_for_each_entry(object, node, slot, member) hlist_for_each_entry(object, node, &slot->head, member)
<<public>> Iterates through all nodes in the slot.
#define tcmi_slot_for_each_entry_safe(object, node, node2, slot, member) hlist_for_each_entry_safe(object, node, node2, &slot->head, member)
<<public>> Iterates through all nodes in the slot - safe version.
#define tcmi_slot_find_first(object, slot, member)
<<public>> Returns the first object in the slot.
#define tcmi_slot_remove_first(object, slot, member)
<<public>> Removes the first object in the slot.
#define tcmi_slot_node_unhashed(n) hlist_unhashed(n)
Check for node being removed from the hlist.
Typedefs
typedef struct hlist_node tcmi_slot_node_t
A slot node is in fact a hlist node.
Functions
static void tcmi_slot_init (struct tcmi_slot *self, u_int index, struct list_head *unused_slots, struct list_head *used_slots, spinlock_t *lock)
Initializes a slot.
static int tcmi_slot_empty (struct tcmi_slot *self)
<<public>> Checks if the slot is empty.
static u_int tcmi_slot_index (struct tcmi_slot *self)
<<public>> Slot index accessor.
static void tcmi_slot_lock (struct tcmi_slot *self)
<<public>> Locks the slot data.
static void tcmi_slot_unlock (struct tcmi_slot *self)
<<public>> Unlocks the instance data
static void tcmi_slot_move (struct tcmi_slot *self, struct list_head *head)
<<private>> Moves a slot into the specified list.
static void tcmi_slot_move_tail (struct tcmi_slot *self, struct list_head *head)
<<private>> Moves a slot to the tail of the specified list.
static void tcmi_slot_insert (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Inserts a new node into the slot.
static void tcmi_slot_move_unused (struct tcmi_slot *self)
<<public>> Moves a slot among unused_slots.
static void __tcmi_slot_remove (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Removes a given node from a slot.
static void tcmi_slot_remove (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Removes a given node from a slot.
static void tcmi_slot_remove_safe (struct tcmi_slot *self, tcmi_slot_node_t *node)
<<public>> Removes a given node from a slot.
Detailed Description
This class represents a slot that is part of a slot vector.
The slot contains a head of a doubly linked list. This list is used for storing objects. Objects within a slot are stored(linked together by means of tcmi_slot_node_t. Each slot is identified by its number. That way, the user can locate it in the slot vector .
Also the slots are internally linked together by the slot_list. The slot is inserted into used_ or unused_slots list. This allows fast allocation of empty slots. The unused_/used_slots list management is done by each slot on its own. The references to unused_/used_slots list are always shared by all slots within a particular slot vector.
An typical object that wants to be stored in a slot will look like this:
* struct object {
*   tcmi_slot_node_t node;
*       .
*       .
*      (other object data items)
* };
*
*
Data Structure Documentation
struct tcmi_slot
A slot compound structure.
Contains the list of items stored items. Also there is another list head provided. This is for internal use by the tcmi_slotvec class.
Definition at line 154 of file tcmi_slot.h.
Data Fields
struct hlist_head head head of the list of items stored in the slot
u_int index The slot number.
unsigned long lock_flags Technical field used for irq safe spinlocks.
spinlock_t * s_lock Protects the unused/used_slots lists from concurrent modification.
Also, this lock is used when modifying the slot itself. Maybe, it would be a good idea to have a separate lock for each slot in addition to this one. The drawback would be the increased size of the slot. I will keep it like this for now
struct list_head slot_list used when linking slots in used or unused lists
struct list_head * unused_slots Protects the slotvector from concurrent modification.
list of unused slots
struct list_head * used_slots list of used slots
Macro Definition Documentation
#define tcmi_slot_entry (ptr, type, member) hlist_entry(ptr, type, member)
<<public>> Extracts the actual entry from a slot node
Definition at line 71 of file tcmi_slot.h.
Referenced by check_duplicates(), kill_all_tasks(), tcmi_man_get_non_shutdowning_migman(), and tcmi_penmigman_migrate_all_home().
#define tcmi_slot_find_first (object, slot, member)
Value:
do {                                \
    tcmi_slot_node_t *__node;              \
    tcmi_slot_for_each_entry(object, __node, slot, member)  \
        break;                      \
} while(0)
<<public>> Returns the first object in the slot.
Parameters
object - will store the pointer to the object in the slot
slot - from which to take the first object
member - name of the list node member in the object
Definition at line 120 of file tcmi_slot.h.
Referenced by tcmi_ccnman_thread(), tcmi_man_emig_npm(), tcmi_man_emig_ppm_p(), tcmi_man_fork(), and tcmi_man_send_generic_user_message().
#define tcmi_slot_for_each (node, slot) hlist_for_each(node, &slot->head)
<<public>> Iterates through all nodes in the slot.
Parameters
node - every iteration points to a new node
slot - slot that we are iterating through
Definition at line 79 of file tcmi_slot.h.
Referenced by check_duplicates(), kill_all_tasks(), tcmi_man_get_non_shutdowning_migman(), tcmi_penmigman_migrate_all_home(), and tcmi_slot_remove_safe().
#define tcmi_slot_for_each_entry (object, node, slot, member) hlist_for_each_entry(object, node, &slot->head, member)
<<public>> Iterates through all nodes in the slot.
This is intended for traversals only, no removals should take place. We still need to ensure the slot protection against concurrent manipulation from other threads.
Parameters
object - every iteration points to a new object
node - temporary storage for the current tcmi_slot_node_t
slot - slot that we are iterating through
member - name of the list node member in the object
Definition at line 92 of file tcmi_slot.h.
Referenced by tcmi_transaction_lookup().
#define tcmi_slot_for_each_entry_safe (object, node, node2, slot, member) hlist_for_each_entry_safe(object, node, node2, &slot->head, member)
<<public>> Iterates through all nodes in the slot - safe version.
This is a version safe against removals. If the current object, will be removed during the iteration, no issues will arise. We still need to ensure the slot protection against concurrent manipulation from other threads.
Parameters
object - every iteration points to a new object
node - temporary storage for the current tcmi_slot_node_t
node2 - another temporary storage for the copy of the previous node tcmi_slot_node_t
slot - slot that we are iterating through
member - name of the list node member in the object
Definition at line 109 of file tcmi_slot.h.
#define tcmi_slot_node_unhashed (n) hlist_unhashed(n)
Check for node being removed from the hlist.
Definition at line 148 of file tcmi_slot.h.
Referenced by tcmi_ccnman_thread(), and tcmi_migman_unhash().
#define tcmi_slot_remove_first (object, slot, member)
Value:
do {                                    \
    tcmi_slot_node_t *__node;                  \
    tcmi_slot_for_each_entry(object, __node, slot, member) {    \
        __tcmi_slot_remove(slot, &object->member);      \
        break;                          \
    }                               \
} while(0)
<<public>> Removes the first object in the slot.
If the slot is empty, does nothing
Parameters
object - will store the pointer to the object in the slot
slot - from which to take the first object
member - name of the list node member in the object
Definition at line 135 of file tcmi_slot.h.
Referenced by tcmi_ccnman_stop_listen_one(), and tcmi_migman_unhash().
Typedef Documentation
typedef struct hlist_node tcmi_slot_node_t
A slot node is in fact a hlist node.
Definition at line 145 of file tcmi_slot.h.
Function Documentation
static void __tcmi_slot_remove (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Removes a given node from a slot.
No check is performed, whether the node belongs to this slot. If the slot becomes empty by removeing the node, it will be moved to the unused slot list.
Note
This method assumes the s_lock is held.
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be removed
Definition at line 321 of file tcmi_slot.h.
References mdbg, self, tcmi_slot_empty(), and tcmi_slot_move_unused().
Referenced by tcmi_slot_remove(), and tcmi_slot_remove_safe().
 {
     hlist_del_init(node);
     if (tcmi_slot_empty(self)) {
         tcmi_slot_move_unused(self);
         mdbg(INFO4, "Slot %d is now empty, moving to unused slots", self->index);
     }
 }
static int tcmi_slot_empty (struct tcmi_slot * self) inline static
<<public>> Checks if the slot is empty.
Parameters
*self - pointer to this slot instance
Returns
1 - when the slot is empty
Definition at line 217 of file tcmi_slot.h.
References self.
Referenced by __tcmi_slot_remove(), and tcmi_slotvec_put().
 {
     return hlist_empty(&self->head);
 }
static u_int tcmi_slot_index (struct tcmi_slot * self) inline static
<<public>> Slot index accessor.
Parameters
*self - pointer to this slot instance
Returns
slot index
Definition at line 228 of file tcmi_slot.h.
Referenced by tcmi_ccnman_listen(), tcmi_ccnman_process_sock(), tcmi_man_emig_npm(), tcmi_man_emig_ppm_p(), tcmi_man_fork(), tcmi_man_send_generic_user_message(), tcmi_migman_slot_index(), and tcmi_penman_connect().
 {
     return self->index;
 }
static void tcmi_slot_init (struct tcmi_slot * self, u_int index, struct list_head * unused_slots, struct list_head * used_slots, spinlock_t * lock) inline static
Initializes a slot.
Assigns it an index and appends it to the tail of the unused_slots list. The slot keeps track whether it is empty or not on its own. That's why we store the unused_slots and used_slots heads inside the slot. The spinlock protects those lists from concurrent modification.
Parameters
*self - pointer to this slot instance
index - slot index
unused_slots - head of the list of unused slots
used_slots - head of the list of used slots
*lock - pointer to the lock that will be used when synchronizing access to the slotvector where the slot resides.
Definition at line 198 of file tcmi_slot.h.
References self.
Referenced by tcmi_slotvec_new().
 {
     self->index = index;
     INIT_LIST_HEAD(&self->slot_list);
     INIT_HLIST_HEAD(&self->head);
     self->unused_slots = unused_slots;
     self->used_slots = used_slots;
     self->s_lock = lock;
     list_add_tail(&self->slot_list, unused_slots);
 }
static void tcmi_slot_insert (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Inserts a new node into the slot.
It is necessary to acquire a lock to prevent races with other threads. The slot is also moved into the used_slots list. This might be considered as overhead operation if the slot is already in that list, but it simplifies the design. Otherwise we would need an extra flag indicating which list it is currently in. Also the operation is O(1), so the penalty is rather small.
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be added
Definition at line 290 of file tcmi_slot.h.
References mdbg, self, tcmi_slot_lock(), tcmi_slot_move(), and tcmi_slot_unlock().
Referenced by tcmi_ccnman_listen(), tcmi_ccnman_process_sock(), tcmi_penman_connect(), tcmi_slotvec_insert_at(), and tcmi_slotvec_insert_at_empty().
 {
     tcmi_slot_lock(self);
     mdbg(INFO4, "Inserted node %p into slot %d", node, self->index);
     INIT_HLIST_NODE(node);
     hlist_add_head(node, &self->head);
     tcmi_slot_move(self, self->used_slots);
     tcmi_slot_unlock(self);
 }
static void tcmi_slot_lock (struct tcmi_slot * self) inline static
<<public>> Locks the slot data.
Spin lock used - no sleeping allowed!
Parameters
*self - pointer to this slot instance
Definition at line 239 of file tcmi_slot.h.
References self.
Referenced by tcmi_migman_unhash(), tcmi_slot_insert(), tcmi_slot_remove(), and tcmi_slot_remove_safe().
 {
     // Have to be irqsave to avoid possible safe->unsafe conflict in forks
     spin_lock_irqsave(self->s_lock, self->lock_flags);
 }
static void tcmi_slot_move (struct tcmi_slot * self, struct list_head * head) inline static
<<private>> Moves a slot into the specified list.
Parameters
*self - pointer to this slot instance
head - list where the slot should be moved
Definition at line 261 of file tcmi_slot.h.
References self.
Referenced by tcmi_slot_insert(), and tcmi_slot_move_unused().
 {
     list_move(&self->slot_list, head);
 }
static void tcmi_slot_move_tail (struct tcmi_slot * self, struct list_head * head) inline static
<<private>> Moves a slot to the tail of the specified list.
Parameters
*self - pointer to this slot instance
head - list where the slot should be moved
Definition at line 272 of file tcmi_slot.h.
References self.
 {
     list_move_tail(&self->slot_list, head);
 }
static void tcmi_slot_move_unused (struct tcmi_slot * self) inline static
<<public>> Moves a slot among unused_slots.
Parameters
*self - pointer to this slot instance
Definition at line 306 of file tcmi_slot.h.
References self, and tcmi_slot_move().
Referenced by __tcmi_slot_remove(), tcmi_ccnman_listen(), and tcmi_man_release_migmanslot().
 {
     tcmi_slot_move(self, self->unused_slots);
 }
static void tcmi_slot_remove (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Removes a given node from a slot.
No check is performed, whether the node belongs to this slot. After locking the slot, the work is delegated to __tcmi_slot_remove().
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be removed
Definition at line 339 of file tcmi_slot.h.
References __tcmi_slot_remove(), self, tcmi_slot_lock(), and tcmi_slot_unlock().
Referenced by tcmi_migman_remove_task(), and tcmi_transaction_put().
 {
     if (self) {
         if ( spin_is_locked(self->s_lock) ) {
             __tcmi_slot_remove(self, node);
         } else {
             tcmi_slot_lock(self);
             __tcmi_slot_remove(self, node);
             tcmi_slot_unlock(self);
         }
     }
 }
static void tcmi_slot_remove_safe (struct tcmi_slot * self, tcmi_slot_node_t * node) inline static
<<public>> Removes a given node from a slot.
A check is performed whether the node belongs to this slot. The work is then delegated to tcmi_slot_remove().
Parameters
*self - pointer to this slot instance
*node - pointer to the node to be removed
Definition at line 361 of file tcmi_slot.h.
References __tcmi_slot_remove(), mdbg, self, tcmi_slot_for_each, tcmi_slot_lock(), and tcmi_slot_unlock().
 {
     struct hlist_node *slot_node;
     int found = 0;
     if (self) {
         tcmi_slot_lock(self);
         tcmi_slot_for_each(slot_node, self) {
             if (slot_node == node) {
                 found = 1;
                 break;
             }
         }
         if (found) {
             mdbg(INFO4, "Found the node %p in slot %d", node, self->index);
             __tcmi_slot_remove(self, node);
         }
         tcmi_slot_unlock(self);
     }
 }
static void tcmi_slot_unlock (struct tcmi_slot * self) inline static
<<public>> Unlocks the instance data
Parameters
*self - pointer to this slot instance
Definition at line 250 of file tcmi_slot.h.
References self.
Referenced by tcmi_migman_unhash(), tcmi_slot_insert(), tcmi_slot_remove(), and tcmi_slot_remove_safe().
 {
     spin_unlock_irqrestore(self->s_lock, self->lock_flags);
 }