Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/task/tcmi_task.c File Reference
tcmi_task.c File Reference
#include <linux/unistd.h>
#include <asm/uaccess.h>
#include <linux/kmod.h>
#include <linux/hardirq.h>
#include <linux/syscalls.h>
#include "tcmi_task.h"
#include <tcmi/manager/tcmi_migman.h>
#include "tcmi_taskhelper.h"
Macros
#define __KERNEL_SYSCALLS__
#define TCMI_TASK_PRIVATE
#define TRANSACTION_ORDER 8
TODO: Move this somewhere to arch.
Functions
int tcmi_task_init (struct tcmi_task *self, pid_t local_pid, struct tcmi_migman *migman, struct kkc_sock *sock, struct tcmi_ctlfs_entry *d_migproc, struct tcmi_ctlfs_entry *d_migman, struct tcmi_task_ops *ops)
Initializes the task.
void tcmi_task_put (struct tcmi_task *self)
<<public>> Releases the instance.
void tcmi_task_submit_method (struct tcmi_task *self, tcmi_method_t *method, void *data, int size)
<<public>> Submits a method for execution.
void tcmi_task_flush_and_submit_method (struct tcmi_task *self, tcmi_method_t *method, void *data, int size)
<<public>> Flushes all pending methods in the queue submits a method for execution.
int tcmi_task_process_methods (struct tcmi_task *self)
<<public>> Processes all methods in the queue.
int tcmi_task_process_msg (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Processes one message from the message queue.
int tcmi_task_send_message (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Sends a message to peer task.
int tcmi_task_emigrate_ppm_p (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Emigrates a task to a PEN
int tcmi_task_migrateback_ppm_p (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Migrates a task back to CCN - PPM w/ physical checkpoint.
int tcmi_task_emigrate_ppm_v (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Emigrates a task to a PEN
int tcmi_task_migrateback_ppm_v (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Migrates a task back to CCN - PPM w/ virtual checkpoint.
int tcmi_task_emigrate_npm (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Emigrates a task to a PEN
int tcmi_task_migrateback_npm (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Migrates a task back to CCN - NPM.
int tcmi_task_exit (void *self, struct tcmi_method_wrapper *wr)
<<public>> Called from method queue - Exits a task.
static int tcmi_task_copy_strings (char ***dst, char **src)
<<private>> Class method - copies an array of strings terminated by NULL string (standard argv/envp format) into the destination array.
int tcmi_task_prepare_execve (struct tcmi_task *self, char *file, char **argv, char **envp)
<<public>> Prepares execution of a file given the arrays of arguments and environment.
int tcmi_task_execve (void *self, struct tcmi_method_wrapper *wr)
<<public>> Executes the file that has been previously setup for execution.
static int tcmi_task_show_remote_pid (void *obj, void *data)
<<private>> Read method for the TCMI ctlfs - reports remote PID.
static void tcmi_task_release_execve_context (struct tcmi_task *self)
<<private>> Releases the execve context (execve file, argv, envp) Since the argv/envp have allocated a linear chunks of memory (including all strings) we need to issue only 1 kfree/vfree for each and don't need to scan the array releasing each string separate.
int tcmi_task_deliver_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<public>> Delivers a specified message.
u_int32_t tcmi_task_migman_id (struct tcmi_task *self)
<<public>> Accessor of id of the migration manager associated with this task.
u_int tcmi_task_migman_slot_index (struct tcmi_task *self)
<<public>> Accessor of vector slot index of the migration manager associated with this task.
Variables
int errno = 0
Macro Definition Documentation
#define __KERNEL_SYSCALLS__
Definition at line 33 of file tcmi_task.c.
#define TCMI_TASK_PRIVATE
Definition at line 42 of file tcmi_task.c.
#define TRANSACTION_ORDER 8
TODO: Move this somewhere to arch.
2^8 elements in the transaction process hash
Definition at line 77 of file tcmi_task.c.
Referenced by tcmi_task_init().
Function Documentation
static int tcmi_task_copy_strings (char *** dst, char ** src) inline static
<<private>> Class method - copies an array of strings terminated by NULL string (standard argv/envp format) into the destination array.
Destination array are released and new memory for the strings is allocated. The idea how the array in the task will be organized is sketched below.
Parameters
***dst - pointer(*) to the destination array(**) (should be &self->argv or &self->envp
**src - source array of strings
Returns
0 upon success
Definition at line 666 of file tcmi_task.c.
References mdbg.
Referenced by tcmi_task_prepare_execve().
 {
     /* auxiliary storage when computing argv/envp length's */
     char **tmp_src = src;
     /* refers to current string being processed */
     char *src_data;
     /* used when copying the strings over */
     char **new_src;
     /* number of elements and total size of all elements in bytes */
     unsigned int src_len = 0, src_size = 0;
     /* calculate the number of elements and total array size, so
      * that we can allocate it all at once */
     for(;*tmp_src != NULL;src_len++, src_size += strlen(*tmp_src) + 1, tmp_src++);
     /* account for the terminating NULL */
     src_len++;
     mdbg(INFO3, "src count %d, src size %d", src_len, src_size);
     if (!(new_src = *dst = (char**)kmalloc((sizeof(char*) * src_len) + src_size, GFP_KERNEL))) {
         mdbg(ERR3, "Can't allocate memory for src array!!");
         goto exit0;
     }
     /* copy the src array over */
     /* compute the start of the data section for src */
     src_data = (char*) *dst + (sizeof(char*) * src_len);
     for (tmp_src = src; *tmp_src != NULL; tmp_src++, new_src++) {
         mdbg(INFO4, "Copying '%s', length %lu", *tmp_src, (unsigned long)strlen(*tmp_src));
         strcpy(src_data, *tmp_src);
         *new_src = src_data;
         src_data += strlen(*tmp_src) + 1;
     }
     *new_src = NULL; /* each array terminated by NULL as required by execve */
     return 0;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static void tcmi_task_release_execve_context (struct tcmi_task * self) static
<<private>> Releases the execve context (execve file, argv, envp) Since the argv/envp have allocated a linear chunks of memory (including all strings) we need to issue only 1 kfree/vfree for each and don't need to scan the array releasing each string separate.
Releasing is atomic as this method is also used when preparing a new execve context (tcmi_task_prepare_execve()).
Parameters
*self - pointer to this task instance
Definition at line 873 of file tcmi_task.c.
References mdbg, self, and tcmi_task_local_pid().
Referenced by tcmi_task_prepare_execve(), and tcmi_task_put().
 {
     char *tmp1, **tmp2;
     mdbg(INFO4, "Destroying TCMI task execve context(%p, %p, %p) PID=%d, %p",
          self->ckpt_pathname, self->argv, self->envp, tcmi_task_local_pid(self), self);
     tmp1 = self->ckpt_pathname;
     self->ckpt_pathname = NULL;
     kfree(tmp1);
     tmp2 = self->argv;
     self->argv = NULL;
     kfree(tmp2);
     tmp2 = self->envp;
     self->envp = NULL;
     kfree(tmp2);
 }
static int tcmi_task_show_remote_pid (void * obj, void * data) static
<<private>> Read method for the TCMI ctlfs - reports remote PID.
For a shadow process, the remote PID is the identifier of the guest process on PEN and vica versa.
Parameters
*obj - pointer to this task instance
*data - pointer where the PID is to be stored.
Returns
0 upon success
Definition at line 852 of file tcmi_task.c.
References tcmi_task::remote_pid, TCMI_TASK, and tcmi_task_remote_pid().
Referenced by tcmi_task_init().
 {
     struct tcmi_task *self = TCMI_TASK(obj);
     int *remote_pid = (int*) data;
     *remote_pid = tcmi_task_remote_pid(self);
     return 0;
 }
Variable Documentation
int errno = 0
Definition at line 32 of file tcmi_task.c.