Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/manager/tcmi_man.c File Reference
tcmi_man.c File Reference
#include <linux/types.h>
#include <linux/random.h>
#include <linux/kthread.h>
#include <tcmi/ctlfs/tcmi_ctlfs.h>
#include <tcmi/lib/tcmi_sock.h>
#include <tcmi/task/tcmi_task.h>
#include "tcmi_ccnmigman.h"
#include <kkc/kkc.h>
#include "tcmi_man.h"
#include <dbg.h>
Macros
#define TCMI_MAN_PRIVATE
#define MAX_NODES 40
maximum number of connected nodes
Functions
int tcmi_man_init (struct tcmi_man *self, struct tcmi_ctlfs_entry *root, struct tcmi_man_ops *ops, const char *man_dirname)
<<public>> Initializes the TCMI manager.
static void tcmi_man_wait_for_migmans_termination (struct tcmi_man *self)
Waits for all migration managers to terminate.
void tcmi_man_shutdown (struct tcmi_man *self)
<<public>> The manager is shutdown exactly in this order:
static int tcmi_man_do_send_generic_user_message (struct tcmi_man *self, int target_slot_index, int user_data_size, char *user_data, struct tcmi_migman *migman)
int tcmi_man_send_generic_user_message (struct tcmi_man *self, int target_slot_index, int user_data_size, char *user_data)
<<public>> Send generic user message
static int tcmi_man_init_ctlfs_dirs (struct tcmi_man *self, struct tcmi_ctlfs_entry *root, const char *man_dirname)
<<private>> Creates the directories as described in here .
static int tcmi_man_init_ctlfs_files (struct tcmi_man *self)
<<private>> Creates the static files described here .
static void tcmi_man_stop_ctlfs_dirs (struct tcmi_man *self)
<<private>> Destroys all ctlfs directories, first the singleton instance specific directories are destroyed
static void tcmi_man_stop_ctlfs_files (struct tcmi_man *self)
<<private>> Unregisters and releases all control files.
static int tcmi_man_init_migration (struct tcmi_man *self)
<<private>>.
static struct tcmi_migman * tcmi_man_get_non_shutdowning_migman (struct tcmi_man *self)
Finds and returns arbitrary migration manager that is either in INIT or CONNECTED state.
static void tcmi_man_stop_migration (struct tcmi_man *self)
<<private>> Stops all migration components.
static int tcmi_man_stop (void *obj, void *data)
<<private>> If the user called this method with parameter > 0, the TCMI manager stops the migration framework.
static int tcmi_man_emig_ppm_p (void *obj, void *data)
<<private>> TCMI ctlfs write method - emigration PPM P What needs to be done:
int tcmi_man_emig_npm (struct tcmi_man *self, pid_t pid, u_int32_t migman_id, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
<<public>> Method that performs non-preemtive migration
int tcmi_man_fork (struct tcmi_man *self, struct task_struct *parent, struct task_struct *child)
<<public>> Method that performs task fork
static int tcmi_man_mig_home_ppm_p (void *obj, void *data)
<<private>> TCMI ctlfs write method - migration home.
Macro Definition Documentation
#define MAX_NODES 40
maximum number of connected nodes
Definition at line 49 of file tcmi_man.c.
Referenced by tcmi_man_init().
#define TCMI_MAN_PRIVATE
Definition at line 43 of file tcmi_man.c.
Function Documentation
static int tcmi_man_do_send_generic_user_message (struct tcmi_man * self, int target_slot_index, int user_data_size, char * user_data, struct tcmi_migman * migman) inline static
Definition at line 155 of file tcmi_man.c.
References mdbg, self, tcmi_generic_user_msg_new_tx(), tcmi_migman_sock(), TCMI_MSG, tcmi_msg_put(), and tcmi_msg_send_anonymous().
Referenced by tcmi_man_send_generic_user_message().
{
     int err = 0;
     struct tcmi_msg* msg;
     // TODO: Node id is passed incorrectly, but on the other hand this node id is complete bullshit and should be likely removed, right?
     if ( !( msg = TCMI_MSG(tcmi_generic_user_msg_new_tx(self->id, user_data, user_data_size)) ) ) {
         mdbg(ERR3, "Error creating response message");
         return - ENOMEM;        ;
     }
     if ((err = tcmi_msg_send_anonymous(msg, tcmi_migman_sock(migman)))) {
         mdbg(ERR3, "Error sending user message %d", err);
         err = -EINVAL;
     }
     tcmi_msg_put(msg);
     return err;
 }
static int tcmi_man_emig_ppm_p (void * obj, void * data) static
<<private>> TCMI ctlfs write method - emigration PPM P What needs to be done:
find the requested migration manager
call instance specific emigration method.
Parameters
*obj - pointer to a particular TCMI manager singleton instance
*data - an array of two integers first contains PID, second one contains the desired manager identifier as it appears in ctlfs. It is the name of its directory.
Returns
0 upon success
Definition at line 455 of file tcmi_man.c.
References mdbg, tcmi_migman::node, pid, self, TCMI_MAN, tcmi_migman_get(), tcmi_migman_put(), tcmi_slot_find_first, tcmi_slot_index(), tcmi_slotvec_at(), tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_man_init_ctlfs_files().
 {
     int err = 0;
     pid_t pid = *((int *)data);
     u_int32_t migman_id = *(((int *)data) + 1);
     struct tcmi_man *self = TCMI_MAN(obj);
     struct tcmi_slot *slot;
     struct tcmi_migman *migman = NULL;
     mdbg(INFO2, "Emigration request PID %d, migration manager %d",
          pid, migman_id);
     /* lookup the migration manager first */
     tcmi_slotvec_lock(self->mig_mans);
     if (!(slot = tcmi_slotvec_at(self->mig_mans, migman_id))) {
         mdbg(ERR3, "Invalid migration manager identifier %d", migman_id);
         goto exit0;
     }
     /* there is always only one mig man per slot */
     tcmi_slot_find_first(migman, slot, node);
     /* Slot might exist, but it might still be empty*/
     if (!tcmi_migman_get(migman)) {
         mdbg(ERR3, "No migration manager in the slot(%d)", tcmi_slot_index(slot));
         goto exit0;
     }
     tcmi_slotvec_unlock(self->mig_mans);
     if (self->ops->emigrate_ppm_p)
         err = self->ops->emigrate_ppm_p(pid, migman);
     /* release the migration manager */
     tcmi_migman_put(migman);
     return err;
     /* error handling */
  exit0:
     tcmi_slotvec_unlock(self->mig_mans);
     return -EINVAL;
 }
static struct tcmi_migman* tcmi_man_get_non_shutdowning_migman (struct tcmi_man * self) static read
Finds and returns arbitrary migration manager that is either in INIT or CONNECTED state.
Definition at line 372 of file tcmi_man.c.
References self, TCMI_MIGMAN_CONNECTED, TCMI_MIGMAN_INIT, tcmi_migman_state(), tcmi_slot_entry, tcmi_slot_for_each, tcmi_slotvec_for_each_used_slot, tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_man_stop_migration().
{
     struct tcmi_slot *slot;
     tcmi_slot_node_t* node;
     struct tcmi_migman *migman = NULL;
     tcmi_migman_state_t migman_state;
     tcmi_slotvec_lock(self->mig_mans);
     tcmi_slotvec_for_each_used_slot(slot, self->mig_mans) {
         tcmi_slot_for_each(node, slot) {
             migman = tcmi_slot_entry(node, struct tcmi_migman, node);
             migman_state = tcmi_migman_state(migman);
             if ( migman_state == TCMI_MIGMAN_INIT || migman_state == TCMI_MIGMAN_CONNECTED ) {
             goto found;
             }
             migman = NULL;
         };
     };
 found:
     tcmi_slotvec_unlock(self->mig_mans);
     return migman;
 }
static int tcmi_man_init_ctlfs_dirs (struct tcmi_man * self, struct tcmi_ctlfs_entry * root, const char * man_dirname) static
<<private>> Creates the directories as described in here .
It is necessary to get the current root directory of the TCMI ctlfs first. So that it won't get unlinked under us.
Parameters
*self - a particular manager singleton instance
*root - root directory of the filesystem, where all entries are to be created
*man_dirname - name for the main directory of the manager (e.g. ccn or pen)
Returns
0 upon success
Definition at line 227 of file tcmi_man.c.
References mdbg, self, tcmi_ctlfs_dir_new(), tcmi_ctlfs_entry_put(), and TCMI_PERMS_DIR.
Referenced by tcmi_man_init().
 {
     mdbg(INFO4, "Creating directories");
     if (!root)
         goto exit0;
     if (!(self->d_man = tcmi_ctlfs_dir_new(root, TCMI_PERMS_DIR, man_dirname)))
         goto exit0;
     if (!(self->d_nodes =
           tcmi_ctlfs_dir_new(self->d_man, TCMI_PERMS_DIR, "nodes")))
         goto exit1;
     if (!(self->d_mig =
           tcmi_ctlfs_dir_new(self->d_man, TCMI_PERMS_DIR, "mig")))
         goto exit2;
     if (!(self->d_migproc =
           tcmi_ctlfs_dir_new(self->d_mig, TCMI_PERMS_DIR, "migproc")))
         goto exit3;
     if (self->ops->init_ctlfs_dirs && self->ops->init_ctlfs_dirs()) {
         mdbg(ERR3, "Failed to create specific ctlfs directories!");
         goto exit4;
     }
     return 0;
     /* error handling */
  exit4:
     tcmi_ctlfs_entry_put(self->d_migproc);
  exit3:
     tcmi_ctlfs_entry_put(self->d_mig);
  exit2:
     tcmi_ctlfs_entry_put(self->d_nodes);
  exit1:
     tcmi_ctlfs_entry_put(self->d_man);
  exit0:
     return -EINVAL;
 }
static int tcmi_man_init_ctlfs_files (struct tcmi_man * self) static
<<private>> Creates the static files described here .
Parameters
*self - a particular manager singleton instance
Returns
0 upon success
Definition at line 276 of file tcmi_man.c.
References mdbg, self, tcmi_ctlfs_entry_put(), tcmi_ctlfs_file_unregister(), tcmi_ctlfs_intfile_new(), tcmi_man_emig_ppm_p(), tcmi_man_mig_home_ppm_p(), tcmi_man_stop(), and TCMI_PERMS_FILE_W.
Referenced by tcmi_man_init().
 {
     mdbg(INFO4, "Creating files");
     if (!(self->f_stop =
           tcmi_ctlfs_intfile_new(self->d_man, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_man_stop,
                      sizeof(int), "stop")))
         goto exit0;
     if (!(self->f_emig_ppm_p =
           tcmi_ctlfs_intfile_new(self->d_mig, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_man_emig_ppm_p,
                      sizeof(int) * 2, "emigrate-ppm-p")))
         goto exit1;
     if (!(self->f_mig_home_ppm_p =
           tcmi_ctlfs_intfile_new(self->d_mig, TCMI_PERMS_FILE_W,
                      self, NULL, tcmi_man_mig_home_ppm_p,
                      sizeof(int), "migrate-home")))
         goto exit2;
     if (self->ops->init_ctlfs_files && self->ops->init_ctlfs_files()) {
         mdbg(ERR3, "Failed to create specific ctlfs files!");
         goto exit3;
     }
     return 0;
     /* error handling */
  exit3:
     tcmi_ctlfs_file_unregister(self->f_mig_home_ppm_p);
     tcmi_ctlfs_entry_put(self->f_mig_home_ppm_p);
  exit2:
     tcmi_ctlfs_file_unregister(self->f_emig_ppm_p);
     tcmi_ctlfs_entry_put(self->f_emig_ppm_p);
  exit1:
     tcmi_ctlfs_file_unregister(self->f_stop);
     tcmi_ctlfs_entry_put(self->f_stop);
  exit0:
     return -EINVAL;
 }
static int tcmi_man_init_migration (struct tcmi_man * self) static
<<private>>.
Parameters
*self - a particular manager singleton instance
Returns
0 upon success
Definition at line 364 of file tcmi_man.c.
References mdbg.
Referenced by tcmi_man_init().
 {
     mdbg(INFO3, "Initializing migration components");
     return 0;
 }
static int tcmi_man_mig_home_ppm_p (void * obj, void * data) static
<<private>> TCMI ctlfs write method - migration home.
Migration home requires delegating work to the instance specific method once we extract the requested PID.
Parameters
*obj - pointer to a particular TCMI manager singleton instance
*data - contains PID that is to be migrated home
Returns
0 upon success
Definition at line 614 of file tcmi_man.c.
References mdbg, self, and TCMI_MAN.
Referenced by tcmi_man_init_ctlfs_files().
 {
     int err = 0;
     pid_t pid = *((int *)data);
     struct tcmi_man *self = TCMI_MAN(obj);
     mdbg(INFO2, "Migration home request for PID %d", pid);
     if (self->ops->migrate_home_ppm_p)
         err = self->ops->migrate_home_ppm_p(pid);
     return err;
 }
static int tcmi_man_stop (void * obj, void * data) static
<<private>> If the user called this method with parameter > 0, the TCMI manager stops the migration framework.
This results in migrating all processes back to CCN and terminating all migration managers.
Parameters
*obj - pointer to a particular TCMI manager singleton instance
*data - if the value that it points to is >0, the action is taken
Returns
always 0 (success)
NOTE: What is a purpose of this method? There is no inverse operation to stop, so is that essentially different from shutdown? ms
Definition at line 428 of file tcmi_man.c.
References mdbg, self, TCMI_MAN, and tcmi_man_stop_migration().
Referenced by tcmi_man_init_ctlfs_files().
 {
     int stop = *((int *)data);
     struct tcmi_man *self = TCMI_MAN(obj);
     mdbg(INFO3, "TCMI manager stop request, action = %d", stop);
     if (stop) {
         /* TODO: Stop operations are called just here, but shouldn't we call them as well on shutdown? */
         if (self->ops->stop)
             self->ops->stop();
         tcmi_man_stop_migration(self);
     }
     return 0;
 }
static void tcmi_man_stop_ctlfs_dirs (struct tcmi_man * self) static
<<private>> Destroys all ctlfs directories, first the singleton instance specific directories are destroyed
Parameters
*self - a particular manager singleton instance
Definition at line 324 of file tcmi_man.c.
References mdbg, self, and tcmi_ctlfs_entry_put().
Referenced by tcmi_man_init(), and tcmi_man_shutdown().
 {
     mdbg(INFO3, "Destroying  TCMI manager ctlfs directories");
     if (self->ops->stop_ctlfs_dirs)
         self->ops->stop_ctlfs_dirs();
     tcmi_ctlfs_entry_put(self->d_migproc);
     tcmi_ctlfs_entry_put(self->d_mig);
     tcmi_ctlfs_entry_put(self->d_nodes);
     tcmi_ctlfs_entry_put(self->d_man);
 }
static void tcmi_man_stop_ctlfs_files (struct tcmi_man * self) static
<<private>> Unregisters and releases all control files.
Parameters
*self - a particular manager singleton instance
Definition at line 341 of file tcmi_man.c.
References mdbg, self, tcmi_ctlfs_entry_put(), and tcmi_ctlfs_file_unregister().
Referenced by tcmi_man_shutdown().
 {
     mdbg(INFO3, "Destroying  TCMI manager ctlfs files");
     if (self->ops->stop_ctlfs_files)
         self->ops->stop_ctlfs_files();
     tcmi_ctlfs_file_unregister(self->f_stop);
     tcmi_ctlfs_entry_put(self->f_stop);
     tcmi_ctlfs_file_unregister(self->f_emig_ppm_p);
     tcmi_ctlfs_entry_put(self->f_emig_ppm_p);
     tcmi_ctlfs_file_unregister(self->f_mig_home_ppm_p);
     tcmi_ctlfs_entry_put(self->f_mig_home_ppm_p);
 }
static void tcmi_man_stop_migration (struct tcmi_man * self) static
<<private>> Stops all migration components.
Terminates all migration managers, they are responsible for migrating all processes to the home node or a another execution node.
Parameters
*self - a particular manager singleton instance
Definition at line 404 of file tcmi_man.c.
References mdbg, tcmi_man_get_non_shutdowning_migman(), and tcmi_migman_stop().
Referenced by tcmi_man_init(), tcmi_man_shutdown(), and tcmi_man_stop().
 {
     struct tcmi_migman *migman = tcmi_man_get_non_shutdowning_migman(self);
     while (migman) {
         mdbg(INFO3, "Requesting migration manager shutdown.");
         tcmi_migman_stop(migman);
         migman = tcmi_man_get_non_shutdowning_migman(self);
     }
 }
static void tcmi_man_wait_for_migmans_termination (struct tcmi_man * self) static
Waits for all migration managers to terminate.
Note: We perform wait by active polling of count of remaining migmas (100ms) interval. In case there were no remote processes running, there would be no wait as all migmans were terminated synchronously. In case there were remote processes, the waiting time for their migration back would be likely in order of seconds, so 100ms does not add much latency In case somebody volunteers, the code could be migrated to notify/wait patter to get rid of polling
Definition at line 113 of file tcmi_man.c.
References self, tcmi_slotvec_empty(), tcmi_slotvec_lock(), and tcmi_slotvec_unlock().
Referenced by tcmi_man_shutdown().
{
     int is_empty;
     tcmi_slotvec_lock(self->mig_mans);
     is_empty = tcmi_slotvec_empty(self->mig_mans);
     tcmi_slotvec_unlock(self->mig_mans);
     while (!is_empty) {
         set_current_state(TASK_INTERRUPTIBLE);
         schedule_timeout(msecs_to_jiffies(100));
         tcmi_slotvec_lock(self->mig_mans);
         is_empty = tcmi_slotvec_empty(self->mig_mans);
         tcmi_slotvec_unlock(self->mig_mans);
     }
 }