Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/task/tcmi_guesttask.c File Reference
tcmi_guesttask.c File Reference
#include <tcmi/comm/tcmi_messages_dsc.h>
#include <tcmi/migration/tcmi_migcom.h>
#include <tcmi/manager/tcmi_migman.h>
#include "tcmi_taskhelper.h"
#include "tcmi_guesttask.h"
#include <proxyfs/proxyfs_helper.h>
#include <director/director.h>
Macros
#define TCMI_GUESTTASK_PRIVATE
Functions
struct tcmi_task * tcmi_guesttask_new (pid_t local_pid, struct tcmi_migman *migman, struct kkc_sock *sock, struct tcmi_ctlfs_entry *d_migproc, struct tcmi_ctlfs_entry *d_migman)
<<public>> Instance constructor.
static int tcmi_guesttask_process_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<private>> Processes a message specified by the caller.
static int tcmi_guesttask_emigrate_p (struct tcmi_task *self)
<<private>> Emigrates a task to a PEN.
static int tcmi_guesttask_migrateback_p (struct tcmi_task *self, struct tcmi_npm_params *npm_params)
Internal helper method for performing both npm/ppm physical migration back to ccn.
static int tcmi_guesttask_migrateback_ppm_p (struct tcmi_task *self)
<<private>> Migrates a task back to CCN using PPM with physical checkpoint image.
int tcmi_guesttask_migrateback_npm (struct tcmi_task *self, struct tcmi_npm_params *npm_params)
Handles non-preemptive migration back of guest tasks.
static int tcmi_guesttask_exit (struct tcmi_task *self, long code)
<<private>> Exit notification for the shadow on CCN.
static int tcmi_guesttask_do_signal (struct tcmi_task *self, unsigned long signr, siginfo_t *info)
<<private>> Processes a specified signal.
static int tcmi_guesttask_process_p_emigrate_msg (struct tcmi_task *self, struct tcmi_msg *m)
<<private>> Processes the physical emigrate process message (both NPM and PPM)
int tcmi_guesttask_post_fork (struct tcmi_task *self, struct tcmi_task *child, long fork_result, pid_t remote_child_pid)
<<public>> Called on post-fork hook on guest task that was forked (parent)
int tcmi_guesttask_post_fork_set_tid (void *self, struct tcmi_method_wrapper *wr)
<<public>> Used to set proper tid after a new process was forked.
static enum tcmi_task_type tcmi_guesttask_get_type (void)
Return type of task.
Variables
static struct tcmi_task_ops guesttask_ops
TCMI task operations that support polymorphism.
Macro Definition Documentation
#define TCMI_GUESTTASK_PRIVATE
Definition at line 37 of file tcmi_guesttask.c.
Function Documentation
static int tcmi_guesttask_do_signal (struct tcmi_task * self, unsigned long signr, siginfo_t * info) static
<<private>> Processes a specified signal.
Currently only SIGKILL signal is handled that causes the task to terminate returned status for the method pump - TCMI_TASK_KILL_ME. Final solution should do a full signal handling and communicate with the shadow too.
Parameters
*self - pointer to this task instance
signr - signal that is to be processed
*info - info for signal to be processed
Returns
TCMI_TASK_KEEP_PUMPING on any signal but SIGKILL
Definition at line 272 of file tcmi_guesttask.c.
References mdbg, TCMI_TASK_KEEP_PUMPING, and tcmi_task_set_exit_code().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     mdbg(INFO2, "Stub is processing signal %lu", signr);
     if (signr == SIGKILL || signr == SIGQUIT || signr == SIGINT) {
         tcmi_task_set_exit_code(self, signr);
         // We have to return keep pumping, because following do_exit call will invoke exit hook and it should be handled by the method pump!
         res = TCMI_TASK_KEEP_PUMPING;
     }
     return res;
 }
static int tcmi_guesttask_emigrate_p (struct tcmi_task * self) static
<<private>> Emigrates a task to a PEN.
Parameters
*self - pointer to this task instance
Returns
result of the task specific emigrate method or TCMI_TASK_KEEP_PUMPING
Definition at line 136 of file tcmi_guesttask.c.
References TCMI_TASK_KEEP_PUMPING.
 {
     int res = TCMI_TASK_KEEP_PUMPING;
 /*  struct tcmi_guesttask *self_tsk = TCMI_GUESTTASK(self);*/
     return res;
 }
static int tcmi_guesttask_exit (struct tcmi_task * self, long code) static
<<private>> Exit notification for the shadow on CCN.
This method is scheduled by the exit system call hook that also invokes the migration mode handler. It sends an exit process control message to the shadow. No response is expected, the message content is the exit code. The method terminates with TCMI_TASK_REMOVE_AND_LET_ME_GO - explained below
Returns
TCMI_TASK_REMOVE_AND_LET_ME_GO, so that the migration component destroys this task. It doesn't itentionally return TCMI_TASK_KILL_ME as it would cause another round of exit, this time using complete_and_exit()
Sync proxyfs files only if peer is alive, else this call makes no sense
Definition at line 237 of file tcmi_guesttask.c.
References mdbg, proxyfs_sync_files_on_exit(), self, tcmi_exit_procmsg_new_tx(), tcmi_msg_put(), tcmi_task_remote_pid(), TCMI_TASK_REMOVE_AND_LET_ME_GO, and tcmi_task_send_anonymous_msg().
 {
     struct tcmi_msg *m;
     /** Sync proxyfs files only if peer is alive, else this call makes no sense */
     if ( !self->peer_lost )
         proxyfs_sync_files_on_exit();
     mdbg(INFO2, "Stub process '%s' local PID=%d terminating",
           current->comm, current->pid);
     if (!(m = tcmi_exit_procmsg_new_tx(tcmi_task_remote_pid(self), code))) {
         mdbg(ERR3, "Can't create error message");
         goto exit0;
     }
     /* send it as anonymous since no response is expected. */
     tcmi_task_send_anonymous_msg(self, m);
     /* dispose the message not needed anymore. */
     tcmi_msg_put(m);
  exit0:
     return TCMI_TASK_REMOVE_AND_LET_ME_GO;
 }
static enum tcmi_task_type tcmi_guesttask_get_type (void) static
Return type of task.
Only for setting task type to kernel task_struct. Polymorphism cannot be used in kernel, bacause tcmi_task is defined outside of kernel.
Definition at line 421 of file tcmi_guesttask.c.
{
     return guest;
 }
static int tcmi_guesttask_migrateback_p (struct tcmi_task * self, struct tcmi_npm_params * npm_params) static
Internal helper method for performing both npm/ppm physical migration back to ccn.
Returns
0 on success, error code otherwise
Definition at line 149 of file tcmi_guesttask.c.
References director_migrated_home(), mdbg, req, tcmi_msg_put(), tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx(), tcmi_task_check_peer_lost(), tcmi_task_ckpt_name(), tcmi_task_local_pid(), tcmi_task_remote_pid(), tcmi_task_send_anonymous_msg(), tcmi_taskhelper_checkpoint(), and tcmi_taskhelper_flushfiles().
Referenced by tcmi_guesttask_migrateback_ppm_p().
{
     struct tcmi_msg *req;
     mdbg(INFO2, "Process '%s' - guest local PID %d, migrating back (npm params: %p)", current->comm, tcmi_task_local_pid(self), npm_params);
     if (tcmi_taskhelper_checkpoint(self, npm_params) < 0) {
         mdbg(ERR3, "Failed to create a checkpoint");
         goto exit0;
     }
     tcmi_taskhelper_flushfiles();
     if (!(req = tcmi_ppm_p_migr_back_guestreq_procmsg_new_tx(tcmi_task_remote_pid(self), tcmi_task_ckpt_name(self)))) {
         mdbg(ERR3, "Error creating a migration back message");
         goto exit0;
     }
     if (tcmi_task_check_peer_lost(self, tcmi_task_send_anonymous_msg(self, req)) < 0) {
         mdbg(ERR3, "Failed to send message!!");
         goto exit1;
     }
     director_migrated_home(tcmi_task_local_pid(self));
     return 0;
  exit1:
     tcmi_msg_put(req);
  exit0:
     return -EFAULT;
 }
static int tcmi_guesttask_migrateback_ppm_p (struct tcmi_task * self) static
<<private>> Migrates a task back to CCN using PPM with physical checkpoint image.
This requires:
creating a new checkpoint of the current process (task helper job)
flush open files of the current process (prevents write conflicts after checkpoint restart)
communicating the checkpoint name to the shadow
terminating (via KILL_ME status)
There are two modes how the migration back can be initiated:
PEN decides to migrate the task back - in that case, the migration back message is sent as a request (trans_id is set to invalid)
CCN decides to migrate the task back - the migration back message is sent back as a response and as such is associated with a transaction. This method handles the first case. : The second method is also handled here, but not exactly as described.. CCN send asynchronous request to migrate back and then the guest initiates the processing of migration back.. we should likely rework it on transactional case described above
Parameters
*self - pointer to this task instance
Returns
TCMI_KILL_ME in either case (should it fail or not) as we want the task away from the PEN.
Definition at line 201 of file tcmi_guesttask.c.
References tcmi_guesttask_migrateback_p(), and TCMI_TASK_KILL_ME.
 {
     tcmi_guesttask_migrateback_p(self, NULL);
     // Migration back was requested so we kill in either case
     return TCMI_TASK_KILL_ME;
 }
static int tcmi_guesttask_process_msg (struct tcmi_task * self, struct tcmi_msg * m) static
<<private>> Processes a message specified by the caller.
It handles:
physical emigration request - this is special - as the guest should turn eventually into a migrated process.
Parameters
*self - pointer to this task instance
*m - message to be processed
Returns
depends on the type of message that has been processed
Definition at line 101 of file tcmi_guesttask.c.
References mdbg, memory_sanity_check, tcmi_guesttask_process_p_emigrate_msg(), tcmi_migcom_migrate_home_ppm_p(), tcmi_msg_id(), tcmi_msg_put(), TCMI_P_EMIGRATE_MSG_ID, TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID, TCMI_TASK_KEEP_PUMPING, and tcmi_task_local_pid().
 {
     int res = TCMI_TASK_KEEP_PUMPING;
     /* struct tcmi_guesttask *self_tsk = TCMI_GUESTTASK(self); */
 memory_sanity_check("On process message");
     switch (tcmi_msg_id(m)) {
         /* task PPM phys. migration request */
     case TCMI_P_EMIGRATE_MSG_ID:
         res = tcmi_guesttask_process_p_emigrate_msg(self, m);
         break;
     case TCMI_PPM_P_MIGR_BACK_SHADOWREQ_PROCMSG_ID:
         /* dispose the message not needed anymore. */
         tcmi_msg_put(m);
         /* Is there some better way to invoke self migration home? If we call directly migrate back of this task the method queue won't be flushed as in the case of this call. */
         tcmi_migcom_migrate_home_ppm_p(tcmi_task_local_pid(self));
         break;
     default:
         mdbg(ERR3, "Unexpected message from the guest task: %x", tcmi_msg_id(m));
         break;
     }
 memory_sanity_check("After process message");
     return res;
 }
static int tcmi_guesttask_process_p_emigrate_msg (struct tcmi_task * self, struct tcmi_msg * m) static
<<private>> Processes the physical emigrate process message (both NPM and PPM)
The remote PID is extracted from the emigration message and stored in the guest task. The checkpoint name is also extracted and passed to the task helper to schedule a restart. This also sets the checkpoint image as the most recent checkpoint of the task.
A response is sent back that will contain the guest task local PID. This PID is needed for further communication between the shadow and guest tasks.
The restart is only scheduled and will be processed upon next iteration of the method pump.
Parameters
*self - this guest task instance
*m - Physical emigration message that will be proceseed
Returns
TCMI_TASK_KEEP_PUMPING if the restart has been successfully scheduled
Definition at line 307 of file tcmi_guesttask.c.
References mdbg, memory_sanity_check, resp, tcmi_err_procmsg_new_tx(), TCMI_GUEST_STARTED_PROCMSG_ID, tcmi_guest_started_procmsg_new_tx(), tcmi_msg_put(), tcmi_msg_req_id(), TCMI_P_EMIGRATE_MSG, tcmi_p_emigrate_msg_ckpt_name(), tcmi_p_emigrate_msg_reply_pid(), tcmi_task_check_peer_lost(), TCMI_TASK_KEEP_PUMPING, TCMI_TASK_KILL_ME, tcmi_task_local_pid(), tcmi_task_remote_pid(), tcmi_task_send_anonymous_msg(), tcmi_task_set_remote_pid(), and tcmi_taskhelper_restart().
Referenced by tcmi_guesttask_process_msg().
 {
     struct tcmi_msg *resp;
     pid_t remote_pid;
     char *ckpt_name;
     /* extract the remote PID */
     remote_pid = tcmi_p_emigrate_msg_reply_pid(TCMI_P_EMIGRATE_MSG(m));
     tcmi_task_set_remote_pid(self, remote_pid);
     /* extract the checkpoint name */
     ckpt_name =  tcmi_p_emigrate_msg_ckpt_name(TCMI_P_EMIGRATE_MSG(m));
     mdbg(INFO2, "Processing emigration request, remote PID=%d, checkpoint: '%s'", tcmi_task_remote_pid(self), ckpt_name);
 memory_sanity_check("On processing");
     /* schedules process restart from a checkpoint image */
     if (tcmi_taskhelper_restart(self, ckpt_name) < 0) {
         /* report a problem */
         if (!(resp = tcmi_err_procmsg_new_tx(TCMI_GUEST_STARTED_PROCMSG_ID,
                              tcmi_msg_req_id(m), -ENOEXEC,
                              tcmi_task_remote_pid(self)))) {
             mdbg(ERR3, "Cannot create a guest error response!!");
             goto exit0;
         }
         memory_sanity_check("After restart");
     }
     /* restart successfully scheduled, respond with our local PID */
     else {
         if (!(resp = tcmi_guest_started_procmsg_new_tx(tcmi_msg_req_id(m),
                                   tcmi_task_remote_pid(self),
                                   tcmi_task_local_pid(self)))) {
             mdbg(ERR3, "Cannot create a guest response!!");
             goto exit0;
         }
         memory_sanity_check("After restart 2");
     }
     /* preliminary announce - the guest has been started (execve still might fail) */
     tcmi_task_check_peer_lost(self, tcmi_task_send_anonymous_msg(self, resp));
     tcmi_msg_put(resp);
     return TCMI_TASK_KEEP_PUMPING;
     /* error handling */
  exit0:
     return TCMI_TASK_KILL_ME;
 }