Clondike: tcmi_mighooks class
tcmi_mighooks class
migration
A <<singleton>> class that installs migration hooks into the kernel.
Functions
static long tcmi_mighooks_do_exit (long code)
<<private>> Exit system call hook.
static long tcmi_mighooks_mig_mode (struct pt_regs *regs)
<<private>> This hook is called upon SIGUNUSED delivery to a particular process.
static void tcmi_try_npm_on_exec (const char *filename, const char __user *const __user *argv, const char __user *const __user *envp, struct pt_regs *regs, struct tcmi_man *man, int is_guest)
static long tcmi_mighooks_execve (const char *filename, const char __user *const __user *argv, const char __user *const __user *envp, struct pt_regs *regs)
static long tcmi_mighooks_replace_proc_self_file (const char *filename, const char **result)
int tcmi_mighooks_init (void)
<<public>> Registers all hooks with the kernel.
void tcmi_mighooks_exit (void)
<<public>> Unregisters all hooks.
Detailed Description
A <<singleton>> class that installs migration hooks into the kernel.
Currently the hooks cover:
migration mode callback
exit system call hook
Function Documentation
static long tcmi_mighooks_do_exit (long code) static
<<private>> Exit system call hook.
Delegates work to the task helper that notifies current process by submitting a task_exit method and supplying the exit code. The task handles the rest on its own.
The priority notification is used, so that the exit follows immediately.
This hook is called for every process in the system, but does something only for TCMI tasks.
Parameters
code - process exit code
Returns
- status of how the notification went.
Definition at line 135 of file tcmi_mighooks.c.
References director_task_exit(), proxyfs_server_release_all(), proxyfs_sync_files_on_exit(), tcmi_task_exit(), and tcmi_taskhelper_notify_current().
Referenced by tcmi_mighooks_init().
 {
     int prio = 1, is_shadow;
     struct rusage rusage;
     mm_segment_t old_fs;
     long res;
     is_shadow = (current->tcmi.task_type == shadow || current->tcmi.task_type == shadow_detached);
     old_fs = get_fs();
     set_fs(get_ds());
     res = getrusage(current, RUSAGE_SELF, &rusage);
     set_fs(old_fs);
     director_task_exit(current->pid, code, &rusage);
     res = tcmi_taskhelper_notify_current(tcmi_task_exit, &code,
                           sizeof(code), prio);
     if ( is_shadow ) { // If the exitting task is a shadow task, we release all its proxy files as they won't be needed
         proxyfs_sync_files_on_exit(); // We have to synchronize all files first so that no new writes occur after server release
         proxyfs_server_release_all();
     }
     return res;
 }
static long tcmi_mighooks_execve (const char * filename, const char __user *const __user * argv, const char __user *const __user * envp, struct pt_regs * regs) static
Definition at line 215 of file tcmi_mighooks.c.
References mdbg, tcmi_task::remote_pid, TCMI_MAN, tcmi_msg_put(), tcmi_task_get_execve_count(), tcmi_task_get_type(), tcmi_task_inc_execve_count(), tcmi_task_send_anonymous_msg(), tcmi_try_npm_on_exec(), and tcmi_vfork_done_procmsg_new_tx().
Referenced by tcmi_mighooks_init().
{
     if ( !current->tcmi.tcmi_task ) {
         /* The task is not controlled by clondike => we can non-preemptively migrate it ONLY if there is CCN registered on current node */
         struct tcmi_ccnman* ccn_man = tcmi_ccnman_get_instance();
         mdbg(INFO4, "DEBUG TCMI_TASK NOT SET");
         if ( ccn_man != NULL )
             tcmi_try_npm_on_exec(filename, argv, envp, regs, TCMI_MAN(ccn_man), 0);
     } else if ( tcmi_task_get_type(current->tcmi.tcmi_task) == guest ) {
         mdbg(INFO4, "DEBUG TCMI_TASK == QUEST");
         // We allow npm only after we get initial execve executed.. not during the initial image load!
         if ( tcmi_task_get_execve_count(current->tcmi.tcmi_task) > 1 ) {
             // Task is guest, so DN has to take care of its possible NPM
             struct tcmi_penman* pen_man = tcmi_penman_get_instance();
             mdbg(INFO3, "Guest exec hook called. File %s", filename);
             tcmi_try_npm_on_exec(filename, argv, envp, regs, TCMI_MAN(pen_man), 1);
         } else {
             /* On first exceve, we notify about possible vfork done
              TODO: We may optimize this, and notify only in case it is required.. this would require some flag in tcmi_task, that would be caried here during emigration */
             struct tcmi_msg *m;
             /* We do not aquire reference to t_task as it cannot be release at this moment*/
             struct tcmi_task* t_task = current->tcmi.tcmi_task;
             if ( !t_task) {
                 mdbg(ERR3, "No tcmi task associated!");
                 goto exit0;
             }
             if (!(m = tcmi_vfork_done_procmsg_new_tx(t_task->remote_pid))) {
                 mdbg(ERR3, "Can't create vfork done message");
                 // TODO: What to do in this case? ;) For now we just ignore it.
                 goto exit0;
             }
             tcmi_task_send_anonymous_msg(t_task, m);
             tcmi_msg_put(m);
             exit0:
             ;
         }
         tcmi_task_inc_execve_count(current->tcmi.tcmi_task);
     } else {
         mdbg(INFO4, "DEBUG TASK OTHER");
         // We are shadow task => ignore this hook, shadow execves only when restarting process that was migrated back
         tcmi_task_inc_execve_count(current->tcmi.tcmi_task);
     }
     return 0;
 };
void tcmi_mighooks_exit (void)
<<public>> Unregisters all hooks.
Definition at line 71 of file tcmi_mighooks.c.
References minfo.
Referenced by tcmi_module_exit().
 {
     minfo(INFO1, "Unregistering TCMI migration hooks");
     tcmi_hooks_unregister_exit();
     tcmi_hooks_unregister_sig_unused();
     tcmi_hooks_unregister_execve();
     tcmi_hooks_unregister_replace_proc_self_file();
 }
int tcmi_mighooks_init (void)
<<public>> Registers all hooks with the kernel.
Returns
0 upon success
Definition at line 58 of file tcmi_mighooks.c.
References minfo, tcmi_mighooks_do_exit(), tcmi_mighooks_execve(), tcmi_mighooks_mig_mode(), and tcmi_mighooks_replace_proc_self_file().
Referenced by tcmi_module_init().
 {
     minfo(INFO1, "Registering TCMI migration hooks");
     tcmi_hooks_register_exit(tcmi_mighooks_do_exit);
     tcmi_hooks_register_sig_unused(tcmi_mighooks_mig_mode);
     tcmi_hooks_register_execve(tcmi_mighooks_execve);
     tcmi_hooks_register_replace_proc_self_file(tcmi_mighooks_replace_proc_self_file);
     return 0;
 }
static long tcmi_mighooks_mig_mode (struct pt_regs * regs) static
<<private>> This hook is called upon SIGUNUSED delivery to a particular process.
All work is delegated to the task helper. The context passed onto the task helper is used for updating the TCMI task. Any potential migration request thus operates on the latest process context.
Parameters
*regs - process context right before entering kernel mode.
Definition at line 171 of file tcmi_mighooks.c.
References tcmi_taskhelper_do_mig_mode().
Referenced by tcmi_mighooks_init().
 {
     tcmi_taskhelper_do_mig_mode(regs);
     return 0;
 }
static long tcmi_mighooks_replace_proc_self_file (const char * filename, const char ** result) static
Definition at line 269 of file tcmi_mighooks.c.
References mdbg.
Referenced by tcmi_mighooks_init().
{
     if ( strncmp("/proc/self",filename,10) == 0 ) {
         int len;
         char * tmp_result = __getname();
         if ( !(tmp_result) )
             return -ENOMEM;
         //len = sprintf((tmp_result), "/proc/%d%s", tcmi_task_remote_pid(current->tcmi.tcmi_task), filename+10);
         len = sprintf((tmp_result), "/mnt/local/proc/self%s", filename+10);
         mdbg(ERR3, "Replaced open filename from %s to %s (len: %d)", filename, (tmp_result), len);
         *result = tmp_result;
     }
     return 0;
 }
static void tcmi_try_npm_on_exec (const char * filename, const char __user *const __user * argv, const char __user *const __user * envp, struct pt_regs * regs, struct tcmi_man * man, int is_guest) static
Definition at line 177 of file tcmi_mighooks.c.
References tcmi_npm_params::argsc, director_npm_check(), tcmi_npm_params::envpc, extract_tcmi_npm_params(), tcmi_npm_params::file_name, mdbg, tcmi_man_emig_npm(), and tcmi_penman_migrateback_npm().
Referenced by tcmi_mighooks_execve().
 {
     struct rusage rusage;
     mm_segment_t old_fs;
     int migman_to_use = -1;
     int migrate_home = 0;
     old_fs = get_fs();
     set_fs(get_ds());
     getrusage(current, RUSAGE_SELF, &rusage);
     set_fs(old_fs);
     if (director_npm_check(current->pid, current_euid(), is_guest, filename, argv, envp, &migman_to_use, &migrate_home, &rusage) != 1 )
         return;
     migrate_home = is_guest ? migrate_home : 0;
     // Check if we should emigrate and if so where
     if ( migman_to_use != -1 || migrate_home ) {
         struct tcmi_npm_params* npm_params = vmalloc(sizeof(struct tcmi_npm_params));
         int err = extract_tcmi_npm_params(npm_params, filename, argv, envp);
         mdbg(INFO4, "AFTER EXTRACT Filename: %s, Argc: %d, Evnpc: %d.", npm_params->file_name, npm_params->argsc, npm_params->envpc);
         if ( err ) {
             mdbg(ERR3, "Error extracting npm params: %d. Skipping npm emigration attempt.", err);
             vfree(npm_params);
         } else {
             if ( migrate_home )
                 tcmi_penman_migrateback_npm(man, regs, npm_params);
             else
                 tcmi_man_emig_npm(man, current->pid, migman_to_use, regs, npm_params);
             // If we got here, the migration was not performed => free npm params
             mdbg(INFO3, "Freeing npm_params after unsuccessful npm migration attempt.");
             vfree(npm_params);
         }
     }
 }