Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/migration/tcmi_migcom.c File Reference
tcmi_migcom.c File Reference
#include <tcmi/task/tcmi_taskhelper.h>
#include <tcmi/task/tcmi_shadowtask.h>
#include <tcmi/task/tcmi_guesttask.h>
#include <tcmi/lib/util.h>
#include "tcmi_migcom.h"
#include <tcmi/manager/tcmi_penmigman.h>
#include <tcmi/migration/fs/fs_mounter_register.h>
#include <tcmi/migration/fs/fs_mounter.h>
#include "tcmi_npm_params.h"
#include <director/director.h>
#include <dbg.h>
Data Structures
struct immigrate_startup_params
Helper struct to be passed to immigration statup thread.
Macros
#define TCMI_MIGCOM_PRIVATE
Functions
static int mount_proxyfs (struct kkc_sock *sock)
static int mount_local_procfs (struct kkc_sock *sock)
Mounts local machine procfs into some directory in chrooted env, so that it can be later accessed if required.
static int tcmi_task_mount_proxyfs (void *self, struct tcmi_method_wrapper *wr)
int tcmi_migcom_emigrate_ccn_ppm_p (pid_t pid, struct tcmi_migman *migman)
<<public>> Migrates a task from a CCN to a PEN.
int tcmi_migcom_emigrate_ccn_npm (pid_t pid, struct tcmi_migman *migman, struct pt_regs *regs, struct tcmi_npm_params *npm_params)
<<public>> Migrates non-preemptively a task from a CCN to a PEN
int tcmi_migcom_immigrate (struct tcmi_msg *m, struct tcmi_migman *migman)
<<public>> Immigrates a task - handles accepting the task on the PEN side.
int tcmi_migcom_migrate_home_ppm_p (pid_t pid)
<<public>> Migrates a task back to its home node using preemptive migration with physical checkpoint file.
static int tcmi_migcom_migrated_task (void *data)
<<private>> This method represents a kernel thread that will eventually become the 'immigrated' task.
int tcmi_migcom_guest_fork (struct task_struct *parent, struct task_struct *child, struct tcmi_migman *migman)
<<public>> Fork of guest.
int tcmi_migcom_shadow_fork (struct task_struct *parent, struct task_struct *child, struct tcmi_migman *migman)
<<public>> Fork of shadow
static void tcmi_migcom_mig_mode_handler (void)
<<private>> This handler is invoked when the sig_unused hook finds a non-NULL entry in the clondike record in the task_struct.
Variables
static const char proc_path [] = "/mnt/local/proc"
Data Structure Documentation
struct immigrate_startup_params
Helper struct to be passed to immigration statup thread.
Definition at line 259 of file tcmi_migcom.c.
Data Fields
struct completion guest_ready fs_ready used to signal the thread the guest(or fs mount respectively) is ready
int16_t fsgid
int16_t fsuid Credentials that can be used for fs mounting.
struct fs_mount_params * mount_params Params for mounting of distributed fs.
struct kkc_sock * sock Migman socket.
. used to determine peers address so that we can mount its proxyfs
Macro Definition Documentation
#define TCMI_MIGCOM_PRIVATE
Definition at line 36 of file tcmi_migcom.c.
Function Documentation
static int mount_local_procfs (struct kkc_sock * sock) static
Mounts local machine procfs into some directory in chrooted env, so that it can be later accessed if required.
Definition at line 95 of file tcmi_migcom.c.
References mdbg, minfo, mk_dir(), and proc_path.
Referenced by tcmi_migcom_migrated_task().
{
     //struct nameidata nd;
     struct path path;   //Replaced struct nameidata to struct path | by Jiri Rakosnik
     int err;
   //Replaced function path_lookup to kern_path for kernel 3.7.1 | by Jiri Rakosnik
     err = kern_path(proc_path, LOOKUP_FOLLOW | LOOKUP_DIRECTORY, &path);
     if ( err ) {
         minfo(ERR1, "Failed to lookup path %s: %d. Trying to create", proc_path, err);
         err = mk_dir(proc_path, 777);
         if (err) {
             goto exit0;
         }
     }
     err = do_mount("none", proc_path, "proc", 0, NULL);
     mdbg(INFO2, "Procfs mount result: %d", err);
     if ( err ) {
         minfo(ERR1, "Failed to mount filesystem: %d", err);
         goto exit0;
     }
 exit0:
     return err;
 }
static int mount_proxyfs (struct kkc_sock * sock) static
Definition at line 48 of file tcmi_migcom.c.
References KKC_MAX_ARCH_LENGTH, kkc_sock_getarchname(), kkc_sock_getpeername(), KKC_SOCK_MAX_ADDR_LENGTH, mdbg, and minfo.
Referenced by tcmi_migcom_migrated_task(), and tcmi_task_mount_proxyfs().
{
     int err = 0, len;
     char buffer[KKC_MAX_ARCH_LENGTH + KKC_SOCK_MAX_ADDR_LENGTH + 2];
     char* last_colon_char;
     struct cred* new_cred;
     new_cred = prepare_creds();
     if ( !new_cred )
         return -ENOMEM;
     // TODO: Make mount dir configurable?
     memset(buffer, 0, KKC_MAX_ARCH_LENGTH + KKC_SOCK_MAX_ADDR_LENGTH + 2);
     kkc_sock_getarchname(sock, buffer, KKC_MAX_ARCH_LENGTH);
     len = strlen(buffer);
     buffer[len] = ':';
     kkc_sock_getpeername(sock, buffer + len + 1, KKC_SOCK_MAX_ADDR_LENGTH);
     // TODO: Ugly ugly... works only for specific format of string and in addition port is hardcoded here
     last_colon_char = strrchr(buffer, ':');
     sprintf(last_colon_char+1, "%d", 1112);
     mdbg(INFO2, "Going to mount proxyfs on dev: %s fsuid: %d euid: %d csa: %d euid: %d uid: %d, suid: %d", buffer, current_fsuid(), current_euid(), capable(CAP_SYS_ADMIN), current_euid(), current_uid(), current_suid() );
     // TODO: Ohh man.. this is something terrible.. we should fiddle better with the fs rights, so that we do not need this
     // The problem is, that all works fine for newly created immigrated processes, since they have these capabilities, but
     // when we start using forked processes, they do not and they have a lot of problems with FS access, for example to proxy-fs
     cap_raise (new_cred->cap_effective, CAP_SYS_ADMIN);
     cap_raise (new_cred->cap_effective, CAP_DAC_READ_SEARCH);
     cap_raise (new_cred->cap_effective, CAP_DAC_OVERRIDE);
     cap_raise (new_cred->cap_effective, CAP_FOWNER);
     cap_raise (new_cred->cap_effective, CAP_FSETID);
     commit_creds(new_cred);
     err = do_mount(buffer, "/mnt/proxy", "proxyfs", 0, NULL);
     mdbg(INFO2, "After Proxyfs mount: %d", err);
     if ( err ) {
         minfo(ERR1, "Failed to mount filesystem: %d", err);
         goto exit0;
     }
 exit0:
     return err;
 }
static void tcmi_migcom_mig_mode_handler (void) static
<<private>> This handler is invoked when the sig_unused hook finds a non-NULL entry in the clondike record in the task_struct.
What needs to be done:
check whether the process in migration mode has a valid TCMI task
launch the method pump
based on its return status:
let's the task return to user mode
detaches the TCMI task from the process and resumes user mode
detaches the TCMI task from the process and kills the process
Definition at line 625 of file tcmi_migcom.c.
References tcmi_task::exit_code, mdbg, TCMI_TASK_EXECVE_FAILED_KILL_ME, tcmi_task_exit_code(), TCMI_TASK_KEEP_PUMPING, TCMI_TASK_KILL_ME, TCMI_TASK_LET_ME_GO, TCMI_TASK_MOVE_ME, tcmi_task_process_methods(), tcmi_task_put(), TCMI_TASK_REMOVE_AND_LET_ME_GO, tcmi_taskhelper_detach(), and tcmi_taskhelper_sanity_check().
Referenced by tcmi_migcom_emigrate_ccn_npm(), tcmi_migcom_emigrate_ccn_ppm_p(), and tcmi_migcom_immigrate().
 {
     struct tcmi_task *tmp, *task;
     int res;
     long exit_code;
     mdbg(INFO3, "Migration mode handler for task '%s' stack rp(%p) executing",
          current->comm, &res);
     if (!(task = tcmi_taskhelper_sanity_check())) {
         mdbg(ERR2, "Process %p PID=%d - invalid entry to migration mode",
               current, current->pid);
         goto exit0;
     }
     /* keep moving the task between migration managers */
     while ((res = tcmi_task_process_methods(task)) ==
            TCMI_TASK_MOVE_ME);
     /* check the result of the last method processed */
     switch (res) {
     case TCMI_TASK_KEEP_PUMPING:
         mdbg(INFO2, "KEEP PUMPING - but no methods left %d", res);
         break;
     case TCMI_TASK_LET_ME_GO:
         mdbg(INFO2, "LET ME GO - request %d", res);
         break;
         /* no need for special handling a fall through causes
          * do_exit which invokes the migration handler again. */
     case TCMI_TASK_EXECVE_FAILED_KILL_ME:
         mdbg(INFO2, "EXECVE_FAILED KILL ME - request %d", res);
         break;
     case TCMI_TASK_KILL_ME:
         mdbg(INFO2, "KILL ME - request %d", res);
         tmp = tcmi_taskhelper_detach();
         /* get the exit code prior terminating. */
         exit_code = tcmi_task_exit_code(tmp);
         tcmi_task_put(tmp);
         mdbg(INFO2, "Put done, going to exit %ld", exit_code);
         complete_and_exit(NULL, exit_code);
         break;
     case TCMI_TASK_REMOVE_AND_LET_ME_GO:
         mdbg(INFO2, "REMOVE AND LET ME GO - request %d", res);
         tcmi_task_put(tcmi_taskhelper_detach());
         break;
     default:
         mdbg(ERR2, "Unexpected result %d.", res);
         break;
     }
     /* error handling */
  exit0:
     return;
 }
static int tcmi_migcom_migrated_task (void * data) static
<<private>> This method represents a kernel thread that will eventually become the 'immigrated' task.
It does following:
tries to mount a distributed filesystem, if required (note, that this must be done by this thread as we are mounting into its private namespace)
mounts a proxyfs into a private namespace
waits until signalled, that the guest is ready
runs its migration mode handler (this picks up the task).
Parameters
*data - pointer to startup parameters
Returns
shouldn't return as the execve will overlay current execution image.
Todo:
process identity should be set according to the the user configuration (tcmi_confman)
Definition at line 439 of file tcmi_migcom.c.
References free_mounter(), immigrate_startup_params::fs_ready, immigrate_startup_params::fsgid, immigrate_startup_params::fsuid, get_new_mounter(), mdbg, minfo, mount_local_procfs(), immigrate_startup_params::mount_params, mount_proxyfs(), fs_mount_params::mount_type, fs_mounter::private_mount, immigrate_startup_params::sock, and tcmi_taskhelper_run_mig_mode_handler().
Referenced by tcmi_migcom_immigrate().
 {
     int err = -EINVAL;
     struct immigrate_startup_params* startup_params = (struct immigrate_startup_params*) data;
     struct completion *guest_ready = &startup_params->guest_ready;
     struct completion *fs_ready = &startup_params->fs_ready;
     struct fs_mounter* mounter;
     struct cred* new_cred;
     mdbg(INFO2, "New potential guest thread started. Pid: %d", current->pid);
     new_cred = prepare_creds();
     if ( !new_cred )
         return -ENOMEM;
     /* set process credentials */
     new_cred->uid = new_cred->euid = new_cred->suid = new_cred->fsuid =
     new_cred->gid = new_cred->egid = new_cred->sgid = new_cred->fsgid = 999;
     commit_creds(new_cred);
 //  current_uid() = current_euid() = current_suid() = current_fsuid() =
 //      current_gid() = current_egid() = current_sgid() =
 //      current_fsgid() = 999;
     /* This part simulates when the process didn't pickup
        the task on time
     set_current_state(TASK_INTERRUPTIBLE);
     schedule_timeout(5*HZ);
     minfo(INFO1, "Task has woken up %p", current);
     */
     // TODO: Close ALL fs.. are there some others? ;)
     sys_close(0);
     sys_close(1);
     sys_close(2);
     mdbg(INFO2, "Creating mounter: %s", startup_params->mount_params->mount_type);
     minfo(ERR1, "Creating mounter: %s", startup_params->mount_params->mount_type);
     mounter = get_new_mounter(startup_params->mount_params);
     mdbg(INFO2, "Created mounter: %p", mounter);
     minfo(ERR1, "Created mounter: %p", mounter);
     if ( mounter ) {
         /* Some file system mounter is registered => perform the mount */
         err = mounter->private_mount(mounter, startup_params->fsuid, startup_params->fsgid);
         if ( !err )
             mdbg(INFO2, "Private Mount succeeded");
         free_mounter(mounter);
         mdbg(INFO2, "Freed mounter");
         minfo(ERR1, "Freed mounter");
         if ( err ) {
             /* We must notify anyway to prevent blocking */
             complete(fs_ready);
             goto exit0;
         }
     }
     minfo(ERR1, "BEFORE mount_proxyfs");
     err = mount_proxyfs(startup_params->sock);
     if ( !err )
         err = mount_local_procfs(startup_params->sock);
     if ( err ) {
         // We must notify anyway to prevent blocking
         complete(fs_ready);
         goto exit0;
     }
     /* Notify about file system mount finished */
     complete(fs_ready);
     minfo(ERR1, "BEFORE Starting new thread for migrating task..");
     mdbg(INFO2, "Starting new thread for migrating task..");
     if ((err = wait_for_completion_interruptible(guest_ready))) {
         minfo(INFO1, "Received signal guest not ready");
         goto exit0;
     }
     mdbg(INFO3, "Guest task is ready by now..");
     /* migration mode handler picks up the task  */
     if (tcmi_taskhelper_run_mig_mode_handler() < 0) {
         mdbg(ERR3, "Failed to run migration mode handler");
         goto exit0;
     }
     return 0;
     /* error handling */
  exit0:
     return err;
 }
static int tcmi_task_mount_proxyfs (void * self, struct tcmi_method_wrapper * wr) static
Definition at line 120 of file tcmi_migcom.c.
References minfo, mount_proxyfs(), tcmi_method_wrapper_data(), and TCMI_TASK_KEEP_PUMPING.
{
     int res;
     struct kkc_sock* sock = *(struct kkc_sock**)tcmi_method_wrapper_data(wr);
     if ( (res =mount_proxyfs(sock)) ) {
         minfo(ERR1, "Failed to mount proxy filesystem: %d", res);
         // Kill current process.. do not exit via kill me as it does not invoke exit hook
         force_sig(SIGKILL, current);
     }
     return TCMI_TASK_KEEP_PUMPING;
 }
Variable Documentation
const char proc_path[] = "/mnt/local/proc" static
Definition at line 93 of file tcmi_migcom.c.
Referenced by mount_local_procfs().