Clondike: tcmi_generic_user_msg class
tcmi_generic_user_msg class
tcmi_msg class
This message can be send both by PEN or CCN.
Data Structures
struct tcmi_generic_user_msg
Generic user message structure.
struct tcmi_generic_user_procmsg
Generic user message structure.
Macros
#define TCMI_GENERIC_USER_MSG_DSC TCMI_MSG_DSC(TCMI_GENERIC_USER_MSG_ID, tcmi_generic_user_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
#define TCMI_GENERIC_USER_MSG(m) ((struct tcmi_generic_user_msg*)m)
Casts to the tcmi_generic_user_msg instance.
#define TCMI_GENERIC_USER_PROCMSG_DSC TCMI_MSG_DSC(TCMI_GENERIC_USER_PROCMSG_ID, tcmi_generic_user_procmsg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
#define TCMI_GENERIC_USER_PROCMSG(m) ((struct tcmi_generic_user_procmsg*)m)
Casts to the tcmi_generic_user_msg instance.
Functions
struct tcmi_msg * tcmi_generic_user_msg_new_rx (u_int32_t msg_id)
<<public>> Message consutructor for receiving.
struct tcmi_msg * tcmi_generic_user_msg_new_tx (u_int32_t node_id, char *user_data, int size)
<<public>> Message constructor for transferring.
static u_int32_t tcmi_generic_user_msg_node_id (struct tcmi_generic_user_msg *self)
<<public>> Node id getter
static u_int32_t tcmi_generic_user_msg_user_data_size (struct tcmi_generic_user_msg *self)
<<public>> User data length getter
static char * tcmi_generic_user_msg_user_data (struct tcmi_generic_user_msg *self)
<<public>> User data data getter
struct tcmi_msg * tcmi_generic_user_procmsg_new_rx (u_int32_t msg_id)
<<public>> Message consutructor for receiving.
struct tcmi_msg * tcmi_generic_user_procmsg_new_tx (u_int32_t node_id, char *user_data, int size)
<<public>> Message constructor for transferring.
static u_int32_t tcmi_generic_user_procmsg_node_id (struct tcmi_generic_user_procmsg *self)
<<public>> Node id getter
static u_int32_t tcmi_generic_user_procmsg_user_data_size (struct tcmi_generic_user_procmsg *self)
<<public>> User data length getter
static char * tcmi_generic_user_procmsg_user_data (struct tcmi_generic_user_procmsg *self)
<<public>> User data data getter
Detailed Description
This message can be send both by PEN or CCN.
It can contain any data that are passed from user space to the director of peer node.
Data Structure Documentation
struct tcmi_generic_user_msg
Generic user message structure.
Definition at line 20 of file tcmi_generic_user_msg.h.
Data Fields
u_int32_t node_id Id of the requestor PEN or CCN.
u_int32_t size Size of user data.
struct tcmi_msg super parent class instance.
char * user_data User passed data.
Opaque to the kernel part, this is purely user space responsibilithy to provide and parse those.
struct tcmi_generic_user_procmsg
Generic user message structure.
Definition at line 20 of file tcmi_generic_user_procmsg.h.
Data Fields
u_int32_t node_id Id of the requestor PEN or CCN.
u_int32_t size Size of user data.
struct tcmi_msg super parent class instance.
char * user_data User passed data.
Opaque to the kernel part, this is purely user space responsibilithy to provide and parse those.
Macro Definition Documentation
#define TCMI_GENERIC_USER_MSG (m) ((struct tcmi_generic_user_msg*)m)
Casts to the tcmi_generic_user_msg instance.
Definition at line 47 of file tcmi_generic_user_msg.h.
Referenced by tcmi_ccnmigman_process_msg(), tcmi_generic_user_msg_new_rx(), tcmi_generic_user_msg_new_tx(), tcmi_generic_user_msg_recv(), tcmi_generic_user_msg_send(), tcmi_generic_user_msg_send_free(), and tcmi_penmigman_process_msg().
#define TCMI_GENERIC_USER_MSG_DSC TCMI_MSG_DSC(TCMI_GENERIC_USER_MSG_ID, tcmi_generic_user_msg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
Definition at line 44 of file tcmi_generic_user_msg.h.
#define TCMI_GENERIC_USER_PROCMSG (m) ((struct tcmi_generic_user_procmsg*)m)
Casts to the tcmi_generic_user_msg instance.
Definition at line 47 of file tcmi_generic_user_procmsg.h.
Referenced by tcmi_generic_user_procmsg_new_rx(), tcmi_generic_user_procmsg_new_tx(), tcmi_generic_user_procmsg_recv(), tcmi_generic_user_procmsg_send(), and tcmi_generic_user_procmsg_send_free().
#define TCMI_GENERIC_USER_PROCMSG_DSC TCMI_MSG_DSC(TCMI_GENERIC_USER_PROCMSG_ID, tcmi_generic_user_procmsg_new_rx, NULL)
<<public>> Message descriptor for the factory class, there is no error handling as this is the starting request
Definition at line 44 of file tcmi_generic_user_procmsg.h.
Function Documentation
struct tcmi_msg* tcmi_generic_user_msg_new_rx (u_int32_t msg_id) read
<<public>> Message consutructor for receiving.
<<public>> Message consutructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this message instance.
Returns
a new message or NULL.
Definition at line 24 of file tcmi_generic_user_msg.c.
References generic_user_msg_ops, mdbg, TCMI_GENERIC_USER_MSG, TCMI_GENERIC_USER_MSG_ID, TCMI_MSG, and tcmi_msg_init_rx().
 {
     struct tcmi_generic_user_msg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_GENERIC_USER_MSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_GENERIC_USER_MSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_GENERIC_USER_MSG(kmalloc(sizeof(struct tcmi_generic_user_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate generic user message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_GENERIC_USER_MSG_ID, &generic_user_msg_ops)) {
         mdbg(ERR3, "Error initializing generic user message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_generic_user_msg_new_tx (u_int32_t node_id, char * user_data, int size) read
<<public>> Message constructor for transferring.
<<public>> Message constructor for transferring.
Parameters
node_id Id of the requesting node
Returns
a new message ready for the transfer or NULL.
Definition at line 62 of file tcmi_generic_user_msg.c.
References generic_user_msg_ops, mdbg, tcmi_generic_user_msg::node_id, tcmi_generic_user_msg::size, size, TCMI_GENERIC_USER_MSG, TCMI_GENERIC_USER_MSG_ID, TCMI_MSG, tcmi_msg_init_tx(), TCMI_TRANSACTION_INVAL_ID, and tcmi_generic_user_msg::user_data.
Referenced by tcmi_man_do_send_generic_user_message().
 {
     struct tcmi_generic_user_msg *msg;
     if (!(msg = TCMI_GENERIC_USER_MSG(kmalloc(sizeof(struct tcmi_generic_user_msg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate generic user message");
         goto exit0;
     }
     msg->node_id = node_id;
     msg->size = size;
     if ( size > 0 ) {
         if (!(msg->user_data = (char*)kmalloc(size, GFP_KERNEL))) {
             mdbg(ERR3, "Can't allocate memory for user data message");
             goto exit1;
         }
         memcpy(msg->user_data, user_data, size);
     } else {
         msg->user_data = NULL;
     }
     /* Initialize the message for transfer */
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_GENERIC_USER_MSG_ID, &generic_user_msg_ops,
                  NULL, 0,
                  0, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing generic user message");
         goto exit2;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit2:
     kfree(msg->user_data);
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static u_int32_t tcmi_generic_user_msg_node_id (struct tcmi_generic_user_msg * self) inline static
<<public>> Node id getter
Parameters
*self - this message instance
Returns
Node id
Definition at line 55 of file tcmi_generic_user_msg.h.
Referenced by tcmi_ccnmigman_process_msg(), and tcmi_penmigman_process_msg().
 {
     return self->node_id;
 }
static char* tcmi_generic_user_msg_user_data (struct tcmi_generic_user_msg * self) inline static
<<public>> User data data getter
Parameters
*self - this message instance
Returns
User data
Definition at line 77 of file tcmi_generic_user_msg.h.
Referenced by tcmi_ccnmigman_process_msg(), and tcmi_penmigman_process_msg().
 {
     return self->user_data;
 }
static u_int32_t tcmi_generic_user_msg_user_data_size (struct tcmi_generic_user_msg * self) inline static
<<public>> User data length getter
Parameters
*self - this message instance
Returns
data length
Definition at line 66 of file tcmi_generic_user_msg.h.
Referenced by tcmi_ccnmigman_process_msg(), and tcmi_penmigman_process_msg().
 {
     return self->size;
 }
struct tcmi_msg* tcmi_generic_user_procmsg_new_rx (u_int32_t msg_id) read
<<public>> Message consutructor for receiving.
<<public>> Message consutructor for receiving.
This method is called by the factory class.
Parameters
msg_id - message ID that will be used for this message instance.
Returns
a new message or NULL.
Definition at line 24 of file tcmi_generic_user_procmsg.c.
References generic_user_procmsg_ops, mdbg, TCMI_GENERIC_USER_PROCMSG, TCMI_MSG, and tcmi_msg_init_rx().
 {
     struct tcmi_generic_user_procmsg *msg;
     /* Check if the factory is building what it really thinks. */
     if (msg_id != TCMI_GENERIC_USER_PROCMSG_ID) {
         mdbg(ERR3, "Factory specified message ID(%x) doesn't match real ID(%x)",
              msg_id, TCMI_GENERIC_USER_PROCMSG_ID);
         goto exit0;
     }
     /* Allocate the instance */
     if (!(msg = TCMI_GENERIC_USER_PROCMSG(kmalloc(sizeof(struct tcmi_generic_user_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate generic user message");
         goto exit0;
     }
     /* Initialized the message for receiving. */
     if (tcmi_msg_init_rx(TCMI_MSG(msg), TCMI_GENERIC_USER_PROCMSG_ID, &generic_user_procmsg_ops)) {
         mdbg(ERR3, "Error initializing generic user message %x", msg_id);
         goto exit1;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
struct tcmi_msg* tcmi_generic_user_procmsg_new_tx (u_int32_t node_id, char * user_data, int size) read
<<public>> Message constructor for transferring.
<<public>> Message constructor for transferring.
Parameters
node_id Id of the requesting node
Returns
a new message ready for the transfer or NULL.
Definition at line 62 of file tcmi_generic_user_procmsg.c.
References generic_user_procmsg_ops, mdbg, tcmi_generic_user_procmsg::node_id, tcmi_generic_user_procmsg::size, size, TCMI_GENERIC_USER_PROCMSG, TCMI_MSG, tcmi_msg_init_tx(), TCMI_TRANSACTION_INVAL_ID, and tcmi_generic_user_procmsg::user_data.
 {
     struct tcmi_generic_user_procmsg *msg;
     if (!(msg = TCMI_GENERIC_USER_PROCMSG(kmalloc(sizeof(struct tcmi_generic_user_procmsg), GFP_KERNEL)))) {
         mdbg(ERR3, "Can't allocate generic user message");
         goto exit0;
     }
     msg->node_id = node_id;
     msg->size = size;
     if ( size > 0 ) {
         if (!(msg->user_data = (char*)kmalloc(size, GFP_KERNEL))) {
             mdbg(ERR3, "Can't allocate memory for user data message");
             goto exit1;
         }
         memcpy(msg->user_data, user_data, size);
     } else {
         msg->user_data = NULL;
     }
     /* Initialize the message for transfer */
     if (tcmi_msg_init_tx(TCMI_MSG(msg), TCMI_GENERIC_USER_PROCMSG_ID, &generic_user_procmsg_ops,
                  NULL, 0,
                  0, TCMI_TRANSACTION_INVAL_ID)) {
         mdbg(ERR3, "Error initializing generic user message");
         goto exit2;
     }
     return TCMI_MSG(msg);
     /* error handling */
  exit2:
     kfree(msg->user_data);
  exit1:
     kfree(msg);
  exit0:
     return NULL;
 }
static u_int32_t tcmi_generic_user_procmsg_node_id (struct tcmi_generic_user_procmsg * self) inline static
<<public>> Node id getter
Parameters
*self - this message instance
Returns
Node id
Definition at line 55 of file tcmi_generic_user_procmsg.h.
 {
     return self->node_id;
 }
static char* tcmi_generic_user_procmsg_user_data (struct tcmi_generic_user_procmsg * self) inline static
<<public>> User data data getter
Parameters
*self - this message instance
Returns
User data
Definition at line 77 of file tcmi_generic_user_procmsg.h.
 {
     return self->user_data;
 }
static u_int32_t tcmi_generic_user_procmsg_user_data_size (struct tcmi_generic_user_procmsg * self) inline static
<<public>> User data length getter
Parameters
*self - this message instance
Returns
data length
Definition at line 66 of file tcmi_generic_user_procmsg.h.
 {
     return self->size;
 }