Clondike: C:/CLONDIKE/clondike/sources/kernel_3.7.1/src/tcmi/ckpt/tcmi_ckpt.c File Reference
tcmi_ckpt.c File Reference
#include <linux/mm.h>
#include <linux/fs.h>
#include <linux/fs_struct.h>
#include <linux/fdtable.h>
#include "tcmi_ckpt.h"
#include "tcmi_ckpt_openfile.h"
#include "tcmi_ckpt_vm_area.h"
#include <arch/arch_ids.h>
#include <arch/current/regs.h>
#include <arch/current/vma.h>
#include <linux/personality.h>
Macros
#define TCMI_CKPT_PRIVATE
Functions
struct tcmi_ckpt * tcmi_ckpt_new (struct file *file)
<<public>> Checkpoint constructor.
int tcmi_ckpt_write_hdr (struct tcmi_ckpt *self, int is_npm)
<<public>> Writes a checkpoint header.
int tcmi_ckpt_read_hdr (struct tcmi_ckpt *self)
<<public>> Reads the checkpoint header.
int tcmi_ckpt_write_files (struct tcmi_ckpt *self)
<<public>> Writes open files into the checkpoint.
int tcmi_ckpt_read_files (struct tcmi_ckpt *self)
<<public>> Reads open files from the checkpoint.
int tcmi_ckpt_write_vmas (struct tcmi_ckpt *self, int heavy)
<<public>> Writes all process memory regions into the checkpoint.
int tcmi_ckpt_read_vmas (struct tcmi_ckpt *self)
<<public>> Reads process pages from the checkpoint.
static int tcmi_ckpt_map_count (struct tcmi_ckpt *self)
<<private>> Calculates the number of memory regions of the current process.
static int tcmi_ckpt_file_count (struct tcmi_ckpt *self)
<<private>> Calculates the number of open files of the current process.
Macro Definition Documentation
#define TCMI_CKPT_PRIVATE
Definition at line 38 of file tcmi_ckpt.c.
Function Documentation
static int tcmi_ckpt_file_count (struct tcmi_ckpt * self) static
<<private>> Calculates the number of open files of the current process.
For each file check if the file is supported if so, adjust the counter.
An error is indicated if any of the files is:
socket
pipe
symlink
special file
Parameters
*self - this checkpoint instance
Returns
number of open files, or error (< 0)
Definition at line 344 of file tcmi_ckpt.c.
References count(), fd, mdbg, tcmi_ckpt_foreach_openfile, and tcmi_ckpt_openfile_supported().
Referenced by tcmi_ckpt_read_files(), tcmi_ckpt_read_hdr(), and tcmi_ckpt_write_hdr().
 {
     /* file descriptor count */
     int fd;
     int count = 0;
     int err = 0;
     struct file *file;
     struct inode *inode;
     /* Check each open file */
     tcmi_ckpt_foreach_openfile(file, fd) {
         inode = file->f_dentry->d_inode;
         if (!tcmi_ckpt_openfile_supported(inode)) {
             mdbg(ERR3, "Unsupported file mode detected %o [FD: %d]", inode->i_mode, fd);
             err = -EINVAL;
             goto exit0;
         }
         count++;
         /*mdbg(INFO4, "Scanned file fd=%d, type=%0o '%s'", fd, file->f_flags,
           file->f_dentry->d_name.name); */
     }
     mdbg(INFO4, "Found %d files, err=%d", count, err);
     return count;
     /* error handling */
  exit0:
     return -EINVAL;
 }
static int tcmi_ckpt_map_count (struct tcmi_ckpt * self) static
<<private>> Calculates the number of memory regions of the current process.
We can't simply return current->map_count. We need to check for special regions that would prevent creating a valid checkpoint
For now, we have to verify that the memory region is not:
VM_IO - I/O mapped devices
VM_SHARED - shared memory - this will be included later on, when we support checkpointing and migration of LWP's
VM_RESERVED - special mappings
Parameters
*self - this checkpoint instance
Returns
number of memory regions, or error (< 0)
Definition at line 309 of file tcmi_ckpt.c.
References count(), mdbg, and vma_ignore.
Referenced by tcmi_ckpt_read_vmas(), and tcmi_ckpt_write_hdr().
 {
     struct vm_area_struct *vma;
     int count = 0;
     int err = 0;
     tcmi_ckpt_foreach_vma(vma) {
         if ( vma_ignore(self, vma) )
             continue;
         count++;
         /* Do not dump I/O mapped devices, shared memory, or special mappings */
         if (vma->vm_flags & (VM_IO | VM_SHARED | VM_DONTDUMP))       // VM_RESERVED replaced to VM_DONTDUMP by Jiri Rakosnik
             err = -EINVAL;
         mdbg(INFO4, "Scanning area start:%08lx, end: %08lx, flags: %08lx, pageprot %08lx",
              vma->vm_start, vma->vm_end, vma->vm_flags, vma->vm_page_prot.pgprot);
     }
     mdbg(INFO4, "Found %d areas, mm indicates: %d", count, current->mm->map_count);
     return (err ? err : count);
 }