Clondike: proxyfs_proxy_file class
proxyfs_proxy_file class
proxyfs_file class
This is used on between VFS and proxyfs_client task.
Modules
proxyfs_generic_proxy_file class
This is used between VFS and proxyfs_client task for proxying generics.
proxyfs_pipe_proxy_file class
This is used between VFS and proxyfs_client task for proxying pipes.
Macros
#define PROXYFS_PROXY_FILE(arg) ((struct proxyfs_proxy_file_t *)(arg))
<<public>> Cast to struct proxyfs_proxy_file_t *
Functions
int proxyfs_proxy_file_write_user (struct proxyfs_proxy_file_t *proxyfile, const char *buf, size_t count)
<<public>> Write to file from user space buffer
int proxyfs_proxy_file_read_user (struct proxyfs_proxy_file_t *proxyfile, char *buf, size_t count)
<<public>> Read from file to user space buffer
unsigned proxyfs_proxy_file_wait_interruptible (struct proxyfs_proxy_file_t *self, unsigned status)
<<public>> Reads from file to peer - reads from write buffer
long proxyfs_proxy_file_ioctl_user (struct proxyfs_proxy_file_t *self, unsigned int cmd, unsigned long arg)
<<public>> Call ioctl with arg in user space
unsigned int proxyfs_file_poll (struct file *file, struct poll_table_struct *wait)
<<public>> Poll for VFS
int proxyfs_proxy_file_init (struct proxyfs_proxy_file_t *self)
<<public>> Initialize proxyfs_file struct
void proxyfs_proxy_file_destroy (struct proxyfs_proxy_file_t *self)
<<public>> Deinitialize proxyfs_file struct
unsigned proxyfs_proxy_file_wait_for_space_interruptible (struct proxyfs_proxy_file_t *self, unsigned space)
<<public>> Interruptible wait for space in file
int proxyfs_proxy_file_close (struct proxyfs_proxy_file_t *self)
<<public>> Close proxyfile
int proxyfs_proxy_file_fsync (struct proxyfs_proxy_file_t *self)
<<public>> Fsync proxyfile and coresponding real file
Detailed Description
This is used on between VFS and proxyfs_client task.
Macro Definition Documentation
#define PROXYFS_PROXY_FILE (arg) ((struct proxyfs_proxy_file_t *)(arg))
<<public>> Cast to struct proxyfs_proxy_file_t *
Definition at line 84 of file proxyfs_proxy_file.h.
Referenced by proxyfs_client_handle_dead_peer(), proxyfs_client_handle_msg(), proxyfs_client_open_proxy(), proxyfs_proxy_file_read_to_peer(), proxyfs_proxy_file_submit_read_to_peer(), proxyfs_proxy_file_write_buf_info(), and proxyfs_proxy_file_write_from_peer().
Function Documentation
unsigned int proxyfs_file_poll (struct file * file, struct poll_table_struct * wait)
<<public>> Poll for VFS
<<public>> Poll for VFS
Parameters
*self - pointer to this file instance
*wait - pointer to poll table
Returns
- mask of file status
Definition at line 346 of file proxyfs_proxy_file.c.
References PROXYFS_FILE, PROXYFS_FILE_CAN_READ, PROXYFS_FILE_CAN_WRITE, and proxyfs_file_get_status().
 {
     struct proxyfs_proxy_file_t *proxyfile = file->private_data;
     unsigned mask = 0;
     poll_wait(file, &proxyfile->waiting_procs, wait);
     if( proxyfs_file_get_status( PROXYFS_FILE(proxyfile), PROXYFS_FILE_CAN_READ ) )
         mask |= POLLIN | POLLRDNORM;
     if( proxyfs_file_get_status( PROXYFS_FILE(proxyfile), PROXYFS_FILE_CAN_WRITE ) )
             mask |= POLLOUT | POLLWRNORM;
     return mask;
 }
int proxyfs_proxy_file_close (struct proxyfs_proxy_file_t * self)
<<public>> Close proxyfile
Parameters
*self - pointer to this file instance
Returns
zero on succes
Definition at line 268 of file proxyfs_proxy_file.c.
References mdbg, minfo, MSG_CLOSE, MSG_CLOSE_RESP, PEER_CONNECTED, proxyfs_client_do_syscall(), PROXYFS_FILE, PROXYFS_FILE_ALL_WRITTEN, proxyfs_file_get_file_ident(), proxyfs_msg_new(), proxyfs_peer_get_state(), proxyfs_proxy_file_wait_interruptible(), and self.
Referenced by proxyfs_fs_fdinode_release().
 {
     struct proxyfs_msg *msg;
     struct proxyfs_msg *msg_resp;
     long rtn = -ERESTARTSYS;
     u_int32_t exitting = current->flags & PF_EXITING;
     mdbg(INFO2, "Close proxy file requested. Ident: %lu Exitting: %d", proxyfs_file_get_file_ident(PROXYFS_FILE(self)), exitting );
     // We have to wait for a write buffer empty event..
     // TODO: however, if the peer connection is broken, this will never happen, and the close method will block.. what to do? Likely we should wait with some long timeout and then just break (or at least recheck connection)
     if( proxyfs_proxy_file_wait_interruptible(self, PROXYFS_FILE_ALL_WRITTEN ) == 0 ) {
         minfo(ERR2, "Closing of ident: %lu failed. Not all written", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
         return -ERESTARTSYS;
     }
     msg = proxyfs_msg_new(MSG_CLOSE, proxyfs_file_get_file_ident(PROXYFS_FILE(self)), sizeof(exitting), &exitting);
     if(msg != NULL){
         msg_resp = proxyfs_client_do_syscall(self->task, self, msg);
         // What the fck?????
         if( msg_resp == (void*)MSG_CLOSE_RESP )
             rtn = 0;
     }
     if ( rtn != 0 && proxyfs_peer_get_state(PROXYFS_FILE(self)->peer) != PEER_CONNECTED) {
           // Even if our remote syscall has failed, we have to pretend it succeded as the peer is no longer connected and there is no chance of further close success
           rtn = 0;
     }
     mdbg(INFO2, "Close proxy file request DONE, Res: %ld", rtn);
     return rtn;
 }
void proxyfs_proxy_file_destroy (struct proxyfs_proxy_file_t * self)
<<public>> Deinitialize proxyfs_file struct
Parameters
self - pointer to uninitialized proxyfs_proxy_file_t structure
Returns
zero on success
Definition at line 402 of file proxyfs_proxy_file.c.
References PROXYFS_FILE, proxyfs_file_destroy(), and self.
Referenced by proxyfs_fs_fdinode_release().
 {
     wake_up( & self->waiting_procs );
     proxyfs_file_destroy( PROXYFS_FILE(self) );
 }
int proxyfs_proxy_file_fsync (struct proxyfs_proxy_file_t * self)
<<public>> Fsync proxyfile and coresponding real file
Parameters
*self - pointer to this file instance
Returns
zero on succes
Definition at line 308 of file proxyfs_proxy_file.c.
References mdbg, MSG_FSYNC, MSG_FSYNC_RESP, proxyfs_client_do_syscall(), PROXYFS_FILE, PROXYFS_FILE_ALL_WRITTEN, PROXYFS_FILE_CLOSED, proxyfs_file_get_file_ident(), proxyfs_msg_new(), proxyfs_proxy_file_wait_interruptible(), and self.
Referenced by proxyfs_fs_fdinode_fsync().
 {
     struct proxyfs_msg *msg;
     struct proxyfs_msg *msg_resp;
     long rtn = -ERESTARTSYS;
     mdbg(INFO2, "Fsync requested. Ident: %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
     // empty write buf
     switch ( proxyfs_proxy_file_wait_interruptible(self, PROXYFS_FILE_ALL_WRITTEN ) ) {
         case 0:
             mdbg(INFO2, "Cannot fsync, interrupted. Ident: %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
             return -ERESTARTSYS;
         case PROXYFS_FILE_CLOSED:
             mdbg(INFO2, "Cannot fsync, already closed. Ident: %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
             return -EFAULT;
         default:
             mdbg(INFO3, "Fsync all written, may proceed");
         // Otherwise process further
     }
     mdbg(INFO2, "Sending fsync request. Ident: %lu", proxyfs_file_get_file_ident(PROXYFS_FILE(self)));
     msg = proxyfs_msg_new(MSG_FSYNC, proxyfs_file_get_file_ident(PROXYFS_FILE(self)), 0, NULL);
     if(msg != NULL){
         msg_resp = proxyfs_client_do_syscall(self->task, self, msg);
         if( msg_resp == (void*)MSG_FSYNC_RESP )
             rtn = 0;
     }
     return rtn;
 }
int proxyfs_proxy_file_init (struct proxyfs_proxy_file_t * self)
<<public>> Initialize proxyfs_file struct
Parameters
self - pointer to uninitialized proxyfs_proxy_file_t structure
Returns
zero on success
Definition at line 383 of file proxyfs_proxy_file.c.
References PROXYFS_FILE, proxyfs_file_init(), and self.
Referenced by proxyfs_client_open_proxy().
 {
     int rtn;
     if( (rtn = proxyfs_file_init( PROXYFS_FILE(self) )) == 0 ){
         sema_init(& self->write_buf_sem, 1);        // Replaced init_MUTEX macro to sema_init by Jiri Rakosnik
         sema_init(& self->read_buf_sem, 1);
         init_waitqueue_head( & self->waiting_procs );
         PROXYFS_FILE(self)->ops = &proxy_file_ops;
     }
     return rtn;
 }
long proxyfs_proxy_file_ioctl_user (struct proxyfs_proxy_file_t * self, unsigned int cmd, unsigned long arg)
<<public>> Call ioctl with arg in user space
<<public>> Call ioctl with arg in user space
Parameters
*self - pointer to this file instance
cmd - ioctl cmd
arg - ioctl arg
Returns
- return code of ioctl
Definition at line 190 of file proxyfs_proxy_file.c.
References proxyfs_msg_header::data, proxyfs_msg::header, IOCTL_ARG_SIZE, ioctl_get_info(), IOCTL_WILL_READ, IOCTL_WILL_WRITE, mdbg, MSG_IOCTL, proxyfs_client_do_syscall(), PROXYFS_FILE, PROXYFS_FILE_ALL_WRITTEN, PROXYFS_FILE_CLOSED, proxyfs_file_get_file_ident(), proxyfs_msg_new(), proxyfs_proxy_file_wait_interruptible(), and self.
Referenced by proxyfs_fs_fdinode_ioctl().
 {
     unsigned long ioctl_info;
     struct proxyfs_msg *msg;
     struct proxyfs_msg *msg_resp;
     size_t arg_size;
     void *ker_buf = NULL;
     u_int32_t command = cmd;
     long rtn = -ERESTARTSYS;
     ioctl_info = ioctl_get_info(cmd);
     arg_size = IOCTL_ARG_SIZE(ioctl_info);
     // Check access to memory
     if( IOCTL_WILL_READ(ioctl_info) && !access_ok(VERIFY_WRITE, (void*)arg, arg_size) ){
         mdbg(ERR3, "Bad read pointer");
         return -EFAULT;
     }
     else if( IOCTL_WILL_WRITE(ioctl_info) && !access_ok(VERIFY_READ, (void*)arg, arg_size) ){
         mdbg(ERR3, "Bad write pointer");
         return -EFAULT;
     }
     // empty write buf
     switch ( proxyfs_proxy_file_wait_interruptible(self, PROXYFS_FILE_ALL_WRITTEN ) ) {
         case 0:
             return -ERESTARTSYS;
         case PROXYFS_FILE_CLOSED:
             return -EFAULT;
         // Otherwise process further
     }
     if( IOCTL_WILL_WRITE(ioctl_info) ){
         ker_buf = kmalloc( arg_size + sizeof(u_int32_t), GFP_KERNEL );
         if( ker_buf == NULL ){
             mdbg(ERR3, "Allocating memory for message data failed");
             goto exit0;
         }
         *(u_int32_t*)ker_buf = command;
         if( __copy_from_user( ker_buf + sizeof(u_int32_t), (void*)arg, arg_size ) != 0 )
             goto exit1;
         msg = proxyfs_msg_new(MSG_IOCTL, proxyfs_file_get_file_ident(PROXYFS_FILE(self)), sizeof(u_int32_t) + arg_size, ker_buf);
         if(msg == NULL)
             goto exit1;
     }
     else{
         msg = proxyfs_msg_new(MSG_IOCTL, proxyfs_file_get_file_ident(PROXYFS_FILE(self)), sizeof(u_int32_t), &command);
         if(msg == NULL)
             goto exit0;
     }
     msg_resp = proxyfs_client_do_syscall(self->task, self, msg);
     if( msg_resp ){
         rtn = msg_resp->header.data[0];
         if( IOCTL_WILL_READ(ioctl_info) ){
             if( __copy_to_user( (void*)arg, &msg_resp->header.data[1], arg_size ) != 0 )
                 mdbg(ERR3, "Copying result back failed");
         }
         kfree( msg_resp );
     }
     if( IOCTL_WILL_WRITE(ioctl_info) )
         kfree(ker_buf);
     return rtn;
 exit1:
     kfree(ker_buf);
 exit0:
     return -ERESTARTSYS;
 }
int proxyfs_proxy_file_read_user (struct proxyfs_proxy_file_t * self, char * buf, size_t count)
<<public>> Read from file to user space buffer
Parameters
*self - pointer to this file instance
*buf - pointer to buffer in userspace
count - size of data
Returns
the number of bytes read or error (negative number)
Definition at line 65 of file proxyfs_proxy_file.c.
References MSG_WRITE_RESP, proxyfs_client_send_message(), PROXYFS_FILE, proxyfs_file_get_file_ident(), proxyfs_msg_compose_new(), self, and virtual_proxyfs_proxy_file_read_user().
Referenced by proxyfs_fs_fdinode_read().
 {
     struct proxyfs_msg *msg;
     u_int32_t read_count = virtual_proxyfs_proxy_file_read_user(self, buf, count);
     msg = proxyfs_msg_compose_new(MSG_WRITE_RESP, proxyfs_file_get_file_ident(PROXYFS_FILE(self)),
         sizeof(u_int32_t), &read_count, 0 );
     proxyfs_client_send_message( self->task, self, msg );
     return read_count;
 }
unsigned proxyfs_proxy_file_wait_for_space_interruptible (struct proxyfs_proxy_file_t * self, unsigned space)
<<public>> Interruptible wait for space in file
Parameters
*self - pointer to this file instance
space - wanted amount of bytes
Returns
- file status or zero if interrupted by signal
Definition at line 173 of file proxyfs_proxy_file.c.
References circ_buf_free_space(), PROXYFS_FILE, proxyfs_file_get_status(), and self.
Referenced by proxyfs_fs_fdinode_write().
 {
     if( wait_event_interruptible( self->waiting_procs,
             circ_buf_free_space( &PROXYFS_FILE(self)->write_buf ) >= space) == -ERESTARTSYS )
         return 0;
     else{
         return proxyfs_file_get_status( PROXYFS_FILE(self), 0xffffFFFF );
     }
 }
unsigned proxyfs_proxy_file_wait_interruptible (struct proxyfs_proxy_file_t * self, unsigned status)
<<public>> Reads from file to peer - reads from write buffer
<<public>> Reads from file to peer - reads from write buffer
Parameters
*self - pointer to this file instance
status - status on which function returns
Returns
- file status or zero if interrupted by signal
Definition at line 146 of file proxyfs_proxy_file.c.
References mdbg, PEER_CONNECTED, PROXYFS_FILE, PROXYFS_FILE_CLOSED, proxyfs_file_get_status(), proxyfs_peer_get_state(), and self.
Referenced by proxyfs_fs_fdinode_read(), proxyfs_fs_fdinode_write(), proxyfs_proxy_file_close(), proxyfs_proxy_file_fsync(), and proxyfs_proxy_file_ioctl_user().
 {
     unsigned rtn = 0;
 wait:   if ( wait_event_interruptible( self->waiting_procs,
             proxyfs_file_get_status( PROXYFS_FILE(self), status ) ||
             proxyfs_peer_get_state(PROXYFS_FILE(self)->peer) != PEER_CONNECTED) == -ERESTARTSYS)
         return 0;
     else {
         if ( proxyfs_peer_get_state(PROXYFS_FILE(self)->peer) != PEER_CONNECTED ) {
             mdbg(INFO3, "Peer not connected in wait. Peer state: %d\n", proxyfs_peer_get_state(PROXYFS_FILE(self)->peer));
             return PROXYFS_FILE_CLOSED; // TODO: Or rather some BROKEN state?
         }
         rtn = proxyfs_file_get_status( PROXYFS_FILE(self), status );
         mdbg(INFO3, "Waiting on state: %u ... was interrupted in state %u\n", status, proxyfs_file_get_status( PROXYFS_FILE(self), status ));
         if( rtn & status)
             return rtn;
         goto wait;
     }
 }
int proxyfs_proxy_file_write_user (struct proxyfs_proxy_file_t * self, const char * buf, size_t count)
<<public>> Write to file from user space buffer
Parameters
*self - pointer to this file instance
*buf - pointer to data in userspace
count - size of data
Returns
the number of bytes written or error (negative number)
Definition at line 48 of file proxyfs_proxy_file.c.
References VIRTUAL_FUNC.
Referenced by proxyfs_fs_fdinode_write().
 {
     VIRTUAL_FUNC(write_user, buf, count);
 }