Clondike: proxyfs_file class
proxyfs_file class
ProxyFS
This is used on between VFS and proxyfs_client task.
Modules
proxyfs_proxy_file class
This is used on between VFS and proxyfs_client task.
proxyfs_real_file class
This is used on real file and proxyfs_server task.
Data Structures
struct proxyfs_file_identifier
Unique identifier of a file managed by the proxy fs system.
Macros
#define PROXYFS_FILE(arg) ((struct proxyfs_file_t*)(arg))
Cast to struct proxyfs_file_t*.
#define PROXYFS_FILE_OPENED 1
The file is opened and both sides known about it.
#define PROXYFS_FILE_DONT_EXISTS 2
The other side rejected opening file.
#define PROXYFS_FILE_READ_EOF 4
We are at and of file.
#define PROXYFS_FILE_CAN_WRITE 8
There is space in write buffer (read only state)
#define PROXYFS_FILE_CAN_READ 16
There is space in read buffer (read only state)
#define PROXYFS_FILE_ALL_WRITTEN 32
There are no data pending in write buffer (read only state)
#define PROXYFS_FILE_ALL_READ 64
There are no data pending in read buffer (read only state)
#define PROXYFS_FILE_IN_SYSCALL 128
Syscall transaction on file.
#define PROXYFS_FILE_CLOSED 256
The file is opened and both sides known about it.
#define PROXYFS_FILE_EPIPE 512
Reading end on peer is closed (pipe or socket only)
#define PROXYFS_FILE_RO_STATUS
Mask of read only file status.
#define PROXYFS_FILE_RW_STATUS
Mask of read/write file status.
#define PROXYFS_FILE_TTY 1
TTY file type.
#define PROXYFS_FILE_GENERIC 2
Generic file type.
#define PROXYFS_FILE_PIPE 3
Pipe file type.
Functions
struct proxyfs_file_identifier __attribute__ ((__packed__))
unsigned proxyfs_file_get_status (struct proxyfs_file_t *self, unsigned status)
<<public>> Get file status
unsigned long proxyfs_file_get_file_ident (struct proxyfs_file_t *self)
<<public>> Get file identifier
void proxyfs_file_set_file_ident (struct proxyfs_file_t *self, unsigned long encoded_identifier)
<<public>> Set file identifier
struct proxyfs_file_t * proxyfs_file_find_in_list (unsigned long ident, struct list_head *start)
<<public>> Set file status
int proxyfs_file_init (struct proxyfs_file_t *self)
<<public>> Initialize proxyfs_file struct
void proxyfs_file_destroy (struct proxyfs_file_t *self)
<<public>> Deinitialize proxyfs_file struct
int proxyfs_file_write_from_peer (struct proxyfs_file_t *self, const char *buf, size_t count)
<<public>> Writes to file from peer - writes to read buffer
int proxyfs_file_read_to_peer (struct proxyfs_file_t *self, char *buf, size_t count)
<<public>> Reads from file to peer - reads from write buffer
void proxyfs_file_submit_read_to_peer (struct proxyfs_file_t *self, size_t count)
<<public>> Submit that data was written to file on other side
void proxyfs_file_write_buf_info (struct proxyfs_file_t *self, size_t *total_size, size_t *size, void **addr)
<<public>> Get maximum amount and address of data, that can be read at one time
void proxyfs_file_set_peer (struct proxyfs_file_t *self, struct proxyfs_peer_t *peer)
<<public>> Sets peer and aquires its reference.
int proxyfs_file_was_read_requested (struct proxyfs_file_t *self)
<<public>> Checks, whether read was requested for this file
void proxyfs_file_mark_read_requested (struct proxyfs_file_t *self)
<<public>> Marks the file as read requested
void proxyfs_file_unset_status (struct proxyfs_file_t *self, unsigned status)
<<public>> Unset file status
void proxyfs_file_set_status (struct proxyfs_file_t *self, unsigned status)
<<public>> Set file status
Detailed Description
This is used on between VFS and proxyfs_client task.
Data Structure Documentation
struct proxyfs_file_identifier
Unique identifier of a file managed by the proxy fs system.
Definition at line 52 of file proxyfs_file.h.
Data Fields
uint16_t file_ident Semi-unique number identificating file.
It is not unique on its own, but only in combination with pid
uint16_t file_owner_pid Pid of the process on CCN that owned the file before we overtook it into the proxyfs.
Macro Definition Documentation
#define PROXYFS_FILE (arg) ((struct proxyfs_file_t*)(arg))
Cast to struct proxyfs_file_t*.
Definition at line 99 of file proxyfs_file.h.
Referenced by check_syscall_done(), proxyfs_client_do_syscall(), proxyfs_client_open_proxy(), proxyfs_client_send_message(), proxyfs_file_get_status(), proxyfs_file_poll(), proxyfs_fs_fdinode_read(), proxyfs_generic_proxy_file_read_user(), proxyfs_generic_proxy_file_write_user(), proxyfs_generic_real_file_open(), proxyfs_generic_real_file_read(), proxyfs_generic_real_file_write(), proxyfs_pipe_proxy_file_read_user(), proxyfs_pipe_proxy_file_write_user(), proxyfs_pipe_real_file_duplicate(), proxyfs_pipe_real_file_open(), proxyfs_pipe_real_file_read(), proxyfs_pipe_real_file_write(), proxyfs_proxy_file_close(), proxyfs_proxy_file_destroy(), proxyfs_proxy_file_fsync(), proxyfs_proxy_file_init(), proxyfs_proxy_file_ioctl_user(), proxyfs_proxy_file_read_user(), proxyfs_proxy_file_wait_for_space_interruptible(), proxyfs_proxy_file_wait_interruptible(), proxyfs_real_file_close(), proxyfs_real_file_destroy(), proxyfs_real_file_do_ioctl(), proxyfs_real_file_fsync(), proxyfs_real_file_init(), proxyfs_real_file_mark_read_request(), proxyfs_real_file_open(), proxyfs_server_duplicate_overtaken_file(), proxyfs_server_overtake_file(), proxyfs_server_poll_queue_proc(), proxyfs_server_read_and_write_real_files(), proxyfs_tty_real_file_destroy(), proxyfs_tty_real_file_duplicate(), proxyfs_tty_real_file_open(), proxyfs_tty_real_file_read(), and proxyfs_tty_real_file_write().
#define PROXYFS_FILE_ALL_READ 64
There are no data pending in read buffer (read only state)
Definition at line 119 of file proxyfs_file.h.
Referenced by proxyfs_file_get_status(), and proxyfs_server_read_and_write_real_files().
#define PROXYFS_FILE_ALL_WRITTEN 32
There are no data pending in write buffer (read only state)
Definition at line 117 of file proxyfs_file.h.
Referenced by proxyfs_file_get_status(), proxyfs_proxy_file_close(), proxyfs_proxy_file_fsync(), and proxyfs_proxy_file_ioctl_user().
#define PROXYFS_FILE_CAN_READ 16
There is space in read buffer (read only state)
Definition at line 115 of file proxyfs_file.h.
Referenced by proxyfs_file_get_status(), proxyfs_file_poll(), and proxyfs_fs_fdinode_read().
#define PROXYFS_FILE_CAN_WRITE 8
There is space in write buffer (read only state)
Definition at line 113 of file proxyfs_file.h.
Referenced by proxyfs_file_get_status(), proxyfs_file_poll(), and proxyfs_fs_fdinode_write().
#define PROXYFS_FILE_CLOSED 256
The file is opened and both sides known about it.
Definition at line 123 of file proxyfs_file.h.
Referenced by proxyfs_fs_fdinode_write(), proxyfs_proxy_file_fsync(), proxyfs_proxy_file_ioctl_user(), proxyfs_proxy_file_wait_interruptible(), proxyfs_server_handle_msg(), proxyfs_server_read_and_write_real_files(), proxyfs_server_release_all(), and proxyfs_task_release_files().
#define PROXYFS_FILE_DONT_EXISTS 2
The other side rejected opening file.
Definition at line 109 of file proxyfs_file.h.
Referenced by proxyfs_client_handle_msg(), and proxyfs_client_open_proxy().
#define PROXYFS_FILE_EPIPE 512
Reading end on peer is closed (pipe or socket only)
Definition at line 125 of file proxyfs_file.h.
Referenced by proxyfs_fs_fdinode_write().
#define PROXYFS_FILE_GENERIC 2
Generic file type.
Definition at line 137 of file proxyfs_file.h.
Referenced by proxyfs_client_handle_msg(), and proxyfs_generic_real_file_open().
#define PROXYFS_FILE_IN_SYSCALL 128
Syscall transaction on file.
Definition at line 121 of file proxyfs_file.h.
Referenced by check_syscall_done(), proxyfs_client_do_syscall(), and proxyfs_client_handle_msg().
#define PROXYFS_FILE_OPENED 1
The file is opened and both sides known about it.
Definition at line 107 of file proxyfs_file.h.
Referenced by proxyfs_client_handle_msg(), and proxyfs_client_open_proxy().
#define PROXYFS_FILE_PIPE 3
Pipe file type.
Definition at line 139 of file proxyfs_file.h.
Referenced by proxyfs_client_handle_msg(), and proxyfs_pipe_real_file_open().
#define PROXYFS_FILE_READ_EOF 4
We are at and of file.
Definition at line 111 of file proxyfs_file.h.
Referenced by proxyfs_fs_fdinode_read(), proxyfs_proxy_file_write_from_peer(), and proxyfs_server_read_and_write_real_files().
#define PROXYFS_FILE_RO_STATUS
Value:
(PROXYFS_FILE_CAN_WRITE | PROXYFS_FILE_CAN_READ | PROXYFS_FILE_ALL_WRITTEN | \
                 PROXYFS_FILE_ALL_READ )
Mask of read only file status.
Definition at line 128 of file proxyfs_file.h.
Referenced by proxyfs_file_get_status().
#define PROXYFS_FILE_RW_STATUS
Value:
(PROXYFS_FILE_OPENED | PROXYFS_FILE_DONT_EXISTS | PROXYFS_FILE_READ_EOF | \
                 PROXYFS_FILE_CLOSED | PROXYFS_FILE_EPIPE       | PROXYFS_FILE_IN_SYSCALL )
Mask of read/write file status.
Definition at line 131 of file proxyfs_file.h.
Referenced by proxyfs_file_get_status().
#define PROXYFS_FILE_TTY 1
TTY file type.
Definition at line 135 of file proxyfs_file.h.
Referenced by proxyfs_client_handle_msg(), and proxyfs_tty_real_file_open().
Function Documentation
struct proxyfs_file_identifier __attribute__ ((__packed__))
void proxyfs_file_destroy (struct proxyfs_file_t * self)
<<public>> Deinitialize proxyfs_file struct
Parameters
self - pointer to this file instance
Definition at line 162 of file proxyfs_file.c.
References circ_buf_destroy(), proxyfs_peer_put(), and self.
Referenced by proxyfs_client_open_proxy(), proxyfs_proxy_file_destroy(), and proxyfs_real_file_destroy().
 {
     circ_buf_destroy( & self->write_buf );
     circ_buf_destroy( & self->read_buf );
     proxyfs_peer_put(self->peer);
 }
struct proxyfs_file_t* proxyfs_file_find_in_list (unsigned long ident, struct list_head * start) read
<<public>> Set file status
Parameters
ident - Unique file identification number
start - List in which we are searching
Returns
pointer to proxyfs_file or NULL
Definition at line 118 of file proxyfs_file.c.
References proxyfs_file_get_file_ident().
Referenced by get_proxy_file_by_id(), and proxyfs_client_handle_msg().
 {
     struct proxyfs_file_t *file = NULL;
     struct list_head *l;
     list_for_each( l, start ){
         file = list_entry(l, struct proxyfs_file_t, files);
         if( proxyfs_file_get_file_ident(file) == ident )
             return file;
     }
     return NULL;
 }
unsigned long proxyfs_file_get_file_ident (struct proxyfs_file_t * self)
<<public>> Get file identifier
Definition at line 76 of file proxyfs_file.c.
References self.
Referenced by check_syscall_done(), proxyfs_client_handle_dead_peer(), proxyfs_client_open_files(), proxyfs_file_find_in_list(), proxyfs_file_get_status(), proxyfs_generic_real_file_open(), proxyfs_generic_real_file_read(), proxyfs_generic_real_file_write(), proxyfs_pipe_proxy_file_read_user(), proxyfs_pipe_proxy_file_write_user(), proxyfs_pipe_real_file_duplicate(), proxyfs_pipe_real_file_open(), proxyfs_pipe_real_file_read(), proxyfs_pipe_real_file_write(), proxyfs_proxy_file_close(), proxyfs_proxy_file_fsync(), proxyfs_proxy_file_ioctl_user(), proxyfs_proxy_file_read_user(), proxyfs_proxy_file_write_from_peer(), proxyfs_real_file_close(), proxyfs_real_file_destroy(), proxyfs_real_file_do_ioctl(), proxyfs_real_file_fsync(), proxyfs_real_file_mark_read_request(), proxyfs_server_duplicate_all_parent(), proxyfs_server_duplicate_overtaken_file(), proxyfs_server_handle_msg(), proxyfs_server_poll_queue_proc(), proxyfs_server_read_and_write_real_files(), proxyfs_server_release_all(), proxyfs_task_find_file(), proxyfs_task_handle_msg(), proxyfs_task_release_files(), proxyfs_task_send_write_buf(), proxyfs_tty_real_file_destroy(), proxyfs_tty_real_file_duplicate(), proxyfs_tty_real_file_open(), proxyfs_tty_real_file_read(), and proxyfs_tty_real_file_write().
{
     unsigned long res = ((uint32_t)self->file_identifier.file_owner_pid << 16) + self->file_identifier.file_ident;
     return res;
 }
unsigned proxyfs_file_get_status (struct proxyfs_file_t * self, unsigned status)
<<public>> Get file status
Parameters
self - pointer to this file instance
status - status we asking for
Returns
true if status is set for file
Definition at line 46 of file proxyfs_file.c.
References circ_buf_count(), circ_buf_get_read_size(), circ_buf_get_write_size(), mdbg, PROXYFS_FILE, PROXYFS_FILE_ALL_READ, PROXYFS_FILE_ALL_WRITTEN, PROXYFS_FILE_CAN_READ, PROXYFS_FILE_CAN_WRITE, proxyfs_file_get_file_ident(), PROXYFS_FILE_RO_STATUS, PROXYFS_FILE_RW_STATUS, and self.
Referenced by check_syscall_done(), proxyfs_client_open_proxy(), proxyfs_file_poll(), proxyfs_fs_fdinode_read(), proxyfs_proxy_file_wait_for_space_interruptible(), proxyfs_proxy_file_wait_interruptible(), proxyfs_server_read_and_write_real_files(), and proxyfs_task_release_files().
 {
     unsigned rtn = 0;
     if( status & PROXYFS_FILE_RO_STATUS ){
         if( status & PROXYFS_FILE_CAN_WRITE ){
             if( circ_buf_get_write_size( & self->write_buf ) )
                 rtn |= PROXYFS_FILE_CAN_WRITE;
         }
         if( status & PROXYFS_FILE_CAN_READ ){
             if( circ_buf_count( & self->read_buf ) )
                 rtn |= PROXYFS_FILE_CAN_READ;
         }
         if( status & PROXYFS_FILE_ALL_WRITTEN ){
             mdbg(INFO3, "file_get_status[%lu] all_written.. %d",proxyfs_file_get_file_ident(PROXYFS_FILE(self)),circ_buf_get_read_size(&self->write_buf));
             if( circ_buf_get_read_size( & self->write_buf ) == 0 )
                 rtn |= PROXYFS_FILE_ALL_WRITTEN;
         }
         if( status & PROXYFS_FILE_ALL_READ ){
             mdbg(INFO3, "file_get_status[%lu] all_read.. %d",proxyfs_file_get_file_ident(PROXYFS_FILE(self)),circ_buf_get_read_size( & self->read_buf ));
             if( circ_buf_get_read_size( & self->read_buf ) == 0 )
                 rtn |= PROXYFS_FILE_ALL_READ;
         }
     }
     if( status & PROXYFS_FILE_RW_STATUS ){
         rtn |= self->state & (status & PROXYFS_FILE_RW_STATUS);
     }
     return rtn;
 }
int proxyfs_file_init (struct proxyfs_file_t * self)
<<public>> Initialize proxyfs_file struct
Parameters
self - pointer to this file instance
Returns
zero on success
Definition at line 136 of file proxyfs_file.c.
References circ_buf_destroy(), circ_buf_init(), mdbg, READ_BUF_SIZE, self, and WRITE_BUF_SIZE.
Referenced by proxyfs_proxy_file_init(), and proxyfs_real_file_init().
 {
     if( circ_buf_init( & self->write_buf, WRITE_BUF_SIZE ) != 0 ){
         mdbg(ERR3, "Allocating write buffer for proxy_file failed");
         goto exit0;
     }
     if( circ_buf_init( & self->read_buf, READ_BUF_SIZE ) != 0 ){
         mdbg(ERR3, "Allocating read buffer for proxy_file failed");
         goto exit1;
     }
     self->state = 0;
     self->write_buf_unconfirmed = 0;
     self->read_was_requested = 0;
     self->peer = NULL;
     return 0;
 exit1:
     circ_buf_destroy( & self->write_buf );
 exit0:
     return -1;
 }
void proxyfs_file_mark_read_requested (struct proxyfs_file_t * self)
<<public>> Marks the file as read requested
Definition at line 208 of file proxyfs_file.c.
Referenced by proxyfs_pipe_proxy_file_read_user(), and proxyfs_real_file_mark_read_request().
{
     self->read_was_requested = 1;
 }
int proxyfs_file_read_to_peer (struct proxyfs_file_t * self, char * buf, size_t count)
<<public>> Reads from file to peer - reads from write buffer
Definition at line 176 of file proxyfs_file.c.
References VIRTUAL_FUNC.
Referenced by proxyfs_task_send_write_buf().
 {
     VIRTUAL_FUNC(read_to_peer, buf, count);
 }
void proxyfs_file_set_file_ident (struct proxyfs_file_t * self, unsigned long encoded_identifier)
<<public>> Set file identifier
Parameters
self - File instance pointer
encuded_identifier - File identifier encoded via get_file_ident method
Definition at line 85 of file proxyfs_file.c.
References mdbg, and self.
Referenced by proxyfs_client_open_proxy().
{
     self->file_identifier.file_ident = 0xffff & encoded_identifier;
     self->file_identifier.file_owner_pid = (encoded_identifier - self->file_identifier.file_ident) >> 16;
     mdbg(INFO3, "Set identifier: %d Pid: %d (encoded: %lu)", (int)self->file_identifier.file_ident, (int)self->file_identifier.file_owner_pid, encoded_identifier);
 }
void proxyfs_file_set_peer (struct proxyfs_file_t * self, struct proxyfs_peer_t * peer)
<<public>> Sets peer and aquires its reference.
If there was some other peer set before, releases its reference
Definition at line 194 of file proxyfs_file.c.
References mdbg, proxyfs_peer_get(), proxyfs_peer_put(), and self.
Referenced by proxyfs_client_handle_msg(), proxyfs_generic_real_file_open(), proxyfs_real_file_close(), and proxyfs_real_file_open().
{
     if ( self->peer )
         mdbg(INFO3, "Switching from peer %p to peer %p", self->peer, peer);
     proxyfs_peer_get(peer); // Aquire ref of a new peer
     proxyfs_peer_put(self->peer); // Release current peer
     self->peer = peer;
 }
void proxyfs_file_set_status (struct proxyfs_file_t * self, unsigned status)
<<public>> Set file status
Parameters
self - pointer to this file instance
status - staus we asking for
Definition at line 97 of file proxyfs_file.c.
Referenced by proxyfs_client_do_syscall(), proxyfs_client_handle_msg(), proxyfs_proxy_file_write_from_peer(), proxyfs_server_handle_msg(), proxyfs_server_read_and_write_real_files(), and proxyfs_server_release_all().
 {
     self->state |= status;
 }
void proxyfs_file_submit_read_to_peer (struct proxyfs_file_t * self, size_t count)
<<public>> Submit that data was written to file on other side
Definition at line 182 of file proxyfs_file.c.
References VIRTUAL_FUNC_VOID.
Referenced by proxyfs_task_handle_msg().
 {
     VIRTUAL_FUNC_VOID(submit_read_to_peer, count);
 }
void proxyfs_file_unset_status (struct proxyfs_file_t * self, unsigned status)
<<public>> Unset file status
<<public>> Unset file status
Parameters
self - pointer to this file instance
status - staus we asking for
Definition at line 107 of file proxyfs_file.c.
Referenced by proxyfs_client_handle_msg().
 {
     self->state &= ~status;
 }
int proxyfs_file_was_read_requested (struct proxyfs_file_t * self)
<<public>> Checks, whether read was requested for this file
Definition at line 203 of file proxyfs_file.c.
Referenced by proxyfs_pipe_proxy_file_read_user(), and proxyfs_pipe_real_file_read().
{
     return self->read_was_requested;
 }
void proxyfs_file_write_buf_info (struct proxyfs_file_t * self, size_t * total_size, size_t * size, void ** addr)
<<public>> Get maximum amount and address of data, that can be read at one time
Definition at line 188 of file proxyfs_file.c.
References VIRTUAL_FUNC_VOID.
Referenced by proxyfs_task_send_write_buf().
 {
     VIRTUAL_FUNC_VOID(write_buf_info, total_size, size, addr);
 }
int proxyfs_file_write_from_peer (struct proxyfs_file_t * self, const char * buf, size_t count)
<<public>> Writes to file from peer - writes to read buffer
Definition at line 170 of file proxyfs_file.c.
References VIRTUAL_FUNC.
Referenced by proxyfs_task_handle_msg().
 {
     VIRTUAL_FUNC(write_from_peer, buf, count);
 }